### ISSUE TITLE
HiveLock is chosen according to new table metadata

### ISSUE THREAD

**Issue by lirui-apache** [apache/iceberg#10006]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

When `HiveTableOperations` commits, which kind of `HiveLock` to use is decided using the new table metadata: https://github.com/apache/iceberg/blob/main/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L180

Suppose a table was initially created with lock enabled. At some time, we decide to disable the lock by running an ALTER TABLE to change the property. I wonder if this ALTER TABLE can cause problem with other concurrent writes, because they will use different lock mechanism.

**Comment by nastra** [comment]
@lirui-apache this seems more like a question than a bug?

**Comment by lirui-apache** [comment]
@nastra I'm trying to work out a test case to verify if the issue is valid. Until then, yes I think it's more like a question.

**Comment by szehon-ho** [comment]
Yes this is possible, I think we tried to document the limitations of this flag here:  https://iceberg.apache.org/docs/latest/configuration/#hadoop-configuration  fyi @pvary

**Comment by pvary** [comment]
@lirui-apache: If all af the writers has the new code, then it should be fine. The `ALTER TABLE` will have a lock, so no concurrent readers should have a lock. When the alter commit finished, then every subsequent reader will get the new property and continue in lockless mode.

**Comment by lirui-apache** [comment]
@szehon-ho  @pvary I'm using this test case to demonstrate the issue:
```java
    final int parallel = 2;
    ThreadPoolExecutor pool = (ThreadPoolExecutor) Executors.newFixedThreadPool(
            parallel,
            new ThreadFactoryBuilder().setDaemon(true).setNameFormat("committer-%d").build());
    pool.prestartAllCoreThreads();
    try {
      List<Future<Void>> futures = Lists.newArrayListWithCapacity(parallel);
      futures.add(pool.submit(() -> {
        Table table = catalog.loadTable(tableId);
        table.updateProperties().set(HIVE_LOCK_ENABLED, "false").commit();
        return null;
      }));
      futures.add(pool.submit(() -> {
        Table table = catalog.loadTable(tableId);
        table.updateProperties().set(GC_ENABLED, "false").commit();
        return null;
      }));
      for(Future<Void> future : futures) {
        future.get();
      }
      Table table = catalog.loadTable(tableId);
      assertEquals("false", table.properties().get(HIVE_LOCK_ENABLED));
      assertEquals("false", table.properties().get(GC_ENABLED));
    }
```
There's a chance the test fails because HIVE_LOCK_ENABLED was not set. BTW the test connects to a local standalone HMS that has the required changes in Hive.

Let's call the threads setting HIVE_LOCK_ENABLED and GC_ENABLED `thread-1` and `thread-2` respectively. I think the issue happens like this:

1. `thread-1` decides to use NoLock because its new table properties have `(HIVE_LOCK_ENABLED, "false")`
2. `thread-2` decides to use MetastoreLock
3. `thread-2` acquires the HMS lock and verifies the metadata location has not been changed
4. `thread-1` made the commit via the no-lock path
5. `thread-2` made the commit, and the change made by `thread-1` is lost

So my question is should we use the old table metadata (i.e. the `base`) to decide which lock to use? So that both threads will use MetastoreLock in the above example. Or do you think this use case is a known limitation and should be avoided in the first place?

**Comment by pvary** [comment]
@lirui-apache: You are right. I thought that we use the old locking mechanism. We need a secure migration path if it is possible to access the old metadata. Also make sure that we handle the table creation case where the previous metadata is missing. I think it is fine, since the second table creation would fail anyway.
