### ISSUE TITLE
OpenApi requestBody: some are optional but should be required

### ISSUE THREAD

**Issue by westse** [apache/iceberg#10004]
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

`requestBody` is [optional by default](https://swagger.io/docs/specification/describing-request-body) and needs `required: true` to override that. It seems the following should be required but are currently optional.
1. [createNamespace](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L250). How else to know the namespace to create?
1. [updateProperties](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L398). How else to know what properties to update?
1. [createTable](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L501). How else to know the table to create?
1. [updateTable](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L682). How else to know what to commit?
1. [registerTable](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L553). How else to know the table to register?
1. [createView](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L1113). How else to know the view to create?
1. [replaceView](https://github.com/apache/iceberg/blob/f425dc7401b268f92778c3c9b2c6abfc7fb661df/open-api/rest-catalog-open-api.yaml#L1211). How else to know what to commit?

Tools that generate code from the spec dutifully make these optional, forcing a developer to handle this confusing and unnecessary case. Can these be marked as required?

**Comment by nastra** [comment]
@westse can you please open a PR with a fix?

**Comment by jbonofre** [comment]
I agree it should be `required: true` on these fields.

**Comment by jbonofre** [comment]
Happy to work on this (I guess the validator might fail) if needed.

**Comment by westse** [comment]
@nastra Is the openapi generated? If so, can you point me to the relevant code? If not, the change is trivial and I can certainly create a PR.

**Comment by westse** [comment]
@nastra , done. See #10125
