### ISSUE TITLE
An error occurred when the iceberg parquet file was loaded in the hive external table

### ISSUE THREAD

**Issue by lpy148145** [apache/iceberg#10005]
### Apache Iceberg version

1.2.1

### Query engine

Hive

### Please describe the bug 🐞

Caused by: java.io.IOException: java.lang.RuntimeException: hdfs://xxxxx.parquet is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [8, 0, 0, 0]

**Comment by RussellSpitzer** [comment]
This needs more details for investigation but is unlikely to be a bug. Iceberg parquet files are just normal parquet files. If the tail is broken in hive, the tail would be broken everywhere. More likely this is just an uncommitted file from a broken writer that wasn't cleaned up

**Comment by lpy148145** [comment]
Yes, I re-imported the partition data into a new table, and hive re-loaded the partition to query it, which was strange

**Comment by lpy148145** [comment]
I used spark to write the iceberg table task without an error, but one of the parquet files failed to be read。
I'm using python to read the file and an exception occurs。
“”“Could not open Parquet input source '/Users/mlamp/error_file.parquet': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.”“”
