### ISSUE TITLE
many doc lost in iceberg official website

### ISSUE THREAD

**Issue by tcguanshuhuai** [apache/iceberg#10018]
For example:
https://iceberg.apache.org/docs/latest/spark-configuration.md#sql-extensions 404

**Comment by nastra** [comment]
Thanks for reporting @tcguanshuhuai, I believe @bitsondatadev wanted to go over the docs and fix such things. @tcguanshuhuai any help is greatly appreciated in case you'd like to contribute and improve the docs

**Comment by bitsondatadev** [comment]
These issues came up initially from cached google entries not being updated immediately after the site change. I forgot to comment here after discussing this directly with @nastra, but this should be resolved after some months of Google scraping.
