### ISSUE TITLE
zorder fails with null binary values

### ISSUE THREAD

**Issue by cccs-jc** [apache/iceberg#10022]
### Apache Iceberg version

1.4.2

### Query engine

Spark

### Please describe the bug 🐞

I have a table of IP flow data. The src_ipv4 and dst_ipv4 columns are of type long.
I can zorder sort this table like so:
```sql
CALL users.system.rewrite_data_files(
        table => 'users.jcc.flow',
        options => map('max-concurrent-file-group-rewrites', '20',
                       'partial-progress.enabled', 'true',
                       'rewrite-all', 'true'),
        strategy => 'sort',
        sort_order => 'zorder(src_ipv4, dst_ipv4)'
        )
```
However, IP can be IPv6, so the table also has a src_ipv6 and dst_ipv6 column of type BINARY. When the src IP is a v4, then src_ipv6 is null. When the src IP is a v6, then src_ipv4 is null. zordering with null v4 works just fine. But not with the v6.

Thus the schema of the table is `src_ipv4 bigint, src_ipv6 binary, dst_ipv4 bigint, dst_ipv6 binary`

Running this statement fails. This is the same statement as above with an added zorder(src_ipv6, dst_ipv6).

```sql
CALL users.system.rewrite_data_files(
        table => 'users.jcc.flow',
        options => map('max-concurrent-file-group-rewrites', '20',
                       'partial-progress.enabled', 'true',
                       'rewrite-all', 'true'),
        strategy => 'sort',
        sort_order => 'zorder(src_ipv4, dst_ipv4), zorder(src_ipv6, dst_ipv6)'
        )
```
When I run that statement I get the following error.

```
[FAILED_EXECUTE_UDF] Failed to execute user defined function (`BYTE-TRUNCATE (functions$$$Lambda$1091/0x00007f88b08cccc8)`: (binary) => binary).    
Caused by: java.lang.NullPointerException: Cannot read the array length because "val" is null
        at org.apache.iceberg.util.ZOrderByteUtils.byteTruncateOrFill(ZOrderByteUtils.java:148)
        at org.apache.iceberg.spark.actions.SparkZOrderUDF.lambda$bytesTruncateUDF$f2cd8334$1(SparkZOrderUDF.java:269)
```

Seems like there is a check missing for null BINARY values.

**Comment by amogh-jahagirdar** [comment]
Yeah I think you're right, just looks like a missing null check. If the byte array is null I think we should just return an empty byte buffer. I'll put up a PR

**Comment by cccs-jc** [comment]
thank you!
