### ISSUE TITLE
Ci: Throttling causes flakyness in link checker

### ISSUE THREAD

**Issue by CsengerG** [apache/iceberg#10038]
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

When you open a new Iceberg PR, the link checker CI step sometimes errors out because of HTTP 429 (Slow down) errors. This was seen in a [recent PR](https://github.com/apache/iceberg/pull/9963), so opening this issue to track.

**Comment by manuzhang** [comment]
I'm also seeing 503 error in https://github.com/apache/iceberg/actions/runs/8423700634/job/23065932581?pr=10037

```
[✖] https://medium.com/@ayushtkn/apache-hive-4-x-with-iceberg-branches-tags-3d52293ac0bf/ → Status: 503
```

**Comment by manuzhang** [comment]
429 error can be mitigated with config `"retryOn429": true` as per https://github.com/tcort/markdown-link-check?tab=readme-ov-file#config-file-format while there are on such options for other status codes like 503.

**Comment by nk1506** [comment]
With my patch https://github.com/apache/iceberg/actions/runs/8441938550/job/23122220366?pr=9852 
Those errors are related to medium , 
```
ERROR: 10 dead links found!
[✖] https://medium.com/@ajanthabhat/how-not-to-use-apache-iceberg-046ae7e7c884 → Status: 429
[✖] https://medium.com/@ayushtkn/apache-hive-4-x-with-iceberg-branches-tags-3d52293ac0bf/ → Status: 429
```
