### ISSUE TITLE
[Potential Bug] insertedRowMap too large could cause flink application failure?

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#10030]
### Apache Iceberg version

main (development)

### Query engine

Flink

### Please describe the bug 🐞

https://github.com/apache/iceberg/blob/5d58750841d3a35a352fcf99d315f10626399e71/core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java#L113
When Flink using BaseEqualityDeltaWriter, wouldn't flink application crash if too many data in the `insertedRowMap` ?

**Comment by pvary** [comment]
You would like to compact the table to get rid of the delete files. RewriteDataFilesAction could help, or Spark compaction

**Comment by puchengy** [comment]
But it does not avoid the map getting too large and fail the application
right?

**Comment by pvary** [comment]
Oh... sry, this is the writer side. My suggestion helps on reader side only.

On writer side you can increase your checkpointing period, migrate to a smaller primary key (introduce a new long id), or increase your task memory.

I have seen suggestions to add a new feature to store these deletes in RocksDB or state, but I think there were no decisions around it yet.

**Comment by manuzhang** [comment]
AFAIK, there are #2680 and [RFC: Control flink upsert sink’s memory usage of insertedRowMap](https://toys-flash-4hl.craft.me/3VHrdWbV30QMk6)

**Comment by puchengy** [comment]
Thanks
