### ISSUE TITLE
sparksql can not create table(base on examples)

### ISSUE THREAD

**Issue by kaidata** [apache/iceberg#1005]
version infos:
spark, 2.4.5
iceberg, 0.7

demo code:
``` scala
import org.apache.iceberg.catalog.TableIdentifier
import org.apache.iceberg.hive.HiveCatalog
import org.apache.iceberg.types.Types.{IntegerType, NestedField}
import org.apache.spark.sql.{SaveMode, SparkSession}

object IcebergDemo {
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder().appName(this.getClass.getName).master("local")
//      .enableHiveSupport()
      .getOrCreate()

    val catalog = new HiveCatalog(spark.sessionState.newHadoopConf())

    import spark.implicits._
    val df = (0 to 100000).toDF("id")

    val name = TableIdentifier.of("default", "iceberg")

    val schema = new Schema(
      NestedField.required(1, "level", IntegerType.get())
    )

    val table = catalog.createTable(name, schema)

    // write into the new logs table with Spark 2.4
    df.write.format("iceberg").mode(SaveMode.Overwrite).save("default.iceberg")

    spark.stop()
  }
}
```

error infos:
```log
Exception in thread "main" java.lang.RuntimeException: Failed to acquire locks from metastore because 'HIVE_LOCKS' doesn't exist, this probably happened when using embedded metastore or doesn't create a transactional meta table. To fix this, use an alternative metastore
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:181)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:102)
	at org.apache.iceberg.BaseMetastoreCatalog.createTable(BaseMetastoreCatalog.java:67)
	at org.apache.iceberg.hive.HiveCatalog.createTable(HiveCatalog.java:60)
	at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:98)
```

**Comment by waterlx** [comment]
@kaidata Seems something wrong here 8-)
```
val catalog = new HiveCatalog(spark.sessionState.newHadoopConf())
```

You might need to provide "hive.metastore.uris" into conf when `new HiveCatalog`

**Comment by kaidata** [comment]
@waterlx ths your reply;
1. my scenario(environment) is just on spark(spark-sql), no hive metastore service;
2. can your introduce some reference files to me that i can read or write iceberg table(all flow), so i can analysis(or debug the deep logical) the metadata and data of iceberg

**Comment by waterlx** [comment]
@kaidata 
Regarding:
> my scenario(environment) is just on spark(spark-sql), no hive metastore service;

Got that. But the code you are using is to new a Hive catalog. Hive Catalog is backed by a Hive MetaStore. You can download Hive 2.3.6 package and launch a local Hive MetaStore (using embedded mode).
Or you can use HadoopTables to create the table. You only need to specify a path on file sytem. No extra service (like Hive MetaStore) is needed. 

Regarding:
> can your introduce some reference files to me that i can read or write iceberg table(all flow), so i can analysis(or debug the deep logical) the metadata and data of iceberg

The following 2 pages are good ones to start with:
(1) http://iceberg.apache.org/java-api-quickstart/
(2) http://iceberg.apache.org/spark/
We also have some posts in Chinese, if you can read Chinese and prefer to reading it, please drop me a mail at waterlx@gmail.com.
Regarding debug, Spark read/write with remote debug on IDE could be used to know internal logic.

**Comment by kaidata** [comment]
@waterlx 
thx your replay, 
1. hadoop table, i have done; but when dataframe append save to location(table)，metadata is right，data have no change(no new parquet generate)
2. hive table, use hive metastore service, i am doing now;

```
Regarding debug, Spark read/write with remote debug on IDE could be used to know internal logic.
```
yes, this is a good way(remote debug, when i write plugin of DataX); but i always debug in local ide environment As much as possible (just config hadoop_home(ddl) or change some line in NativeIO)【sometimes you should to overwrite opensource logical in temporary】【this is more convenient】

on the other hand，i am researching the data lake tech at recent(the document is [here](https://www.yuque.com/docs/share/8752f4b6-81aa-4feb-8929-a424b642f4bd?#));

**Comment by waterlx** [comment]
@kaidata  I used remote debug to debug local Spark and Iceberg too. Not sure if it could work for you.

**Comment by Fokko** [comment]
Thanks for raising this. Closing this since Spark 2.4 has been deprecated a while ago.
