### ISSUE TITLE
In case of Positional Deletes "file_path" in lowerbound & upperbound do not have full file_path Buffer

### ISSUE THREAD

**Issue by agrawalreetika** [apache/iceberg#10064]
### Apache Iceberg version

None

### Query engine

PrestoDB

### Please describe the bug 🐞

I am trying to introduce Delete File pruning based on the file_path stored as part of lowerbound & upperbound in case of Positional Delete File for PrestoDB Engine.
While experimenting with this, I observed "file_path" in lowerbound & upperbound do not have full path Buffer.

![image](https://github.com/apache/iceberg/assets/7887476/5ab8ddd9-1b13-4662-aac2-1fbd2f50d994)

Refernce - https://github.com/prestodb/presto/blob/master/presto-iceberg/src/main/java/com/facebook/presto/iceberg/delete/DeleteFile.java#L48

While the actual file path looks like this -
![image](https://github.com/apache/iceberg/assets/7887476/91419057-3029-4dbf-91f1-3d69220ffbd4)

**Comment by yingsu00** [comment]
@agrawalreetika Is this an Iceberg lib issue?

**Comment by singhpk234** [comment]
which iceberg version ? 

seems like the file_path metrics were truncated : 

> This is because these metrics were truncated, Iceberg's default metrics mode for column metric is truncate(16). 

This should be fixed by https://github.com/apache/iceberg/pull/6313.

more on this via : https://github.com/apache/iceberg/issues/6694

**Comment by agrawalreetika** [comment]
Thank you for your response @singhpk234 
So we are using iceberg version 1.4.3 in Presto.
And I checked https://github.com/apache/iceberg/pull/6313 looks like it's fixed for Flink, so it wouldn't work for others?

**Comment by singhpk234** [comment]
are you using presto as a writer as well ? if you check it's still 16 characters so the writer which is generating the delete files is generating wrong metrics i.e still using truncate(16).

**Comment by singhpk234** [comment]
seems like we always get default config setting in presto 

https://github.com/prestodb/presto/blob/c5674d6e7c1008eb7935542a836f8f90d6bf09c6/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergParquetFileWriter.java#L74C1-L74C194

even for deletes we need to have special handling here i think :), if i am not mistaken it would be interesting to see if it causes regression for already released version of presto which are being used as a writer it would just end up reading more data i guess , not sure though

**Comment by agrawalreetika** [comment]
Thanks for your input @singhpk234 I will explore around the write from Presto side to see where truncate is happening as part of write.
