### ISSUE TITLE
Flink inserts creates duplicates per primary key

### ISSUE THREAD

**Issue by kinggarden1983** [apache/iceberg#10076]
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

1. define a table like this
CREATE TABLE `iceberg`.`marlin`.`users_base_mor_without_upsert` (
  `id` BIGINT NOT NULL,
  `body` VARCHAR(2147483647),
  `created_at` VARCHAR(2147483647)
  PRIMARY KEY (`id`) NOT ENFORCED
) 
WITH (
  'write.merge.mode' = 'merge-on-read',
  'format-version' = '2',
  'write.delete.mode' = 'merge-on-read',
  'write.update.mode' = 'merge-on-read'
);

2. using flink to write into this table

`FlinkSink.forRow(
                        rawSinkTableFlinkRows,
                        JobGraphUtils.createFlinkSchemaForRowWithPK(cdcEventClass, "cdcEventRawSinkTableSchema"))
                .tableLoader(sinkTableLoaders.get(JobGraphUtils.TableType.RAW))
                .append();`

3.  flink generates snapshots like 

{"added-data-files": "16", "added-position-deletes": "2520", "total-equality-deletes": "0", "added-records": "7503"...}

4. I expect we should have uniqued rows per id column but it's not true.

**Comment by manuzhang** [comment]
I don't see where you have configured `write.upsert.enabled=true` which is required for Flink upsert.

**Comment by amogh-jahagirdar** [comment]
Yeah +1 to what @manuzhang said. You're expecting UPSERT behavior but it seems like you don't have that configured. See https://iceberg.apache.org/docs/nightly/flink-writes/#upsert for more details.

 I'm going to close this for now, but please feel free to reopen if you have any remianing questions.
