### ISSUE TITLE
Add capability to support an external index for additional file filtering

### ISSUE THREAD

**Issue by asuresh8** [apache/iceberg#10083]
### Feature Request / Improvement

Iceberg supports skip indexes natively, but these skip indexes are limited in scope. Users should be able to create additional indices that can be applied at query time. For example, in https://github.com/opensearch-project/opensearch-spark skip indices with VALUE_SET are supported. Iceberg should provide a way to allow the user to provide additional file filtering logic when generating the query plan to take advantage of external skip indices.

### Query engine

Spark

**Comment by piyushsingariya** [comment]
How come this hasn't garnered attention yet.
