### ISSUE TITLE
official site none offer get start and in action document

### ISSUE THREAD

**Issue by kaidata** [apache/iceberg#1009]
1. [official site](https://iceberg.apache.org/) can not use
2. no get start or in action document offer

**Comment by waterlx** [comment]
Hi @kaidata, thanks for bringing those issues to the community ^_^

The  offical website could be accessed. I met only a few times when the website could not be accessed or responded slowly. Please try to refresh it and that always works.

We do have "get started" pages, like:
(1) http://iceberg.apache.org/java-api-quickstart/
(2) http://iceberg.apache.org/spark/
I know they are not perfect and need to be refined to some extend, so please raise detailed issues on which are not clear or not easy to understand, and we could make it better and more convenient to new comers (I am also a new comer here)

**Comment by kaidata** [comment]
@waterlx 
i very sorry about this；
i hava test on my own laptop, it is normal;
it should be problem of my company network;

**Comment by kaidata** [comment]
about get started(or code examples), i think it should declare the pre condition, eg:
(i think the perfect opensource tech for develop is spark(examples(project model code))) and hbase(reference guide)
1. maven dependency(version)
2. it can run(debug)
3. out dependency(hive metastore(version?))
4. it can and not()
5. architect
6. roadmap
