### ISSUE TITLE
Implement `Closable` interface for class `HiveCatalog` and `HiveClientPool`

### ISSUE THREAD

**Issue by yuqi1129** [apache/iceberg#10100]
### Feature Request / Improvement

Resources like Hive connection pool should be closed when instances of `HiveCatalog` and `HiveClientPool` are no longer used, so I suggest that we can make these two classes implement the `Closable` interface and do some cleaning jobs in the `close` method.

### Query engine

None

**Comment by pvary** [comment]
This comes up from time-to-time.
Like: https://github.com/apache/iceberg/issues/1502#issuecomment-698635234

The original intention was to keep the HMS client pool open between catalog creations, since opening the connection has a significant overhead, and a typical user uses only a single pool.

What is your use case which needs this behavior change?

Thanks, Peter

**Comment by yuqi1129** [comment]
@pvary 
Thank you for your kind reply. 

The reason we need to close the `HiveCatalog` and `HiveClientPool` is that we are working on a metadata management system https://github.com/datastrato/gravitino and Gravitino will manage several catalogs. Each Iceberg catalog will have the following operations:

1. Create an Iceberg catalog. In this step, Gravitino will use a `IsolatedClassloader` to load classes that belongs to Icebergs catalog
2. `LoadTable`, `LoadSchema`, and other operations under the classloader
3. Finally, we are going to drop the Iceberg catalog if it's no longer needed, so we need to close the catalog, close the classloader, and release associated resources. However, due to a daemon thread introduced by `CachedClientPool` (Implementation class of CachedClientPool), the classloader can't be GC and thus will leads to OOM eventually.

```java

    // Code block from CachedClientPool#init
    clientPoolCache =
          Caffeine.newBuilder()
              .expireAfterAccess(evictionInterval, TimeUnit.MILLISECONDS)
              .removalListener((ignored, value, cause) -> ((HiveClientPool) value).close())
              .scheduler(
                 // This daemon thread can't be explicitly closed.
                  Scheduler.forScheduledExecutorService(
                      ThreadPools.newScheduledPool("hive-metastore-cleaner", 1)))
              .build();
```

**Comment by pvary** [comment]
@yuqi1129: Could setting the `client.pool.cache.eviction-interval-ms`, and decreasing the `clients` size help your case?

**Comment by yuqi1129** [comment]
> @yuqi1129: Could setting the `client.pool.cache.eviction-interval-ms`, and decreasing the `clients` size help your case?

I'm afraid it won't work for me, decreasing `client.pool.cache.eviction-interval-ms` will not affect the fact that thread pool `hive-metastore-cleaner` is a daemon thread, only when the JVM exit can it be closed automatically. We can't close it in an isolated class loader as we won't be able to get its reference.

**Comment by ben-manes** [comment]
Can you use the daemon thread from the jdk (via systemScheduler)?

**Comment by pvary** [comment]
@yuqi1129: Do I understand correctly, that your main issue is that the cleaner threads are remaining, and those are the only ones causing the issue?

**Comment by yuqi1129** [comment]
> Can you use the daemon thread from the jdk (via systemScheduler)?

Then how can I use the `systemScheduler` here? I can't change the following code from an external project as it's part of the Iceberg inner class.  

```
 // Code block from CachedClientPool#init
    clientPoolCache =
          Caffeine.newBuilder()
              .expireAfterAccess(evictionInterval, TimeUnit.MILLISECONDS)
              .removalListener((ignored, value, cause) -> ((HiveClientPool) value).close())
              .scheduler(
                 // This daemon thread can't be explicitly closed.
                  Scheduler.forScheduledExecutorService(
                      ThreadPools.newScheduledPool("hive-metastore-cleaner", 1)))
              .build();
```

**Comment by yuqi1129** [comment]
> @yuqi1129: Do I understand correctly, that your main issue is that the cleaner threads are remaining, and those are the only ones causing the issue?

Yeah, I want a mechanism to explicitly close them.

**Comment by pvary** [comment]
@yuqi1129: Caffeine suggests using Java9 system scheduler if possible. https://github.com/ben-manes/caffeine/wiki/Cleanup

Would it work for you, or the specific classpath handling you are using, would cause issues with it?

**Comment by yuqi1129** [comment]
> @yuqi1129: Caffeine suggests using Java9 system scheduler if possible. [Wiki: Cleanup (ben-manes/caffeine)](https://github.com/ben-manes/caffeine/wiki/Cleanup)
> 
> Would it work for you, or the specific classpath handling you are using, would cause issues with it?

Unfortunately, we plan to support Java8 , what's more, the `Cache` instance is internal field of `CachedClientPool`, I'm afraid we can't change it except for the reflection mechanism. 

Let me explain our user cases.

The Gravitino supports creating multiple catalogs, for example, assuming we have created 3 Iceberg catalogs ,each Iceberg catalog will use a separate classloader to load iceberg-related jars (include `iceberg-hive-metastore.jar`) to provide service.  After some time, we do not need a specific catalog and we plan to drop it. When we plan to close the corresponding classloader, it cannot be GC by the JVM as there is still a daemon thread mentioned before in the issue, so we need a mechanism to explicitly close the daemon thread. 

can you give me some advice, thanks.

**Comment by pvary** [comment]
I would suggest to bring this up on the dev list, to see if the opinion of the community has been evolved in the past few years, and you can gather support for the closeable catalog.

But independently of the decision of the community, having your own catalog implementation is always an option you

**Comment by yuqi1129** [comment]
> I would suggest to bring this up on the dev list, to see if the opinion of the community has been evolved in the past few years, and you can gather support for the closeable catalog.
> 
> But independently of the decision of the community, having your own catalog implementation is always an option you

Ok, let's retry, thanks.
