### ISSUE TITLE
Can Iceberg old partition with no data  be deleted?

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg#10121]
### Query engine

spark

### Question

![image](https://github.com/apache/iceberg/assets/23215922/f89489c9-dd57-418d-8f25-6627376b1a5b)
As image above, how to delete partition field path as "xxx=null/yyy=null/" **with no data in it** 

/data/old_xxx=null/old_yyy=null/new_partition_1=123/new_partition_2=abc  =>
/data/new_partition_1=123/new_partition_2=abc

**Comment by ajantha-bhat** [comment]
how is the table partitioned? Can you do describe table or show create table to show the partition scheme? Also, was there any partition evolution? Are you using V1 Iceberg table or v2?

**Comment by madeirak** [comment]
> how is the table partitioned? Can you do describe table or show create table to show the partition scheme? Also, was there any partition evolution? Are you using V1 Iceberg table or v2?

thx for reply, this table has indeed changed partitions.
Before, show create table on this table , and get "PARTITIONED BY (old_xxx, old_yyy)", with no data in the table.
Then, the partition fields change to  "PARTITIONED BY (new_partition_1, new_partition_2)"

I know this form is used for data co-existence between new and old partitions，with old partition field = null.
but in my case, old partition field has no data in it, I am worried that a long path will affect the efficiency of READ and WRITE, 
**so I wonder if there is way to delete the old partition path with no data, or the impact of a long path on the efficiency of READ and WRITE**?

**Comment by ajantha-bhat** [comment]
I think Iceberg v1 tables has a concept of void transform and it will keep the dropped partition still as a void after partition evolution. 

Try changing the table default format version table property to 2 and try the partition evolution freshly with rewrite data files again.

**Comment by ajantha-bhat** [comment]
Lastly I think there is no way to delete empty folders in Iceberg. Only files are tracked by Iceberg metadata. So, GC operations only clean up the files.

**Comment by madeirak** [comment]
> Lastly I think there is no way to delete empty folders in Iceberg. Only files are tracked by Iceberg metadata. So, GC operations only clean up the files.

thx set version of table to 2, it does fix my problem😘
