### ISSUE TITLE
Iceberg Rest OpenAPI Spec views/rename should return 204

### ISSUE THREAD

**Issue by c-thiel** [apache/iceberg#10135]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

I believe I found a small inconsistency in the Iceberg Openapi spec.
views/rename returns a 200 OK according to the openapi spec, while all other NO CONTENT returns, such as head for views or tables/rename return a 204 code.

https://github.com/apache/iceberg/blob/81b3310ab469408022cc14af51257b7e8b36614f/open-api/rest-catalog-open-api.yaml#L1390

**Comment by ajantha-bhat** [comment]
@c-thiel : You are right. Would you like to raise a PR to fix it?
