### ISSUE TITLE
 spark.table() raises warn: Unclosed S3FileIO instance in NessieTableOperations

### ISSUE THREAD

**Issue by KingLommel** [apache/iceberg#10144]
### Apache Iceberg version

1.4.2

### Query engine

Spark

### Please describe the bug 🐞

Similar to this issue https://github.com/apache/iceberg/issues/7841

When I use `spark.table()` with the NessieCatalog I get a warning: `WARN  o.a.i.a.s.S3FileIO: Unclosed S3FileIO instance created by ...`

**Full Stacktrace:**

`  | => rorg.apache.iceberg.aws.s3.S3FileIO.initialize(S3FileIO.java:359)
        org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:325)
	org.apache.iceberg.nessie.NessieCatalog.initialize(NessieCatalog.java:125)
	org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:239)
	org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:284)
	myproject.iceberg.Iceberg$.getIcebergCatalog(Iceberg.scala:56)
	myproject.streaming.CdcStreaming$.stream(CdcStreaming.scala:32)
	myproject.CdcStreamingApp.$anonfun$run$1(CdcStreamingApp.scala:42)
	scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	scala.util.Try$.apply(Try.scala:213)
	myproject.CdcStreamingApp.run(CdcStreamingApp.scala:31)
	myproject.integrationtests.Checkpointing.$anonfun$new$2(Checkpointing.scala:45)
	scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	org.scalatest.Transformer.apply(Transformer.scala:22)
	org.scalatest.Transformer.apply(Transformer.scala:20)
	org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1832)
	org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1686)
	org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1830)
	org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1842)
	org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1842)
	org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1824)
	myproject.integrationtests.Checkpointing.com$dimafeng$testcontainers$scalatest$TestContainersForAll$$super$runTest(Checkpointing.scala:16)
	com.dimafeng.testcontainers.scalatest.TestContainersForAll.runTest(TestContainersForAll.scala:70)
	com.dimafeng.testcontainers.scalatest.TestContainersForAll.runTest$(TestContainersForAll.scala:62)
	myproject.integrationtests.Checkpointing.org$scalatest$BeforeAndAfterEach$$super$runTest(Checkpointing.scala:16)
	org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:234)
	org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
	myproject.integrationtests.Checkpointing.runTest(Checkpointing.scala:16)
	org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1900)
	org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	scala.collection.immutable.List.foreach(List.scala:431)
	org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1900)
	org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1899)
	org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1686)
	org.scalatest.Suite.run(Suite.scala:1114)
	org.scalatest.Suite.run$(Suite.scala:1096)
	org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1686)
	org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1945)
	org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1945)
	org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1943)
	myproject.integrationtests.Checkpointing.com$dimafeng$testcontainers$scalatest$TestContainersForAll$$super$run(Checkpointing.scala:16)
	com.dimafeng.testcontainers.scalatest.TestContainersForAll.run(TestContainersForAll.scala:45)
	com.dimafeng.testcontainers.scalatest.TestContainersForAll.run$(TestContainersForAll.scala:37)
	myproject.integrationtests.Checkpointing.run(Checkpointing.scala:16)
	org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
	org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
	sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by Fokko** [comment]
@KingLommel Thanks for raising this. Do you know if this issue also exists in 1.5.0?

**Comment by KingLommel** [comment]
Yes. I currently tested it and for Iceberg Version 1.5.0 I get the same warning

**Comment by ajantha-bhat** [comment]
@KingLommel, @Fokko : Recently someone else also reported it in Iceberg slack. 

`NessieCatalog` properly closing the fileIO during `NessieCatalog.close()` 
Does this mean, `SparkCatalog` is not closing the `icebergCatalog` object? I wonder this is the common problem for all the catalogs?

**Comment by ajantha-bhat** [comment]
cc: @dimas-b

**Comment by KingLommel** [comment]
@ajantha-bhat This user defined function just calls the function ```org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:284)``` and puts in the right arguments and returns the catalog as a result. Nothing special there.

**Comment by ajantha-bhat** [comment]
the count from `buildIcebergCatalog` has to be closed for its fileIO to be closed. Now we are getting fileIO not closed warning because, catalog is not closed.
