### ISSUE TITLE
Doubts about the types supported by Iceberg, Not in line with expectations

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg#10153]
### Query engine

spark sql

### Question

At first, I got the official doc as below about supported types.
https://iceberg.apache.org/docs/latest/spark-getting-started/#spark-type-to-iceberg-type
Then I want to add column with type "list/array" through spark sql as image below
![image](https://github.com/apache/iceberg/assets/23215922/16a78c49-a177-4ccf-9fc7-1f359c7ae4b6)
![image](https://github.com/apache/iceberg/assets/23215922/22365c0c-153b-4d92-85f9-5ece603c9b12)

Did I use it in the wrong way? How should I use it correctly?

**Comment by ajantha-bhat** [comment]
@madeirak, you forgot to mention the data type for `array` column? for example `ARRAY<STRING>`

**Comment by madeirak** [comment]
> @madeirak, you forgot to mention the data type for `array` column? for example `ARRAY<STRING>`

damn
