### ISSUE TITLE
Timestamp/Day transform returns Date as required type while days is actually stored integer

### ISSUE THREAD

**Issue by zinking** [apache/iceberg#10159]
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

when querying partition information of a day(timestamp_field) partition table.  the spec states `day` transfrom returns an integer. 

when looking at spec.javaClass() it is also integer, but when the transform processes the result type. it seems it puts Date there on purpose like this 

```
  @Override
  public Type getResultType(Type sourceType) {
    if (granularity == ChronoUnit.DAYS) {
      return Types.DateType.get();
    }
    return Types.IntegerType.get();
  }
```

no idea why would day() transform yield a date class,  while the spec states it should return integer?

**Comment by manuzhang** [comment]
@zinking You may check [this comment](https://github.com/apache/iceberg/issues/279#issuecomment-519620975) for the background.

**Comment by zinking** [comment]
> @zinking You may check [this comment](https://github.com/apache/iceberg/issues/279#issuecomment-519620975) for the background.

thanks
