### ISSUE TITLE
Iceberg may occur data duplication when use flink to write data to iceberg and commit failed

### ISSUE THREAD

**Issue by zlzhang0122** [apache/iceberg#10165]
### Apache Iceberg version

1.3.0

### Query engine

Spark and Flink

### Please describe the bug 🐞

Iceberg may occur data duplication when use flink to write data to iceberg and commit failed, it cannot distinguish the snapshot emit by each checkpoint, and then once the committer stuck for a moment or similar situation, it will commit all the snapshots produced by current checkpoint and all previous checkpoints.

We can modify some flink config to avoid this problem, but I think this is not a perfect resolvent since it can cause other relative problem, maybe we can emit the snapshots and checkpointId together and we can solve it completely. What do u think and any reply will be appreciated, thanks!

**Comment by pvary** [comment]
Could you please describe the exact si
