### ISSUE TITLE
Restrict generated locations to URI syntax

### ISSUE THREAD

**Issue by dimas-b** [apache/iceberg#10168]
### Feature Request / Improvement

It is [possible](https://github.com/projectnessie/nessie/issues/8328) to make Iceberg produce S3 (as an example) locations that violate URI syntax.

Granted that existing Iceberg code works fine with that, it would be nice for Iceberg to stay within the URI syntax when producing data file locations (e.g. transforming partition column names and values to set of chars permitted in URI).

The general rationale for this request is to increase interoperability.

### Query engine

N/A

**Comment by ajantha-bhat** [comment]
Assigned the milestone "Iceberg V3 spec" milestone as discussed on community sync.
