### ISSUE TITLE
does iceberg can run on k8s?

### ISSUE THREAD

**Issue by JunseoChoJJ** [apache/iceberg#10196]
### Query engine

I am using spark 

### Question

hi
I'm a newbee to iceberg. and it might be stupid question but please tell me 
does iceberg can run on k8s?
My think was spark can run on k8s so icberg can also run on k8s
other spark, superset, flink has docs on how to install on k8s
but iceberg doesn't have docs on how to install on k8s. so I'm in struggle.

**Comment by nastra** [comment]
@JunseoChoJJ yes Iceberg can run on k8s. There are no special installation docs required for k8s. Iceberg is integrated through your engine of choice (Flink, Spark, Trino, ..), so all you need to do is properly set up Iceberg with your engine according to the docs. (e.g. setting up Spark with Iceberg is documented [here](https://iceberg.apache.org/docs/latest/spark-configuration/))

**Comment by JunseoChoJJ** [comment]
@nastra thank you can I ask you one more After they etl in spark using iceberg, they put data in to storage like s3, Gcs, minio. Can I put this data into our storage as well using rest api?

**Comment by nastra** [comment]
If Naver Cloud Storage has an S3-compatible API, then you can use it with Iceberg by using `S3FileIO` in your Spark catalog config: `--conf spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO`

**Comment by JunseoChoJJ** [comment]
@nastra Thanks a lot
