### ISSUE TITLE
Add _file and _pos metadata columns to ORC readers

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#1021]
Position-based delete files encode row deletes as a file and ordinal row position within that file. To write position-based delete files for ORC, Iceberg should produce the file and position for a given row as metadata columns.

The file metadata column is a constant and can reuse the id-to-constant map that sets identity-partition values.

The position metadata column will require tracking the starting position of the first row in each stripe using footer metadata, and using a counter within each stripe to produce the final position value.

**Comment by shardulm94** [comment]
I was planning to work on this, but I am unsure of some of the details.
- How does the ORC reader know that it has to project metadata columns? Will it be part of the expected Iceberg schema provided to the readers? If yes, will these columns have reserved field ids which helps the readers identify the metadata columns or do they have specific names?
- I was thinking of passing starting position of the first row in each VectorizedRowBatch as part of the OrcValueReader interface and then create a new OrcValueReader returns baseOffset+currentRowIndex for every row. Let me know if this sounds okay to you.

**Comment by rdblue** [comment]
> How does the ORC reader know that it has to project metadata columns? Will it be part of the expected Iceberg schema provided to the readers?

Yes. Iceberg will pass in a schema that has the metadata column. We have an example implementation in our current branch with [the column definitions](https://github.com/Netflix/iceberg/blob/netflix-spark-2.4/spark/src/main/java/org/apache/iceberg/spark/source/MetadataColumns.java) and an [implementation for `_file`](https://github.com/Netflix/iceberg/blob/netflix-spark-2.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java#L410-L458) that uses a joined row (the way we used to do for identity partition values).

We would add detection to the value reader builder that injects the `_pos` reader.

> I was thinking of passing starting position of the first row in each VectorizedRowBatch as part of the OrcValueReader interface and then create a new OrcValueReader returns baseOffset+currentRowIndex for every row.

Sounds reasonable to me.

**Comment by shardulm94** [comment]
Since open source Spark does not support metadata columns, is it okay for these columns be included in the readSchema returned to Spark, maybe enabled through an option? That way we can return data/rows with `_file` and `_pos` to Spark without having to apply a projection to filter them out, similar to how we handle extra columns required for filters.

**Comment by rdblue** [comment]
Yes, we can do that. Is the use case to be able to build a job that deletes rows in Spark?

I don't think we would need to expose the columns to Spark just for merging in position delete files. We can project those columns in the read builder if they are needed.

**Comment by shardulm94** [comment]
I was trying to wrap my head around how it would all fit in together. I was also thinking of possibly using Spark to write test cases for this, but I guess we can test using `ORC.read()` directly.

**Comment by rdblue** [comment]
Yeah. Given how long Spark tests take to run, we should keep the number of them down and try to write as many tests as possible without it.

**Comment by rdblue** [comment]
This was implemented in #1207.
