### ISSUE TITLE
AWS: Updating Glue catalog table removes column descriptions

### ISSUE THREAD

**Issue by aajisaka** [apache/iceberg#10220]
### Apache Iceberg version

main (development)

### Query engine

Spark

### Please describe the bug 🐞

In AWS Glue Catalog, user can set arbitrary descriptions to the table and its columns via Web UI or even from Amazon Athena. However, the descriptions are deleted after upgrading the table.

I submitted a patch to retain the table description in https://github.com/apache/iceberg/pull/10199, but I would like to retain column descriptions as well in a separate PR later.

**Comment by lawofcycles** [comment]
I would be interested in working on a fix for this.
