### ISSUE TITLE
Documentation page returning 404

### ISSUE THREAD

**Issue by yakovsushenok** [apache/iceberg#10249]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

[This](https://iceberg.apache.org/docs/1.5.0/spark-configuration.md#sql-extensions) link (the second one) on [this](https://iceberg.apache.org/docs/1.5.0/spark-procedures/) page is returning a 404. Not sure if this is the right place to report it.

**Comment by manuzhang** [comment]
We are still fixing doc links in previous releases tracked at #10116
