### ISSUE TITLE
Renaming of ConfVars Enums in Apache Hive breaks compatibility of HiveCatalog dependency in Apache Iceberg

### ISSUE THREAD

**Issue by dom93dd** [apache/iceberg#10254]
### Feature Request / Improvement

With following PR https://github.com/apache/hive/pull/4919 all ConfVars Enums in Apache.Hive dependency were renamed for better readability. This is included from the 4.0.0 Beta version in Hive.

Unfortunately, this breaks the compatibility with with apache.iceberg.hive dependency. Especially for the HiveCatalog class.

My suggestion is to change all the Enums in apache.icerberg too.

### Query engine

Hive

**Comment by dom93dd** [comment]
@nastra I did see that and moved over to that dependency. The problem is, that apache.hive is using shading for fasterxml in the https://mvnrepository.com/artifact/org.apache.hive/hive-iceberg-catalog/4.0.0 dependency. That breaks the usage of the JsonUtil class from apache.iceberg which isn't using shading for fasterxml. 
I added my own shading to resolve this issue, but in my case I need to build a thin jar where I can't include the fix.

**Comment by nastra** [comment]
Shading in https://github.com/apache/hive/blob/master/iceberg/iceberg-shading/pom.xml#L97-L100 is correct IMO. Are you using the `iceberg-core` jar directly rather than through a shaded jar? If that's the case, then you'd need to switch to using a shaded jar

**Comment by dom93dd** [comment]
@nastra Do you mean those two deps?:

```
<dependency>
	<groupId>org.apache.hive</groupId>
	<artifactId>patched-iceberg-core</artifactId>
	<version>patched-1.4.3-4.0.0</version>
</dependency>
<dependency>
	<groupId>org.apache.hive</groupId>
	<artifactId>patched-iceberg-api</artifactId>
	<version>patched-1.4.3-4.0.0</version>
</dependency>
```

Even when using that, I get the error for the shading (missing function of fasterxml mapper).

I need to use this dependency to resolve the missing underscores in HiveCatalog:

```
<dependency>
	<groupId>org.apache.hive</groupId>
	<artifactId>hive-iceberg-catalog</artifactId>
	<version>4.0.0</version>
</dependency>
```

**Comment by nastra** [comment]
Those seem to be patched versions for api/core. What you typically would use is a shaded version that bundles all dependencies together. In any case, I don't see anything that needs to be fixed in the Iceberg repo itself related to this, so I think this issue can be closed.

**Comment by nastra** [comment]
For Hive < 4 there is [iceberg-hive-runtime](https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-hive-runtime) (which is maintained by the Iceberg community)
For Hive >= 4 there is [hive-iceberg-shading](https://mvnrepository.com/artifact/org.apache.hive/hive-iceberg-shading) (which is maintained by the Hive community)

**Comment by dom93dd** [comment]
@nastra Danke Dir!
