### ISSUE TITLE
org.apache.iceberg.expressions.(Max/Min)Aggregate  Don't handle null DataFile.(upper/lower)Bounds() 

### ISSUE THREAD

**Issue by jkolash** [apache/iceberg#10258]
### Apache Iceberg version

1.5.0

### Query engine

Spark

### Please describe the bug 🐞

If you use the snapshot table command and run 

```select max(intValue) from table``` this can be reproduced. 

The spec says this is optional
https://iceberg.apache.org/spec/#manifests
![image](https://github.com/apache/iceberg/assets/801170/60989007-7323-484c-8d7c-378869e23441)

Let me know if you want me to provide a test case/fix as it seems like a pretty simple issue to test/fix for.

**Comment by jkolash** [comment]
relevant code
https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/expressions/MaxAggregate.java#L42
```java
  @Override
  protected boolean hasValue(DataFile file) {
    boolean hasBound = file.upperBounds().containsKey(fieldId); //NPE here
    Long valueCount = safeGet(file.valueCounts(), fieldId);
    Long nullCount = safeGet(file.nullValueCounts(), fieldId);
    boolean boundAllNull =
        valueCount != null
            && valueCount > 0
            && nullCount != null
            && nullCount.longValue() == valueCount.longValue();
    return hasBound || boundAllNull;
  }
```

**Comment by amogh-jahagirdar** [comment]
> Let me know if you want me to provide a test case/fix as it seems like a pretty simple issue to test/fix for.

@jkolash if you're up for it, feel free to raise a PR! I'm happy to review.
