### ISSUE TITLE
Upgrade HadoopTableOperations.version from int32 to long64

### ISSUE THREAD

**Issue by jkolash** [apache/iceberg#10277]
### Feature Request / Improvement

We are using the hadoop catalog and have encountered tables written by a 3rd party that are encoding the latest-version.text field in a value higher than supported by int32. 

I can provide a PR if it is desired, the changes are all isolated to HadoopTableOperations.

The only issue I encountered were if the spark driver/worker iceberg jars were not the same we'd have serialization issues, but this is very often the case anyway when upgrading libraries.

### Query engine

Spark

**Comment by nastra** [comment]
@jkolash can you share a little bit more details about the 3rd party that is writing this? It would be good to know why this 3rd party writes this as a long instead of an int.

**Comment by nastra** [comment]
@jkolash you might want to report this to Snowflake as the version should currently be an int instead of a long to comply with the implementation in Iceberg

**Comment by jkolash** [comment]
Seeing other implementations that use version-latest.text and whether int32 would break them.

# duckdb
https://github.com/duckdb/duckdb_iceberg/blob/main/src/common/iceberg.cpp#L220C25-L220C40 uses a string and makes no assumptions about the type other than that it seems.

**Comment by jkolash** [comment]
Closing this issue, as it won't be relevant for snowflake anymore.
