### ISSUE TITLE
 "Iceberg.engine.hive.enabled" Conf is not honouring for HIVE CATALOG

### ISSUE THREAD

**Issue by shivjha30** [apache/iceberg#10286]
### Apache Iceberg version

1.4.3

### Query engine

Hive

### Please describe the bug 🐞

 In the iceberg documentation it could be seen that
"To enable Hive support globally for an application, set iceberg.engine.hive.enabled=true in its Hadoop configuration."

The value of iceberg.engine.hive.enabled must be true in order to enable hive support. However, it could still use Iceberg's hive support even if it  is set as "iceberg.engine.hive.enabled" to false. If i understand correctly, the value "iceberg.engine.hive.enabled" is irrelevant.

Current scenario:

if it is a hive catalog we are setting engine.hive.enabled as true.
In

[iceberg/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java](https://github.com/apache/iceberg/blob/01bc864b8eb8c4ca4240af85f00f4e67c78c466e/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L486)

Line 486 in [01bc864](https://github.com/apache/iceberg/commit/01bc864b8eb8c4ca4240af85f00f4e67c78c466e)

Even when we set ConfigProperties.ENGINE_HIVE_ENABLED to FALSE in Hadoop configuration, we are passing the ConfigProperties.ENGINE_HIVE_ENABLED as TRUE in the HiveIcebergMetaHook#commitCreateTable if it's of HiveCatalog type. 
We are initially evaluating the 'engine.hive.enabled' value in HiveTableOperations#hiveEngineEnabled. In cases where it's a Hive catalog, this value is consistently 'True', rendering the 'iceberg.engine.hive.enabled' as unnecessary.

**Comment by pvary** [comment]
This is intentional.
If you are using [HiveIcebergMetaHook](https://github.com/apache/iceberg/blob/ed0959257cba02f378f7097d81cecaaaef9fa43f/mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java) then you are using Hive to create the table. The expectation in this case, that you want to be able read the table with Hive.

See the discussion here: https://github.com/apache/iceberg/pull/1495#discussion_r1582544488

**Comment by shivjha30** [comment]
@pvary then, for a cluster level if we set icebeg.engine.hive.enabled as false and we don’t pass the table properties(hive.engine.enabled as false), even then we are creating the table with Iceberg, ideally it shouldn’t be.
