### ISSUE TITLE
Add an action to rewrite data files and remove deleted rows

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#1028]
Tables will eventually need to apply deletes to data files and remove deleted rows. Iceberg should provide an action to do this.

**Comment by bigheadzen** [comment]
@rdblue Is this rewrite process mutually exclusive with other UPDATE/DELETE operations in partition level, if not table level? IIUC, we cannot generate delete files for a base file while it's being rewritten to a new base file.
