### ISSUE TITLE
Spec: Add schema IDs, schema list, and associate each Snapshot with a schema

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#1029]
Replacing an entire table is a supported action that replaces the schema of a table along with all of the data. The use case is reporting tables, where the data completely changes from day to day and it makes little sense to maintain the schema using DDL when the report is generated using a CTAS or RTAS query. For these tables, each snapshot may have its own schema and reading an older snapshot should use that snapshot's schema.

**Comment by waterlx** [comment]
The same as #1508

**Comment by rdblue** [comment]
This is done. #2654 updated the spec and @yyanyy implemented the changes in the reference implementation in #2096 and #2275. There are still a couple more things to do for #1508, but the spec and tracking portion are done.
