### ISSUE TITLE
remove orphan file question

### ISSUE THREAD

**Issue by JunseoChoJJ** [apache/iceberg#10363]
### Query engine

trino 

### Question

when certain data files in Iceberg table might lose their reference in any metadata files and become orphan

I'm not sure when does iceberg table might lose their reference
Is there any case? 

I kind of understand in context meaning but not sure when is the case so it is hard for me to use this remove orphan file 

does anyone have this idea as well? #10299

**Comment by manuzhang** [comment]
It usually happens when snapshots are removed while their referenced files are not somehow. For example, in `expire_snapshots`  procedure, expired file are removed after their snapshots having been deleted. If the file removal fails, they are left as orphans.

**Comment by JunseoChoJJ** [comment]
@manuzhang thanks a lot can i ask you one more question

**Comment by manuzhang** [comment]
All maintenance procedures are one-time and you need to set up periodical jobs with a scheduler like Airflow

**Comment by JunseoChoJJ** [comment]
@manuzhang thanks a lot
