### ISSUE TITLE
Introduce a parameter to control whether the flink writer is linked with the previous operator

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/iceberg#10371]
### Feature Request / Improvement

The flink task written to iceberg can set write-parallelism, which allows it to have different parallelism degrees from the previous operator. However, when it modifies why the parallelism degree of the previous operator is the same, it cannot be restored from the checkpoint, because flink defaults to The operators are chained together, so we should have a parameter to actively cause them to be separated

### Query engine

None

**Comment by pvary** [comment]
Could you use one of the ways described [here](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/overview/#task-chaining-and-resource-groups) to archive this?

**Comment by huyuanfeng2018** [comment]
> Could you use one of the ways described [here](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/overview/#task-chaining-and-resource-groups) to archive this?

Yes, it can be achieved through the flink api in this

**Comment by pvary** [comment]
If we have a possibility to archive this using Flink features without any changes in Iceberg, then I don't think we need to add this feature to Iceberg too.

**Comment by huyuanfeng2018** [comment]
> If we have a possibility to archive this using Flink features without any changes in Iceberg, then I don't think we need to add this feature to Iceberg too.

In the scenario of using flinksql, it is impossible to use the capabilities provided by flink to complete this feature. This is similar to Apache Paimon. We have also added similar functions to paimon.

https://github.com/apache/paimon/pull/3300

**Comment by pvary** [comment]
Do I understand correctly,  that this is a missing feature in Flink SQL? Did we consider adding this feature to Flink SQL? I might be able to find reviewers for a Flink PR, if we find that's a better way to move forward.

**Comment by huyuanfeng2018** [comment]
> Do I understand correctly, that this is a missing feature in Flink SQL? Did we consider adding this feature to Flink SQL? I might be able to find reviewers for a Flink PR, if we find that's a better way to move forward.

It is indeed impossible to implement it in flinksql at this stage, but I feel that this does not seem to be within the scope of flinksql's capabilities, because iceberg flink runtime is a flink connector. Does flinksql have the ability to intervene in the logic in the connector? I'm not sure. It seems that we need Flink developers who know more about this area to answer it. Can you help in this area?

**Comment by pvary** [comment]
@huyuanfeng2018: Did we try to add this feature to Flink? What was the response of the community there? Seems suboptimal for me to add this feature to every connector independently...

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018: Did we try to add this feature to Flink? What was the response of the community there? Seems suboptimal for me to add this feature to every connector independently...

Sounds like a good implementation in flink, I'll try to push this feature in the flink community

**Comment by pvary** [comment]
@huyuanfeng2018: Please link the discussion here, so it it's easy to follow the discussion.
Thanks, Peter

**Comment by huyuanfeng2018** [comment]
https://issues.apache.org/jira/browse/FLINK-35462
