### ISSUE TITLE
Iceberg TTL setting

### ISSUE THREAD

**Issue by smileyboy2019** [apache/iceberg#10372]
### Feature Request / Improvement

iceberg
The expired table of the table can be automatically archived, and TTL can be set for the table. At the same time, the archiving path can be set, and it can be automatically archived. When querying archived data, it has no impact on the user.

### Query engine

None

**Comment by jbonofre** [comment]
By TTL, you mean on a table snapshot ? 

Table snapshot has a timestamp, so, we could have a TTL based on snapshots timestamp and remove "expired" snapshot.
Is it what you mean ?

Do you have an use case where this feature would make sense ? Is it just a way to "reduce" the manifest file ?

Thanks !

**Comment by BsoBird** [comment]
你是指iceberg可以支持将数据写入到多级存储的不同路径中么?

**Comment by smileyboy2019** [comment]
是支持生命周期的TTL，同时设置归档目录，到期的数据自动归档历史数据路径里面

//TTL时间设置，超过7天数据自动删除
CREATE TABLE my_table (   id INT,   name STRING ) PARTITIONED BY (dt STRING, city STRING) TBLPROPERTIES ("hive.table.parameters.ttl" = "7 days");
//对这张表超过7天数据进行归档，自动存放到对应目录
set hive.archive.enabled=true; hive&gt; set hive.archive.har.parentdir.settable=true; hive&gt; set har.partfile.size=1099511627776;


&nbsp;


志阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "PLASH ***@***.***&gt;; 
发送时间: 2024年5月27日(星期一) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/iceberg] iceberg TTL set (Issue #10372)














 
你是指iceberg可以支持将数据写入到多级存储的不同路径中么?
