### ISSUE TITLE
Copy iceberg table from hdfs to GCS and register table to BLMS

### ISSUE THREAD

**Issue by Manoranjan93** [apache/iceberg#10389]
### Query engine

_Dataproc_

### Question

Does iceberg table support in place migration - I have iceberg tables stored in hdfs location which have been copied to GCS location, Now I want to register those tables in big lake metastore (BLMS). Please suggest the best approach ?

**Comment by Fokko** [comment]
Hey @Manoranjan93 Thanks for reaching out!

Iceberg has absolute paths, so you cannot just copy the files as the paths in the metadata still point to S3. The best way to copy this is using a query engine such as Spark, Trino, etc.

Biglake is still underway, see https://github.com/apache/iceberg/pull/7412 I hope this helps!
