### ISSUE TITLE
Iceberg Roadmap is 404

### ISSUE THREAD

**Issue by gphilipp** [apache/iceberg#10390]
### Question

This page yields a 404: https://iceberg.apache.org/roadmap/

Is this where the roadmap is supposed to be?

**Comment by ajantha-bhat** [comment]
It was removed after discussion in https://github.com/apache/iceberg/pull/9941

**Comment by gphilipp** [comment]
Thanks, I also found out. It'd be nice to point to _something_. For example, Delta Lake has a placeholder page which points to https://github.com/orgs/delta-io/projects/10/views/1.

**Comment by gphilipp** [comment]
Maybe just add a pointer to https://github.com/apache/iceberg/projects?query=is%3Aopen&type=classic in https://iceberg.apache.org/roadmap/?

**Comment by ajantha-bhat** [comment]
https://github.com/apache/iceberg/projects?query=is%3Aopen&type=classic is not well maintained as of now. Also It only captures ongoing projects. Roadmaps usually will also include future projects too. 

Last time @Fokko, @jbonofre, @bitsondatadev had some conclusion about roadmap. I will wait for them to reply.

**Comment by jbonofre** [comment]
roadmap page has been removed to avoid confusion as it was not up to date.
We proposed/discussed to replace with a link on GitHub issues using milestone tag. That said, I'm not sure the GH Issues as up to date and maybe some are missing.
