### ISSUE TITLE
How iceberg implements materialized views

### ISSUE THREAD

**Issue by smileyboy2019** [apache/iceberg#10406]
### Feature Request / Improvement

Iceberg registers the external catalog table through Spark SQL and converts it into a materialized view by querying SQL
![image](https://github.com/apache/iceberg/assets/59221294/3690ea80-3484-4c2d-8014-ebc84ad1ad8e)
![image](https://github.com/apache/iceberg/assets/59221294/97967c31-7380-4a20-a9b9-74db911f97ee)

### Query engine

None

**Comment by smileyboy2019** [comment]
https://github.com/StarRocks/starrocks
Refer to starrocks

**Comment by manuzhang** [comment]
The proposal of materialized view is still under active discussion. Please refer to https://github.com/apache/iceberg/issues/10043 and discussion on the mailing list.

**Comment by findepi** [comment]
Closing as a duplicate of https://github.com/apache/iceberg/issues/10043
