### ISSUE TITLE
Broken links in Spark Writes documentation

### ISSUE THREAD

**Issue by gphilipp** [apache/iceberg#10409]
### Apache Iceberg version

1.5.2 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I'm not an Iceberg user, just browsing the doc around. 
I've noticed that all links pointing to other pages are broken on https://iceberg.apache.org/docs/latest/spark-writes (there might be additional broken links in other pages but I haven't checked those).

Eg
> To use Iceberg in Spark, first configure [Spark catalogs](https://iceberg.apache.org/docs/latest/spark-configuration.md).

**Comment by Fokko** [comment]
Thanks for reporting this @gphilipp 🙌 I checked, and the nightly ones are working, so that's good. Looks like @manuzhang is fixing the already published versions.

**Comment by gphilipp** [comment]
It’s fixed thanks
