### ISSUE TITLE
End-of-life Flink 1.16 is still referenced in docs

### ISSUE THREAD

**Issue by manuzhang** [apache/iceberg#10412]
### Apache Iceberg version

main (development)

### Query engine

Flink

### Please describe the bug 🐞

Flink 1.16 is no longer supported, but it's still referenced in the nightly docs. For example, at https://iceberg.apache.org/docs/nightly/flink/#preparation-when-using-flink-sql-client

> Download Flink from the [Apache download page](https://flink.apache.org/downloads.html). Iceberg uses Scala 2.12 when compiling the Apache iceberg-flink-runtime jar, so it's recommended to use Flink 1.16 bundled with Scala 2.12.

There is another link to `https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-flink-runtime-1.16/1.5.2/` on this page, and it won't work after next feature release (1.6.0).

We can easily forget to update these docs when Flink versions reaching end-of-life. However, I haven't figured out a better alternative. Thoughts? @nastra @Fokko @pvary @stevenzwu

**Comment by ajantha-bhat** [comment]
While removing the module/folder during EOL marking, we should look up the documents and update it aswell (Reviewer also should check this). 

We (I) handled it for Spark 3.1 and 3.2 while marking EOL. Maybe we missed for latest Flink update.

**Comment by Fokko** [comment]
@manuzhang Thanks for bringing this up 🙌 

What about making the version configurable, both for Spark and Flink, similar to what we did for [Iceberg and Nessie](https://github.com/apache/iceberg/blob/252168419f8ac1d251b39f0944a189184056e543/site/mkdocs.yml#L80-L82).

**Comment by manuzhang** [comment]
Yes, I'm thinking about introducing a DEFAULT_FLINK_VERSION as we do for the code.
