### ISSUE TITLE
Improve remove_orphan_files performance by using "inventory listing"

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#10426]
### Feature Request / Improvement

Compared to listFiles API, inventory listing can be cost efficient for remove_orphan_files performance. 
So, we can enhance the procedure/action to accept the inventory information.  

Reference: https://delta.io/blog/efficient-delta-vacuum/

### Query engine

Spark

**Comment by anuragmantri** [comment]
Hi @ajantha-bhat - Don't we already support this after https://github.com/apache/iceberg/pull/4503?

**Comment by anuragmantri** [comment]
@flyrain did some analysis on this internally. He may have some ideas here.
