### ISSUE TITLE
Iceberg supports binlog logs

### ISSUE THREAD

**Issue by smileyboy2019** [apache/iceberg#10452]
### Feature Request / Improvement

When doing real-time data warehousing, it is possible to achieve CDC to Iceberg from the source. How can the data written to Iceberg be perceived by Flink or Spark. I hope that similar to the binlog mechanism, we can provide CDC services to the outside world

### Query engine

None

**Comment by xiaoxuandev** [comment]
Hi @smileyboy2019, could you clarify your specific goal with binlogs and what you are looking for in Iceberg?
