### ISSUE TITLE
Prioritize the catalog setting method to polaris-catalog.

### ISSUE THREAD

**Issue by 911432** [apache/iceberg#10455]
### Proposed Change

It is understood that the polaris-catalog does not rely on the Hadoop EcoSystem.
[Polaris-catalogs](https://www.snowflake.com/en/data-cloud/polaris-catalog/) look good because they don't rely on the Hadoop ecosystem.
I'd like you to explain how to use Polaris catalog first when connecting to catalog by engine(like spark, flink, trino) except Apache Hive.

### Specifications

- [ ] Table
- [ ] View
- [X] REST
- [ ] Puffin
- [ ] Encryption
- [ ] Other

**Comment by nastra** [comment]
Hey @911432, the Polaris Catalog is not managed by the Iceberg Community so we can't provide any answers about how it works internally and what features it supports and such. You would have to get in contact with Snowflake to figure out those details. I'll go ahead and close this issue

**Comment by 911432** [comment]
[It](https://github.com/snowflakedb/polaris-catalog) complies with the Apache 2.0 license.
