### ISSUE TITLE
Express REST server capabilities

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#10462]
### Proposed Change

When introducing Views to the REST catalog it was clear that we need a way in the REST spec to signal which endpoints are being supported by a REST server. The idea of the proposal is to introduce and express server capabilities via the `/config` endpoint, so that clients know that it is safe to call a particular endpoint on a given REST server.

Capabilities that currently come to mind are:

- views
- vended-credentials
- remote-signing
- multi-table-commit

https://github.com/apache/iceberg/pull/9940 adds the required REST spec changes to introduce `capabilities`.

### Proposal document

https://docs.google.com/document/d/1F1xh6SJhS-opgWRe1pPvWh01j8VHNHRocfCCFttKNf0/edit?usp=sharing

### Specifications

- [ ] Table
- [ ] View
- [X] REST
- [ ] Puffin
- [ ] Encryption
- [ ] Other

**Comment by danielcweeks** [comment]
This has been addressed by #10928
