### ISSUE TITLE
Iceberg tables creation using Spark2.4

### ISSUE THREAD

**Issue by trsree** [apache/iceberg#10479]
### Apache Iceberg version

1.2.1

### Query engine

Spark

### Please describe the bug 🐞

I am trying to integrate iceberg with spark 2.4 to create iceberg tables. what is the correct version of iceberg jar and what is the correct spark configuration to create spark session?
How can i create iceberg tables using spark 2.4?

**Comment by manuzhang** [comment]
You may find latest support version 1.2.1 [in this table](https://iceberg.apache.org/multi-engine-support/#apache-spark)
