### ISSUE TITLE
No module named 'pyiceberg.table.partitioning'

### ISSUE THREAD

**Issue by mounahaadi** [apache/iceberg#10491]
When I run 

from pyiceberg.table.partitioning import PartitionSpec, PartitionField
from pyiceberg.transforms import DayTransform

Getting error like this
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pyiceberg.table.partitioning import PartitionSpec, PartitionField
      2 from pyiceberg.transforms import DayTransform

ModuleNotFoundError: No module named 'pyiceberg.table.partitioning'

**Comment by Shekharrajak** [comment]
Issue should be part of https://github.com/apache/iceberg-python

**Comment by Shekharrajak** [comment]
I think you must try

```
>>> from pyiceberg.partitioning import PartitionSpec, PartitionField
```
