### ISSUE TITLE
Add support for Spark 4.0.0

### ISSUE THREAD

**Issue by Desmeister** [apache/iceberg#10497]
### Feature Request / Improvement

We should explore adding support for Spark 4.0.0.

Based on the [Spark 4.0.0 Umbrella JIRA](https://issues.apache.org/jira/browse/SPARK-44111) and [this mailing list discussion](https://lists.apache.org/thread/nxmvz2j7kp96otzlnl3kd277knlb6qgb), the target release date is within the month.

On June 3rd, a [preview release was announced](https://spark.apache.org/news/spark-4.0.0-preview1.html) corresponding to [this commit](https://github.com/apache/spark/releases/tag/v4.0.0-preview1).

### Query engine

Spark

**Comment by jbonofre** [comment]
Spark 4.0.0-preview2 is available but no 4.0.0 release yet. I think we can prepare a bit the work. I will take a look.

**Comment by jivanic-demystdata** [comment]
Hi 🙂

What is the status of support for Apache Spark 4.0?
It was released last week, and this issue is the first link we find when googling for Apache Spark 4.0 support in Iceberg 


Thanks

**Comment by ajantha-bhat** [comment]
@jivanic-demystdata: Iceberg main branch now supports Spark-4.0 with this PR 
https://github.com/apache/iceberg/pull/13121

There were many duplicate issue to track 4.0 support. This was one of them.
