### ISSUE TITLE
Hive 4.0.0 can't read Iceberg table while inserting data works fine

### ISSUE THREAD

**Issue by nadialeiden** [apache/iceberg#10506]
### Query engine

Hive 4.0.0

### Question

**Versions**

Hive 4.0.0
Hadoop 3.4.0

**Problem**

Hello, I have just encountered a problem regarding to Hive and Iceberg. Based on [https://iceberg.apache.org/docs/latest/hive/#feature-support](url), Hive 4 doesn't need any additional configurations to use Iceberg. Moreover, regarding the catalog, it said that if we does not specify any catalog, it will automatically set to use a HiveCatalog. So I just created the table using this command:

`CREATE EXTERNAL TABLE test (
    id INTEGER,
    name STRING
)
STORED BY ICEBERG
LOCATION '/user/username/datasets/icebergTest';`

and then I inserted a value:

`INSERT INTO test VALUES (1, 'John'), (2, 'Jane'), (3, 'Doe');`

It seemed to insert without any problem, as it returned a message that said 3 rows are affected, and when I checked hive.log it does not seem to encounter a problem while inserting it. However, when I do `select * from test;` it returns nothing as follows:

+----------+------------+
| test.id  | test.name  |
+----------+------------+
+----------+------------+

It successfully generated three directories: metadata, data (containing parquet file), and a temp directory on hdfs. But I can't seem to find why Hive could not read the table. Everything works fine if I created or inserted a table without Iceberg. I have also done `DESCRIBE FORMATTED test;`

it returned: 

![image](https://github.com/apache/iceberg/assets/82803405/928f9912-2e2e-43b6-889d-821209e8ddce)

And the table looks like it saved as an iceberg table and also points to the right directory that stores the metadata. Does this has something to do with the Hive version I'm using? or something with Metastore? Any advice will be appreciated, thank you

**Comment by pvary** [comment]
I would ask this question on the Hive users list, and the if appropriate, I would file a Hive jira. The folks there would know, if this is the way how you should use Hive 4.0.0.

**Comment by nadialeiden** [comment]
@pvary I see, thank you

**Comment by nastra** [comment]
Closing this as Hive4 is being maintained by the Hive community

**Comment by eugeny-stoyka** [comment]
@nadialeiden have you fixed it?
