### ISSUE TITLE
Does iceberg already support spark 3.0?

### ISSUE THREAD

**Issue by yiguolei** [apache/iceberg#1053]

**Comment by chenjunjiedada** [comment]
@yiguolei , Currently, Iceberg has a spark-3 branch that already supports spark 3.0-preview2, but it is a bit lag behind the current master.

**Comment by yiguolei** [comment]
@chenjunjiedada Does it support SQL DDL and DML command?

**Comment by rdblue** [comment]
Yes, the Spark 3 branch supports both SQL DDL and DML.
