### ISSUE TITLE
iceberg-aws-bundle jar includes org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by devinrsmith** [apache/iceberg#10534]
### Apache Iceberg version

1.5.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

I noticed some strange logging issues after depending on `iceberg-aws-bundle`. After a bit of debugging, I found that `iceberg-aws-bundle` includes an unshadowed `org.slf4j.LoggerFactory` (and other `org.slf4j` classes) in the jar:

```
$ jar tf iceberg-aws-bundle-1.5.2.jar | grep "org/slf4j/LoggerFactory"
org/slf4j/LoggerFactory.class
```

I understand the "shading" part of the story, but it does seem a bit odd to also bring in slf4j. Typically, I'd expect `iceberg-aws-bundle` to declare a dependency on `slf4j-api`.

Our application depends on, and is bootstrapped assuming slf4j 2.x (for example, we depend on the `ServiceLoader` mechanism for configuration, https://www.slf4j.org/faq.html#changesInVersion200).

Normally, if a library we depend on declares a dependency on slf4j-api 1.x this isn't an issue since the public APIs are compatible https://www.slf4j.org/faq.html#compatibility. But, when both 1.x and 2.x are on the same classpath and 1.x "wins", our logging isn't able to initialize properly.

Was including `org.slf4j` internal to the bundled jar done on purpose?

**Comment by nastra** [comment]
@devinrsmith thanks for reporting this. Would you be interested in contributing a fix for this?

**Comment by devinrsmith** [comment]
@nastra Just submitted a PR, thanks.

**Comment by nastra** [comment]
> Typically, I'd expect iceberg-aws-bundle to declare a dependency on slf4j-api

The general idea of `iceberg-aws-bundle` is to be a fat jar that bundles everything related to AWS dependencies, meaning that such a jar wouldn't declare any other dependencies. Have you tried excluding slf4j when you consume `iceberg-aws-bundle` as a dependency via `exclude group: 'org.slf4j'`?

**Comment by devinrsmith** [comment]
Exclusions only work for [transitively declared dependencies](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps); in the case of the current `iceberg-aws-bundle`, `org.slf4j` is baked into the fat jar so an `exclude` won't work from the consumers point of view.
