### ISSUE TITLE
Adding an attribute in ORC TypeDescription causes failures.

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#1057]
Details here: https://github.com/apache/incubator-iceberg/pull/989#discussion_r421384789

**Comment by shardulm94** [comment]
@rdsr This should have been fixed already by https://issues.apache.org/jira/browse/ORC-556. Are you sure your local copy was using ORC >= 1.6.3 when you tested this?

**Comment by rdsr** [comment]
Most likely. I'll try this again and check.
