### ISSUE TITLE
Update HiveConf Variable Names

### ISSUE THREAD

**Issue by joy91227** [apache/iceberg#10577]
### Apache Iceberg version

1.5.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

In Hive 4.0.0 many HiveConf.ConfVar variables have changed names. See: https://github.com/apache/hive/commit/b33b3d3454cc9c65a1879c68679f33f207f21c0e

**Comment by nastra** [comment]
@joy91227 the Hive 4 Iceberg support is maintained by the Hive community and so this was already addressed by the linked commit. There's nothing to be done on the Iceberg side for this, so I'll go ahead and close this
