### ISSUE TITLE
ORC support broken for Java 8

### ISSUE THREAD

**Issue by snazy** [apache/iceberg#10598]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

Code in ORC support references `java.lang.Math#floorMod(long, int)` and `java.lang.Math#floorDiv(long, int)`, which are *not* available in Java 8.

**Comment by Fokko** [comment]
Thanks for raising this @snazy. Digging into it:
```
➜  orc git:(main) grep -R "floorDiv" . | grep -v "Test"
./java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java:      long longValue = Math.floorDiv(millis, 1000);
./java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java:      double result = Math.floorDiv(ts.getTime(), 1000);
./java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java:      long seconds = Math.floorDiv(timestampColVector.time[elementNum], 1000);
./java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java:    return Instant.ofEpochSecond(Math.floorDiv(vector.time[element], 1000),
➜  orc git:(main) grep -R "floorMod" . | grep -v "Test"
./java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java:            (int) Math.floorMod(millis, 1000) * 1_000_000;
./java/core/src/java/org/apache/orc/impl/StringHashTableDictionary.java:    return Math.floorMod(hash, capacity);
```

Looking at the code, it has been in there for 5 years, [introduced in `ORC-578`](https://issues.apache.org/jira/browse/ORC-578): https://github.com/apache/orc/blame/517776f3e7f8745c365cc0fc69d7cabbdc34d714/java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java#L627

What's happening here is that the compiler applies implicit cast type from `int ➜ long` before passing it in `floorMod(long, long)`. The ORC 1.x branch is tested against Java 8, and the new 2.x release is Java 17+, so I think we're good here.
