### ISSUE TITLE
Possible heap data corruption of `org.apache.iceberg.rest.auth.OAuth2Util.AuthSession#headers`

### ISSUE THREAD

**Issue by snazy** [apache/iceberg#10591]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

The operation on the volatile `org.apache.iceberg.rest.auth.OAuth2Util.AuthSession#headers` is not atomic.

**Comment by adutra** [comment]
FYI the operation in question is this:

https://github.com/apache/iceberg/blob/3d3e565a793280f2925114ada9d853ea304d6b9b/core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java#L581
