### ISSUE TITLE
Question about `day` transform result type 

### ISSUE THREAD

**Issue by lurnagao-dahua** [apache/iceberg#10616]
### Apache Iceberg version

1.5.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

Hi!
The transform name 'day' result type is 'int' in spec.md and [partition-transforms](https://iceberg.apache.org/spec/#partition-transforms)
and the code in Days.java is:
` @Override
  public Type getResultType(Type sourceType) {
    return Types.DateType.get();
  }`
So may I ask if the document was written incorrectly and the actual return type is date?

**Comment by ajantha-bhat** [comment]
Good catch. I think the spec is correct. 
Now if we change it the schema will be different from old client and new client (compatibility issue).

I think it has to be handled as per 2.0 release. 
Let us wait for others opinion.

**Comment by Fokko** [comment]
Hey @lurnagao-dahua Thanks for raising this, and @ajantha-bhat for jumping in here. This was discussed earlier in https://github.com/apache/iceberg/issues/10159 and points to a comment in https://github.com/apache/iceberg/issues/279#issuecomment-519620975.

Some historical context:

- `int -> date` in https://github.com/apache/iceberg/pull/447/
- `date -> int` in https://github.com/apache/iceberg/pull/5980/
- Discussed earlier this year in https://github.com/apache/iceberg/pull/9345/

So the logical type is a `date`, but the physical type is still an `int32`, maybe we should make that more explicit? It seems to cause a lot of confusion. Looking forward to hearing what others think.

**Comment by ajantha-bhat** [comment]
@Fokko: Thanks for pointing out the previous discussions. I was certain that important topics like this had been covered before, but I couldn't find the relevant threads. I appreciate you sharing them. It's great to know that you bumped into this during the Python implementation 👍

**Comment by lurnagao-dahua** [comment]
Thank you everyone!
