### ISSUE TITLE
Add DataFile rewrite support to compact small data files

### ISSUE THREAD

**Issue by jerryshao** [apache/iceberg#1061]
Iceberg will potentially generate large amount of small data files, especially when using streaming mode (Structured Streaming Write/Flink Sink). So we should have a mechanism to compact the small data files into large ones. 

In Iceberg we already have `RewriteManifestsAction` and `RemoveOrphanFilesAction`, maybe we could add a new action to compact the data files.

Any thoughts on it? @rdblue @aokolnychyi

**Comment by rdblue** [comment]
Sounds great! I'd love to see more actions to maintain table data and metadata.

**Comment by rdsr** [comment]
@jerryshao is this done?

**Comment by zhangdove** [comment]
If understood correctly, I think this issue has been solved by  [1083](https://github.com/apache/iceberg/pull/1083). I also did some local testing of the module. @rdsr
