### ISSUE TITLE
Read manifest file Permission denied

### ISSUE THREAD

**Issue by lurnagao-dahua** [apache/iceberg#10634]
### Apache Iceberg version

1.4.3

### Query engine

Hive3.1.3

### Please describe the bug 🐞

`A user` execution query `select * from iceberg_tb`

and the error log is :
`Caused by: org.apache.iceberg.exceptions.RuntimeIOException: Failed to open input stream for file: hdfs://hdfsHACluster/user/hive/warehouse/yc_iceberg.db/iceberg_tb/metadata/a72f8bf5-5d93-405b-953e-a8fed8bfa6b6-m0.avro
at org.apache.hive.service.cli.operation.SQLOperation.getNextRowSet(SQLOperation.java:507)
...
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=B, access=EXECUTE, inode="/user/hive/warehouse":hadoop:supergroup:drwx------`

Strangely, the error message is that user B does not have permission.

Is it possible that it is related to ThreadPools.WORKER_POOL?

**Comment by lurnagao-dahua** [comment]
Hi，Can you take a look at this issue for me! @nastra 
Thank you very much

**Comment by wangyinsheng** [comment]
Could you provide more infomation? hive version and how do you config it to enable iceberg support

**Comment by lurnagao-dahua** [comment]
> Could you provide more infomation? hive version and how do you config it to enable iceberg support

The hive version is 3.1.3
I put `iceberg-hive-runtime-1.4.3.jar`  into $HIVE_HOME/lib
and it This is a very occasional problem and when id restart hiveserver2 it will be normal

**Comment by wangyinsheng** [comment]
How do you set accessing user , and have you ever switch user?

**Comment by lurnagao-dahua** [comment]
> How do you set accessing user , and have you ever switch user?

jdbc use keytab, and i always use the same user

if i create new table, it will show correct owner on table properties.

**Comment by lurnagao-dahua** [comment]
> How do you set accessing user , and have you ever switch user?

when i restart hiveserver2, it will be normal, doesit feel like a caching issue?

**Comment by wangyinsheng** [comment]
This may be a issue of client pool in hive catalog. 
https://github.com/apache/iceberg/blob/24d26b6a35a1287531e72357691d9dbd3d7f79bd/hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java#L71C45-L71C60

**Comment by wangyinsheng** [comment]
you can  try to disable cache,  set `iceberg.catalog.default_iceberg.client.pool.cache.eviction-interval-ms=0`

**Comment by lurnagao-dahua** [comment]
> This may be a issue of client pool in hive catalog. https://github.com/apache/iceberg/blob/24d26b6a35a1287531e72357691d9dbd3d7f79bd/hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java#L71C45-L71C60

Hi, may I ask if reading the manifest file will use CachedClientPool?

**Comment by lurnagao-dahua** [comment]
> you can try to disable cache, set `iceberg.catalog.default_iceberg.client.pool.cache.eviction-interval-ms=0`

May I ask if this configuration is available in hive-site.xml?

**Comment by lurnagao-dahua** [comment]
> sorry, I confuse the problem. `CachedClientPool` is used for connection to hms, not hdfs file.

if i query another table(All of them were created by me), it will be normal
If there is a cache, it seems to be related to the path?

**Comment by lurnagao-dahua** [comment]
when i roll back snapshot before a72f8bf5-5d93-405b-953e-a8fed8bfa6b6-m0.avro generation, it can be queried

**Comment by lurnagao-dahua** [comment]
I find the ugi with a72f8bf5-5d93-405b-953e-a8fed8bfa6b6-m0.avro is B and other file is A

**Comment by lurnagao-dahua** [comment]
> sorry, I confuse the problem. `CachedClientPool` is used for connection to hms, not hdfs file.


Hi, I find the ugi with a72f8bf5-5d93-405b-953e-a8fed8bfa6b6-m0.avro is B and other file is A
