### ISSUE TITLE
Missing Artifacts for Flink v1.19

### ISSUE THREAD

**Issue by ymshinde** [apache/iceberg#10638]
### Query engine

Flink v1.19

### Question

Could not locate the artifacts for Flink v1.19 at the following link:
https://repo1.maven.org/maven2/org/apache/iceberg/

Do you have any suggestions on how I might find these artifacts?

**Comment by ajantha-bhat** [comment]
Iceberg doesn't support Flink 1.19 with the last release (1.5.x). 
Only the upcoming release (1.6.0) will have it. 1.6.0 will be released in a week or two.
