### ISSUE TITLE
[Build] Gradle 8.8 crashed on MacOS 11.x and before

### ISSUE THREAD

**Issue by hantangwangd** [apache/iceberg#10636]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

In PR #8486 we have upgrade to gradle 8.8. However, after fetch and rebase the change, my local branch always fails to build because of crashing JVM. After checking the gradle community, I found it's a known issue in version 8.8:

https://github.com/gradle/gradle/issues/29476

This issue would lead in JVM crash when executing `./gradlew build` on MacOS 11.x and before, and it was fixed in `8.9-rc-1` in the following PR. So should we consider solving this problem as well?

https://github.com/gradle/gradle/pull/29514

**Comment by nastra** [comment]
Hey @hantangwangd thanks for reporting this issue. As a workaround you could switch back to Gradle 8.7 locally in https://github.com/apache/iceberg/blob/565352d12be30735d9224f894099defd6cd45b09/gradle/wrapper/gradle-wrapper.properties#L4 to make the build work for you.

We might want to consider switching back to Gradle 8.7 in Iceberg until 8.9 is out.

**Comment by hantangwangd** [comment]
@nastra OK, got it. Thanks for the information.
