### ISSUE TITLE
Unable to get field from serde: org.apache.iceberg.mr.hive.HiveIcebergSerDe

### ISSUE THREAD

**Issue by Sourabh-Dilraj** [apache/iceberg#10633]
### Query engine

HIve

### Question

I am using HIve branch-4.0.0-alpha-1 , I have placed iceberg-hive-runtime-1.6.0-SNAPSHOT.jar jar in hive/lib/ dir.
Also made all the required configurations, but when I am trying to create an external table SORTED by iceberg using hive, it is throwing :
org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException
ERROR : DDLTask failed, DDL Operation: class org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation
ERROR : FAILED: Execution Error, return code 40000 from org.apache.hadoop.hive.ql.ddl.DDLTask. java.lang.NullPointerException
INFO  : Completed executing command(queryId=hive_20240705113346_0195bea3-cf74-40fb-b965-3fc71b222d60); Time taken: 0.013 seconds
Error: Error while compiling statement: FAILED: Execution Error, return code 40000 from org.apache.hadoop.hive.ql.ddl.DDLTask. java.lang.NullPointerException (state=08S01,code=40000)

**Comment by pvary** [comment]
Hive 4 uses its own embedded Iceberg. You don't need to add additional jars to the lib.

**Comment by pvary** [comment]
Also this is most probably a Hive related questions, so better asked on the Hive user list.
