### ISSUE TITLE
Does iceberg have a plan to support Multi-Statement and Multi-Table Transactions ? 

### ISSUE THREAD

**Issue by yiguolei** [apache/iceberg#1074]

**Comment by rdblue** [comment]
This should be possible, but as far as I know, no processing engines support it. Until then, it doesn't make much sense to worry about it for Iceberg.

**Comment by yiguolei** [comment]
Why does it relate with processing engines?

**Comment by rdblue** [comment]
The primary way to work with Iceberg tables is through a processing engine like Presto or Spark. Without cross-table transaction support in those, there would be no way to use it besides going directly to the API.

**Comment by lirui-apache** [comment]
I think this might be a useful feature. Suppose I want to atomically add columns to two iceberg tables, is there a way to do this with current API?

**Comment by ajantha-bhat** [comment]
@lirui-apache : Currently, With the Nessie catalog it is possible to achieve multi-table transactions via branching and merging.  https://projectnessie.org/features/transactions/#cross-table-transactions

Recently, the community is working on Catalog level transactions to support multi-table transactions
https://github.com/apache/iceberg/pull/6948

**Comment by lirui-apache** [comment]
@ajantha-bhat thanks for the pointers. Our metadata is stored in HMS and I don't think we can migrate off any time soon. I'm not sure if this can be achieved with HiveCatalog, since IIRC the HMS doesn't support altering multi tables in a single transaction.

**Comment by ajantha-bhat** [comment]
Status can be tracked from https://github.com/apache/iceberg/projects/30

**Comment by HemantMarve** [comment]
Hi @rdblue , Is there any engine starts supporting Multi-Table transactions?
