### ISSUE TITLE
Remaining Kafka Connect sink tasks

### ISSUE THREAD

**Issue by bryanck** [apache/iceberg#10740]
### Feature Request / Improvement

This is a placeholder ticket, once more specific issues are opened we can close this.

We need to submit the following remaining tasks to complete the initial Kafka Connect sink submission:
- Building of the runtime distributions
- Integration tests
- Docs and/or READMEs
- SMT subproject
- Delta writer and CDC support

**Comment by nk1506** [comment]
Hi @bryanck , 
I am interested in contributing to Kafka-Connect tasks. Please let me know if there are any opportunities for me to contribute.

**Comment by ajantha-bhat** [comment]
I think it is better to have individual issue trackers for each feature (with `KAFAKACONNECT` label). So, we can close them when each task is completed.

**Comment by bryanck** [comment]
Thanks @nk1506 that would be great! There definitely are some opportunities. This is just a placeholder issue to note the big ticket items, I'll create individual tasks soon for some more specific tasks and you can see if you want to pick any of those up.

**Comment by nk1506** [comment]
Thanks @bryanck , By any chance are we planning to consider adding `upsert` support here too? I saw few thread on the slack where there was mixed feedback about `upsert` performances.

**Comment by bryanck** [comment]
That's the hope. It will likely involve a discussion with the community first, as there are some performance considerations.

**Comment by bryanck** [comment]
I added individual issues and tagged them with `KAFKACONNECT`, so I'm going to close this.
