### ISSUE TITLE
Site - latest release not showing 1.6.0

### ISSUE THREAD

**Issue by raphaelauv** [apache/iceberg#10803]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

![image](https://github.com/user-attachments/assets/49f793ee-ba0a-4387-9cce-5b90bdf27d1c)

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by Fokko** [comment]
@raphaelauv Thanks for raising this 👍 

@jbonofre  A couple of steps that we need to take:

It looks like we need to do a couple more steps:

- docs: we need to create a 1.6.0 directory on https://github.com/apache/iceberg/tree/docs, and copy the content from the `docs/*` from the 1.6.0 release tag in there.
- javadoc: we need to create a 1.6.0 directory on https://github.com/apache/iceberg/tree/javadoc from the release tag.

I noticed that the release `tar.gz` does not include the docs. It might be good to make that part of the release. Also, we need to update the docs on https://github.com/apache/iceberg/tree/main/site#release-process, it looks like that the release process is still undecided. cc @bitsondatadev

**Comment by jbonofre** [comment]
Sorry, my bad, I forgot to publish it. I will do that.

**Comment by jbonofre** [comment]
This PR (https://github.com/apache/iceberg/pull/10783) should have updated the latest version on the website. Let me check.

**Comment by Fokko** [comment]
@raphaelauv @jbonofre 

The issue has been resolved: https://iceberg.apache.org/releases/

Thanks for the help here JB 👍
