### ISSUE TITLE
Add docker demo for iceberg starters

### ISSUE THREAD

**Issue by Jiayi-Liao** [apache/iceberg#1081]
As far as I know, currently, users can only work with iceberg on an existing hadoop / hdfs / hive / spark cluster or deploying a new one. It's not very friendly to starters, especially those who want to know more about iceberg but don't have an available environment to make iceberg work well. I believe there're many users like me in situations like:

* users that cannot try iceberg because of limitations like (spark / hdfs / hive version).
* users that work with other frameworks (like Flink), want to know more about iceberg.
* users that want to demonstrate the capability of Iceberg to other potential users.

I'm proposing this because I'm exploring the data lake related frameworks right now and Hudi already has the [Docker Demo](https://hudi.apache.org/docs/docker_demo.html) and it helps me to demonstrate the demo to other members in the same team.

I believe this also will do a lot of help to starters in Iceberg, and I can work on this if committers think this's worth doing.

**Comment by tonyqus** [comment]
+1

**Comment by rdblue** [comment]
I think it would be great to have an easy demo. I can help review if you want to create one!

**Comment by Jiayi-Liao** [comment]
@rdblue I think the initial version is almost done and I'd like to discuss more details. Let's move the discussion to https://github.com/apache/iceberg/pull/1100. Thanks for your time!
