### ISSUE TITLE
Error referring PartitionSpec to the google.common class library

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#1082]
import org.apache.iceberg.relocated.com.google.common.base.Preconditions;
import org.apache.iceberg.relocated.com.google.common.collect.ImmutableList;
import org.apache.iceberg.relocated.com.google.common.collect.ListMultimap;
import org.apache.iceberg.relocated.com.google.common.collect.Lists;
import org.apache.iceberg.relocated.com.google.common.collect.Maps;
import org.apache.iceberg.relocated.com.google.common.collect.Multimaps;
import org.apache.iceberg.relocated.com.google.common.collect.Sets;
@rdblue

**Comment by rdblue** [comment]
Can you be more clear? What is the problem?

**Comment by felixYyu** [comment]
<img width="950" alt="微信图片_20200602092626" src="https://user-images.githubusercontent.com/3785228/83469993-a5717980-a4b3-11ea-9240-ed9461f7e644.png">

referring google.common class is ok? GenericRecord.java and Bucket.java have the same problem.

**Comment by felixYyu** [comment]
Reference the Google class in PartitionSpec.java file via "import org.apache.iceberg.relocated.com.google.common.base.Preconditions",GenericRecord.java and Bucket.java have the same problem,Isn't that the right way "import com.google.common.base.Objects".Can you explain it for me,thanks.

**Comment by rdblue** [comment]
#1068 added a shaded guava module to avoid classpath conflicts in other projects, so this is expected.
