### ISSUE TITLE
Remove Scala from the build

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#1088]
[`SparkTableUtil`](https://github.com/apache/iceberg/blob/master/spark/src/main/scala/org/apache/iceberg/spark/SparkTableUtil.scala) was written in Scala so that it could use case classes, but this over-complicates the build and ties Iceberg to a Scala version (2.11 or 2.12). We should rewrite these methods in Java and remove Scala from the build completely.

**Comment by raptond** [comment]
Let me take care of this, if no one is looking into this. Thanks.

**Comment by aokolnychyi** [comment]
@raptond, I think we can use some of the work we did in Spark actions as an example.

**Comment by rdblue** [comment]
This was completed in #1126. Thanks @raptond!
