### ISSUE TITLE
Ensure that the site is published when the spec is being updated

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#10900]
### Feature Request / Improvement

To ensure that the website reflects the latest version of the spec.

### Query engine

None

### Willingness to contribute

- [ ] I can contribute this improvement/feature independently
- [ ] I would be willing to contribute this improvement/feature with guidance from the Iceberg community
- [ ] I cannot contribute this improvement/feature at this time

**Comment by manuzhang** [comment]
Isn't this already achieved https://github.com/apache/iceberg/actions/workflows/site-ci.yml?

**Comment by Fokko** [comment]
@manuzhang Yes, I was unsure about this, but it looks like it indeed. I can see the trademarks on the site 👍
