### ISSUE TITLE
Spark can't read its own write after another one commits data to the iceberg table

### ISSUE THREAD

**Issue by chenzl25** [apache/iceberg#10919]
### Apache Iceberg version

1.5.2

### Query engine

Spark

### Please describe the bug 🐞

How to reproduce:
- Spark-sql runs `CREATE TABLE demo.demo_db.t_bug(a int) TBLPROPERTIES ('format-version'='2')`
- Spark-sql runs `insert into demo.demo_db.t_bug values (1)`
- Another SDK ([icelake](https://github.com/icelake-io/icelake)): `insert into demo.demo_db.t_bug values (2)`
- After that, the weird thing happens
- `select * from demo.demo_db.t_bug.files` told me there are 2 parquet files, but when I run `select * from demo.demo_db.t_bug` only 1 row returns. And I run 2 time travel queries, you can see both snapshots return 1 row. The first time travel query result with id `6579104674932036030` is expected, but the second one with id `6579104674932036031` is unexpected
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/5c8718bc-3c47-480b-b9f8-0b8ee3e7c804">

- BTW, some query engines like clickhouse and duckdb can read 2 rows, so I think something wrong in spark.

I also include the table `t_bug` metadata and data directory here for those who are interested in this issue.

[t_bug.zip](https://github.com/user-attachments/files/16588151/t_bug.zip)

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [X] I cannot contribute a fix for this bug at this time

**Comment by lurnagao-dahua** [comment]
What is the result of executing query using SparkSQL:
`select * from demo.demo_db.t_bug`

**Comment by chenzl25** [comment]
Never mind. I found it is a bug of `icelake`. It doesn't follow the iceberg spec. https://github.com/icelake-io/icelake/pull/280 Let me close this issue.
