### ISSUE TITLE
Add HadoopCatalog example to create/load tables in the Iceberg User docs

### ISSUE THREAD

**Issue by hzfanxinxin** [apache/iceberg#1093]
In the Spark API Quickstart(http://iceberg.apache.org/api-quickstart/) and Java API Quickstart(http://iceberg.apache.org/java-api-quickstart/)，there are only HiveCatalog and HadoopTables example to create a table，maybe we should also add HadoopCatalog example.

Any thoughts on it? @rdblue

**Comment by rdblue** [comment]
Sounds good to me! Would you like to open a pull request?

**Comment by hzfanxinxin** [comment]
Thanks for quick response. Yes, i will open a pull request to add HadoopCatalog example。

**Comment by rdblue** [comment]
This was added in #1095. I'll close the issue.
