### ISSUE TITLE
Remove Hadoop 2

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#10940]
### Feature Request / Improvement

Hadoop 2 does not support Java 11+ https://github.com/apache/iceberg/pull/10518#issuecomment-2285844068

@steveloughran took a stab at it here: https://github.com/apache/iceberg/pull/10932#issuecomment-2286877905 but he's open for someone else to take it over.

### Query engine

Hive

### Willingness to contribute

- [ ] I can contribute this improvement/feature independently
- [ ] I would be willing to contribute this improvement/feature with guidance from the Iceberg community
- [X] I cannot contribute this improvement/feature at this time

**Comment by steveloughran** [comment]
The troublespot is not remove hadoop 2: it's "remove hive2 profile and testing"

**Comment by Fokko** [comment]
This has been done a while ago :)
