### ISSUE TITLE
Data duplication may occur when flink checkpoint fails

### ISSUE THREAD

**Issue by klion26** [apache/iceberg#11008]
### Apache Iceberg version

1.4.3

### Query engine

Flink

### Please describe the bug 🐞

Currently, the Flink sink connector logic is
1. The writer receives checkpoint barrier and flush data and sends `WriteResult` to the committer operator
2. The committer operator finalizes all `WriteResult` received from current checkpoint interval
3. commit to the table when the checkpoint is completed.

if we fail in step 2 before the finalize process[1], then data written in checkpoint i and checkpoint i+1 will squashed into one commit, this will result in the "loss" of some eq-delete data.

for example,
update for primary key A in checkpoint i this will translate to: `eq-delete A` + `insert A`,
update for primary key A in checkpoint i + 1, this will translate to `eq-delete A` + `insert A`

after the checkpoint i fails, we'll commit to the table with `eq-delete A` + `insert A` + `eq-delete A` + `insert A` this second `eq-delete A` will be "lost" when we read from the table.

[1] https://github.com/apache/iceberg/blob/9aa354d2224eb78c19c773227693df117954312b/flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java#L215

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by pvary** [comment]
@klion26: Could you please check #10526? Is this a duplicate of that issue?
Thanks,
Peter

**Comment by klion26** [comment]
@pvary thanks for the information, yes, this is a duplicate of #10526 , will close this issue.
