### ISSUE TITLE
[Question] Is there a way to add a commit message to Snapshot?

### ISSUE THREAD

**Issue by vanliu-tx** [apache/iceberg#1106]
In our use case, we are reading messages from Kafka, and periodic writing to iceberg tables. Now we need a very complex logic to keep the exactly-once semantic, as we have to store the last Kafka message offset, which has been committed to iceberg table, in external storage, and make this operation atomic with iceberg table commit. 

If there is a way to add a commit message to a snapshot, I can put the last Kafka message offset to be a part of this commit message, and it is guaranteed to be atomic with table commit. So in the failure recovering process, my life would be much easier, I only need to read the commit messages in some snapshots and find out the consumed Kafka message offsets, then start reading Kafka messages from the next offset.

**Comment by shardulm94** [comment]
You can use [`SnapshotUpdate#set()`](https://github.com/apache/iceberg/blob/736c68da7c0c8558a06d2d30a78940172653ab86/api/src/main/java/org/apache/iceberg/SnapshotUpdate.java#L38) to set key value properties for a snapshot, these properties would then be accessible using [`Snapshot#summary()`](https://github.com/apache/iceberg/blob/736c68da7c0c8558a06d2d30a78940172653ab86/api/src/main/java/org/apache/iceberg/Snapshot.java#L101)

**Comment by vanliu-tx** [comment]
Thank you, @shardulm94 ! That works for me.
