### ISSUE TITLE
Flink: multiple sinks for the different iceberg tables in the same job？

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#11074]
### Query engine

flink 1.15
iceberg 1.2.1

### Question

can we use one source sinks to different tables in one task?  such as 
<img width="392" alt="image" src="https://github.com/user-attachments/assets/67e529b1-7294-442d-a739-fba8d11c7559">
we found data is missed up between two table when IcebergFilesCommitter initializing, such as table A has a datafile reference  in B, and table B has a datafile reference  in A

**Comment by pvary** [comment]
I don't think this should happen. Could you please create a small unit test to reproduce?

Thanks, Peter

**Comment by chenwyi2** [comment]
yes that's no iceberg problem, but with our platform, thx
