### ISSUE TITLE
execute sql "select partition from dbxx.tbxx.partitons" on table which has never had partition field get error❌

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg#11105]
### Apache Iceberg version

1.4.3

### Query engine

Spark

### Please describe the bug 🐞

Brief process for reproduction:
```
CREATE TABLE db11.t11 (id INT,name STRING)USING iceberg;
select partiton form db11.t11.partitions;❌
select file_count form db11.t11.partitions;✅
```
![image](https://github.com/user-attachments/assets/aa1e6744-5d8b-4e26-8784-27590b4f3e8f)

**I tend to believe that the two SQL statements above should yield the same result.** In other words,  sql `select partiton form db11.t11.partitions` should not throw exception in the situation above.

**Comment by manuzhang** [comment]
As documented at https://iceberg.apache.org/docs/nightly/spark-queries/#partitions

> For unpartitioned tables, the partitions table will not contain the partition and spec_id fields.
