### ISSUE TITLE
what does value of partition mean in table dbxxx.tbxxx.partitions?

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg#11125]
### Query engine

spark sql
iceberg=1.4.3

### Question

From the below picture, it can be seen that the value of `hour(time)` is displayed as 473356 in the dbxx.tbxx.sections table. How can I understand the relationship between the two value??     How to get 473356 from 12
![image](https://github.com/user-attachments/assets/309be609-a5da-4d97-ba7b-4b6bda39e939)

**Comment by amogh-jahagirdar** [comment]
Hey @madeirak you can check out the partition transform portion of the spec to determine how these values are obtained, https://iceberg.apache.org/spec/#partition-transforms.

For `hours`, the transform extracts a timestamp hour, as hours from 1970-01-01 00:00:00.
So 473356 means that those timestamps are 473356 hours after 1970-01-01 00:00:00.

**Comment by amogh-jahagirdar** [comment]
I'm going to go ahead and close, feel free to reopen if you have any more questions!
