### ISSUE TITLE
REST Catalog pagination can throw IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rcjverhoef** [apache/iceberg#11142]
### Apache Iceberg version

1.6.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

The calls to do pagination of namespaces, tables and views throws unexpected exceptions. 

For example, if you have 10 namespaces and you request a page of size 100: the current code blows up. The problem is that the logic does use `List.subList` with a start and end index. The end-index is calculate as the start + pagesize. But poor java doesn't like it if end-index is bigger than the list size.

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by rcjverhoef** [comment]
To be more specific, this is the offending code:

*Namespaces*:
https://github.com/rcjverhoef/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java#L134-L136

*Tables*:
https://github.com/rcjverhoef/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java#L208-L210

*Views*:
https://github.com/rcjverhoef/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java#L453-L455

**Comment by munendrasn** [comment]
@rcjverhoef Is this good to be closed as the PR is merged? cc @amogh-jahagirdar

**Comment by rcjverhoef** [comment]
yes it! let me do so.
