### ISSUE TITLE
Proposal: add Variant type to iceberg

### ISSUE THREAD

**Issue by aihuaxu** [apache/iceberg#11178]
### Feature Request / Improvement

As discussed in the mailing list, and [described in this doc](https://docs.google.com/document/d/1QjhpG_SVNPZh3anFcpicMQx90ebwjL7rmzFYfUP89Iw/edit), I'd like to add Variant type to Iceberg.

We will adopt the Spark Variant spec and move the spec to Parquet - see [discussion](https://lists.apache.org/thread/0k5oj3mn0049fcxoxm3gx3d7r28gw4rj). There are some ongoing discussion on how Parquet will adopt the spec and implementation - seed the [doc]( https://docs.google.com/document/d/1guEzBQjzOEEZvvibeZjNraKmZHWtxQR95O_DvtZU0xw/edit), but from Iceberg side, I would like to start the implementation assuming the spec is available and make the final changes when the spec is finalized.

### Query engine

None

### Willingness to contribute

- [X] I can contribute this improvement/feature independently
- [ ] I would be willing to contribute this improvement/feature with guidance from the Iceberg community
- [ ] I cannot contribute this improvement/feature at this time

**Comment by manuzhang** [comment]
Since this is a major feature, it might be better labeled as `proposal` following https://iceberg.apache.org/contribute/#what-is-an-improvement-proposal
