### ISSUE TITLE
Improve Memory Use in SparkScanBuilder

### ISSUE THREAD

**Issue by trohwer** [apache/iceberg#11245]
### Feature Request / Improvement

When using Iceberg 1.6.1 with Spark 3.5.1, I ran into OutOfMemory error with a statement like
"select max(some_column) from some_table" . Even
"explain select max(some_column) from some_table" ran into an OutOfMemory error.

It turned out that in
org.apache.iceberg.spark.source.SparkScanBuilder
the retained size of
      List<FileScanTask> tasks = ImmutableList.copyOf(fileScanTasks);
can get rather large.

As an example, in one case with 560 FileScanTasks, the retained size of the whole array was about 30MB and the retained size of the first object about 0.5MB. I.e. per FileScanTask Object you would have a memory use of around (30MB-0.5MB)/559 approx.= 50kb in that case. That does not scale well with many files (say 10^6), as this memory has to reside in the Spark driver.

After I changed the code to directly use the Iterator fileScanTasks in the following for loop
for (FileScanTask task : tasks) {...
the statement (and the explain) finished quickly without running into an OutOfMemory error.

I can't see an obvious reason that the content of the iterator is copied into a list first instead of being used directly.

### Query engine

Spark

### Willingness to contribute

- [ ] I can contribute this improvement/feature independently
- [X] I would be willing to contribute this improvement/feature with guidance from the Iceberg community
- [ ] I cannot contribute this improvement/feature at this time

**Comment by huaxingao** [comment]
@trohwer Thanks for reporting this. `fileScanTasks` should be used directly. I will have a PR to fix this.

**Comment by huaxingao** [comment]
cc @szehon-ho Could you approve this for upstream?

**Comment by trohwer** [comment]
Thanks @huaxingao for creating a PR.

**Comment by nastra** [comment]
fixed by https://github.com/apache/iceberg/pull/11319
