### ISSUE TITLE
Spark, Flink: Test failures after updating JUnit 5.10 to 5.11

### ISSUE THREAD

**Issue by tomtongue** [apache/iceberg#11296]
### Apache Iceberg version

main (development)

### Query engine

Spark

## Issue
Many tests in Spark/Flink inherited from each `TestBase` class fail after updating the JUnit version from 5.10 to 5.11. Specifically, if a test inherited from a `TestBase` or a specific test base class has the `static` method with annotation such as `@BeforeAll`/`@AfterAll` or `@Parameters`, the test failure due to the following search semantics change:

https://github.com/junit-team/junit5/wiki/Upgrading-to-JUnit-5.11
> This addresses several bugs and results in the following changes in behavior.
>  * Fields no longer hide fields from super types.
>       * This applies to non-static as well as static fields (@TempDir, @RegisterExtension, etc.).
>  * Methods no longer hide methods from super types unless a given method literally overrides the other method.
>       *  This applies to non-static as well as static methods (@BeforeAll, @BeforeEach, @Test, etc.).
>  * Extensions and TestEngines may have to revise their search algorithms for fields and methods.
>       * See case study in [#3774](https://github.com/junit-team/junit5/issues/3774) for an example.

## Details
The version updates causes the following behavior changes:

Assuming the following class structure, the actual tests are in the `TestA` class.

```
abstract class TestBase (including @BeforeAll)
    <- abstract class Feature1TestBase (including @BeforeAll)
        <-  class TestA
```

When you run the tests in `TestA`, 
* In JUnit 5.11.1, a static method with `@BeforeAll` in the `TestBase` class is called, then the same name static method with `@BeforeAll` in the `Feature1TestBase` class is called.
* In JUnit 5.10, only a static method with `@BeforeAll` in the `Feature1TestBase` class is called, the static method in the `TestBase` class is NOT called.

The below shows more details:

### Code

`TestBase`:

```java
// TestBase
import org.junit.jupiter.api.BeforeAll;

public abstract class TestBase {
    @BeforeAll
    public static void beforeAll() {
        System.out.println("Run beforeAll in TestBase.");
    }

    public void testMethod() {
        System.out.println("Run testMethod in TestBase.");
    }
}
```

`Feature1TestBase`:

```java
import org.junit.jupiter.api.BeforeAll;

public abstract class Feature1TestBase extends TestBase {
    @BeforeAll
    public static void beforeAll() {
        System.out.println("Run beforeAll in Feature1TestBase.");
    }
}
```

`TestA`:

```java
import org.junit.jupiter.api.Test;

public class TestA extends ConcreteTestBase {
    @Test
    public void runTestA1() {
        testMethod();
    }
}
```

### Output

JUnit 5.11.1:

```java
Run beforeAll in TestBase.
Run beforeAll in Feature1TestBase.
Run testMethod in TestBase.
```

JUnit 5.10.5:

```
Run beforeAll in Feature1TestBase.
Run testMethod in TestBase.
```

### Progress
- [x] iceberg-core
- [x] iceberg-mr
- [ ] iceberg-spark
- [ ] iceberg-flink

**Comment by tomtongue** [comment]
`iceberg-core` and `iceberg-mr` also have this issue, however created the PR (https://github.com/apache/iceberg/pull/11262) to fix this. 
For Spark and Flink, there are a lot of tests required to be fixed, so add `junit.platform.reflection.search.useLegacySemantics` and will make all test cases in Spark and Flink compatible with JUnit 5.11

**Comment by tomtongue** [comment]
This PR (https://github.com/apache/iceberg/pull/11263) for bumping the JUnit version is also affected by this search semantics change.

**Comment by nastra** [comment]
fixed by https://github.com/apache/iceberg/pull/11262
