### ISSUE TITLE
Question:  Does it possible `Concurrent write operations` over s3?

### ISSUE THREAD

**Issue by GrigorievNick** [apache/iceberg#1131]
Hi ICBQm community please help me to understand how icbq grant commits consistency on s3 for concurrent writes.
From [icbq documentation ](https://iceberg.apache.org/reliability/#concurrent-write-operations)
```
Concurrent write operations
Iceberg supports multiple concurrent writes using optimistic concurrency.

Each writer assumes that no other writers are operating and writes out new table metadata for an operation. Then, the writer attempts to commit by atomically swapping the new table metadata file for the existing metadata file.

If the atomic swap fails because another writer has committed, the failed writer retries by writing a new metadata tree based on the new current table state.
```
But Lest image situation:
User one writes data to the table and then commits a new snapshot. But commit where? To **file**(Valid snapshots in an Iceberg table are stored the table metadata file) **on s3.**
Because of eventually consistency of s3, the Second User writes new data and going to commit.
Before commit, the user checks iceberg table metadata file for snapshots to do an optimistic lock, but S3 is eventually consistent. So the user doesn't see a new Iceberg table metadata file created by the user one and just overwrite this file on s3. 

This situation leads to the loss of all changes done by the User one. Am I right? or I miss something?
 P.S. As far as I understand delta-lake does not support this feature over s3, just because reason I describe above.

**Comment by GrigorievNick** [comment]
Look like I find an answer. But in very [another place]( https://iceberg.apache.org/api-quickstart/),
```
Warning

Hadoop tables shouldn’t be used with file systems that do not support atomic rename. Iceberg relies on rename to synchronize concurrent commits for directory tables.
```
So`Concurrent writes operations` only supported with Hive metadata catalog.

**Comment by edgarRd** [comment]
Since Hive Catalog requires Locking support from the Hive Metastore, you could implement your own Catalog based on https://iceberg.apache.org/custom-catalog/ and implement your own distributed locking mechanism.

**Comment by rdblue** [comment]
That's right, concurrent writes are supported through the Hive catalog implementation. You can customize this as @edgarRd pointed out.
