### ISSUE TITLE
Arrow - Removed unused vectorized code readers

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#11370]
### Apache Iceberg version

1.6.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

The following functions and their classes are no longer in use and we need to remove them

[IntBackedDecimalReader](https://github.com/apache/iceberg/blob/012386261841c1eb50cdc01d13ae146ad40ae011/arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java#L847)
[LongBackedDecimalReader](
https://github.com/apache/iceberg/blob/012386261841c1eb50cdc01d13ae146ad40ae011/arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java#L851)
[FixedLengthDecimalReader](https://github.com/apache/iceberg/blob/012386261841c1eb50cdc01d13ae146ad40ae011/arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java#L835)

There are no tests covering any of their behaviors and their parent callers were deprecated and removed in 1.4.0

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by dramaticlly** [comment]
closed by #11276

**Comment by RussellSpitzer** [comment]
I think you are correct, @wypoon Can you confirm?

**Comment by wypoon** [comment]
@RussellSpitzer yes, this has already been done by https://github.com/apache/iceberg/pull/11276. There is also https://github.com/apache/iceberg/pull/11292 for additional dead code that was made public and so may not be removed yet.
