### ISSUE TITLE
Spark: use newHadoopConf() in SessionState to get Hadoop conf

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1142]
We need to use `newHadoopConf()` in `SessionState` to pick full Hadoop conf.

**Comment by holdenk** [comment]
Should this issue be resolved? Looking in the code it seems that we do now use `newHadoopConf` since 4bb2b0893a5de0b0452cb9db32401729c098ca8b ?

**Comment by aokolnychyi** [comment]
Yes, this has been resolved. Thanks!
