### ISSUE TITLE
Bad Table Properties cause commit failure

### ISSUE THREAD

**Issue by dramaticlly** [apache/iceberg#11435]
### Apache Iceberg version

1.6.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Today iceberg does not validate the type of table properties values on and this can be problematic if those table properties value are used for commit. 

Example setup
```
                sql(
                    "CREATE TABLE foo.bar "
                        + "(id BIGINT NOT NULL, data STRING) "
                        + "USING iceberg "
                        + "TBLPROPERTIES ('commit.retry.num-retries'='x', p2='x')",
```

See the value for `commit.retry.num-retries` is accidentally set to some non-integer value, we will unable to rectify this through either spark SQL or iceberg API 

```
table.updateProperties.remove("commit.retry.max-wait-ms").apply.commit

table.updateProperties.remove("commit.retry.max-wait-ms").commit
java.lang.NumberFormatException: For input string: "commit.retry.max-wait-ms"
  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
  at java.base/java.lang.Integer.parseInt(Integer.java:668)
  at java.base/java.lang.Integer.parseInt(Integer.java:786)
  at org.apache.iceberg.util.PropertyUtil.propertyAsInt(PropertyUtil.java:64)
  at org.apache.iceberg.TableMetadata.propertyAsInt(TableMetadata.java:472)
  at org.apache.iceberg.PropertiesUpdate.commit(PropertiesUpdate.java:105)
  ... 48 elided
```

After some look, I believe this block of code might be the problem: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/PropertiesUpdate.java#L100-L114, where  propertyAsInt will throw NumberFormatException before commit can proceed to rectify or remove incorrectly set table properties. 

Current workaround is move back to previous table metadata before the table properties change, but I plan to contribute the patch to fix the problem in 2 ways
1. add validation for new table where commit related table properties need to have value type checked (as integer)
2. relax the condition in `PropertiesUpdate` class to allow update when existing value is corrupted, this help with existing table to move forward. 

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by singhpk234** [comment]
Nice catch !
Sounds great looking forward to the change !
