### ISSUE TITLE
iceberg docker-compose quickstart fail 

### ISSUE THREAD

**Issue by HelloWorldwangjiacheng** [apache/iceberg#11544]
### Apache Iceberg version

1.5.0

### Query engine

Spark

### Please describe the bug 🐞

Background: I just want to make a quick-start spark-iceberg under docker-compose to experiment with data lake related functions

My Steps:
1、Obtain the docker-compose.yml code
![image](https://github.com/user-attachments/assets/4f259272-dd72-45bd-8d8b-949cbee748d9)
Due to the occupation of ports 8888 and 8080, 28888 and 28080 were used instead.
2、Then execute docker-compose up -d to start it.
![image](https://github.com/user-attachments/assets/21ce2061-9b76-4777-8175-fb427ee3e356)

3、Then execute docker-compose ps, but there is no content related to "rest" displayed here. I'm not sure if this is normal.
![image](https://github.com/user-attachments/assets/0734ccae-5810-4e9a-9945-0703d1211be9)

4、Execute docker compose exec -it spark-iceberg pyspark to enter PySpark.
![image](https://github.com/user-attachments/assets/af17b694-9b0e-414a-a3dc-86ed8c51bc47)
Here, I executed the statement df.select(df.columns[:7]).show(3) with the intention of querying the first seven columns of the first three rows of data, but unfortunately, an error occurred.
5、Error Content: The ultimate cause of the error seems to be that the hostname for "rest" is not configured, or possibly other containers are unable to read it.
![image](https://github.com/user-attachments/assets/c290f36e-e3af-4037-9ce3-33a3369de2b3)
![image](https://github.com/user-attachments/assets/134a0090-1b71-497d-825e-ebf1b4027117)

6、I seem to have seen this kind of error in past issues, but it was related to version 0.1.0 of "rest" and was reported in 2022. Moreover, that issue was closed at the time, suggesting that it had been resolved. However, it seems to have appeared again now? Or could it be that I haven't configured something correctly? url:https://github.com/apache/iceberg/issues/5993

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [X] I cannot contribute a fix for this bug at this time

**Comment by nastra** [comment]
@HelloWorldwangjiacheng this means that your `iceberg-rest` container isn't running. Maybe try running docker compose in the foreground via `docker compose up` to see why `iceberg-rest` isn't starting. Also try pulling the latest images via `docker compose pull`

**Comment by HelloWorldwangjiacheng** [comment]
Hello friend, you are right. I did find an error in iceberg-rest when starting the front-end through docker-compose up, but I am now confused and don't know how to solve it. Because the literal meaning seems to be that I have insufficient memory, so I have reserved enough memory and increased the startup size of the JVM to xms512M Xmx1024M, but when I restart, I still get the same error
![image](https://github.com/user-attachments/assets/58b447d3-8d1c-415b-8e41-98e8ab8b2d57)
![image](https://github.com/user-attachments/assets/cb496e25-1dba-466c-97a8-8b9f482e4cfb)

**Comment by nastra** [comment]
It might be because docker is limiting how much memory that container gets. Maybe try running the `iceberg-rest` container in isolation first. Typically it shouldn't need a lot of memory. I'll go ahead and close this issue, since there isn't really an issue with Iceberg itself.
