### ISSUE TITLE
Support custom catalog for Iceberg StorageHandler

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#1155]
@massdosage, @rdblue  .  Is anyone workin on this? I wanted to take this up and we are only using HiveCatalog.

**Comment by guilload** [comment]
I have some thoughts regarding this. Now that the SerDe has been merged, there are two pieces of code that do essentially the same thing:
- [IcebergInputFormat.findTable(...)](https://github.com/apache/iceberg/blob/master/mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java#L357)
- [TableResolver.resolveTableFromConfiguration(...)](https://github.com/apache/iceberg/blob/master/mr/src/main/java/org/apache/iceberg/mr/mapred/TableResolver.java#L45)

1. Those two classes should probably be consolidated into one.
2. The ability to define a custom catalog loader is neat. We actually use our own catalog at Airbnb and that feature comes in handy.
3. At the same, most users are going to use either the default Hadoop or Hive catalogs, so let's make it easy for them.
4. I'm personally not a fan of using  a "table path" configuration property to pass either a file path or a table identifier and have to look for the `/` character  to know which use is intended.

Roughly, I have something like that in mind:

```python
def find_table(conf)
  assert conf.get('table.identifier') is None or conf.get('table.path') is None
  assert conf.get('catalog') is None or conf.get('catalog.loader.class') is None

  if conf.get('table.path'):
    return HadoopTables.load(conf.get('table.path'))

  if conf.get('catalog.loader.class'):
    loader = load_class(conf.get('catalog.loader.class'))
    return loader.load(conf)

  identifier = conf.get('table.identifier')

  if (conf.get('catalog') == 'hadoop'):
    return HadoopCatalog.load(identifier)
  elif (conf.get('catalog') == 'hive'):
    return HiveCatalog.load(identifier)
  else:
    raise ...
```

**Comment by rdsr** [comment]
I had something similar in mind.

**Comment by massdosage** [comment]
This is on our TODO list but we were only going to start looking at it properly after the `mapred` InputFormat is merged. The above suggestion to merge the code and the logic outlined above looks good. If someone else wants to start working on this now that's fine by me.

**Comment by guilload** [comment]
Has anybody started working on this issue? Happy to get this going otherwise.

**Comment by rdsr** [comment]
@guilload I might be able to get to this this week. So I'm cool if you'd like to finish this up. Happy to review the code!

**Comment by guilload** [comment]
Ok, I'll take a stab at it!

**Comment by pvary** [comment]
I think we can close this issue, as the catalog configuration is already there.
What do you think @rdsr?

Thanks,
Peter

**Comment by rdsr** [comment]
I think so too, I haven't been following the code changes, but I do see in the `hive.md` that we can use `HiveCatalog`
