### ISSUE TITLE
How an application can communicate with the Iceberg REST catalog like Dremio Arctic (Nessie), Snowflake’s Polaris , Gravitino

### ISSUE THREAD

**Issue by anusshetty** [apache/iceberg#11649]
Hi Team,

How can I access the Iceberg REST catalog like Dremio Arctic (Nessie), Snowflake’s Polaris , Gravitino from my application .

Can I use the SPARK SQL APIs to fetch metadata and  Read/Write data to REST catalog or should I use only REST APIs to interact with REST catalog.

Any help would be appreciated.

Regards,
Anush

**Comment by ajantha-bhat** [comment]
Duplicate of https://github.com/apache/iceberg/issues/11655
