### ISSUE TITLE
Renamed column returns null values from 'appended' Parquet file not originally created by Iceberg

### ISSUE THREAD

**Issue by pedorro** [apache/iceberg#11650]
### Apache Iceberg version

1.7.0 (latest release)

### Query engine

Athena

### Please describe the bug 🐞

When both of the following criteria are met, queries for a renamed column return nulls instead of the original values:

1. The data is in an existing Parquet file that is 'appended' to the table (using the Java SDK `appendFile()` function)
2. The existing Parquet file was created by something _other_ than Iceberg

As a contrived example, assume there exists in S3 a Parquet file with three columns and one row. This Parquet file is written by something other than the Iceberg libs (e.g. Apache Parquet lib v1.14.4).  This file is appended to a new (empty) Iceberg table called `example_table`.  Using the Java SDK:
```
table.newAppend().appendFile(existingParquet).commit();
```

Querying (in AWS Athena) from the table now returns the single row.
```
select * from example_table;

| first | second | third |
+-------+--------+-------+
| aaa   | bbb    | ccc   |
```

Now rename column `second` to `renamed`. Using the Java SDK:
```
table.updateSchema().renameColumn("second", "renamed").commit();
```

Querying from the table _now_ returns the single row, but without the value in column `renamed`:
```
select * from example_table;

| first | renamed | third |
+-------+---------+-------+
| aaa   |         | ccc   |
```
This is true when queried by both AWS Athena & Redshift Spectrum.

Interestingly, if the existing Parquet file _was_ originally created by Iceberg (either via an `insert` query or using the Java SDK), this issue does not present. In that case, a query for the renamed column _does_ return the correct (original) value. Even if the Iceberg-created Parquet file is copied or moved from its original location before being appended to a new table, the column-rename works as expected. This suggests there is some unique (non-standard?) quality to Parquet files created by Iceberg, and the column rename operation relies on it.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by singhpk234** [comment]
This is an interesting observation can you please help with the following : 
[1] is this prop being set : schema.name-mapping.default in tbl properties if not can you set it ?
[2] whats the table create command ?

**Comment by pedorro** [comment]
Well dad-gum! Setting that table property appears to have resolved it. I'm quite new to Iceberg in general, and so was unaware of this property.  I really appreciate you taking a minute to review this ticket and offer your suggestions. And I apologize if I jumped the gun on submitting a bug report.

Just for future reference, and anyone else who happens across this same question, the `schema.name-mapping.default` property appears to be intended precisely for this use-case, of appending non-Iceberg Parquet files to an Iceberg table. It is described here: https://iceberg.apache.org/spec/#name-mapping-serialization

I'm setting that property during table creation like this:
```
[
    {"field-id": 1, "names": ["first"]},
    {"field-id": 2, "names": ["second"]},
    {"field-id": 3, "names": ["third"]}
]
```

**Comment by pedorro** [comment]
Closing this ticket as apparently not an issue, but rather ignorant-user-error.
