### ISSUE TITLE
Unsupported class file major version 65 when building Iceberg 1.4.x with JDK 1.8

### ISSUE THREAD

**Issue by JackeeH** [apache/iceberg#11689]
### Apache Iceberg version

1.4.3

### Query engine

None

### Please describe the bug 🐞

I am using OpenJDK 1.8 and trying to build Iceberg 1.4.x using the command `./gradlew build -x test -x integrationTest`. However, I encountered a failure while building the subproject `Task :iceberg-spark:iceberg-spark-runtime-3.5_2.12:shadowJar`, which is likely related to shadow plugin. 
During the build process, it can be confirmed that I am using JDK1.8. 
The error message is as follows. 
![image](https://github.com/user-attachments/assets/16f4a2ec-8423-466a-9ed0-9c2daaf0f7dd)

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by JackeeH** [comment]
The stack picture is not very clear, you can see the picture below: 
![image](https://github.com/user-attachments/assets/d2172b08-2565-4ec3-93d0-3d4e81757ee1)

**Comment by nastra** [comment]
I do recall that this was potentially an issue with the Shadow plugin we were using at the time when 1.4.x was released (https://github.com/GradleUp/shadow/issues/894). We're not going to do another 1.4.x release with the fix but I've attached the below patch as a workaround for people that want to build Iceberg 1.4.x with JDK8: [jdk8.patch](https://github.com/user-attachments/files/17990207/jdk8.patch)

@JackeeH can you confirm that the attached patch works for you?

**Comment by JackeeH** [comment]
@nastra Yes, I can confirm that I did successfully build version 1.4.x by using the command `./gradlew build -x test -x integrationTest` after applying this patch.

**Comment by nastra** [comment]
thanks for confirming @JackeeH. I'll close this then since we have a documented workaround for this
