### ISSUE TITLE
Iceberg Kafka-Connect runtime not published as part of 1.7.0 release?

### ISSUE THREAD

**Issue by thjaeckle** [apache/iceberg#11685]
### Question

Hello Iceberg community.

I saw that in the recent `1.7.0` release you moved the Kafka-Connect Iceberg sink to this project, which is great.  
I however do not see it published (as you do it for other runtimes, e.g. Flink, Spark) at [1.7.0 Downloads](https://iceberg.apache.org/releases/#downloads).  
I also did not find it at https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-kafka-connect/

I would like to use it in a Docker image and download the official and signed release from somewhere.

Was that forgotten or on purpose that runtime artifacts for Kafka-Connect were not published?

**Comment by manuzhang** [comment]
I believe it's on purpose according to the [installation guide](https://iceberg.apache.org/docs/nightly/kafka-connect/#installation)

**Comment by Fokko** [comment]
Let's ask @bryanck

**Comment by bryanck** [comment]
I was going to look into the distribution of the connector for 1.8 (see https://github.com/apache/iceberg/issues/10745). I'll see if we can get something into the 1.7.1 release.

**Comment by Fokko** [comment]
@bryanck Patch releases should only contain bug fixes. I would suggest targetting the runtime for the 1.8.0 release. That one should go out somewhere in the next few weeks.

**Comment by bryanck** [comment]
Sounds good, so for 1.7 @thjaeckle you will need to build it locally.

**Comment by thjaeckle** [comment]
Ok, understood.
Good that you have it already on the agenda. 👍

**Comment by raphaelauv** [comment]
could we re-open this issue , since it's still not done with 1.8.0 release
