### ISSUE TITLE
Kafka Connect runtime package is missing Nessie catalog jars

### ISSUE THREAD

**Issue by nikulaja** [apache/iceberg#11733]
### Apache Iceberg version

1.7.1 (latest release)

### Query engine

Kafka Connect

### Please describe the bug 🐞

Hello,

Kafka Connect runtime build is currently missing Nessie catalog jars. In documentation there are instructions how to use Nessie catalog, but when running connector with given Nessie settings connector startup fail with.
```
java.lang.IllegalArgumentException: Cannot initialize Catalog implementation org.apache.iceberg.nessie.NessieCatalog: Cannot find constructor for interface prg.apache.iceberg.catalog.Catalog  
Missing org.apache.iceberg.nessie.NessieCatalog [java.lang.ClassNotFoundException: org.apache.iceberg.nessie.NessieCatalog
```

Tabular/databrick project from which this connector was cloned has these files in current 0.6.19 runtime build:
`iceberg-nessie-1.5.2.jar, 
nessie-client-0.77.1.jar, 
nessie-model-0.77.1.jar`

Can the needed jars be added to next release?

Thank you!

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [X] I cannot contribute a fix for this bug at this time

**Comment by Fokko** [comment]
@nikulaja You have to add the jar separately: https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-nessie Since not everyone uses the Nessie catalog, we don't want to include this jar all the time.

**Comment by nikulaja** [comment]
@Fokko Thank you for reply! Seems very reasonable. Could this information be added to documentation? I'm very new to iceberg so wouldn't know if this is a regular thing with other integrations.

**Comment by ankurbansal-tradedoubler** [comment]
I encountered the similar issue today and I think too that it would be great if the documentation could be updated with these details.
