### ISSUE TITLE
Bump Flink to 1.11

### ISSUE THREAD

**Issue by JingsongLi** [apache/iceberg#1179]
https://flink.apache.org/news/2020/07/06/release-1.11.0.html

**Comment by rdblue** [comment]
Should we do this before merging #1182? Then we could use [`SHOW TABLES`](https://github.com/apache/iceberg/pull/1182#discussion_r453429303).

**Comment by JingsongLi** [comment]
> Should we do this before merging #1182? Then we could use [`SHOW TABLES`](https://github.com/apache/iceberg/pull/1182#discussion_r453429303).

Yes, we should
