### ISSUE TITLE
Cannot create DBMS Table automatically when JdbcCatalog initialize

### ISSUE THREAD

**Issue by liangyouze** [apache/iceberg#11862]
### Apache Iceberg version

1.7.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

When JdbcCatalog initialize, it will globally search whether `iceberg_tables` and `iceberg_namespace_properties` exist instead of searching the current catalog and schema for the URI. This means that when tables with the same name exist in other catalogs or schemas, these two tables will not be automatically created.

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [x] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by ebyhr** [comment]
I guess we should use `conn.getCatalog()` for "catalog name", and `conn.getSchema()` for "schemaPattern" with an escape:

https://github.com/apache/iceberg/blob/ca3db931b0f024f0412084751ac85dd4ef2da7e7/core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java#L161-L166

https://github.com/apache/iceberg/blob/ca3db931b0f024f0412084751ac85dd4ef2da7e7/core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java#L179-L185

**Comment by ebyhr** [comment]
It seems there is an existing issue. #11423
