### ISSUE TITLE
i meet a question，time travel has some error to the query of timestamp 

### ISSUE THREAD

**Issue by hashmapybx** [apache/iceberg#11889]
### Query engine

spark-sql: 3.4.2 iceberg:1.6.1

### Question

命令行根据时间戳做时间旅行查询报错
spark-sql (cjh_test)> select * from cjh_test.datalake_iceberg_table timestamp as of '2024-12-30 10:28:57.321';
Invalid usage of '*' in Project.; line 1 pos 7;
'Project [*]
+- 'TimeTravelRelation 2024-12-30 10:28:57.321
   +- SubqueryAlias spark_catalog.cjh_test.datalake_iceberg_table
      +- RelationV2[id#187, name#188, year#189, month#190] spark_catalog.cjh_test.datalake_iceberg_table spark_catalog.cjh_test.datalake_iceberg_table

**Comment by Fokko** [comment]
Thanks @hashmapybx for raising this question, unfortunately, the information that you provide is very little. At first glance, the SQL seems to be correct. What kind of version of Spark/Iceberg are you using?

**Comment by hashmapybx** [comment]
Additional Notes：
<img width="1154" alt="Clipboard_Screenshot_1735540767" src="https://github.com/user-attachments/assets/efbf317f-db87-4c65-84eb-2fe4d2da955b" />
<img width="930" alt="Clipboard_Screenshot_1735540801" src="https://github.com/user-attachments/assets/96cabcc5-7f5e-412f-955b-d3650390d0f3" />

**Comment by hashmapybx** [comment]
> Thanks @hashmapybx for raising this question, unfortunately, the information that you provide is very little. At first glance, the SQL seems to be correct. What kind of version of Spark/Iceberg are you using?

i addtions notes, the version of spark and iceberg

**Comment by KnightChess** [comment]
`TimeTravelRelation`, this seems to be hudi's logical plan. could you confirm if hudi has been included?

**Comment by hashmapybx** [comment]
> `TimeTravelRelation`, this seems to be hudi's logical plan. could you confirm if hudi has been included?

thanks,i  find that  the content of spark-default.conf file  has icberg and hudi ,spark.sql.extensions    org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.apache.spark.sql.hudi.HoodieSparkSessionExtension,org.apache.kyuubi.plugin.spark.authz.ranger.RangerSparkExtension.

i change config

**Comment by hashmapybx** [comment]
change after config.

<img width="1533" alt="Clipboard_Screenshot_1735611037" src="https://github.com/user-attachments/assets/c03e4f40-aa2c-4f16-9a21-7ed8c43afb54" />
