### ISSUE TITLE
[Question] Do Spark Iceberg module implement Copy On Write Delete and Update?

### ISSUE THREAD

**Issue by GrigorievNick** [apache/iceberg#1202]
Hi, 
I have a question >
Do Spark Iceberg Implement Copy On Write Delete and Update?
* I find [this MR](https://github.com/apache/iceberg/pull/351), so Iceberg itself supports it. 
  But what about implementation in spark? 
  Looking on [this code](https://github.com/apache/iceberg/blob/master/spark3/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java#L87) I can say that at least Spark 3 supports it, am I right? 
 * But looking to spark the only usage of this builder method is in delete sections of org.apache.spark.sql.execution.datasources.v2.OverwriteByExpressionExecV1 and OverwriteByExpression.
 * So does it possible to implement Eager(CopyOnWriteUpdate) or there is some known issues?

Do Spark 2 Iceberg Implement Copy On Write Delete and Update?

**Comment by rdblue** [comment]
Both Spark 2.4 and Spark 3.0 support dynamic partition overwrite. Spark 3.0 also supports overwrite by expression, although the expression must match all rows in a data file or no rows of a data file, or else it will cause an exception because the granularity of a delete is a whole data file.

**Comment by GrigorievNick** [comment]
> Both Spark 2.4 and Spark 3.0 support dynamic partition overwrite. Spark 3.0 also supports overwrite by expression, although the expression must match all rows in a data file or no rows of a data file, or else it will cause an exception because the granularity of delete is a whole data file.

But Overwrite that implemented in delete is match smarter then overwrite all data in the partition. 
it will change only files that contain changes, while simple overwrite will update all partition.
So of course I can read data all data from partition -> manipulate -> overwrite. 
But I can do it with any code. What I am looking for is to update only files that match changes.
So as I understand, there is no such solution right now, yes?

I can implement it manually using low-level(java-core) API.
But in this case, I have one more question, which I can't find in docs. 
Does it possible to do concurrent [Table Operation](https://iceberg.apache.org/api/#table-metadata) -> `newRewrite`?
 Small explanation: I will have different spark partitions that will overwrite one or a few dataFiles.
And of course, a partition is idempotent and running in parallel.
