### ISSUE TITLE
ORC does not support Name Mapping of schemas with no Iceberg IDs

### ISSUE THREAD

**Issue by edgarRd** [apache/iceberg#1204]
In order to be able to import existing ORC data to Iceberg tables, we need to support name mapping of schemas to existing ORC data files.

At the moment, only Parquet and Avro have the support for this feature, but not ORC.

**Comment by edgarRd** [comment]
I'm currently working on a PR for this.

**Comment by rdsr** [comment]
Thanks @edgarRd! We need this feature :)
