### ISSUE TITLE
Importing a Spark table with Whitespace in Partition URI Results in FileNotFound Exception

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#1224]
Because SparkPartition stores partition URI's as a String, there is an issue when reconverting the URI into a Hadoop path if the String contains URI encoded characters (like a space -> %20). This ends up causing FNF errors when attempting the import into iceberg.

Example Test Case

```
    String partitionCol = "dAtA sPaced";
    String spacedTableName = "whitespacetable";
    String whiteSpaceKey = "some key value";

    List<SimpleRecord> spacedRecords = Lists.newArrayList(new SimpleRecord(1, whiteSpaceKey));

    File location = temp.newFolder("partitioned_table");

    spark.createDataFrame(spacedRecords, SimpleRecord.class)
        .withColumnRenamed("data", partitionCol)
        .write().mode("overwrite").partitionBy(partitionCol).format("parquet")
        .saveAsTable(spacedTableName);

    TableIdentifier source = spark.sessionState().sqlParser()
        .parseTableIdentifier(spacedTableName);
    HadoopTables tables = new HadoopTables(spark.sessionState().newHadoopConf());
    Table table = tables.create(SparkSchemaUtil.schemaForTable(spark, spacedTableName),
        SparkSchemaUtil.specForTable(spark, spacedTableName),
        ImmutableMap.of(),
        location.getCanonicalPath());
    File stagingDir = temp.newFolder("staging-dir");
    SparkTableUtil.importSparkTable(spark, source, table, stagingDir.toString());
    List<Row> results = spark.read().format("iceberg").load(location.toString()).collectAsList()
```

Which throws

```
    Caused by:
        org.apache.iceberg.exceptions.RuntimeIOException: Unable to list files in partition: file:/var/folders/yl/6cwgks7919s1td2mfdq86cbm0000gn/T/hive4638538718213787020/whitespacetable/dAtA%20sPaced=some%20key%20value
            Caused by:
            java.io.FileNotFoundException: File file:/var/folders/yl/6cwgks7919s1td2mfdq86cbm0000gn/T/hive4638538718213787020/whitespacetable/dAtA%20sPaced=some%20key%20value does not exist
```

I am currently working on a PR to fix this (and add a failing test case) and will have it up soon

**Comment by aokolnychyi** [comment]
Is it because `URI.toString` that we are using does not decode the URI correctly? We later create `Path` from `String`? Spark has `CatalogUtils` that handles `URI` to `String` conversion through Hadoop `Path` but we should be ok with just using `URI` to construct `Path`?

**Comment by RussellSpitzer** [comment]
Yes. Basically the constructor `public Path(String pathString) throws IllegalArgumentException` is just take apart string as is and attempts to break it into the correct parts.

While the constructor `public Path(URI)` just takes the URI as is and sets it to the internal representation of the path so it handles the encoding properly

**Comment by RussellSpitzer** [comment]
```scala> new URI("file:///has%20spaces")
res3: java.net.URI = file:///has%20spaces

scala> val uri = new URI("file:///has%20spaces")
uri: java.net.URI = file:///has%20spaces

scala> new Path(uri).toString
res4: String = file:/has spaces

scala> new Path(uri.toString).toString
res5: String = file:/has%20spaces```

**Comment by raptond** [comment]
👍  to keep the paths as `URI` objects and not convert to` String`s. I thought perhaps we should `unescape`, but it seems a better idea to delegate that to `Path`.

**Comment by aokolnychyi** [comment]
We would need to check the remove orphan files action in a follow-up too to make sure we are safe.
