### ISSUE TITLE
Some compiler warnings about methods missing the @Override tag

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#1248]
When building the project from a clean download using `./gradlew build`, there are several warnings about class methods that are missing `@Override` tag. While these don't necessarily cause any issues and are only warnings, they violate the google style guide.

An example would be
```
    (see https://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public ByteBuffer keyMetadata() {'?
/Users/kbendick/repos/iceberg/core/src/main/java/org/apache/iceberg/BaseFile.java:346: warning: [MissingOverride] splitOffsets implements method in ContentFile; expected @Override
  public List<Long> splitOffsets() {
```

Some of these warnings are possibly false positives, which could be suppressed using `@SuppressWarnings("MissingOverride")`. Otherwise, the `@Override` tag should be included if one were following the google style guide (or even just following the warnings from the gradle build as suggested in the README).

I'd be happy to submit a PR to remove some of these warnings so that potential new contributors or anyone building the project for the first time don't see them.

They're also arguably error prone, but I'm mostly interested in removing the compiler warnings in the most correct way possible.

**Comment by kbendick** [comment]
I opened a PR to fix the issues from one class only, in case this work isn't wanted (e.g. in case the Overrides are intentionally not present in this class). I can fix the other warnings in a larger PR later or in this PR if this looks good to any of the committers.

**Comment by kbendick** [comment]
I received an approval on this first PR from @rdsr. If somebody wants to assign this to me, I can keep going on the rest of the warnings for `MissingOverride`.

There's also some equality check warnings, e.g. using `==` vs. something like `Object.equals` that I'd be interested in taking a look at, though that is a more complicated process and definitely its own issue.

cc @JingsongLi @rdblue @rdsr for hopefully assigning this issue to me!

**Comment by rdblue** [comment]
@kbendick, we don't really assign issues, especially if there is clear interest from someone that wants to work on it -- that's just as good.

We rarely have cases where people decide to work on the same thing that would be avoided by assigning issues, but I've often seen people claim an issue and then not work on it.

**Comment by kbendick** [comment]
Thanks @rdblue for letting me know. I plan on fixing the remaining missing Override annotations and then taking on this issue as I continue to familiarize myself with the codebase.

My eventual hope is to contribute to the project in a more meaningful way, whether that be through further automation, additions to the Flink or Spark integration (these are the technologies I work with regularly at work), or something else.

I appreciate you taking the time to help me learn the projects standards. 👍

**Comment by rdblue** [comment]
I'm closing this because both #1249 and #1252 are merged. Thanks for fixing this, @kbendick!
