### ISSUE TITLE
Create an Action for Importing Tables to Iceberg

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#1258]
Currently the only way to import a table from Spark to Iceberg is via an internal SparkTableUtil function.  While this works, we were wondering if we should create another Action API to encompass this functionality.

Having an action wrapper would make it more clear that this is a User facing API. In addition, when we start working on the SQL Extensions there will be a more clear mapping between new grammar and existing actions.

I propose an API a bit like the following but am open to all suggestions and ideas

```java
/**
*.Imports a Spark Table into Iceberg, Returns list of files imported
**/ 
class ImportTableAction<List<Path>> {

  public ImportTableAction fromCatalog(String catalogIdentifier)

  public ImportTableAction fromTable(String[] Identifier) // I think we should use prefer the Spark Identifier here if we can

  public ImportTableAction toLocation(Path location)

  public List<Path> execute() {
    SparkTableUtils.import(...)
  }
}
```

**Comment by aokolnychyi** [comment]
One of the things such action should do is to assign name mapping so that we have reliable nested schema pruning for imported tables. Such tables will not have column ids in data files.

**Comment by edgarRd** [comment]
Issue #1206 is related to what @aokolnychyi mentioned.

**Comment by aokolnychyi** [comment]
Done in PR #1525
