### ISSUE TITLE
Expose time travelling using multi-part identifiers

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1260]
Until we have proper SQL support for time travelling in Spark, we should expose it using multi-part identifiers.

Background [here](https://docs.google.com/document/d/1Nf8c16R2hj4lSc-4sQg4oiUUV_F4XqZKth1woEo6TN8/edit?disco=AAAAGvqh7BA).

**Comment by rdsr** [comment]
I believe this ticket to address time travel by both `snapshot-id` and `as-of-timestamp`?

**Comment by aokolnychyi** [comment]
@rsdr, ideally, yes. We will need to distinguish them, though. I think `as-of-timestamp` should be a properly formatted timestamp and not the number of seconds since the epoch.

**Comment by aokolnychyi** [comment]
There are native APIs in Spark now.
