### ISSUE TITLE
Add a github action to label PRs with the relevant subprojects that are affected

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#1277]
As the number of subprojects grows and as the number of committers and contributors grows, it will likely become more and more difficult to find PRs that are associated with certain subproject (e.g., if I wanted to look at PRs proposing changes for `iceberg-core` or for `flink`).

It would be entirely possible to use a github action to place labels on each PR automatically that mentions the relevant affected subprojects.

This way, contributors could find the PRs that are most relevant to the work that they're doing.

I'm not sure if the ASF has infrastructure in place that they prefer to use over github actions. However, for public projects, github actions are free so I don't see the harm in using them personally. Additionally, given it's the ASF, there is definitely infra in place for running certain automated tasks. However, I'm not sure if tagging PRs is possible outside of github actions. And it would after all be free for us as we're an OSS project.

Do people feel there would be benefit in having this? It wouldn't necessarily help locate PRs for say, spark streaming vs spark batch, but it would at least help identify PRs without requiring the contributor to mark `Flink` or `Spark3 Runtime` in their PR titles.

I'm open to hearing what others have to say before committing to adding this. I personally think it would help triage PRs more effectively, especially for heavy contributors / PMCs who likely have to remember many different subprojects they've promised to take a look at in "the next few days" ™️  😄 

For pricing info, see the section marked `Simple, pay-as-you-go pricing`. But tldr: it's free. https://github.com/features/actions

**Comment by HeartSaVioR** [comment]
That sounds exactly same as what Apache Spark project adopted recently, and I see much benefits on auto-labeling so big +1. I think marking PR title is a bit orthogonal though, as it would still help to construct commit title.

**Comment by aokolnychyi** [comment]
I am +1. We try to prefix commits while merging but having actions to mark sounds like a good idea.

I think we may also consider adding a template for PR descriptions as the project grows (it is totally separate).

**Comment by kbendick** [comment]
Ok great. I will try to open a PR for this either this weekend or early next week. I have some experience with github actions, and thanks to @HeartSaVioR for the idea to search for inspiration from Spark.

I agree that marking PR title is a bit orthogonal, and nothing will stop people from continuing to mention projects in the commit title. If we also add a template, we can consider instructing people to add informative information about affected subprojects or affected areas, especially things like `[spark-streaming]` that can't be captured simply based on gradle subprojects easily would be great candidates for addition to commit title.
