### ISSUE TITLE
Iceberg Datasource Writer Should Automatically Prune Identity Transform Partition Columns

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#1281]
While writing the vectorized reader for Identity transforms in parquet I ran into the detail that when you write to a Parquet backed Iceberg table it will write columns for all data present even if those rows are already defined by the partitioning. I think it probably makes sense to strip out these columns on write to save space and time when writing. Any thoughts?

**Comment by ericsun2** [comment]
So you are suggesting the Hive-style Virtual Partition Column which only stored in metadata but no the data files?
Then that is probably against the original design of Iceberg.
The space waste for such repetitive values of `Identity()` Transform in Parquet/ORC should be close to nothing.
