### ISSUE TITLE
`select` will overwrite `project` whatever the order in TableScan

### ISSUE THREAD

**Issue by JingsongLi** [apache/iceberg#1304]
`select` will overwrite `project` whatever the order.
-> table.newScan().select("id").project(SCHEMA.select("data"))
Expected: "data"
Actual: "id"

Should we fix this? Invalid `select` when `project`?

**Comment by rdblue** [comment]
The two methods are alternatives to one another, so I would not expect users to call both of them. I'd be okay with fixing this (open to suggestions on behavior) or simply throwing an exception if both methods are used to configure the same table scan.

**Comment by JingsongLi** [comment]
> The two methods are alternatives to one another, so I would not expect users to call both of them. I'd be okay with fixing this (open to suggestions on behavior) or simply throwing an exception if both methods are used to configure the same table scan.

Thank you for your reply, I think simply throwing an exception is good.
