### ISSUE TITLE
Run iceberg-mr and iceberg-hive tests on Hive 3.1.2 as well

### ISSUE THREAD

**Issue by marton-bod** [apache/iceberg#1371]
Currently, the iceberg-mr and iceberg-hive tests are run using Hive version 2.3.7. In order to make sure that any existing/future Iceberg code can play well with more up-to-date Hive versions as well, and catch any incompatibility early, our proposal with @pvary is to add logic in Gradle in some form to run the test suites on both Hive 2.3.7 and 3.1.2 (the latest release), thereby testing compatibility for both versions.

cc @massdosage - any thoughts on this from your side? thanks

**Comment by massdosage** [comment]
Some of the Hive integration-style tests use HiveRunner but this doesn't currently support Hive 3.x, I looked into it a while ago and I don't think it's too much work to add this, see https://github.com/klarna/HiveRunner/issues/120. If we could get that merged into HiveRunner and released then we could support testing of both Hive 2 and 3.

**Comment by marton-bod** [comment]
Thanks @massdosage. I'm working on fixing the test failures/warn logs in HiveRunner (hive-3.x) and will post a PR so we can push this forward

**Comment by marton-bod** [comment]
@massdosage I've created the PR: https://github.com/klarna/HiveRunner/pull/125
