### ISSUE TITLE
Flink:  Improvements for iceberg sink connector.

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#1403]
In this [patch](https://github.com/apache/iceberg/pull/1185), we have several minor issues to follow up for flink sink connector:

* Support multiple iceberg sinks in the same flink job. [discussion](https://github.com/apache/iceberg/pull/1185/files#r479448928).
* provide a method to set user-provided write parallelism in FlinkSink#Builder. 
* The netflix team have improved their flink sink by buffering all the uncommitted data files in a separate manifest file to reduce the state size.  It would be really helpful if users put their data files and metstore in two different cloud region, because we could keep the job going even if  we fail to commit to iceberg sometimes.  [discussion](https://github.com/apache/iceberg/pull/1185/files#r478772412)

**Comment by stevenzwu** [comment]
just want to add another [unaddressed comment](https://github.com/apache/iceberg/pull/1185#discussion_r479589663) regarding distinguishing DataFile from different Flink checkpoints.
