### ISSUE TITLE
Support Parquet modular encryption

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1413]
We would need to design an API for users to put their logic for managing keys to support [modular encryption](https://github.com/apache/parquet-format/blob/master/Encryption.md) in Parquet. Also, we would need to propagate the encryption config to Parquet read and write options in `Parquet`.

**Comment by aokolnychyi** [comment]
Actually, we may not need anything. One moment.

**Comment by aokolnychyi** [comment]
I think we can try to leverage [this](https://github.com/apache/parquet-mr/blob/3d45fd5480b1b58074c5b53d0738774cf355d11e/parquet-hadoop/src/main/java/org/apache/parquet/crypto/DecryptionPropertiesFactory.java#L45) in Parquet.

**Comment by shangxinli** [comment]
EncryptionPropertiesFactory/DecryptionPropertiesFactory help you build up the FileEncryptionProperties/FileDecryptionProperties. There is an open PR(https://github.com/apache/parquet-mr/pull/808) about how to use them.

**Comment by shangxinli** [comment]
Sounds good @ggershinsky! Look forward to reviewing your changes!

**Comment by ggershinsky** [comment]
Cool, I'll send them in a pr (after the parquet-mr-1.12 artifact is released; CI checks won't pass otherwise).
