### ISSUE TITLE
Is there anyway to deploy Iceberg with Flink instead of Spark 3 now? 

### ISSUE THREAD

**Issue by xmuyoo** [apache/iceberg#1414]
Hi, guys! 

Since there is already a Flink cluster in my company, I want to try to deploy Iceberg with it to write/read data instead of Spark.

But I can't find any documents about how to do it. Is there anyway to deploy it?

If not, is there a roadmap with Iceberg-Flink? 

Thanks a lot!

**Comment by Muyoo** [comment]
I've noticed that there is a module named `iceberg-flink`. It seems that Iceberg can work with Flink instead of Spark. 

But I don't know how it go now.

**Comment by zixi0825** [comment]
+1

**Comment by chenjunjiedada** [comment]
@Muyoo @zixi0825 , I guess you guys may be interested in this PR: https://github.com/apache/iceberg/pull/1423.
