### ISSUE TITLE
TestHiveIcebergFilterFactory.testDateType run failed.

### ISSUE THREAD

**Issue by Simon0806** [apache/iceberg#1416]
![image](https://user-images.githubusercontent.com/12323514/92067997-4e43b380-edd8-11ea-8e74-23b29586cae2.png)
 
As shown in pic, I run ut in my local env and it throws UT failed, is this caused by my environment ? or it's UT bug ?

**Comment by zhangdove** [comment]
The problem relates to time zones, where `Timestamp` is used in function calls. 

@rdblue Do you have any good ways to avoid this problem?

**Comment by rdblue** [comment]
I think we need to address this. Tests should not be timezone dependent. I'll try to take a look.

**Comment by pan3793** [comment]
`java.util.Date` and any class derived from it include `java.sql.Date` always keep epoch and timezone internal.

`java.sql.Date.valueOf("2015-11-12")` actually return a "offset date" at system default zone offset, but hive `SearchArgument` is build by it's epoch, this is equivalent to convert it to GMT date, then the test case should be failed in any GMT+x timezone. I think the solution is construct a GMT `java.sql.Date` to avoid this timezone dependent.
