### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/iceberg#1426]
https://github.com/apache/iceberg/blob/454101c3573acb9cd94d6d9a306ed99a5a324ed9/data/src/main/java/org/apache/iceberg/data/orc/GenericOrcReaders.java#L54

This field is never used.

**Comment by RussellSpitzer** [comment]
I think we actually have a large number of other unused things, our current warning level is quite high. We should probably go through and clean them up. I have some time this morning so I think I'll grab all the obvious ones.
