### ISSUE TITLE
Support for Row level column values update

### ISSUE THREAD

**Issue by it-sceptic** [apache/iceberg#1439]
I think to support SCD type-2 it would be very helpful 

Supplier_Key	  Supplier_Code	Supplier_Name	Supplier_State	                   Start_Date	                      End_Date
123	                  ABC	                Acme Supply Co	CA	                            2000-01-01T00:00:00	      2004-12-22T00:00:00
124	                 ABC	               Acme Supply Co	IL	                            2004-12-22T00:00:00	                 NULL

**Comment by ismailsimsek** [comment]
@it-sceptic this is now possible with [MERGE INTO](https://iceberg.apache.org/spark-writes/#merge-into) feature (iceberg release 0.11.0)

you can find [scd2 example here](https://github.com/ismailsimsek/iceberg-examples/blob/master/src/main/java/IcebergSCD2.java)
