### ISSUE TITLE
make Flink iceberg sink work without checkpoint enabled.

### ISSUE THREAD

**Issue by simonsssu** [apache/iceberg#1442]
Current Flink Iceberg Sink depends on checkpoint to do commit. If we don't enable checkpoint, the data will not be commit into iceberg. so we have to do an improvement.

**Comment by simonsssu** [comment]
relate to PR: [https://github.com/apache/iceberg/pull/1515]

**Comment by JingsongLi** [comment]
Hi @simonsssu , can you explain more about the user cases?
Without checkpointing, it seems that consistency is not guaranteed at all. What are the disadvantages of opening checkpointing?

**Comment by vu-hoang-phan-form3** [comment]
@JingsongLi In my use case, the input is a NATS stream which already supports durable and acknowledge mechanism, so I don't think I need checkpointing to guarantee consistency. 

Also, opening checkpointing means another storage needed to store checkpoint files?
