### ISSUE TITLE
Possible need to use flink's shaded classes in place of org.apache.flink.runtime.util.HadoopUtils

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#1462]
When looking through issues, I noticed from @openinx's issue https://github.com/apache/iceberg/issues/1437 that we are using `org.apache.flink.runtime.util.HadoopUtils`.

However, it appears that a hotfix has been applied in Flink by @JingsongLi  which shades ` org.apache.flink.runtime.util` to  `org.apache.flink.hive.shaded.util` in this PR https://github.com/apache/flink/pull/12646/files (which shows merged to master in Github on June 15th).

Flink 1.11 was released in early July, so it's possible that we don't need to use the shaded package name. But I wanted to open this issue to track.

One place that I saw that we use it is here, though it's probably that it's possible that it's used in more places: https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java#L122

If any of the interested parties tagged can confirm that we should or should not be using the new `org.apache.flink.hive.shaded.util` when using `flink-connector-hive`, I would be more than happy to put in a PR to make the change.

If I don't hear from anybody (hoping @JingsongLi will know off the top of his head), then I will do further investigation.

**Comment by JingsongLi** [comment]
Thanks @kbendick for start this discussion. 
I think we don't need change this to shaded class.
Actually, Flink-iceberg is not relevant to Flink-hive, they just reuse some hive dependencies. We don't have to tie them up.
And Flink cluster already contains `org.apache.flink.runtime.util.HadoopUtils` in lib.

**Comment by kbendick** [comment]
Cool. Thanks for letting me know. I wasn't sure if the flink cluster would contain the shaded or non-shaded library based on what I saw. I figured I could either spend a good amount of time looking into it or simply tag you since you were the one that added shading @JingsongLi. 

I appreciate you taking the time to let me know and for getting back to me so promptly. I'll close this issue now.
