### ISSUE TITLE
Make HiveCatalog inheritable for custom IMetaStoreClient

### ISSUE THREAD

**Issue by JingsongLi** [apache/iceberg#1470]
Our internal has a custom meta store which implements Hive `IMetaStoreClient`, I think it is good to reuse Iceberg `HiveCatalog`:
- Change `HiveMetaStoreClient` to `IMetaStoreClient`. (Actually depends on `IMetaStoreClient` is enough in Iceberg?)
- Make `HiveClientPool` pluggable in `HiveCatalog`, maybe a new constructor like: `public HiveCatalog(String name, HiveClientPool clients, Configuration conf)`.

**Comment by pvary** [comment]
> * Change `HiveMetaStoreClient` to `IMetaStoreClient`. (Actually depends on `IMetaStoreClient` is enough in Iceberg?)

IMetaStoreClient definitely should be enough for Iceberg.
We still have to keep the HMS for testing though (or need a replacement implementation)

**Comment by kesavkolla** [comment]
I also have very similar requirement. I'm not using hadoop or spark I just want to interact with the S3 and HiveMetaStore. Currently there is no way to use HiveMetaStoreClient and use iceberg. Any idea when will this be implemented?

**Comment by pvary** [comment]
@kesavkolla: This should not be that complicated. Currently I am focusing on other parts of the code, but if you want to try out yourself and contribute the code, I would be happy to review your change.

Thanks,
Peter
