### ISSUE TITLE
How to use VectorizedRowBatchIterator

### ISSUE THREAD

**Issue by naishu** [apache/iceberg#1486]
Hi , I need to use Orc Iterator which is renamed to VectorizedRowBatchIterator in another package outside iceberg as an Java Iterator . so I had installed iceberg-orc.

But i' unable to use it because VectorizedRowBatchIterator constructor is private. So How do i use VectorizedRowBatchIterator as adapter for iterator?

**Comment by HeartSaVioR** [comment]
You can do the hack on package private access - create a new class extending VectorizedRowBatchIterator in the same package in your application.

But I'm not sure Iceberg project intends to provide utilities other than Iceberg API as public API. I wonder that is not encouraged to be used outside of Iceberg.
