### ISSUE TITLE
Spark3: Add SQL extension for import/convert table

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#1498]
Currently, we have helper functions in `SparkTableUtil` to import Spark/Hive tables. It would be great if Iceberg provides the SQL extension to the end-user. For example, Delta lake has `CONVERT TO` syntax.

This would depend on Anton's first PR for SQL extension.

**Comment by aokolnychyi** [comment]
We've planned [SNAPSHOT and MIGRATE commands ](https://docs.google.com/document/d/1Nf8c16R2hj4lSc-4sQg4oiUUV_F4XqZKth1woEo6TN8/)and @RussellSpitzer is already working on that.

**Comment by RussellSpitzer** [comment]
Yep I should have a PR up soon for the backing "spark actions" which we'll
be able to plug into our new Extensions very easily

**Comment by chenjunjiedada** [comment]
Thanks @aokolnychyi and @RussellSpitzer , Looking forward to this.
