### ISSUE TITLE
The iceberg-flink jar in the maven repository is incomplete

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1510]
The iceberg-flink jar I downloaded from the maven repository is incomplete (https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-flink/0.9.1/iceberg-flink-0.9.1.jar), the lack of some class files and other configuration files, such as org.apache.flink.table.factories.TableFactory, leads to an error when using maven project development.

I decompressed the jar downloaded from the maven repository, and then used the linux tree command to list all the files，As follows：

├── LICENSE
├── META-INF
│   └── MANIFEST.MF
├── NOTICE
└── org
    └── apache
        └── iceberg
            └── flink
                ├── data
                │   ├── FlinkAvroReader$1.class
                │   ├── FlinkAvroReader.class
                │   ├── FlinkAvroReader$RowReader.class
                │   ├── FlinkAvroWriter$1.class
                │   ├── FlinkAvroWriter.class
                │   ├── FlinkAvroWriter$RowWriter.class
                │   ├── FlinkParquetReaders.class
                │   ├── FlinkParquetReaders$RowReader.class
                │   ├── FlinkParquetWriters$1.class
                │   ├── FlinkParquetWriters.class
                │   └── FlinkParquetWriters$RowWriter.class
                ├── FlinkSchemaUtil.class
                ├── FlinkTypeToType.class
                └── FlinkTypeVisitor.class

**Comment by zhangjun0x01** [comment]
hi,@openinx 

I am not sure if this is an issue, but in my program I did introduce the jar of the maven warehouse, and some exceptions that the factory class could not be loaded would be reported. I finally found the reason is that the jar does not have the SPI configuration file. 
`org.apache.flink.table.factories.TableFactory`

**Comment by openinx** [comment]
@zhangjun0x01  the flink sink connector in 0.9.1 is not complete,  the real available release version would be iceberg 0.10.0,   I guess the time point would be Oct.  Also,   the flink users won't depend on this `flink-iceberg.jar` directly,  instead they would use `flink-iceberg-runtime.jar`  which have shaded the common dependency jars such as guava etc. 

For now, if you want to test this feature,  you might need to build the `flink-iceberg-runtime` jar by building the iceberg project now.  

So this issue could be closed now, right ?

**Comment by zhangjun0x01** [comment]
ok,I will close it
