### ISSUE TITLE
The document can't perfectly display on mac 13 inch

### ISSUE THREAD

**Issue by lordk911** [apache/iceberg#1524]
document ：http://iceberg.apache.org/spark/  it's left sidebar can't perfectly display:

![image](https://user-images.githubusercontent.com/19989300/94411752-84900b00-01ab-11eb-9c7b-34950cca57a6.png)

some thing missed.

**Comment by kbendick** [comment]
Thanks for bringing this up. As mentioned in the really large footer, we use [MkDocs](https://www.mkdocs.org/) for generating the documentation.

I'm not incredibly familiar with the MkDocs system and how we configure it (especially the UI theme), but this feels like an issue that might be brought up to them.

I'll let anybody with more experience in how the docs are generated chime in if they can.
