### ISSUE TITLE
TestCatalogs temporary folder created in wrong location and not cleaned up

### ISSUE THREAD

**Issue by marton-bod** [apache/iceberg#1534]
`TestCatalogs.testCreateDropTableToLocation` creates a temporary folder in the wrong location and fails to clean it up in the end. That's because `tmp.toString()` is used in a couple of places:
https://github.com/apache/iceberg/blob/master/mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java#L110
https://github.com/apache/iceberg/blob/master/mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java#L130 

`tmp.toString()` gives back the default string representation of `TemporaryFolder`, e.g. `org.junit.rules.TemporaryFolder@6688b3d0`. When adding the `location` property to the properties using this method, we end up creating a directory called `org.junit.rules.TemporaryFolder@6688b3d0` inadvertently. Instead of `tmp.toString()`, we should use `tmp.getRoot()` to resolve this issue.

**Comment by HeartSaVioR** [comment]
Looks like the PR got merged - mind closing the issue? Thanks!

**Comment by marton-bod** [comment]
Sure, thanks for the reminder!
