### ISSUE TITLE
Dynamically load LocationProvider implementation

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#1538]
Currently the `LocationProviders` class only load either `DefaultLocationProvider` which follows the Hive standard or the `ObjectStoreLocationProvider` that is optimized for cloud storage use case. Use cases like #1531 will become increasingly common, and we should allow users to load their custom location providers without the need to change core package.

Therefore, I propose dynamically loading the `LocationProvider` implementation in the method `LocationProviders.locationsFor` and use new table property `write.location-provider.class` to determine the class. Table property `write.object-storage.enabled` will still be supported to keep backwards compatibility.

Plan to submit a PR in 1-2 days, please let me know if there is any concern, thanks.

**Comment by mickjermsurawong-stripe** [comment]
This PR https://github.com/apache/iceberg/issues/1538 was re-purposed from solving specific problem of data localization to address this more general use case.
