### ISSUE TITLE
numBuckets can cause division by zero

### ISSUE THREAD

**Issue by gaborkaszab** [apache/iceberg#1543]
The numBuckets member in Bucket class is not verified and I managed to create a table with a Bucket partition with zero buckets. This later could cause an exception due to modulo by zero here:
https://github.com/apache/iceberg/blob/c28d1c8ba6322af07f0206c4cf3fdad875f37ac1/api/src/main/java/org/apache/iceberg/transforms/Bucket.java#L87

**Comment by zhangdove** [comment]
We can do some validation on the input parameters when creating the bucket partition.

**Comment by zhangdove** [comment]
It seems that some time has passed and there is no reply. I would provide a relevant PR to fix this small problem.
