### ISSUE TITLE
Consider adding extra validation for metrics config when creating a table

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1548]
What I see frequently is that people clone some examples but miss to update the metrics config. As a result, it points to fields that don't exist. I think we should consider doing some checks while creating a table to ensure metrics config references columns in our schema. It is important to get the metrics config right while creating a table.

**Comment by aokolnychyi** [comment]
@holdenk, would you have time to look into this? Not urgent.

**Comment by SteNicholas** [comment]
@aokolnychyi IMO, `MetricsConfig` could add `validateProperties` method to check metrics config references columns in schema, and the method should be called in `createTable()`.   Is this similar with your point?

**Comment by aokolnychyi** [comment]
@SteNicholas, yeah, that's something I had in mind.

**Comment by holdenk** [comment]
Rocking, I've finally got a bit of time for next week, I'll pick this up :)
