### ISSUE TITLE
Create an action to clean up tables

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1549]
I think we need an action to clean up tables that would use metadata tables to figure out which files must be removed. Then we can construct a table using `StaticTableOperations` and leverage the action to clean up locations in DROP TABLES and while aborting creation of staged tables. The logic to find out what files must be deleted is already available in `BaseAction`.

**Comment by aokolnychyi** [comment]
This should replace the existing logic that finds out what files must be removed on the driver.

**Comment by aokolnychyi** [comment]
@holdenk, would you have time to look into this? Not urgent.

**Comment by holdenk** [comment]
Sure I can try :)

**Comment by aokolnychyi** [comment]
@karuppayya here is the item we talked about. I think Holden will be busy with some Spark tasks and the create table validation so it would be great if you could pick it up.

**Comment by aokolnychyi** [comment]
This has been done.
