### ISSUE TITLE
Add AvroRecordTaskWriterFactory for Flink sink

### ISSUE THREAD

**Issue by stevenzwu** [apache/iceberg#1555]
For stream writer, incoming data can come in as Avro record as Avro schema is pretty popular with streaming source (like Kafka). Instead of inefficiently converting Avro Record to Flink Row, we can implement a native writer support for Avro Record.

**Comment by stevenzwu** [comment]
@openinx @JingsongLi @rdblue I am thinking about pushing our Avro writer upstream. this is the tracking issue.

**Comment by rdblue** [comment]
I would rather not use the Avro object model upstream, since it has some serious problems:
* No support for date/time types
* No support for decimal
* No support for non-string map keys

And, accepting Avro records introduces issues when users have records with unsupported union types.

How about using the Iceberg generic records upstream instead?

**Comment by stevenzwu** [comment]
@rdblue that is fair. we will keep the Avro writer locally then. We can revisit the decision if there are more askings.

I definitely see a need for Iceberg GenericRecord upstream. E.g. we have a user asking for non-string Map key.

But since we are using Avro for Kafka data, I would rather avoid the type conversion btw Avro GenericRecord and Iceberg GenericRecord. In a nutshell, internally we probably would need both Avro and Iceberg Record support.

**Comment by rdblue** [comment]
I agree, we probably need both. We should be able to use Iceberg generics directly for most internal uses. It is easier the more we move toward Iceberg schemas for streams, too.

**Comment by openinx** [comment]
If we write records by using avro writer directly and there are data types that we iceberg don't support, then other compute engine readers could not read the avro record correctly, that sounds a big risk ?   Did your internal users write any iceberg unsupported avro types ? 

Accepting the GenericRecords  sounds good to me.

**Comment by rdblue** [comment]
We would just have to fail if an Avro record used a union schema. I don't think we've hit this case internally. We did hit the case where users wanted to write maps with numeric keys, though.

**Comment by stevenzwu** [comment]
@openinx I don't think there is risk. if Avro schema is incompatible (like non-optional union usage) with Iceberg schema, I would think write will fail. On the other hand, for the streaming path we do internally limit the Avro schema features that are compatible with Iceberg schema.
