### ISSUE TITLE
[Flink] dropTable(...) does not remove all parquet files while the table is dropped

### ISSUE THREAD

**Issue by elkhand** [apache/iceberg#1556]
While using `dropTable()` with the purge flag set to true in Flink, does not completely remove parquet files when the table is dropped. 

How to proceed so that when the table is dropped all data is purged and removed?

I’m using Apache Iceberg `96959ec` build from the master branch.

The table is created via HiveCatalog, the data is stored on S3.
```
Configuration hadoopConf = getHadoopConfig(false);
Catalog icebergCatalog = new HiveCatalog(hadoopConf);
TableIdentifier tableIdentifier = getTableIdentifier();
final Table table = icebergCatalog.createTable(tableIdentifier, schema, spec);
```
While using `catalog.dropTable(tableIdentifier, true)` feature, I see that some of the parquet files are still leftover even after the table is dropped. Even with `overwrite=true` flag, Parquet files on S3 are not deleted.
```
if (icebergCatalog.tableExists(tableIdentifier)) {
    Table existingTable = icebergCatalog.loadTable(tableIdentifier);
    boolean dropped =  icebergCatalog.dropTable(tableIdentifier, true);
    # dropped evaluates to true
    boolean tableExists = icebergCatalog.tableExists(tableIdentifier)
    # tableExists evaluates to false
}
```
The leftover parquet files scenario happens both for partitioned and unpartitioned tables.

I even set `overwrite=true` FlinkSink creation time, which did not help either to completely remove parquet files when the table is dropped.
```
FlinkSink.forRow(dataEventStream, tableSchema)
   .table(table)
   .tableLoader(tableLoader)
   .hadoopConf(hadoopConf)
   .overwrite(true)
   .build()
   .setParallelism(parallelism);
```
Some of the leftover parquet files in kilobytes, some are in megabytes.

Thanks.

**Comment by kbendick** [comment]
Thanks for bringing up this issue @elkhand! When you were running the Flink pipeline that was writing to these tables, was it the only writer? Additionally, were there any restarts of the job (due to task manager fail over, etc)?

**Comment by openinx** [comment]
@elkhand  we're responsible for maintaining the apache flink iceberg sink connector.   Just curious : did you have any log message such as the following ? 

```
 LOG.info("Dropped table: {}", identifier);
```

or 

```
LOG.info("Skipping drop, table does not exist: {}", identifier, e);
```

Is it possible that we've provided a non-existing table identifier ?

**Comment by elkhand** [comment]
I did retry with a clean table. 
I confirm the drop table worked as expected, and removed all the data.
Thanks.
