### ISSUE TITLE
Problem inserting data into a table with structs (iceberg-spark)

### ISSUE THREAD

**Issue by cccs-dm** [apache/iceberg#1560]
Hello!

It seems there's a bug trying to insert data into a table containing a Spark StructField.
I can create a table without any issues:

```
sc = spark.sparkContext
df = SQLContext(sc).range(0, 1000)
df = df.withColumn("MARK", F.struct(F.lit(7)))
df.write.option("path", outputPath).format("iceberg").saveAsTable(tableName)
```

But when I try to insert more data in this table, I get an exception:

`df.write.mode("overwrite").insertInto(tableName)`

Here's a full example to reproduce the issue:

```
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql import functions as F
from pyspark.sql.types import *
import os
spark = ( SparkSession.builder
    .master('local')
    .appName("iceberg_spark_bug")
    .config("spark.executor.memory", "2g")
    .config("spark.cores.max", 12)
    .config("spark.sql.sources.partitionOverwriteMode", "dynamic")
    .config("spark.sql.files.maxPartitionBytes", "1g")
    .config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog")
    .config("spark.sql.catalog.spark_catalog.type", "hive")
    .config("spark.sql.catalog.hive_dev", "org.apache.iceberg.spark.SparkCatalog")
    .config("spark.sql.catalog.hive_dev.type", "hive")
    .enableHiveSupport()
    .getOrCreate())
tableName = "iceberg_spark_bug"
outputPath = "file:///tmp/"+tableName
sc = spark.sparkContext
# Use range to create a DF with an id column containing a long from 0 to 1000.
df = SQLContext(sc).range(0, 1000)
# Let's add a dumb struct with a single integer column filled with 7
df = df.withColumn("MARK", F.struct(F.lit(7)))
df.write.option("path", outputPath).format("iceberg").saveAsTable(tableName)
df.write.mode("overwrite").insertInto(tableName)
spark.stop()
``` 

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<ipython-input-16-03570806093c> in <module>
----> 1 df.write.mode("overwrite").insertInto(tableName)

/usr/local/spark/python/pyspark/sql/readwriter.py in insertInto(self, tableName, overwrite)
    838         if overwrite is not None:
    839             self.mode("overwrite" if overwrite else "append")
--> 840         self._jwrite.insertInto(tableName)
    841 
    842     @since(1.4)

/usr/local/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/usr/local/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    135                 # Hide where the exception came from that shows a non-Pythonic
    136                 # JVM exception message.
--> 137                 raise_from(converted)
    138             else:
    139                 raise

/usr/local/spark/python/pyspark/sql/utils.py in raise_from(e)

AnalysisException: unresolved operator 'OverwriteByExpression RelationV2[id#42L, MARK#43] spark_catalog.default.iceberg_spark_bug, true, false;;
'OverwriteByExpression RelationV2[id#42L, MARK#43] spark_catalog.default.iceberg_spark_bug, true, false
+- Project [id#31L, struct(col1, 7) AS MARK#33]
   +- Range (0, 1000, step=1, splits=Some(12))

**Comment by HeartSaVioR** [comment]
Spark version and Iceberg version, and the table schema, please?

**Comment by cccs-dm** [comment]
I am using Spark 3.0.0 and Iceberg 0.9.0.

Here's the table schema:
```
            "schema": {
                "fields": [
                    {
                        "metadata": {},
                        "name": "id",
                        "nullable": false,
                        "type": "long"
                    },
                    {
                        "metadata": {},
                        "name": "MARK",
                        "nullable": false,
                        "type": {
                            "fields": [
                                {
                                    "metadata": {},
                                    "name": "col1",
                                    "nullable": false,
                                    "type": "integer"
                                }
                            ],
                            "type": "struct"
                        }
                    }
                ],
                "type": "struct"
            }
```

Thanks.

**Comment by HeartSaVioR** [comment]
I figured out as Spark bug which may exist only on Spark 3. Filed https://issues.apache.org/jira/browse/SPARK-33136 and will submit a PR on Spark repo.

**Comment by HeartSaVioR** [comment]
The PR for SPARK-33136 is merged and will be shipped to Spark 3.0.2 / 3.1.0. Shall we close this, or would someone like to build the Spark on branch-3.0 and verify on their end?

**Comment by NJordan72** [comment]
I think it is safe to close.  I haven't been able to confirm with the patch, but using some casts I was able to match the nullability and I can confirm that fixed the problem.

**Comment by HeartSaVioR** [comment]
Thanks @NJordan72 for confirming! Could you please close this issue, @cccs-dm ?

**Comment by cccs-dm** [comment]
Sure thing! Thanks for fixing it so quickly.
