### ISSUE TITLE
build iceberg failed: can't resolve dependency (ORC-1.6.5)

### ISSUE THREAD

**Issue by liukun4515** [apache/iceberg#1584]
Could not determine the dependencies of task ':iceberg-flink-runtime:shadowJar'.
> Could not resolve all dependencies for configuration ':iceberg-flink-runtime:compile'.
   > Could not resolve org.apache.orc:orc-core:1.6.5.
     Required by:
         project :iceberg-flink-runtime > project :iceberg-flink > project :iceberg-orc
      > Could not resolve org.apache.orc:orc-core:1.6.5.
         > Could not get resource 'http://palantir.bintray.com/releases/org/apache/orc/orc-core/1.6.5/orc-core-1.6.5.pom'.
            > Could not GET 'http://palantir.bintray.com/releases/org/apache/orc/orc-core/1.6.5/orc-core-1.6.5.pom'.

**Comment by HeartSaVioR** [comment]
Could you please post the error message? Looks like Orc 1.6.5 is released and available in maven central.
https://search.maven.org/artifact/org.apache.orc/orc/1.6.5/pom

**Comment by liukun4515** [comment]
cc @HeartSaVioR

**Comment by liukun4515** [comment]
The issue is about my firewall and will be closed
