### ISSUE TITLE
Spark SQL Extensions: Introduce spark3-extensions module

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1589]
Introduce a new module and set up parsing logic for Spark SQL extensions.

**Comment by aokolnychyi** [comment]
This one is on me.

**Comment by zhangjun0x01** [comment]
I think we should extract some common functions when designing the code, because we should also do flink sql extension in the future

**Comment by aokolnychyi** [comment]
@zhangjun0x01 Does Flink support stored procedures or being able to plugin extensions like Spark?

**Comment by zhangjun0x01** [comment]
hi,@aokolnychyi 
I don't know whether flink supports stored procedures, but I see that the source code of flink has a related sqlnode extension interface. I think we should be able to do sql extension by implementing this interface.

https://github.com/apache/flink/blob/master/flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ExtendedSqlNode.java

**Comment by aokolnychyi** [comment]
Done in #1728.
