### ISSUE TITLE
Spark SQL Extensions: Expire snapshots

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1597]
Until we have a proper VACUUM command, we can expose a stored procedure for expiring snapshots. 

```
CALL catalog.schema.expire_snapshots(
  namespace  => 'namespace_name'
  table => 'table_name',
  older_than => timestamp,
  retain_last => number
)
```

The output from this command may include the number of deleted data, manifest, manifest list files.

I think we should make the older_than and retain_last args optional and require at least one to be present. It seems Presto recently added support for optional args in procedures. 

Then we can expire snapshots that are older than a given interval:

```
CALL catalog.schema.expire_snapshots(
  namespace => 'namespace_name',
  table => 'table_name',
  older_than => CURRENT_TIMESTAMP() - INTERVAL '7' DAYS
)
```

We can also provide a minimum number of snapshots to keep:

```
CALL catalog.schema.expire_snapshots(
  namespace => 'namespace_name',
  table => 'table_name',
  older_than => CURRENT_TIMESTAMP() - INTERVAL '7' DAYS,
  retain_last => 100
)
```

Or just give a number of snapshots to keep:

```
CALL catalog.schema.expire_snapshots(
  namespace => 'namespace_name',
  table => 'table_name',
  retain_last => 100
)
```

Or give a specific point in time:

```
CALL catalog.schema.expire_snapshots(
  namespace => 'namespace_name',
  table => 'table_name',
  older_than => TIMESTAMP '2020-01-19 03:14:07',
  retain_last => 100
)
```

**Comment by aokolnychyi** [comment]
@liukun4515 has expressed interest in working on this.

**Comment by liukun4515** [comment]
@aokolnychyi 
```
CALL catalog.schema.expire_snapshots(
  namespace => 'namespace_name',
  table => 'table_name',
  retain_last => 100
)
```
In the `expire snapshot` API, if we only give the `retain last num` for a table, the commit action is invalid.

the apply code is:
```
  private TableMetadata internalApply() {
    this.base = ops.refresh();

    TableMetadata updateMeta = base.removeSnapshotsIf(snapshot ->
        idsToRemove.contains(snapshot.snapshotId()) ||
        (expireOlderThan != null && snapshot.timestampMillis() < expireOlderThan &&
            !idsToRetain.contains(snapshot.snapshotId())));
    List<Snapshot> updateSnapshots = updateMeta.snapshots();
    List<Snapshot> baseSnapshots = base.snapshots();
    return updateSnapshots.size() != baseSnapshots.size() ? updateMeta : base;
  }
```
if the `expireOlderThan` is not set, the `retain last num` or `idsToRetain` is invalid.

**Comment by aokolnychyi** [comment]
I'd make both `older_than` and `retain_last` optional and require at least one to be present. If only `retain_last` is present, I'd default `timestamp` to the current timestamp. 

The following would keep only 100 last snapshots, for example.

```
CALL catalog.schema.expire_snapshots(
  namespace => 'namespace_name',
  table => 'table_name',
  retain_last => 100
)
```

**Comment by liukun4515** [comment]
> I'd make both `older_than` and `retain_last` optional and require at least one to be present. If only `retain_last` is present, I'd default `timestamp` to the current timestamp.

I agree with the default timestamp (current time) for `older_than`, but what's the default time zone?

**Comment by liukun4515** [comment]
please assign the issue to me!

**Comment by liukun4515** [comment]
> I'd make both `older_than` and `retain_last` optional and require at least one to be present. If only `retain_last` is present, I'd default `timestamp` to the current timestamp.

In the procedure SQL：
```
CALL catalog.schema.expire_snapshot(
    namespace => 'namespace_name',
    table => 'table_name'
)
```
if the `expire snapshot sql` lacks the two parameters `retain_last` and `older_than`, how to tell the user where the error occurred?

**Comment by aokolnychyi** [comment]
Can we just use `System.currentTimeMillis`? Spark returns us `java.sql.Timestamp` that is time zone agnostic, I guess.

**Comment by liukun4515** [comment]
> Can we just use `System.currentTimeMillis`? Spark returns us `java.sql.Timestamp` that is time zone agnostic, I guess.

The `system.currenttimestamp` is the absolute time which does need to consider the time zone.
