### ISSUE TITLE
Spark SQL Extensions: Remove orphan files

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1599]
We can define the following stored procedure for removing orphan files.

```
CALL catalog.schema.remove_orphan_files(
  namespace => 'namespace_name',
  table => 'table_name',
  older_than => timestamp,
  ignore_scheme => true, -- optional
  ignore_authority => true, -- optional
  dry_run => true -- optional
)
```

The stored procedure should return a list of file locations that are considered orphan.

It can be called with an interval:

```
CALL catalog.schema.remove_orphan_files(
  namespace => 'namespace_name',
  table => 'table_name',
  older_than => CURRENT_TIMESTAMP - INTERVAL '5' DAYS,
  dry_run => true
)
```

Or with a given timestamp:

```
 CALL catalog.schema.remove_orphan_files(
  namespace => 'namespace_name',
  table => 'table_name',
  older_than => TIMESTAMP '2020-01-19 03:14:07',
  dry_run => false
)
```

**Note**: we must validate `older_than` is large enough. We should either force it to be at least 1 day old or allow users to configure the min interval through table properties.

**Comment by aokolnychyi** [comment]
Let me know if anybody is interested in working on this.

**Comment by RussellSpitzer** [comment]
@jbirtman You may want to check this out, once the Procedure API is finalized this should be a pretty straightforward task

**Comment by liukun4515** [comment]
> Let me know if anybody is interested in working on this.

Can I take this task?

**Comment by liukun4515** [comment]
I am working on this issue.

**Comment by aokolnychyi** [comment]
We can probably skip `ignore_scheme` and `ignore_authority` for now since we haven't agreed on this yet.

**Comment by aokolnychyi** [comment]
Thanks for working on this one, @liukun4515!

Unfortunately, GitHub did not pick the commit annotation.

```
Lead-authored-by: Kun Liu <liukun@apache.org>
Co-authored-by: Anton Okolnychyi <aokolnychyi@apple.com>
```
