### ISSUE TITLE
Spark SQL Extensions: Document all stored procedures

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1601]
We should update publics docs once stored procedures are implemented.

**Comment by RussellSpitzer** [comment]
https://github.com/apache/iceberg/pull/3334

**Comment by atifiu** [comment]
@RussellSpitzer Are there any procedures left which are still not documented. I am willing to work on the same. Also I would suggest to add more details about the column of metadata tables such as "manifests" to explain their usage.

**Comment by RussellSpitzer** [comment]
@atifu
