### ISSUE TITLE
Create JDBC-based Catalog

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#1634]
I've been working on a docker-compose based demo.

One thing that I've wanted to avoid is having to have too many dependencies on the classpath just to set up the metastore.

When talking to @rdblue about it, he suggested that we might implement a JDBC Catalog. Ryan suggested to create a single table with an entry for each Iceberg table.

Especially as we are adding other Catalogs at the moment, this will hopefully be a useful addition for people who don't have a full Hive based data lake.

**Comment by kbendick** [comment]
I'll work on this.

**Comment by kbendick** [comment]
Ahhh my bad. I've been really busy with other things and have let this sit. I have an implementation that works with Spark that I was going to open up this weekend or early next week after cleaning it up, but it seems you've beaen me to it @ismailsimsek

**Comment by rdblue** [comment]
Yeah, please help with reviews, @kbendick! This happens, but we can all benefit from taking the best of the two approaches.

**Comment by ismailsimsek** [comment]
@kbendick I thought this will be good feature to learn iceberg and implement. I'm ok to continue whichever implementain looks good to you? Is it possible to combine best from both?

**Comment by gf-brian** [comment]
To anyone following in my footsteps: attached is schema I used to create an Iceberg JDBC catalog that Trino v455 would use. May it help in your journey.
[Iceberg_JDBC_Catalog_Schema.txt](https://github.com/user-attachments/files/16922626/Iceberg_JDBC_Catalog_Schema.txt)
