### ISSUE TITLE
[Bug] Metric filtering skips row groups incorrectly on older Parquet files

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#1635]
When older files are read with Iceberg the metrics are improperly evaluated. We incorrectly assumes that there are 0 nonNull values in every row group which leads to the reader skipping all row groups. 

https://github.com/RussellSpitzer/iceberg/blob/4d1fc91d6528db88548c506a0b110b50121d67ff/parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java#L299-L302

In a Parquet 1.5.0 file we were working with the stats for `String` columns are reported as 

`[num_nulls: 0, min/max not defined]`

For all row groups

This causes `colStats.isEmpty` to be false because these are valid settings while also returning false for  `hasNonNullValues`.

This leads us to returned `ROWS_CANNOT_MATCH` and skip the row group.

These failures make any filter pushdown to the files return 0 records regardless of whether or not the filter actually matches anything.

**Comment by RussellSpitzer** [comment]
I *think* the right thing to do here is to not rely on hasNonNullValues and also check if rowCount > numNull. I'll check other readers tomorrow to see how they deal with the issue

**Comment by rdblue** [comment]
Are there non-null values in the row group?

**Comment by RussellSpitzer** [comment]
Yes, there are only non null values in the row group

**Comment by kbendick** [comment]
I can take a stab at this if you dont have time @RussellSpitzer

**Comment by kbendick** [comment]
Do you know if there's a version number at which this is fixed? Are we able to tell which version the files were written with and possibly check that? I imagine not, as they usually say the writer type and I don't think parquet files usually have the parquet version in them, more the spark version etc. But a thought.

**Comment by RussellSpitzer** [comment]
All I know for sure is we had a user with 1.5.0-Cloudera build of Parquet
Files. I haven't actually explored past the point where we figured out this
was the issue. I know in 1.11 there is no problem since when I initially
tried to repo this issue by just faking their data it was fine. The issue
only repo'd when I took an actual file they had and imported them into a
new Iceberg table.

**Comment by RussellSpitzer** [comment]
The issue is "hasNonNull" was only added in 1.7 
https://github.com/apache/parquet-mr/commit/4bf9be34a87b51d07e0b0c9e74831bbcdbce0f74


Prior to this "isEmpty" had a different definition as well

https://github.com/apache/parquet-mr/blame/d70fdbc40195077057a1edb14ccd16a26435d007/parquet-column/src/main/java/parquet/column/statistics/Statistics.java#L222-L224

So I think out best thing to do is again to not rely only on "hasNonNull"

**Comment by RussellSpitzer** [comment]
Ok just fixing the nonnull check is not sufficient because the min and max values cannot be serialized correctly either. I wrote a quick test to just manual check for nonnull s and when you do that it crashes attempting to check the min and max bounds

**Comment by RussellSpitzer** [comment]
@kbendick I think it's probably best I take this one since I have the active repo, Should be ready soon.

**Comment by RussellSpitzer** [comment]
Ok I can get repos on Hive 1.Latest and Hadoop 2.Latest. The default config there produces Parquet-mr 1.6 which has the same issue.

**Comment by RussellSpitzer** [comment]
So this is a bit more complicated. This bug only effects files made by parquet versions not effected by

https://github.com/apache/parquet-mr/pull/197/files

And also made after 1.7

This means it should only effect Parquet Files made by Cloudera Parquet builds since they are the only pre 1.7.0 builds which also have valid statistics which can be read

**Comment by RussellSpitzer** [comment]
PR up https://github.com/apache/iceberg/pull/1638
