### ISSUE TITLE
How to excute checktyle in interllij-idea 

### ISSUE THREAD

**Issue by wg1026688210** [apache/iceberg#1653]
I found  file   '.baseline/idea/intellij-java-palantir-style.xml' in project ,but I don't know how to use it in idea.

**Comment by RussellSpitzer** [comment]
I'll write up some docs for this if you haven't figured it out yet, also you want to use .baseline/checkstyle/checkstyle.xml

**Comment by wg1026688210** [comment]
hi~ @RussellSpitzer  I have resolved it ,  I think it's a good idea to add some docs for somebody  who want to join iceberg community
