### ISSUE TITLE
Action: support spark3 and customer catalog

### ISSUE THREAD

**Issue by liukun4515** [apache/iceberg#1662]
In the spark2.4, the action uses the interface `spark.read().format("iceberg").load(table)` to load the table as the dataset.
But It just can load the default spark catalog(`spark_catalog`) table, and the `table` is `db.tablename`.
If I want to use the action to handle some tables which are in the other iceberg customer catalog, there will throw an exception referred to the #1652.

**Comment by HeartSaVioR** [comment]
When you deal with DataFrameWriterV1 you may want to "forget about" catalog, and also want to "double-check about" how the "path" is interpreted for the format (data source).

Btw what's the use case we would like to touch some tables in other catalog?

**Comment by RussellSpitzer** [comment]
I thought you could still load it directly from the path (ignoring the other catalogs?)

**Comment by RussellSpitzer** [comment]
I think I understand the point now,

We want to invoke an action on a table whose identifier cannot be read using the current logic in BaseAction to generate metadata tables.

**Comment by liukun4515** [comment]
> I think I understand the point now,
> 
> We want to invoke an action on a table whose identifier cannot be read using the current logic in BaseAction to generate metadata tables.

@RussellSpitzer 

I'm working on the SQL extension(remove orphan files), and want to use the spark action to implement it.
But the current actions just support spark2.

**Comment by RussellSpitzer** [comment]
Yep we'll have to make some modifications. I think probably a first step is just only making the extensions work for the default catalog. But otherwise we need to start extending some of the methods in the base class so they properly handle multi-part identifiers and we determine how to load up metadata tables properly for tables in other catalogs.

**Comment by liukun4515** [comment]
> Yep we'll have to make some modifications. I think probably a first step is just only making the extensions work for the default catalog. But otherwise we need to start extending some of the methods in the base class so they properly handle multi-part identifiers and we determine how to load up metadata tables properly for tables in other catalogs.

There are pull requests about the modifications?

**Comment by RussellSpitzer** [comment]
Not yet, but obviously we will need to make some :)

**Comment by liukun4515** [comment]
Is this #1525 pr is about supporting spark3 action?
@RussellSpitzer
