### ISSUE TITLE
Optimize generation of CombinedScanTask for RewriteDataFilesAction

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1667]
In RewriteDataFilesAction, the default value of targetSizeInBytes is 128M, if there are the following data files: 20M, 20M, 20M, 70M, 100M,The current logic is to scan these data file in turn until the sum of the data file sizes  <= targetSizeInBytes,
So three CombinedScanTask tasks will be generated, (20M, 20M, 20M), (70M), (100M).

Obviously, it is more appropriate to generate two CombinedScanTask tasks (20M, 20M, 70M), (20M, 100M).

We should optimize this algorithm to generate as few target data files as possible and make its size as close to targetSizeInBytes as possible.

**Comment by rdblue** [comment]
What alternative algorithm would you suggest? The current algorithm is simple and I'm sure could be improved.

**Comment by zhangjun0x01** [comment]
My idea is to use the dynamic programming algorithm to get an optimal result, but I haven't implemented this algorithm yet. I will think about how to do it and do a test later

**Comment by kingeasternsun** [comment]
It seems like a Knapsack problem

**Comment by RussellSpitzer** [comment]
We should really get in my Medium Files PR first which would fix the
suggested layout ^ (if the blocks were the right sizes)
https://github.com/apache/iceberg/pull/3292
