### ISSUE TITLE
Iceberg table hive and Flink cannot read or write to each other?

### ISSUE THREAD

**Issue by paulzanmei** [apache/iceberg#1684]
I tried to create a table on flink to write data into it, and use hive to re-read the table and it was empty; I created a table on hive, but I couldn’t write to it using flink.

Metadata uses HiveCatalog

Is there any solution？

**Comment by RussellSpitzer** [comment]
Could you explain step by step what you did and what you expected to have happen? For example how you created the table and then how you attempted to read from it, what tools were you using etc?

**Comment by openinx** [comment]
Yeah,  I think we need more context ( such as how did you test those cases step by step ) to help find out what's wrong. Thanks.

**Comment by paulzanmei** [comment]
@RussellSpitzer   @openinx  
My expectation is to use hive to create an iceberg table, use flink to write data, and then use hive and Presto to query and analyze the data


Operation steps:

hive:
1.  add jar /path/to/iceberg-hive-runtime.jar
2. CREATE EXTERNAL TABLE customers
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
TBLPROPERTIES ('iceberg.mr.table.schema'='{"type":"struct","fields":[{"id":1,"name":"customer_id","required":true,"type":"long"},{"id":2,"name":"first_name","required":true,"type":"string"}]}');

flink:
3. 
tableEnv.executeSql("CREATE CATALOG iceberg_catalog WITH (\n" + 
    			"  'type'='iceberg',\n" + 
    			"  'catalog-type'='hive',\n" + 
    			"  'uri'='thrift://dcwork03:9083',\n" + 
    			"  'default-database'='test',\n" + 
    			"  'clients'='5',\n" + 
    			//"  'warehouse'='/user/hive/warehouse',\n" + 
    			"  'hive-conf-dir'='/Users/zhongbaoluo/Applications/app/apache-hive-3.1.2/conf/',\n" + 
    			"  'property-version'='1'\n" + 
    			")");
4. 
tableEnv.executeSql("INSERT INTO iceberg_catalog.test.customers SELECT `customer_id`,first_name from datagen").print();

5. 

tableEnv.executeSql("SELECT `customer_id`,first_name from iceberg_catalog.test.customers").print();

hive:

6. 
select * from customers;


problem:

1.   The data actually inserted into the iceberg/data file by flink already exists, and flink run cannot be stopped. The next select sql query also has no data.
![image](https://user-images.githubusercontent.com/20592867/97662661-974f7580-1ab2-11eb-8bde-96c2c7e4b96b.png)

2. Hive query statement is also empty table

![image](https://user-images.githubusercontent.com/20592867/97662819-0200b100-1ab3-11eb-9b0b-18639b25bc90.png)

**Comment by paulzanmei** [comment]
1. hive create table
CREATE EXTERNAL TABLE customers
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
LOCATION '/data/iceberg_catalog/test/customers'
TBLPROPERTIES ('iceberg.mr.table.schema'='{"type":"struct","fields":[{"id":1,"name":"customer_id","required":true,"type":"long"},{"id":2,"name":"first_name","required":true,"type":"string"}]}');

2. flink operation table
tableEnv.executeSql("CREATE CATALOG iceberg_catalog WITH (\n" + 
    			"  'type'='iceberg',\n" + 
    			"  'catalog-type'='hive',\n" + 
    			"  'uri'='thrift://dcwork03:9083',\n" + 
    			"  'default-database'='test',\n" + 
    			"  'clients'='5',\n" + 
    			"  'warehouse'='/data/iceberg_catalog/test/customers',\n" + 
    			//"  'hive-conf-dir'='/Users/zhongbaoluo/Applications/app/apache-hive-3.1.2/conf/',\n" + 
    			"  'property-version'='1'\n" + 
    			")");

tableEnv.executeSql("SELECT `customer_id`,first_name from iceberg_catalog.test.customers").print();

error:

+----------------------------+
|                 table name |
+----------------------------+
|                  customers |
|                   ld_test1 |
|                     orders |
|                  orders002 |
|                   orders02 |
|                 partitest2 |
|                  t_dc_user |
| t_mpos_integral_sign_water |
|                update_test |
+----------------------------+
9 rows in set
Exception in thread "main" org.apache.flink.table.api.ValidationException: SQL validation failed. From line 1, column 38 to line 1, column 67: Object 'customers' not found within 'iceberg_catalog.test'
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$validate(FlinkPlannerImpl.scala:146)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:108)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:185)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:78)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:684)
	at org.datacloud.flinksql.iceberg.FlinkIcebergApp2.main(FlinkIcebergApp2.java:75)
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 38 to line 1, column 67: Object 'customers' not found within 'iceberg_catalog.test'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:457)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:839)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:824)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5089)
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:173)
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:184)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1110)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1084)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3256)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3238)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3510)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1110)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1084)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1059)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:766)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$validate(FlinkPlannerImpl.scala:141)
	... 5 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'customers' not found within 'iceberg_catalog.test'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:457)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:550)
	... 24 more

Is this unusable?
@RussellSpitzer @openinx

**Comment by openinx** [comment]
The approach looks strange about the test steps,  you created a hive external table by hive firstly,   then created hive catalog in flink, finally you tried to query the table which created in `hive shell` by `flink SQL`  ?   The flink `TableEnvironment` won't know there's a created table named `customers` unless you register this table to `TableEnvironment` explicitly,  while I saw that  it will only `register` table when executing `CREATE TABLE`.     However,  if we `CREATE TABLE` again in flink sql, then it will throw a `TableAlreadyExistException`. 

I will suggest creating table in flink sql shell rather than hive shell.

**Comment by paulzanmei** [comment]
> The approach looks strange about the test steps, you created a hive external table by hive firstly, then created hive catalog in flink, finally you tried to query the table which created in `hive shell` by `flink SQL` ? The flink `TableEnvironment` won't know there's a created table named `customers` unless you register this table to `TableEnvironment` explicitly, while I saw that it will only `register` table when executing `CREATE TABLE`. However, if we `CREATE TABLE` again in flink sql, then it will throw a `TableAlreadyExistException`.
> 
> I will suggest creating table in flink sql shell rather than hive shell.

Create a table in the flink sql shell, the data in the table cannot be read through select in the hive sql shell, and the number of returned data is 0.
My ultimate goal is to write data in through flink sql shell, and then query the data through hive and presto, but currently the tables created and written data through flink sql shell cannot be queried through hive and presto

@openinx

**Comment by openinx** [comment]
Hi @paulzanmei 

I tried your case on my local host,  I did not query the hive catalog table ( which is created in flink sql) in hive sql successfully,   but I did the similar thing successfully for hadoop table.  Say the following steps would work: 

Step#1 :  Create a hadoop catalog/database/table in flink sql and then write one record:

```bash
Flink SQL> CREATE CATALOG hadoop_catalog WITH (
>   'type'='iceberg',
>   'catalog-type'='hadoop',
>   'clients'='5',
>   'warehouse'='file:///Users/openinx/test/hive-warehouse1'
> );
[INFO] Catalog has been created.

Flink SQL> show databases;
default_database

Flink SQL> show tables; 
[INFO] Result was empty.

Flink SQL> use catalog hadoop_catalog; 

Flink SQL> show tables;
sample

Flink SQL> insert into sample select 1, 'a';
[INFO] Submitting SQL update statement to the cluster...
[INFO] Table update statement has been successfully submitted to the cluster:
Job ID: 4b4b8c2b1a8d6f876a56f55abe4de1fe
```

Step#2:   Create an external hive table in hive shell: 

```sql
CREATE EXTERNAL TABLE sample_mirror2
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
LOCATION 'file:///Users/openinx/test/hive-warehouse1/default/sample';
```

And show tables: 

```
show tables; 

+-----------------+
|    tab_name     |
+-----------------+
| sample_mirror2  |
+-----------------+
1 rows selected (0.056 seconds)
```

Step#3:  Query the records in hive shell: 

```sql
select * from sample_mirror2;

+--------------------+----------------------+
| sample_mirror2.id  | sample_mirror2.data  |
+--------------------+----------------------+
| 1                  | a                    |
+--------------------+----------------------+
1 row selected (0.86 seconds)
```

I will figure out why it does not work for hive catalog table.  @paulzanmei FYI

**Comment by paulzanmei** [comment]
Hi @openinx   Thank you, the usage you provided can indeed.

I have a question, write data in flink sql, produce source through datagen connector, write to iceberg table

1. Flink creates CATALOG as hive type and can be written successfully

2. Flink creates CATALOG as the hadoop type, and the datagen connector is inserted into the iceberg table. The program keeps running, and hive can't query the data. The file on hdfs has been queried through hadoop.

Step#1 : flink write data

tableEnv.executeSql("CREATE TABLE datagen (\n" + 
    			" `customer_id` BIGINT,\n" + 
    			" first_name STRING,\n" + 
    			" amount INT,\n" + 
    			" ts AS localtimestamp,\n" + 
    			" WATERMARK FOR ts AS ts\n" + 
    			") WITH (\n" + 
    			" 'connector' = 'datagen',\n" + 
    			" -- optional options --\n" + 
    			" 'rows-per-second'='100',\n" + 
    			" 'fields.user.kind'='sequence',\n" + 
    			" 'fields.user.start'='1',\n" + 
    			" 'fields.user.end'='1000',\n" + 
    			" 'fields.amount.min'='1',\n" + 
    			" 'fields.amount.max'='1000',\n" + 
    			" 'fields.product.length'='10'\n" + 
    			")").print();

tableEnv.executeSql("CREATE CATALOG iceberg_catalog WITH (\n" + 
    			"  'type'='iceberg',\n" + 
    			"  'catalog-type'='hadoop',\n" + 
    			//"  'uri'='thrift://dcwork03:9083',\n" + 
    			//"  'default-database'='test',\n" + 
    			//"  'clients'='5',\n" + 
    			"  'warehouse'='/data/iceberg_catalog/test/customers3',\n" + 
    			//"  'hive-conf-dir'='/Users/zhongbaoluo/Applications/app/apache-hive-3.1.2/conf/',\n" + 
    			"  'property-version'='1'\n" + 
    			")");

tableEnv.executeSql("USE CATALOG iceberg_catalog");

tableEnv.executeSql("INSERT INTO customers3 SELECT `customer_id`,first_name from default_catalog.default_database.datagen").print();


The program keeps running without stopping

Step#1 : hive read data

`hive> select * from customers3;
OK
1	a
Time taken: 0.216 seconds, Fetched: 1 row(s)`

`[hive@dcwork01 17:34:09 /app/apache-hive-3.1.2/conf]# hadoop fs -ls /data/iceberg_catalog/test/customers3/default/customers3/data
Found 65 items
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-1faeb5ce-055b-41c2-b692-4f4f5a90f6f8-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-1faeb5ce-055b-41c2-b692-4f4f5a90f6f8-00002.parquet
-rw-r--r--   3 hive hadoop        682 2020-11-02 17:12 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-5243a813-5f89-450d-ac4b-1cfd927dccca-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-58a2b995-fc43-4426-af39-2ff75e165662-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-58a2b995-fc43-4426-af39-2ff75e165662-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-addee3dd-9787-4c66-80ff-f6ab8a75e9d8-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-addee3dd-9787-4c66-80ff-f6ab8a75e9d8-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-d0f4ee74-ab8a-4b83-be12-8b996bc3da64-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00000-0-d0f4ee74-ab8a-4b83-be12-8b996bc3da64-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-05ef151d-6947-4492-8437-57f38ebf1605-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-05ef151d-6947-4492-8437-57f38ebf1605-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-143d2ca4-67a6-417d-b048-f5fb921c5402-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-143d2ca4-67a6-417d-b048-f5fb921c5402-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-4854127f-46f8-472d-99de-4c7f363984a0-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-4854127f-46f8-472d-99de-4c7f363984a0-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-61820fe9-69ef-4744-9de1-bf7edaadc66c-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00001-0-61820fe9-69ef-4744-9de1-bf7edaadc66c-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-086e8481-84e1-4dac-8912-72ab1ed76f59-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-086e8481-84e1-4dac-8912-72ab1ed76f59-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-5f498d83-665d-43fa-8372-768f81d703a8-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-5f498d83-665d-43fa-8372-768f81d703a8-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-73ea0a23-6004-4c71-8b16-5d1c4902cf56-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-73ea0a23-6004-4c71-8b16-5d1c4902cf56-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-b725e121-0e5d-4a65-9e6f-7410c34af304-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00002-0-b725e121-0e5d-4a65-9e6f-7410c34af304-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-0fea48da-1d3d-43a1-8ea2-a547735c89a1-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-0fea48da-1d3d-43a1-8ea2-a547735c89a1-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-2fc5f77b-d29e-416f-bd64-e38321cdab7e-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-2fc5f77b-d29e-416f-bd64-e38321cdab7e-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-5d7818b4-e457-4d8b-8152-09174b72bff6-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-5d7818b4-e457-4d8b-8152-09174b72bff6-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-eef9fad5-d622-4713-b698-59968dfb84d6-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00003-0-eef9fad5-d622-4713-b698-59968dfb84d6-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-2dbc1835-3545-45e2-a16c-cdf6bdb5d8e0-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-2dbc1835-3545-45e2-a16c-cdf6bdb5d8e0-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-68273c5d-77fa-4b44-89f6-e948a8068687-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-68273c5d-77fa-4b44-89f6-e948a8068687-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-8bc85407-eb17-4806-89f9-12ac860d1d7d-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-8bc85407-eb17-4806-89f9-12ac860d1d7d-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-fa7d1e9c-06f0-4210-a679-679856fd22a0-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00004-0-fa7d1e9c-06f0-4210-a679-679856fd22a0-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-2e7e240e-c359-4ef7-9723-23815c61bf62-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-2e7e240e-c359-4ef7-9723-23815c61bf62-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-51d742e4-27d8-45e5-8950-715db1eb6206-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-51d742e4-27d8-45e5-8950-715db1eb6206-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-8648284e-2e67-4025-b20e-e35bd00507b8-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-8648284e-2e67-4025-b20e-e35bd00507b8-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-e680aac9-780e-4c70-994e-6fdc92587718-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00005-0-e680aac9-780e-4c70-994e-6fdc92587718-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-2871c6b0-2577-428d-8d58-585e8fc12729-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-2871c6b0-2577-428d-8d58-585e8fc12729-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-59042f49-2777-4aed-ac29-0641e733c571-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-59042f49-2777-4aed-ac29-0641e733c571-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-837a1142-3098-4b5c-9791-c57cad73db66-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-837a1142-3098-4b5c-9791-c57cad73db66-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-c1f381e5-7595-4f4a-82a8-621f1e0b6e1f-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00006-0-c1f381e5-7595-4f4a-82a8-621f1e0b6e1f-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-33e57d8c-c810-4c4b-aa88-b05560680f3d-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:16 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-33e57d8c-c810-4c4b-aa88-b05560680f3d-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-705ca828-f7f8-4190-b765-d7b963f7e0c8-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:37 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-705ca828-f7f8-4190-b765-d7b963f7e0c8-00002.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-d33906f3-2dc3-4eab-bc3c-cb5a29a4870c-00001.parquet
-rw-r--r--   3 hive hadoop          0 2020-11-02 17:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-d33906f3-2dc3-4eab-bc3c-cb5a29a4870c-00002.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-dd42ce67-fc60-4af8-8412-acb8b486c121-00001.parquet
-rw-r--r--   3 hive hadoop          4 2020-11-02 16:13 /data/iceberg_catalog/test/customers3/default/customers3/data/00007-0-dd42ce67-fc60-4af8-8412-acb8b486c121-00002.parquet`

**Comment by openinx** [comment]
> The program keeps running, and hive can't query the data. The file on hdfs has been queried through hadoop.

Could you pls check that whether it did commit the iceberg transaction successfully ?  If we did not commit the transaction, then hive won't see the results.  As we transaction commitment happened when flink checkpoint occur, so it's better to check the checkpoint configurations (such as checkpoint interval, disable or enable ? )

**Comment by paulzanmei** [comment]
> Could you pls check that whether it did commit the iceberg transaction successfully ? If we did not commit the transaction, then hive won't see the results. As we transaction commitment happened when flink checkpoint occur, so it's better to check the checkpoint configurations (such as checkpoint interval, disable or enable ? )

Hi @openinx  

flink checkpoint is not turned on

If flink uses hive CATALOG, data can be written normally, and the datagen connector data is generated, the process will automatically end;
hadoop CATALOG does not end the process of writing data

**Comment by openinx** [comment]
Could you help to dump the stack trace for the hadoop catalog case ?

**Comment by JingsongLi** [comment]
According to https://github.com/apache/iceberg/blob/master/site/docs/hive.md
Hive reader only supports read a existed Hadoop table...

**Comment by paulzanmei** [comment]
Hi @openinx  @JingsongLi  Thank you for your help. The problem has been solved

Checkpoint needs to be configured to write data successfully

**Comment by junsionzhang** [comment]
> ```sql
> CREATE EXTERNAL TABLE sample_mirror2
> STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
> LOCATION 'file:///Users/openinx/test/hive-warehouse1/default/sample';
> ```

I have the same question now.

**Comment by junsionzhang** [comment]
> Hi @paulzanmei
> 
> I tried your case on my local host, I did not query the hive catalog table ( which is created in flink sql) in hive sql successfully, but I did the similar thing successfully for hadoop table. Say the following steps would work:
> 
> Step#1 : Create a hadoop catalog/database/table in flink sql and then write one record:
> 
> ```shell
> Flink SQL> CREATE CATALOG hadoop_catalog WITH (
> >   'type'='iceberg',
> >   'catalog-type'='hadoop',
> >   'clients'='5',
> >   'warehouse'='file:///Users/openinx/test/hive-warehouse1'
> > );
> [INFO] Catalog has been created.
> 
> Flink SQL> show databases;
> default_database
> 
> Flink SQL> show tables; 
> [INFO] Result was empty.
> 
> Flink SQL> use catalog hadoop_catalog; 
> 
> Flink SQL> show tables;
> sample
> 
> Flink SQL> insert into sample select 1, 'a';
> [INFO] Submitting SQL update statement to the cluster...
> [INFO] Table update statement has been successfully submitted to the cluster:
> Job ID: 4b4b8c2b1a8d6f876a56f55abe4de1fe
> ```
> 
> Step#2: Create an external hive table in hive shell:
> 
> ```sql
> CREATE EXTERNAL TABLE sample_mirror2
> STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
> LOCATION 'file:///Users/openinx/test/hive-warehouse1/default/sample';
> ```
> 
> And show tables:
> 
> ```
> show tables; 
> 
> +-----------------+
> |    tab_name     |
> +-----------------+
> | sample_mirror2  |
> +-----------------+
> 1 rows selected (0.056 seconds)
> ```
> 
> Step#3: Query the records in hive shell:
> 
> ```sql
> select * from sample_mirror2;
> 
> +--------------------+----------------------+
> | sample_mirror2.id  | sample_mirror2.data  |
> +--------------------+----------------------+
> | 1                  | a                    |
> +--------------------+----------------------+
> 1 row selected (0.86 seconds)
> ```
> 
> I will figure out why it does not work for hive catalog table. @paulzanmei FYI

hi, have you figured out the reason now ?  @JingsongLi  said 'Hive reader only supports read a existed Hadoop table...' ,but I think the link(https://iceberg.apache.org/hive/) does not say it clearly .

**Comment by junsionzhang** [comment]
> Hi @paulzanmei
> 
> I tried your case on my local host, I did not query the hive catalog table ( which is created in flink sql) in hive sql successfully, but I did the similar thing successfully for hadoop table. Say the following steps would work:
> 
> Step#1 : Create a hadoop catalog/database/table in flink sql and then write one record:
> 
> ```shell
> Flink SQL> CREATE CATALOG hadoop_catalog WITH (
> >   'type'='iceberg',
> >   'catalog-type'='hadoop',
> >   'clients'='5',
> >   'warehouse'='file:///Users/openinx/test/hive-warehouse1'
> > );
> [INFO] Catalog has been created.
> 
> Flink SQL> show databases;
> default_database
> 
> Flink SQL> show tables; 
> [INFO] Result was empty.
> 
> Flink SQL> use catalog hadoop_catalog; 
> 
> Flink SQL> show tables;
> sample
> 
> Flink SQL> insert into sample select 1, 'a';
> [INFO] Submitting SQL update statement to the cluster...
> [INFO] Table update statement has been successfully submitted to the cluster:
> Job ID: 4b4b8c2b1a8d6f876a56f55abe4de1fe
> ```
> 
> Step#2: Create an external hive table in hive shell:
> 
> ```sql
> CREATE EXTERNAL TABLE sample_mirror2
> STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
> LOCATION 'file:///Users/openinx/test/hive-warehouse1/default/sample';
> ```
> 
> And show tables:
> 
> ```
> show tables; 
> 
> +-----------------+
> |    tab_name     |
> +-----------------+
> | sample_mirror2  |
> +-----------------+
> 1 rows selected (0.056 seconds)
> ```
> 
> Step#3: Query the records in hive shell:
> 
> ```sql
> select * from sample_mirror2;
> 
> +--------------------+----------------------+
> | sample_mirror2.id  | sample_mirror2.data  |
> +--------------------+----------------------+
> | 1                  | a                    |
> +--------------------+----------------------+
> 1 row selected (0.86 seconds)
> ```
> 
> I will figure out why it does not work for hive catalog table. @paulzanmei FYI

hi, have you figured out the reason now ?  @JingsongLi  said 'Hive reader only supports read a existed Hadoop table...' ,but I think the link(https://iceberg.apache.org/hive/) does not say it clearly .
