### ISSUE TITLE
Where can I find the design documents? For example, support java to write iceberg

### ISSUE THREAD

**Issue by liujinhui1994** [apache/iceberg#1690]
Where can I find the design documents? For example, support java to write iceberg？

**Comment by kbendick** [comment]
There's the main website: https://iceberg.apache.org/

**Comment by liujinhui1994** [comment]
The official website does not seem to exist? What I want to find is similar to RFC, or design documents described in google document
@kbendick

**Comment by openinx** [comment]
@liujinhui1994  which part you want to read about the design document ?  flink sink connector ? we don't have a page to collect all those documents,  but I think I can provide the design context  or some link about the discussion if you really need to read.

**Comment by HeartSaVioR** [comment]
If you're trying to find Java API, https://iceberg.apache.org/api/ & https://iceberg.apache.org/javadoc/

If you're trying to find the internal details, https://iceberg.apache.org/spec/

**Comment by idealspark** [comment]
where can I  find all design documents?
like this 
[https://docs.google.com/document/d/1FMKh_SQ6xSUUmoCA8LerTkzIxDUN5JbStQp5Hzot4eo/edit#heading=h.wjf8k8pka3iq](url)
