### ISSUE TITLE
Create a bash script to verify the apache iceberg release tarball automatically

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#1700]
It's good to write a script to do all the steps for verifying the release https://lists.apache.org/thread.html/rd5e6b1656ac80252a9a7d473b36b6227da91d07d86d4ba4bee10df66@%3Cdev.iceberg.apache.org%3E,  so that people from the community don't have to test those by handle.

**Comment by JingsongLi** [comment]
I doubt it slightly. 
I think it's better to keep manual validation to cover all kinds of situations.

I think we can add documents to describe how to verify.

**Comment by HeartSaVioR** [comment]
FYI I had been using similar verification script to verify release candidates for Apache Storm, and I'm sure it would help much on the steps everyone will do the same. The steps which script will cover would be the "minimum" steps of verification. Ideally every releases should be tested with manual workloads individual would have, which will not be covered by the automation script. That said, the script will ease your work to do the basic verification steps, and after the script verifies the RC, you can go with manual verification (which shouldn't be just running the test in the local - that can be just automated).
