### ISSUE TITLE
Publish an incremental scan event during planning

### ISSUE THREAD

**Issue by skambha** [apache/iceberg#1711]
There is a todo in the `IncrementalDataTableScan` to publish a incremental scan event. 

I can take a look into this. 
Incremental scan has a ‘from’ and ‘to’ snapshot that needs to be passed to the event as well. 

- We can add a new `IncrementalScanEvent` that has the ‘from’ and ‘to’ snapshot information as well in addition to the projection, filter and tablename info.  _Or_
- We could enhance the `ScanEvent` that exists today, although the snapshotId there won’t apply to the Incremental scan event.  What is the compatibility guarantees for ScanEvent across releases since it is part of the api folder?

@rdsr, @rdblue, please let me know your comments.  Thanks.

**Comment by rdblue** [comment]
I think we should maintain compatibility in `ScanEvent` since it is part of the API. I think I favor the first option, to add an `IncrementalScanEvent`.

**Comment by skambha** [comment]
sounds good. I went ahead and created a pr using the first option.
