### ISSUE TITLE
Failed to create hive table with hadoopCatalog

### ISSUE THREAD

**Issue by qphien** [apache/iceberg#1718]
Related to https://github.com/apache/iceberg/pull/1495
```
set iceberg.mr.catalog=hadoop;
hive (default)> create external table iceberg_table (id int) 
              > stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
              > location '/hive/default.db/iceberg_table';
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot set a custom location for a path-based table. Expected hdfs://mycluster/iceberg/warehouse/default/iceberg_table but got hdfs://mycluster/hive/default.db/iceberg_table
```

```
    // HadoopCatalog.java
private class HadoopCatalogTableBuilder extends BaseMetastoreCatalogTableBuilder {
     ...
    @Override
    public TableBuilder withLocation(String location) {
      Preconditions.checkArgument(location == null || location.equals(defaultLocation),
          "Cannot set a custom location for a path-based table. Expected " + defaultLocation + " but got " + location);
      return this;
    }
   ...
}
```

HadoopCatalogTableBuilder only support null location

**Comment by pvary** [comment]
The `

**Comment by qphien** [comment]
> Have seen the problem when working on #1612 and fixed it there.
> 
> The `/hive/default.db/iceberg_table` does not seem like a valid HadoopCatalog table path, so that too has to be changed to a valid path if I am correct.

Yes, `/hive/default.db/iceberg_table` is not in HadoopCatalog table path format `hadoopCatalogWarehouse/db/table`. #1612 solves location setting problem but we need to set `iceberg.mr.catalog.hadoop.warehouse.location` if table location prefix is inconsistent with `fs.defaultFs/iceberg/warehouse`. Is there any way to skipping setting `iceberg.mr.catalog.hadoop.warehouse.location`?
