### ISSUE TITLE
Implement spark fanout writer

### ISSUE THREAD

**Issue by XuQianJin-Stars** [apache/iceberg#1746]
Changes involved in this PR:
1. Move the `PartitionedFanoutWriter` of flink to `core/src/main/java/org/apache/iceberg/io` package.
2. Implement immobile writers for spark2 and spark3 modules respectively.
3. User can turn it on according to the parameter `write.partitioned.fanout.enabled= true` in the setting table. The default is false and can also set spark option `partitioned.fanout.enabled` to override it.

**Comment by HeartSaVioR** [comment]
Could you please elaborate this with details?

**Comment by XuQianJin-Stars** [comment]
> Could you please elaborate this with details?

hi @HeartSaVioR well, I will verify the implementation of this function to supplement this isuses.

**Comment by HeartSaVioR** [comment]
I meant, what is the use case, and what is the goal of the issue, and what would be your approach to deal with this if you'd like to work on this. I guess this is essential information to construct as rationalization when adding a new feature.

**Comment by XuQianJin-Stars** [comment]
hi @HeartSaVioR  This the [PR](https://github.com/apache/iceberg/pull/1774)
