### ISSUE TITLE
Reading iceberg table using Amazon Athena

### ISSUE THREAD

**Issue by ismailsimsek** [apache/iceberg#1766]
is it possible to read iceberg table using Amazon Athena, will that be possible after  "AWS Glue catalog and table operations"  #1633 ?

**Comment by jackye1995** [comment]
Hi this is Jack from AWS Athena. Currently we do not have support for this. We are in the progress of adding support, but we have to wait until this Glue catalog is officially released in Iceberg, which will most likely happen in 0.11.0. Before this happens, you can use EMR (version >= 6.0.0) to create Spark 3 cluster and run all the Iceberg queries through that.

**Comment by ismailsimsek** [comment]
thank you @jackye1995

**Comment by WilliamWhispell** [comment]
Hi @jackye1995 - I see 0.11.0 was released today on Github - Any update on Athena support?

**Comment by stayrascal** [comment]
Hi, just given an example here follow the [document](https://iceberg.apache.org/aws/), and meet a 'unknown' classification issue in Glue data catalog.

1. Start Spark SQL
```
spark-sql --packages org.apache.iceberg:iceberg-spark3-runtime:0.11.0,software.amazon.awssdk:bundle:2.15.40,software.amazon.awssdk:url-connection-client:2.15.40 \
    --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
    --conf spark.sql.catalog.my_catalog.warehouse=s3://xxxx/lake_house/iceberg/spark \
    --conf spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
    --conf spark.sql.catalog.my_catalog.lock-impl=org.apache.iceberg.aws.glue.DynamoLockManager \
    --conf spark.sql.catalog.my_catalog.lock.table=myGlueLockTable
```

2. Create table and insert data:
```
CREATE TABLE my_catalog.exist_db.table_demo (id bigint, data string) USING iceberg;
INSERT INTO my_catalog.exist_db.table_demo VALUES (1, 'a'), (2, 'b'), (3, 'c');
```

3. When Query table from AWS glue data catalog console, it look like missed the `storageDescriptor` filed about the table schema. didn't see where the [GuleCatalog](https://github.com/apache/iceberg/blob/ad78cc6cf2/aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java#L109) set the storage descriptor before create table by `Glue` client
```
{
   "actionResponses":[
      {
         "action":"com.amazonaws.console.glue.awssdk.shared.context.AWSGlueContext.getTable",
         "data":{
            xxxxx
            },
            "sdkHttpMetadata":{
               xxxx
               },
               "httpHeaders":{
                 xxxx
               },
               "httpStatusCode":200
            },
            "table":{
               "name":"table_demo",
               "databaseName":"exist_db",
               "createTime":1616384916000,
               "updateTime":1616384939000,
               "retention":0,
               "tableType":"EXTERNAL_TABLE",
               "parameters":{
                  "previous_metadata_location":"s3://xxxxxxx/lake_house/iceberg/spark/exist_db.db/table_demo/metadata/00000-d7d65077-55a9-4b3b-b812-7ae34a4687be.metadata.json",
                  "metadata_location":"s3://xxxxxxx/lake_house/iceberg/spark/exist_db.db/table_demo/metadata/00001-3e4ed2c5-fe12-4d04-ab45-74f208afce71.metadata.json",
                  "table_type":"ICEBERG"
               },
               "createdBy":"arn:aws:sts::xxxxx:assumed-role/xxxxxxx",
               "isRegisteredWithLakeFormation":false,
               "catalogId":"xxxxxxx",
               "isRowFilteringEnabled":false
            }
         }
      }
   ]
}
```

**Comment by jackye1995** [comment]
> When Query table from AWS glue data catalog console, it look like missed the storageDescriptor filed about the table schema.

@stayrascal Hi, this is expected behavior. Glue is only used as a storage service to store Iceberg related table information in parameters, which are the ones you see in `parameters` section. `storageDescriptor` is not set intentionally because we plan to support a different read & write mechanism.

**Comment by jackye1995** [comment]
> I see 0.11.0 was released today on Github - Any update on Athena support?

@WilliamWhispell I somehow missed your comment, sorry for the late reply. 

And for anyone else who is also interested in Athena support, please ping me directly (through LinkedIn or Slack) to discuss more details.

**Comment by stayrascal** [comment]
> > When Query table from AWS glue data catalog console, it look like missed the storageDescriptor filed about the table schema.
> 
> @stayrascal Hi, this is expected behavior. Glue is only used as a storage service to store Iceberg related table information in parameters, which are the ones you see in `parameters` section. `storageDescriptor` is not set intentionally because we plan to support a different read & write mechanism.

@jackye1995 thanks a lot for your quick response.
so is that the icebreg table cannot be read by Athena/Presto, because if the `storageDescriptor`(which include the table schema, input/output format) is not set, Glue catalog cannot recognize this table, and cannot be queried by Athena.

is there other approach that support the Athean query icebreg table?

**Comment by jackye1995** [comment]
@stayrascal storage descriptor is needed if the table is intended to be read through Hive. Even in open source Trino today, this is technically not needed (although the Trino iceberg connector basically depends on the hive connector so there might be some checks for it, I have not verified)

And as I said in the other comment, please contact me directly through LinkedIn or Slack if you are interested in Athena support to discuss more details 😄

**Comment by stayrascal** [comment]
> @stayrascal storage descriptor is needed if the table is intended to be read through Hive. Even in open source Trino today, this is technically not needed (although the Trino iceberg connector basically depends on the hive connector so there might be some checks for it, I have not verified)
> 
> And as I said in the other comment, please contact me directly through LinkedIn or Slack if you are interested in Athena support to discuss more details 😄

@jackye1995 Thanks. could you please share your Slack ID or link?

**Comment by bhanuunrivalled** [comment]
creating a table as below also does not work . we used format_version 2
```
  Map<String,String> properties = new HashMap<>();
        properties.put(TableProperties.FORMAT_VERSION, "2");
        Table iceBergTable = glueCatalog.createTable(TableIdentifier.of(namespace, tableName), SCHEMA, PartitionSpec.unpartitioned(),properties);
        
```

**Comment by ismailsimsek** [comment]
integration is available now, closing

https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg.html
