### ISSUE TITLE
add list partitions for flinkcatalog

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1791]
show partitions of table is very common required,I think we should add the funtions.

**Comment by openinx** [comment]
Sounds good to me, we might need to implement those methods in `FlinkCatalog`: 

```java
  @Override
  public List<CatalogPartitionSpec> listPartitions(ObjectPath tablePath)
      throws CatalogException {
    throw new UnsupportedOperationException();
  }

  @Override
  public List<CatalogPartitionSpec> listPartitions(ObjectPath tablePath, CatalogPartitionSpec partitionSpec)
      throws CatalogException {
    throw new UnsupportedOperationException();
  }

  @Override
  public List<CatalogPartitionSpec> listPartitionsByFilter(ObjectPath tablePath, List<Expression> filters)
      throws CatalogException {
    throw new UnsupportedOperationException();
  }
```

**Comment by zhangjun0x01** [comment]
In the first PR, I currently only implement the first method `listPartitions(ObjectPath tablePath)`.

 the `listPartitions(ObjectPath tablePath, CatalogPartitionSpec partitionSpec)` method requires a CatalogPartitionSpec parameter, and the type of the `CatalogPartitionSpec#partitionSpec `  is Map<String, String>. I tested it, the filter in iceberg needs to match the value and type.
For example, if the partition type is int, we need to pass  `123`. pass `"123"` is wrong, so I think we may need to improve the CatalogPartitionSpec#partitionSpec of flink to Map<String, Object> so that  more  compatibility 

  The `listPartitionsByFilter(ObjectPath tablePath, List<Expression> filters)` method need to transform the expression of flink to the expression of iceberg. I think it will also need a lot of work.

  So I think we can implement the first method first, and then implement the other two methods in sub-PR later.
