### ISSUE TITLE
Finalise the proposal for including Partition stats for Iceberg tables

### ISSUE THREAD

**Issue by vvellanki** [apache/iceberg#1832]
This ticket is to come up with a final spec for including partition index for Iceberg tables

**Comment by wangmiao1981** [comment]
Trying to log an issue for supporting secondary index (https://docs.google.com/document/d/1E1ofBQoKRnX04bWT3utgyHQGaHZoelgXosk_UNsTUuQ/edit). This may be related to the index support. 

@rdblue  please advise if I need to open a new issue.

**Comment by vvellanki** [comment]
@wangmiao1981 I was referring to the [following](https://docs.google.com/document/d/1G6GeOXkGSiSTcu0lDS6VA1FtJ_uz9FO4tF2Pffmx9LU/edit#heading=h.48c09kgpva06) when I refer to Partition Index.

Reading your document, these two appear to be quite different:
- The partition index proposal is at the table scope; while secondary indexes are per-file, per-column scope
- The secondary indexes themselves are files - one or more files per data file; as opposed to the partition index (one per snapshot)

@rdblue @wangmiao1981 I see the Partition Index and Secondary Indexes as being sufficiently different that we should treat them independently

**Comment by vvellanki** [comment]
@rdblue @wangmiao1981 Piyush from my team has uploaded a PR for partition-stats. I am of the opinion that the secondary indexes work that @wangmiao1981 is doing is quite different from what we are proposing.

Can you guys take a look and comment?

**Comment by rdblue** [comment]
I think I agree that the two features are separate. We probably won't use the same format for partition-level data and file-level indexes. Sorry I haven't had a chance to take a look at these proposals in detail yet. I should have some time once the MERGE INTO support is about finished, as that's a high priority for the community.

**Comment by ajantha-bhat** [comment]
tracked by https://github.com/apache/iceberg/issues/8450
