### ISSUE TITLE
hive query flink sql insert data,but error.

### ISSUE THREAD

**Issue by zuoyebushiwo** [apache/iceberg#1883]
this my step:
CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://hd-node-3-41.wakedata.com:9083',
  'clients'='5',
  'property-version'='1',
  'warehouse'='hdfs://HDFSCluster/warehouse'
);

CREATE DATABASE iceberg_db;

use CATALOG hive_catalog;    
use iceberg_db;

CREATE TABLE hive_catalog.iceberg_db.sample (
    id BIGINT COMMENT 'unique id',
    data STRING
) ;

SET execution.type = batch;
INSERT  hive_catalog.iceberg_db.sample VALUES (1, 'a');

flink sql query is ok!

I think it should be query by hive engine, so i dot it like:
  add jar hdfs://HDFSCluster/user/flink/iceberg-hive-runtime-0.10.0.jar;
use iceberg_db;
select * from sample;

but error happened!

Error: java.io.IOException: java.io.IOException: Cannot create an instance of InputFormat class org.apache.hadoop.mapred.FileInputFormat as specified in mapredWork! (state=,code=0)

help me! thanks.

**Comment by zhangjun0x01** [comment]
> CREATE CATALOG hive_catalog WITH (
> 'type'='iceberg',
> 'catalog-type'='hive',
> 'uri'='thrift://hd-node-3-41.wakedata.com:9083',
> 'clients'='5',
> 'property-version'='1',
> 'warehouse'='hdfs://HDFSCluster/warehouse'
> );

try use hadoop catalog instead of hive catalog to create the  catalog

 ```
CREATE CATALOG hadoop_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hadoop',
  'warehouse'='hdfs://nn:8020/warehouse/path',
  'property-version'='1'
);
```

**Comment by zuoyebushiwo** [comment]
> > CREATE CATALOG hive_catalog WITH (
> > 'type'='iceberg',
> > 'catalog-type'='hive',
> > 'uri'='thrift://hd-node-3-41.wakedata.com:9083',
> > 'clients'='5',
> > 'property-version'='1',
> > 'warehouse'='hdfs://HDFSCluster/warehouse'
> > );
> 
> try use hadoop catalog instead of hive catalog to create the catalog
> 
> ```
> CREATE CATALOG hadoop_catalog WITH (
>  'type'='iceberg',
>  'catalog-type'='hadoop',
>  'warehouse'='hdfs://nn:8020/warehouse/path',
>  'property-version'='1'
> );
> ```

i think it should create by catalog-type=hive
and it should query by hive engine by  add jar hdfs://HDFSCluster/user/flink/iceberg-hive-runtime-0.10.0.jar in hive shell command;
how can id dot?

**Comment by zuoyebushiwo** [comment]
> > CREATE CATALOG hive_catalog WITH (
> > 'type'='iceberg',
> > 'catalog-type'='hive',
> > 'uri'='thrift://hd-node-3-41.wakedata.com:9083',
> > 'clients'='5',
> > 'property-version'='1',
> > 'warehouse'='hdfs://HDFSCluster/warehouse'
> > );
> 
> try use hadoop catalog instead of hive catalog to create the catalog
> 
> ```
> CREATE CATALOG hadoop_catalog WITH (
>  'type'='iceberg',
>  'catalog-type'='hadoop',
>  'warehouse'='hdfs://nn:8020/warehouse/path',
>  'property-version'='1'
> );
> ```

i see!  this can do this with create hive external table for hive engine query.

**Comment by wxy7** [comment]
@zuoyebushiwo have you solved now ?

**Comment by hulin-ola** [comment]
ALTER TABLE `hive_catalog`.`test`.`sample` SET ('engine.hive.enabled'='true');
 add  above table properties to your table
