### ISSUE TITLE
hive document example is not work!

### ISSUE THREAD

**Issue by zuoyebushiwo** [apache/iceberg#1884]
CREATE EXTERNAL TABLE table_a (id BIGINT, data STRING) 
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
LOCATION 'hdfs://HDFSCluster/warehouse/iceberg_db.db/table_a';

Error: 
Error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: MetaException(message:org.apache.hadoop.hive.serde2.SerDeException Please provide an existing table or a valid schema) (state=08S01,code=1)

How can i should.

**Comment by RussellSpitzer** [comment]
Did you create the Iceberg table first?

**Comment by XuQianJin-Stars** [comment]
hi @zuoyebushiwo  You need to specify the schema information and perform the following operations to successfully create the table.
`
CREATE EXTERNAL TABLE customers STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' LOCATION 'hdfs://namenode:8020/cs/table_a' TBLPROPERTIES ('iceberg.mr.table.schema'='{"type":"struct","fields":[{"id":1,"name":"customer_id","required":false,"type":"long"},{"id":2,"name":"first_name","required":false,"type":"string"},{"id":3,"name":"last_name","required":false,"type":"string"}]}', 'iceberg.mr.table.partition.spec'='{"spec-id":0,"fields":[{"name":"customer_id","transform":"identity","source-id":1,"field-id":1000}]}', 'dummy'='test');
`

**Comment by XuQianJin-Stars** [comment]
> Did you create the Iceberg table first?

hi @RussellSpitzer  Regarding this point, I think the document needs to be updated to further explain in detail.

**Comment by zuoyebushiwo** [comment]
> > Did you create the Iceberg table first?
> 
> hi @RussellSpitzer Regarding this point, I think the document needs to be updated to further explain in detail.

think very much! it help me a lot
