### ISSUE TITLE
Flink  1.11.1 Not Supoort timestamptz

### ISSUE THREAD

**Issue by txdong-sz** [apache/iceberg#1915]
Flink Not Support Timestampz
![image](https://user-images.githubusercontent.com/5066512/101902034-f5609400-3bec-11eb-892c-c38561342633.png)

**Comment by XuQianJin-Stars** [comment]
hi @txdong-sz This type is supported since the version of flink1.9, you can use `TIMESTAMP WITH LOCAL TIME ZONE` or `TIMESTAMP WITH TIME ZONE`.
The ddl statement can be:
```
CREATE TABLE iceberg.iceberg_db2.iceberg_001 (
    id BIGINT COMMENT'unique id',
    data STRING,
    ftime TIMESTAMP(3) WITH LOCAL TIME ZONE
) WITH ('connector'='iceberg','write.format.default'='ORC');
```

**Comment by txdong-sz** [comment]
what is the different of  TIMESTAMP(3) WITH LOCAL TIME ZONE  and   TIMESTAMP(6) WITH LOCAL TIME ZONE

**Comment by vbabenkoru** [comment]
@XuQianJin-Stars `TIMESTAMP WITH TIME ZONE` does not exist.
