### ISSUE TITLE
Hive: Schema conversion should convert NOT NULL/required fields

### ISSUE THREAD

**Issue by pvary** [apache/iceberg#1922]
Currently the `HiveSchemaUtil` converts every Hive field to an `optional` NestedField. We should convert `NOT NULL` fields to `required` and in the other directions we should convert `required` Iceberg NestedFileds to `NOT NULL`

**Comment by lcspinter** [comment]
The NotNullConstraines are stored separately from the HMS Table. To get a list of not null columns we would need to call the HMS API from the HiveIcebergMetaHook, which is not straight forward.
