### ISSUE TITLE
Absolute address can be optimized to relative address in file(*.metadata.json.)？

### ISSUE THREAD

**Issue by scanry** [apache/iceberg#1938]
for example:
hdfs://127.0.0.1:8020/xxx1      ->   /xxx1
hdfs://127.0.0.1:8020/xxx2      ->  /xxx2   
{
  "format-version" : 1,
  "table-uuid" : "1e5ef490-ac9f-4339-9da5-b53b5c63c392",
  "location" : "hdfs://127.0.0.1:8020/xxx1",
  "last-updated-ms" : 1588297651079,
  "last-column-id" : 8,
  "schema" : {
  },
  "partition-spec" : [ ],
  "default-spec-id" : 0,
  "partition-specs" : [ {
    "spec-id" : 0,
    "fields" : [ ]
  } ],
  "properties" : { },
  "snapshots" : [ {
    "manifest-list" : "hdfs://127.0.0.1:8020/xxxx2"
  } ]
}

**Comment by zhangjun0x01** [comment]
you can trace the pr https://github.com/apache/iceberg/issues/1617

**Comment by scanry** [comment]
> you can trace the pr #1617

thanks
