### ISSUE TITLE
Read options to read append and delete with overwrite snapshots in Incremental reads

### ISSUE THREAD

**Issue by mehtaashish23** [apache/iceberg#1949]
Currently, the IncrementalDataScan doesn't support IncrementalReads on Overwrite snapshot [here], but as a client, I should be able to read just append data or delete data explicitly and construct an incremental reader at the application level.
For instance: A client doing updates based on the primary key can potentially be able to construct back CDC by reading append data and delete data in separate DataFrame, and then take client-side joins.

There should be options for the reader to pass options 
1. To read the overwrite snapshots (to allow appended data via it)
2. Another option to read-only Deleted DataFiles during IncrementalScan

NOTE: This is to allow clients, who would prefer "copy on write" implementation with Iceberg for executing SQL like DELETE or MERGE_INTO (in future).

[here]: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java#L122

**Comment by mehtaashish23** [comment]
@rdblue , @aokolnychyi Let me know your thoughts on it. We would like to contribute this to community ASAP, since we are looking to use copy-on-write mode with Delete/MergeInto (before switching to "merge on read" implementation)

cc: @dilipbiswal

**Comment by rdblue** [comment]
Can you give us a clearer example of what you're trying to support here? I'm trying to understand the use case for ignoring the deletes in an overwrite.

**Comment by mehtaashish23** [comment]
@rdblue started an email thread for this, will summarize the details here as it concludes, but here is the detail. 

For us, our main use case is primary key based dataSets (like MySQL bin log export) where the DELETE and MERGE always
update records based on the primary key. Considering that I know the primary key and this fixed use case of primary key-
based updates, I can easily construct back CDC from the appended/deleted data from the table, by taking full outer join on 
primary key between appended data and deleted data, and expose what all rows were updated/inserted/deleted, along with 
the previous value in case of updates/deletes.

**Comment by ayush-san** [comment]
@mehtaashish23 We are also doing something similar, were you able to contribute this feature?

**Comment by vamen** [comment]
Is there any updates on this ?
Would be glad contribute to this feature.

**Comment by jhchee** [comment]
This feature sounds like blocked by this https://github.com/apache/iceberg/issues/3941
