### ISSUE TITLE
Flink:  Commit the existing manifests to iceberg txn in IcebergFilesCommitter.

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#1959]
Currently,    the flink's IcebergFilesCommitter will persist the recieved data files to flink manifests under a customized directory path ( in `snapshotState`),  and then read all data files from the persist flink manifests to commit the iceberg txn ( in `notifyCheckpointComplete` ). 

![image](https://user-images.githubusercontent.com/5028729/102599481-7e7d4b00-4158-11eb-852b-249e0fd50a71.png)

( I have a slide to show the current design, referenced from [flink forward asia 2020](https://flink-forward.org.cn/)).

@stevenzwu  suggested [1] to commit the written flink manifests to iceberg txn (by `appendManifests` or `appendDeleteManifests` API directly),  which means we don't have to read the data files from persisted flink manifests and then construct the committing manifests again. 

That  sounds a great idea for the case that will commit lots files in a single TXN.  I think it's good to create a separate issue to address that thing, let's track it here.

1. https://github.com/apache/iceberg/pull/1939#discussion_r545471359

**Comment by rdblue** [comment]
I think it is a good idea to commit the manifests directly, but I would want a flag to tell Iceberg whether it should rewrite them. In some cases, manifests are correctly written into the metadata directory. But it should be possible to write a manifest in a different location. For example, we write manifests in a bucket in the local region and rewrite in the committer to create a manifest in the table's normal region.
