### ISSUE TITLE
Capture lower and upper bound stats for ORC

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#197]
For specific columns (long, double etc) ORC exposes lower and upper bounds as part of the `ColumnStatistics` API (e.g see `org.apache.orc.DoubleColumnStatistics`)

**Comment by edgarRd** [comment]
Isn't this addressed by https://github.com/apache/incubator-iceberg/pull/199?

**Comment by rdsr** [comment]
Yes!

**Comment by edgarRd** [comment]
We can close this, fixed in #199.
