### ISSUE TITLE
Can we compact data files by some partition?

### ISSUE THREAD

**Issue by EricJoy2048** [apache/iceberg#1973]
For example:
My table partition by month(time),day(time)，Now Iceberg will generate a file a day. But in order to optimize query performance, I hope that the files from 1 month ago can be one file per month. Does Iceberg support？

**Comment by openinx** [comment]
Currently, the RewriteDataFilesAction does not support compacting in a single partition directly, but provided a row [filter](https://github.com/apache/iceberg/blob/da9a0b24f21a4390a5270d94c576b62f3b49caec/core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java#L188)  option to filter those data files that need to compact.  If you have a column `ts` and partitioned by `day(ts)`,    I think you can use the expression `Expressions.equals("ts", "2020-12-23")` to execute the rewrite files action.

**Comment by gaojun2048** [comment]
> Currently, the RewriteDataFilesAction does not support compacting in a single partition directly, but provided a row [filter](https://github.com/apache/iceberg/blob/da9a0b24f21a4390a5270d94c576b62f3b49caec/core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java#L188) option to filter those data files that need to compact. If you have a column `ts` and partitioned by `day(ts)`, I think you can use the expression `Expressions.equals("ts", "2020-12-23")` to execute the rewrite files action.

Thank you, In my case I want to merge all data files of `2020-11-01 <= ts <= 2020-11-30` into one file. But I see `Partition values for a data file must be the same for all records stored in the data file` in the Iceberg document . I don`t know if an error will be reported if there are multiple partition values in one data file.

**Comment by gaojun2048** [comment]
Is event one can help me?

**Comment by HeartSaVioR** [comment]
I'm not sure that is supported, as you see in the Iceberg document. At least the case requires Iceberg to support partition value "range" for a specific data file (as your data file will be no longer bound to the single partition), which I'm not sure that is something Iceberg community would like to solve in near future. (DISCLAIMER: I'm just a contributor and the direction is made by Iceberg community, more likely from PMC members.)

If you have some use cases where the feature is critical, would you mind posting to dev mailing list instead and try to get traction?

**Comment by prashantgohel1** [comment]
Were you able to find answer for this? I have similar use case where I want to compact data across multiple day level partitions to month level for the data older than X.
