### ISSUE TITLE
FlinkOrcWriter case must have a default case

### ISSUE THREAD

**Issue by txdong-sz** [apache/iceberg#1976]
FlinkOrcWriter case must have a default case

![image](https://user-images.githubusercontent.com/5066512/102962461-e39ebb00-4521-11eb-9003-2b9d82fcd85c.png)
![image](https://user-images.githubusercontent.com/5066512/102962526-0630d400-4522-11eb-812a-93b5adf3b9df.png)

**Comment by openinx** [comment]
@txdong-sz I guess you are using a different checkstyle.xml  which is not the iceberg's [checkstyle](https://github.com/apache/iceberg/blob/master/.baseline/checkstyle/checkstyle.xml) guide.    If the code violate the checkstyle, the build process would be failure.
