### ISSUE TITLE
Spark Iceberg manifest reports wrong parquet file sizes.

### ISSUE THREAD

**Issue by dmgcodevil** [apache/iceberg#1980]
We are using spark iceberg and some iceberg manifest files report the wrong data file (parquet)  size, it's ~ 2x  larger than the actual parquet file size. The issue was found while investigating Presto Iceberg [iss6369](https://github.com/prestosql/presto/issues/6369)

the problem might be in `ParquetWriter#length()`, method

```
return writer.getPos() + (writeStore.isColumnFlushNeeded() ? writeStore.getBufferedSize() : 0);
```

maybe that's why a parquet file size in manifest > actual file size on drive

**Comment by dmgcodevil** [comment]
Quick update: I've reproduced the issue. will update the ticked as soon as I have the details

**Comment by dmgcodevil** [comment]
Ok, based on my debugging research the _problem_ in this [line](https://github.com/apache/iceberg/blob/1b66bdfc084ac73fe999299d041aa2e5677f43c9/parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java#L130)

i.e. `writer.getPos() ` returns the corrent size of the actual parquet file saved on disk, but `writeStore.isColumnFlushNeeded()` returns true and adds extra bytes. 

In my case, the actual file size is `4351656`, rows count = `470099`

at the moment when `length()` is called , `ColumnWriteStoreV1.rowCountForNextSizeCheck` == `470100` so `writeStore.isColumnFlushNeeded()` returns true. 

maybe it can be fixed by adding an extra check : 

```java
  @Override
  public void close() throws IOException {
    flushRowGroup(true);
    writeStore.close();
    writer.end(metadata);
    this.closed = true; // new flag indicates that writer was closed


      @Override
  public long length() {
    try {
      if (closed) {
        return writer.getPos();
      } else {
        return writer.getPos() + (writeStore.isColumnFlushNeeded() ? writeStore.getBufferedSize() : 0);
      }
    } catch (IOException e) {
      throw new RuntimeIOException(e, "Failed to get file length");
    }
  }  

  }
```

**Comment by dmgcodevil** [comment]
UPDATE: I did some testing: 739578885 total rows, 900 parquet files, 1953 manifest files. No errors found. 
The fix might be not ideal but I can confirm the now manifest files contain the correct data file sizes

**Comment by rdblue** [comment]
Sounds like you have a fix. Could you open a PR with it? Thanks!

**Comment by dmgcodevil** [comment]
@rdblue [PR](https://github.com/apache/iceberg/pull/2001) The fix fork, but I believe that there is a better way to fix it

**Comment by dmgcodevil** [comment]
@rdblue do you know when a new release will be cut off?

**Comment by rdblue** [comment]
We should have a release sometime this month.

**Comment by aokolnychyi** [comment]
@rdblue @dmgcodevil does this problem happen all the time or only in given cases? Shall we create a repair action that would fix the metadata by checking the fs?

**Comment by dmgcodevil** [comment]
@aokolnychyi I'd suggest creating a repair action. This is what we are about to do with our data.

**Comment by rdblue** [comment]
Why repair this? Is it causing problems with split planning?

**Comment by dmgcodevil** [comment]
@rdblue if you are using prestosql >= 348 you will face this [problem](https://github.com/trinodb/trino/issues/6369)

**Comment by rdblue** [comment]
Thanks for the context, @dmgcodevil. That's is definitely a problem. I think we will want to have a Trino fix for it, with the ability to fix metadata as a work-around until that is released. If you have a utility to share that fixes the metadata, I think that would be useful for other people. Thanks!
