### ISSUE TITLE
Flink :  query large iceberg tables slowly 

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1983]
when I use flink to query large iceberg table , I found that it is query slowly, it need a few minutes. 

the table is partitioned table, the daily data is about 700 million , and the sql is like this `select * from mytable where d = 20201224 limit 1`.

I only want to select one data to validate the data , but I found that the query is slowly ，even though we have push down the limit

**Comment by openinx** [comment]
Could you pls dump the stacktrace when executing the `SELECT` query  ?   I will check what's the reason that hung the query.

**Comment by zhangjun0x01** [comment]
I checked the log and found that the log is not comprehensive and does not have more useful information, 
so I want to add some logs to print the execution time of each process

**Comment by zhangjun0x01** [comment]
I tested it ,found that `limit push down` is invalid for partitioned tables

**Comment by openinx** [comment]
> limit push down is invalid for partitioned tables. 

Could you provide more details ?  This is limited by apache flink,  Or bugs from iceberg integration work ?

**Comment by zhangjun0x01** [comment]
I did a detail test, if we add a query condition in `where`, for example `select * from mytable where d = 20201224 limit 1 ` the limit push down will fail , both partitioned table and unpartitioned table.

I test `HiveTableSource` in flink,it has the same problem. (Except the condition is the partition field)

I am not sure whether this is a bug for flink

**Comment by zhangjun0x01** [comment]
I look up the flink source code ,I found the comment. [here](https://github.com/apache/flink/blob/master/flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushLimitIntoTableSourceScanRule.java#L64)

```
      // a limit can be pushed down only if it satisfies the two conditions: 1) do not have order
        // by keys, 2) have limit.
```

I think it may be a flink bug ,I create a [flink issue](https://issues.apache.org/jira/browse/FLINK-20809) to trace this
