### ISSUE TITLE
no 0.10.0 for iceberg-hive

### ISSUE THREAD

**Issue by bowenli86** [apache/iceberg#1992]
Hello, why isn't there a 0.10.0 for https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-hive?

**Comment by kbendick** [comment]
Hi @bowenli86, there is no 0.10.0 version of that artifact as the iceberg hive code has been broken up into a few modules. Likely the one that you want is [https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-hive-runtime](https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-hive-runtime) if you're looking to run hive jobs.

Feel free to close this issue if that sorts out your problem!

**Comment by pvary** [comment]
Hi @bowenli86,

Was iceberg-hive-runtime.jar what you were looking for?

Thanks,
Peter

**Comment by yutaoChina** [comment]
iceberg will support hive1.x
