### ISSUE TITLE
Flink : table column comment missing

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1995]
When we create an iceberg table by flink (hive catalog mode), the field comment is missing, so we cannot view the column comment on hive or flink.

**Comment by kbendick** [comment]
This is possibly somewhat related to the loss of field level docs when converting between iceberg schemas and avro schemas, as mentioned here: https://github.com/apache/iceberg/issues/1954

I submitted a patch which merged this morning. You might see if that resolves the issue? If I have time I can add a test to check if this is still the case (or just test manually), but from memory the flink code _appeared_ to pull field docs when I worked on that ticket so I think they're likely lost when the iceberg schema is passed through to avro (for manifests).

**Comment by kbendick** [comment]
For reference, the associated PR that retains the avro field docs (which I'm pretty sure is where the loss is happening) is https://github.com/apache/iceberg/pull/1991.

It's possible that the field comments have been lost given that you cannot view the comments in either hive or flink. You could inspect one of the more recent table manifest files for the header to get the schema. If the comments are not there, you might need to run an `ALTER TABLE` command to re-add them on existing tables (assuming this patch fixes the problem).

**Comment by zhangjun0x01** [comment]
@kbendick I tested it use iceberg master branch , the comment is still missing,I will look up the reason later

**Comment by luoyuxia** [comment]
Flink itself dosen't support column comment.  There is  [FLINK-22936)](https://issues.apache.org/jira/browse/FLINK-22936) for supporting it.
