### ISSUE TITLE
Add Python Operation for STARTS_WITH

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#2019]
While working on this issue for adding a NOT_STARTS_WITH operation, I noticed that there does not seem to be a Python equivalent to the Java STARTS_WITH operation.

We should add this in.

**Comment by kbendick** [comment]
I can try to handle this while I'm working on adding the NOT_STARTS_WITH operator, though if anybody else has interest in it, please let me know and I'll let you know where I'm at and if you can take it over 👍

**Comment by kbendick** [comment]
This issue was found while I was working on a PR for this issue, supporting not starts_with, and should be linked. https://github.com/apache/iceberg/issues/1952

**Comment by kbendick** [comment]
If somebody else wants to take over this, I'm still waiting on my NOT_STARTS_WITH pr to be finished getting reviewed. It's possible I'll have time for this soon, but putting that out there in case this is blocking anybody somehow.

**Comment by holdenk** [comment]
I've been meaning to get familiar with the iceberg Python stuff so if your open to having me work on this one let me know :)

**Comment by Fokko** [comment]
This has been implented a while ago: https://github.com/apache/iceberg/pull/6892 closing this one, thanks everyone!
