### ISSUE TITLE
Flink : The Iceberg metadata is not updated after the SavePoint recovery task

### ISSUE THREAD

**Issue by sunzheng1002** [apache/iceberg#2023]
My task logic is to consume Kafka data and write to HDFS.
I stopped the task through the flink stop command, generated savePoint, and then resumed the task according to savePoint. After starting the task,checkpoint is submitted normally, and the data file on HDFS is generated normally. However, iceberg's metadata is not updated, so I cannot search the recovered data.

**Comment by openinx** [comment]
What do you mean about `iceberg's metadata is not updated`  ?  You mean the iceberg did not commit the txn successfully then you can read the latest data files ?

**Comment by sunzheng1002** [comment]
> What do you mean about `iceberg's metadata is not updated` ? You mean the iceberg did not commit the txn successfully then you can read the latest data files ?

Yes, the Iceberg txn is not submitted properly and I can't read the new data.

**Comment by sanguines** [comment]
@sunzheng1002 How was this problem resolved?
