### ISSUE TITLE
Flink should push down filter to iceberg

### ISSUE THREAD

**Issue by dixingxing0** [apache/iceberg#2037]
Currently IcebergTableSource did not implement FilterableTableSource interface, so the filter can not push down to iceberg.
I found a related issue https://github.com/apache/iceberg/issues/1983

**Comment by openinx** [comment]
There's a PR addressing this issue https://github.com/apache/iceberg/pull/1893,  but it's still being reviewing.  I think it will be merged before 0.11.0 release.

**Comment by dixingxing0** [comment]
Ok， i will close it.
