### ISSUE TITLE
Partial data ingestion to Iceberg in failing with Spark 3.0.x

### ISSUE THREAD

**Issue by mehtaashish23** [apache/iceberg#2040]
GIST: https://gist.github.com/mehtaashish23/7fccdd8df620cf9fe34dd146441126a9

If you have a table with 3 fields (Example: f1, f2, f3) but you create dataFrame with field f1,f2 (partial data) and write it to Iceberg, it fails with following exception on Spark 3.0.x. GIST to reproduce this is mentioned above.

```
org.apache.spark.sql.AnalysisException: Cannot write incompatible data to table 'file:////Users/ashmehta/git_code/aep/siphon-tools/test/87f082ca-0463-4d10-8300-f8667e5005dc-master':
- Cannot find data for output column 'f3';
  at org.apache.spark.sql.catalyst.analysis.TableOutputResolver$.resolveOutputColumns(TableOutputResolver.scala:72)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveOutputRelation$$anonfun$apply$30.applyOrElse(Analyzer.scala:2859)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveOutputRelation$$anonfun$apply$30.applyOrElse(Analyzer.scala:2854)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDown$2(AnalysisHelper.scala:108)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:73)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDown$1(AnalysisHelper.scala:108)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:212)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDown(AnalysisHelper.scala:106)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDown$(AnalysisHelper.scala:104)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators(AnalysisHelper.scala:73)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators$(AnalysisHelper.scala:72)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:29)```

**Comment by mehtaashish23** [comment]
@rdblue : I tried to debug this, it seems in V2WriteCommand in Spark 3.0.x (not the latest master) gets the table (NamedRelation) with 3 columns [here] in output, whereas in Spark 3.2.x (latest master) we are able to write partial data, because we are getting 2 columns there (not sure what major things have changed, and if they are intended)

NOTE: If I try to insert data using insert SQL in Spark 3.2.x (where the dataFrame.write works fine) I hit following

So at this point in time, I am not clear what's the correct direction to resolve this, because of inconsistent behavior.

```
scala> sc.parallelize(Seq((s"f1ValueFile",s"f2ValueFile"))).toDF("f1","f2").registerTempTable("input")
warning: there was one deprecation warning (since 2.0.0); for details, enable `:setting -deprecation' or `:replay -deprecation'

scala> spark.read.format("iceberg").load(masterTablePath).registerTempTable("target")
warning: there was one deprecation warning (since 2.0.0); for details, enable `:setting -deprecation' or `:replay -deprecation'

scala> spark.sql("insert into target (select * from input)").show(false)
org.apache.spark.sql.AnalysisException: Cannot write to 'file:////Users/ashmehta/git_code/aep/siphon-tools/test/172adb28-dff0-4063-bdea-0cd533c4c8de-master', not enough data columns:
Table columns: 'f1', 'f2', 'f3'
Data columns: 'f1', 'f2';
```


[here]: https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/v2Commands.scala#L47

**Comment by RussellSpitzer** [comment]
I'm not sure why the INSERT INTO behavior has changed, but from what I know the command by default only uses positional information not name resolution when doing inserts. My assumption is that it assumes that since no columns were specified, the insert will be looking for 3 input columns to match the 3 columns in the target.

I am pretty sure that to do an insert of specific columns it is supposed to be 
```sql
INSERT INTO TABLE table (col1, col2) (SELECT dataForCo1, dataForCol2 FROM otherTable)
```
Which i believe is the Hive syntax for this sort of thing. Programmatically the "writeTo(table)" api should do automatic name resolution and not have the same issues as the "INSERT INTO" sql command.

**Comment by kirandk** [comment]
I have the issue even in Spark 3.2.0 (same code as in posted in original https://gist.github.com/mehtaashish23/7fccdd8df620cf9fe34dd146441126a9)

Any workaround/alternate?

**Comment by heimohe** [comment]
i meet the same problem, want to write part column to table.
for example:
my dataframe data has 5 columns , but my iceberg table  has 8 columns, it will "org.apache.spark.sql.AnalysisException: Cannot write incompatible data to table 'iceberg.default...."

**Comment by mriveraFacephi** [comment]
Same problem here with Spark 3.1.1 and Iceberg 0.13.1. I'm trying to write dataframe by using the Spark v2 API command writeTo. 
Every column in my schema is nullable. In my case, I'm using AWS Glue, and the table metadata looks like:
`"Columns": [
      {
        "Name": "col",
        "Type": "string",
        "Parameters": {
          "iceberg.field.current": "true",
          "iceberg.field.id": "1",
          **"iceberg.field.optional": "true"**
        }
      },...`

Thanks

**Comment by haydenflinner** [comment]
Same thing here, happening whether I use INSERT INTO or the dataframe API. How annoying. Is there really no solution besides messing with the dataframe schema to ensure it has the same number of columns as the iceberg table? Seems annoying to evolve the table this way.

```
    # spark.sql(
    #     f"""CREATE OR REPLACE TEMPORARY VIEW myview USING parquet
    #             OPTIONS (path "{path}")"""
    # )
    # log.info("calling-insert")
    # spark.sql(f"INSERT INTO {tablename}({', '.join(df.columns)}) SELECT * FROM myview")

---> leads to:
    # Table columns: 'server_name', 'backed_up_path', 'backed_up_filesize', 'num_lines', 'backed_up_ts', 'start_ts', 'end_ts', 'first_x_ts', 'last_x_ts'
    # Data columns: 'server_name', 'backed_up_path', 'backed_up_filesize'
```
or
```
    df.to_parquet(path, index=False, allow_truncated_timestamps=True, coerce_timestamps='us')
    spark = _get_spark()
    spark.sql("use dev_catalog")
    sdf = spark.read.parquet(path)
    sdf.writeTo(f"dev_catalog.{tablename}").append()
--> leads to:
AnalysisException: Cannot write incompatible data to table 'dev_catalog.logfiles':
- Cannot write nullable values to non-null column 'backed_up_path'
- Cannot find data for output column 'num_lines'
- Cannot find data for output column 'backed_up_ts'
- Cannot find data for output column 'start_ts'
- Cannot find data for output column 'end_ts'
- Cannot find data for output column 'first_x_ts'
- Cannot find data for output column 'last_x_ts'

```

**Comment by RussellSpitzer** [comment]
Both Spark and Iceberg have their own checks to determine whether an input schema is valid for writing to a given table. The Spark checks are first and require that all of the columns present in the output table are also present in the Dataframe writing to that table. To fix this a flag is allowed to be set which will disable the Spark Checks for compatible schema and instead it will only use the Iceberg check. This is accomplished by setting write.spark.accept-any-schema in the table properties.

```
  public static final String SPARK_WRITE_ACCEPT_ANY_SCHEMA = "write.spark.accept-any-schema";
```

You may also

**Comment by Akshay-connectwise** [comment]
Hi @RussellSpitzer,
Have tried setting up the table properties but it didn't worked for me below is table creation query and error when I have an extra column "comment" . This is using Pyspark in jupyter notebook
-->spark.sql("CREATE TABLE iceberg.employee ( \
	firstname string, \
	middlename string, \
	lastname string, \
	id string, \
	gender string, \
	salary bigint ) \
USING iceberg \
TBLPROPERTIES ('SPARK_WRITE_ACCEPT_ANY_SCHEMA'='write.spark.accept-any-schema')")

Error:
AnalysisException: 
Cannot write to 'local_schema_evo.iceberg.employee', too many data columns:
Table columns: 'firstname', 'middlename', 'lastname', 'id', 'gender', 'salary'
Data columns: 'firstname', 'middlename', 'lastname', 'id', 'gender', 'salary', 'comment'

While checking table properties this property is enabled but still not working. Please suggest if we have any other way for schema evolution without using Alter queries.

**Comment by RussellSpitzer** [comment]
The property key is 

'write.spark.accept-any-schema'
And the value should be 
'true'

**Comment by Akshay-connectwise** [comment]
Thanks!!
After adding the property key able to append data with additional column while keeping "mergeSchema" option true.
