### ISSUE TITLE
Remove calls to the deprecated Metrics constructors

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#2044]
There are a couple of constructors for `org.apache.iceberg.Metrics` that are marked as deprecated (and to be removed in the Iceberg 0.12 release). I encountered these when working on an issue for supporting not starts with functionality.

It seems easy enough to clean up. If nobody picks up this task, I'll take it after I complete the NOT_STARTS_WITH functionality. I should have a PR for that by Friday or so.

**Comment by kbendick** [comment]
For reference, here's the issue I'm working on before I can pick this one up: https://github.com/apache/iceberg/issues/1952

If anybody would like to take this issue, please just comment on this ticket and let me know and I'd be happy to hand it off to you. 👍

**Comment by yyanyy** [comment]
Thanks for creating this task! Just to give some context, I originally added the new constructors and marked the old one as deprecated, as I was implementing NaN counter across different writers, which is still in progress/under review.
