### ISSUE TITLE
Could Hive alter iceberg table?

### ISSUE THREAD

**Issue by a49a** [apache/iceberg#2063]
I'm not found in offical document. I only found that Spark SQL 3.0 can alter iceberg table? Could Hive do this?

**Comment by pvary** [comment]
@deadwind4: If your question is about having a Hive SQL command which could alter an EXTERNAL Hive table which is backed by an Iceberg table then sadly the answer is no. With some further development we can make it possible with the use the Hive 3.1.2 API to update the table properties, but with the current API I do not see a way for schema evolution.

**Comment by deadwind4** [comment]
So, it is not supported to add a column to INTERNAL Hive table with hive current API, right?

**Comment by silvermissile** [comment]
So this means that  table created though hive_catalog   con't schema evoulution  for now

**Comment by pvary** [comment]
I think using Spark/Flink or whatever API we can evolve the schema (we have not checked yet if the resulting table could be read or not by Hive), but we can not do schema evolution from Hive or Impala - there are ongoing efforts but nothing available ATM
