### ISSUE TITLE
Rewrite metrics during schema transformation

### ISSUE THREAD

**Issue by holdenk** [apache/iceberg#2079]
See discussion @ https://github.com/apache/iceberg/pull/2048#discussion_r555831963

**Comment by aokolnychyi** [comment]
@RussellSpitzer @holdenk, will you have time to work on this one? I think it is quite important since our schema evolution will break if someone renames or drops a column that is referenced by the metrics config.

**Comment by holdenk** [comment]
Yeah I'm happy to do the follow on task :)

**Comment by aokolnychyi** [comment]
Thanks, @holdenk!

**Comment by holdenk** [comment]
So I'm thinking that rather than rewrite the metrics during schema transformation, when the schema is loaded we convert the from column names to references. What do folks think?

**Comment by aokolnychyi** [comment]
@holdenk, could you elaborate a bit more on the idea? I am not sure I fully understood.

**Comment by holdenk** [comment]
So when we resolve we'd transform the table properties to point to column references. This would mean the table properties would sort of change underneath folks which might not be desirable, but it would simplify the logic for handling updates.

**Comment by holdenk** [comment]
So @aokolnychyi WDYT?

**Comment by aokolnychyi** [comment]
Oops, I missed the last comment.

**Comment by aokolnychyi** [comment]
So, @holdenk, are you saying instead of modifying the table properties during schema evolution, try to resolve them correctly during writes?

Let's take an example. Suppose we have a metrics config for `sort_col_1` as `full`. Then we rename `sort_col_1` into `sort_col_2`. What should happen with metrics? I am afraid it will fail now as there is no `sort_col_1` anymore.

**Comment by holdenk** [comment]
So what I'm saying is when we write out table properties we resolve the current column name to the column index and write out the column index.

**Comment by aokolnychyi** [comment]
Essentially migrate the metrics config to use column ids instead of column names?

**Comment by aokolnychyi** [comment]
Let me summarize how I got it.

The idea is to interpret table properties like `write.metadata.metrics.col1` as `write.metadata.metrics.10` (where 10 is the column id of `col1`). That way, we don't have to do anything when a column is renamed as the id stays same. We will also need to add some logic to convert column ids back into column names when showing table properties to the user.

 When we drop `col1`, it is alright to keep the old property and it will simply not be shown to the user?

Is that the idea, @holdenk?

**Comment by holdenk** [comment]
That's the idea, however now that I'm looking at the code again that would require changing the (public) API of `MetricsConfig.java` so it's maybe not ideal.

**Comment by aokolnychyi** [comment]
We have been discussing using column ids in the metrics config for a while. I'd support the migration now.

@RussellSpitzer @rdblue @shardulm94 @danielcweeks @pvary @openinx, thoughts?

**Comment by aokolnychyi** [comment]
We will have to be careful with existing tables as they may be accessed by different versions of Iceberg but I feel we can figure that out.

**Comment by holdenk** [comment]
Ah, that's a good point, how about I start with the rewriting for now and we can figure out what we want to do with the translation later?

**Comment by pvary** [comment]
What happens if we have missing metrics? Could we still read the data, or we error out?

Anyway, I would suggest to have a different prefix for the new properties, so we do not accidentally try to read column names as column ids or column names as ids.

**Comment by aokolnychyi** [comment]
> Ah, that's a good point, how about I start with the rewriting for now and we can figure out what we want to do with the translation later?

Seems like old writers would still need us to rewrite, yeah.

> What happens if we have missing metrics? Could we still read the data, or we error out?

I *think* we just use the default value and never fail writes. If that is not the case, we should fix it.

> Anyway, I would suggest to have a different prefix for the new properties,

Maybe we can have some prefix for internal properties we don't want to show to the user? Thoughts, @holdenk @pvary @rdblue @RussellSpitzer?
