### ISSUE TITLE
Improve HadoopCatalog performance/scalability

### ISSUE THREAD

**Issue by steveloughran** [apache/iceberg#2124]
By moving HadoopCatalog onto `listStatusIterator()` list API calls, filesystem clients which do paged listings (hdfs, webhdfs, s3a, and soon abfs) can mix prefetching of the next page of results while HadoopCatalog examines the current entries. This makes a difference on object stores. (Not that you should be using HadoopCatalog on S3; ABFS is a different matter)

**Comment by aokolnychyi** [comment]
Thanks for submitting a fix for this, @steveloughran. Seems like this issue is resolved but I am wondering whether we should add this functionality to other places like `RemoveOrphanFilesAction` that do lists as well.

**Comment by steveloughran** [comment]
possibly. main performance gain would be on azure storage as abfs does async paged reads; for s3 you shouldn't be using this catalog
