### ISSUE TITLE
MySQL binlog is synchronized to iceberg through CDC

### ISSUE THREAD

**Issue by zanmeipaul** [apache/iceberg#2128]
Does the community have a plan to synchronize data to iceberg through MySQL binlog CDC, and DDL statements can be synchronized at the same time, or does the community plan to solve it

**Comment by ismailsimsek** [comment]
@zanmeipaul i have [ debezium-server-iceberg ](https://github.com/memiiso/debezium-server-iceberg) doing that, using debezium-server. 
using this project you can append CDC data/events to iceberg table. without spark or kafka in between.

i was planing to add it to iceberg reference list, if it fits to iceberg project Im happy to create pull request. @rdblue

**Comment by rdblue** [comment]
@ismailsimsek, sounds like an interesting use case! If you write up a blog post or anything, please let us know. I don't think that we want to include projects that specific in Iceberg itself, but I would definitely want to highlight your work in the community to let others know about it. Maybe send an email to the dev list?

**Comment by ismailsimsek** [comment]
agree that makes sense, i will share on dev list, and put link to blog page after its created
