### ISSUE TITLE
Improve the flink document page for iceberg release 0.11.0

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#2136]
Since we've merged those major features for flink module,  it's necessary to update the flink document so that flink users could get start to use those features quickly.  

The major features are: 
1.  Flink Streaming reader ; 
2.  Iceberg's `write.distribution-mode` to reduce small files when starting flink streaming job to write data to iceberg.
3.  Flink's batch rewrite actions.

**Comment by rdblue** [comment]
Merged #2147.

Docs aren't included in the releases, we just update the site afterwards. So there is no need to get these done before the release in the future. We can always fix the site after.
