### ISSUE TITLE
Spark : list Avro format partition error in SparkTableUtil

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#2161]
In method `org.apache.iceberg.spark.SparkTableUtil#listAvroPartition` ,when we list the file to structure `DataFile`，the  `recordCount` is missing, the `recordCount` of `Metrics` is -1, and also not be set by `DataFiles.builder(spec).withRecordCount()`,but the recordCount is required.

`org.apache.iceberg.DataFiles.Builder#build` method will check the recordCount
```
Preconditions.checkArgument(recordCount >= 0, "Record count is required");
```

**Comment by szehon-ho** [comment]
This issue fixed by linked PR
