### ISSUE TITLE
release python pkg to pypi?

### ISSUE THREAD

**Issue by CodingCat** [apache/iceberg#2194]
Hi, all

is there any recent plan to release python pkg to pypi?

Thanks

Nan

**Comment by alec-heif** [comment]
+1 for this, it seems to have been available for quite a while now so hopefully is out of the pure "development only" stage?

**Comment by jun-he** [comment]
Yes, we are working on it now. The progress is tracked at https://github.com/apache/iceberg/projects/7.

**Comment by samredai** [comment]
Closing this now that pyiceberg has been released.
