### ISSUE TITLE
Flink: IcebergTableSink to write data into multiple iceberg tables

### ISSUE THREAD

**Issue by ashajyothi828** [apache/iceberg#2208]
Hi Team,

I have a flink job that read tranasctions data from a single source and creates iceberg tables. I need to create multiple datasets for each account in the list of transactions. The IcebergTableSink accepts the TableLoader on the constructor, but my table name is based on the account Id on each transaction and the account Ids is not a predefined list. This means I have to decide which table to load data into while writing the code, but I want it to be dynamic based on the account Id. Is there a better way to handle it? Here's the job I have to create one iceberg table from the job. Appreciate any help here.

public static void main(String[] args) throws Exception {
		StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

		DataStream<Transaction> transactions = env
			.addSource(new TransactionSource())
			.name("transactions");

		DataStream<RowData> rows = transactions
			.keyBy(Transaction::getAccountId)
			.process(new FraudDetector())
			.name("fraud-detector");
                TableSchema ts = TableSchema.builder()
     	                         .field("AccountId", DataTypes.BIGINT())
     	                         .field("Timestamp", DataTypes.BIGINT())
     	                         .field("Amount", DataTypes.DOUBLE())
     	                         .build();
               // TODO: need to write to multiple tables here based on Transaction::getAccountId
               String tablelocation = "./data/flinklocal/transactions5";
               TableLoader tl = TableLoader.fromHadoopTable(tablelocation, hadoopConf);
               IcebergTableSink sink = new IcebergTableSink(false, tl, ts);
               sink.consumeDataStream(rows);
               env.execute("Multiple transactional datasets");
}

**Comment by zhangjun0x01** [comment]
Why do you want to create multiple tables? I think it might be more reasonable to use dynamic partition

**Comment by ashajyothi828** [comment]
> Why do you want to create multiple tables? I think it might be more reasonable to use dynamic partition

Because the incoming data belongs to different datasets. The transaction that I'm trying to insert here is a very simple schema, but our main aim is to implement this job for a larger usecase where the incoming data can belong to multiple datasets. I'm doing some groundwork for some design options we are considering and this is where I got stuck.

**Comment by stevenzwu** [comment]
Currently, Flink Iceberg sink can only write to one table with exactly-once semantic.

If the table partition doesn't fit your requirements, maybe you can use filter or side output to split the stream into multiple sub streams. then attach a separate Iceberg sink to each sub DataStream. This probably won't work if the number of tables/datasets is really high (like hundreds). In that case, maybe split the uber stream before the Iceberg ingestion jobs.

**Comment by caseylucas** [comment]
I work with Asha, so chiming in (and seeking guidance):

Assumptions:
1. There will N destination Iceberg tables that have *different schemas*.
2. N will grow over time and may be large - probably unreasonable to have a growing number of Kafka topics.

So the scenario looks like:
```
1. data for all N destinations (packaged up with some discriminator)
--->
2. single Kafka topic
--->
3. Flink job (reading from Kafka source)
--->
4. N Iceberg tables
```

In step 3 & 4, I assume there would need to be some demultiplexing - selecting the
appropriate Iceberg table dynamically.  There are some options for doing this with
Kafka (https://stackoverflow.com/questions/45391877/apache-flink-dynamic-number-of-sinks) -
allowing runtime selection of a destination topic
(https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/util/serialization/KeyedSerializationSchema.html),
but the Iceberg Sink doesn't appear to currently support this scenario.

Being new to Iceberg and Flink, I'm wondering if this demultiplexing needs to be implemented
in the Iceberg Flink sink or maybe there is some built in Flink support or concept that we're
missing.

If demultiplexing needs to be built into the Flink sink, are there any issues that should be
considered before we go down the path of implementing such a strategy?

**Comment by stevenzwu** [comment]
Yeah, a single Kafka producer/sink supports writing to multiple Kafka topics as long as they are all on the same Kafka cluster. However, it is not without penalty though, as it will affect data batching and impact disk I/O on the broker side. 

It is very expensive for a single Iceberg sink to support growing and large number tables. The writers would need to keep many open files. That could lead to memory pressure for writer tasks. When it is time to checkpoint and commit, the writers need to flush and upload files for hundreds of tables and the committer needs to commit hundreds of tables. That would be very slow. I would suggest doing the demux before the sink jobs to Iceberg.

Also if you have single Kafka topic holding different and growing number of datasets, you also loose the benefit of schema validation when ingesting data to Kafka. Having separate Kafka topic and schema validation for each dataset may also help with the data quality.

**Comment by caseylucas** [comment]
@stevenzwu Thanks for the advice. We're now looking at using the approach (as you mentioned) of doing the demux before the sink. Based on my understanding, we may need to implement our own sink similar to the existing IcebergTableSink but instead of knowing the table name at construction time, we'll lazily determine the table. We'll use the KeyBy transformation in flink so that we end up with one sink per key (which corresponds to an iceberg table in our case.)

**Comment by stevenzwu** [comment]
@caseylucas keyBy can help address some of the problems. not sure about your datasets. just watch out the traffic imbalance for the keyBy shuffle.

**Comment by ashajyothi828** [comment]
@stevenzwu Thanks for your response. We actually tried implementing a custom sink that can determine the table name at runtime, but I faced trouble when trying to generate the table name based on the key. I was not able to get the key in the sink based on which I want to name my table. I see that there's a `getCurrentKey()` function in the KeyedProcessFunction, but that was not available in the sink. Couldn't find anything that can help (with passing the data from the source to sink) in the Sink.Context available. Can you think of anything that can help me with this?

**Comment by stevenzwu** [comment]
I probably missed sth here. can't you get the key from payload/record?

**Comment by ashajyothi828** [comment]
Cant get the key from a record in the stream, the sink takes the stream as input and couldnt figure out how to get the key that applies to that stream. Basically tried to implement the below method in the sink and was not able to get the key value present in  RowData.

public DataStreamSink<?> consumeDataStream(DataStream<RowData> dataStream) {}

**Comment by spancer** [comment]
> Currently, Flink Iceberg sink can only write to one table with exactly-once semantic.
> 
> If the table partition doesn't fit your requirements, maybe you can use filter or side output to split the stream into multiple sub streams. then attach a separate Iceberg sink to each sub DataStream. This probably won't work if the number of tables/datasets is really high (like hundreds). In that case, maybe split the uber stream before the Iceberg ingestion jobs.

Hi steven, 
  Using a side-output stream and attach a separate sink to each sub-stream can't solve the problem gracefully. This requires a fixed count of sub-streams, or we have to bind each sub-stream to a pre-defined name, otherwise, we can't use them in the follow-up sink. Because we have to make sure the job graph is pre-defined. I think using two jobs might achieve this.

**Comment by stevenzwu** [comment]
here is the difference btw Kaka sink and Iceberg sink. Kafka essentially takes in byte[] as payload. Hence it doesn't care about the schema. Iceberg sink has table schema when writing out data files. that is why it is difficult for a single Iceberg sink to write to multiple Iceberg tables with different schemas.

On the other hand, this ask has been brought up a few times. so there is demand for it. If we are going to support it, it will likely be a facade sink that can creates the individual writers internally. We would also need the multi-table transaction capability from PR #6948 first.

Then there is another question on if the Iceberg table creation should be outside the scope of the Flink sink, which is the case today. maybe we should continue to operate with that assumption that table creation is out of band.

**Comment by AraiYuno** [comment]
Is there any update on this feature?

**Comment by MichaelHan0228** [comment]
> Is there any update on this feature?

I also need this feature in my own project, just when try to do sth like ETL from kafka to iceberg, I need to write data into different tables based on log name. It seems that this can not be achieved still

**Comment by AraiYuno** [comment]
> > Is there any update on this feature?
> 
> I also need this feature in my own project, just when try to do sth like ETL from kafka to iceberg, I need to write data into different tables based on log name. It seems that this can not be achieved still

I ended up writing my own `IcebergFilesCommitter` for multiple tables

**Comment by thuongle2210** [comment]
> @caseylucas keyBy can help address some of the problems. not sure about your datasets. just watch out the traffic imbalance for the keyBy shuffle.

How did you ensure Flink sink data to iceberg that achieve exactly-once semantic?

**Comment by thuongle2210** [comment]
> Currently, Flink Iceberg sink can only write to one table with exactly-once semantic.
> 
> If the table partition doesn't fit your requirements, maybe you can use filter or side output to split the stream into multiple sub streams. then attach a separate Iceberg sink to each sub DataStream. This probably won't work if the number of tables/datasets is really high (like hundreds). In that case, maybe split the uber stream before the Iceberg ingestion jobs.

**Comment by thuongle2210** [comment]
> Currently, Flink Iceberg sink can only write to one table with exactly-once semantic.
> 
> If the table partition doesn't fit your requirements, maybe you can use filter or side output to split the stream into multiple sub streams. then attach a separate Iceberg sink to each sub DataStream. This probably won't work if the number of tables/datasets is really high (like hundreds). In that case, maybe split the uber stream before the Iceberg ingestion jobs.

How did you ensure Flink sink data to iceberg that achieve exactly-once semantic?  @stevenzwu
