### ISSUE TITLE
Spark: Extend expire_snapshots procedure with an optional arg for snapshot ids

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2221]
I think we should extend our `expire_snapshots` procedure to also accept an optional list of snapshots ids. That way we match the behavior in the `Table` API. It may be useful when someone generated a lot of compaction snapshots and wants to expire them even though they are recent.

```
  private static final ProcedureParameter[] PARAMETERS = new ProcedureParameter[] {
      ProcedureParameter.required("table", DataTypes.StringType),
      ProcedureParameter.optional("older_than", DataTypes.TimestampType),
      ProcedureParameter.optional("retain_last", DataTypes.IntegerType),
      // new optional parameter to specify snapshot ids to expire
      ProcedureParameter.optional("snapshots_ids", DataTypes.createArrayType(DataTypes.LongType))
  };
```

**Comment by aokolnychyi** [comment]
@RussellSpitzer @rdblue, thoughts?

**Comment by RussellSpitzer** [comment]
I think that's reasonable, better than full subquery support :) One thing I worry about is we have a bunch of code which relies on the snapshot chain being fully connected. So if we have Snapshots A, B, C and remove B, will we have issues?

Also this means we will have to extend the parser to also handle Array types I think

**Comment by rdblue** [comment]
Hm, I'm not sure it's a good idea to age off individual snapshots. It is safe for the parallel operation, but it can cause issues with incremental snapshot expiration because of assumptions that snapshots are expired linearly. Maybe that's okay since the deletes happen using the reachability set?

**Comment by aokolnychyi** [comment]
@RussellSpitzer @rdblue, isn't it a use case we allow in the Table and Actions APIs?

**Comment by aokolnychyi** [comment]
I think expiring B in A, B, C should be fine as we will have a union of all files referenced by A and C as our reachability set.

**Comment by aokolnychyi** [comment]
Plus, expiring by ids may be useful if a snapshot was rolled back, for example.

**Comment by capkurmagati** [comment]
I did something like the below to expire selected snapshots via Java API
```scala
val snapshots = sql("select * from iceberg.db.tbl.snapshots")
val snapshotsToDel = snapshots.select("snapshot_id").filter($"committed_at" < "2020-10-06 12:59:00" ).filter($"committed_at" > "2020-10-06 12:01:00" ).collectAsList
snapshotsToDel.forEach( id => table.expireSnapshots.expireSnapshotId(id.getLong(0)).commit()  )
```
I don't if it's a common use case but our use case is:
1. We have a CDC pipeline for an online RDBMS table. The writer consumes the CDC log and writes to Iceberg every 15min.
2. The users can query/time travel hot data via 15-min snapshots.
3. Once the data became cold. (usually after 2 weeks in our environment). We want to downsample the snapshots to reduce the data size. To keep the `hourly` snapshots only and remove those in between.
4. (Haven't done it yet). Maybe we want to downsample to daily after a longer period. (Our previous batch ingestion pipeline is based on daily Sqoop jobs)

**Comment by rdblue** [comment]
> @RussellSpitzer @rdblue, isn't it a use case we allow in the Table and Actions APIs?

Yes, but this is in the API from back when we didn't keep parent information for snapshots. I'm not sure how good of an idea it was for me to add it back then.

**Comment by RussellSpitzer** [comment]
I was mentioning the sequence thing because our current plans for doing the Streaming source basically rely on our ability to successfully crawl from the "begin snapshot" to the "end snapshot". If a user removed internal snapshot "b", is it still possible to do an incremental scan? What does it mean in that case?

**Comment by pan3793** [comment]
> I don't if it's a common use case but our use case is:
> 
> 1. We have a CDC pipeline for an online RDBMS table. The writer consumes the CDC log and writes to Iceberg every 15min.
> 2. The users can query/time travel hot data via 15-min snapshots.
> 3. Once the data became cold. (usually after 2 weeks in our environment). We want to downsample the snapshots to reduce the data size. To keep the `hourly` snapshots only and remove those in between.
> 4. (Haven't done it yet). Maybe we want to downsample to daily after a longer period. (Our previous batch ingestion pipeline is based on daily Sqoop jobs)

It coincides with my idea, I am also planing to manage snapshots in such way:
1. keep hourly snapshot in current day;
2. keep daily snapshots in current week;
3. keep weekly snapshots in current month;
4. etc.

**Comment by rdblue** [comment]
@pan3793 and @capkurmagati, thanks for your comments. I think there is definitely a use case here to keep fewer snapshots in table metadata. The only problem is that we need to understand what it will do to snapshot expiration for users that don't run the version that uses reachability sets.

Maybe what we could do is add a property to disable incremental expiration before some snapshot when there was a break in history.

**Comment by aokolnychyi** [comment]
@rdblue, you mean users that rely on the Table API for expiring snapshots? That probably does not rely on reachability set.

**Comment by aokolnychyi** [comment]
@RussellSpitzer's comment on supporting streaming reads is a good one. Expiring snapshots in the middle will probably break that.

**Comment by rdblue** [comment]
@aokolnychyi, yes I am talking about the table API for expiring snapshots. That uses an incremental approach. We would need to either convert that to a reachability-based implementation (which would be slower, but good to have) or disable it.

**Comment by aokolnychyi** [comment]
Well, I think we should delay adding new params to the procedure for now given the points that were raised.

**Comment by Neuw84** [comment]
Hi! 

I have a usecase similar to the ones described (CDC).

If we are using latest version of Iceberg (1.1.0) it is safe then to delete specific snapshots using the Table API? Reading the comments seems like there could be some problems with this approach. 

Thanks!

**Comment by aokolnychyi** [comment]
@Neuw84, I think we switched the approach used in the table API to leverage a reachability set. I assume it should be safe.

**Comment by aokolnychyi** [comment]
Resolving as not something we want to do.

**Comment by ajantha-bhat** [comment]
haha. Actually we did support it. I remember someone adding it few months ago. 

https://github.com/apache/iceberg/pull/6992
