### ISSUE TITLE
Add Python Create Table support to documentation?

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#2226]
It seems while python is in development, create-table does work as per:  https://github.com/apache/iceberg/pull/1216. I was able to get it to work in our setup.

I think python users will be very interested, as many believe today that it is not supported to documentation.

Should we add this to :

https://github.com/apache/iceberg/blob/master/site/docs/python-feature-support.md
https://github.com/apache/iceberg/blob/master/site/docs/python-quickstart.md

**Comment by szehon-ho** [comment]
I am happy to add to the doc, unless there are concerns at its stability?

**Comment by rymurr** [comment]
this has been on my list for some time. We should definitely update and publish the docs.
