### ISSUE TITLE
Drop table support in python

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#2227]
After create-table is supported in: https://github.com/apache/iceberg/pull/1216, it makes sense to implement drop table.

Unless I missed it somwhere, it doesn't seem it's supported now as per:  https://github.com/apache/iceberg/blob/master/python/iceberg/hive/hive_tables.py#L37

**Comment by szehon-ho** [comment]
I would be happy to give this a stab,  but wanted to check if anyone is working on it?  @rdblue @rymurr  thanks

**Comment by rymurr** [comment]
Hey @szehon-ho no one that I am aware of is working on it and your contributions would be very welcome! Shout if you have any questions.

**Comment by szehon-ho** [comment]
Hi @rymurr i pushed my implementation (tested manually on real Iceberg table and verified all the files are gone if purge=true, if you had time to take a look.

The 3.7 tox test failures were broken before my change actually.
