### ISSUE TITLE
Can snapshot has an optional name?

### ISSUE THREAD

**Issue by pan3793** [apache/iceberg#2231]
Currently, we build ETL workflows based on Hive tables, and to achieve version control ability of data, we add a top level partition which named `ts` to all tables. And assign `ts` a specific value when trigger the workflow, then we can get the expected version of data of all tables with one `ts`.

I know I can use `snapshot_id` which is auto generated to fetch the specific version of data in iceberg table, and it means if I want to identify the snapshots of all tables involved in one workflow, every time run the workflow, I need to persist each table's `snapshot_id` when the table updated so I can use it later.

Is there an approach to assign the snapshot a `snapshot_name` besides `snapshot_id`? So we can track the snapshots of relevant tables such as generated in the same workflow in a convenient way.

**Comment by rdblue** [comment]
We've considered naming snapshots as a "tagging" feature (to borrow a term from git). I'm also interested in named branches as well, since I think you may want to actually maintain data that has been tagged. I don't have current plans to build this yet, though.
