### ISSUE TITLE
Missing handling of Timestamp Without Timezone type 

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#2244]
Spark currently possess no readers for the Timestamp.withoutZone() type but is able to create tables with this schema. These tables if you attempt to read them from Spark will error out.

Currently in master the only reader for this type that I can see is for the generic case
https://github.com/apache/iceberg/blob/631efec2f9ce1f0526d6613c81ac8fd0ccb95b5e/data/src/main/java/org/apache/iceberg/data/orc/GenericOrcReader.java#L116-L117

Other systems if they hit a table with this type will fail immediately since they do not have valid readers.

This is a bit troubling because this column type is used by default when non-iceberg ORC writers make new files, for example:

```scala
spark.sql("CREATE EXTERNAL TABLE mytable (foo timestamp) location '/Users/russellspitzer/Temp/foo'")
 spark.sql("INSERT INTO mytable VALUES (now())") 
```

Creates files 
```
File Version: 0.12 with ORC_135
Rows: 1
Compression: SNAPPY
Compression size: 262144
Calendar: Julian/Gregorian
Type: struct<foo:timestamp>
```

The non-iceberg Spark and Hive Orc readers and writers have no problem dealing with these files but, if an iceberg table is created and these files are added to it then they are unreadable by Iceberg's orc readers and writers.

There is also a related problem with Migrate -- @RussellSpitzer Add Link Here

**Comment by RussellSpitzer** [comment]
We decided in the last Sync that a reasonable solution here would be for Spark to read both timezone types as timestamp with timezone with a flag disabling this behavior by default. If the flag is disabled an error message would alert the user that Spark cannot handle the two different types and will always display the local timezone, but the underlying data would be correct.

**Comment by javsanbel2** [comment]
Hello @RussellSpitzer! I am having a similar issue and I agree to your solution as well. Did you continue working on this? I would like to know more about your approach. How would this work in practice?
