### ISSUE TITLE
Couldn't find corresponding Hive SerDe for data source provider iceberg

### ISSUE THREAD

**Issue by rlcyf** [apache/iceberg#2260]
iceberg：0.11
spark:3.0.1

bin/spark-sql \
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
--conf spark.sql.catalog.test=org.apache.iceberg.spark.SparkSessionCatalog \
--conf spark.sql.catalog.test.type=hive
```
CREATE TABLE ods.sample (id bigint COMMENT 'unique id',data string) USING iceberg
```
2021-02-21 05:30:06,902 WARN hive.HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider iceberg. Persisting data source table `ods`.`sample` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.

```
desc formatted sample;

...
Table Parameters:                
        owner                   root                
        provider                iceberg             
        spark.sql.create.version        3.0.1               
        spark.sql.partitionProvider     catalog             
        spark.sql.sources.provider      iceberg             
        spark.sql.sources.schema.numParts       1                   
        spark.sql.sources.schema.part.0 {\"type\":\"struct\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}},{\"name\":\"data\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}]}
        transient_lastDdlTime   1613907771          
                 
# Storage Information            
SerDe Library:          org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe                  <-------------
InputFormat:            org.apache.hadoop.mapred.SequenceFileInputFormat                 <-------------
OutputFormat:           org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat   <------------    
Compressed:             No                       
Num Buckets:            -1                       
Bucket Columns:         []                       
Sort Columns:           []
```

**Comment by pvary** [comment]
@rlcyf: Could you try out this with SparkCatalog instead of SparkSessionCatalog?
I have seen some problems with the SparkSessionCatalog implementation using internal Hive Catalog instead of the provided Iceberg one. The consensus was that Spark should and will fix this in their catalog implementation.

The tests were running correctly with this config:
```
        new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
            "type", "hive",
            "default-namespace", "default"
        )},
```
Thanks,
Peter

**Comment by rlcyf** [comment]
> @rlcyf：您可以使用SparkCatalog代替SparkSessionCatalog尝试一下吗？
> 我已经看到使用内部Hive Catalog而非提供的Iceberg的SparkSessionCatalog实现的一些问题。共识是Spark应该并且将在其目录实现中解决此问题。
> 
> 使用此配置，测试可以正常运行：
> 
> ```
>         new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
>             "type", "hive",
>             "default-namespace", "default"
>         )},
> ```
> 
> 谢谢
> 彼得

**Comment by rlcyf** [comment]
> @rlcyf: Could you try out this with SparkCatalog instead of SparkSessionCatalog?
> I have seen some problems with the SparkSessionCatalog implementation using internal Hive Catalog instead of the provided Iceberg one. The consensus was that Spark should and will fix this in their catalog implementation.
> 
> The tests were running correctly with this config:
> 
> ```
>         new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
>             "type", "hive",
>             "default-namespace", "default"
>         )},
> ```
> 
> Thanks,
> Peter

I have tested both SparkCatalog and SparkSessionCatalog,still can not!
use java api work fine!

**Comment by rlcyf** [comment]
> @rlcyf: Could you try out this with SparkCatalog instead of SparkSessionCatalog?
> I have seen some problems with the SparkSessionCatalog implementation using internal Hive Catalog instead of the provided Iceberg one. The consensus was that Spark should and will fix this in their catalog implementation.
> 
> The tests were running correctly with this config:
> 
> ```
>         new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
>             "type", "hive",
>             "default-namespace", "default"
>         )},
> ```
> 
> Thanks,
> Peter

I have tested both SparkCatalog and SparkSessionCatalog,still can not!
use java api work fine!

**Comment by rlcyf** [comment]
>  new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
>             "type", "hive",
>             "default-namespace", "default"
>         )},

how to use this config! can u give a full example?

**Comment by pvary** [comment]
> > new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
> > "type", "hive",
> > "default-namespace", "default"
> > )},
> 
> how to use this config! can u give a full example?

I am not too familiar with spark, but I expect that this should be something like this:

```
bin/spark-sql
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
--conf spark.sql.catalog.test=org.apache.iceberg.spark.SparkCatalog
--conf spark.sql.catalog.test.type=hive
```

**Comment by rlcyf** [comment]
> > > new Object[] { "testhive", SparkCatalog.class.getName(), ImmutableMap.of(
> > > "type", "hive",
> > > "default-namespace", "default"
> > > )},
> > 
> > 
> > how to use this config! can u give a full example?
> 
> I am not too familiar with spark, but I expect that this should be something like this:
> 
> ```
> bin/spark-sql
> --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
> --conf spark.sql.catalog.test=org.apache.iceberg.spark.SparkCatalog
> --conf spark.sql.catalog.test.type=hive
> ```

ths!
I configured it like this！Still report that warning.

**Comment by pvary** [comment]
@rlcyf: Does this prevent you from reading the data? Or it is just a warning? Does adding the iceberg-hive-runtime.jar to the classpath help?

Thanks,
Peter

**Comment by rlcyf** [comment]
> @rlcyf: Does this prevent you from reading the data? Or it is just a warning? Does adding the iceberg-hive-runtime.jar to the classpath help?
> 
> Thanks,
> Peter

put iceberg-hive-runtime.jar and iceberg-spark3-runtime.jar to spark/jars
all can be executed normally!
thanks!
