### ISSUE TITLE
Flink : add watermark support for streaming read

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#2264]
in order to support flink eventtime,I think we should add watermark support for flink streaming read.

**Comment by Reo-LEI** [comment]
Recently, I try use event time on flink streaming read. I remove the validation of watermark on `FlinkCatalog`,  and I found the watermark can work correctly. I think the watermark is the ability of flink, not the iceberg. So I want to figure out what should we need to support to iceberg for use watermark on flink streaming read
