### ISSUE TITLE
Hive: Support identifiers with catalog

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2274]
Hive 3 offers support for identifiers like `catalog_name.db_name.tbl_name`. I wanted to discuss whether we want this as it is not currently supported by our `HiveCatalog`.

One problem we will face is that v1 and v2 client APIs don't have a way to pass a catalog. It is purely a v3 feature. We could use reflection, as we do in other places, to call it, though. We can also default it in the same way Hive does for older clients.

**Comment by aokolnychyi** [comment]
@rdblue @RussellSpitzer @pvary @marton-bod, what do you think?

**Comment by pvary** [comment]
AFAIK Hive queries does not support HMS catalogs so I have only seen unit tests for them.

Shall I check the current status? What are the features we are looking for? Just one more level in the namespace hierarchy, or we are looking for sonething more?

Thanks, Peter

**Comment by marton-bod** [comment]
Hi Anton,
I just checked the Hive master code and found no query language support for catalogs, only HMS API support. I tried from our iceberg-mr unit tests and got compilation errors when using `catalog_name.db_name.tbl_name` in create table or select statements. This might limit the utility of including this into the `HiveCatalog`, at least from the Hive side - not sure if it'd add more benefit to Spark or Flink. To echo Peter, is it an extra level of namespacing that you're primarily looking for?

**Comment by aokolnychyi** [comment]
Thanks for checking the Hive side, @pvary @marton-bod. Yeah, I was primarily looking for adding an extra level of namespacing.

We have an internal metastore that implements the v3 protocol. That's why I was wondering if we ever plan to support catalogs in our `HiveCatalog` or we need to look for an alternative.

**Comment by aokolnychyi** [comment]
FYI @raptond @karuppayya
