### ISSUE TITLE
hive create external table for iceberg have error.

### ISSUE THREAD

**Issue by allenzhg** [apache/iceberg#2277]
env: 
flink version:  1.11.3 
hive version:  3.1.1
hadoop version: 3.1.2

The following is the hive table building statement ：

CREATE EXTERNAL TABLE sample2
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
LOCATION 'hdfs://xxx/usr/hive/warehouse/iceberg.db/sample1'
TBLPROPERTIES (
  'iceberg.mr.catalog'='hadoop_catalog', 
  'iceberg.mr.catalog.hadoop.warehouse.location'='hdfs://xxx/usr/hive/warehouse')
;

error:
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: MetaException(message:org.apache.hadoop.hive.serde2.SerDeException Please provide an existing table or a valid schema)

help me!!!

**Comment by pvary** [comment]
@allenzhg: What catalog do you try to do?
The valid values are:
- `hive` - HiveCatalog
- `hadoop` - HadoopCatalog

Where do you issue the table building statement? (Hive/Flink/Spark?)

Thanks,
Peter

**Comment by marton-bod** [comment]
@allenzhg Did you create the Iceberg table from Flink and then try to create a Hive table on top of it?
You might want to reference this documentation: https://iceberg.apache.org/hive/, under the `Using Hadoop Catalog` section. A couple of things stand out:
- `'iceberg.mr.catalog'='hadoop_catalog'` is not a valid catalog value, as Peter pointed out. Can you retry with `'iceberg.mr.catalog'='hadoop'`?
- According to the docs, the table name you specify to the Hive DDL must match the table name of the Iceberg table. In this case, it seems that the Iceberg table is called `sample1`, whereas you are trying to create a Hive table called `sample2` on top of it.

**Comment by allenzhg** [comment]
> @allenzhg: What catalog do you try to do?
> The valid values are:
> 
> * `hive` - HiveCatalog
> * `hadoop` - HadoopCatalog
> 
> Where do you issue the table building statement? (Hive/Flink/Spark?)
> 
> Thanks,
> Peter


the table building statement in hive. i wanted from hive read iceberg table content.
thanks.

**Comment by allenzhg** [comment]
> * case

1. hadoop_catalog does me created.
building statement is :
CREATE CATALOG hadoop_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hadoop',
  'warehouse'='hdfs://usr/hive/warehouse/',
  'property-version'='1'
);

CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://172.24.xxx:xxx'
  'clients'='20',
  'property-version'='1',
  'warehouse'='hdfs://usr/hive/warehouse/'
);

2. create same table for sample1 and have a same error.
 create table statement  in flink sql client:
USE CATALOG hive_catalog;
CREATE DATABASE iceberg_db;
CREATE TABLE sample1(
    id BIGINT COMMENT 'unique id',
    data STRING
);

thanks.

**Comment by pvary** [comment]
@allenzhg: Could you please explain what are you trying to archive here?

The table should be either in HiveCatalog, or in HadoopCatalog. The exact commands are described in  https://iceberg.apache.org/hive/. If the documentation is not clear then please help us highlighting the issues, so we can fix them.

Thanks,
Peter

**Comment by openinx** [comment]
@allenzhg , You mean you want to writing data by flink streaming job into apache iceberg table, then read it by using Hive sql query ?

**Comment by silvermissile** [comment]
> @allenzhg , You mean you want to writing data by flink streaming job into apache iceberg table, then read it by using Hive sql query ?

yeah , I meet the same situation:

``` sql
CREATE EXTERNAL TABLE tmp.order_detail_sort 
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
LOCATION 'hdfs:///data/new-ib/tmp/order_detail_sort' TBLPROPERTIES ( 'iceberg.mr.catalog'='hadoop', 
'iceberg.mr.catalog.hadoop.warehouse.location'='hdfs:///data/new-ib') ;
```

**Comment by liudi1184** [comment]
I also encountered this problem. Have you solved it?

**Comment by ubyyj** [comment]
same here. I already have an iceberg table store in s3, registered in a hive metastore. Now I want to access the table from another hive, so I wanted to create table on top of existing data.

**Comment by pvary** [comment]
@ubyyj: A few questions for future development:
- Is the 2nd HiveServer2/TezAM able to access the 1st HMS?
- Do you plan to change the tables from both Hive installations?

Thanks, Peter
