### ISSUE TITLE
Build a utility to infer partitions at a given path

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2300]
We need to infer partitions to migrate path-based tables to Iceberg. While we can leverage some internal code in query engines like `InMemoryFileIndex` in Spark, it is better to build our own utility and use it in Spark, Flink, etc modules.

**Comment by aokolnychyi** [comment]
I'll give it a try.

FYI, @RussellSpitzer @pvary @openinx @rdblue

**Comment by pvary** [comment]
We are also thinking about migrating Hive tables to Iceberg tables by creating the appropriate metadata files. 

For us it  would be better to have an API what the engines can implement. In Hive it is possible to set the location on partition level, so we might be better off using HMS to get the partition information than parsing the path. So I think some API that will return Pair<Map<PARTITION_KEY, PARTITION_VALUE>, List<PATH>> might be better.

**Comment by aokolnychyi** [comment]
@pvary, I think this logic would only apply to path-based tables that are not tracked in a metastore. It is pretty popular at least in Spark. Whenever we have a metastore, we should talk to it for figure out the list of partitions and their locations.
