### ISSUE TITLE
Lock remains in HMS if HiveTableOperations gets killed (direct process shutdown - no signals) after lock is acquired 

### ISSUE THREAD

**Issue by pPanda-beta** [apache/iceberg#2301]
Although unlock is kept inside the finally block,

https://github.com/apache/iceberg/blob/a7901992c252bb28d10686ef24c1de788c90d663/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L220

### YET INFINITE LOCK MAY HAPPEN

Steps to reproduce : 

1. Start a new commit
2. Let icberg acquire the lock
3. Kill the job (signal 9 / 19 ) or disconnect network. (See below to know more about actual scenarios that happened)
4. Restart the job, a fresh new commit
5. Thats it, it will never be able to acquire a new lock on same resource again

### Lets make it more spicy

Consider it as the table create operation 🥰  , i.e. the actual "table" does not exist yet and before creation it will be killed.

Steps: 

1. Start creating the table
2. Let it acquire the lock on the non-existent table resource (HMS allows that)
3. Kill the job before the table is even created
4. Go cry yourself, cause you can not remove this lock manually using beeline / hive-cli since table doesn’t exist.

### What is this "Killed" thingy?

Well here in rapido we use GCP preemptible VMs for low cost. Now on such kind of infra, VM may be preempted at any point of time with very short notice period (15 sec). 
**Consider this as a network cable unplug**. We will never get a chance for InterruptedException and do clean up operations. 

### Why hive never faced this issue?
Well hive has expiry of its locks which works as a TTL. So system recovers eventually.

### Disaster Recoveries that we tried so far:
1. Ensure no jobs are running for that table (which may not have been created yet)
2. Use java api to connect to the hive metastore
3. Delete all locks for that table 

## Suggestions

1. Before acquiring locks, delete all locks that have not received any heartbeats since last 'x' minutes. (configurable)
2. After acquiring lock keep sending heart beats to HMS from a different daemon thread. This will ensure concurrent writes are protected
3. After operation finishes (success or fail), unlock and cancel the heartbeat thread.

**Comment by pvary** [comment]
Quick question: Hive removes the locks by the `AcidHouseKeeperService` which should run on the HMS side. Shouldn't that remove the "forever" from the problem statement?

The commits should be fairly quick so having a small timeout could be acceptable if HMS is only used as a HiveCatalog for Iceberg.

**Comment by marton-bod** [comment]
What's the value of `metastore.txn.timeout` on your HMS instance? As @pvary suggested, the `AcidHouseKeeperService` should clean up any locks without that haven't heartbeated within the timeout period (which is 300 seconds by default), preventing the forever-blockage. The housekeeper service itself will run every 60 seconds by default to purge these timed-out locks (configured by `metastore.acid.housekeeper.interval`). Maybe it's worth checking the HMS logs also to double check if the house keeper service is running regularly

**Comment by pPanda-beta** [comment]
@pvary @marton-bod 
Thanks for the suggestion. 
I've gone through their implementation.  

This does cleanup via: 
1. https://github.com/apache/hive/blob/8190d2be7b7165effa62bd21b7d60ef81fb0e4af/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/AcidHouseKeeperService.java#L60

2. https://github.com/apache/hive/blob/8190d2be7b7165effa62bd21b7d60ef81fb0e4af/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java#L4403

and 

3. https://github.com/apache/hive/blob/8190d2be7b7165effa62bd21b7d60ef81fb0e4af/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java#L3633-L3636


But I believe ALL OF THIS WONT WORK: 
**cause iceberg does not create transactions before creating the locks**.
https://github.com/apache/iceberg/blob/a7901992c252bb28d10686ef24c1de788c90d663/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L322-L329

This is more like a transaction less lock 😭 . So the lifecycle needs to be maintained via iceberg only.

Also  I would insist approaches which are heavily involving hive metastore features only, acid has mostly came from a hive feature. In modern days no one even installs hive. People mostly use spark/presto on top of HMS.

**Comment by pPanda-beta** [comment]
While dealing with independent locks we have to implement with the following columns only,
```
| lockid | database | table | partition | lock_state | blocked_by | lock_type | transaction_id | last_heartbeat | acquired_at | user | hostname | agent_info
```

**Comment by marton-bod** [comment]
Hi @pPanda-beta 
Transaction-less locks (where transaction id is 0) should be cleaned up the same way, once the timeout period expires. 
They are cleaned at this point: https://github.com/apache/hive/blob/8190d2be7b7165effa62bd21b7d60ef81fb0e4af/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java#L4400
even one step before the timed-out transactions are cleaned up.
See: https://github.com/apache/hive/blob/8190d2be7b7165effa62bd21b7d60ef81fb0e4af/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java#L4316

**Comment by pPanda-beta** [comment]
@marton-bod Thanks for pointing it out.
Theoretically this should work.

I've the value of `metastore.task.threads.remote` as `org.apache.hadoop.hive.metastore.txn.AcidHouseKeeperService,org.apache.hadoop.hive.metastore.txn.AcidOpenTxnsCounterService,org.apache.hadoop.hive.metastore.txn.AcidCompactionHistoryService,org.apache.hadoop.hive.metastore.txn.AcidWriteSetService,org.apache.hadoop.hive.metastore.MaterializationsRebuildLockCleanerTask`

And I dont see the logs "Failed to purge timedout locks due to".
Definitely something is broken on my HMS. 

Let me investigate that. Meanwhile we can remove the "forever" part.

**Comment by pPanda-beta** [comment]
@marton-bod Found it in an integration test powered by embed hive metastore. 
We need
```metastore.compactor.initiator.on=true```
At least on embedded HMS, this is `false` by default, which was not running those threads.

**Comment by marton-bod** [comment]
You're correct, it needs to be turned on for the house keeper to be launched.

**Comment by markope** [comment]
Is there any workaround for this? How could I manually fix my HMS?

**Comment by szehon-ho** [comment]
I found it useful to have a small script to unlock manually as well (in case the HMS thread is not configured).  In scala for instance assuming you get a hmsclient:

```
 def unlock(db: String, table: String): Unit = {
    val lockIds = getLockIds(db, table)
    lockIds.foreach{
      hmsClient.unlock(_)
    }
  }

  private def getLockIds(db: String, table: String): Set[Long] = {
    val showLockRequest = new ShowLocksRequest()
    showLockRequest.setDbname(db)
    showLockRequest.setTablename(table)
    showLockRequest.setIsExtended(true)
    val response = hmsClient.showLocks(showLockRequest)
    val locks = response.getLocks.asScala
    locks.map(_.getLockid).toSet
  }
```

**Comment by pvary** [comment]
@zhangminglei:
The code path protected by the lock does this:
```
acquireLock()
  loadHmsTable()
  setHmsTableParameters(newMetadataLocation, tbl, metadata.properties(), removedProps, hiveEngineEnabled, summary);
  persistTable(tbl, updateHiveTable)
unlock(lockId)
```

This is 2 HMS calls and some object data update. So this should not take very long. Also the TXN_TIMEOUT is configured to 300s by default.

All that said, you are right, that in extreme scenarios this could be a problem.

**Comment by dmgcodevil** [comment]
We faced similar issues:

1. We are using Flink and some processes attempt to modify a table concurrently, e.g.: ingestion process and data compaction process. If one of them fails then a lock can remain in `ACQUIRED` state. We clear all the logs from another process in `onInit` function.
2. This one is weird. We see a lot of errors in logs: `Base metadata location '%s' is not same as the current table metadata location '%s' for %s.%s`  [see](https://github.com/apache/iceberg/blob/6b8f7e0e31a81029b478e7757aba749f5ed27f42/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L295), which means table has been updated regardless of an acquired lock.

**Comment by pvary** [comment]
> We faced similar issues:
> 
> 1. We are using Flink and some processes attempt to modify a table concurrently, e.g.: ingestion process and data compaction process. If one of them fails then a lock can remain in `ACQUIRED` state. We clear all the logs from another process in `onInit` function.

This is problematic. You should not `clear` locks. You should only do this when you are sure that the other process is not writing/committing.

> 2. This one is weird. We see a lot of errors in logs: `Base metadata location '%s' is not same as the current table metadata location '%s' for %s.%s`  [see](https://github.com/apache/iceberg/blob/6b8f7e0e31a81029b478e7757aba749f5ed27f42/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L295), which means table has been updated regardless of an acquired lock.

This is exactly the case which could happen when the locks are removed during a commit and another process is trying to commit concurrenly.

The correct solution for the issue is to try to make sure that the lock is removed by the failing process

**Comment by dmgcodevil** [comment]
@pvary Flink won't run start any actual processing until every process finishes its initialization

**Comment by pvary** [comment]
Are you doing the following:
- Collect the new data files,
- Refresh the table metadata,
- Create a transaction and add the new files,
- Commit the changes?
