### ISSUE TITLE
Support Spark 3.1.1+

### ISSUE THREAD

**Issue by roderickyao** [apache/iceberg#2306]
Many changes happened in Spark 3.1.1+, Iceberg should start to plan for support. 

one example is, in Spark 3.1.1+, there is a change in `org.apache.spark.sql.catalyst.util.DateTimeUtils`, renaming `toMillis` method to `microsToMillis`. It prevents compiling against Spark 3.1.1

https://github.com/apache/iceberg/blob/master/spark3/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java#L83
https://github.com/apache/iceberg/blob/master/spark3/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java#L81
https://github.com/apache/iceberg/blob/master/spark3/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java#L80

**Comment by aokolnychyi** [comment]
I'll look into that soon.

**Comment by openinx** [comment]
Closed via https://github.com/apache/iceberg/pull/2512
