### ISSUE TITLE
Display Table Location in Spark SQL Properties

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#2309]
I realized today that while you are able to set the location of an Iceberg Table in Spark3, you cannot then view that location using the standard SQL commands.

Maybe we should considering populating this in table properties?

**Comment by RussellSpitzer** [comment]
I would also tag this as "good first ticket" but I do not know how to add labels

**Comment by aokolnychyi** [comment]
I feel it will be useful.

**Comment by aokolnychyi** [comment]
@flyrain, would you be interested in working on this?

**Comment by aokolnychyi** [comment]
We need to check if this will have any possible implications.

**Comment by aokolnychyi** [comment]
As far as I see, Spark passes the location as a table property. I think we can fake it in `SparkTable` like we fake the provider and the current snapshot id.

**Comment by aokolnychyi** [comment]
I think we can simply adapt `SparkTable$properties`.

**Comment by RussellSpitzer** [comment]
Totally agree, I was worried about it being mis used somewhere, but I think this is the right thing to do

**Comment by flyrain** [comment]
Looking at this.

**Comment by somayaj** [comment]
Can this be worked?

**Comment by flyrain** [comment]
Hi @somayaj , the PR #2330 has been merged into the master branch. Please have a try.

**Comment by aokolnychyi** [comment]
Closing this one as it has been fixed.
