### ISSUE TITLE
Type Equality Check

### ISSUE THREAD

**Issue by Sealina** [apache/iceberg#2347]
Hello,

I'm using iceberg 0.10.0 and Junit 5 for unit testing my app based on iceberg. I noticed something out of expectation as the following

```
...
@Test
public MyUnitTest() {
    assertEquals(
        new org.apache.iceberg.types.Types.IntegerType(),
        new org.apache.iceberg.types.Types.IntegerType()
    )
}
```
Output:
```
...
java.lang.AssertionError: expected: org.apache.iceberg.types.Types$IntegerType<int> but was: org.apache.iceberg.types.Types$IntegerType<int>
Expected :org.apache.iceberg.types.Types$IntegerType<int>
Actual   :org.apache.iceberg.types.Types$IntegerType<int>
...
```

It looks like the iceberg types are using the default Java Object way of equality check (pointer equality instead of value equality). I want to know if this is by design, or if there's other ways of checking equality for iceberg types.

Thank you

**Comment by openinx** [comment]
For `IntegerType`,  we'd better to use the `typeId` to accomplish the assertion like:

```java
    assertEquals(IntegerType.typeId(),  IntegerType.typeId());
```

**Comment by Sealina** [comment]
Thank you. On top of that, I also detected that this statement will fail:

```
assertEquals(
    Types.NestedField.required(1, "FieldName", new Types.IntegerType()),
    Types.NestedField.required(1, "FieldName", new Types.IntegerType())
)
```
because NestedField equality relies on equality of type object (not typeId): https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/types/Types.java#L520

Given that in a unit test, we may not have explicit control over what actual NestedField object we get when we do assertEquals, is there a better way we can validate the NestedField object we get is as expected?
