### ISSUE TITLE
trion very slow

### ISSUE THREAD

**Issue by ys610zz** [apache/iceberg#2351]
iceberg 0.11.0
trino 351

trino worker*3
16CORE 32G RAM

```
trino:odsx1> select count(*) from sample03;
 _col0 
-------
     9 
(1 row)

Query 20210318_152248_00001_5mzin, FINISHED, 3 nodes
Splits: 78 total, 78 done (100.00%)
4.11 [9 rows, 5.62KB] [2 rows/s, 1.37KB/s]
```

**Comment by openinx** [comment]
@yyanyy @jackye1995 Did you encounter the similar issue ?

**Comment by yyanyy** [comment]
I don't think I have, but we are mostly using our internal repository based on glue catalog and S3FileIO so our experiences wouldn't be the same. @jackye1995 did you encounter this before? 

I think this performance problem could be associated with other factors as well; how is the data/table look like, did you try the same query in sparksql or other engines? Is this a customized trino server, since I think trino 351 only has Iceberg 0.9?

**Comment by jackye1995** [comment]
I think this is too little information, there are many conditions of the cluster that can cause this in rare situations, could you at least rerun the query many times and see if it can be reproduced?

Also could you also describe information around the table itself, its partition scheme, size, etc.?

**Comment by rdblue** [comment]
It's also suspicious that there were 78 splits, but only 9 rows. I'd be interested to see the contents of the files metadata table for this.

**Comment by rlcyf** [comment]
```
spark.sql("CREATE TABLE tcsa.ods.sample3 (id bigint COMMENT 'unique id',data string) USING iceberg").show
```

```
hive.metastore.uri=thrift://hive:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml,/etc/hive/conf/hive-site.xml
iceberg.file-format=Parquet
```

**Comment by rlcyf** [comment]
> @yyanyy @jackye1995 Did you encounter the similar issue ?

halo 

sure_date range 2018-2021

```
val partitionSpec = PartitionSpec.builderFor(schema).day("sure_date").build()

java.lang.IllegalStateException: Already closed files for partition: sure_date_day=2020-09-03


val partitionSpec = PartitionSpec.builderFor(schema).month("sure_date").build()

java.lang.IllegalStateException: Already closed files for partition: sure_date_month=2020-09

```

**Comment by nautilus28** [comment]
We also experience poor performance on `count(*)` query

iceberg 0.11.0
trino 357

trino worker*3
32CORE 150GB RAM

```
trino> select count(1) from iceberg.raw.users;
 _col0
--------
 284903
(1 row)

Query 20210616_132555_00103_cyj8y, FINISHED, 3 nodes
Splits: 197,393 total, 197,393 done (100.00%)
6:27 [285K rows, 3.01GB] [735 rows/s, 7.96MB/s]
```

The table `iceberg.raw.user` is partitioned by `day(created_date)`

**Comment by ckdarby** [comment]
@nautilus28 Are you writing each user as a new snapshot?

**Comment by nautilus28** [comment]
@ckdarby no, we updated rows, so new snapshot will contain new rows and some existing rows.

**Comment by ckdarby** [comment]
@nautilus28 Do you do this for every user? My understanding is that you'd have the latest manifest but the latest manifest would point to all these individual manifest lists created for every user, no?

Asking also from the perspective of that would explain why it had nearly 200k splits.

**Comment by nautilus28** [comment]
@ckdarby you might be right. What information I could check to confirm your assumption?

**Comment by ckdarby** [comment]
@nautilus28 I think you're on Trino slack. I sent a message there and we can discuss more. If not, send over an email to ckdarby [at] gmail.com
