### ISSUE TITLE
TimeZone‘s ERROR on testInsertSupportedTypes

### ISSUE THREAD

**Issue by XuQianJin-Stars** [apache/iceberg#2356]
Hi everyone, I found the following errors when running UT:
![image](https://user-images.githubusercontent.com/10494131/111982702-406f3900-8b44-11eb-80dc-1b685579aab0.png)

**Comment by pvary** [comment]
@XuQianJin-Stars: Could you please share some details how did you run these tests?
For example: Which version, which timezone?

Thanks,
Peter
