### ISSUE TITLE
Flink : the construction method of the class DataIterator<T> can be optimized

### ISSUE THREAD

**Issue by wynjauu** [apache/iceberg#2369]
![image](https://user-images.githubusercontent.com/32868128/112283764-72f37000-8cc3-11eb-8fa0-c6cbaa3e6d97.png)

In the code block marked in the above figure, the implementation process of the code block for the initialization value of the **inputFiles** variable can be further optimized, streamlined, and reduce multiple loops.At the same time, the code will be more elegant.

I optimized the code as follows:
![image](https://user-images.githubusercontent.com/32868128/112285240-109b6f00-8cc5-11eb-8653-5055aeec0dc4.png)

**Comment by zhuxiaoshang** [comment]
Good Job!

**Comment by rdblue** [comment]
I'm closing this because I don't think the refactor is a good idea. More details are on the PR.
