### ISSUE TITLE
Rotation of encryption keys

### ISSUE THREAD

**Issue by ggershinsky** [apache/iceberg#2373]
The envelope encryption practice requires periodic (or on-demand) re-wrapping of DEKs (data encryption keys) with new versions of master keys. KMS (key management service) generates the new master keys and keeps their history. The re-wrapped DEKs need to be updated in Iceberg metadata. In a case of double envelope encryption, the KEKs (key encryption keys) are either re-wrapped with new master keys - or re-generated, wrapped with new master keys, and used to re-wrap the DEKs.
This mechanism will add a DDL clause to perform key rotation in Iceberg tables.

**Comment by yeshvant-bhavnasi** [comment]
We can use the `RewriteManifest` api on spark which will use the rotated kms master key.
