### ISSUE TITLE
Lack test on runtime jar

### ISSUE THREAD

**Issue by pan3793** [apache/iceberg#2382]
#2331 relocated the antlr4 classes in spark3 runtime module jar, but it cause several issues.

For example,
```
spark.sql("ALTER TABLE t2 WRITE ORDERED BY birthday ASC, height DESC NULL FIRST, weight ASC NULL LAST")
```
will cause
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.parser.UpperCaseCharStream.<init>(Lorg/apache/iceberg/shaded/org/antlr/v4/runtime/CodePointCharStream;)V
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parse(IcebergSparkSqlExtensionsParser.scala:124)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:105)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:605)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:605)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
	at com.hiscat.iceberg.spark.QuickStart$.main(QuickStart.scala:70)
	at com.hiscat.iceberg.spark.QuickStart.main(QuickStart.scala)
```

This is because spark `UpperCaseCharStream` refer the original antlr4 `CharStream`, but Iceberg invoke with the relocated one.

And I think the root cause here is we just build a runtime jar with relocation, but has none test on it.

Temporarily, I think we should revert #2331, because it broken the runtime jar. 
But we do need relocated antrl4, because Spark 3.1 use a different version Antlr4 which will conflict with iceberg.
cc @aokolnychyi

**Comment by pan3793** [comment]
cc @RussellSpitzer

**Comment by openinx** [comment]
We may need to provide several integration tests to validate that the spark-runtime jar & flink-runtime jar. Those tests will set up  a spark/flink mini cluster, and then load generated the spark/flink runtime jar, and finally run the sql script to do the validation.  In this way,  we could avoid the broken case when merging patches.

**Comment by RussellSpitzer** [comment]
For Spark we could just run in local mode, no need to setup a full cluster. The classpath issues would be the same.

**Comment by flyrain** [comment]
Hit the same issue. Hi @pan3793, are we going to revert #2331 anytime soon?

**Comment by flyrain** [comment]
Or use the unshaded version of `CharStreams` in the following code if we keep shading Antlr4
```
    val lexer = new IcebergSqlExtensionsLexer(new UpperCaseCharStream(CharStreams.fromString(command)))
```

**Comment by pan3793** [comment]
@flyrain Are you planning to write IT for runtime jar modules? I thought that some Committer or PMC will revert the bad commit. Should I raise a revert PR?

**Comment by flyrain** [comment]
I think we should copy class `UpperCaseCharStream` from Spark to Iceberg rather than reverting #2331. In that way, we can still shade antlr4 runtime, which isolates antlr4 dependency for Iceberg. Using the same version of antlr4 from Spark may cause problem in the future.

**Comment by pan3793** [comment]
>> I think we should copy class UpperCaseCharStream from Spark to Iceberg rather than reverting #2331.

It's not such a simple thing. `UpperCaseCharStream` is one of the issues I hit, and after a fast glance, I found another one. It like a Whac-a-Mole game.

So the safe solution I think is build a IT for the runtime jar modules rather than do manual test again and again.

**Comment by RussellSpitzer** [comment]
So is the issue here that because we extend Spark's Parser we end up shading Spark's internal references to Antlr Runtime code which causes our issues. 

If this is the case I think we should drop the runtime reference altogether, although I really dislike it when library code depends on a transitive of another library.

Another option is to mark the Antlr-runtime version as "Strictly" so that we at least fail quickly if Spark changes the version from underneath us.

**Comment by pan3793** [comment]
> If this is the case I think we should drop the runtime reference altogether, although I really dislike it when library code depends on a transitive of another library.

agree with that. but we need IT(or something else, maybe gradle has such plugins) to enforce it rather than manual check.

> Another option is to mark the Antlr-runtime version as "Strictly" so that we at least fail quickly if Spark changes the version from underneath us.

Spark 3.1.1 upgraded antlr4

**Comment by flyrain** [comment]
Yeah, by looking at more code, reverting it is more practical. I like the fail-fast approach, but checking the antlr-runtime version is not feasible since we want a unified iceberg runtime version for all Spark 3.x, and Spark3.1.1 has changed antlr4 as @pan3793 mentioned.

Yes, integration test or something similar is necessary. This issue should be considered as a blocker since every customized iceberg sql will fail, but obviously it didn't get much attention.

**Comment by aokolnychyi** [comment]
I took a look as well. The only place we interact with antlr4 from Spark is in `IcebergSparkSqlExtensionsParser#parse`.

Our `IcebergSqlExtensionsPostProcessor` is actually a copy of `PostProcessor` in Spark. We thought that is sufficient but it looks like not if we are shading. If I am correct and that's the only place we interact with antlr4 from Spark, the number of classes we should copy should be limited. I guess `UpperCaseCharStream`, `ParseErrorListener`, `ParseException`.

**Comment by aokolnychyi** [comment]
If it is a matter of copying a few classes to make shading work, I think we should do that. If not, let's revert the shading PR.

**Comment by pan3793** [comment]
Agreed with @aokolnychyi analysis, we should redefine `UpperCaseCharStream`, `ParseErrorListener`, `ParseException` in Iceberg. And if we done that, the shading should work, it's better to do it after #2428 get in.
