### ISSUE TITLE
Spark：spark need support timestamp time zone fileds

### ISSUE THREAD

**Issue by wynjauu** [apache/iceberg#2388]
When using spark to query iceberg, because it is the binlog data synchronized by flink, there are some fields with timestamp without time zone, so the parsing error, and then use the presto iceberg connector to solve the problem. Need support at iceberg's source code. I think data types without time zone are often seen in daily production.

![image](https://user-images.githubusercontent.com/32868128/112724713-9e8a8a80-8f4f-11eb-82f5-4010841daf97.png)

**Comment by RussellSpitzer** [comment]
This is covered by #2244 which is currently in review

**Comment by RussellSpitzer** [comment]
Pr at #2282

**Comment by wynjauu** [comment]
Thanks, I closed this and will continue to follow https://github.com/apache/iceberg/pull/2282
