### ISSUE TITLE
Upgrade Parquet version to 1.12.0

### ISSUE THREAD

**Issue by shangxinli** [apache/iceberg#2390]
Parquet 1.12.0 is about to release(https://issues.apache.org/jira/browse/PARQUET-1898) in a few days. Once it is available, we can upgrade the version to 1.12.0, which has great features like column encryption for Iceberg to integrate.

**Comment by RussellSpitzer** [comment]
We are already testing with builds of this, so the bump should be safe

**Comment by liujinhui1994** [comment]
Would this be compatible with Spark 2.x. guess not? I think this needs Spark 3.2?
https://github.com/apache/spark/blob/branch-3.2/pom.xml
@RussellSpitzer  @shangxinli

**Comment by rdblue** [comment]
This was released in 0.12.0.
