### ISSUE TITLE
Please tidy up Incubator resources

### ISSUE THREAD

**Issue by sebbASF** [apache/iceberg#2413]
The following Incubator resources should now be removed please:

https://dist.apache.org/repos/dist/dev/incubator/iceberg/
https://dist.apache.org/repos/dist/release/incubator/iceberg/

**Comment by aokolnychyi** [comment]
cc @rdblue @danielcweeks @omalley

**Comment by rdblue** [comment]
I'll take a look at this.

**Comment by aokolnychyi** [comment]
Thanks, @rdblue!

**Comment by rdblue** [comment]
Removed. Thanks for letting us know about this, @sebbASF.

**Comment by sebbASF** [comment]
Thanks for dealing with this so promptly.
