### ISSUE TITLE
Why createParquetAsIceberg is true in IcebergSource?

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2423]
I am wondering why `parquet-enabled` is true when we set up a default Iceberg catalog in `IcebergSource`. That's a different default value than what we usually use. Any particular reason?

**Comment by aokolnychyi** [comment]
cc @rdblue @rymurr

**Comment by rymurr** [comment]
Hey @aokolnychyi, from my reading that is an oversight/copy-paste error. I personally think it should be removed.

It appears that the parameter goes unused by default correct? The `IcebergSource` sets up the default_iceberg catalog as a `SparkCatalog` with that parameter set and `SparkCatalog` doesn't use it. It could have strange effects if the default catalog was switched to a session catalog though....

**Comment by aokolnychyi** [comment]
I don't think it causes any issues right now but I think we should remove it to avoid any surprises in the future.
