### ISSUE TITLE
Consider deprecating updating table state through ALTER TABLE ... SET TBLPROPERTIES

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2424]
I'd consider deprecating and then removing support for changing the table location, current snapshot id, etc through ALTER TABLE ... SET TBLPROPERTIES. We have procedures/commands for most operations now. If missing, let's add more.

**Comment by szehon-ho** [comment]
Is there any procedure to change table location (pretty useful)?  Could not find it so far in spark-procedure.md doc: https://github.com/apache/iceberg/blob/90225d6c9413016d611e2ce5eff37db1bc1b4fc5/site/docs/spark-procedures.md

**Comment by szehon-ho** [comment]
Looked through the latest code and didn't find it unless I missed it.  If nobody is working on it, I can take a look to add 'update_location' procedure (and maybe update_properties) to familiar myself with this code?

**Comment by szehon-ho** [comment]
Talked offline, i guess its more to do with snapshot, already supported by procedure.  location can be changed via ALTER TABLE SET LOCATION
