### ISSUE TITLE
update build.gradle to support gradle 7.0

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#2429]
`compile` `runtime` `testCompile` and `testRuntime` are deprecated since gradle 4.1.0.  These will be finally removed in gradle 7.0.  We need to replace them with `implementation`, `runtimeOnly`, `testImplemenetion`, and `testRuntimeOnly`.

@aokolnychyi @RussellSpitzer. Gradle start to support Apple M1 from 7.0. Do you guys use Mac Pro m1? :)

**Comment by RussellSpitzer** [comment]
I can neither confirm nor deny the existence of Apple computers.

**Comment by chenjunjiedada** [comment]
I got one and are running `gradle builld` now.

**Comment by RussellSpitzer** [comment]
I think it's a great idea to update, I find compile and runtime a bit confusing about really describing what's going on

**Comment by chenjunjiedada** [comment]
thanks https://github.com/apache/iceberg/pull/2826

**Comment by RWClem** [comment]
> `testImplemenetion`

For future reference, the correct spelling is `testImplementation`
