### ISSUE TITLE
Move site-related things to a separate repo

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2446]
We should move site-related things to a separate repo to avoid indexing all those files in our IDEs as discussed in #2426.

cc @openinx @rdblue @RussellSpitzer @rymurr

**Comment by rymurr** [comment]
I am happy to take a look at this.

I guess the approach would be:

- [ ]  get ASF to make a new repo for us, say `iceberg-site` , copying from https://github.com/apache/arrow-site
- [ ] move the `site` subdirectory there
- [ ] build and publish to `asf-site` branch
- [ ]  get ASF to point to new repo for main site?
- [ ] celebrate

**Comment by openinx** [comment]
@rymurr , that's the exactly approach to address this issue !

**Comment by aokolnychyi** [comment]
Sounds like a solid plan!

**Comment by rymurr** [comment]
@aokolnychyi could you request the new repo `iceberg-site`? Only PMC can request new repositories.

**Comment by aokolnychyi** [comment]
Sorry, missed the last messages. Any tips on how to do that, @rymurr?

cc @rdblue

**Comment by rymurr** [comment]
I believe you can request on gitbox
