### ISSUE TITLE
[Spark] Dropping Partition Field Breaks Describe Table

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#2453]
```java
sql("ALTER TABLE local.db.alter ADD PARTITION FIELD bucket(16, id)");
sql("ALTER TABLE local.db.alter ADD PARTITION FIELD truncate(data, 4)");
sql("ALTER TABLE local.db.alter ADD PARTITION FIELD years(ts)");
sql("ALTER TABLE local.db.alter ADD PARTITION FIELD bucket(16, category) AS shard");
sql("ALTER TABLE local.db.alter DROP PARTITION FIELD bucket(16, id)");
sql("ALTER TABLE local.db.alter DROP PARTITION FIELD truncate(data, 4)");
sql("ALTER TABLE local.db.alter DROP PARTITION FIELD years(ts)");
sql("ALTER TABLE local.db.alter DROP PARTITION FIELD shard");
```
    Builds the following partition Specs
    
![image](https://user-images.githubusercontent.com/413025/114247079-de8f3b80-9959-11eb-933f-36da18b679ee.png)

  The void transforms are not compatible with our describe code and throws an UnsupportedOperationException
  
Because we describe using this transformer https://github.com/apache/iceberg/blob/ab6a5e9ebf2f580fb7be21fb00f1f543726f43eb/api/src/main/java/org/apache/iceberg/transforms/PartitionSpecVisitor.java#L85-L87

**Comment by aokolnychyi** [comment]
Dropping a partition field just makes it use `void` transforms?

**Comment by RussellSpitzer** [comment]
@jun-he Could you please take a look? Just trying to figure out what the right fix is here.

**Comment by jun-he** [comment]
@RussellSpitzer  I will take a look. BTW, is this v1 or v2 table?

**Comment by RussellSpitzer** [comment]
I believe so, I didn't do anything special I actually just was going through our Doc's as I was writing general integration tests, so it's just a bunch of Spark SQL run in sequence.

**Comment by jun-he** [comment]
👌  the void partition field is used as a placeholder to reserve the partition field id for the dropped partition so that future spec evolutions won't reuse it. A quick fix is to skip void transform at https://github.com/apache/iceberg/blob/ab6a5e9ebf2f580fb7be21fb00f1f543726f43eb/api/src/main/java/org/apache/iceberg/transforms/PartitionSpecVisitor.java#L120
