### ISSUE TITLE
Fix ArrowReader to return Arrow vectors with logical Iceberg data type instead of physical

### ISSUE THREAD

**Issue by mayursrivastava** [apache/iceberg#2484]
For reference, the ArrowReader was added in https://github.com/apache/iceberg/pull/2286.
Columns with constant values are physically encoded as a dictionary. During reads, the Arrow vector type is int32 instead of the type as per the Iceberg table schema. Fix the ArrowReader and related code to return the Arrow vector corresponding to the logical data type.
After fixing it, remove ignore annotation from ArrowReaderTest#testReadAllWithConstantRecords().

**Comment by nastra** [comment]
addressed this in https://github.com/apache/iceberg/pull/3024. @mayursrivastava would you like to review the PR?

**Comment by mayursrivastava** [comment]
@nastra I left 2 comments in the pr. Thanks for adding the feature.
