### ISSUE TITLE
Add support and test cases in ArrowReader for UUIDType, FixedType and DecimalType data types

### ISSUE THREAD

**Issue by mayursrivastava** [apache/iceberg#2486]
For reference, the ArrowReader was added in https://github.com/apache/iceberg/pull/2286.
The test cases should be added in ArrowReaderTest.

**Comment by nastra** [comment]
Decimal support was added as part of https://github.com/apache/iceberg/commit/97a99c3cf4f3293fe3536402f015c5b65906e0ba
