### ISSUE TITLE
Table SortOrder not being respected in Spark write

### ISSUE THREAD

**Issue by huadongliu** [apache/iceberg#2490]
The table is created with `SortOrder.builderFor(schema).withOrderId(1).asc("userId", NULLS_LAST).build()` and populated with `df.write().format("iceberg").mode("append").save(tableLocation)`. The table has below schema and partition spec. I am trying to improve `userId` join and query by sorting them in parquet partitions.

```
Schema schema = new Schema(
        optional(1, "userId", Types.StringType.get()),
        optional(2, "eventTime", Types.TimestampType.withZone()),
        optional(3, "count", Types.IntegerType.get())
);

PartitionSpec spec = PartitionSpec.builderFor(schema)
        .day("eventTime")
        .truncate("userId", 2)
        .build();
```

userId is not sorted in parquet data files. Is Spark iceberg write supposed to respect SortOrder? `df.sortWithinPartitions("userId").write().format("iceberg").mode("append").save(tableLocation)` works around the issue.

**Comment by yyanyy** [comment]
I think currently sort order support is only implemented on API level, but no engine integration is completed yet; I think the situation doesn't change much from the email thread here, in case you need more information: https://lists.apache.org/thread.html/r4d41a78b722af230738e597203d42e524f5f09738fcf041ba78f613a%40%3Cdev.iceberg.apache.org%3E

**Comment by shay1bz** [comment]
Any update on this? 
Would a PR for Spark rewrite action be any good or are you looking for a more holistic solution?

**Comment by RussellSpitzer** [comment]
> Any update on this? Would a PR for Spark rewrite action be any good or are you looking for a more holistic solution?

The Spark rewrite action already uses SortOrder. The SparkWrite code needed the distribution and ordering changes in Spark 3.2, I think the current snapshot already has this implemented. So it should be done

**Comment by shay1bz** [comment]
Thanks @RussellSpitzer . I'm using 0.12.1 so I did not see this addition. Do you have any idea when is the next release? I prefer to use release package rather than custom build.
