### ISSUE TITLE
Reduce errorprone warnings for Iceberg build

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#2545]
I recently noticed an increasing number of warnings from errorprone when building Iceberg. Currently Iceberg does not fail the build for these warnings, but I think errorprone provides a lot of valuable insights and we should not just let the warning list grow. The long list of warnings also make it very hard to find the actual errors when debugging locally. We should either fix those warnings, or suppress the warnings if we think they are false alarms. Adding suppression also makes it easier to identify issues when reviewing PRs.

I will start to fix those warnings (probably module by module), if anyone is also interested feel free to join the effort.

I think we should turn on build failure for errorprone in the future once we are in a good state, but we can discuss that later when we reach there.

**Comment by marton-bod** [comment]
+1 - I've had similar thoughts as well just the other day, would be happy to reduce/eliminate these warnings on the mr/hive side.
