### ISSUE TITLE
Consider suppressing INFO level io.quarkus.http.access-log logs in tests

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#2557]
When running `./gradlew clean build` and the associated test suites, there are a lot of INFO level logs coming from `io.quarkus.http.access-log`.

When running `build`, there's a pretty large number of logs like this that come out that we should potentially suppress.

Here's a sample. They all seem to be coming from Task :iceberg-nessie:test. 

```
23:33:42.481 [executor-thread-1] INFO  io.quarkus.http.access-log - 127.0.0.1 - - 05/May/2021:23:33:42 -0700 "GET /api/v1/contents/a.t3?ref=6c80eedd3b189148729ec13f3473453c4803819b217c0beec1f47850560d3b6e HTTP/1.1" 404 149
23:33:42.514 [executor-thread-1] INFO  io.quarkus.http.access-log - 127.0.0.1 - - 05/May/2021:23:33:42 -0700 "POST /api/v1/trees/branch/test-namespace/commit?expectedHash=6c80eedd3b189148729ec13f3473453c4803819b217c0beec1f47850560d3b6e HTTP/1.1" 204 -
23:33:42.518 [executor-thread-1] INFO  io.quarkus.http.access-log - 127.0.0.1 - - 05/May/2021:23:33:42 -0700 "GET /api/v1/trees/tree/test-namespace HTTP/1.1" 200 131
23:33:42.522 [executor-thread-1] INFO  io.quarkus.http.access-log - 127.0.0.1 - - 05/May/2021:23:33:42 -0700 "GET /api/v1/contents/a.t3?ref=8fdf0fce4f17f9d8f56498e71535c951549116512760b319bbda184ef2f5c9a3 HTTP/1.1" 200 206
```

If nobody has any objections, I think we should suppress this as it's quite a lot when running the test suites, but arguably we do keep the Flink INFO logs so it might just be something I'm less used to.

The INFO Flink ones all seem to be coming from `org.apache.flink.runtime.io.disk.FileChannelManagerImpl`, so possibly we can suppress that too.

**Comment by kbendick** [comment]
For reference, the `iceberg-spark3` tests only have two spark logs.

```
> Task :iceberg-spark3:test
[Thread-7] INFO org.apache.spark.util.ShutdownHookManager - Shutdown hook called
[Thread-7] INFO org.apache.spark.util.ShutdownHookManager - Deleting directory /private/var/folders/p7/pjs_74qn64x7x4w5201ctck00000gn/T/spark-6badeb97-ea2a-432a-b53b-31616481347a
```

```
> Task :iceberg-spark3-runtime:integrationTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.common.base.internal.Finalizer (file:/Users/kbendickson/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/16.0.1/5fa98cd1a63c99a44dd8d3b77e4762b066a5d0c5/guava-16.0.1.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of com.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Thread-7] INFO org.apache.spark.util.ShutdownHookManager - Shutdown hook called
[Thread-7] INFO org.apache.spark.util.ShutdownHookManager - Deleting directory /private/var/folders/p7/pjs_74qn64x7x4w5201ctck00000gn/T/spark-6bcb11d7-a0d8-4737-9dec-b0e8983a4d99
```

**Comment by rymurr** [comment]
Cc @snazy

**Comment by kbendick** [comment]
For the record, these logs are not a big deal if you guys find them helpful. I don't typically work over there, so I don't know.

If we did want to do clean up, I'd be happy to open another issue for Flink. Or if this is not something that's relatively simple to update in Gradle for test suites, then it's likely not worth the effort as mostly what I look for in test logs is just failure related issues.

**Comment by snazy** [comment]
I think, it's fine to "hide" these logs by default. Will try to write something that hides the HTTP-access-logs by default.

**Comment by snazy** [comment]
As discussed on #2588, the iceberg-nessie tests fail against Nessie 0.6.1, because Nessie's Quarkus-server is already built for Java 11 (Quarkus 2 will drop support for Java 8 anyways). We've opted to change the Gradle + Maven plugins to pull the uber-jar  and launch that one in a separate Java 11 VM. It has the nice "side effect", that both environment-variables and system-properties can be set very explicitly, so setting the environment variable to reduce the amount of log from the Quarkus HTTP access log is quite easy then.

**Comment by snazy** [comment]
Since #2834 the Nessie-tests are no longer ran via Quarkus and there's no more "log spam". Think, this one can be closed.
