### ISSUE TITLE
Web 404 Not Found, Many page jump links cannot be opened

### ISSUE THREAD

**Issue by wulei0302** [apache/iceberg#2561]
On the iceberg official website, I found that the jump path cannot be opened in many pages.
for example, 
button '_FlinkSource#Builder_' on page [flink](https://iceberg.apache.org/flink/#writing-with-sql).
And what makes me wonder is that there is no flink html folder in [master](https://github.com/apache/iceberg/tree/master/site/docs/javadoc/master)

**Comment by openinx** [comment]
I think that's because we've changed the page to [here](https://iceberg.apache.org/javadoc/0.11.1/),  would you like to prepare a PR for those broken link ?

**Comment by wulei0302** [comment]
> I think that's because we've changed the page to [here](https://iceberg.apache.org/javadoc/0.11.1/), would you like to prepare a PR for those broken link ?



> I think that's because we've changed the page to [here](https://iceberg.apache.org/javadoc/0.11.1/), would you like to prepare a PR for those broken link ?

I'm very happy to do it, but I want to confirm the repair plan with you:
1. Do I need to point the ‘javadoc/html’ links of all modules to the latest version, which is 0.11.1? Such as hive, flink, spark
2. If it points to the latest version, then we need to modify the version every time we release a new version later.
tks~

**Comment by openinx** [comment]
Okay,  I think I misunderstood the javadoc issue,  the iceberg master branch haven't updated the javadoc since 2 years ago, so we could not see the correct  `FlinkSource#Builder`.

**Comment by openinx** [comment]
Linked to this [issue](https://github.com/apache/iceberg/issues/2446).
