### ISSUE TITLE
Spark on iceberg table is slower than spark on hive parquet table

### ISSUE THREAD

**Issue by smallx** [apache/iceberg#2562]
Through test and comparison, we find that spark on iceberg table is slower than spark on hive parquet table, and its performance is reduced by about half. After optimizing some parameters, iceberg's performance is improved, but it is still slower than simple parquet. The optimized parameters are as follows.

```sql
ALTER TABLE iceberg_table SET TBLPROPERTIES ('write.parquet.compression-codec'='snappy');
ALTER TABLE iceberg_table SET TBLPROPERTIES ('read.parquet.vectorization.enabled'='true');
ALTER TABLE iceberg_table SET TBLPROPERTIES ('read.parquet.vectorization.batch-size'='100000');
ALTER TABLE iceberg_table SET TBLPROPERTIES ('commit.manifest.min-count-to-merge'='2');
```

It seems that iceberg's vectorization reading performance is not as good as spark's. There are too many `for` loops and function calls in vectorization reading code. See the following code.

https://github.com/apache/iceberg/blob/a2103b7131bb039c531a2c9f70c7c8b9fe9715ac/arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedDictionaryEncodedParquetValuesReader.java#L42-L70

Perhaps my guess is wrong, please help to analyze the reasons. Thanks very much.

Version info:
- spark 3.0.2
- iceberg 0.11.1

**Comment by RussellSpitzer** [comment]
Do you have a reproducible benchmark? That would be helpful but I try not to guess on root causes of performance differences without benchmarks and instrumented code.

**Comment by norrishuang** [comment]
I found too. I test iceberg on spark 3.3.1 used TPC-DS 3TB. The performance is slower than spark on parquet table 3-4 times.

**Comment by wenna** [comment]
I tested too，on spark 3.3.2 and  iceberg 1.3.0，TPC-DS 1GB， I only have 3 Virtual server,16core   32GB
the result is almost the same,Originally I thought it could be faster.
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



Query | 3average(secs)-spark | 3average(secs)-iceberg use spark_catalog
-- | -- | --
query01 | 15.50 | 14.84
query02 | 19.54 | 20.89
query03 | 14.24 | 16.17
query04 | 30.96 | 33.10
query05 | 27.12 | 23.76
query06 | 18.60 | 17.95
query07 | 18.71 | 17.49
query08 | 15.52 | 16.34
query09 | 15.11 | 20.47
query10 | 19.19 | 26.83
query11 | 23.09 | 22.01
query12 | 14.25 | 13.80
query13 | 16.92 | 17.04
query14 | 38.21 | 34.12
query14 | 13.66 | 14.41
query15 | 13.37 | 14.06
query16 | 16.20 | 16.67
query17 | 18.39 | 19.14
query18 | 18.71 | 19.32
query19 | 13.94 | 15.32
query20 | 12.73 | 13.88
query21 | 18.01 | 16.99
query22 | 17.62 | 18.24
query23 | 32.33 | 28.79
query23 | 14.93 | 14.35
query24 | 15.66 | 16.47
query24 | 3.08 | 3.06
query25 | 18.06 | 19.79
query26 | 15.41 | 14.73
query27 | 14.76 | 16.10
query28 | 21.90 | 22.76
query29 | 19.14 | 19.39
query30 | 15.78 | 16.24
query31 | 21.03 | 22.99
query32 | 12.77 | 14.09
query33 | 17.53 | 18.70
query34 | 16.23 | 19.05
query35 | 20.65 | 23.02
query36 | 16.30 | 16.32
query37 | 16.50 | 15.41
query38 | 21.88 | 18.41
query39 | 19.61 | 17.16
query39 | 3.98 | 3.73
query40 | 16.10 | 15.23
query41 | 11.61 | 13.23
query42 | 11.80 | 13.82
query43 | 13.97 | 14.61
query44 | 14.31 | 17.41
query45 | 14.52 | 14.31
query46 | 19.29 | 16.66
query47 | 19.78 | 22.67
query48 | 14.39 | 15.68
query49 | 22.83 | 20.48
query50 | 15.48 | 16.75
query51 | 21.60 | 24.16
query52 | 13.17 | 14.54
query53 | 14.35 | 16.80
query54 | 19.46 | 20.59
query55 | 13.45 | 14.12
query56 | 21.80 | 19.26
query57 | 17.43 | 20.75
query58 | 17.32 | 18.45
query59 | 16.52 | 17.42
query60 | 25.25 | 20.09
query61 | 15.06 | 18.02
query62 | 13.54 | 15.13
query63 | 14.67 | 15.67
query64 | 30.27 | 31.99
query65 | 15.56 | 18.44
query66 | 18.79 | 17.92
query67 | 20.24 | 23.34
query68 | 17.01 | 17.29
query69 | 19.40 | 24.13
query70 | 15.45 | 17.48
query71 | 15.29 | 17.93
query72 | 183.08 | 36.23
query73 | 14.17 | 15.71
query74 | 18.40 | 19.99
query75 | 26.01 | 26.43
query76 | 15.27 | 16.02
query77 | 21.20 | 20.94
query78 | 19.89 | 21.97
query79 | 15.31 | 15.94
query80 | 19.20 | 21.57
query81 | 14.30 | 15.88
query82 | 18.14 | 20.43
query83 | 16.87 | 16.93
query84 | 12.49 | 15.43
query85 | 21.19 | 19.05
query86 | 14.25 | 14.72
query87 | 19.59 | 18.83
query88 | 18.14 | 21.19
query89 | 15.08 | 16.19
query90 | 12.18 | 13.62
query91 | 13.37 | 16.01
query92 | 12.74 | 14.11
query93 | 14.25 | 15.83
query94 | 15.55 | 16.15
query95 | 20.51 | 21.51
query96 | 11.36 | 13.23
query97 | 17.29 | 17.27
query98 | 14.96 | 16.14
query99 | 14.11 | 16.14



</body>

</html>

**Comment by Rajdipc** [comment]
Lately we have also faced the same issue where we tried with TPCH data over 100GB, 3TB and 10TB. Is it still being worked upon? Any resolution?

**Comment by smallx** [comment]
closing this outdated pr.
