### ISSUE TITLE
Fix hadoop data source options in Spark

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#259]
Hadoop configs passed as data source options in Spark are not propagated correctly as `DataSourceOptions` convert all configs to lower case. So, properties such as `fs.defaultFS` are not set correctly.

**Comment by aokolnychyi** [comment]
@mccheah @rdblue do we actually need `hadoop.` data source options? Won't be enough to pick Hadoop configs from table properties?

**Comment by rdblue** [comment]
There is a fix for this in Spark 3.0 that allows you to get the original options map. Let's just keep this as a known issue until we can use that.

**Comment by aokolnychyi** [comment]
No longer applies.
