### ISSUE TITLE
Does Spark sql support time-travel?

### ISSUE THREAD

**Issue by coolderli** [apache/iceberg#2618]
I tried to set `snapshot-id` in TableProperties when I use spark SQL to use time-travel, but it didn't work.
I have tried that it can be used in [DataFrames Api](http://iceberg.apache.org/spark-queries/#spark-24-with-sql), but SQL is easier. 
I'd like to use SQL hint syntax to set the options just like [Flink ](https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/dev/table/sql/queries/hints/#dynamic-table-options) does.

**Comment by coolderli** [comment]
I wonder if we can add a dynamic table option to spark SQL.
eg: [Coalesce Hints for SQL Queries](https://spark.apache.org/docs/latest/sql-performance-tuning.html#coalesce-hints-for-sql-queries)

**Comment by rdblue** [comment]
Fixed by #5156
