### ISSUE TITLE
Does spark integrated iceberg support concurrent insert overwrite

### ISSUE THREAD

**Issue by lizu18xz** [apache/iceberg#2633]
Does spark integrated iceberg support concurrent insert overwrite？

**Comment by zz22394** [comment]
Short answer:
Yes.

Ref:
# How does Iceberg handle multiple concurrent writes?
https://www.dremio.com/apache-iceberg-faq/#h-how-does-iceberg-handle-multiple-concurrent-writes
```
Iceberg uses "optimistic concurrency" to provide transactional guarantees during multiple concurrent writes.
```

**Comment by zz22394** [comment]
https://iceberg.apache.org/docs/latest/spark-writes/
**MERGE INTO** is recommended instead of **INSERT OVERWRITE** because Iceberg can replace only the affected data files
