### ISSUE TITLE
Shoud Flink Iceberg table source implement the LookupTableSource to support temporal table join for flink streaming task?

### ISSUE THREAD

**Issue by sfiend** [apache/iceberg#2645]
In many scenarios, flink streaming source table will consume kafka topics and join with a dimension table like hive, due to flink hive table source will cache all hive partitions and then look up the match rows from cache for now, the performance of hive is not good  enough if the hive table is large. Iceberg table has metadata and support primary key now, and also can push down the filters when scan data files, so I think maybe it's prefect if the iceberg table can used to be a dimension table.

**Comment by wulei0302** [comment]
This is a great idea, but whether it can be realized is a matter to consider ...

**Comment by openinx** [comment]
@sfiend ,  It's good to implement the LookupTableSource for flink iceberg connector, so  that we could maintain the dimension table into apache iceberg table also.   The primary key in iceberg was designed to improve the query performance and maintain the deduplicate semantics but it was not indexed,  so in theory iceberg table is still not suitable to maintain too large dimension table. But I still like to see that the iceberg connector support `LookupTableSource`.

**Comment by xinbinhuang** [comment]
@openinx want to take a stab at this. Can you assign to me?

**Comment by yeezychao** [comment]
@sfiend I come across the same scenarios.Next I will develop this features on flink iceberg connector.

**Comment by YesOrNo828** [comment]
Hello @yeezychao @xinbinhuang, do you have any progress about this ticket ?

**Comment by ymZhao1001** [comment]
hello, @openinx @yeezychao @xinbinhuang ,are you still working on this ? If someone else is not already working on this, I am happy to pick this up , also happy to collaborate if it's already being worked upon.

**Comment by damjad** [comment]
It seems like we are seeing Iceberg everywhere.  I think we should have it. It is an extremely useful feature that expands the use case horizon of Iceberg.
