### ISSUE TITLE
Flink: Can not see hive udf in Flink when use iceberg hive catalog

### ISSUE THREAD

**Issue by liubo1022126** [apache/iceberg#2653]
Flink: **flink-1.11.1-bin-scala_2.12**
Jar: ./bin/sql-client.sh embedded -j /app/flink-1.11.1/lib/**iceberg-flink-runtime-0.11.0.jar** -j /app/flink-1.11.1/**flink-sql-connector-hive-2.3.6_2.11-1.11.0.jar** shell
Hive: **2.3.8**
JDK: **1.8.0_202**

As [Flink doc](https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/hive/hive_functions.html#hive-user-defined-functions) say, Hive’s UDF and GenericUDF are automatically translated into Flink’s ScalarFunction.

So what I do is:

1. Create hive udf in hive like.
>create function udf1 as 'com.xxx.xxxx' using jar 'hdfs://icebergHadoop/user/deploy/udf/xxx.jar';

2. Put the udf xxx.jar in flink lib path.

3. Open flink sql-client.
>sql-client.sh embedded

4. Create hive catalog in flink sql-client and use it.
> CREATE CATALOG myhive WITH (
>      'type' = 'hive',
>      'default-database' = 'default',
>      'hive-conf-dir' = '/app/hive/conf'
> );
>
> use catalog myhive;

5. show functions and use udf1 like .
>show functions;
>
>select udf1('a', 'b');

It works Ok.

But when I use iceberg hive catalog As [iceberg hive catalog Doc](https://iceberg.apache.org/flink/#hive-catalog), I can not use hive udf.

As what I do is like:

1.Open flink sql-client with iceberg.
> export HADOOP_CLASSPATH=`$HADOOP_HOME/bin/hadoop classpath`
>
> ./bin/sql-client.sh embedded \
>     -j <flink-runtime-directory>/iceberg-flink-runtime-xxx.jar \
>     -j <hive-bundlded-jar-directory>/flink-sql-connector-hive-2.3.6_2.11-1.11.0.jar \
>     shell

2.Create iceberg hive catalog in flink sql-client and use it.
> CREATE CATALOG hive_catalog WITH (
>   'type'='iceberg',
>   'catalog-type'='hive',
>   'uri'='thrift://localhost:9083',
>   'clients'='5',
>   'property-version'='1',
>   'warehouse'='hdfs://nn:8020/warehouse/path'
> );

3.show functions and use udf1 like **(What is not works Ok, I can not see the hive udf which is registered in hive metastore)**
>show functions;

So how can I use hive udf on iceberg table in Flink, Thx

Besides this, When use iceberg hive catalog in flink sql-client, Only can see iceberg tables, can not see hive tables which table_type is not iceberg. 

Although I can create iceberg catalog and hive catalog at the same time, and use them in the way of select * from catalog.db.table. But I am not sure if there any problems with using hive udf which are in hive metastore. Although currently not available under iceberg in Flink to use hive udf as what I said before.

**Comment by StefanXiepj** [comment]
@liubo1022126 I'll try to support this feature.

**Comment by liubo1022126** [comment]
thanks for @StefanXiepj ,is there any PR for this? We urgently need this function, or is there any other way to achieve this requirement ?

**Comment by StefanXiepj** [comment]
Someone think it’s like this：Iceberg catalog for hive just support loaded tables from a hive metastore, in other words, iceberg is a table format, so it only focus on the meta data about tables.

But I think we should support this feature, which is the standard defined by the Catalog interface.

@rymurr cc

**Comment by luoyuxia** [comment]
I don't think it should be supported in iceberg , it's too specific and many other catalog implementation will never have udf.
For you case, I'll still advice you to use the hive catalog created in Flink SQL-client.
 Or you can just create a hive catalog in flink way as a dummy catalog, and all table are still stored in the catalog created in iceberg way,
but use the hive catalog as the default catalog, then the udf is available.
