### ISSUE TITLE
Improve hidden partition support for Hive CREATE TABLE

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#2681]
Currently user can only create table with identity transforms through the standard Hive CREATE TABLE syntax, or specify the json text of the partition spec as table parameter using key `iceberg.mr.table.partition.spec`. This is very hard to use for users writing SQL manually using in an interactive console or notebook.

We would like to contribute a more user friendly way to specify the values, so a create table statement with hidden partition looks like:

```sql
CREATE TABLE database_a.table_a (
  id bigint, 
  category string,
  ts timestamp,
  data string
) TBLPROPERTIES (
  'iceberg.catalog'='hadoop',
  'iceberg.partitioning'='bucket(id, 16);category;days(ts)'
) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
```

Would like to know if this is something valuable to be added, and any additional suggestions for this. I will put up the PR once we have some initial agreements.

@pvary @marton-bod

**Comment by pvary** [comment]
Hi @jackye1995,

We definitely think that having the ability to create partitioned Iceberg tables with all of the supported transformation is important. @lcspinter is working on the feature in hive codebase: https://issues.apache.org/jira/browse/HIVE-25179

The main goal there is to support the same syntax that is supported by Spark.

**Comment by jackye1995** [comment]
@pvary thanks for the quick reply!

I saw the JIRA, the major concern I have is that organizations might not be able to switch to a new syntax given the complexity of Hive upgrade, so this proposal is really to allow people to use hidden partition without the need to upgrade Hive.

**Comment by pvary** [comment]
I agree with you about the complexity of the switch, especially as Hive 4.0 is not released.

Parsing a string could be a way to enable the the users to archive something, but I would definitely try to avoid it as a long term solution.
