### ISSUE TITLE
Hadoop tables: how to view history, and snapshots.

### ISSUE THREAD

**Issue by aimenglin** [apache/iceberg#2682]
Hi All,

When I created Iceberg table by Hadoop tables, how can I view the history, snapshots?
If I created by Hive Catalog, it's very easy to use spark.read.format("iceberg").load("db.table.history").show(truncate = false).
What should be the cl in Hadoop tables?

Thanks in advance.

**Comment by rymurr** [comment]
Hi @aimenglin I believe you would use `spark.read.format("iceberg").load("/path/to/table#history").show(truncate=false)`

**Comment by aimenglin** [comment]
@rymurr Thanks so much!
