### ISSUE TITLE
Could Hive use Time Travel if the overlay iceberg table is created as a Hadoop Table?

### ISSUE THREAD

**Issue by aimenglin** [apache/iceberg#2687]
Hi Iceberg experts,

I am wondering about if we could enjoy the gourmet of the Iceberg when we are using Hive (shell) when the underlying Iceberg Table was created as a *Hadoop Table*. 

According to the documentation ([page](https://iceberg.apache.org/hive/#hive-read-support)) we could create a overlay table directly in Hive by the support from StorageHandler like:
```
CREATE EXTERNAL TABLE table_a 
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 
LOCATION 'hdfs://some_bucket/some_path/table_a';
```
But I am not sure after the creation, how to use (if it is available?) the cool features of Iceberg like Snapshot Read or doing some simple checking of its metadata tables like Snapshot, Manifests etc.

Thanks for your attention in advance!

Best

**Comment by aimenglin** [comment]
@marton-bod Thank you for the guide. I'll look into it.

**Comment by marton-bod** [comment]
I'm closing this issue. Thanks for reaching out. Feel free to post questions though, if any.
