### ISSUE TITLE
lost table columns while making iceberg table accessible via hive by adding table property

### ISSUE THREAD

**Issue by jhsenjaliya** [apache/iceberg#2725]
```
val catalog = new HiveCatalog(spark.sparkContext.hadoopConfiguration);

// Create table name "example" under Hive database default
val name = TableIdentifier.of("jay_db","example");

// Sample data
val df1=Seq((1,"A"),(2,"A"),(3,"B"),(4,"C")).toDF("id","level");
val df1_schema = SparkSchemaUtil.convert(df1.schema);
// Specify partition strategy based on column "level"
val partition_spec=PartitionSpec.builderFor(df1_schema).identity("level").build;

// Creating the table
val table=catalog.createTable(name,df1_schema,partition_spec);

```

At this point the table created looks like this if you "show create table jay_db.example", 
```
CREATE EXTERNAL TABLE `jay_db.example`(
  `id` int,
  `level` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.FileInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.mapred.FileOutputFormat'
LOCATION
  'gs://<GCP_BUCKET>/jay_db/example'
TBLPROPERTIES (
  'metadata_location'='gs://<GCP_BUCKET>/jay_db/example/metadata/00000-24290321-a6d0-4bc6-9468-b6c94894143a.metadata.json',
  'table_type'='ICEBERG',
  'transient_lastDdlTime'='1624439550')
```

this is not queriable though , if you try "select * from jay_db.example" then it throws the error "java.io.IOException: Cannot create an instance of InputFormat class org.apache.hadoop.mapred.FileInputFormat as specified in mapredWork!" 

To make it readable via Hive, as per the iceberg docs, we have to add "engine.hive.enabled" = "true" property to the table. 
what I noticed is adding this property chnages serde and storageHandler as well, when u execute following to add the property.
```
table.updateProperties().set("engine.hive.enabled", "true").commit()
```

**here is the bug:**
when u add the above table property, it removes all the rows, so the table looks like this.
```
CREATE EXTERNAL TABLE `jay_db.example`(
)
ROW FORMAT SERDE
  'org.apache.iceberg.mr.hive.HiveIcebergSerDe'
STORED BY
  'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'

LOCATION
  'gs://<GCP_BUCKET>/jay_db/example'
TBLPROPERTIES (
  'engine.hive.enabled'='true',
  'metadata_location'='gs://<GCP_BUCKET>/jay_db/example/metadata/00001-88aef830-4c29-4291-b5c3-dd1784bd8162.metadata.json',
  'previous_metadata_location'='gs://<GCP_BUCKET>/jay_db/example/metadata/00000-24290321-a6d0-4bc6-9468-b6c94894143a.metadata.json',
  'table_type'='ICEBERG',
  'transient_lastDdlTime'='1624439550')
```

This iceberg lib is compiled from master with patch for spark 3.1.1 support ( #2460 )

update:
I found that columns are not shown with `show create table <table_name>` but i can see it with `describe extended <table_name>`

**Comment by pvary** [comment]
Maybe this is the `table.updateProperties()`.

Could you please try to set this property when the table is created?

Thanks,
Peter

**Comment by jhsenjaliya** [comment]
Yes, I actually tried that as well, as following
```
val table_props = new java.util.HashMap[String,String] { put("engine.hive.enabled","true") }
val table=catalog.createTable(name, df1_schema, partition_spec, null, table_props );
```

I also noticed that the on Spark 3.1.1 the table created has serde is LazySimpleSerDe whereas on spark 3.0.2 the serde is HiveIcebergSerDe so it looks like the problem with #2460 , the way the compatibility for spark 3.1.1 is added, which is not in merged yet.
