### ISSUE TITLE
merge error is back on iceberg master + spark 3.1.1 : MERGE INTO TABLE is not supported temporarily.

### ISSUE THREAD

**Issue by jhsenjaliya** [apache/iceberg#2737]
the table in context is created using iceberg APIs and it looks good (has all required setup)
- insert query works
- insert overwrite also works
- merge into throws below error
```
java.lang.UnsupportedOperationException: MERGE INTO TABLE is not supported temporarily.
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:718)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
```

spark-sql is created with following configs
```
spark-sql --conf spark.sql.warehouse.dir=gs://mybucket/     
--conf spark.eventLog.enabled=false     
--jars /home/jsenjaliya/iceberg-spark89de6d.jar,/home/jsenjaliya/iceberg-hive-runtime-0.11.1.jar     
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions     
--conf spark.sql.catalog.hive_prod=org.apache.iceberg.spark.SparkCatalog     
--conf spark.sql.catalog.hive_prod.type=hive     
--conf spark.sql.catalog.hadoop_prod=org.apache.iceberg.spark.SparkCatalog     
--conf spark.sql.catalog.hadoop_prod.type=hadoop     
--conf spark.sql.catalog.hadoop_prod.warehouse=gs://mybucket/
```

**Comment by RussellSpitzer** [comment]
Are you sure your target table is in hive_prod or hadoop_prod catalogs?

**Comment by jhsenjaliya** [comment]
u r right, it was probably not created using hive_prod catalog even though the structure looks exactly same,  recreating using hive_prod catalog worked. 
I did had to manually add `engine.hive.enabled` property to table property to make it readable via hive. Thanks for checking on this.

**Comment by vsingh99** [comment]
Thanks for your help.

As suggested added following line and MERGE INTO works as expected.

.config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")

**Comment by weichampion** [comment]
@jhsenjaliya hello, i'm a question :
spark-sql --packages org.apache.iceberg:iceberg-spark3-runtime:0.13.1  --conf spark.sql.catalog.hadoop_prod=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.hadoop_prod.type=hadoop --conf spark.sql.catalog.hadoop_prod.warehouse=hdfs://10.195.5.62:9001/_iceberg/warehouse

I just run into spark-sql shell, and use merge into command : 
MERGE INTO hadoop_prod.default.target t USING (SELECT * FROM hadoop_prod.default.source) u ON t.id = u.id 
WHEN MATCHED THEN UPDATE SET t.name = u.name 
WHEN NOT MATCHED THEN INSERT *;

then return a message like this : 

java.lang.UnsupportedOperationException: MERGE INTO TABLE is not supported temporarily.
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:796)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)


Can you help me ?

**Comment by RussellSpitzer** [comment]
@weichampion 

Looks like you are missing 
```
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions   
```

Please see the docs, https://iceberg.apache.org/docs/latest/getting-started/
