### ISSUE TITLE
Support hive metastore client retries

### ISSUE THREAD

**Issue by thomaschow** [apache/iceberg#2741]
Currently, the hive metastore client used in the iceberg HiveClientPool and HiveCatalog is [`HiveMetastoreClient`](https://github.com/apache/iceberg/blob/c3ac4c6ca74a0013b4705d5bd5d17fade8e6f499/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveClientPool.java#L32). This client implementation doesn't support retry on failure as stated in: https://github.com/apache/hive/blob/6246c47b95f6cab7ea24d1deadfd13b2b43cf876/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java#L99-L100. The recommendation is to use [`RetryingMetaStoreClient`](https://github.com/apache/hive/blob/6246c47b95f6cab7ea24d1deadfd13b2b43cf876/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java#L63) where we can configure retry delays and timeouts. 

We'd like for iceberg to be able to either support a pluggable HMS client implementation, or switch to just using the `RetryingMetaStoreClient` entirely.

**Comment by jhsenjaliya** [comment]
this is fairly easy but due to the usage of `DynConstructors` in `HiveClientPool`, the constructor of `RetryingMetaStoreClient` can not be spinned up. 

we may not need the `DynConstructors` here. if it sounds ok, I can create PR.

**Comment by thomaschow** [comment]
@jhsenjaliya  do you have a PR available? I also have cycles to author if needed.

**Comment by jhsenjaliya** [comment]
yes, can u pls help review it: #2804 , Thanks!
