### ISSUE TITLE
JdbcCatalog can not work on mysql and postgresql

### ISSUE THREAD

**Issue by haormj** [apache/iceberg#2744]
hi all:
thanks for your job on https://github.com/apache/iceberg/pull/1870

1. environment
    - flink 1.12.4
    - iceberg 98da9749edee574b8ed673d69e0ef80ce7ae0272
2. use JdbcCatalog by mysql 5.6
    - engine: innodb
    - error: `Specified key was too long; max key length is 767 bytes`
    - cause by:   `PRIMARY KEY (catalog_name, table_namespace, table_name)`
    - how should we fix it?
3. use JdbcCatalog by postgresql 11.5
    - create iceberg_tables first time works ok
    - second time ` ERROR: relation "iceberg_tables" already exists`
    - I change this [line](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L30) ICEBERG_TABLES to iceberg_tables, it works ok
    -  if this method looks ok, I can commit pull request

**Comment by ismailsimsek** [comment]
Thank you @haormj for testing the new feature,

tested your suggestion with Mysql, Postgresql, MsSQL databases and its working, please feel free to open PR

for 2. Error  it seems like we should use reasonable VARCHAR size current size is too big,
following column sizes are working with MySQL 5.6 and other databases and i believe they should be sufficient 

```
      "CREATE TABLE " + CATALOG_TABLE_NAME +
          "(" +
          CATALOG_NAME + " VARCHAR(255) NOT NULL," +
          TABLE_NAMESPACE + " VARCHAR(255) NOT NULL," +
          TABLE_NAME + " VARCHAR(255) NOT NULL," +
          METADATA_LOCATION + " VARCHAR(5500)," +
          PREVIOUS_METADATA_LOCATION + " VARCHAR(5500)," +
          "PRIMARY KEY (" + CATALOG_NAME + ", " + TABLE_NAMESPACE + ", " + TABLE_NAME + ")" +
          ")";
```

**Comment by haormj** [comment]
@ismailsimsek thanks for you reply :-)

1. about MySQL: I will create table by myself with your suggestion, and choose a reasonable length in our scene
2. about table name: I have corrected it and pr [here](https://github.com/apache/iceberg/pull/2778)

**Comment by openinx** [comment]
Closed via https://github.com/apache/iceberg/pull/2778
