### ISSUE TITLE
Drop table doesn't clean up metadata and data files

### ISSUE THREAD

**Issue by canhduong28** [apache/iceberg#2784]
Hello,

We have noticed that `DROP TABLE` doesn't clean up metadata and data files stored in GCS.

Is this by design choice or a bug?

Iceberg 0.11.1, Spark 3.0.1
Data files are in Parquet format.

**Comment by openinx** [comment]
What's catalog you are using in your GCS ?  Sounds like it's a specific behavior from the GCS catalog..

**Comment by nautilus28** [comment]
Yes, I am using GCS catalog
