### ISSUE TITLE
Dead link found on the home page / time travel

### ISSUE THREAD

**Issue by be-rock** [apache/iceberg#2786]
Hi,

Thanks for the great project. Found a dead link here:

https://iceberg.apache.org/spark#time-travel

```
Not Found
The requested URL was not found on this server.
```

Thanks again!

**Comment by rdblue** [comment]
Where was this linked from?

**Comment by be-rock** [comment]
The home page, labeled "Time travel".

**Comment by be-rock** [comment]
And multiple here labeled "Spark SQL": https://iceberg.apache.org/evolution/#partition-evolution

**Comment by RussellSpitzer** [comment]
Found 4 occurances

aws.md
evolution.md
spark-streaming.md

Will post a fix asap
