### ISSUE TITLE
 Semi-structured data and unstructured data support.

### ISSUE THREAD

**Issue by deadwind4** [apache/iceberg#2798]
Will iceberg support semi-structured data and unstructured data in the future.
For example, CSV, logs, XML, JSON, documents, PDFs etc.

**Comment by kbendick** [comment]
By support, do you mean storing the data in these formats?

I can't speak for the direction of the project as a whole, but I would think that would not be the case. Iceberg is really designed to take advantage of tabular data and the storage formats that benefit from having schema to be able to reduce the amount of data that is read for a query. I'm not sure that would be something that could be accomplished with json data storage.

Could you describe your specific use case case (or one of them) in more detail? There might be a solution or pattern in practice that you could benefit from.

If you're looking for a simple one of column, you can  always have a string column for a json blob as an example.

**Comment by LLsion** [comment]
> 
I am currently using iceberg+hdfs, I want to store an image or video in hdfs and manage it via iceberg (via java API, sprak or flink), is this possible?
I have read the development documentation and found no relevant API to store the image, when I deposit the image it does become .parquet format, but I don't know how to read this image out, can you answer this question for me?
