### ISSUE TITLE
Add partition spec evolution to Table API

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#281]
Tables currently support schema evolution using [`updateSchema()`](http://iceberg.apache.org/javadoc/master/index.html?org/apache/iceberg/UpdateSchema.html):

```java
table.updateSchema()
    .addColumn("a", Types.IntegerType.get())
    .commit()
```

Iceberg should support a similar API for evolving a partition spec, which is currently a manual operation.

**Comment by timmylicheng** [comment]
I'm still new to this and trying to pick up some fixes to get deeper into the code base. Could you say more about the manual operation here? Is it happening in PartitionData?

**Comment by rdblue** [comment]
@timmylicheng, #280 should be done first so that metadata tables can handle schema evolution.

Updating a schema works fine, I'm referencing it so that we have a guide for building partition spec evolution. I think the two APIs should be similar.

Updating a partition spec is currently a manual operation because there is no API for making the change. You can build a replacement spec and add it to a table, though. Unfortunately, you might need to do that by editing JSON, depending on what methods we expose to update partition specs in `TableMetadata`.

**Comment by massdosage** [comment]
Is this done now? Just curious as it mentions closed and merged PRs.

**Comment by rdblue** [comment]
Yes. I'll close it. Thanks!
