### ISSUE TITLE
Can we use table property MAX_SNAPSHOT_AGE_MS for spark Actions snapshot retention default value

### ISSUE THREAD

**Issue by jinchengchenghh** [apache/iceberg#2821]
I find this PR set the table property as default snapshots retention, but only used for RemoveSnapshots

`public static final String MAX_SNAPSHOT_AGE_MS = "history.expire.max-snapshot-age-ms";`
`public static final long MAX_SNAPSHOT_AGE_MS_DEFAULT = 5 * 24 * 60 * 60 * 1000; // 5 days`

Maybe this default value can also used for Actions.forTable(table).expireSnapshots().expireOlderThan(end)

while
`end = System.currentTimeMillis() - maxSnapshotAgeMs`

@aokolnychyi 
#1868

**Comment by RussellSpitzer** [comment]
Expire snapshots action uses remove snapshots under the hood to actually do the snapshot expiration so I think this should work right now

**Comment by jinchengchenghh** [comment]
Thanks you for your reply. I misunderstand, it has worked now
