### ISSUE TITLE
org.apache.flink.sql.parser.impl.ParseException: Encountered 

### ISSUE THREAD

**Issue by yunfeng79** [apache/iceberg#2822]
flink-1.11.1
create table hive_catalog.default.sample ( id BIGINT COMMENT 'unique id',data STRING);
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.sql.parser.impl.ParseException: Encountered ". default" at line 1, column 26.
Was expecting one of:
    <EOF> 
    "LIKE" ...
    "WITH" ...
    "COMMENT" ...
    "PARTITIONED" ...
    "(" ...
    "." <IDENTIFIER> ...
    "." <QUOTED_IDENTIFIER> ...
    "." <BACK_QUOTED_IDENTIFIER> ...
    "." <BRACKET_QUOTED_IDENTIFIER> ...
    "." <UNICODE_QUOTED_IDENTIFIER> ...
    "." "*" ...

**Comment by lsyldliu** [comment]
Try `hive_catalog`.`default`.`sample`?

**Comment by yunfeng79** [comment]
thank you.
