### ISSUE TITLE
JdbcCatalog createNamespace is not supported

### ISSUE THREAD

**Issue by haormj** [apache/iceberg#2825]
when use JdbcCatalog in flink, and use flink sql client

```
[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Cannot create namespace default: createNamespace is not supported
```

https://github.com/apache/iceberg/blob/b3fb81a19e9632608b2bd4cdede4bbfcbd26bc8e/core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java#L254-L257

**Comment by haormj** [comment]
@ismailsimsek @openinx how should we fix it?

**Comment by kbendick** [comment]
If you look at the original PR for the JDBC catalog, there might be a reference in there as to why createNamespace is not explicitly supported.

I think that namespaces are implicit, and the namespace is created by simply adding a table with a / in it (if you look at the code for dropNamespace or listNamespace, you’ll see what I mean).

**Comment by kbendick** [comment]
What query are you running that’s generating this exception?

Looking at your stack trace, it says the namespace is “default”. Usually, I thought that didn’t need to be created (but I might be thinking of Spark).

**Comment by haormj** [comment]
@kbendick thinks for your reply

I use flink SQL client to query data from jdbc catalog

**Comment by cassiemudan** [comment]
I have the same problem with @haormj. Are we able to create jdbc catalog using flink sql client? It automatically create the namespace and throws the not supported exception.

**Comment by nssalian** [comment]
@cassiemudan that's being worked on #3275

**Comment by luxl6** [comment]
[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Cannot create namespace icebergcat_flink: createNamespace is not supported
我也遇到了这个错
CREATE CATALOG my_catalog_2 WITH (
> 'type'='iceberg',
> 'catalog-impl'='org.apache.iceberg.jdbc.JdbcCatalog',
> 'default-database'='icebergcat_flink',
> 'uri'='jdbc:postgresql://ip:5432/icebergcat_flink',
> 'user'='postgres',
> 'password'='postgres',
> 'warehouse'='s3://iceberg/',
> 's3.endpoint'='http://ip:9000',
> 's3.access.key'='minioadmin',
> 's3.secret.key'='minioadmin',
> 'io-impl'='org.apache.iceberg.aws.s3.S3FileIO',
> 'property-version'='1'
> );

**Comment by jbonofre** [comment]
@nastra I don't have permission to close this issue. Can you please close it ? Thanks !

**Comment by ajantha-bhat** [comment]
fixed via https://github.com/apache/iceberg/pull/3275
