### ISSUE TITLE
Possible NPE in DataFiles.Builder.copy(DataFile toCopy)

### ISSUE THREAD

**Issue by smg260** [apache/iceberg#2885]
When calling `org.apache.iceberg.DataFiles.Builder.copy(DataFile toCopy)`, the builder instance variable `int sortOrderId` is assigned to the incoming `DataFile` argument's `Integer sortOrderId`.  An unboxing NPE can occur when the incoming `sortOrderId` is `null`

- [Builder](https://github.com/apache/iceberg/blob/c57e07cb1e7110959e3ab353d48f16468a4d05da/core/src/main/java/org/apache/iceberg/DataFiles.java#L179)
- [ContentFile](https://github.com/apache/iceberg/blob/c57e07cb1e7110959e3ab353d48f16468a4d05da/api/src/main/java/org/apache/iceberg/ContentFile.java#L132)

**Comment by openinx** [comment]
You're correct, there's a PR for this before : https://github.com/apache/iceberg/pull/2852

**Comment by openinx** [comment]
Closed via https://github.com/apache/iceberg/pull/2852
