### ISSUE TITLE
AWS DMS integration?

### ISSUE THREAD

**Issue by tooptoop4** [apache/iceberg#2889]
Hudi (https://cwiki.apache.org/confluence/display/HUDI/2020/01/20/Change+Capture+Using+AWS+Database+Migration+Service+and+Hudi) and Delta Lake (https://databricks.com/blog/2019/07/15/migrating-transactional-data-to-a-delta-lake-using-aws-dms.html) both show steps to integrate CDC changes from AWS DMS. Does Iceberg have similar documentation?

**Comment by openinx** [comment]
I think this merged [PR](https://github.com/apache/iceberg/pull/2410) can help you experience the flink + iceberg CDC integration work.
