### ISSUE TITLE
How to change hours transform time zone?

### ISSUE THREAD

**Issue by coolderli** [apache/iceberg#2947]
I am in Beijing China (UTC+8). When  I create an iceberg table with hours(date) partition, I got the wrong directory name.

Here is what I did.

My table is partition by hours(date_time):
```
spark-sql> desc test_timestamp;
id	string	
date_time	timestamp	
		
# Partitioning		
Part 0	hours(date_time)
```

And then I insert a record using spark:
```
spark-sql> insert into test_timestamp values (1, CURRENT_TIMESTAMP());
Time taken: 106.969 seconds
spark-sql>  select * from test_timestamp;
1	2021-08-06 12:54:55.786
```

And I found the partition name is wrong：
![image](https://user-images.githubusercontent.com/38486782/128462724-0829a687-9c2a-4986-b1da-e36fc325d958.png)

I think the correct name is `date_hour=2021-08-06-12`.
Is there anything wrong with my operation？ When I use Flink, I came to the same problem.

**Comment by RussellSpitzer** [comment]
There was a discussion of using non utc boundaries, but I don't think it was ever made possible and we just decided that utc was fine.

**Comment by coolderli** [comment]
Thanks. I'll check it out.
