### ISSUE TITLE
Use SerializableTable instead of TableLoader in Flink

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2978]
I am wondering whether we can in certain cases switch to using `SerializableTable` instead of `TableLoader` in Flink. In particular, I am talking about `FlinkInputFormat`. My primary motivation is the ability to pass just a `Table` object instead of a number of individual parts. For example, I want to pass `Table` to `PartitionUtil#constantsMap` as the partition type depends on all specs. A side benefit of using `SerializableTable` is that we won't have to load and close the catalog.

**Comment by aokolnychyi** [comment]
Thoughts, @openinx @stevenzwu?

**Comment by aokolnychyi** [comment]
There may be still valid places to use `TableLoader`, though. I think the initial loading in `FlinkSource` can be done through it.

**Comment by stevenzwu** [comment]
I agree that we can switch to `SerializableTable` in some cases (like `FlinkInputFormat` you mentioned). Since `FlinkSource` already loaded the table, it can just pass in a `SerializableTable` copy. We can also simplify the params for `FlinkInputFormat` constructor

**Comment by aokolnychyi** [comment]
Okay, I'll fire a PR to discuss it in detail.
