### ISSUE TITLE
Support AWS Glue Catalog in Python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#2996]
Related slack thread: https://apache-iceberg.slack.com/archives/C029EE6HQ5D/p1629304790017500

**Comment by jackye1995** [comment]
As discussed in the slack channel, I think we can put this as a part of the 0.1 release milestone. I can start to work on this as soon as the Tables API in python is consolidated.

**Comment by jun-he** [comment]
Thanks @jackye1995 
Updated the issue to include it in the milestone.

**Comment by Fokko** [comment]
I know that @JonasJ-ap is also looking into this 👍🏻 

I created a first draft in https://github.com/apache/iceberg/pull/5569

**Comment by Fokko** [comment]
This is in https://github.com/apache/iceberg/pull/6034
