### ISSUE TITLE
Getting the following error when using from spark thrift server

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [apache/iceberg#3010]
I am starting thrift server using the following command.
```
$SPARK_HOME/sbin/start-thriftserver.sh --master spark://*****:7077 --conf "spark.cores.max=24" --conf "spark.executor.cores=4" --conf "spark.driver.cores=15" --executor-memory=1G --driver-memory=50G --conf spark.sql.adaptive.coalescePartitions.enabled=true --conf spark.sql.adaptive.skewJoin.enabled=true --conf spark.sql.cbo.enabled=true --conf spark.sql.adaptive.enabled=true --conf spark.rpc.io.serverThreads=64 --conf "spark.shuffle.file.buffer=1MB" --packages org.apache.iceberg:iceberg-spark3-runtime:0.12.0 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.local.type=hadoop --conf spark.sql.catalog.local.warehouse=$PWD/warehouse
```

Getting the following error when trying to connect to it.
```
Error: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000/: Failed to open new session: org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.iceberg.spark.SparkSessionCatalog (state=08S01,code=0)
```

**Comment by RussellSpitzer** [comment]
The underlying error incase you didn't see is 
```Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.iceberg.spark.SparkSessionCatalog```

Which means that the iceberg-spark3-runtime jar wasn't actually put on the classpath. I would check the startup log for the thrift server and make sure that the process was able to correctly connect to maven and get the required binaries. I double checked the binaries this morning and they are ok, so my guess is there is an issue with connectivity of this particular thirft-server process. 

Other possibilities include some unmatched double quote or something in the cli command which would cause it to combine some of the conf options although my brief look  didn't spot anything. The fact that it picks up spark_catalog correctly does mean it at least read that property correctly and independently.

**Comment by chajath** [comment]
I'm seeing the same issue, especially when running spark's thrift server. If I instead use a custom catalog name, it works fine.

**Comment by fizaashraf37** [comment]
were you able to fix this issue. how did you solve this? I am facing the same issue.

**Comment by tkent** [comment]
:wave: Recording one solution to this error. I ran into this using an Azure databricks cluster and the underlying error was what @RussellSpitzer noted. However, the runtime JAR for iceberg spark _was_ on the classpath of the spark instance.

What resolved the issue was adding a second JAR to the classpath - the `azure-bundle` release for Iceberg. I haven't chased down why that fixes it, but things are working fine now.

**Comment by dvaldivia** [comment]
I suspect the problem is that `start-thriftserver.sh` doesn't load the dynamic dependencies via `--packages` the way `spark-shell` does

**Comment by Aigul9** [comment]
i added --packages as mentioned [here](https://medium.com/itversity/iceberg-catalogs-a-guide-for-data-engineers-a6190c7bf381), and it worked
