### ISSUE TITLE
PartitionSpec isUnpartitioned returns true for tables which previously had Partitions but no longer do

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#3014]
Because SpecV1 creates "void" transforms when removing partition transforms, a v1 table whose partitions are removed will always return an unpartitioned spec.

https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/PartitionSpec.java#L97-L99

This method should always return true if all of the transforms are void as well.

**Comment by xinbinhuang** [comment]
@RussellSpitzer can you assign this to me, and timebox it till Thursday?  Wanna take a look at iceberg code, but don't want to block it if I get occupied by other things

**Comment by RussellSpitzer** [comment]
Done! Let me know if anything is u nclear

**Comment by RussellSpitzer** [comment]
@xinbinhuang How are things going?

**Comment by xinbinhuang** [comment]
Hi @RussellSpitzer  , I had some time to look into the code last week but haven't gotten the time to draft up a PR yet. Planing to do it in the next two days. But I'm aware it has passed quite a few days from last Thursday, so if it'll be too late to get into the release cycle or it blocks other works. Please go ahead to fix it :)

Thanks!
Bin
