### ISSUE TITLE
Currently, a DynamicTableSource with SupportsFilterPushDown ability is not supported.

### ISSUE THREAD

**Issue by zhaoyuxiaoxiao** [apache/iceberg#3019]
flink1.11.3 + iceberg0.12.0 An error
Flink SQL> select * from table_d;
[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Currently, a DynamicTableSource with SupportsFilterPushDown ability is not supported.
Need help!

**Comment by openinx** [comment]
The iceberg 0.12.0 was built on top of flink 1.12.0 version, which is implementing the flink1.12's  `DynamicTableSource`.  While the `DynamicTabelSource` was not introduced in flink 1.11.3.  So if you want to use the iceberg 0.12.0 , then you'd better to upgrade your flink cluster to flink 1.12.

Plan to close this issue now,  feel free to reopen this if have more question, thanks !
