### ISSUE TITLE
Help needed in migrating parquet file to iceberg table.

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [apache/iceberg#3042]
Can someone point me to some documentation ? Please. Thanks.

**Comment by zhaoyuxiaoxiao** [comment]
I have a problem. Spark migrated form V1, and I changed it into V2 form with ALTER. But table V2 requires a primary key field. How do I add this field@RussellSpitzer

**Comment by openinx** [comment]
@zhaoyuxiaoxiao , What's the specific stacktrace ? And which apache iceberg version (git commit) in your environment ? How did you upgrade your v1 table to v2  (according to the description in [PR](https://github.com/apache/iceberg/pull/2887) ) ?

It will be helpful to locate the solution for you if you can provide the above information.

**Comment by zhaoyuxiaoxiao** [comment]
@openinx  ，I am using the master compiled version, I am upgrading the table form through sparkSQL，SQL：“alter table hive_prod.test.hive2iceberg_table set TBLPROPERTIES ('engine.hive.enabled' = 'true' , 'format-version' = '2', 'write.upsert.enable' = 'true') ;”
I'm not sure there's a problem with that。
After the upgrade I used flinkSQL test to insert data and he reported an error. 
[ERROR] Could not execute SQL statement. Reason:
java.lang.IllegalStateException: Equality field columns shouldn't be empty when configuring to use UPSERT data stream.
Error prompt: It seems that I did not specify a primary key。
Please take a look at it for me. Thank you

**Comment by zhaoyuxiaoxiao** [comment]
@openinx ，Sorry, I found the cause of FLINKSQL error, but I have a question is, how to update V1 to V2 table add primary key field, implement CDC function
