### ISSUE TITLE
`AppendFile` can add duplicated data files

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg#3064]
The following Java APIs add a duplicated data file object(newDataFile1)
```
   Transaction t = table.newTransaction();
    t.newAppend().appendFile(newDataFile1).appendFile(newDataFile1).commit();
```
The manifest file will have two identical data file items after the commit. Also, any row in the data file will be doubled while reading back from the table.

Looks like a bug. Can we fix it in core? Two classes are involved `FastAppend` and `MergeAppend`.

**Comment by RussellSpitzer** [comment]
@szehon-ho This is similar to the import data files fix that you added, I'm wondering if we should do the same thing here, or just always outlaw this ...

**Comment by flyrain** [comment]
It is not a big deal if the compute engine like Spark has done extra work to remove the duplication. However, the APIs are considered public Java APIs, https://iceberg.apache.org/api/#transactions. It would be nice to let user be aware of that.

**Comment by szehon-ho** [comment]
Yea it makes sense to just add the documentation , if it adds little value to do a whole spark job.  If we really want to do something, we can do a quick in memory comparison on the Merge/FastAppend?
