### ISSUE TITLE
iceberg-data, Row level Java API do not have any examples or descriptions in site Java API tab.

### ISSUE THREAD

**Issue by GrigorievNick** [apache/iceberg#3082]

**Comment by openinx** [comment]
Hi @GrigorievNick ,  Yes, we did not add any document for the row-level delete feature yet.  It's a necessary thing in our plan but still don't do.  What's your case that wanna to use the iceberg row-level feature ?

**Comment by GrigorievNick** [comment]
I use it, for query iceberg table from spark xecutors. My iceberg table
organized as sequential index. So I can do join by sorted keys with out
shuffle data.
For simplicity we can name this operation,  enrichment by range of
monitonical sequential keys.

I create this issue in pair to my PR. So repo maintainer can track it in
more comfortable way, then just pr without details. Please close it, if
it's not necessary.

вт, 7 сент. 2021 г., 15:08 openinx ***@***.***>:
