### ISSUE TITLE
Docs:  Add document how to export records from CDC/Upsert Stream into apache iceberg table.

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#3105]
I think this document should include those changes: 

1. https://github.com/apache/iceberg/pull/2410 
2. https://github.com/apache/iceberg/pull/2863

**Comment by adiroy05** [comment]
hey i would like to work on this issue...assign to me

**Comment by hililiwei** [comment]
> hey i would like to work on this issue...assign to me

 don't have to be assigned. feel free to go on. :)

**Comment by Kshitiz-Mhto** [comment]
@adiroy05  if you busy doing some other work, can i work in place of you in this issue.

**Comment by Kshitiz-Mhto** [comment]
i am a newbie to open source so can you provide some helps. 
where should i includes those change in 
iceberg/docs/flink/flink-connector.md
or 
iceberg/docs/flink/flink-getting-started.md
or u want something different?

**Comment by hililiwei** [comment]
@Kshitiz-Mhto Thank you very much for your interest. There are currently two PR's related to this, for reference:
https://github.com/apache/iceberg/pull/3827
https://github.com/apache/iceberg/pull/3823

**Comment by shreyanshR7** [comment]
Hello @openinx I am new to open source and want to work on this issue please guide me about the issue, the technical knowledge prerequisites to solve the issue, so that I can go through them and start working on the issue.
