### ISSUE TITLE
Optimize stats estimation in Spark 2

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#3108]
We should probably match the updated stats estimation behavior in Spark 2 to match what we have in Spark 3.
See PR #3038.

**Comment by wypoon** [comment]
I created https://github.com/apache/iceberg/pull/3134.

**Comment by wypoon** [comment]
@aokolnychyi this can be closed now. (I don't think I can close this myself.) @rdblue has merged my PR.

**Comment by rdblue** [comment]
Thanks, @wypoon!
