### ISSUE TITLE
SparkSessionCatalog.listTables() does not list Iceberg tables

### ISSUE THREAD

**Issue by netvl** [apache/iceberg#3109]
The `SparkSessionCatalog.listTables()` method (the V2 Spark catalog API) looks like this:
https://github.com/apache/iceberg/blob/838cc652273c1444155bec2e1d6029cfbdbf3ea3/spark3/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java#L110-L113

That is, it delegates to the underlying session catalog directly. This results in Iceberg tables not being listed in the result of the `listTables()` call, making a code like this to fail in presence of Iceberg tables:
```scala
val tables = catalog.listTables(namespace)
tables.foreach(catalog.dropTable)
catalog.asInstanceOf[SupportsNamespaces].dropNamespace(namespace)
```
because the namespace is not actually empty, because `listTables()` does not return Iceberg tables.

This is highly confusing, because as a user I would expect the catalog API behave consistently to the method names and API description. `listTables()` not returning all tables in a namespace seems like a major breach of the API contract.

**Comment by netvl** [comment]
cc @RussellSpitzer @rdblue

**Comment by RussellSpitzer** [comment]
@rdblue As far as I could tell there was no explicit reason for this behavior but I was wondering if there is some Spark Code somewhere that will be unhappy with us if we list Iceberg tables as well. If you don't know of any instances of that, i think we should complete the implementation.

**Comment by netvl** [comment]
Ok, it seems that the reason why `dropNamespace` fails is not tied to the `listTables()` problem directly (because `SparkSessionCatalog` seems to delegate `dropNamespace` directly to the legacy session catalog, which should ignore any Iceberg tables), but the issue IMO is still relevant as itself.

**Comment by flyrain** [comment]
Interesting, my test works, `SparkSessionCatalog::listTables` can list both iceberg table and non-iceberg table. We need to dig deeper.

**Comment by netvl** [comment]
@flyrain most likely, that's because the session catalog is also set to source tables from Hive. If the session catalog does not point to Hive (e.g. in-memory) then there will be a discrepancy.

**Comment by flyrain** [comment]
Make sense. As @RussellSpitzer and me discussed before, the Spark build-in session catalog cannot list tables from Iceberg “Hadoop” type catalog. We cannot only rely on the the Spark build-in session catalog in that sense. This is a confusing behavior for the SparkSessionCatalog.

**Comment by RussellSpitzer** [comment]
Maybe SparkSessionCatalog should have a special list behavior when the iceberg catalog is Hadoop or we just don't support Hadoop as a catalog type for session catalog?

**Comment by flyrain** [comment]
Won't hurt anything. And we probably need the similar changes for methods `listNamespaces`, `createNamespace`, `dropNamespace` and so on. We can borrow something code from class `SparkCatalog` for that.

**Comment by fnqista** [comment]
Hey @RussellSpitzer @rdblue - years have passed since this issue gained traction. Is this still going to be fixed?
