### ISSUE TITLE
Table to retractStream error

### ISSUE THREAD

**Issue by flyxu1991** [apache/iceberg#3121]
I group by TUMBLE(proctime, INTERVAL '1' DAY) in the upstream. Then it's ok when i execute tableEnv.sqlQuery.print, but when i execute tableEnv.toRetractStream(table, ROW.class), 
it's error like this:
java.lang.IllegalArgumentException: Row arity: 4, but serializer arity: 3
at org.apache.flink.table.runtime.typeutils.RowDataSerializer.copy(RowDataSerializer.java:124)
at org.apache.flink.table.runtime.typeutils.RowDataSerializer.copy(RowDataSerializer.java:48)
What's the problem with my procedure?

**Comment by flyxu1991** [comment]
Don't table-format v2 support streaming read?

**Comment by openinx** [comment]
Yes, the current format v2 don't support streaming read now.  The stacktrace is a bug which was addressed in this PR: https://github.com/apache/iceberg/pull/2731

**Comment by flyxu1991** [comment]
Thanks for you help, yige
