### ISSUE TITLE
Rename the existing python module

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3122]
Create an issue to track this follow up item from the sync meeting.

**Comment by jun-he** [comment]
related PR: https://github.com/apache/iceberg/pull/3074

**Comment by joshuarobinson** [comment]
Not sure if this is the right place for this question -- are there any notes or docs online that discuss the plan going forward for python/iceberg?
thanks

**Comment by danielcweeks** [comment]
> Not sure if this is the right place for this question -- are there any notes or docs online that discuss the plan going forward for python/iceberg? thanks

@joshuarobinson There's a [github project](https://github.com/apache/iceberg/projects/7) tracking the python work and links to various docs and resources are in the project description.

The current focus is restructuring the legacy python packages then adding additional support/features.

**Comment by danielcweeks** [comment]
@jun-he I believe we can close this issue out, right?

**Comment by danielcweeks** [comment]
Closing as complete

**Comment by jun-he** [comment]
Thanks.
