### ISSUE TITLE
how create iceberg hive catalog kerberos

### ISSUE THREAD

**Issue by Neo966** [apache/iceberg#3128]
Is that so？

SET iceberg.catalog.another_hive.type=hive;
SET iceberg.catalog.another_hive.uri=thrift://xxx:9083;
SET iceberg.catalog.another_hive.clients=10;
SET iceberg.catalog.another_hive.warehouse=hdfs://xxx/hive_db; SET iceberg.catalog.another_hive.hadoop.hive.metastore.kerberos.keytab.file=xxx.keytab;
SET iceberg.catalog.another_hive.hadoop.hive.metastore.kerberos.principal=xxx

**Comment by pvary** [comment]
@liuhd666: Currently it is not possible to provide different credentials for the second metastore.

To enable this we would need something similar for Hive that has been created here for spark: #2607 - #2792

**Comment by pvary** [comment]
CC: @marton-bod

**Comment by liuhd666** [comment]
> @liuhd666: Currently it is not possible to provide different credentials for the second metastore.
> 
> To enable this we would need something similar for Hive that has been created here for spark: #2607 - #2792

**Comment by liuhd666** [comment]
> @liuhd666: Currently it is not possible to provide different credentials for the second metastore.
> 
> To enable this we would need something similar for Hive that has been created here for spark: #2607 - #2792

it's not work that using a HiveCatalog that corresponds to the metastore configured in the Hive environment : #3127
