### ISSUE TITLE
beeline query iceberg table error

### ISSUE THREAD

**Issue by Neo966** [apache/iceberg#3146]
0: jdbc:hive2://xxx:218> select * from iceberg_test;
INFO  : Compiling command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7): select * from iceberg_test
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:iceberg_test.id, type:bigint, comment:null), FieldSchema(name:iceberg_test.name, type:string, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7); Time taken: 1.196 seconds
INFO  : Concurrency mode is disabled, not creating a lock manager
INFO  : Executing command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7): select * from iceberg_test
INFO  : Completed executing command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7); Time taken: 0.027 seconds
INFO  : OK
Error: java.io.IOException: java.lang.ClassCastException: org.apache.iceberg.mr.mapred.Container cannot be cast to org.apache.iceberg.mr.mapred.Container (state=,code=0)

0: jdbc:hive2://xxx:218> set iceberg.mr.reuse.containers=true;
Error: Error while processing statement: Cannot modify iceberg.mr.reuse.containers at runtime. It is not in list of params that are allowed to be modified at runtime (state=42000,code=1)

**Comment by liuhd666** [comment]
sometimes report this error:

0: jdbc:hive2://xxx:218> select * from iceberg_test;
INFO  : Compiling command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7): select * from iceberg_test
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:iceberg_test.id, type:bigint, comment:null), FieldSchema(name:iceberg_test.name, type:string, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7); Time taken: 1.196 seconds
INFO  : Concurrency mode is disabled, not creating a lock manager
INFO  : Executing command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7): select * from iceberg_test
INFO  : Completed executing command(queryId=hive_20210918134550_136a108f-6791-4c3a-ac0b-25cde234c7a7); Time taken: 0.027 seconds
INFO  : OK
Error: java.io.IOException: java.lang.ClassCastException: org.apache.iceberg.mr.mapred.Container cannot be cast to org.apache.iceberg.mr.mapred.Container (state=,code=0)
0: jdbc:hive2://xxx:218> set iceberg.mr.reuse.containers=true;
Error: Error while processing statement: Cannot modify iceberg.mr.reuse.containers at runtime. It is not in list of params that are allowed to be modified at runtime (state=42000,code=1)

hive version:2.1.1
create table ddl:
CREATE TABLE iceberg_test(id bigint, name string) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';

**Comment by MrSuperLi** [comment]
Have you found a solution? I have the same problem

**Comment by pvary** [comment]
Could you please try this with Hive 2.3.8? We do all of the testing with that version.

Thanks, Peter

**Comment by pvary** [comment]
Or alternatively 3.1.2

**Comment by Neo966** [comment]
it's works, place the iceberg-hive-runtime-0.12.0 jar under the hive auxlib directory.

**Comment by pvary** [comment]
Maybe order of the jars in the classpath is different. Is there another iceberg jar on the classpath?

**Comment by Neo966** [comment]
no, only one jar.

It works, but does not support field filtering. throw exception: java.lang.NoSuchMethodError: org.apache.hadoop.hive.ql.io.sarg.ConvertAstToSearchArg.create(Lorg/apache/hadoop/conf/Configuration;Lorg/apache/hadoop/hive/ql/plan/ExprNodeGenericFuncDesc;)Lorg/apache/hadoop/hive/ql/io/sarg/SearchArgument;

the official website say support 2.x and 3.1.2 hive version, only 2.3.8 and 3.1.2 version was fully tested?

**Comment by pvary** [comment]
> the official website say support 2.x and 3.1.2 hive version, only 2.3.8 and 3.1.2 version was fully tested?

Those are the versions that the unit tests are run. 
Maybe we should clarify in the doc. Good point!

**Comment by wangmiao1002** [comment]
I also encountered the same problem. I tried to solve it in this way. At present, the test is successful. I don't know whether it is reasonable or not. 

Put iceberg-hive-runtime-0.13.1 jar in hive_ AUX_ JARS_ Path configuration directory;
 Recompile the hive runtime module and modify the dependencies in the project to version 2.1.1
