### ISSUE TITLE
Extend Iceberg metadata with SortOrder

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#317]
Here is a short summary of the [discussion](https://lists.apache.org/thread.html/7692ce3c1714f1733fa11aa632da2f8c0696b4ae64d04c6563f17e50@%3Cdev.iceberg.apache.org%3E) on the dev list:
- Iceberg should allow users to define a sort order in its metadata that applies to partitions.
- We should never assume the sort order is actually applied to all files in the table, as that would require rewriting data immediately when we change the sort order.
- Sort orders might evolve and change over time. When this happens, existing files will not be rewritten. Query engines should follow the updated sort order during subsequent writes. As a result, files within a table or partition can be sorted differently at a given point in time.
- We should be able to define a sort order even for unpartitioned tables, as opposed to current Spark tables that allow a sort order only for bucketed tables.
- `SortOrder` should be separate from `PartitionSpec`.
- `SortOrder` will rely on transformations to define complex sort orders.
- Files will be annotated with `sort_order_id` instead of `sort_columns`. We keep the question of `file_ordinal` open for now.
- To begin with, we will support asc/desc natural sort orders (UTF8 ordering for Strings).

**Comment by aokolnychyi** [comment]
I'll submit a PR soon

**Comment by waterlx** [comment]
Hi @aokolnychyi are you still working on the PR?
By the way, regarding 
> Sort orders might evolve and change over time. When this happens, existing files will not be rewritten. Query engines should follow the updated sort order during subsequent writes. As a result, files within a table or partition can be sorted differently at a given point in time.

In terms of "changing sort order", do we only support adding new sort order, while it is prohibited to change existing sort orders (especially when they are tied by some data files).
If it is allowed to change an existing sort order, we could run into problems when visiting the old data files tied to it, right?

**Comment by aokolnychyi** [comment]
@waterlx I have started working on this, but then got distracted by our internal milestones. I hope to submit a PR by the end of this week.

I think it makes sense to follow the same approach as we currently follow for partition spec evolution: we can keep a list of sort orders with their ids in the metadata and files will be annotated with `sort_order_id`. That way, we can always reconstruct the correct sort order for a file.

**Comment by waterlx** [comment]
@aokolnychyi , thanks for sharing the progress!
I did not make myself clear. Yes, we could change the sort order for partitions. But regarding the individual sort order in the list of sort order in the metadata, is it allowed to change one of them? Say we have a sort order with id =1, sorting on source_column_id = 1 with ascending order, is it supported that it is updated to descending order? Shall we prohibit such kind of change, as it could run into problem when an existing data file is tied it, right?

**Comment by aokolnychyi** [comment]
@waterlx I agree that sort orders should be immutable. If we change the sort order for a table, we should produce a new sort order with a fresh id.

**Comment by prodeezy** [comment]
@aokolnychyi good stuff! 

Should we also add an API for sort order evolution ? like `UpdateSortOrder`? So that changes to sort order can be controlled/audited within this API.  This API can be accessed using `Table.updateSortOrder()` maybe?

**Comment by aokolnychyi** [comment]
PR: https://github.com/apache/iceberg/pull/1373

**Comment by rdblue** [comment]
This was implemented in #1373.
