### ISSUE TITLE
No metrics from S3FileIO

### ISSUE THREAD

**Issue by krisdas** [apache/iceberg#3205]
I am following https://spark.apache.org/docs/latest/monitoring.html#metrics to emit metrics from [HadoopFileIO](https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java) and get the metrics successfully. But after switching to [S3FileIO](https://iceberg.apache.org/aws/#s3-fileio), don't get similar metrics from it.

Curious to know, if S3FileIO emits any metrics, no open source document available for this.

**Comment by danielcweeks** [comment]
You might want to take a look at #3062 which has a little more detail on this subject
