### ISSUE TITLE
Support ZSTD compression codec for Avro files

### ISSUE THREAD

**Issue by kekwan** [apache/iceberg#3206]
Currently, only SNAPPY and GZIP compression codec are supported for Avro files. Are there plans to support ZSTD? It is several times faster than GZIP.

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/avro/Avro.java#L77

**Comment by amogh-jahagirdar** [comment]
I am happy to look into raising a PR for support ZSTD Compression for Avro. We should define a sane default compression level and should allow configurable compression level options as well. What are your thoughts?

@jackye1995 @rdblue @kekwan

**Comment by rdblue** [comment]
Yes, Zstd for Avro would be great if Avro supports it. I'd go with whatever the default is in the Zstd library.
