### ISSUE TITLE
Extend DeleteOrphanFiles use cases

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3212]
`DeleteOrphanFiles` currently has the following limitations:
1. it assume a single location for all the files, which would not work for tables that stores files in a separated directory
2. it does not work if multiple tables store files under the same root, which would be a common case for people having object storage mode to store all data files at the root bucket to minimize throttling
3. it still requires a file system to perform file listing, so for S3FileIO users they still have to install S3A file system just to remove orphan files

My current thoughts are the following:

For 1, can be mitigated by running the action multiple times with different root locations, which would probably be enough as a maintenance procedure.

For 2, maybe we can add a few filters, which includes:
1. path filter: allowing a regex to know if a path might belong to some other table and should not be removed
2. metadata filter: allowing checks against some specific metadata of a file to know if it might belong to some other table. This also requires adding a new `Map<String, String> metadata()` interface in `InputFile` for `FileIO` to implement.
3. we also have the hard-coded restriction that only lists `at most 3 levels and only dirs that have less than 10 direct sub dirs on the driver`, which I think should be made configurable.

For 3, I am not sure what is the best way. I am thinking if we could add listing operation also to `FileIO`, and it would only be used for this action. Would listing be useful for any other potential actions? Or would it cause a potential abuse of file listing?

@aokolnychyi

**Comment by szehon-ho** [comment]
Yea I was also thinking about this issue.  

For (2.1) and (2.2), maybe we can have a multi-table Action instead of having user pass in path and metadata filter which could be dangerous.  And yes for (2.3), I was thinking this for awhile.

For (3) I think yes we could add FileIO.list and be vigilant in the reviews to not allow listing unless absolutely necessary.

**Comment by kbendick** [comment]
For clarification, in (2), by `object storage mode`, do you mean the [`ObjectStorageLocationProvider`](https://github.com/apache/iceberg/blob/12e30ebaeb6dc0ff7e6bb01c0d9f8ae8a5f06ddf/core/src/main/java/org/apache/iceberg/LocationProviders.java#L98)?

**Comment by jackye1995** [comment]
> For clarification, in (2), by object storage mode, do you mean the ObjectStorageLocationProvider?

Yes
