### ISSUE TITLE
[Python] support iceberg expressions in python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3217]
- [ ] Literals
- [ ] Operations
- [ ] Terms
- [ ] Boolean Expressions
- [ ] Predicates (bounded and unbounded)
- [ ] Binders
- [ ] Expression Visitors

**Comment by samredai** [comment]
PR activity around expressions is picking up so I wanted to provide some ordering in terms of dependency that should be helpful. My understanding is this is the order that things need to be implemented (where 2 depends on 1, 3 depends on 2, etc...):

1. Conversions (PR #4263)
2. Literals (PR #4262)
3. Operations
4. Parsers
5. Terms
6. References
7. Predicates
8. Expression visitors

**Comment by Fokko** [comment]
I think most of the above-mentioned [are in](https://github.com/apache/iceberg/blob/master/python/pyiceberg/expressions/base.py) or are being worked on ([expression visitors](https://github.com/apache/iceberg/pull/5303)). I'll take the liberty of closing this now, and we can create new (smaller) tickets for follow-up functionality.
