### ISSUE TITLE
[Python] support iceberg jdbc catalog in python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3221]

**Comment by nssalian** [comment]
Can I take this up? I am working on the JdbcCatalog on the Java side as well.

**Comment by nssalian** [comment]
@jun-he  Thanks. Don't see a issue for the base catalog.

**Comment by srilman** [comment]
Will this catalog be based off the JDBC interface like the Java implementation or will it use Python's DB API (https://peps.python.org/pep-0249, many DB libraries follow this API)? I think the latter would be preferable.

**Comment by Fokko** [comment]
Fixed in https://github.com/apache/iceberg/pull/7921
