### ISSUE TITLE
[Python] support table in iceberg python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3227]

**Comment by xinbinhuang** [comment]
@jun-he I want to take a stab at this if it doesn't have dependencies on other issues. Can you assign it to me?

**Comment by jun-he** [comment]
SG, thanks for the help. BTW, table depends on the partition spec and schema, which are ongoing work.

**Comment by xinbinhuang** [comment]
> SG, thanks for the help. BTW, table depends on the partition spec and schema, which are ongoing work.

Understood, I'm keeping an eye on those

**Comment by dhruv-pratap** [comment]
@xinbinhuang I have some bandwidth available right now and I was thinking of picking up this issue. Are you cool if I can get going on this?

**Comment by xinbinhuang** [comment]
@dhruv-pratap feel free to pick it up!

**Comment by dhruv-pratap** [comment]
This tracker is essentially an epic and needs to be broken down further into smaller pieces. We need to break this down into the below pieces to begin with:

1. Define a `TableBuilder` API to create a Table without `Transaction` to begin with.
2. Create a table using `TableBuilder` API without `Transaction`.
 a. With table identifier and schema
 b. With PartitionSpec 
 c. With SortOrder
 d. With Location
 e. With Properties
3. Load a table which returns the `Table` instance with the current table spec.
4. Define `Transaction` API for performing multiple updates to a table in a transaction.
5. Extend the `TableBuilder` API to start create/replace transactions.
6. Create a table in transaction using `Transaction` API
7. Replace a table in transaction using `Transaction` API
8. Create or Replace a table in transaction using `Transaction` API

Class Diagrams:
![TableBuilder](https://user-images.githubusercontent.com/11399509/169559989-40519b91-f423-41cc-add6-212c07d2e2f1.png)

**Comment by Fokko** [comment]
I'll pick this up if that's okay. I'm working on the REST Catalog, and need to implement this anyway

**Comment by dhruv-pratap** [comment]
Hi @Fokko that should be okay, please go ahead. Apologies I couldn't get to this as some work related stuff came up at my end. I'll sync up with you once I circle back to this to see if there are any left overs from this item that I can pick-up. Thanks!

**Comment by Fokko** [comment]
@dhruv-pratap 👍🏻  I think we can close this, we have a table structure: https://github.com/apache/iceberg/blob/master/python/pyiceberg/table/__init__.py#L32
