### ISSUE TITLE
Python README should include build and test instructions

### ISSUE THREAD

**Issue by jbapple** [apache/iceberg#323]
The README in the top-level `python` directory has no build and test instructions. There is a `setup.py`, but the usage is not fully clear to me. Various combinations of python2, python3, dependencies, command orders, and sudo or not produce a variety of errors.

As an example, `sudo python setup.py install` warns about `setuptools` being too old (version 0.0.0, according to the filename), even after `pip install`ing the latest setuptools.

**Comment by rdblue** [comment]
@TGooch44, could you add this?

**Comment by TGooch44** [comment]
Will check it out

**Comment by TGooch44** [comment]
@jbapple I'm going to submit a PR on this, but can you try doing a pip install -e . from the python directory?  Note that the iceberg client requires python >= 3.4

**Comment by jbapple** [comment]
Didn't work without `sudo`. With it:

```
ERROR: awscli 1.14.19 has requirement botocore==1.8.23, but you'll have botocore 1.12.199 which is incompatible.
ERROR: awscli 1.14.19 has requirement s3transfer<0.2.0,>=0.1.12, but you'll have s3transfer 0.2.1 which is incompatible.
...
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/iceberg-0.0.0-py3.5.egg'
```
