### ISSUE TITLE
Don't consider groups for compaction if they have a single file that cannot be split

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#3236]
Currently we allow MIN_INPUT_FILES to be any positive number but if we set the value to 1 this means single files will be rewritten. 

https://github.com/apache/iceberg/blob/adc6d153b26e7f982d75b427f62002e32f1913fc/core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java#L234-L236

There are two circumstances in my mind when this value is set to 1

1. There is a single file which is too small. We should ignore this file since we can't actually do anything with it
2. There is a single file which is too big, this should actually be rewritten as files of the correct size.

Currently we would rewrite in both cases, I think we should put in an extra check to always turn 1. into a NOOP

**Comment by singhpk234** [comment]
May I have a try ?

**Comment by RussellSpitzer** [comment]
Go for it

**Comment by singhpk234** [comment]
Thanks @RussellSpitzer .

Can you please help me with some clarification's :) or can point me to some resources : 

when it's said groups which have single file you mean to say the packed groups ?
https://github.com/apache/iceberg/blob/adc6d153b26e7f982d75b427f62002e32f1913fc/core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java#L137-L139

Implying an additional condition on filtering the potentialGroups .
```
(group.size() >= minInputFiles && group.size() != 1)  || sizeOfInputFiles(group) > targetFileSize
```
or you mean skip all groups when `minInputFiles = 1` .

As per my understanding, this story, attemps to save op's when we have one file within our targetSize we don't need to re-write it and thus can make this a no-op. But if there is a file whose size is  > targetSize it make sense for it to be re-written into optimal size files and hence the skipping all groups when this config is set to 1 is incorrect and thus we should intend to modify the filter condition in the potentialGroups filtering.

**Comment by RussellSpitzer** [comment]
We are talking about "potential groups" whose contents, if re-written would not create a different file than the groups contents before the rewrite.

So the easy example is:
A group which contains a single file that is unaffected by deletes and which cannot be split into multiple files
A group with a single file that is modified by deletes should be rewritten (if the rewrite deletes filter is on)
A group with a single very large file should be rewritten (but only if we can split it into target size files)

More complicated examples which you don't have to cover in this PR are things like:
A group which contains multiple files which cannot be combined into more efficent files, For example we currently do not support binpacking portions of row groups, so if you have 3 files and each has a single 100 MB row group, we won't be able to rewrite that into say, 2 150 MB files since the original files cannot be split except on row group boundaries.
