### ISSUE TITLE
Enable Python Client to work with non-AWS object stores (endpoint_override)

### ISSUE THREAD

**Issue by joshuarobinson** [apache/iceberg#3238]
Using a non-AWS object store (e.g., Pure FlashBlade, Minio, etc) requires setting an endpoint_url, so that boto3 knows how to find the object store. 

Note that Spark, Trino, et al provides these overrides already, so it's just the direct library that needs this support. (Perhaps Java does too need this? I'm only using python at the moment)

**Comment by rdblue** [comment]
This is related to #5332. We should make sure this is possible with the new Python lib.

**Comment by joshuarobinson** [comment]
This will be fixed by https://github.com/apache/iceberg/pull/5747
