### ISSUE TITLE
Add table property to disable snapshot expiration

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#3246]
For tables tracked by the NessieCatalog it makes sense to always disable snapshot expiration and let Nessie itself take care of when to expire snapshots, thus a new property `history.expire.enabled` in `TableProperties` is required

**Comment by jackye1995** [comment]
why not just set `history.expire.max-snapshot-age-ms` to `Long.MAX_VALUE`?

**Comment by nastra** [comment]
Using the `GC_ENABLED` flag makes probably sense.

**Comment by rdblue** [comment]
I'm closing this because `GC_ENABLED` already implements what we want.
