### ISSUE TITLE
SparkCatalog.alterTable() violates the contract of the TableCatalog interface

### ISSUE THREAD

**Issue by netvl** [apache/iceberg#3281]
The `alterTable()` method on the `SparkCatalog` class always returns `null`. However, per the [API documentation](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/connector/catalog/TableCatalog.html#alterTable-org.apache.spark.sql.connector.catalog.Identifier-org.apache.spark.sql.connector.catalog.TableChange...-) of the `TableCatalog` interface, this method must return the updated `Table` instance.

**Comment by RussellSpitzer** [comment]
Marking this as another good first issue for anyone who wants to get started on Iceberg :)

**Comment by xinbinhuang** [comment]
can you assign this to me? :)

**Comment by RussellSpitzer** [comment]
Will do! Feel free to just say you are working on an issue, I don't think we usually use Assignees
