### ISSUE TITLE
[Python] gist examples for iceberg python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3283]

**Comment by chulucninh09** [comment]
Extending the idea of @fjetter and also being mentioned in https://apache-iceberg.slack.com/archives/C029EE6HQ5D/p1635453723004300, I wrote this gist to describe more about my expected experience using `iceberg`.
https://gist.github.com/chulucninh09/3484445d4cea62096de6e6e3ea684fa2

As a pandas user, I think of iceberg is a kind of IO engine, my main focus is to process the data, while iceberg is the driver to connect to my data.

I also wrote the expected way of using Iceberg management API, taking from experience with `pyarrow` and `parquet`, in case I need more fine-grained way to access my data.
