### ISSUE TITLE
How to disable snapshot at table level?

### ISSUE THREAD

**Issue by ChengzhiZhao** [apache/iceberg#3290]
Hi All, I have a question need some advice here, we want to disable snapshot (time travel) for certain iceberg tables while keep other tables with snapshot still enabled. Any suggestions on how to achieve this?

**Comment by RussellSpitzer** [comment]
This is not possible as Iceberg only operates through Snapshots ie, it always makes changes by adding a new snapshot. You could expire snapshots after every write which would effectively disable time travel but this would be manual. 

Maybe someone else has a better idea ...
