### ISSUE TITLE
Expose AncestorsOf Snapshot as Spark Procedure

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#3297]
Currently we have found that there is some utility in being able to get all the snapshot ancestors of a particular snapshot. This information can be obtained using 

https://github.com/apache/iceberg/blob/d9ab0babd2de7c5d3dc14e8f458bd1020a14329e/core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java#L77-L89

But there is no way to get this information from SQL directly. I was thinking we may benefit from exposing this, and several other functions as stored procedures for SQL use.

Something like

```SQL
CALL ice_cat.system.ancestorsOf(table, snapshotId = currentSnapshot)
| snapshotId |
| 3                |
| 2                 |
| 1                 |
```

**Comment by RussellSpitzer** [comment]
I was considering you could pass and arg to get ancestors of another snapshot that is not current. For example if you rolled back

**Comment by KnightChess** [comment]
> I was considering you could pass an arg to get ancestors of another snapshot that is not current. For example if you rolled back

oh, its mean all snapshots find the target id slowly, but pass an arg, the ancestors will be find quickly? I don't know much about rollback for the metadata, but it does not affect the realization of this function. I will confirm the mechanism later.

**Comment by RussellSpitzer** [comment]
More like - 
Says I have snapshots
```
A -> B - > C -> (D)
```
I then roll back to B and add C' and D'

So i have the following live snapshots
```
A -> B - > C -> D
           \ -> C' -> (D')
```
           
Now I want to know the ancestors of "D".


Basically the default behavior of AcnestorsOf would give you the ancestors of the table's current snapshot, but you can pass in an arguement to get ancestors of another snapshot in the current history, or in a divergent one you rolled back from

**Comment by KnightChess** [comment]
Hi, @RussellSpitzer  I am newbie to open source, not sure about the rules. Looked other issue, seems to need to assign issue...
this is the pr for this issue, #3317

**Comment by RussellSpitzer** [comment]
We have no rules here :) But I can assign you if you like. Honestly we tend to just respect whoever wants to do the work should put up a pr, and then we go from there.
