### ISSUE TITLE
How do I need to merge small files with the new API

### ISSUE THREAD

**Issue by SusurHe** [apache/iceberg#3327]
I find the class `org.apache.iceberg.actions.Actions` was deprecated, when i want to use it to merge small files;
Now I find the new class `SparkActions`, but I don't know how to set target files size?

**Comment by pan3793** [comment]
You can find demo from [TestNewRewriteDataFilesAction](https://github.com/apache/iceberg/blob/119d20d22e66655bce1590041e4ba25ae48874fb/spark/v3.0/spark3/src/test/java/org/apache/iceberg/spark/actions/TestNewRewriteDataFilesAction.java)
