### ISSUE TITLE
Outdated object-store-file-layout documentation

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#3401]
https://iceberg.apache.org/aws/#object-store-file-layout

It seems:

1. write.data.path is not used anymore, but it still appears in the doc
2. formatting issue beginning with "the logic is as follows:"...

**Comment by yyanyy** [comment]
I think `write.data.path` is a new thing introduced in #3094 but we did not update table property related doc, potentially because this change is currently not in any official release yet
