### ISSUE TITLE
After merging small files, the number of files is still large

### ISSUE THREAD

**Issue by SongJok** [apache/iceberg#3409]
When we successfully write data, the number of small files and the space of small files increase greatly, but after the small file merge on the official website, the number of files does not change, and there is no merge

**Comment by peterxiong13** [comment]
我也碰到此问题了，发现快照过期时很多文件并没有删除掉。用并行方式快照过期会卡住，移除孤儿文件也会卡住

**Comment by peterxiong13** [comment]
我也碰到此问题了，发现快照过期时很多文件并没有删除掉。用并行方式快照过期会卡住，移除孤儿文件也会卡住
