### ISSUE TITLE
commit snap of merge small files and normal java job has complict

### ISSUE THREAD

**Issue by tlchao** [apache/iceberg#3417]
I started a job used java api to generate an iceberg partiton-table. This job append data to table every two minutes, this will lead to lots of small files. I hope to merge small files in another spark job with writing operation parallelly. I have found two operators will generate snap complicit, which leads to writing job meet "snap-xxxx.avro can't be found" when merge job is running. And now the way we can use is making writing job and merging job execute serially. It seems this way is inefficient. Is any good ways? thanks!

**Comment by dylzlt** [comment]
what's the logic of the merge job? Did you expire and clean the old snapshot when your merge job completed?

**Comment by owencwl** [comment]
It seems to be the same problem as the issue 4550， https://github.com/apache/iceberg/issues/4550

**Comment by Fokko** [comment]
@tlchao Thanks for opening this issue. What catalog are you using?
