### ISSUE TITLE
Website navbar not showing properly on Firefox

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3426]
@samredai 

Not sure if it's just me, I am seeing the following on Firefox. The same issue does not exist on Chrome and Safari.

![Snip20211030_1](https://user-images.githubusercontent.com/29823233/139555680-1f1b1577-4901-491a-a949-03f719af71de.png)

**Comment by nssalian** [comment]
Not hitting the same issue but the landing page didn't load for me as it did in Chrome and Safari.

**Comment by ismailsimsek** [comment]
Got same issue, after cleaning cookies-and-site-data it loaded correctly. also it did load correctly with Firefox incognito mode.

https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox

**Comment by kbendick** [comment]
Confirming that it no longer happens for me on Chrome when I opened a new window (presumably the cookies change).

**Comment by samredai** [comment]
Sorry for the noise here, GitHub pages sets a default 10 minute cache but that's persisting in some browsers for some reason. Clearing the cache should work.

**Comment by jackye1995** [comment]
Thanks for the investigation! I can confirm the fix works, closing this issue.
