### ISSUE TITLE
In CDC to Iceberg， why data files is still growing rapidly when finished Expire Snapshots & Compact data files

### ISSUE THREAD

**Issue by deepeye** [apache/iceberg#3447]
In 10 hours, the number of data files has increased by four times, and the file size has increased by five times, even though I have performed the operations of expire snapshots & compact data files。
I do not know why？Please help me！

iceberg table case：
```
CREATE TABLE iceberg_user(
  user_id STRING,
  `name` STRING,
  PRIMARY KEY (`user_id`) NOT ENFORCED
)
WITH(
    'connector'='iceberg',
    'format-version' = '2',
    'engine.hive.enabled' = 'true',
    'write.distribution-mode'='hash',
    'write.metadata.delete-after-commit.enabled' = 'true',
    'write.metadata.previous-versions-max' = '6',
    'history.expire.max-snapshot-age-ms' = '180000',
    'flink.rewrite.enable' = 'true',
    'flink.rewrite.parallelism' = '1',
    'flink.rewrite.target-file-size-bytes' = '134217728',
    'flink.rewrite.max-files-count' = '50',
    'catalog-name'='hive_prod',
    'catalog-database'='hch_data_center',
    'catalog-table'='iceberg_user',
    'uri'='thrift://flink001:9083',
    'io-impl'='org.apache.iceberg.aliyun.oss.OSSFileIO',
    'oss.endpoint'='',
    'oss.access.key.id'='',
    'oss.access.key.secret'='',
    'warehouse'='oss://bucket/iceberg/warehouse'
);
```

**Comment by kbendick** [comment]
A few things are possible that I can think of. First and foremost, you should check out the docs on:
- table maintenance https://iceberg.apache.org/#maintenance/#table-maintenance 
- streaming table maintenance: https://iceberg.apache.org/#spark-structured-streaming/#maintenance-for-streaming-tables

If you're running the expire snapshots operation, keep in mind that there is the option for how many days worth of data do you want to retain. By default, the spark action to expire snapshots retains 5 days worth of snapshots, which would explain why no files are being removed.

When you run the expire snapshots job, do you see any logs saying things are enabled?
Some links that might help:
- Javadoc for the action itself: https://iceberg.apache.org/#javadoc/0.12.0/org/apache/iceberg/ExpireSnapshots.html
- Docs for the options from the Spark maintenance actions: https://iceberg.apache.org/#spark-procedures/#metadata-management

I'd also make sure that your table doesn't have `gc.enabled = true` as a table property. If that's set to `false` (default should be `true`), then files won't be removed regardless.

Additionally, it's possible that you have orphan files from commits that did not succeed and needed to be retried. You should also run the `remove orphan files` action: https://iceberg.apache.org/#maintenance/#remove-orphan-files

How are you running the actions? With Java code or with Spark? I don't believe that Flink presently supports all of the maintenance procedures. Either way, given that it's only 10 hours worth of data, you'll definitely need to pass in the timestamp you want to expire older than.

Try it out, ensuring that you pass in something for the `older_than` field of the Spark procedure (or the equivalent method if using the Java API). Something like `now() - INTERVAL '4 hours'` or `System.currentTimeMillis - (Duration.ofHours(4).getSeconds() * 1000)` or something.

Let us know if that solves your problem, particularly passing in a maximum age of files to keep. The default is well over 10 hours in all cases.

**Comment by deepeye** [comment]
Thanks for your help！I guess the reason is that when compact data files ， equality deletes are ignored。Please focus on https://github.com/apache/iceberg/pull/2372#issuecomment-845514501 
 and https://github.com/apache/iceberg/projects/10 ，
but I am not sure that solved the problem。I will try your suggest，thanks！

**Comment by myandpr** [comment]
> A few things are possible that I can think of. First and foremost, you should check out the docs on:
> 
> * table maintenance https://iceberg.apache.org/#maintenance/#table-maintenance
> * streaming table maintenance: https://iceberg.apache.org/#spark-structured-streaming/#maintenance-for-streaming-tables
> 
> If you're running the expire snapshots operation, keep in mind that there is the option for how many days worth of data do you want to retain. By default, the spark action to expire snapshots retains 5 days worth of snapshots, which would explain why no files are being removed.
> 
> When you run the expire snapshots job, do you see any logs saying things are enabled? Some links that might help:
> 
> * Javadoc for the action itself: https://iceberg.apache.org/#javadoc/0.12.0/org/apache/iceberg/ExpireSnapshots.html
> * Docs for the options from the Spark maintenance actions: https://iceberg.apache.org/#spark-procedures/#metadata-management
> 
> I'd also make sure that your table doesn't have `gc.enabled = true` as a table property. If that's set to `false` (default should be `true`), then files won't be removed regardless.
> 
> Additionally, it's possible that you have orphan files from commits that did not succeed and needed to be retried. You should also run the `remove orphan files` action: https://iceberg.apache.org/#maintenance/#remove-orphan-files
> 
> How are you running the actions? With Java code or with Spark? I don't believe that Flink presently supports all of the maintenance procedures. Either way, given that it's only 10 hours worth of data, you'll definitely need to pass in the timestamp you want to expire older than.
> 
> Try it out, ensuring that you pass in something for the `older_than` field of the Spark procedure (or the equivalent method if using the Java API). Something like `now() - INTERVAL '4 hours'` or `System.currentTimeMillis - (Duration.ofHours(4).getSeconds() * 1000)` or something.
> 
> Let us know if that solves your problem, particularly passing in a maximum age of files to keep. The default is well over 10 hours in all cases.

Hi, @kbendick ,I have been confused whether this action [RewriteDataFilesAction](https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/actions/RewriteDataFilesAction.java) in Flink supports v2 table?I mean that whether this action can rewrite equality delete files and position delete files in 'merge on read' mode.

Could you explain to me？thinks very much!
