### ISSUE TITLE
Doc: missing Spark doc for some system tables

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3465]
We are missing `partitions`, `entries`, `all_data_files`, `all_manifests`, `all_entries` tables in https://github.com/apache/iceberg/blob/master/site/docs/spark-queries.md?plain=1#L130

**Comment by KnightChess** [comment]
I'll supplement this doc this week, please assgin to me.

**Comment by jackye1995** [comment]
@KnightChess thanks! assigned

**Comment by bitsondatadev** [comment]
@jackye1995 can this be closed?
