### ISSUE TITLE
Website: Hive page does not show sections in sidebar

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3474]
Unlike Spark and Flink, Hive page does not show the section information in the sidebar. I suspect this is because we only have a single Hive markdown file comparing to Flink and Spark that has multiple so nested contents are displayed. We can either split Hive contents also to multiple files, or is there a way to fix the problem? @samredai 

![Snip20211104_5](https://user-images.githubusercontent.com/29823233/140446101-4118eac4-71d3-4980-a233-c8cf064f182e.png)
![Snip20211104_7](https://user-images.githubusercontent.com/29823233/140446107-8fc4c059-dcaf-494d-a42c-a58fa918c576.png)

**Comment by samredai** [comment]
You're exactly right that it doesn't show the section because it's a single file referenced at the top-level section. We could definitely break it up into multiple files but one issue to consider there is that the url links would change and could break links that have been saved/shared/bookmarked.

**Comment by jackye1995** [comment]
What about using:

```
  - Hive:
      - Getting Started: hive.md
```

**Comment by samredai** [comment]
I'll give that a try and open a PR. Thanks for highlighting this Jack!
