### ISSUE TITLE
Website: spec page does not show subsections in sidebar

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3475]
In the spec page, the `specification` section contains the majority of the contents. It is really hard to navigate without the ability to jump across subsections. Should we try to separate this to another independent markdown file? Or is there a way to enable subsections in sidebar? (maybe that will make the sidebar too nested...) @samredai 

![Snip20211104_8](https://user-images.githubusercontent.com/29823233/140446430-791e9d0f-e430-4569-8ed4-e86c696df3f6.png)

**Comment by samredai** [comment]
Agreed there is a lot of information buried within a single sub-section. Although the extra level of nesting under `Spec` does get busy very fast (see the image below).

<img width="1791" alt="Screen Shot 2021-11-05 at 7 13 39 PM" src="https://user-images.githubusercontent.com/43911210/140594439-2f77a16f-a68e-4d7a-a179-eaa3b3965153.png">

How about if we break them out into top sections under Format? The subsections in the page can then all be changed to `##` and be displayed in the navbar.
```
.
└── Format
    ├── Definitions
    ├── Spec Overview
    ├── Table Metadata
    └── Appendices
```

**Comment by jackye1995** [comment]
Thanks for testing it out! I am for the approach of breaking down to the sections you proposed, that is much easier to navigate for readers. For backwards compatibility, users accessing `/spec` can always land in the overview page.

**Comment by samredai** [comment]
Ok great, I'll get a PR ready for this!

**Comment by rdblue** [comment]
It would be nice to have a ToC similar to the old one, with different section levels shown.
