### ISSUE TITLE
Doc: Missing type mapping between Iceberg and Flink

### ISSUE THREAD

**Issue by luoyuxia** [apache/iceberg#3481]
Is there any document about type mapping between Iceberg and Flink in the doc site?
If not, I would like to add it in the document.

**Comment by xuzhiwen1255** [comment]
Are you referring to this https://iceberg.apache.org/docs/latest/flink/#iceberg-to-flink

**Comment by bitsondatadev** [comment]
@rdblue is this good to close?

**Comment by luoyuxia** [comment]
Thanks all. Close it.
