### ISSUE TITLE
set user timezone

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#3494]
val spark = SparkSession
      .builder()
      .master("local[2]")
      .appName("IcebergAPI")
      .config("spark.sql.catalog.hadoop_prod", "org.apache.iceberg.spark.SparkCatalog")
      .config("spark.sql.catalog.hadoop_prod.type", "hadoop")
      .config("spark.sql.catalog.hadoop_prod.warehouse", "file:///D:\\lake-iceberg")
      .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
      .config("spark.sql.sources.partitionOverwriteMode", "dynamic")
      .config("spark.sql.iceberg.handle-timestamp-without-timezone", "true")
      .config("spark.sql.session.timeZone", "Asia/Shanghai")// user local timeZone
      .getOrCreate()

In this case, user local timeZone has been setted "Asia/Shanghai", but inserted data's timeZone is still “UTC”.
How to setting user local timeZome? thanks.

**Comment by felixYyu** [comment]
spark.sql(
      s"""
        |CREATE TABLE IF NOT EXISTS hadoop_prod.$schemaName.$tableName (
        |    id string,
        |    data string,
        |    jydw_no string,
        |    ts timestamp)
        |USING iceberg
        |--PARTITIONED BY (bucket(12, id), days(ts), truncate(jydw_no, 5))
        |PARTITIONED BY (days(ts))
        |TBLPROPERTIES ('write.distribution-mode'='hash', 'write.metadata.compression-codec'='gzip',
        | 'write.metadata.delete-after-commit.enabled'='true', 'write.metadata.previous-versions-max'='9')
        |""".stripMargin)

spark.sql(
      s"""
         |INSERT OVERWRITE hadoop_prod.$schemaName.$tableName
         |  VALUES ($index, '$index', 'B3$index', CAST (from_utc_timestamp('2021-11-08 07:00:00', 'Asia/Shanghai') AS timestamp))
         |""".stripMargin)

in this DML the function of "from_utc_timestamp" is setted partitioned by '2021-11-08', but unused fuction it is setted partitioned by '2021-11-07', how to setting spark config of the partitioned by '2021-11-08'?

**Comment by felixYyu** [comment]
cc @rdblue @aokolnychyi @RussellSpitzer  can you help? thanks

**Comment by RussellSpitzer** [comment]
Underlying hidden partitioning is always done based on UTC, we had a few discussion on extending this in the past, but it was decided not to do so.

https://github.com/apache/iceberg/pull/1368
https://github.com/apache/iceberg/pull/1355
https://github.com/apache/iceberg/issues/2947

**Comment by rdblue** [comment]
Yes, Russell is correct. The time zone used for partitioning is internal and isn't a good idea to change. You should be able to set the SQL session time zone in Spark and use that just fine, but Iceberg will always partition values in UTC because the partition boundaries shouldn't matter to applications since they are hidden. If you need to ensure that there are partition boundaries in certain places, you can use hourly partitioning.

**Comment by felixYyu** [comment]
thanks very much @RussellSpitzer @rdblue

**Comment by atifiu** [comment]
Problem I see here is that I have to read two partitions if in query I give 24 hour range since local partition is ranging over two days based on UTC. I am using daily partitions. Any alternative to this ?

**Comment by RussellSpitzer** [comment]
@atifiu sort on timestamp as well as partiion on day, that way all the files will be excluded that don't have information from the 24 hour range you are looking for. This would also be timezone agnostic if you happen to change query timezones

**Comment by atifiu** [comment]
You meant to write data by sorting on timestamp column... example write ordered by timestamp, col1 ?

**Comment by atifiu** [comment]
@RussellSpitzer This approach doesn't help me much because I have filter criteria on other columns which I have included in sort order while writing the data files. If I sort on timestamp column without days or hours, within each file other filter column values are present and if I use date then it is same as previously i.e. two partitions are read. Please suggest ?

**Comment by RussellSpitzer** [comment]
I don't understand your comment, you sort on the time stamp and then your others columns

**Comment by RussellSpitzer** [comment]
If you have so much data that this is still an issue just partition on hour

**Comment by atifiu** [comment]
Existing sort order col1, col2, col3 and daily partition on timestamp column. After your suggestion my new sort order timestamp, col1, col2, col3. While my filter criteria is partition column with 24 hour range i.e one full day and then col1, col2, col3. I dont really want to change my partition spec because it means too many partition approx 2 yrs data 730x24 = 17520 partitions. Will this not impact performance adversely ?

**Comment by RussellSpitzer** [comment]
Depends on how much data you have, if you don't have enough data for that many partitions you probably aren't benefiting from all those sort columns either. Also if you don't have enough data to make multiple files in each "day" partition it's probably fine to just do nothing. Reading 2 files is not that much worse than reading one in most distributed engines.

**Comment by atifiu** [comment]
@RussellSpitzer I have approx 200 million rows for single day with 200 files for each day. Each file has size of approx 300mb. Query will be generally for a single day with additional filter criteria.

**Comment by atifiu** [comment]
@RussellSpitzer Really appreciate your help. I got your point now. Just one final advice I need, what should be more ideal solution, partition with lesser number of bigger files or partition with more number of smaller files ?

**Comment by RussellSpitzer** [comment]
In Iceberg partitions are really just tuples associated with file metadata, so number of partitions really doesn't matter except as it defines file size.  In general, you want files between 128 - 512 (or some multiple of your row group size). The opening file cost is different in different file systems and some have better performance with smaller vs larger files. 

Those partition tuples though are used during queries, so I think you generally want the most granular partitioning you can get so you can support more types of queries. Like I mentioned above, you can get similar effects though with sorting although that tends to me a little more expensive at write time or by doing sort optimizes.
