### ISSUE TITLE
Split SparkCatalogTestBase and allow running tests with one catalog

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#3499]
See [here](https://github.com/apache/iceberg/pull/3400#discussion_r744294889) for details.

**Comment by aokolnychyi** [comment]
We can probably just offer a new test class with 1 catalog and migrate some tests to use it.

**Comment by hililiwei** [comment]
May I have a try?

**Comment by RussellSpitzer** [comment]
Go for it @hililiwei

**Comment by hililiwei** [comment]
master:419684a9f089cd14628d573399f18af44a1098d5

**Comment by aokolnychyi** [comment]
Thanks, @hililiwei!
