### ISSUE TITLE
Implement strict projection in more transforms

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#35]
Strict projection isn't required and wasn't implemented for several of the partitioning transformations. When strict projection isn't implemented (the `projectStrict` method returns `null`) Iceberg will fall back to a safe implementation. For example, residual evaluation will not remove predicates because they cannot be guaranteed to be true, and deletes can't determine that all values in a file match so the file can't be deleted (deletes usually fall back to min/max metrics evaluation).

Implementing strict projection for all transforms where possible will help query efficiency, will make deletes faster, etc.

**Comment by jun-he** [comment]
I am working on this issue now and will send a PR soon.

**Comment by waterlx** [comment]
I think we could close this issue. Shall we?

**Comment by shiyi23** [comment]
Has this issue been fied yet?

**Comment by nssalian** [comment]
@rdblue , if no one else has picked this up, could I pick this up as a first issue?

**Comment by rdblue** [comment]
@nssalian, thanks for volunteering! I think that this one is already done, though. I should have closed it. (Thanks for pointing it out @waterlx!)

I think there are other good first issues though!
