### ISSUE TITLE
Set the write order of the table to be case sensitive, use WRITE ORDERED BY? Should the default value be changed to false

### ISSUE THREAD

**Issue by xiaotianzhang01** [apache/iceberg#3523]
Set the write order of the table to be case sensitive, use WRITE ORDERED BY? Should the default value be changed to false

It is not case-sensitive when creating the table, but it is case-sensitive here

```
ALTER TABLE lo_iceberg WRITE ORDERED BY s_city;

org.apache.iceberg.exceptions.ValidationException: Cannot find field 's_city' in struct: struct<1: LO_ORDERKEY: optional long, 2: LO_LINENUMBER: optional long, 3: LO_CUSTKEY: optional int, 4: LO_PARTKEY: optional int, 5: LO_SUPPKEY: optional int, 6: LO_ORDERDATE: optional int, 7: LO_ORDERPRIOTITY: optional string, 8: LO_SHIPPRIOTITY: optional int, 9: LO_QUANTITY: optional long, 10: LO_EXTENDEDPRICE: optional long, 11:....
```

**Comment by xiaotianzhang01** [comment]
@rdblue  @RussellSpitzer @danielcweeks @aokolnychyi

**Comment by xiaotianzhang01** [comment]
Is it possible to add an externally accessible caseSensitive method in the `SortOrderBuilder`

**Comment by felixYyu** [comment]
in your struct the 's_city' filed has been setted ?

**Comment by xiaotianzhang01** [comment]
> in your struct the 's_city' filed has been setted ?
yep, When I create a table, I use 'S_ CITY'

**Comment by rdblue** [comment]
Is your Spark environment case sensitive? Or are you saying that the case sensitivity is turned on for all `WRITE ORDERED BY` statements?

**Comment by xiaotianzhang01** [comment]
Some code behaves inconsistently when I set `spark.sql.caseSensitive`  to  `false`. I think it should be configured and unified by the upper-layer engine.  but i can't configure based on the `SortOrderBuilder` class
