### ISSUE TITLE
Nessie: Drop table from Nessie catalog is not cleaning the table files. 

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#3528]
<img width="904" alt="Screenshot 2021-11-10 at 10 04 50 PM" src="https://user-images.githubusercontent.com/5889404/141155046-a18b3306-ad35-4b46-8af1-5cafad0f0704.png">

Default drop table behaviour in Iceberg is to clean the files. NessieCatalog is not honouring the `purge` flag. 

Should have an implementation that queries Nessie and get the reachable snapshots for table@ref and clean the reachable files referred by the snapshots.

**Comment by ajantha-bhat** [comment]
please assign this issue to me.
cc: @rymurr

**Comment by ajantha-bhat** [comment]
we log a warning now for purge flag and we can use https://projectnessie.org/features/gc/

**Comment by shayantabrizi** [comment]
Why is that? Shouldn't it actually do the purging?
