### ISSUE TITLE
Improve iceberg site documentation.

### ISSUE THREAD

**Issue by RocMarshal** [apache/iceberg#3534]
A preliminary [plan](https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1636616737430600)(cc @rdblue ) to translate the iceberg site into Chinese as a special edition for iceberg-china developers browsing.
It would be split into two parts simply:

1. Uses mkdocs-static-i18n (recommended by @jackye1995 )  to add tab in the site UI header to switch language edition and construct the mapping mechanism for language to source page files. mkdocs-static-i18n is integrated with mkdocs-material theme features. Such as search, language switcher, and tabs.

2. Translates the corresponding pages. Give priority to Google-Translation, supplemented by  manual correction.

Looking forward to your discussion and suggestions.

Best,
Roc.

**Comment by hililiwei** [comment]
+1, If there are Chinese doc, it will be more friendly to Chinese developers.
