### ISSUE TITLE
Does iceberg plan to implement SQL to optimize the layout?

### ISSUE THREAD

**Issue by xiaotianzhang01** [apache/iceberg#3537]
eg:
```
OPTIMIZE TABLE 'example' order by c_city asc,p_brand asc OPTIONS ('target-file-size-bytes'='536870912'); 
```

This can be more convenient for verification and use

```
OPTIMIZE TABLE multipartIdentifier rewriteLayout order (OPTIONS '(' (pair (',' pair)*)? ')')? #optimizeLayout
```

**Comment by RussellSpitzer** [comment]
https://github.com/apache/iceberg/pull/3375

Currently in progress to add procedure support, we could add custom DDL as well but we should probably start first with just the procedure
