### ISSUE TITLE
Support for S3FileIO in hadoop catalog

### ISSUE THREAD

**Issue by chulucninh09** [apache/iceberg#3546]
Hi, I'm using AWS S3 with hadoop catalog for Spark without GlueCatalog.

Then I received an error `org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"`

Debugging for a while, I noticed that Hadoop Catalog is implement in a way that it will raise unknown s3 scheme exception. The problem will not happen if I use `catalog-impl=GlueCatalog`

1. To my case, I only want to use S3 with iceberg, I don't want to use GlueCatalog. How can I do that?
2. Can we make the docs more clear about dependencies and configs in aws? Happy to make PR for that.
3. If it is the problem with the implementation, can someone make a PR

Here is my code, Spark 3.1.2 with Hadoop 3.2.0. No `core-site.xml` file

```
import os
from pyspark.context import SparkContext
from pyspark import SparkConf
from pyspark.sql import SQLContext

AWS_SDK_VERSION="2.15.40"
AWS_MAVEN_GROUP="software.amazon.awssdk"
AWS_PACKAGES=[
    "bundle",
    "url-connection-client"
]
ICEBERG_VERSION="0.12.1"
DEPENDENCIES=f"org.apache.iceberg:iceberg-spark3-runtime:{ICEBERG_VERSION}"

for package in AWS_PACKAGES:
  DEPENDENCIES += f",{AWS_MAVEN_GROUP}:{package}:{AWS_SDK_VERSION}"

os.environ['PYSPARK_SUBMIT_ARGS'] = f'--packages {DEPENDENCIES} pyspark-shell'
scConf = ( SparkConf()
  .set('spark.sql.extensions','org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions')
  .set('spark.sql.catalog.my_catalog','org.apache.iceberg.spark.SparkSessionCatalog')
  .set('spark.sql.catalog.my_catalog.type','hadoop')
  .set('spark.sql.catalog.my_catalog.warehouse','s3://test-iceberg/test-iceberg-dremio4')
  .set('spark.sql.catalog.my_catalog.io-impl','org.apache.iceberg.aws.s3.S3FileIO')
  )

sc = SparkContext(conf=scConf).getOrCreate()
sc.setLogLevel("DEBUG")
sql = SQLContext(sc)

sql.sql('create table my_catalog.common.table (id bigint, data string) using iceberg')
```

And here is the log
```python
Py4JJavaError: An error occurred while calling o35.sql.
: org.apache.iceberg.exceptions.RuntimeIOException: Failed to get file system for path: s3://test-iceberg/test-iceberg-dremio4
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:53)
	at org.apache.iceberg.hadoop.HadoopCatalog.initialize(HadoopCatalog.java:103)
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:193)
	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:225)
	at org.apache.iceberg.spark.SparkCatalog.buildIcebergCatalog(SparkCatalog.java:105)
	at org.apache.iceberg.spark.SparkCatalog.initialize(SparkCatalog.java:388)
	at org.apache.iceberg.spark.SparkSessionCatalog.buildSparkCatalog(SparkSessionCatalog.java:70)
	at org.apache.iceberg.spark.SparkSessionCatalog.initialize(SparkSessionCatalog.java:246)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:61)

Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3281)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:51)
	... 70 more
```

GlueCatalog was implemented differently from HadoopCatalog, no scheme detection in GlueCatalog:
https://github.com/apache/iceberg/blob/b6ce66112bea752513d5317c0813c77ea980643a/aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java#L119-L124

HadoopCatalog has `getFs` to detect scheme and throw error:
https://github.com/apache/iceberg/blob/b6ce66112bea752513d5317c0813c77ea980643a/core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java#L102

**Comment by jackye1995** [comment]
You can use S3FileIO with Hadoop catalog by setting `io-impl` catalog property as `org.apache.iceberg.aws.s3.S3FileIO`, and it will load it instead of `HadoopFileIO`: https://github.com/apache/iceberg/blob/b6ce66112bea752513d5317c0813c77ea980643a/core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java#L104-L105.

Please let me know if this solves your issue, thanks.

**Comment by jackye1995** [comment]
I see, it looks like you want to use Hadoop catalog layout instead of just read and write data files using the s3:// scheme. These are 2 different concepts in Iceberg. The FIleIO concept is specifically used for only reading and writing files. The HadoopCatalog is a catalog implementation that relies on Hadoop file system, so if you want to have that also support s3:// scheme, just register the scheme through your Hadoop config, something like this:

https://github.com/hanborq/hadoop/blob/master/src/core/core-default.xml#L174-L178

And you can choose whatever file system implementation you like for s3://, the recommended one is https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java

**Comment by chulucninh09** [comment]
Got it, but I want to try out the new S3FileIO standalone like the doc said. 

Since there is no compatible concept & implementation between Hadoop FileSystem and Iceberg, I have to use `S3AFileSystem` instead. Can we use `s3a://` scheme in conjunction with `io-impl` to use S3FileIO?

> Iceberg allows users to write data to S3 through S3FileIO. GlueCatalog by default uses this FileIO, and other catalogs can load this FileIO using the io-impl catalog property.

https://iceberg.apache.org/#aws/#s3-fileio

**Comment by jackye1995** [comment]
You can use any other catalog with S3FileIO standalone, except for HadoopCatalog, since it requires a Hadoop FileSystem initialization.

If you have to use HadoopCatalog, then as long as you register the scheme you want to use it can work, no matter `s3://` or `s3a://`, and they can point to the same implementation class. But I actually don't recommend HadoopCatalog especially on S3, because you will have all table information shared under the same storage prefix, and S3 is throttled by prefix.

**Comment by chulucninh09** [comment]
Isn't there is `'write.object-storage.enabled'=true` config to negate S3 throttling problem? Can Hadoop Catalog use that or that only apply to Hive and Glue?

**Comment by jackye1995** [comment]
Hadoop catalog uses the file path as an indicator that a table / namespace exists. This is the internal implementation detail of the Hadoop catalog. This is equivalent to Hive using Hive metastore to store such information.

The object storage mode defines how new data files are stored in Iceberg, this is the same feature across all catalogs.

By the way, another issue with using Hadoop catalog with S3 is that S3 does not support atomic file write, but Hadoop catalog relies on the atomic write of a table version hint file to ensure transaction. So it is definitely not recommended for production usage.

**Comment by chulucninh09** [comment]
Got it now. I bet this really depends on the actual case and usage commitment.

I only use single writer with batch job style, so I feel safe to use Hadoop & S3 only since Hadoop has the most obvious implementation & layout. In case of strong consistency & atomic for multi-writer, I guess `lock-impl=DynamoDB` is enough

**Comment by cccs-mjs** [comment]
> By the way, another issue with using Hadoop catalog with S3 is that S3 does not support atomic file write, but Hadoop catalog relies on the atomic write of a table version hint file to ensure transaction. So it is definitely not recommended for production usage.

In the Iceberg docs for Spark Configuration (https://iceberg.apache.org/docs/latest/spark-configuration/#using-catalog-specific-hadoop-configuration-values) it shows using a Hadoop catalog with s3.  Is that configuration also not recommended for production usage?

> spark.sql.catalog.hadoop_prod.hadoop.fs.s3a.endpoint = http://aws-local:9000

**Comment by ahmedriza** [comment]
In the doc on [JDBC integration](https://iceberg.apache.org/docs/latest/jdbc/) we have the following
```
Class.forName("com.mysql.cj.jdbc.Driver"); // ensure JDBC driver is at runtime classpath
Map<String, String> properties = new HashMap<>();
properties.put(CatalogProperties.CATALOG_IMPL, JdbcCatalog.class.getName());
properties.put(CatalogProperties.URI, "jdbc:mysql://localhost:3306/test");
properties.put(JdbcCatalog.PROPERTY_PREFIX + "user", "admin");
properties.put(JdbcCatalog.PROPERTY_PREFIX + "password", "pass");
properties.put(CatalogProperties.WAREHOUSE_LOCATION, "s3://warehouse/path");
Configuration hadoopConf = new Configuration(); // configs if you use HadoopFileIO
JdbcCatalog catalog = CatalogUtil.buildIcebergCatalog("test_jdbc_catalog", properties, hadoopConf);
```

This configuration uses Hadoop File IO to write the warehouse data to S3.  Isn't this unsafe as well, since the actual write takes place on S3?
