### ISSUE TITLE
alter table drop partition can't use [if exists] keyword, why reason?

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#3554]
ALTER TABLE prod.db.sample DROP [if exists] PARTITION FIELD catalog
![image](https://user-images.githubusercontent.com/3785228/141734233-1b6fdafc-d09b-4d10-8263-47a37869e57e.png)

**Comment by felixYyu** [comment]
ALTER TABLE ... ADD if exsits PARTITION FIELD col also

**Comment by RussellSpitzer** [comment]
Those particles are not supported in the Spark SQL extension we use to support partition field modifications

https://github.com/apache/iceberg/blob/master/spark/v3.2/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4#L70-L71

When we switch to using the DataSourceV2 "alterPartition" capability which was recently added to Spark, we will be able to use the native grammar.

Supports Alter Partition Interface in Spark
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/java/org/apache/spark/sql/connector/catalog/SupportsPartitionManagement.java

Spark Grammar
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4#L178-L179

**Comment by felixYyu** [comment]
Will the spark SQL extension be supported in the future？

**Comment by RussellSpitzer** [comment]
Pull requests are welcome :) I think I actually saw someone working on this with "Show Partitions" support which uses the same extension point

**Comment by felixYyu** [comment]
I'm well, this PR assigne to me please. thanks Russell.

**Comment by RussellSpitzer** [comment]
Sounds good, let's close out this issue and i'll make a new one for the support drop partition.
