### ISSUE TITLE
iceberg0.12 support removing duplicate primary key all the partition or one partition? 

### ISSUE THREAD

**Issue by kaohaonan6666** [apache/iceberg#3566]
we want to remove duplicate primary key in  about 50 partitions in hive, but it only support one partitions to remove

**Comment by kbendick** [comment]
Hi @kaohaonan6666!

First, which engine are you using?

Iceberg has support for row level deletes as well as row level upserts. It possible to have a delete that's based on a key identifier as well (an equality delete, which you can roughly think of as an expression in a SQL where clause like `pk = 'Value'`.

One thing that people often do, for supporting use cases based on primary key, is use Spark SQL for `MERGE INTO`.

Such as
```sql
MERGE INTO table as T using updates as U

In general though, for existing tables, I think you'd need to write a job to delete data by row. However, Iceberg has support for row level deletes as well as row level upserts. It possible to have a delete that's based on a key identifier as well (an equality delete, which you can roughly think of as an expression in a SQL where clause like `pk = 'Value'`.

**Comment by RussellSpitzer** [comment]
In Iceberg this is done by just issuing a delete command. Under the hood this becomes a metadata only operation.
