### ISSUE TITLE
Add sequence numbers to metadata

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#358]
Row-level deletes require a way to determine whether a given delete file applies to a data file.

The scope of a delete file will be limited in 2 ways: by time and by partition. Sequence numbers will be used to implement the first. All data and delete files will be added with a sequence number and deletes apply to any data file with a sequence number less than or equal to the delete's sequence number.

**Comment by rdblue** [comment]
Yes, a delete should not be applied to a file with the same sequence number. An upsert would add a delete file and a data file with the same sequence number, one containing the row-level delete and one containing the upserted row content. Not applying deletes with the same sequence number ensures that the upsert doesn't delete itself.

**Comment by chenjunjiedada** [comment]
I would like to restart this job by myself upon https://github.com/apache/incubator-iceberg/pull/588. 

Next step are adding sequence number for manifest file in the manifest list and modifying the manifest reader.

**Comment by rdblue** [comment]
I think this is complete enough to close.
