### ISSUE TITLE
Delete File Performance in ExpireSnapshots and RemoveOrphans

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#3582]
For ExpireSnapshotAction and RemoveOrphanFile, if there are a lot of files to remove then the Spark jobs run very slow (can timeout).  

I guess current design for driver-side delete is to be prevent throttling or DDOS'ing the storage system, but I wonder if this can be made flexible.  

- Could we make a configuration to allow deletion on the Spark executors?
- Could we make a batch deleteObjects() interface in FileIO to take advantage of some faster delete methods native to different storages?  For example AWS Multi-Object Delete (1000 at a time)

**Comment by szehon-ho** [comment]
@rdblue @RussellSpitzer @aokolnychyi @jackye1995 

Would you guys have any thoughts on either or both of these ideas will be good contributions, or any other ideas?  Appreciate any thoughts

**Comment by RussellSpitzer** [comment]
There is a parameter for doing concurrent deletes from the driver, I was working with someone who had this issue and by increasing parallelism they resolved it. RemoveOrphanFiles is missing the parallelism parameter but I believe I made a ticket for it and it is being worked on. I think we should test this out to see if it’s sufficient before distributed deletes since it’s would be much easier to tune.

**Comment by rdblue** [comment]
Deleting from Spark executors is usually not a good idea because it is easy to hit S3 too hard and get throttled. Concurrent deletes on the driver makes a lot more sense to me. We'd just need to expose a way to pass a pool for deleting objects.

**Comment by szehon-ho** [comment]
Yea makes sense, thanks guys for the reply.  Look forward to having the driver parallelism in RemoveOrphans, let me know if you have the pr / issue.

It may still make sense to introduce a batch mode (the second point) to take advantage of storage-system bulk deletes?    HadoopFileSystem seems like it does not have it, but S3 does: (https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html), can save 1000 HTTP calls.  I can take a look to see if it's not too ugly to add.

**Comment by stevenzwu** [comment]
@szehon-ho +1 for the bulk deletion. It can improve the throughput without causing throttling.

**Comment by szehon-ho** [comment]
Thanks.  @RussellSpitzer is anyone working on the parallelism part?  (i couldnt find the ticket you mentioned).  If not, I was chatting with @dramaticlly about this and he could help submit a PR

**Comment by RussellSpitzer** [comment]
@szehon-ho This was added to the ExpireSnapshots procedure here https://github.com/apache/iceberg/blob/master/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java#L129-L137

In the action it's always been possible by just passing through the Executor Service, for RemoveOrphans it doesn't exist (I don't think there is a api in the action for passing through another executor service) so I think there is work to do there

**Comment by szehon-ho** [comment]
Yep, cool, so if there's no ticket, ill assign the issue for now to @dramaticlly
