### ISSUE TITLE
Duplicate records with primary key in iceberg 0.12.0 when use flinkSQL

### ISSUE THREAD

**Issue by fengsen-neu** [apache/iceberg#3599]
Flink 1.12.1  iceberg 0.12.0
![image](https://user-images.githubusercontent.com/58256617/143039161-0d9eaf32-e8a9-4086-b357-8a9efd5c0736.png)
![image](https://user-images.githubusercontent.com/58256617/143039409-aea35b22-7cdc-452c-acbc-16ecabd2efbd.png)

I found duplicate records with primary key in iceberg 0.12.0. Does Iceberg currently not support duplicate data removal across snapshots? Is there any plan for the future or is there any PR about it?

**Comment by Reo-LEI** [comment]
Is this table created under the Iceberg catalog? From the result, this looks like a normal flink table. Can you post the complete SQL statement? @fengsen-neu

**Comment by fengsen-neu** [comment]
> Is this table created under the Iceberg catalog? From the result, this looks like a normal flink table. Can you post the complete SQL statement? @fengsen-neu
![image](https://user-images.githubusercontent.com/58256617/143232615-9e39e61f-11fb-4f7a-89ea-9cca37222cfe.png)
![image](https://user-images.githubusercontent.com/58256617/143232951-6924d868-be78-466f-a4d7-42cf08567110.png)

**Comment by fengsen-neu** [comment]
Don't the primary key contain unique constraints within the same partition or snapshot? if not, what't the primary key used for?

**Comment by openinx** [comment]
@fengsen-neu ,  You will need to make sure those PR got merged in your flink-iceberg-runtime libarary [1], [2]. And enable the switch `write.upsert.enabled=true`.   It will recommend to use the apache iceberg master branch to build the runtime library.

[1]. https://github.com/apache/iceberg/pull/3504/files#diff-5620e28d3a7d13259b12e251b9eca2f59c66fd3ab96d6b62c36062f1f5ac0ca1R251
[2]. https://github.com/apache/iceberg/pull/2863

**Comment by fengsen-neu** [comment]
> @fengsen-neu , You will need to make sure those PR got merged in your flink-iceberg-runtime libarary [1], [2]. And enable the switch `write.upsert.enabled=true`. It will recommend to use the apache iceberg master branch to build the runtime library.
> 
> [1]. https://github.com/apache/iceberg/pull/3504/files#diff-5620e28d3a7d13259b12e251b9eca2f59c66fd3ab96d6b62c36062f1f5ac0ca1R251 [2]. #2863

@openinx Thank you very much, it works.
