### ISSUE TITLE
Why use DistributionAndOrderingUtils$ to import?

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#3615]
in Spark3SortStrategy class file
import org.apache.spark.sql.catalyst.utils.DistributionAndOrderingUtils$;
protected LogicalPlan sortPlan(Distribution distribution, SortOrder[] ordering, LogicalPlan plan, SQLConf conf) {
    return DistributionAndOrderingUtils$.MODULE$.prepareQuery(distribution, ordering, plan, conf);
}
'$' has been used, why
------------------------------------------------------------------------------------------------------------
import org.apache.spark.sql.catalyst.utils.DistributionAndOrderingUtils;
protected LogicalPlan sortPlan(Distribution distribution, SortOrder[] ordering, LogicalPlan plan, SQLConf conf) {
    return DistributionAndOrderingUtils.prepareQuery(distribution, ordering, plan, conf);
}
this format is also right?

**Comment by felixYyu** [comment]
cc @rdblue @RussellSpitzer

**Comment by RussellSpitzer** [comment]
This is one of those fun things about Java Scala interoperability. Scala compiles .scala files into several Java classes depending on their usage. Singleton's and Static methods end up getting placed in a Class$.MODULE$ java class, so if we want to access the methods from a Scala `object` we need to use these weird $'s. I'm not sure if there is a way to make Scala compile it into a singleton with the same class name without $ but I just always use $.MODULE$ when I'm interoperating with Scala singletons from Java.

**Comment by felixYyu** [comment]
thanks Russell replay, I get.
