### ISSUE TITLE
Proposal: Switch docs site from mkdocs to hugo and relocate to a separate iceberg-docs repo

### ISSUE THREAD

**Issue by samredai** [apache/iceberg#3616]
This is a follow up to PR #3378 which at its core was a mkdocs proposal on how to achieve versioned docs. Since then I've been doing a comparison of other static site frameworks to see if any can provide a significant improvement over mkdocs. I think [hugo](https://gohugo.io/) is a big winner here and I was able to get a hugo version of the site up very quickly with a landing page and versioning, all without much fuss.

A separate but related proposal is to separate the docs out into their own iceberg-docs repo. To achieve versioned docs, it requires a custom deployment workflow that pushes branches automatically to the gh-pages branch (which we would change to the asf-site branch in an apache/iceberg-docs repo). However having this in the same repo as the source code could be noisy.

Here is the prototype site that I put together in my personal repo so everyone could check it out: https://samredai.github.io/iceberg-docs-prototype/latest/

There are still some things that need to be cleaned up such as replacing the mkdocs variables with hugo variables in all of the markdown pages. If you go to docs part of the site and scroll down to the "Releases" section on the left, you can see what looking at a previous version site looks like. A trivial thing to add here would be top level banners for older versions that let the user know "You are not looking at the documentation for the latest version of Iceberg."

https://user-images.githubusercontent.com/43911210/143689701-4e05fdd4-dd89-4741-9e89-917a92d0d86a.mp4

**Comment by ajantha-bhat** [comment]
> A separate but related proposal is to separate the docs out into their own iceberg-docs repo.

Regarding this, If we move the docs to separate repo. It may be difficult to synchronise the code PR and doc PR. Merging also is extra effort. Some dev may forget to raise doc PR. 

So, Is it possible to keep the docs currently where it is and separate repo will import *.md files from main repo and build site docs from some github actions ?

**Comment by samredai** [comment]
@ajantha-bhat I covered this a bit in my reply to Jack on the dev mailing list. We definitely could keep the docs as part of the main repo but there's extra effort on that end as well. The main one being that we'd need to align the branching pattern of the source code with the doc site versioning (`0.12.0` and `0.12.1` branches instead of `0.12.x`, for example). If we go with a separate repo, we would still maintain a copy of the docs in the main repo, and a release of a new iceberg version would include a process of pushing the docs directory to the `iceberg-docs` repo in a branch that matches the version number (we could automate that). The only time commits directly to the iceberg-docs would be required is to fix parts of the previously released versions.

There are definitely pros and cons to either direction so a healthy discussion around this would be great. (Although I know this has already been explored in previous convos)

**Comment by samredai** [comment]
Closing this since it's completed. The docs have been moved to https://github.com/apache/iceberg-docs
