### ISSUE TITLE
can not change nullable via Spark SQL sometimes

### ISSUE THREAD

**Issue by Initial-neko** [apache/iceberg#3617]
When a field is nullable, SparkSQL cannot change this field to (not null)

refer to this SQL:

```
create table test_null2 (id INT NOT NULL, data int, data2 int) using iceberg;
alter table test_null2 alter column id set not null; 
alter table test_null2 alter column id drop not null;
alter table test_null2 alter column id set not null;  (error)
alter table test_null2 alter column data set not null;(error)
```

this is an empty table, Moreover, iceberg can support schema changes
I can change this though iceberg API like this：

`table.updateSchema().allowIncompatibleChanges().requireColumn("data").commit();`
can someone know how to use SQL changing this field null property？

**Comment by rajarshisarkar** [comment]
Seems like Spark has a validation in `CheckAnalysis` to restrict changing nullable column to non-nullable.

https://github.com/apache/spark/blob/5d45a415f3a29898d92380380cfd82bfc7f579ea/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckAnalysis.scala#L1009-L1013

**Comment by Initial-neko** [comment]
> 

This operation may be unsafe if not used properly，I get answer from slack。

Daniel Weeks ：**This is a bit of an edge case and while you could technically support deeper inspection of the data to allow those modifications, it currently isn't supported.  The API does allow for a workaround, but that can be problematic if used incorrectly.**
