### ISSUE TITLE
Add checkstyle rule to prevent using raw HashMap, HashSet, ArrayList

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3657]
For project code consistency, we should add checkstyle rules that prevent the use of raw `new HashMap<>`, `new HashSet<>()` and `new ArrayList<>` in favor of `Maps.newHashMap()`, `Sets.newHashSet()` and `Lists.newArrayList()`

**Comment by hililiwei** [comment]
I'd like to try it. May I have the ticket?

**Comment by jackye1995** [comment]
assigned!

**Comment by hililiwei** [comment]
merged master: 2531545e3cd3b97494c9e3c137cfe04f4459a9fb

**Comment by felixYyu** [comment]
can you take a look the patch. cc @jackye1995
