### ISSUE TITLE
Split_Offset Information is not Included when Reading Manifests for Planning

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#3662]
DataTableScan requires the following columns passed to ManifestGroup when reading Manifests to create scan tasks

https://github.com/apache/iceberg/blob/97055c4114d396eeef24d8280006984b1c2cb306/core/src/main/java/org/apache/iceberg/DataTableScan.java#L31-L34

Missing from this is "split_offsets" which means ScanTasks created from these manifest entries will not have any SplitInformation. While I think this worked previously because of bugs in our Avro Pruning code

https://github.com/apache/iceberg/issues/1735

I think we are now having issues because the select is working as it should which also unfortunately means split_offset information is not populated.

I also think we lack any explicit tests for making sure split offset information is being used (or read) during split planning. I discovered the current issue when I noticed my test suite for #3292 started failing which requires split_offset information to function properly.

**Comment by jackye1995** [comment]
Thanks for investigating this Russell, I think this is a pretty important bug we need to fix before 0.13, please let me know if you have time, if not I can publish the fix. If my understanding is correct, do we add the `split_offsets` to `SCAN_COLUMNS` and also add tests related to this?

**Comment by RussellSpitzer** [comment]
I have the fix and tests, just waiting for internal approval to put it upstream.

**Comment by RussellSpitzer** [comment]
Additionally I would like us to fix the other issues in #3292 that I note but i'll leave that for another PR.

1. We allow arbitrary splitting of formats that are splittable if they are missing split information (A parquet file with a single row group can be turned into infinite tasks)
2. We do not allow combining partial scans into a single scan task. For example, if I have 3 files each with 2 row groups, but my read split size is 3 row groups large, I will still get 3 tasks even if file open cost is 0.

**Comment by RussellSpitzer** [comment]
@jackye1995 ^ Fix attached

**Comment by rdblue** [comment]
@RussellSpitzer, I'm going to review #3292 again this weekend. Thanks for being patient with my reviews on that one!

**Comment by RussellSpitzer** [comment]
No rush, I need to fix this first and rebase
