### ISSUE TITLE
Add documentation about Iceberg config naming convention

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3678]
See #3659 for more details, we should add some guidelines about the config naming conventions.

**Comment by hililiwei** [comment]
What does this naming convention look like? Which section do we want to add this to?

**Comment by jackye1995** [comment]
The 2 rules mentioned in the linked PR were:
1. `-` is used to link words at the same level, e.g. prefer `access-key-id` over `access.key.id`
2. `.` is used to create sublevels and group similar configs, e.g. `s3.access-key-id`, `s3.secret-access-key`

I think a good place to put it is at https://github.com/apache/iceberg/blob/master/CONTRIBUTING.md

**Comment by sanyud24** [comment]
Hi , I would like to work on this issue !! can I get it assigned

**Comment by jackye1995** [comment]
thanks, assigned!
