### ISSUE TITLE
Should the specified number of data be added as the partition transform for data with a large amount of data and that will continue to increase with id as the primary key?

### ISSUE THREAD

**Issue by xloya** [apache/iceberg#3682]
I have a question with the extremely large amount of data written into Iceberg: we have a scenario where 2 billion data need to be written to Iceberg, and CDC datas need to be consumed through Flink. These data have only Long type auto-increment id as the primary key, and it is likely to swell to 4 billion data in the future.  
I took a look at the current partition transforms, and it seems that it is not very suitable for this kind of non-temporal primary key scenario with a large amount of data that needs to be updated.  
Can we use the specified number of data as the partition transform to partition by the auto-increment primary key? Or do you have any better solutions for reference? Thanks!
cc @rdblue @kbendick @jackye1995 @RussellSpitzer

**Comment by xloya** [comment]
For example, we can partition with 500,000 pieces of data as a threshold, and write the data corresponding to the id into the corresponding partition.

**Comment by jackye1995** [comment]
> For example, we can partition with 500,000 pieces of data as a threshold, and write the data corresponding to the id into the corresponding partition. The data's id between 1 - 500,000 will be written into partition_1, and the data's id between 500,001 - 1,000,000 will be written into partition_2, and so on.

This sounds like you want to have your data range-partitioned. Would `truncate` transform solve the issue?

**Comment by xloya** [comment]
> > For example, we can partition with 500,000 pieces of data as a threshold, and write the data corresponding to the id into the corresponding partition. The data's id between 1 - 500,000 will be written into partition_1, and the data's id between 500,001 - 1,000,000 will be written into partition_2, and so on.
> 
> This sounds like you want to have your data range-partitioned. Would `truncate` transform solve the issue?

Hey jack, thx for reply! I misunderstood the function of truncate transform, it is indeed feasible after actual testing, thanks!
