### ISSUE TITLE
Spark: We should probably say why we cannot process the snapshot in SparkMicroBatchStream

### ISSUE THREAD

**Issue by rajarshisarkar** [apache/iceberg#3699]
We should probably say why we cannot process the snapshot here:

https://github.com/apache/iceberg/blob/cbf56a336531c6b216f8261843d86d4355a5aba9/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java#L201-L209

**Comment by jackye1995** [comment]
@rajarshisarkar would you like to add the documentation?

**Comment by rajarshisarkar** [comment]
Yes, documentation would be better. @RussellSpitzer Any thoughts?

**Comment by RussellSpitzer** [comment]
I think we should change the exception and add documentation. Exception should probably be "Cannot process snapshot, Structured Streaming does not support snapshots of type X"
