### ISSUE TITLE
Slove the problem that failed to remove the data files  when using HiveCatalog.dropTable

### ISSUE THREAD

**Issue by alexkingli** [apache/iceberg#3726]
When using HiveCatalog.dropTable, we found that dropping successfully  in metastore but failed to remove the data files，it is caused by no permission to delete the hdfs files of iceberg table。Then we use the account with permissions to delete this table again,   it is still failed to delete the HDFS file. We think the reason is that this iceberg table‘s metadata in metastore are deleted successfully during the first operation, it will find table does not exist and don't delete data files when we delete again .

**Comment by alexkingli** [comment]
I make a pull request to fix this problem. https://github.com/apache/iceberg/pull/3730

**Comment by kbendick** [comment]
Have you tested with a table that hadn't been dropped, where the full permissions were there? Did that work as expected?

For your case, where there were orphaned files from a lack of permissions, we have a spark procedure for that `RemoveReachableFIles`. There's a PR open right now to make it into a Spark SQL `CALL` styled stored procedure.

**Comment by alexkingli** [comment]
> Have you tested with a table that hadn't been dropped, where the full permissions were there? Did that work as expected?
> 
> For your case, where there were orphaned files from a lack of permissions, we have a spark procedure for that `RemoveReachableFIles`. There's a PR open right now to make it into a Spark SQL `CALL` styled stored procedure.

It wil work well if we drop table by using the user with permissions. Now I use the hadoop command to delete these unuseful files first.  It is a good idea to make RemoveReachableFIles into a Spark SQL CALL styled stored procedure. Thanks.
