### ISSUE TITLE
Problem of data overflow when convert Integer to Long

### ISSUE THREAD

**Issue by chenzihao5** [apache/iceberg#3738]
I met a problem of data overflow when writer a data whose type is java.sql.Time. After debug, I find the root problem that cause by converting Integer to Long In FlinkValueWriters.

before:
![image](https://user-images.githubusercontent.com/38340392/145926044-3db8678e-57cf-4038-b2e7-5ccbc2c79295.png)
after:
![image](https://user-images.githubusercontent.com/38340392/145926109-0bfe16af-2cad-412b-a4a9-5bcdab45532a.png)

@openinx @JingsongLi Please help confirm this problem, Thanks.

**Comment by rdblue** [comment]
Fixed by #3740.
