### ISSUE TITLE
[Improvement] ParallelIterable#hasNext submit reading ManifestFile task slowly with DataTableScan#planTasks

### ISSUE THREAD

**Issue by yohengyang** [apache/iceberg#3741]
This Issuse manily to speed up reading `Iterator<FileScanTask>` with planTasks.

### Background
We use trino to query icebergTable,  but same query are sometimes very slow in scheduling stage. 
Using Arthas,  finally positioned to `fileScanTasks.hasNext()`  in [`io.trino.plugin.iceberg.IcebergSplitSource#getNextBatch`](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java)
This method traverse `Iterator<FileScanTask>` to get IcebergSplit .
![image](https://user-images.githubusercontent.com/39874737/145963998-73330aec-2bc0-4b06-b950-7b8146442b60.png)

`fileScanTasks` generated by `DataTableScan.planTasks,`  when called `ParallelIterable.hasNext()`,  it should parallel submiting Runnable task to workPool ,  but when called `tasks.next()`,  it will reading manifest firstly.  
When Hdfs has bad performance, this step will take too many time to stuck submitTask.
So,  it's better to put reading manifest step into Runnable rather than `Iterables.transform()` in `ManifestGroup#entries`.

![image](https://user-images.githubusercontent.com/39874737/145956804-0d466e40-6877-4c35-baa9-cb3255474700.png)

Through profile,  we can sure that` ManifestFiles.read()` and `ManifestReader.entries()` reading avro file from the hdfs.
![image](https://user-images.githubusercontent.com/39874737/145945692-d8b03971-80f0-4ba7-8ee5-1740d6d7dfbd.png)

### Reslove
I’m not familiar with iceberg. I provide a rewrite idea which may not right. Hoping everyone can help to improve it. Thanks all !
https://github.com/apache/iceberg/pull/3742

### Test Performence
Query the same sql 100 times per test, the sql read 47 arvo file,
Count trino scheduling time

![image](https://user-images.githubusercontent.com/39874737/145999989-b955d29f-189e-4690-a1dd-ad8d4eaa8db3.png)

**Comment by liupan664021** [comment]
I met the same problem with you when using iceberg connector in presto. The `ManifestFiles.read()` is executed serially can significantly slow down the plan if manifest file is masssive. And I made similar fix as you but I haven't test the performance improvement yet. I think delaying the `ManifestFiles.read()` to parallel threads is quite reasonable.

**Comment by yohengyangyang** [comment]
@liupan664021 aswome thks for suggestion~ , i make both ManifestFiles.read() and ManifestReader.entries() to parallel threads ，we have use this patch on our online cluster, but

**Comment by RussellSpitzer** [comment]
I'm confused about the task.next(), issue. From what I can see task.next should be checking the parallel iterable queue which starts by calling hasNext which repopulates the queue if it has any empty slots. It populates these slots with a runnable of the entry in the iterable.

https://github.com/apache/iceberg/blob/f71091539e1fa9e4064cfbc5141fe3e890e1a5f0/core/src/main/java/org/apache/iceberg/util/ParallelIterable.java#L63-L73

Also has anyone checked to see whether just increasing the parallelism of the work pool would work?

**Comment by yohengyangyang** [comment]
@RussellSpitzer add some log 
` private <T> Iterable<CloseableIterable<T>> entries(
      BiFunction<ManifestFile, CloseableIterable<ManifestEntry<DataFile>>, CloseableIterable<T>> entryFn) {
    long start = System.currentTimeMillis();
   // ……
    Iterable<CloseableIterable<T>> res = Iterables.transform(
        matchingManifests,
        manifest -> {
          long start2 = System.currentTimeMillis();
          ManifestReader<DataFile> reader = ManifestFiles.read(manifest, io, specsById)
              .filterRows(dataFilter)
              .filterPartitions(partitionFilter)
              .caseSensitive(caseSensitive)
              .select(columns);

          CloseableIterable<ManifestEntry<DataFile>> entries = reader.entries();
          if (ignoreDeleted) {
            entries = reader.liveEntries();
          }

          if (ignoreExisting) {
            entries = CloseableIterable.filter(entries,
                entry -> entry.status() != ManifestEntry.Status.EXISTING);
          }

          if (evaluator != null) {
            entries = CloseableIterable.filter(entries,
                entry -> evaluator.eval((GenericDataFile) entry.file()));
          }

          entries = CloseableIterable.filter(entries, manifestEntryPredicate);
          CloseableIterable<T> res2 = entryFn.apply(manifest, entries);
          long end2 = System.currentTimeMillis();
          LOG.info("transform_time: {}", end2 - start2);
          return res2;
        });
    long end = System.currentTimeMillis();
    LOG.info("entries_time: {}", end - start);
    return res;
  }`

**Comment by rdblue** [comment]
It sounds like this just wants to move the `transform` call in `ManifestGroup` into the tasks that execute in parallel. That sounds reasonable to me. I'll went to take a look at this PR, but there were changes that were unrelated. Once those are removed, I'll have another look.

Thanks for working on this, @yohengyang!

**Comment by yohengyang** [comment]
long time no see, https://github.com/apache/iceberg/pull/5206
