### ISSUE TITLE
current master branch can't run "./gradlew idea", caused by "Cannot infer Scala class path because no Scala library Jar was found. "

### ISSUE THREAD

**Issue by KarlManong** [apache/iceberg#3762]
Running "./gradlew idea" failed on master branch commit a2260faa

> * What went wrong:
Execution failed for task ':ideaProject'.
> Cannot infer Scala class path because no Scala library Jar was found. Does project ':iceberg-aliyun' declare dependency to scala-library? 

The problem was caused by `apply plugin: 'com.github.alisiikh.scalastyle'` at `baseline.gradle`.

Will you please fix this?

**Comment by hililiwei** [comment]
hi @nastra ,cloud you please take a look?  `'com.github.alisiikh.scalastyle'`  seems to block './gradlew idea'.

**Comment by nastra** [comment]
I'm ooo until Jan 10, but will take a look once I'm back
