### ISSUE TITLE
flink iceberg catalog support hadoop-conf-dir option to read hadoop conf?

### ISSUE THREAD

**Issue by moon-fall** [apache/iceberg#3788]

**Comment by ZhangChaoming** [comment]
@moon-fall Perhaps you can try to set HADOOP_CONF_DIR to specify hadoop conf in your flink runtime.

**Comment by moon-fall** [comment]
@ZhangChaoming  
A major problem is that when create a table through the flick SQL client, if you do not set Hadoop_ CONF_ Dir in the environment variable, but  use  hive as a catalog  point to HDFS with dfs.nameservices , will report an error unknownhostexception. In flink, hivecatalog supports Hadoop conf dir option to configure the configuration file of each catalog separately.
https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/connectors/table/hive/overview/#:~:text=hadoop%2Dconf%2Ddir,each%20HiveCatalog%20separately.
but flink iceberg catalog has no this option ? I think it is more convenient to add new cluster configuration
