### ISSUE TITLE
Drop managed table after drop data

### ISSUE THREAD

**Issue by jotarada** [apache/iceberg#3792]
If somehow data is deleted from files there is some way to drop table from the metastore?

Using spark or trino to to drop the table always led to this exception:

```
Failed to open input stream for file: <deleted-files-location>/metadata/<someuuid>.metadata.json
```

Is there any workaround to fix this?

**Comment by flyrain** [comment]
As a workaround, you can uses the the metastore APIs to drop the table? For HMS, you can fire a hive cli or a Hive Java API to do that.
