### ISSUE TITLE
In flinksql, there is a problem of partial updating of wide table fields

### ISSUE THREAD

**Issue by Initial-neko** [apache/iceberg#3814]
now:
```
+----+-------+-------+
| id | data1 | data2 |
+----+-------+-------+
|  1 |     2 |     3 |
|  2 |     3 |     4 |
+----+-------+-------+
```

insert INTO table（id,data1）values(1,3)

```
result：
+----+-------+-------+
| id | data1 | data2 |
+----+-------+-------+
|  1 |     3 |     null |
|  2 |     3 |     4 |
+----+-------+-------+
```

However, if I want to keep other fields unchanged and just update the specified field, I need to read this row of data. 
Can someone give me some advice，How can I read it gracefully? Thanks！
insert INTO table（id,data1）values(1,3)
result like that
```
+----+-------+-------+
| id | data1 | data2 |
+----+-------+-------+
|  1 |     3 |     3 |
|  2 |     3 |     4 |
+----+-------+-------+
```

At present, my idea is to build a read request somewhere, but I don't know where to build such a request

**Comment by ZhangChaoming** [comment]
@Initial-neko IMO, set the column value of `data2` to `null` is within expectation. Perhaps you can try like this:
```sql
INSERT INTO t SELECT id, 3, data2 FROM t WHERE id = 1;
```

**Comment by Initial-neko** [comment]
> 
Thanks！It works

**Comment by kbendick** [comment]
It seems that this has been solved. I'm going to close this issue. Please feel free to open a new issue if you have any more questions!

And thank you @ZhangChaoming for providing support!
