### ISSUE TITLE
Need an exmple of java code that uses hive as meta store and s3.

### ISSUE THREAD

**Issue by zeromsi** [apache/iceberg#3825]
I'm really struggling to get started with Java api's. If anyone got an example code , please share with me! 
Thanks

**Comment by RussellSpitzer** [comment]
What would you like an example of the Java API doing? There are a large number of tests in the repository which I usually use as a fallback when I forget how something works. What specifically are you looking for?

**Comment by zeromsi** [comment]
@RussellSpitzer  Thanks for your reply. I Need an working maven dependency. Can You help me on that?

**Comment by kyle-cx** [comment]
@zeromsi Is your problem solved, need help anymore ?

**Comment by RussellSpitzer** [comment]
@zeromsi all the artifacts are https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-core/0.13.1
Sorry I didn't see the reply back then. Depending on what you want to use you may need other modules as well but they are all there
