### ISSUE TITLE
Docs: ('format-version' = '2') option should be described in create table sections

### ISSUE THREAD

**Issue by samredai** [apache/iceberg#3832]
A recent slack thread ([here](https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1640599048329900)) revealed that the create table DDL docs don't include instructions on how to create a table that uses the v2 Iceberg spec. (Also thanks @ajreid21 for mentioning this). Additionally, I don't think it's clearly specified anywhere that tables are v1 by default.

**Comment by ajantha-bhat** [comment]
@samredai : few days ago, I have raised PR for the same. Please have a look.
https://github.com/apache/iceberg/pull/3809

**Comment by samredai** [comment]
Thanks @ajantha-bhat ! I'll close this one then.
