### ISSUE TITLE
Need a working maven dependency 

### ISSUE THREAD

**Issue by zeromsi** [apache/iceberg#3835]
I'm using hive metastore, s3 , spark to create table. Getting ```NoClassDefFoundError``` again and again. Can anyone help me by providing a working pom.xml file?

**Comment by youngxinler** [comment]
NoClassDefFoundError usually has a class conflict in the project, you can check whether the relevant dependencies of the project are repeatedly introduced.
if no relevant dependencies are introduced, the error that appears is ClassNotFoundException. @zeromsi

**Comment by flyrain** [comment]
It'd be better to provide more details to get help. Something like a full stack trace, what did you do to trigger the issue.
