### ISSUE TITLE
How to use Hilbert curves feature?

### ISSUE THREAD

**Issue by RohitR1** [apache/iceberg#3836]
Z-Ordering helps to optimize high cardinality columns by colocating related information in a similar set of files
How to use these features with Iceberg tables?

**Comment by ajantha-bhat** [comment]
@RohitR1 :
It is not available in the iceberg yet.
It is in the roadmap.
https://docs.google.com/document/d/1UfGxaB7qlrGzzMk9pBm03oKPOkm-jk-NQVQQvHP-0Bc/edit
