### ISSUE TITLE
Python library feature request: check_for_partition api

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#3843]
I am requesting for a `check_for_partition` api in the python library.

We currently use apache airflow's HiveParitionSensor heavily to monitor the arrival of a partition for an upstream table. When migrating these tables to Iceberg, the existing way no longer works.

It will be great if we can have capabilities for python library to check whether a partition/ multi-partition exist. This will open up opportunity for iceberg integration with apache airflow.

**Comment by krisdas** [comment]
We encountered same problem and couldn't find a good solution. So we wrote some hacky code, which needs to be called by the client repeatedly after specific interval (essentially pull model). In the hacky code, we simply check, whether the asked partition exists or not, by running a query like "select count(*) where partition=input partition" and checking if the count is > 0.

This hacky code was not written in python but just as a console scala app, which can be called easily from airflow using bash operator.
