### ISSUE TITLE
Docs: Add an example of CTAS with PARTITIONED BY

### ISSUE THREAD

**Issue by samredai** [apache/iceberg#3854]
The docs should include an example of using PARTITIONED BY in a CTAS statement (such as in [this ](https://github.com/apache/iceberg/blob/master/spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java#L45-L46)test). It may not be clear to a user that they can do this and would be useful to highlight in the docs that describe CTAS.

**Comment by hililiwei** [comment]
Doc seems to have been added here: https://iceberg.apache.org/#spark-ddl/#partitioned-by

**Comment by kyle-cx** [comment]
hi @samredai , I guess you didn't see the latest page, we already got an explicit example of CATS now.

![image](https://user-images.githubusercontent.com/10529123/164352332-e86ca3dd-7025-441b-b4f3-d01141cf742c.png)

**Comment by kyle-cx** [comment]
> I'm specifically referring to one that includes PARTITIONED BY. The reason I opened this issue is because someone told me they weren't aware they could add a partition spec as part of their CTAS statement.
> 
> We can either add a sentence there or include PARTITIONED BY (similar to the RTAS statement right below it).

got u
