### ISSUE TITLE
A bug for Structed Streaming micro_batch read iceberg table

### ISSUE THREAD

**Issue by flyxu1991** [apache/iceberg#3859]
Structed Streaming read iceberg table will report NullPointerException when iceberg table was expired snapshot.
public StreamingOffset initialOffset() {
    InputFile inputFile = this.io.newInputFile(this.initialOffsetLocation);
    if (inputFile.exists()) {
        return this.readOffset(inputFile);
    } else {
        this.table.refresh();
        StreamingOffset offset = this.table.currentSnapshot() == null ? StreamingOffset.START_OFFSET : new StreamingOffset(SnapshotUtil.oldestSnapshot(this.table).snapshotId(), 0L, false);
        OutputFile outputFile = this.io.newOutputFile(this.initialOffsetLocation);
        this.writeOffset(offset, outputFile);
        return offset;
    }
}

public static Snapshot oldestSnapshot(Table table) {
    Snapshot current;
    for(current = table.currentSnapshot(); current != null && current.parentId() != null; current = table.snapshot(current.parentId())) {
    return current;
}

parentId exists while the meta and data file was deleted, i'd like to fix code like this:
StreamingOffset offset = this.table.currentSnapshot() == null ? StreamingOffset.START_OFFSET : this.table.currentSnapshot();

@SreeramGarlapati

**Comment by SreeramGarlapati** [comment]
@flyxu1991 - I see that you closed this issue - did any discussion happen on this? pl. let me know how you are handling this case?
