### ISSUE TITLE
Support time travel with the partition evolution

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#3860]
Currently snapshot spec is having only schema-id and it is used for the time travel.
Similarly we need a spec change for partition-spec-id inside snapshot and then use that for time travel. 

I want to work on this in my free time. Please assign this issue to me.

cc: @rdblue , @jackye1995 , @openinx

**Comment by PiyushHurpadeDremio** [comment]
Valid set of partition-spec-id's for a snapshot will be right requirement.
