### ISSUE TITLE
question on using iceberg with KMS through IAM role

### ISSUE THREAD

**Issue by sgedward** [apache/iceberg#3886]
Hi everyone,

I am new to iceberg,  we are trying to use iceberg to replace our current storage format. We encrypt customer data at rest with a customer-provided key using AWS KMS service in S3 using SSE-KMS custom key. One of the challenges is we assume customers' KMS permission through the IAM role in order to access data in S3. Our role and KMS key is 1 to 1 mapping. Thus, every time we access different customer data in S3, we will need to use different IAM roles. Does the iceberg support a customized IAM role for the S3 client when doing `S3FileIO`? If not, is there any workaround solution? Thanks!

**Comment by joshua-yeung-mox** [comment]
Hi @sgedward , how did you solve this issue?
