### ISSUE TITLE
Clarify usage of ValidationException vs IllegalArgumentException

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3895]
based on https://github.com/apache/iceberg/pull/3104#discussion_r780844208

I did not have a good way to distinguish what exception to use for what case, the definition provided by Ryan was clear. I think we should add that in the javadoc of `ValidationException` class about when to use it and when to use `Preconditions` to throw illegal argument exception.

This will give more clarity to both implementer and reviewer.

**Comment by sanyud24** [comment]
May I work on this issue @jackye1995

**Comment by molsionmo** [comment]
Is it over?
