### ISSUE TITLE
Deprecate TableMetadata.removeSnapshotsIf in favor of metadata builder

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3900]
based on https://github.com/apache/iceberg/pull/3104/files/7fe760e534bd34a1affe6e8f989f6b31b59e71aa#r780846388

**Comment by amogh-jahagirdar** [comment]
After https://github.com/apache/iceberg/pull/3883 gets closed, I'll raise a PR for this that I have ready. I am planning on deprecating the existing TableMetadata#removeSnapshotsIf and adding the a new removeSnapshots method which simply accepts a set of snapshot ids to remove. It will do validation that the set of snapshot ids passed in does not contain the latest snapshot id. Something like the following.

`  public TableMetadata removeSnapshots(Set<Long> snapshotIdsToRemove) {
    ValidationException.check(!snapshotIdsToRemove.contains(currentSnapshotId),
        String.format("Cannot remove the latest snapshot id: %d", currentSnapshotId));
    return new Builder(this)
        .removeSnapshots(snapshotIdsToRemove)
        .build();
  }`

**Comment by amogh-jahagirdar** [comment]
As a follow up, I think in the scope of the API we should also make sure we are cleaning up any references as well, as to prevent a "corrupt" state of TableMetadata. So if snapshot 2 is to be removed and there are references to snapshot 2, within this API we should also remove those references. This way we don't have any dangling references. We could also filter and not remove any snapshots which have references in this method, and then force callers to remove references first and then the snapshot ids. This seems like too much work for callers, and to me is not as intuitive. Let me know your thoughts.

**Comment by jackye1995** [comment]
Overall there are 3 use cases:
1. filter snapshots with ref and skip removal of those
2. throw exception if a snapshot to remove has ref
3. directly remove snapshot and its associated refs

Consider the use case if this method, it is basically used for snapshot expiration and nothing else. The logic is:

```java
    TableMetadata updateMeta = base.removeSnapshotsIf(snapshot ->
        idsToRemove.contains(snapshot.snapshotId()) ||
        (snapshot.timestampMillis() < expireOlderThan && !idsToRetain.contains(snapshot.snapshotId())));
```

When we add branching and tagging, we will have a much more complex if statement to filter out snapshots, and we should be sure that the snapshots passed into the method are the ones we truly want to remove. The snapshot might have associated refs, but removing the refs along the way seems like the correct choice, so that we don't need to have another operation like `RemoveSnapshotRef` to clean those things up.

Based on this, I think option 3 makes sense to me at this point of time based on the use case.

This is also not a one way door, we can always add a flag to achieve 1 or 2 in the future if that is absolutely needed, but it should be simpler to enforce that requirement before the information is passed into the method.
