### ISSUE TITLE
Support time travel to a snapshot by ref name

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#3901]
Allow users to specify a snapshot name instead of ID to time travel to. For example, if a process produces daily snapshot and tag it with the date, then I can time travel back to the snapshot by specifying the date name instead of a timestamp/snapshot ID. By doing so I can optimize the specific snapshot (e.g. compaction) and just update the tag to improve performance, and the query does not need to change.

**Comment by zhangminglei** [comment]
@jackye1995  Is there any progress on this so far ?
