### ISSUE TITLE
Make retry number and backoff policy configurable

### ISSUE THREAD

**Issue by timothy-khom** [apache/iceberg#3903]
Hi colleagues,
Could the hard-coded value of numRetries at https://github.com/apache/iceberg/blob/0.12.x/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L160 and backoff policy at https://github.com/apache/iceberg/blob/0.12.x/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L175 be specified via configuration somehow? When there is an intermittent network issue or so it is usually enough to retry less times. Otherwise, for instance if there is a stale information in metadata for some reason and the underlying files do not exist this retry mechanism causes overall process to “stuck” for 10 mins unnecessarily retrying the read operation.

**Comment by szehon-ho** [comment]
Hi,I think this is solved by https://github.com/apache/iceberg/pull/3099, (you can pass the relevant configs now  supported by RetryingHiveMetaStoreClient) can you check?

**Comment by timothy-khom** [comment]
Hi @szehon-ho,
Thank you for suggestion. However it seems it will be available in 0.13.x won't it ?

**Comment by szehon-ho** [comment]
Yea i think in current versions there is no good way I could find, unfortunately.
