### ISSUE TITLE
When we use spark action rewriteDataFiles, how to limit equality_delete file compations memory.

### ISSUE THREAD

**Issue by fengsen-neu** [apache/iceberg#3909]
When we use spark action rewriteDataFiles on v2 table, we will also merge equality_delete file with data file.  The equality_delete file will merge with all data file that sequence num less than it, this will cause spark executor memory GC frequently, and cause 'connection reset by peer' , ' hearbeat timeout' error during rewriteDataFiles. 
How could we limit the jvm using memory when rewriteDataFiles with equality_delete file compations?

**Comment by moon-fall** [comment]
A large amount of memory is used because each datafile will read all the data of the deletefile which seqNum is bigger than datafile in a hashSet for filtering, In the optimized version of my company , I use a Datafile bloom filter to filter out unnecessary eq-deletefile keys (datafile hashset also works, but using hashset usually consumes more memory) , if the datafile support storage Bloom filter Such as  using parquet format based on #2642 ，It's easier to read bloom filters directly from a datafile.
 maybe I can pull a request if need.

**Comment by fengsen-neu** [comment]
> A large amount of memory is used because each datafile will read all the data of the deletefile which seqNum is bigger than datafile in a hashSet for filtering, But only those keys that are also in the datafile are necessary to read , In the optimized version of my company , I use a bloom filter of datafile's keys to filter out unnecessary eq-deletefile keys (hashset of datafile's keys also works, but using hashset usually consumes more memory) , if the datafile support storage Bloom filter Such as using parquet format based on #2642 ，It's easier to read bloom filters directly from a datafile. maybe I can pull a request if need.

![image](https://user-images.githubusercontent.com/58256617/150480410-dffc1c5f-66db-41ab-ac7f-199e8f65542b.png)
![image](https://user-images.githubusercontent.com/58256617/150480438-bb672d08-94de-4f1e-86f0-1ee203dc9306.png)
The DeleteFilter object that include deletefile is using much more memory when compaction. As you said 'each datafile will read all the data of the deletefile which seqNum is bigger than datafile in a hashSet for filtering', so I think we should control the DeleteFilter size to limit memory use.

**Comment by fengsen-neu** [comment]
> A large amount of memory is used because each datafile will read all the data of the deletefile which seqNum is bigger than datafile in a hashSet for filtering, But only those keys that are also in the datafile are necessary to read , In the optimized version of my company , I use a bloom filter of datafile's keys to filter out unnecessary eq-deletefile keys (hashset of datafile's keys also works, but using hashset usually consumes more memory) , if the datafile support storage Bloom filter Such as using parquet format based on #2642 ，It's easier to read bloom filters directly from a datafile. maybe I can pull a request if need.

It's easier to read bloom filters directly from a datafile. maybe I can pull a request if need. --- Could you please provide the PR for my reference?

**Comment by coolderli** [comment]
> 

This is also a headache for us. We use RocksDBSet (reference #2680) but it is hard to tune the rocksdb, @moon-fall Could you please provide your PR? It matters to us.
