### ISSUE TITLE
Is there a full example for Iceberg+Flink+Minio

### ISSUE THREAD

**Issue by Bryanquan** [apache/iceberg#3968]

**Comment by qq240035000** [comment]
I want it too

**Comment by luohaifang** [comment]
i also want to

**Comment by openinx** [comment]
@qq240035000 @luohaifang I did not try the flink + iceberg on Minio environment, but as Minio is an AWS S3 compatible storage  file system,  so I think you can follow the AWS flink document to try your demo. The difference is:  the catalog I think we will need to use HiveCatalog, right ? ( Minio don't has any DynamicDB service to provide the table lock service).

**Comment by qq240035000** [comment]
0.13.0 Release Notes

**Comment by qq240035000** [comment]
0.13.0 Release Notes

**Comment by qq240035000** [comment]
0.13.0 Release Notes
Any S3-compatible storage (e.g. MinIO) can now be accessed through AWS S3FileIO with custom endpoint and credential configurations [[#3656](https://github.com/apache/iceberg/pull/3656)] [[#3658](https://github.com/apache/iceberg/pull/3658)]

I do not know how to configure the credential configurations and use S3FileIO. The AWS flink document do not show with detail. @openinx

**Comment by caesar168** [comment]
I This demand is still quite a lot. We also need such a complete example.

**Comment by Fokko** [comment]
I'm just seeing this now, there is an example available here: https://github.com/tabular-io/docker-spark-iceberg
