### ISSUE TITLE
Enable data and delete files for a table to be in different formats

### ISSUE THREAD

**Issue by SinghAsDev** [apache/iceberg#3995]
Data and delete files could be in different formats right now, however, table scans don't support reading different formats for data and delete files.

**Comment by flyrain** [comment]
It should work by checking the code. Did you test it out? For example, data file is parquet, delete file is avro.
Here is the delete read path, which is different from data file read path. https://github.com/apache/iceberg/blob/7fd7ccbcc5493b98aba3d5a26117e87d299bdbcf/data/src/main/java/org/apache/iceberg/data/DeleteFilter.java#L241
