### ISSUE TITLE
Support S3 Batch Removal of objects as part of snapshot expiration and removing orphan files

### ISSUE THREAD

**Issue by amogh-jahagirdar** [apache/iceberg#4012]
Mentioned in https://github.com/apache/iceberg/issues/3582 as well.

In the current spark procedures for snapshot expiration and removing orphan files, we delete s3 objects using the DeleteObject API which accepts 1 object. We currently parallelize these calls within the spark driver based on a max concurrent deletes configuration. Another improvement we maybe could do is make S3#DeleteObjects calls so that we reduce the number of network calls made and improve throughput of the deletion operations. Different storage implementations would have to surface on the FileIO interface if they support this batch removal semantic.

**Comment by szehon-ho** [comment]
@amogh-jahagirdar  @jackye1995  are you guys working on it?  I chatted with @dramaticlly , maybe we can give it a try if you haven't started it yet?  

Was thinking we can have a new FileIO method like delete(Iterator<File>) , and default it to calling delete one by one, but in S3FileIO case can call S3#DeleteObjects like you say?  It does get a bit messier with the the user-facing API BaseDeleteOrphanFilesSparkAction.deleteWith(), not sure if we might need to add another bulk API there or just have the default implementation use the better FileIO method

**Comment by amogh-jahagirdar** [comment]
I have started it and have some changes on a local branch (still some more implementation and testing needed).  Will push it up so you can take a look. I am happy to continue working on it if that works for you @szehon-ho @dramaticlly ?

**Comment by szehon-ho** [comment]
Sounds good, thanks!  Let us know if we can help any part

**Comment by dramaticlly** [comment]
Wire S3 batch deletion for snapshot expiration can be found in #5412
