### ISSUE TITLE
Implementor of Transform

### ISSUE THREAD

**Issue by elferherrera** [apache/iceberg#4015]
Im trying to use `createTable` from `SparkCatalog` and it needs an array of objects that implement the interface `org.apache.spark.sql.connector.expressions.Transform`. But I couldnt find any in the documentation.
Can anyone point me to a constructor for these objects?

**Comment by rajarshisarkar** [comment]
Hi @elferherrera,

I think you are referring to `Spark3Util.toTransforms` which creates an array of `Transform`: [Code Link](https://github.com/apache/iceberg/blob/master/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java#L255-L311)

You can refer `SparkTable` class to understand the caller.
