### ISSUE TITLE
Writing a Spark Repartition-ed Dataframe into Iceberg Table goes into infinite loop 

### ISSUE THREAD

**Issue by akghbti** [apache/iceberg#4035]
Spark Version 3.0
Iceberg Version 0.12.1

Sample Code-Snippet
"
sparkSession.sql("CREATE TABLE local.db.sampleTable(_c0 string, _c1 string, _c2 string) USING iceberg");
Dataset<Row> ds = sparkSession.read().format("csv").load("C:\\STUDY\\SPARK_ICEBERG\\Data\\input.csv);
ds = ds.repartition(functions.col("_c2"));
ds.write().option("write-format", "parquet").insertInto("local.db.sampleTable");

"

Infinite output 
[BUG_2.log](https://github.com/apache/iceberg/files/7996705/BUG_2.log)
log attached.

**Comment by akghbti** [comment]
No its not getting completed...Its actually stuck in writing the last file (deleting and recreating it) in the data folder..
video attached.

https://user-images.githubusercontent.com/64609106/152398681-7e1272d6-7bea-4d04-9237-5ae58739c5d6.mp4

**Comment by RussellSpitzer** [comment]
Your video shows it creating a different file every single time. You can watch the number increase

**Comment by akghbti** [comment]
I will wait for a bit long and then report here..
