### ISSUE TITLE
push down aggregation (min/max/count) to iceberg scan

### ISSUE THREAD

**Issue by huaxingao** [apache/iceberg#4046]
Currently, when doing SELECT max/min/count FROM table, all the files will be scanned and then the max/min/count will be calculated. Ideally, we should avoid doing a full scan and just use the metrics statistics for max/min/count.

**Comment by huaxingao** [comment]
cc @RussellSpitzer @flyrain

**Comment by Zhangg7723** [comment]
Iceberg has provided the metric api of data files, I think the pushdown should be implemented in the SQL engine, maybe build a  plan with a datasource that collect the statistics。

**Comment by flyrain** [comment]
As @RussellSpitzer mentioned in https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1645289087247769, the MOR deletes make the metrics unreliable. In that case, we still need to read data files.

**Comment by flyrain** [comment]
This is not fixed yet AFAIK. We need it to be open. I don't have the permission to add/change a label.
cc @aokolnychyi @rdblue

**Comment by rdblue** [comment]
@flyrain, commenting will keep the issue alive.
