### ISSUE TITLE
Add navigation on the spec page

### ISSUE THREAD

**Issue by zjffdu** [apache/iceberg#4059]
The spec page is very long, it is hard to navigate to the right content quickly without navigation. It is better to have navigation on the right side like other pages.

https://iceberg.apache.org/spec/

**Comment by kyle-cx** [comment]
@zjffdu  I think here is what u like, and u can close this

![image](https://user-images.githubusercontent.com/10529123/161932210-5916eaa0-842f-4a64-9138-ca157501e4df.png)

**Comment by zjffdu** [comment]
Thanks @kyle-cx
