### ISSUE TITLE
Delete files are not getting generate by using format-version 1 and 2

### ISSUE THREAD

**Issue by naushadahamad786** [apache/iceberg#4063]
Spark Version 3.0.1
Iceberg Version 0.12.1

-SQL Query
MERGE INTO local.db.Mergetable1 t USING (SELECT * FROM local.db.Mergetable2) u ON t.id = u.id WHEN MATCHED AND t.id=1 THEN UPDATE SET t.data='z'

We are expecting '"total-delete-files" attribute value should be 1, but it's show '0'.

"summary" : {
      "operation" : "overwrite",
      "spark.app.id" : "local-1644210838923",
      "deleted-data-files" : "1",
      "deleted-records" : "2",
      "removed-files-size" : "658",
      "changed-partition-count" : "1",
      "total-records" : "0",
      "total-files-size" : "0",
      "total-data-files" : "0",
      "total-delete-files" : "0",
      "total-position-deletes" : "0",
      "total-equality-deletes" : "0"
    }

Please find attached file for 'metadata.json' file.
[v7.metadata.zip](https://github.com/apache/iceberg/files/8021379/v7.metadata.zip)

If I missed any configuration to reproduce the "total-delete-files" , please help me.

**Comment by zhongyujiang** [comment]
@naushadahamad786  0.12.1 only supports copy-on-write MERGE INTO, matching data files will be replaced with new data files immediately, so it won't produce delete files.

**Comment by akghbti** [comment]
Even 0.13 is not producing delete files with Spar 3.2 . Any config needs to be set for the same ??

**Comment by naushadahamad786** [comment]
I have used also below version but We are not able to find any delete files-

Spark Version 3.2.0
Iceberg Version 0.13.1
and 
iceberg-spark-runtime-3.2_2.12

**Comment by zhongyujiang** [comment]
@akghbti @naushadahamad786 0.13 supports merge-on-read delete: [0.13.0 Release Notes](https://iceberg.apache.org/releases/), and merge-on-read merge is still in progress, you can track progress [here](https://github.com/apache/iceberg/projects/11).

**Comment by RussellSpitzer** [comment]
Did you set ```TableProperties.UPDATE_MODE, "merge-on-read"```
