### ISSUE TITLE
create table writeTo() operation doesn't support "partitionedBy“  method

### ISSUE THREAD

**Issue by ekin4l** [apache/iceberg#4079]
hi
 
  I followed the documentation example and encountered an error when writing a DataFrame to a table

  for example : shopDF is a dataframe contains some shop infos,  when write  to an iceberg table, it throw an error:

 shopDF.writeTo("hive_prod.icedb.t_shop").tableProperty("write.format.default","parquet").partitionBy($"city").createOrReplace()

<console>:24: error: value partitionBy is not a member of org.apache.spark.sql.CreateTableWriter[org.apache.spark.sql.Row]
       shopDF.writeTo("hive_prod.icedb.t_shop").tableProperty("write.format.default","parquet").partitionBy($"city").createOrReplace()

   thanks

--------vesion infomation----
spark : 3.2.1
iceberg : org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.0
java : 1.8

**Comment by hililiwei** [comment]
https://github.com/apache/iceberg/pull/4247
