### ISSUE TITLE
Docs: Search Preview Window is Very Small

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#4095]
The search preview window is sized to the same size as the search bar itself which is quite small with tiny text. I think the preview portion should probably much larger than the original search bar

![image](https://user-images.githubusercontent.com/413025/153643385-4259f7b7-e345-4670-83ed-d54bcf46b48b.png)

**Comment by kyle-cx** [comment]
hi @RussellSpitzer, I have tried and found it's hard to widen the result view below the search input, so I put it on the right side

## when only one result
![image](https://user-images.githubusercontent.com/10529123/164202923-d1723f1a-1aeb-4485-b935-34e426e9879f.png)


## when more results
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/10529123/164202598-b1662886-f709-4ab6-a04b-58e598b16541.png">

**Comment by rdblue** [comment]
Fixed by https://github.com/apache/iceberg-docs/pull/74
