### ISSUE TITLE
Delete files not eventually removed if RewriteDataFile run right after delete (when using 'use-starting-sequence-number' default)

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#4127]
This RewriteDataFile flag value 'use-starting-sequence-number' (added and default true in #3480) seems to prevent delete files from getting cleaned up if these operations are run:

``` Delete from my_table where =  ```     
=> new delete_file has sequence number = n
``` CALL %s.system.rewrite_data_files(table => my_table, options => map ('delete-file-threshold','1')```   
=> new data files have sequence_number = n, because starting sequence number = n

The only cleanup mechanism for delete files today is only when they have a sequence number less than all existing data files.  So these delete files are not cleaned up in the subsequent operation (unlike if the flag was off and the rewritten files get the next sequence number n+1).  As these data-files were just successfully re-written, it's doubtful their delete file can ever get cleaned up because further rewrites will probably skip these already-optimized data files.  These delete files will stay until all these data files get deleted.

**Comment by szehon-ho** [comment]
Not sure how common this will be in real life, but I think it is a bit of surprise to users trying to play with feature the first time.  

Is the case that the flag solves (equality delete while rewrite-data-file happens) more common that default should be true?  If so, maybe the only solution here is to implement the RemoveDanglingDeleteFiles Spark job in the design doc.

**Comment by coolderli** [comment]
I have a PR to solve this problem：https://github.com/apache/iceberg/pull/3990

**Comment by szehon-ho** [comment]
Looks like more people hit this issue.

@rdblue @aokolnychyi @RussellSpitzer @jackye1995 (or anyone else) fyi if any thoughts on this.  Its probably not a huge issue as delete files will not apply, and we plan eventually to have removeDanglingDeleteFiles, but not sure if we need to document this for time being or any other quick fix.

**Comment by szehon-ho** [comment]
Note , plan to put a design doc up next week for this.

**Comment by szehon-ho** [comment]
Design doc here:  https://github.com/apache/iceberg/issues/6126

**Comment by chenwyi2** [comment]
@szehon-ho Is there a plan to deal with equality delete?
