### ISSUE TITLE
Partitioning by Year/Month/Day

### ISSUE THREAD

**Issue by FocalChord** [apache/iceberg#4129]
```
CREATE TABLE IF NOT EXISTS local.default.t4 (sessionid string, eventtime timestamp, type string)" 
USING iceberg
PARTITIONED BY (type, years(eventtime), months(eventtime), days(eventtime));
```

Hi I would think that you would be able to create a table that is partitioned by y/m/d, when I go to create this table I get this error: 

`Cannot add redundant partition: 1001: eventtime_year: year(2) conflicts with 1002: eventtime_month: month(2)`

Is this intentional/expected?

**Comment by yaooqinn** [comment]
Seems intentional, see https://github.com/apache/iceberg/pull/2061#discussion_r559051327

**Comment by RussellSpitzer** [comment]
This is a design choice to prevent adding a partitioning which wouldn't change the data layout

**Comment by dendihandian** [comment]
```
CREATE TABLE my_database.my_table (
    id bigint,
    title string
)
PARTITIONED BY (y string, m string, d string) 
LOCATION 's3://my-bucket/the-path-to/my_database/my_table/' 
TBLPROPERTIES (
  'table_type'='ICEBERG',
  'format'='parquet'
)
```

I failed to create nested y/m/d partition for iceberg table in Athena, how to accomplish this?

**Comment by l20DfX35JnKBfRn** [comment]
If anyone is confused about this error on AWS Athena, unlike with hive-style file partitioning in S3 like `{table-s3-location}/year={}/month={}/day={}/`

The equivalent in iceberg, e.g.
```SQL
CREATE TABLE documents (
id string,
created_at timestamp
...
)
PARTITIONED BY (
	day(created_at)
	);
LOCATION 's3://{table-s3-location}/'
TBLPROPERTIES ('table_type' = 'ICEBERG');
```

This will create separate partitions for each day exactly like hive

**Comment by wfxxh** [comment]
I use pa

> If anyone is confused about this error on AWS Athena, unlike with hive-style file partitioning in S3 like `{table-s3-location}/year={}/month={}/day={}/`
> 
> The equivalent in iceberg, e.g.
> 
> ```sql
> CREATE TABLE documents (
> id string,
> created_at timestamp
> ...
> )
> PARTITIONED BY (
> 	day(created_at)
> 	);
> LOCATION 's3://{table-s3-location}/'
> TBLPROPERTIES ('table_type' = 'ICEBERG');
> ```
> 
> This will create separate partitions for each day exactly like hive

But I use hdfs set partition like yours,the data folder is {date_time column}_day=$YEAR-$MONTH-$DAY.  One year it will be 365 numbers of dirs in the data folder,several years it will be too many dirs ,whether it will have a bad impact on performance
