### ISSUE TITLE
Docs: Broken JavaDoc Links on Spark Procedures Page

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#4134]
![image](https://user-images.githubusercontent.com/413025/154167813-9b0fd444-6c4e-44dd-82f9-569b640f78f5.png)
https://iceberg.apache.org/docs/latest/spark-procedures/

**Comment by kelvin9314** [comment]
could i work on this if its available?

**Comment by RussellSpitzer** [comment]
@kelvin9314 go for it
