### ISSUE TITLE
Table operations support planning with provided thread pool

### ISSUE THREAD

**Issue by yittg** [apache/iceberg#4145]
For some processing engines, it will cause exception using static common Thread pool to access manifests and plan, like #3776 in Flink.

This issue try to provide a way to support providing thread pool from processing engine.

* [x] table scan #4146 
* [x] snapshot update #4147 
* [x] snapshot remove #4148

**Comment by yittg** [comment]
cc @rdblue

**Comment by rdblue** [comment]
Thanks for getting these in!
