### ISSUE TITLE
Spark:CALL [rewrite_manifests] error Manifest is missing

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#4161]
spark 3.2.1
iceberg 0.13.0
How to deal with this case? thanks.
```
try{
      val manifestsOutput = spark.sql(
        s"""
           |CALL $catalogName.system.rewrite_manifests('${metaTable.schema}.${metaTable.tableName}', false)
           |""".stripMargin)
      manifestsOutput.show(false)
    } catch {
      case e: ValidationException => println(s"Current ${table.name()} table CALL [rewrite_manifests] error ${e.getMessage}")
    }
```

error message:
`Current hadoop_prod.wmsb.wms_do table CALL [rewrite_manifests] error Manifest is missing: hdfs://jybigdata/iceberg/warehouse/wmsb/wms_do/metadata/ab8d63b7-4d8c-450c-8cf5-e89eb257ba71-m0.avro`

**Comment by felixYyu** [comment]
BaseRewriteManifests check method:
```
private void validateDeletedManifests(Set<ManifestFile> currentManifests) {
    // directly deleted manifests must be still present in the current snapshot
    deletedManifests.stream()
        .filter(manifest -> !currentManifests.contains(manifest))
        .findAny()
        .ifPresent(manifest -> {
          throw new ValidationException("Manifest is missing: %s", manifest.path());
        });
  }
```

**Comment by felixYyu** [comment]
cc @racevedoo，@ajantha-bhat
the expire_snapshots->rewrite_data_files->rewrite_manifests->remove_orphan_files of processing in a transaction is it correct?

**Comment by ajantha-bhat** [comment]
> the expire_snapshots->rewrite_data_files->rewrite_manifests->remove_orphan_files of processing in a transaction is it correct?

regarding the order I guess `expire_snapshots` should be called after `rewrite_data_files` files to clean up old data files which are compacted into the new files.

No need to call  `remove_orphan_files` every time (as having orphan files is rare scenario) 

And regarding the error on `rewrite_manifests`, 
a. Is it a sequential operation or concurrent with other operations here?
b. Is this problem only for table in hadoop catalog ?

**Comment by felixYyu** [comment]
thanks @ajantha-bhat .
a.it is sequential operation, order of expire_snapshots->rewrite_data_files->rewrite_manifests->remove_orphan_files.
b.I only test for table in hadoop catalog.

**Comment by ajantha-bhat** [comment]
@felixYyu : Please add more information while closing the issue. Like, is the issue fixed? (If yes, which PR has fixed it) and why we are closing the issue.  Thanks.

**Comment by zqzhen091** [comment]
I also have this problem. I use the iceberg table of hive Catalog, and the operation is rewrite_data_file-&gt; rewrite_manifest-&gt; expire_snapshot, but the problem of “Manifest is missing..." occasionally occurs in the operation of rewrite_manifest. How do you solve the problem

**Comment by okayhooni** [comment]
@aokolnychyi

I got the same issue on calling `rewrite_data_files()` to the table with S3 bucket storage and Glue catalog backend.

I tested this procedure on the EMR `v6.7` (packaged with Spark version `3.2.1` and Iceberg version `0.13.1-amzn-0`)

According to the thread on your PR #4652, this update was back-ported to Spark `v3.2`. (Is it not the perfect defender for this issue..yet..?) or... AWS own custom version is not updated with those back-ported commits..?)

How can I prevent this issue..?

**Comment by 372242283** [comment]
Spark:3.3
Iceberg:13.0
Encountering the same problem

I also have this problem. I use the iceberg table of hive Catalog, and the operation is rewrite_data_file-> rewrite_manifest-> expire_snapshot, but the problem of “Manifest is missing..." occasionally occurs in the operation of rewrite_manifest. How do you solve the problem
