### ISSUE TITLE
Remove Orphan Files error...

### ISSUE THREAD

**Issue by Initial-neko** [apache/iceberg#4192]
when I call SparkAction 
`SparkActions
                .get()
                .deleteOrphanFiles(table)
                .olderThan(System.currentTimeMillis() - 1000000)
                .execute();`
it throws

`Exception in thread "main" java.lang.IllegalArgumentException: Cannot find the metadata table for xxxx of type ALL_MANIFESTS
	at org.apache.iceberg.spark.actions.BaseSparkAction.loadMetadataTable(BaseSparkAction.java:191)
	at org.apache.iceberg.spark.actions.BaseSparkAction.buildValidDataFileDF(BaseSparkAction.java:121)
	at org.apache.iceberg.spark.actions.BaseDeleteOrphanFilesSparkAction.doExecute(BaseDeleteOrphanFilesSparkAction.java:154)
	at org.apache.iceberg.spark.actions.BaseSparkAction.withJobGroupInfo(BaseSparkAction.java:101)
	at org.apache.iceberg.spark.actions.BaseDeleteOrphanFilesSparkAction.execute(BaseDeleteOrphanFilesSparkAction.java:141)
	at org.apache.iceberg.spark.actions.BaseDeleteOrphanFilesSparkAction.execute(BaseDeleteOrphanFilesSparkAction.java:76)
	`

So what exactly is a metadata table? Why don't I find it in my data file and metadata file
thanks~

**Comment by RussellSpitzer** [comment]
The issue is probably that the table object you are using is not from the configured Spark Catalog.  Try loading the table instance without Spark3Util.loadIcebergTable. 

The error is because Spark needs the catalog name to match the one in the Spark conf. Otherwise it does not know where to find the table. When instantiating a new table using the Java api it will have the default catalog name which is most likely not the same.

**Comment by Initial-neko** [comment]
> The issue is probably that the table object you are using is not from the configured Spark Catalog. Try loading the table instance without Spark3Util.loadIcebergTable.
> 
> The error is because Spark needs the catalog name to match the one in the Spark conf. Otherwise it does not know where to find the table. When instantiating a new table using the Java api it will have the default catalog name which is most likely not the same.
> 
> A metadata table is just a special view of a table which returns information like what partitions are in the table or what files are in the table. All iceberg tables have them available, see the docs for more info.

Our tables are loaded through hivecatalog. There will be no such problems in expiresnapshot and rewrite operations. I will confirm it; Thanks for your reply~

**Comment by JunjianS** [comment]
@RussellSpitzer hello, my deleteOrphanFiles case throws the same error, but expireSnapshots and expireOlderThan running successfully, whether SparkActions(13.1) is ok for spark2.4 ?
![截屏2022-06-10 16 39 18](https://user-images.githubusercontent.com/7474234/173026741-145fd68a-52b7-4722-b27d-a065ef82a603.png)
