### ISSUE TITLE
Support vectorized Parquet reads with INT96

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#4200]
We should support INT96 timestamps in imported files with vectorized reads.

**Comment by aokolnychyi** [comment]
cc @gustavoatt @edgarRd as you expressed interest in INT96 timestamps before

**Comment by sumeet-gajjar** [comment]
I can on adding this support unless @gustavoatt or @edgarRd has already started working on this :-)

**Comment by sumeetgajjar** [comment]
I can work on adding this support unless @gustavoatt or @edgarRd has already started working on this :-)

**Comment by gustavoatt** [comment]
@sumeetgajjar Feel free to take it over, unfortunately we haven't had any bandwidth to work on this.

Appreciate the help 😄
