### ISSUE TITLE
where is comment info for column or table in iceberg

### ISSUE THREAD

**Issue by zihaochen68** [apache/iceberg#4219]
i can not find comment info in {version}.metadata.json

**Comment by itaise** [comment]
Can you give details on how you wrote the comments on the fields?

**Comment by zihaochen68** [comment]
> Can you give details on how you wrote the comments on the fields?

i'm create a table in flink SQL
Here is my catalog:
```
CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://localhost:port',
  'clients'='5',
  'property-version'='1',
  'warehouse'='hdfs://localhost:port/hive/metastore/catalog'
);
```
Then
```
CREATE TABLE hive_catalog.yuyi.sample (
    id BIGINT COMMENT 'unique id',
    test STRING COMMENT 'test'
) COMMENT 'a';
```

where can i find my comments for table or column.
There are not in hive or {version}.metadata.json

thnx

**Comment by zihaochen68** [comment]
It works when I use the Java API, There seems to be something wrong with Flink API
