### ISSUE TITLE
Spark:rename table column name from lower(data) to upper(DATA)?

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#4230]
`ALTER TABLE prod.db.sample RENAME COLUMN data TO DATA`

**Comment by felixYyu** [comment]
cc @rdblue @RussellSpitzer @jackye1995

**Comment by RussellSpitzer** [comment]
Are you asking about the case insensitivity of SQL?

**Comment by felixYyu** [comment]
yes

**Comment by felixYyu** [comment]
MySQL table column name is Upper，execute function of `from_json(col("data"), icebergSchema)`, so Iceberg table column name shoud case consistency. then I traverse the iceberg schema structType and modify field to Upper. thanks @RussellSpitzer and close it.
