### ISSUE TITLE
Allow disabling `HiddenPathFilter` from `RemoveOrphanFiles`

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#4249]
There's a `PathFilter`, `HiddenPathFilter`, that is used during the `RemoveOrphanFiles` Spark actions (amongst other places).

Hadoop filtering will remove anything with an underscore or a dot in a path, so if a partition filter is created that has a leading underscore, then remove orphan files will fail to remove these files.

We should update `RemoveOrphanFiles` to handle cases where directories are erroneously marked as hidden paths.

**Comment by felixYyu** [comment]
I want to try to realize it.
