### ISSUE TITLE
[Python] support iceberg literal classes

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#4250]
Literals are wrapper classes to be used in expressions, which return unbound predicates.
Here is the current python implementation, https://github.com/apache/iceberg/blob/master/python_legacy/iceberg/api/expressions/literals.py
and the Java implementation:
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/expressions/Literals.java

We want to refactor the current one to make it more pythonic but also make sure it is easy to maintain.
For example, a static method can be replaced to be a module method, which is more pythonic, etc.

**Comment by dramaticlly** [comment]
hey @jun-he , I can help this task. But in the mean time, can you share a bit more in detail on what's the success criteria of this task? It might help both assignee and reviewer

**Comment by dramaticlly** [comment]
> this is the current python legacy one: https://github.com/apache/iceberg/blob/master/python_legacy/iceberg/api/expressions/literals.py

> and java implementation: https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/expressions/Literals.java

**Comment by jun-he** [comment]
@dramaticlly  Thanks for taking it. Added some details to the description based on the offline discussion. Please let me know if you have any additional questions.

**Comment by rdblue** [comment]
Closing this since it is implemented by #4262.
