### ISSUE TITLE
PartitionsTable doesn't take old specs into consideration

### ISSUE THREAD

**Issue by szlta** [apache/iceberg#4292]
Currently PartitionsTable will be constructed with a schema based on the latest table spec only:
https://github.com/apache/iceberg/blob/master/core%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Ficeberg%2FPartitionsTable.java#L48
Especially with V2, this can result in funny partition table prints when we drop a partition field and create a different one.
E.g:
Table schema: a int, b timestamp
spec0: year(b) -> partitions table schema: b_year int
spec1: day(b) -> partitions table schema: b_day date

Any rows inserted in spec0 times will store partition values that is epoch years, like 52 for 2022.
Then after spec change the value 52 would be considered an epoch day instead, and will yield to "1970-02-22"

I believe the solution would be to use what DataFilesTable has already:
Partitioning.partitionType(table()); 
see: https://github.com/apache/iceberg/blob/master/core%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Ficeberg%2FDataFilesTable.java#L55

cc: @RussellSpitzer @aokolnychyi

**Comment by aokolnychyi** [comment]
I agree with your analysis, @szlta. I am surprised `PartitionsTable` does not use `Partitioning$partitionType`.

I'd do the following in separate PRs:
- Rename conflicting columns in old specs in `Partitioning$partitionType` as [discussed](https://github.com/apache/iceberg/pull/3411#discussion_r821845093).
- Use `Partitioning$partitionType` in all metadata tables.
- Consider adding `partition_spec_id` to metadata tables like `data_files` and `partitions`.
- Consider reusing equivalent columns with column IDs during spec evolutions.

**Comment by szehon-ho** [comment]
Third point was already done in #3015 for *files_table, though I think not yet Partitions table

**Comment by aokolnychyi** [comment]
@szlta, would you be interested to work on the steps above? If you don't have time, I may ask someone on our team to do this.

**Comment by szlta** [comment]
Hi @aokolnychyi sorry for the longer pause here, I was on paternity leave ;)
Before I left, I was looking into how proposal 2 in https://github.com/apache/iceberg/pull/3411#discussion_r823692312 could be implemented in Iceberg. It seemed to be quite tricky, so first I'd jump onto the smaller fixes of the above proposed list.
I'd be happy to take this up and work on a PR that should fix these two points:

- Use Partitioning$partitionType in all metadata tables.
- Consider adding partition_spec_id to metadata tables where this is missing (I think it's only the partitions meta table).

These two relate strongly, so I think they are worth handling in the same change request. I'll start working on this PR today.

**Comment by aokolnychyi** [comment]
Thanks for fixing, @szlta!

It looks like the only remaining point is this:

> Consider reusing equivalent columns with column IDs during spec evolutions.

I agree it is quite tricky. Shall we close this issue as the original problem seems to be fixed and open a new issue for the remaining work?

**Comment by szlta** [comment]
Yup, we should continue with fixing the column reuse problem at https://github.com/apache/iceberg/issues/4661
And I'm closing this one, thanks!
