### ISSUE TITLE
Running the same batch task multiple times using the Flink Session pattern causes the linux out of memory

### ISSUE THREAD

**Issue by renshangtao** [apache/iceberg#4305]
I have A batch task that inserts 100 million data from table A into table B after the primary key hash. I use Flink mode to execute this task. After several times of executing this task, I find that the Flink TaskManager process occupies more and more memory.  Finally, the Flink TaskManager process is killed when the system runs out of memory.  

Manually performing GC memory reclamation after the task execution is completed has no effect, and viewing memory through top does not decrease. unless the Flink TaskManager is turned off.

Logically, when a task is finished, it should release the resources it occupies, so that subsequent tasks can continue to run, but it does not. 

The growth of memory occurs in the icebergStreamWriter stage, but I look at the code and do not find a place to use off-heap memory, so it is more confusing, can anyone help me?

![image](https://user-images.githubusercontent.com/53618158/157629972-7f0b98d5-22ae-4c37-a079-dca685ba6b53.png)

Memory usage is 25% before running the job, and 72% memory is reached after three times
![image](https://user-images.githubusercontent.com/53618158/157630574-5709313f-a097-4053-9e92-ab1f8b926e0a.png)

The Configuration
![006](https://user-images.githubusercontent.com/53618158/157634301-b9e364f6-c66c-4a71-945f-dff51dae1acd.PNG)

The System kill taskmanager process
![003](https://user-images.githubusercontent.com/53618158/157634893-c3e1f8f6-48d8-4f4e-8772-463be2a388a3.PNG)

**Comment by renshangtao** [comment]
Install jemalloc on the every node of flink cluster can solve this problem

1、install jemalloc 

2、Add the configuration below in /etc/profile
export LD_PRELOAD=/usr/local/lib/libjemalloc.so
#export MALLOC_CONF="prof:true,prof_prefix:/home/bigdata/jeprof.out,lg_prof_interval:30,lg_prof_sample:20"

3、The source /etc/profile    

4、And Then start flink cluster

5、execute the batch jobs

I install jemalloc on two of five nodes， then here are the result of test,  after seven times exec batch job the memory is increse to 50%+ who use glibc-malloc

![1647448675433-20ce92b8-894a-4649-bf7f-0039072831cf](https://user-images.githubusercontent.com/53618158/158756660-f730b170-05c3-460a-bd41-e2c5294d3892.png)


Why change the glibc-malloc to jemalloc 

The reason i think maybe the glibc-malloc casued plenty memory fragmentation。

@rdblue @openinx 

can you help me，i use flink to writer hive table don't have this problem

**Comment by openinx** [comment]
I think the core reason is:  we have set the primary keys in iceberg table for flink DDL,  so the flink write job will think that we are trying to write all those results into an iceberg format v2 table.  see the following code piece: 


https://github.com/apache/iceberg/blob/master/flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java#L62-L72

Do you want to write all those records into an iceberg format v2 table to deduplicate those rows who has the same primary key ? If not , then I will suggest to remove the primary key definition in the flink sink table DDL. If sure, then I think we may need to port[ this PR](https://github.com/apache/iceberg/pull/4298) in your branch to fix the OutOfMemory issue.

**Comment by renshangtao** [comment]
First thanks a lot for  your reply, It was I who didn't describe the scene clearly


1、This is my source table:
 create table hive_catalog.iceberg_db.sourceTable (
    step_id string,
    param_id string,
    wafer_id string,
    chip_id string,
    product_id1 string,
    product_id2 string,
    product_id3 string,     
    product_id4 string,
    product_id5 string,
    num_item1 double,
    num_item2 double,
    num_item3 double,
    num_item4 double,
    num_item5 double,
    num_item6 double,
    start_date date,
    PRIMARY KEY (chip_id, param_id, step_id, wafer_id) NOT ENFORCED)
PARTITIONED BY (step_id, start_date)
WITH ('format-version'='2');

2、This is Temp Table:
create table hive_catalog.iceberg_db.temp_data (
     step_id string,
     param_id string,
     wafer_id string,
     chip_id string,
     product_id1 string,
     product_id2 string,
     product_id3 string,     
     product_id4 string,
     product_id5 string,
     num_item1 double,
     num_item2 double,
     num_item3 double,
     num_item4 double,
     num_item5 double,
     num_item6 double,
     start_date date,
     part_id int)
 PARTITIONED BY (part_id)
 WITH ('format-version'='2', 'write.distribution-mode'='hash');

This is the sql which my batch job use.

3、insert into temp_data select 
     step_id,
     param_id,
     wafer_id,
     chip_id,
     product_id1,
     product_id2,
     product_id3,
     product_id4,
     product_id5,
     num_item1,
     num_item2,
     num_item3,
     num_item4,
     num_item5,
     num_item6,
     start_date,
     (HASH_CODE(step_id || param_id || step_id || wafer_id)) % 10 as part_id 
     from source;

After i run this job seven or eight tims the memory of linux will be incresed to 80%，And the memory which taskmanger used is 60%.

But if i use jemalloc to run several times of job, the memory is noraml , which is same as the flink cluster just started

**Comment by renshangtao** [comment]
i find an article an solve this problem

https://github.com/prestodb/presto/issues/8993
