### ISSUE TITLE
Issue with Iceberg table read/write using Spark

### ISSUE THREAD

**Issue by iam8139** [apache/iceberg#4313]
Facing "ClassNotFoundException: iceberg.DefaultSource" when I am trying to read/write Iceberg tables using Spark.

Dataset<Row> data = spark.read()
	    	.format("iceberg")
	    	.load("Iceberg_table_Path");

My pom.xml includes following dependencies ->
<dependency>
		    <groupId>org.apache.iceberg</groupId>
		    <artifactId>iceberg-core</artifactId>
		    <version>0.13.1</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.iceberg</groupId>
		    <artifactId>iceberg-hive</artifactId>
		    <version>0.9.1</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.iceberg</groupId>
		    <artifactId>iceberg-spark3-runtime</artifactId>
		    <version>0.13.1</version>
		    <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.apache.iceberg</groupId>
		    <artifactId>iceberg-spark</artifactId>
		    <version>0.9.1</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.thrift</groupId>
		    <artifactId>libthrift</artifactId>
		    <version>0.16.0</version>
		</dependency>

**Comment by hililiwei** [comment]
try 
```
org.apache.iceberg
iceberg-spark3-runtime
0.13.1
```
no test
