### ISSUE TITLE
DataFrameWriterV2 doesn't create partitions when using partitionedBy

### ISSUE THREAD

**Issue by krisvaz** [apache/iceberg#4363]
When I try using the DataFrameWriterV2 to create an Iceberg table, the partitioning columns seem to get ignored (thereby not partitioned) even though they are specified.

Spark version: 3.1.2
Iceberg version: 0.13.0

Note: The application is written in python.

```
orders_df.writeTo("iceberg_catalog.p2.orders").using("iceberg").option(
    "fanout-enabled", "true"
).partitionedBy("date(pickupts)", "appname").create()
```

Using Spark SQL to describe the table using this way shows this:
```
# Partitioning
Not partitioned
```

The workaround for creating the tables with the appropriate partitions is via Spark SQL.

i.e. this works as expected (see note below snippet): 
```
orders_df.createOrReplaceTempView("p2_orders_view")
spark.sql(
    """
    create table iceberg_catalog.p2.orders using iceberg
    PARTITIONED BY (date(pickupts), appname)
    as select * from p2_orders_view
    """
)
```

Here, when using Spark SQL to describe the table using this above method to create the table shows this:
```
# Partitioning
Part 0	days(pickupts)
Part 1	appname
```

My question is, am I using the DataFrameWriterV2 correctly when specifying the partitionedBy columns?

**Comment by RussellSpitzer** [comment]
Looks right to me, and the code looks fine on the Spark Side

https://github.com/apache/spark/blob/v3.1.2/sql/core/src/main/scala/org/apache/spark/sql/DataFrameWriterV2.scala#L83-L126

Probably need to debug this later to find out exactly what is going wrong

**Comment by hililiwei** [comment]
@krisvaz I debugged it locally and it works as expected, can you share more information? Like your test data?

**Comment by krisvaz** [comment]
@hililiwei 

Here's an example of using the DataFrameWriterV2 to try creating the partitioned table and it's result:
```
>>> df = spark.createDataFrame([{'partition_a': 'A', 'partition_b': 'B', 'data': 'somestuff'}])
>>> df.writeTo("iceberg_catalog.p2.test").partitionedBy("partition_a", "partition_b").create()
>>> spark.sql("describe iceberg_catalog.p2.test").show()
+---------------+---------+-------+
|       col_name|data_type|comment|
+---------------+---------+-------+
|           data|   string|       |
|    partition_a|   string|       |
|    partition_b|   string|       |
|               |         |       |
| # Partitioning|         |       |
|Not partitioned|         |       |
+---------------+---------+-------+
```

Here's an example of using spark sql to create the partitioned table and it's result:
```
>>> df = spark.createDataFrame([{'partition_a': 'A', 'partition_b': 'B', 'data': 'somestuff'}])
>>> df.createOrReplaceTempView('test_view')
>>> spark.sql("""
... create table iceberg_catalog.p2.test using iceberg partitioned by (partition_a, partition_b)
... as select * from test_view""")
DataFrame[]
>>> spark.sql("describe iceberg_catalog.p2.test").show()
+--------------+-----------+-------+
|      col_name|  data_type|comment|
+--------------+-----------+-------+
|          data|     string|       |
|   partition_a|     string|       |
|   partition_b|     string|       |
|              |           |       |
|# Partitioning|           |       |
|        Part 0|partition_a|       |
|        Part 1|partition_b|       |
+--------------+-----------+-------+
```

I should note that I am running this within an AWS EMR cluster that's configured as defined [here](https://iceberg.apache.org/docs/latest/aws/#spark). 
Instead of starting a spark-sql shell, I'm starting a pyspark shell with those same configs.

**Comment by hililiwei** [comment]
@krisvaz 
```
./pyspark --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
    --conf spark.sql.catalog.spark_catalog.type=hive \
    --conf spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog \
    --conf spark.sql.catalog.local.type=hadoop \
    --conf spark.sql.catalog.local.warehouse=$PWD/warehouse
```
```
>>> spark.sql("create database local.p2").show()
>>> df = spark.createDataFrame([{'partition_a': 'A', 'partition_b': 'B', 'data': 'somestuff'}])
>>> df.writeTo("local.p2.test").using("iceberg").partitionedBy("partition_a", "partition_b").create()
>>> spark.sql("describe local.p2.test").show()

+--------------+-----------+-------+
|      col_name|  data_type|comment|
+--------------+-----------+-------+
|          data|     string|       |
|   partition_a|     string|       |
|   partition_b|     string|       |
|              |           |       |
|# Partitioning|           |       |
|        Part 0|partition_a|       |
|        Part 1|partition_b|       |
+--------------+-----------+-------+

```

**Comment by liuchunhua** [comment]
@krisvaz @hililiwei 

https://github.com/apache/spark/blob/v3.1.2/python/pyspark/sql/readwriter.py#L1496-L1525
missing "self._jwriter.partitionedBy(col, cols)"

**Comment by davidrimprobable** [comment]
I assume based on the above that @krisvaz was able to get this to work on a newer Spark - but are there any pointers for when you're already running a Spark without the bug shown above?

I'm on Spark 3.2.0 and using 
```python
df = session.createDataFrame([{'partition_a': 'A', 'partition_b': 'B', 'data': 'somestuff'}])
df.writeTo("my_catalog.db.test").using("iceberg").partitionedBy("partition_a", "partition_b").create()
session.sql("describe my_catalog.db.test").show()
```

I receive
```
+---------------+---------+-------+
|       col_name|data_type|comment|
+---------------+---------+-------+
|           data|   string|       |
|    partition_a|   string|       |
|    partition_b|   string|       |
|               |         |       |
| # Partitioning|         |       |
|Not partitioned|         |       |
+---------------+---------+-------+
```

This is S3A with catalog-impl of `org.apache.iceberg.jdbc.JdbcCatalog` to a postgres database

Is this expected for this combination of options?

**Comment by hililiwei** [comment]
@davidrimprobable Could you please list your environment in more detail? I can't reproduce the mistake for the time being.

**Comment by aajisaka** [comment]
FYI

> https://github.com/apache/spark/blob/v3.1.2/python/pyspark/sql/readwriter.py#L1496-L1525
> missing "self._jwriter.partitionedBy(col, cols)"

Nice catch. This issue has been fixed in https://issues.apache.org/jira/browse/SPARK-37079

**Comment by atifiu** [comment]
@aajisaka I am trying to use date function on partitionedBy clause to match with my table partitioning but its throwing error. I am using Spark 3.3.1 and Apache Iceberg 1.3.0

```
df.writeTo("schema1.table_name1").partitionedBy("date(page_view_dtm)", "id", "v_num").append()

File "/app/spark3.3.1/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1420, in partitionedBy
  File "/app/spark3.3.1/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/app/spark3.3.1/python/lib/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
pyspark.sql.utils.ParseException:
Syntax error at or near '('(line 1, pos 4)

== SQL ==
date(page_view_dtm)
----^^^
```

**Comment by aajisaka** [comment]
You should add a partition column by `withColumn` and call `partitionedBy` with the new column.

**Comment by Yotamho** [comment]
> You should add a partition column by `withColumn` and call `partitionedBy` with the new column.

Will it support hidden partition this way? I think that in this way, when I will query using the column `page_view_dtm` (without the explicit transformation), it wouldn't benefit from the partitioning..
