### ISSUE TITLE
HiveCatalog: renameTable recursively lists file status

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#4406]
While #734 fixes the recursive file status listing for HiveTableOperations, we still trigger this in HiveCatalog.renameTable https://github.com/apache/iceberg/blob/d9296ca2d1b1143e6bbcdd1004962e653400489d/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L211

**Comment by singhpk234** [comment]
based on this discussion https://github.com/apache/iceberg/pull/734#issuecomment-574062407
Looks like passing this env context to the alter table should be sufficient to avoid recursive listing here as well : 
```java
          EnvironmentContext envContext = new EnvironmentContext(
              ImmutableMap.of(StatsSetupConst.DO_NOT_UPDATE_STATS, StatsSetupConst.TRUE)
          );
```

can I pick this up ?

**Comment by RussellSpitzer** [comment]
Sure I am way behind on reviews anyway :)
