### ISSUE TITLE
Support `rewrite-all` rewrite flag in Binpack

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#4426]
Currently only the Sort RewriteDataFiles strategy supports triggering a rewrite on all data files [regardless of size](https://github.com/apache/iceberg/blob/61fe9b1ce3ecff4354bb7624c9b5e3f76df2221b/core/src/main/java/org/apache/iceberg/actions/SortStrategy.java#L51-L56). Every once in a while we see a use case where a user wants to trigger a rewrite on every file, regardless of size or other criteria. I think it makes sense to allow for the `rewrite-all` flag to work in Binpack as well.

My suggestion would be that we take the property and move it to BinPackStrategy and allow both BinPackStrategy and SortStrategy to use the option. An additional test would be required as well to make sure that BinPack Strategy can use the new option.

**Comment by rajarshisarkar** [comment]
Can I pick this up?

**Comment by rajarshisarkar** [comment]
Thanks, for bringing this up. I'm working on this.

**Comment by anuragmantri** [comment]
Thanks for creating this issue Russell. 

@rajarshisarkar - Feel free to add me to the PR. I will be happy to review.

**Comment by rajarshisarkar** [comment]
Sure, @anuragmantri.
