### ISSUE TITLE
How to delete commited logs in new PR?

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#4447]
Do not delete the self master of fork，How to delete commited logs in new PR?

**Comment by felixYyu** [comment]
exp：committed on 1 Dec 2021 commit 6aa419cc0ff2c4526b598418ac1f9e01c1eb3301

**Comment by ZhangchengHu0923** [comment]
@felixYyu  u can roll-back the branch u initiated the PR, and recommit the change u like to the same branch. Modifications will be automatically reflected on PR.

ps: remember to back up the code before the roll-back

**Comment by felixYyu** [comment]
thanks @ZhangchengHu0923

**Comment by rajarshisarkar** [comment]
You can rebase your change on top of master and force push the same in your branch for a cleaner history.

**Comment by felixYyu** [comment]
```
PS D:\jiuye-pro\jydata-git\iceberg> git reset --hard 7bfecd8514b943b00415fc4f49d1c7626fe62f4c
Updating files: 100% (8211/8211), done.
HEAD is now at 7bfecd851 Core: Initial implementation of ResolvingFileIO (#3593)
PS D:\jiuye-pro\jydata-git\iceberg> git push origin HEAD --force
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/felixYyu/iceberg
 + bad9bee04...7bfecd851 HEAD -> master (forced update)
PS D:\jiuye-pro\jydata-git\iceberg>

```
Commit history has been Initialized
![image](https://user-images.githubusercontent.com/3785228/161505653-113262aa-2ea8-40fb-9f05-c038f9b69b3e.png)
