### ISSUE TITLE
iceberg support branch/tag, what is the difference between nessie and iceberg?

### ISSUE THREAD

**Issue by melin** [apache/iceberg#4476]
iceberg support branch/tag, what is the difference between nessie and iceberg?
https://docs.google.com/document/d/1PvxK_0ebEoX3s7nS6-LOJJZdBYr_olTWH9oepNUfJ-A/edit#
iceberg branch support Cross-table transactions?

@nastra  @rdblue @jackye1995

**Comment by amogh-jahagirdar** [comment]
Would love to hear other's perspective on this, but Nessie supports other formats such as Delta Lake. There is an ongoing PR for enabling the ability for cross table transactions. https://github.com/apache/iceberg/pull/1849 . As for accomplishing cross-trable txns via branching, similar to what Nessie does if I am not mistaken, I'm not sure that's something needed to be in Iceberg native. Nessie operates at a higher level abstraction and has rich functionality in this area. In my view, I think the goal with Iceberg native branching and tagging would be to give some of these capabilities to Iceberg users without requiring a full Nessie setup.

**Comment by melin** [comment]
1. nessie branch is catalog level，Unlike traditional databases, a multi-table transaction can contain multiple tables, and a nessie transaction contains multiple transactions. Seems like the transaction is at the catalog level?
2. Iceberg branch is catalog level. catalog level branching supported?

**Comment by amogh-jahagirdar** [comment]
1.) Yes, Nessie branching is at the catalog level. Nessie catalog implementations implement the transactional capabilities for themselves so yes to that as well (if I'm not mistaken ).

2.) Iceberg branching is at the table level

**Comment by melin** [comment]
@amogh-jahagirdar  iceberg branch considering supporting catalog level?

**Comment by nastra** [comment]
@amogh-jahagirdar gave a pretty good high-level summary of Nessie vs Iceberg (thanks for that). @melin is that sufficient for you at this point to understand the differences or would you like me to get into more details?

**Comment by melin** [comment]
> @amogh-jahagirdar gave a pretty good high-level summary of Nessie vs Iceberg (thanks for that). @melin is that sufficient for you at this point to understand the differences or would you like me to get into more details?

Catalog branch is too large, table branch is too small, database branch is supported?

**Comment by nastra** [comment]
do you mean whether branching at the database level is supported? Maybe you could describe the use case you have in mind, so that I can better understand your requirements.

**Comment by melin** [comment]
In many cases, there is only one catalog. Generally, each department or team is assigned a database. It is difficult to require all teams to switch to the same branch. The granularity of the database branch is more appropriate.

**Comment by nastra** [comment]
In such a scenario, all teams would eventually merge their work into the main line (`main` branch), but each team could work on their own branch? Or is each database completely isolated from one another? If so, then each team could have their own nessie repository

**Comment by nastra** [comment]
@melin also feel free to ping me on Slack to talk about details/approaches to your use case

**Comment by melin** [comment]
Git features may not be needed by all teams, and may be used more often by warehouse teams, which are more flexible if they support Database Branch
