### ISSUE TITLE
Can I reorganize the documentation for the flink section?

### ISSUE THREAD

**Issue by polaris6** [apache/iceberg#4490]
When I read the flink-related documentation in iceberg, I found that the Getting Started section contains many aspects, makes it inconvenient to read, so I want to reorganize the flink-related documents with reference to the spark section, and divide the flink documents into Getting Started, Configuration, DDL, Queries, Writes, and Flink Connector, like this: 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/29967142/161563807-3db76967-4047-4ac3-b6e7-6407b147d888.png">

I don't know if it's possible to do this @samredai @openinx

**Comment by samredai** [comment]
@polaris6 we've been thinking a lot lately about re-organizing the docs to flow more logically with how different personas would navigate. I'm currently working on a proposal for a new structure that we can discuss in the next community sync. That's a good time to add how you'd organize the Flink section!

**Comment by polaris6** [comment]
@samredai Thank you for your reply, I am very interested in doing these work, you can call me anytime if you need it!

**Comment by samredai** [comment]
@polaris6 if you're still up to tackle this, it would be helpful to split the flink section into what's purely reference type documentation (such as things that need to be versioned with Iceberg releases) and pure getting started/quickstart material. We can carve out anything that feels like "quickstart" material and put it in a `flink-quickstart.md` file in the iceberg-docs repo's landing-page ([this](https://github.com/apache/iceberg-docs/tree/main/landing-page/content/common) directory).

Then the Flink item at the top of the landing-page could go to that quickstart, and the quickstart could link to the versioned docs site Flink section which can be exclusively configuration material, reference material, and a detailed list of feature items. Let me know what you think and feel free to message me on slack or we can jump on a call to brainstorm more on this.

**Comment by polaris6** [comment]
@samredai This is a great job and will be very fulfilling, I will look at your proposal and take the time to think about it.
