### ISSUE TITLE
Checkstyle: Do need to add the checkstyle rule of static variables?

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#4498]
In ALL iceberg project，Static variables are directly embedded in the code segment, which is not conducive to maintenance.
Do need to formulate a unified rule?

> e.g. BaseRewriteManifestsSparkAction#REWRITE-MANIFESTS ...

```
@Override
  public RewriteManifests.Result execute() {
    String desc = String.format("Rewriting manifests (staging location=%s) of %s", stagingLocation, table.name());
    JobGroupInfo info = newJobGroupInfo("REWRITE-MANIFESTS", desc);
    return withJobGroupInfo(info, this::doExecute);
  }

private Dataset<Row> buildManifestEntryDF(List<ManifestFile> manifests) {
    Dataset<Row> manifestDF = spark()
        .createDataset(Lists.transform(manifests, ManifestFile::path), Encoders.STRING())
        .toDF("manifest");

    Dataset<Row> manifestEntryDF = loadMetadataTable(table, ENTRIES)
        .filter("status < 2") // select only live entries
        .selectExpr("input_file_name() as manifest", "snapshot_id", "sequence_number", "data_file");

    Column joinCond = manifestDF.col("manifest").equalTo(manifestEntryDF.col("manifest"));
    return manifestEntryDF
        .join(manifestDF, joinCond, "left_semi")
        .select("snapshot_id", "sequence_number", "data_file");
  }
```

**Comment by felixYyu** [comment]
cc @rdblue @RussellSpitzer @jackye1995 @aokolnychyi @kbendick @openinx

**Comment by RussellSpitzer** [comment]
I'm not sure what you mean

**Comment by felixYyu** [comment]
private static final String REWRITE_MANIFESTS = "REWRITE-MANIFESTS";

public RewriteManifests.Result execute() {
    String desc = String.format("Rewriting manifests (staging location=%s) of %s", stagingLocation, table.name());
    // I think static var should instead, Other code should also be used as a constraint
    //JobGroupInfo info = newJobGroupInfo("REWRITE-MANIFESTS", desc);
    JobGroupInfo info = newJobGroupInfo(REWRITE_MANIFESTS, desc);
    return withJobGroupInfo(info, this::doExecute);
  }

**Comment by felixYyu** [comment]
It's hard to unify, so close this issue.
