### ISSUE TITLE
how to load customer Listener on spark

### ISSUE THREAD

**Issue by idealspark** [apache/iceberg#4506]
first I customer a org.apache.iceberg.events.Listener  then package it to a jar, but how to load my listener when spark start?

I need register my Listener on Iceberg Listeners

**Comment by felixYyu** [comment]
e.g.

```
private CreateSnapshotEvent currentEvent;

  public TestCreateSnapshotEvent(int formatVersion) {
    super(formatVersion);
    Listeners.register(new MyListener(), CreateSnapshotEvent.class);
  }

class MyListener implements Listener<CreateSnapshotEvent> {
    @Override
    public void notify(CreateSnapshotEvent event) {
      currentEvent = event;
    }
  }
```

**Comment by idealspark** [comment]
> e.g.
> 
> ```
>   private CreateSnapshotEvent currentEvent;
> 
>   public TestCreateSnapshotEvent(int formatVersion) {
>     super(formatVersion);
>     Listeners.register(new MyListener(), CreateSnapshotEvent.class);
>   }
> 
> class MyListener implements Listener<CreateSnapshotEvent> {
>     @Override
>     public void notify(CreateSnapshotEvent event) {
>       currentEvent = event;
>     }
>   }
> ```

thank you for reply.
I resolved this by spark listener, after later i will give a example
