### ISSUE TITLE
HIVE_METASTORE_ERROR: Table storage descriptor is missing SerDe info - when query a view using an Iceberg table on Athena

### ISSUE THREAD

**Issue by a-agmon** [apache/iceberg#4549]
We have create an Iceberg table using Athena as follows: 

```sql 
CREATE TABLE
  table_test (c1 string, c2 string, c3 string, c4 string)
  LOCATION 's3://bucket/warehouse/default.db/table_test/data/'
  TBLPROPERTIES ( 'table_type' ='ICEBERG')
``` 
The table is filled with data using Spark and can be queried. 
We want to create a view that joins this table with a non-iceberg table. The join between the tables works as expected, but after we create the view on the basis of this join and try to query then we receive this error:

HIVE_METASTORE_ERROR: Table storage descriptor is missing SerDe info

**Comment by rajarshisarkar** [comment]
Hi, please refer: https://aws.amazon.com/premiumsupport/knowledge-center/athena-hive-metastore-error/

**Comment by rsinnet** [comment]
@a-agmon did you make any progress on this?

**Comment by yakovsushenok** [comment]
I used iceberg table format v2 and when I was querying with Athena engine 2, I was getting this error. When I changed to Athena engine 3 this error went away.
