### ISSUE TITLE
Duplicated data files when to use FlinkSink upsert mode to stream upsert records

### ISSUE THREAD

**Issue by 0xffmeta** [apache/iceberg#4552]
I'm trying to use the `upsert` mode in FlinkSink to stream write the records, but I found that the data files were duplicated, similar for the manifest files - not sure if this is expected for `upsert` FlinkSink.
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/98149057/163225844-ff72c816-641c-48ca-b3cd-70c19d785708.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/98149057/163226134-cbd0d835-cae2-4a03-a68e-2c722dc978e3.png">

I can see from the writer, it will first delete the row and then write the row. Not sure if there is any way to optimize this.
https://github.com/apache/iceberg/blob/3f5230d312c5b0630681a18da0f30439ba7f6982/flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java#L83

**Comment by hameizi** [comment]
In upsert mode there will generate one delete data for everyone insert data, and the delete data will be write to equal delete file(if there is duplicate primary key data be write in one snapshot will add postion delete file).So, just as you see there are two files that one data file and one equal delete file.

**Comment by 0xffmeta** [comment]
@hameizi Thanks for the help. Do we have any documentation for the file naming convention? I noticed `xx-00002.parquet` and `xx-00001.parquet`, and similar for `xx-m0.avro` and `xx-m1.avro`. 
I checked this [doc](https://iceberg.apache.org/spec/), but seems no related documentation.

**Comment by hameizi** [comment]
> @hameizi Thanks for the help. Do we have any documentation for the file naming convention? I noticed `xx-00002.parquet` and `xx-00001.parquet`, and similar for `xx-m0.avro` and `xx-m1.avro`. I checked this [doc](https://iceberg.apache.org/spec/), but seems no related documentation.

You can see https://iceberg.apache.org/spec/#manifests and https://iceberg.apache.org/spec/#row-level-deletes.

**Comment by SML0127** [comment]
> In upsert mode there will generate one delete data for everyone insert data, and the delete data will be write to equal delete file(if there is duplicate primary key data be write in one snapshot will add postion delete file).So, just as you see there are two files that one data file and one equal delete file.

@hameizi 
I have some question about your answer.
Then.. how to distinguish whether equality filed in equality delete file was append by DELETE or INSERT/UPDATE_AFTER ?

**Comment by pvary** [comment]
There is no way by design. Other engines could write equality deletes too. The reason is not important, the result is important
