### ISSUE TITLE
Metadata file not found when restart flink job from latest checkPoint with iceberg v2

### ISSUE THREAD

**Issue by litiliu** [apache/iceberg#4557]
We have a flink job that write upsert stream into a partitioned icebergV2 table  ,and the flink version is 1.13.  When that job get failed, we restart it from the latest checkPoint. But we got that exception: Files does not exists. 
Why does that exception occur, and what should we do to avoid that problem? 

<img width="1272" alt="FileNotFoundException" src="https://user-images.githubusercontent.com/38579068/163315681-9bbe064d-8103-470d-8359-c776b617c66d.png">

**Comment by chenwyi2** [comment]
is this solved? i have this problem, too

**Comment by pvary** [comment]
Do you have a concurrent compaction/cleanup job which removes orphan files?

**Comment by chenwyi2** [comment]
yes, we have removes orphan files,but only remove files which are older than 3 days

**Comment by pvary** [comment]
On HDFS you might have an audit log to check when the files were removed and find out what happend with them based on the timing.
The other thing could be some messed up metadata where the `flink.max-committed-checkpoint-id` is wrong. Out of order commits, or multiple jobs without jobId writing to the same table.

**Comment by chenwyi2** [comment]
what happened if the table metadata has been updated to latest checkpoing and jobid ,but flushing snapshot state to state backend was failed, for examplethe, in the IcebergFilesCommitter calss,  the latest commiting commitOperation has done but snapshotState was failed, what wiil hadppen? this can cause filenotfound ?
