### ISSUE TITLE
Unable to read AWS Glue created iceberg tables from S3

### ISSUE THREAD

**Issue by ganathan** [apache/iceberg#4564]
I am getting the following error when attempting to perform a select statement using trino from an iceberg table created in Glue.

"Query 20220414_160541_00007_h5c3z failed: Error reading tail from s3:///fund_perf_f/data/084faaf5/fund_perf_f/load_date=2022-01-31/1ccc2482-2274-46e2-a5c5-06b4a4c44a6b.gz.parquet with length 7757"

When I checked the physical location of the file.. there is an empty folder in the path.
s3:///fund_perf_f/data//084faaf5/fund_perf_f/load_date=2022-01-31/1ccc2482-2274-46e2-a5c5-06b4a4c44a6b.gz.parquet with length 7757

I have created the table using Athena console and also via a Glue pyspark job with the same end result. Could anyone help resolve this issue?

Not sure if this an Apache Iceberg issue, or AWS issue or Trino issue.

**Comment by amogh-jahagirdar** [comment]
> I have created the table using Athena console and also via a Glue pyspark job with the same end result. Could anyone help resolve this issue?

Just to clarify, you mean you also tried creating the table through Glue Pyspark and after a subsequent read attempt it failed?

**Comment by rdblue** [comment]
Looks like a malformed path since it starts with `s3:///`. There's no bucket.
