### ISSUE TITLE
How to determine iceberg version after table created

### ISSUE THREAD

**Issue by sontt710** [apache/iceberg#4567]
Hello,

I used **iceberg-spark-runtime-3.2_2.12-0.13.1.jar** to create Iceberg table, and I want to verify version of this table is 0.13.1. 

How can I get this version from Spark or catalog, etc..? 

Thanks.

**Comment by RussellSpitzer** [comment]
Iceberg tables only have two possible versions (1 or 2) and this is stored in the format-version table property

**Comment by sontt710** [comment]
Thanks @RussellSpitzer , I agree with you.

But in Our environment have multiple iceberg-spark-runtime-* for testing, so I want to know table was created from which runtime version

**Comment by RussellSpitzer** [comment]
This is not recorded in any way as the version shouldn't make a difference in the spec the table is written with. There should be no material difference other than possibly changing defaults.

**Comment by sontt710** [comment]
thanks @RussellSpitzer
