### ISSUE TITLE
Python library feature proposal: list_partitions api

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#4589]
I am proposing a feature of list_partitions of a given table in the python library.

Similar to https://github.com/apache/iceberg/issues/3843, during the migration from Hive to Iceberg, we see usage on partition listing (`get_partitions` on HMS), thus we want to support similar usage.

**Comment by Fokko** [comment]
Hey @puchengy I'm seeing this just now. This should be quite straightforward to implement in the new `pyiceberg` library. Let me know if this is something that you want to implement.

**Comment by puchengy** [comment]
@Fokko Hey thanks for responding! I don't have a plan to implement it recently due to other priorities. But I am definitely happy to help when available.
