### ISSUE TITLE
publish Iceberg-dell to Apache Maven Repository

### ISSUE THREAD

**Issue by BiuBiu2323** [apache/iceberg#4597]
Could you publish Iceberg-dell to the Apache Maven repository? I'm using maven to import Iceberg-dell dependency, but I can't find it in apache maven repository. Thanks

**Comment by openinx** [comment]
The apache iceberg dell module was introduced in the latest master branch,  and we still don't have an official release for this branch.  I think the next official release will be iceberg 0.14.0 release. 

If you want to access those iceberg-dell modules, you may need to use the official apache snapshots maven repository : https://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-dell/

**Comment by BiuBiu2323** [comment]
> apache iceberg dell 模块是在最新的 master 分支中引入的，我们仍然没有这个分支的正式发布。我认为下一个正式版本将是 iceberg 0.14.0 版本。
> 
> 如果您想访问那些 iceberg-dell 模块，您可能需要使用官方 apache 快照 maven 存储库：[https ://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-dell/](https://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-dell/)

Thanks!
