### ISSUE TITLE
[Docs] Create an item list for re-organizing docs to the proposed layout

### ISSUE THREAD

**Issue by samredai** [apache/iceberg#4607]
Now that we have a proposal for the new navigation flow, we need to translate that to action items. So far there seems to be consensus that we need to move all of the non-versioned material (concepts, quickstarts, and overviews) over to the landing-page and reserve the versioned docs-site for configuration/reference type of material that's expected to include changes with every Iceberg release. The landing-page markdown files are stored in the [iceberg-docs](https://github.com/apache/iceberg-docs/tree/main/landing-page/content/common) repo.

Some good first items are:
- [ ] Move quickstarts to landing-page site (docker-compose and a few quickstart code snippets)
- [ ] Create a single configuration page with only tables of all configuration parameters (Catalog/Table/Compute Engine)
- [ ] Create a high level "Catalog" concept page (no code snippets here)
- [ ] Create a high level "Table" concept page (no code snippets here)
- [ ] Create a high level "Snapshots" concept page (no code snippets here)
- [ ] Create a high level "FileIO" concept page (no code snippets here)

![iceberg-docs-proposal](https://user-images.githubusercontent.com/43911210/164499437-39db663a-1192-4566-9bab-cb9a741dcd68.png)

**Comment by kyle-cx** [comment]
hi @samredai, need any volunteer? 
Will you create an issue for each item? Or do it directly under the current issue?

**Comment by samredai** [comment]
@kyle-cx that would be awesome! I think we can just work on it directly under this issue. Do you want to tackle the "single configuration page"?

Some context around that requirement is that many people found it inefficient to have to search all over the site to find the one configuration table they need. So this item is to take the config tables out of separate sections, like [table](https://iceberg.apache.org/docs/latest/configuration/#table-properties) configs, [spark catalog](https://iceberg.apache.org/docs/latest/spark-configuration/#catalog-configuration) configs and [spark runtime](https://iceberg.apache.org/docs/latest/spark-configuration/#runtime-configuration) configs, and put them in a single `configuration.md` page that's purely a list of tables (perfect for a CMD/Ctrl+F).

**Comment by kyle-cx** [comment]
@samredai ok, I'll tackle the "single configuration page"
