### ISSUE TITLE
Add Checkstyle Rule for Objects.notNull

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#4613]
We prefer Preconditions.notNull in the project (cc: @findepi ) so we should make it a failing rule in the checkstyle tests. Like we ban usages of new HashMap() here

https://github.com/apache/iceberg/blob/master/.baseline/checkstyle/checkstyle.xml#L54-L57

**Comment by tal66** [comment]
is this what you mean?:
```
<module name="RegexpSinglelineJava">
        <property name="format" value="Objects\.requireNonNull.*\(.*\)"/>
        <property name="message" value="Prefer using Preconditions.checkNotNull(Object, String)."/>
</module>
```
this includes: Objects.requireNonNull() + .requireNonNullElse();

second option: 
`value="Objects\.(require|)[Nn]onNull.*\(.*\)"` - the above + Objects.nonNull().

could add it in line 340.

**Comment by RussellSpitzer** [comment]
Yep exactly something like although I haven't checked the regexes you put in there :)

**Comment by RussellSpitzer** [comment]
If you do submit a PR please add a few console logs of the rule in action and failing a build
