### ISSUE TITLE
Add support to alter table comment

### ISSUE THREAD

**Issue by cccs-jc** [apache/iceberg#4615]
I looking for a way to change the table comment. You can create a table with a comment

```sql
CREATE TABLE prod.db.sample (
    id bigint COMMENT 'unique id',
    data string)
USING iceberg
```

You can alter the comment of a column

```sql
ALTER TABLE prod.db.sample ALTER COLUMN measurement COMMENT 'unit is kilobytes per second'
```

But there does not appear to be a way to alter the tables comment.

**Comment by felixYyu** [comment]
you can use `COMMENT ON TABLE my_table IS 'This is my table';`

[](https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-comment.html)

**Comment by kbendick** [comment]
According to the vanilla spark docs, this syntax should also work `ALTER TABLE StudentInfo ALTER COLUMN name COMMENT "new comment";`

**Comment by kbendick** [comment]
For table comment, this should work:

```sql
— SET TABLE COMMENT Using SET PROPERTIES
ALTER TABLE dbx.tab1 SET TBLPROPERTIES ('comment' = 'A table comment.')
```

**Comment by kbendick** [comment]
Both of these examples came from here: https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-alter-table.html

Please let us know if that does not work with Iceberg. If it does, feel free to close this issue 🙂

**Comment by kbendick** [comment]
If it does work, please feel free to open up a small PR to add this to the Spark docs section (or @felixYyu if @cccs-jc says they don’t have time)

**Comment by felixYyu** [comment]
I will open a PR to add this to the Spark docs.  @kbendick
