### ISSUE TITLE
Add checkstyle rule for %d in Preconditions.checkArgument

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#4618]
Reference: https://github.com/apache/iceberg/pull/4558, Preconditions.checkArgument only works with %s, as %d does not parse and returns a bad error message.

We can make a checkstyle rule to prevent this, example of a checkstyle rule:  https://github.com/apache/iceberg/blob/master/.baseline/checkstyle/checkstyle.xml#L54-L57

It should probably use multi-line regex rule as some of these are across multiple lines:  https://checkstyle.sourceforge.io/config_regexp.html#RegexpMultiline (thanks @RussellSpitzer for pointer)

**Comment by selectbook** [comment]
@szehon-ho Hello, I would like to contribute in this issue, Can you assign it to me? thank you

**Comment by felixYyu** [comment]
If you want just do it. @selectbook

**Comment by xrl1** [comment]
Hey, I saw the @selectbook was unassigned and wanted to contribute a first, so I tried to fix it: #5057

**Comment by XN137** [comment]
i am wondering why isnt https://errorprone.info/bugpattern/PreconditionsInvalidPlaceholder catching those violations already? :thinking: 
it should be part of the build already through `com.palantir.baseline-error-prone`
