### ISSUE TITLE
Python: PartitionSpec Construction

### ISSUE THREAD

**Issue by dramaticlly** [apache/iceberg#4631]
From both issue https://github.com/apache/iceberg/issues/3228#issuecomment-1095661430 and pull request https://github.com/apache/iceberg/pull/3407#discussion_r738976688, there's some discussion on how do we build the immutable PartitionSpec with proper validation against every PartitionField 

- in java we leveraged the builder pattern
- in python there's no perfect substitution, some proposed to look into  `PartitionSpec` dunder init.

In this issue, I want to highlight the list of validation we need to enforce before we can construct a valid PartitionSpec. 

Considering its attribute, the PartitionSpec has
- spec_id (int) as unique identifier
- schema (Schema) as data table schema
- list of PartitionField
- lastAssignedPartitionFieldId (int): from offset of 1000, increment 1 for each partitionField

In the meantime, the PartitionField is defined by 
- field_id (int) as unique identifier
- source_id (int), the source id found in table schema
- name (str), human-readable identifier
- transform(Transform), the transformation from source column in data table to partition values, include identity, bucket etc

Validation we want to enforce when build the partitionSpec
- for each partitionField in `__init__` parameter, we want to make sure
  - [`findSourceColumn`](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/PartitionSpec.java#L399), source column in table schema can be found by referencing its name
  - [`checkAndAddPartitionName`](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/PartitionSpec.java#L364),  the new name is neither null nor empty, not duplicated
  - [`checkForRedundantPartitions`](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/PartitionSpec.java#L385), there's no collision on PartitionField in PartitionSpec if we group by tuple of source column id and transform
  - [`checkCompatibility`](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/PartitionSpec.java#L539), lastly we need to make sure source column in table schema have a type such that its type is not null, and is of iceberg primitive type, also the registered transform can transform the given type

**Comment by dramaticlly** [comment]
Since there's some sporadic discussion in both PR and slack (which I cannot see it history unfortunately), so I want to collect the opinion of yours to see if above list of validations above are enough to construct the PartitionSpec in python without the `builder`

CC @rdblue  @samredai  @jun-he

**Comment by samredai** [comment]
Hey @dramaticlly, we all discussed this in the python community sync this past Wednesday. The decision was to go with the builder pattern (a `PartitionSpecBuilder` class) here but to make an attempt to consider the option to directly instantiate a spec using the `PartitionSpec` init method. In Java that class is protected and so you are forced to go through the builder pattern, but it may turn out feasible to allow more flexibility in the python client.

A consideration to keep in mind is that someone directly instantiating a `PartitionSpec` won't have any checks or other logic that the builder offers. As the builder grows in complexity, I'd imagine the option to directly instantiate a `PartitionSpec` becomes less feasible (we wouldn't want to duplicate the builder logic in an overly complex init method for `PartitionSpec`).

Let's keep this issue open and as you work on this, feel free to comment here with anything you find that may require reconsidering all of this.
