### ISSUE TITLE
iceberg bucketing via writeTo api? bucket on a non partitioned column?

### ISSUE THREAD

**Issue by scaladevspark** [apache/iceberg#4646]
I would like to create a bucketed table, e.g.

```
 val df = dfToWrite
    .writeTo(s"iceberg_catalog.$db.$table")
    .partitionedBy(col(TIME_KEY_COL))
    **.bucketBy(200, "ANOTHER_COL")**   _this part is missing from the api_
    .create()
```

Is this currently possible via writeTo? 
https://iceberg.apache.org/docs/latest/spark-ddl/ shows creating buckets via spark-sql

Also, I would like to create buckets on a col that is not a partition col. This does not seem to be possible in iceberg currently as well? Thanks.

**Comment by felixYyu** [comment]
[sql-extensions](https://iceberg.apache.org/docs/latest/spark-configuration/#sql-extensions)

`ALTER TABLE prod.db.sample ADD PARTITION FIELD bucket(16, id)`

**Comment by scaladevspark** [comment]
yes, it can be done via sql as seen in the link I posted.

I am asking if you can do it via writeTo api and if there is a way to do a bucket without a partition

**Comment by kbendick** [comment]
When this is completed, you’ll be able to achieve this for non-partition columns.

https://github.com/apache/iceberg/issues/5349

For now, you can register the function as a UDF and call it like `iceberg_bucket_12(column)` like in this example (and this test suite in general): https://github.com/apache/iceberg/blob/76fabd8435da891809f72862dce3e4d04e159d7d/spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java#L60-L66

**Comment by kbendick** [comment]
`IcebergSpark` has methods for registering other transforms as UDFs as well outside of bucketing (namely `truncate`). But the FunctionCatalog is the future as it can be integrated into Spark for things like code generation and query planning (that would happen first or most likely only on a partition column for the actual join optimization).

**Comment by kbendick** [comment]
But TLDR `IcebergSpark.refisterBucketUDF` Is what you’re looking for right now.

In most likely Iceberg 1.0 (the next non-patch), they’ll be available functions you can use that way.

I’m gonna close this but feel free to reopen if you have any questions still. 👍
