### ISSUE TITLE
Snapshot summary should contain default values

### ISSUE THREAD

**Issue by homar** [apache/iceberg#4647]
Currently snapshot summary, which is a map, contains particular values only if they were affected by changes in that snapshot.
These pieces of information would be easier to use and more feasible if they were always present there and had default values.
For example DELETED_RECORDS_PROP, ADDED_POS_DELETES_PROP, REMOVED_POS_DELETES_PROP, ADDED_EQ_DELETES_PROP etc. could be set to 0 by default.

**Comment by findepi** [comment]
> For example DELETED_RECORDS_PROP, ADDED_POS_DELETES_PROP, REMOVED_POS_DELETES_PROP, ADDED_EQ_DELETES_PROP etc. could be set to 0 by default.

At least for snapshots created with `table.newDelete()....commit()`.

This is needed in Trino to reliably provide number of deleted rows to the user, _also_ when delete happens to delete no files.
(Related discussion https://github.com/trinodb/trino/pull/12136#discussion_r858518648)

**Comment by homar** [comment]
I made a pr for this https://github.com/apache/iceberg/pull/4660
