### ISSUE TITLE
Metadata table queries fail if a partition column was reused in V2

### ISSUE THREAD

**Issue by szlta** [apache/iceberg#4661]
As already discussed in https://github.com/apache/iceberg/pull/3411#discussion_r821845093 this special case will fail to create a metadata schema with the following error:
```
PartitionSpec initialSpec = PartitionSpec.builderFor(SCHEMA)
    .identity("data")
    .build();
TestTables.TestTable table = TestTables.create(tableDir, "test", SCHEMA, initialSpec, V2_FORMAT_VERSION);

table.updateSpec()
    .removeField("data")
    .commit();

table.updateSpec()
    .addField("data")
    .addField("id")
    .commit();

struct<1000: data: optional string, 1001: data: optional string, 1002: id: optional int>
```
gives:
`Invalid schema: multiple fields for name partition.data: 1000 and 1001 `

It's due to how `Partitioning$partitionType` method collects all specs and creates a union partition type. For V2 tables reused partition columns don't get renamed, they just get a new id.

**Comment by d4r3topk** [comment]
This issue has not been resolved yet for V2 API. 

I have a table where one of the columns is "region" and "region" is also part of the partition spec.


I run a query with spark sql - `INSERT OVERWRITE db_name.table_name PARTITION(region = 'us-east-1') SELECT * FROM data`. This leads to Error: `An error occurred while calling o190.sql. Invalid schema: multiple fields for name region: 16 and 17`
