### ISSUE TITLE
MERGE INTO TABLE is not supported temporarily.

### ISSUE THREAD

**Issue by akshayjain-tmdc** [apache/iceberg#4671]
I am not able to resolve this issue as of now.
Spark Version: 3.2.1
Iceberg Version: 0.13.1
I am using "org.apache.iceberg" %% "iceberg-spark3-runtime" % "0.13.1" dependency

Exact Code:

```
object Test {

  val spark: SparkSession = SparkSession.builder()
    .config("spark.driver.bindAddress", "127.0.0.1")
    .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
    .master("local").getOrCreate()

  def main(args: Array[String]): Unit = {
    testUnit()
  }
 
 def testUnit(): Unit = {
    spark.read.format("iceberg").load("abc").createTempView("abc")
    spark.read.format("iceberg").load("xyz").createTempView("xyz")
    val query = "" +
      "MERGE INTO abc AS target " +
      "USING xyz AS source ON target.id = source.id " +
      "WHEN " +
      "MATCHED THEN UPDATE SET target.Data = source.Data " +
      "WHEN " +
      "NOT MATCHED THEN INSERT (target.Data) VALUES (\'New Value\')"
    spark.sql(query).show(false)
  }

}
```

**Comment by RussellSpitzer** [comment]
I can't see your runtime class path but your listing of your runtime dependency is for Spark 3.0 and not 3.2. Please see the quick start docs for the correct dependency and startup config.

https://iceberg.apache.org/docs/latest/getting-started/

**Comment by kbendick** [comment]
We should _really_ consider not publishing the information old iceberg-spark3-runtime.

it’s a breaking change, but arguably it was a breaking change to move from spark3-runtime that supported Spark 3.0 and Spark 3.1 to per version runtime jar.

I think far more users will find the right jar if they go to get the latest version and there’s only jars for specific minor versions.
