### ISSUE TITLE
Partition Summaries Found in Snapshot Summaries for Unpartitioned Tables

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#4689]
When writing to a table that is _not_ partitioned, if the `write.summary.partition-limit` property of the table is set to some non-zero value, partition summaries will be written still.

Here's a sample snapshot summary for an unpartitioned table that received one write. Notice that the prefix `partitions.` is included before the partition summary, which is the [changed partitions prefix](https://github.com/apache/iceberg/blob/3584c79022ec70f79b326550736b4600d249e4a2/core/src/main/java/org/apache/iceberg/SnapshotSummary.java#L54) which is usually followed by a field name and the value for that partition.

```
"summary" : {
      "operation" : "append",
      "spark.app.id" : "local-1651499999454",
      "added-data-files" : "1",
      "added-records" : "1",
      "added-files-size" : "608",
      "changed-partition-count" : "1",
      "partition-summaries-included" : "true",
      "partitions." : "added-data-files=1,added-records=1,added-files-size=608",
      "total-records" : "1",
      "total-files-size" : "608",
      "total-data-files" : "1",
      "total-delete-files" : "0",
      "total-position-deletes" : "0",
      "total-equality-deletes" : "0"
    }
```

Also of note is that if a table was previously partitioned, and then the partition field is dropped, and data is then inserted afterwards, the partition summary can have a reference to the partition field for the value `null`.

```
summary" : {
      "operation" : "append",
      "spark.app.id" : "local-1651499999454",
      "added-data-files" : "2",
      "added-records" : "2",
      "added-files-size" : "1215",
      "changed-partition-count" : "1",
      "partition-summaries-included" : "true",
      "partitions.cat=null" : "added-data-files=2,added-records=2,added-files-size=1215",
...
```

Is there some use case where we intentionally want to include partition summaries for the "global" partition of an unpartitioned table? The same data seems to be available in the rest of the summary, but maybe this was intentional.

I'm almost certain that number 2 is not intentional (though maybe that has something to do with the void transform).

cc @rdblue @RussellSpitzer @flyrain @aokolnychyi @szehon-ho @danielcweeks for visibility.

**Comment by flyrain** [comment]
I'm not aware of any use case that needs partition summary when the table is no partitioned. This looks confusing to me. We may remove it.

**Comment by danielcweeks** [comment]
I think both cases are erroneous.  Partition summaries should only be emitted if the current schema has partitions and the summaries should reflect that schema.

Even if the table previously had summaries, including summaries about prior partitioning strategies would be ambiguous.  There are still edge cases with partition evolution, but the summaries are not a complete view of tables changes.

**Comment by kbendick** [comment]
I think I found the issue for this. PartitionoSpec.unpartitioned() results in a spec of `{"spec-id":0,"fields":[]}`, so I think we need to ensure that the partition specs have fields and are not the void spec.

I will investigate further.

**Comment by kbendick** [comment]
Following up on this
> Also of note is that if a table was previously partitioned, and then the partition field is dropped, and data is then inserted afterwards, the partition summary can have a reference to the partition field for the value null.

This is an artifact of the V1 table's using the void transform, which uses `alwaysNull` for its transform, so this one is a little harder to deal with (and I'm not 100% sure it matters too much as it's for V1 tables and anybody using the partition summaries is likely somewhat of a power user). This is at least well defined behavior.

Otherwise, I have a PR which removes these summaries https://github.com/apache/iceberg/pull/5009.
