### ISSUE TITLE
Spark can not delete table metadata and data when drop table

### ISSUE THREAD

**Issue by cutiechi** [apache/iceberg#4698]
How to delete table data in hdfs when i drop table?

**Comment by felixYyu** [comment]
Can refer to [spark-procedures](https://iceberg.apache.org/docs/latest/spark-procedures/)

**Comment by Zephyr589** [comment]
If you use SPARK SQL, you can use `Drop TABLE [name] purge`

**Comment by felixYyu** [comment]
link #4746
