### ISSUE TITLE
[Spark 3.3] : Support Apache Spark 3.3 in iceberg

### ISSUE THREAD

**Issue by singhpk234** [apache/iceberg#4713]
Hello All Members,

As we might be aware, Spark [v3.3.0-rc1](https://github.com/apache/spark/releases/tag/v3.3.0-rc1) is cut and being actively voted upon.

If someone else is not already working on this, I am happy to pick this up , also happy to collaborate if it's already being worked upon. 

--- 

cc @aokolnychyi @rdblue

**Comment by hililiwei** [comment]
+1

**Comment by abmo-x** [comment]
@singhpk234 
checking to see if you already started working on this? Let me know, happy to work together.

**Comment by singhpk234** [comment]
@abmo-x 
I have started working on it, resolving conflicts due to [SPARK-38085](https://issues.apache.org/jira/browse/SPARK-38085), will update an initial patch soon.

**Comment by singhpk234** [comment]
are you suggesting doing this : 
```
mv spark/v3.2 spark/v3.3
cp -r spark/v3.3 spark/v3.2
```

@hililiwei

**Comment by singhpk234** [comment]
Thanks @hililiwei for highlighting this, this is a good proposal. will make sure I follow this.

**Comment by singhpk234** [comment]
Resolved via https://github.com/apache/iceberg/pull/5094
