### ISSUE TITLE
[Feature Request][Flink][cdc]Iceberg FlinkSink support for writes multiple tables in a database, base on JoinedRowData which have value and value schema

### ISSUE THREAD

**Issue by molsionmo** [apache/iceberg#4723]
**Is your feature request related to a problem? Please describe this feature request.**
Flink CDC now supports  that capture multiple tables in a database into chang log stream:JoinedRowData(with value and value schema). Iceberg FlinkSink can realize a feature that support for writes multiple tables in a database

**Describe the solution you'd like**
org.apache.iceberg.flink.sink.FlinkSink just support one table sink based on change log stream(RowData) with pre-defined structure, such as org.apache.iceberg.flink.sink.TestFlinkIcebergSinkV2#testChangeLogOnIdKey.It has pre-defined structure(id data), and send rows that like record(1, "bbb") one by one.

we can realize another FlinkSink that support for writes multiple tables in a database base on JoinedRowData and catalog.

**Describe alternatives you've considered**

@openinx

**Comment by stevenzwu** [comment]
The main problem I see is that Iceberg doesn't support transaction across multiple tables, which I assume is what this would requires.

**Comment by molsionmo** [comment]
@stevenzwu Thank you for your comment.Do we have any other solutions to this problem that want to writes multiple tables in iceberg? Just insert one by one?

**Comment by molsionmo** [comment]
@stevenzwu Do you have DingDing account? Are you in DingDing group(数据湖技术交流 31584735)
