### ISSUE TITLE
[HadoopFileIO] Empty table directory left after being dropped

### ISSUE THREAD

**Issue by yittg** [apache/iceberg#4735]
The table directory will be still there after being dropped using HadoopFileIO.

We should find a way to clean it. Personally prefer to resolve it directly in HadoopFileIO itself.

cc @kbendick

**Comment by felixYyu** [comment]
- Drop Non empty table  can use `DROP TABLE prod.db.sample`
- Drop empty table shoule must use `DROP TABLE prod.db.sample PURGE`

I think we should add this description in spark-ddl/#drop-table

**Comment by felixYyu** [comment]
@yittg @kbendick

**Comment by yittg** [comment]
@felixYyu Sorry for delay reply. How does it work? Is it spark specific?

**Comment by felixYyu** [comment]
yes, It is spark specific.
