### ISSUE TITLE
flink1.14.4+iceberg0.13.1+hive-metastore3.1.2+minio（S3） error！

### ISSUE THREAD

**Issue by caesar168** [apache/iceberg#4743]
Welcome! Enter 'HELP;' to list all available commands. 'QUIT;' to exit.

Flink SQL> CREATE CATALOG hive_catalog WITH (
>   'type'='iceberg',
>   'catalog-type'='hive',
>   'uri'='thrift://hive-metastore:9083',
>   'clients'='5',
>   'property-version'='1',
>   'warehouse'='s3a://lake/iceberg/vcs'
> );

15:14:12.277 [main] ERROR org.apache.flink.table.client.SqlClient - SQL Client must stop. Unexpected exception. This is a bug. Please consider filing an issue.
java.lang.VerifyError: Stack map does not match the one at exception handler 72
Exception Details:
  Location:
    org/apache/iceberg/hive/HiveCatalog.loadNamespaceMetadata(Lorg/apache/iceberg/catalog/Namespace;)Ljava/util/Map; @72: astore_2
  Reason:
    Type 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' (current frame, stack[0]) is not assignable to 'org/apache/thrift/TException' (stack map, stack[0])
  Current Frame:
    bci: @27
    flags: { }
    locals: { 'org/apache/iceberg/hive/HiveCatalog', 'org/apache/iceberg/catalog/Namespace' }
    stack: { 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' }
  Stackmap Frame:
    bci: @72
    flags: { }
    locals: { 'org/apache/iceberg/hive/HiveCatalog', 'org/apache/iceberg/catalog/Namespace' }
    stack: { 'org/apache/thrift/TException' }
  Bytecode:
    0x0000000: 2a2b b700 9e9a 0016 bb01 0a59 1301 0c04
    0x0000010: bd01 0e59 032b 53b7 0111 bf2a b400 8c2b
    0x0000020: ba02 9600 00b9 00c2 0200 c002 984d 2a2c
    0x0000030: b702 9c4e b200 4113 029e 2b2d b902 6501
    0x0000040: 00b9 0108 0400 2db0 4dbb 010a 592c 1301
    0x0000050: 0c04 bd01 0e59 032b 53b7 0289 bf4d bb01
    0x0000060: 1359 bb01 1559 b701 1613 028b b601 1c2b
    0x0000070: b601 1f13 0209 b601 1cb6 0123 2cb7 0126
    0x0000080: bf4d b801 2cb6 012f bb01 1359 bb01 1559
    0x0000090: b701 1613 028d b601 1c2b b601 1f13 0209
    0x00000a0: b601 1cb6 0123 2cb7 0126 bf            
  Exception Handler Table:
    bci [27, 71] => handler: 72
    bci [27, 71] => handler: 72
    bci [27, 71] => handler: 93
    bci [27, 71] => handler: 129
  Stackmap Table:
    same_frame(@27)
    same_locals_1_stack_item_frame(@72,Object[#152])
    same_locals_1_stack_item_frame(@93,Object[#152])
    same_locals_1_stack_item_frame(@129,Object[#154])

**Comment by caesar168** [comment]
my lib dir：

LICENSE  NOTICE  README.txt  bin  conf  examples  lib  licenses  log  opt  plugins
# cd lib
# ls
commons-logging-1.1.3.jar                  flink-shaded-zookeeper-3.4.14.jar               jdo-api-3.2.jar
datanucleus-api-jdo-5.2.7.jar              flink-sql-client_2.12-1.14.4.jar                log4j-1.2-api-2.17.1.jar
datanucleus-core-5.2.7.jar                 flink-sql-connector-hive-3.1.2_2.12-1.14.4.jar  log4j-api-2.17.1.jar
datanucleus-jdo-query-5.0.9.jar            flink-sql-connector-postgres-cdc-2.2.0.jar      log4j-core-2.17.1.jar
flink-csv-1.14.4.jar                       flink-table_2.12-1.14.4.jar                     log4j-slf4j-impl-2.17.1.jar
flink-dist_2.12-1.14.4.jar                 hadoop-client-api-3.2.2.jar                     metrics-core-3.2.2.jar
flink-json-1.14.4.jar                      hadoop-client-runtime-3.2.2.jar                 sql-client-defaults.yaml
flink-python_2.12-1.14.4.jar               iceberg-flink-runtime-1.14-0.13.1.jar
flink-shaded-hadoop-2-uber-2.8.3-10.0.jar  iceberg-hive-runtime-0.13.1.jar

**Comment by lvyanquan** [comment]
I got this error too, and I found that It may be  incompatible when you using  iceberg-flink-runtime-1.14-0.13.1.jar and flink-sql-connector-hive-3.1.2_2.12-1.14.4.jar  at the same time. You could try only put one single jar at $FLINK_HOME/lib when using SQL Client once at a time.

**Comment by ramdas-jagtap** [comment]
I have same setup of [flink1.13.2+iceberg0.13.0+hive-metastore3.0.0+minio（S3). How are specifying s3 storage properties while creating tables?

CREATE TABLE test_table (   
    `id`          DECIMAL(20, 0) NOT NULL,
    name          STRING,
    address       STRING,
    phone_number  STRING,
    email         STRING,
    PRIMARY KEY (`id`) NOT ENFORCED
  ) WITH (
    'connector'='iceberg',
    'catalog-type'='hive',	
    'catalog-name'='hive_RJ05',	
    'catalog-database'='hive_db05',        
    'uri'='thrift://hive-metastore:9083',	
	'fs.s3a.path-style'='true',
	'fs.s3a.endpoint'='http://minio:9000',
	'fs.s3a.access.key'='xxxxx',
	'fs.s3a.secret.key'='xxxxxxx',
    'fs.s3a.aws.region'='us-east-1',   
    'warehouse'='s3a://s3 bucket path'
  );
  
  I have added below files in flink/lib
  flink-csv-1.13.2.jar           flink-shaded-hadoop-2-uber-2.7.5-10.0.jar       flink-table-blink_2.11-1.13.2.jar               log4j-1.2-api-2.12.1.jar
flink-dist_2.11-1.13.2.jar     flink-shaded-zookeeper-3.4.14.jar               flink-table_2.11-1.13.2.jar                     log4j-api-2.12.1.jar
flink-json-1.13.2.jar          flink-sql-connector-hive-3.1.2_2.11-1.13.2.jar  hive-metastore-3.1.3.jar                        log4j-core-2.12.1.jar
flink-s3-fs-hadoop-1.13.2.jar  flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar  iceberg-flink-1.13-runtime-0.13.0-SNAPSHOT.jar  log4j-slf4j-impl-2.12.1.jar

I am getting below aws error 
[ERROR] Could not execute SQL statement. Reason:
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: XXXXXXX; S3 Extended Request ID: xyz==; Proxy: null)

**Comment by pvary** [comment]
This last error seems different than the original one in the issue. 

403 means that the authentication is failing, and S3 access is not available.

**Comment by ramdas-jagtap** [comment]
@pvary I know the error is diff than the issue. Do we have document for Flink on how to configure flink with Flink with Iceberg, Hive, and Minio. I am more interested in configuration part. 
Thanks!

**Comment by pvary** [comment]
Maybe opening another issue would have been 

> @pvary I know the error is diff than the issue.

Maybe opening another issue would have been better in this case

> Do we have document for Flink on how to configure Flink with Iceberg, Hive, and Minio. I am more interested in configuration part. Thanks!

I do not think we have specific documentation for you case.
We have a general docs: https://iceberg.apache.org/docs/latest/flink/
We have https://iceberg.apache.org/docs/latest/flink/#hive-catalog and https://iceberg.apache.org/docs/latest/flink-connector/#table-managed-in-hive-catalog for Hive Catalog
We have https://iceberg.apache.org/docs/latest/aws/#s3-fileio for S3 access

**Comment by ramdas-jagtap** [comment]
Thanks @pvary for sharing the docs.

**Comment by ramdas-jagtap** [comment]
@caesar168 Were you successful in creating a catalog using the environment mentioned above? If yes please share the Flink client configuration details. As I'm still getting this error 

[ERROR] Could not execute SQL statement. Reason:
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: XXXXXXX; S3 Extended Request ID: xyz==; Proxy: null)

**Comment by adamyasharma2797** [comment]
Approach provided by @lvyanquan worked for me! Thanks!!
