### ISSUE TITLE
Add sequenceNumber method for ContentFile interface

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#4749]
Now the `DeleteFile` and `DataFile` don't have `sequenceNumber` method to get their sequence number directly, so we have to read inherited metadata from `Manifest`. It is not convenient, for example, we use two arrays and `Pair` in the delete file index.  Besides, we may have some actions to deal with deletes in real production, such as cleaning up deletes that have no data file with a smaller sequence number.  It would benefit many places if we could add a method `sequenceNumber`.

This is easy to implement but it changes the spec a bit, but actually, the `DeleteFile` and `DataFile` do have the sequence number in the V2 format definition.

**Comment by szehon-ho** [comment]
Do you mean just add it to the ContentFile API?  Maybe it can be done without changing the spec much, like https://github.com/apache/iceberg/pull/1317 ?

**Comment by chenjunjiedada** [comment]
@szehon-ho, What I want is like this https://github.com/apache/iceberg/pull/4769.
