### ISSUE TITLE
[Question] Flink delete support

### ISSUE THREAD

**Issue by shiyuhang0** [apache/iceberg#4753]
Iceberg supports Delete statement in spark. As for Flink, I don't find anything about delete in the doc.
I want to ask
1. Is iceberg providing any API to do delete in Flink?
2. If not, is there any plan?

thanks

**Comment by Zhangg7723** [comment]
Delete statement is not supported in Flink SQL.

**Comment by shiyuhang0** [comment]
So, iceberg is not able to support delete before Flink SQL supports it?

**Comment by Zhangg7723** [comment]
> So, iceberg is not able to support delete before Flink SQL supports it?

Yes, flink is not good at update and delete operation until it becomes a real batch&streaming engine.

**Comment by shiyuhang0** [comment]
thank you for your answer.
