### ISSUE TITLE
Update the Hive documentation for 4.0.0-alpha-1

### ISSUE THREAD

**Issue by pvary** [apache/iceberg#4805]
With the help of Kristine Hahn we created the documentation for the Hive 4.0.0-alpha-1 Iceberg integration.
See: [hive-ice.pdf](https://github.com/apache/iceberg/files/8715819/hive-ice.pdf)

@rdblue, @samredai: What do you think about the following proposed menu structure:
```
Hive -+-- Getting started
      +-- Type compatibility
      +-- Hive 2/3
      \-- Hive 4.0.0-alpha-1
           +-- DDL
           +-- DML
           \-- Configuration
```

**Comment by pvary** [comment]
cc: @krishanhn

**Comment by pvary** [comment]
@krishahn kindly updated the doc based on your comments @samredai 
[Uploading Hive iceberg documentation.pdf…]()

**Comment by samredai** [comment]
> or we can link a 4.0.0 docker image where the users can try out Hive 4.0.0.

Is this image already available or would we need to create one?

**Comment by pvary** [comment]
> > or we can link a 4.0.0 docker image where the users can try out Hive 4.0.0.
> 
> Is this image already available or would we need to create one?

I would have to ask @kgyrtkirk. He is the one who usually knows these stuff 😄

**Comment by pvary** [comment]
I

> > or we can link a 4.0.0 docker image where the users can try out Hive 4.0.0.
> 
> Is this image already available or would we need to create one?

@samredai: Talked with @kgyrtkirk and he kindly helped me with the commands:
```
# To download and start the Hive in a docker image
docker run --rm -p 10000:10000 --name hive4 -e HIVE_VERSION=4.0.0-alpha-1 -e TEZ_VERSION=0.10.1 -v hive-dev-box_work:/work kgyrtkirk/hive-dev-box:bazaar

# After the pervious command is finished (it takes some time to download the image and start Hive)
# In another terminal, to connect with BeeLine to Hive
docker exec -it hive4 /bin/bash --login -e safe_bl
```

After that you are ready to create Iceberg tables through Hive. I have tried a few commands and it seems working as excepted.

**Comment by pvary** [comment]
@samredai: How could we proceed with merging the Hive documentation to the site?
Can we create the new pages, or you can create the new pages and link them, and we just add the code there?

Thanks,
Peter

**Comment by samredai** [comment]
@pvary I've added the configuration properties to the other PR #4801. Can you open a PR to add the Type Compatibility and DDL sections to the hive page? The DDL support table at the top of the PDF can probably be placed in the beginning of the DDL section instead of "Getting Started". Once that's in, it would be great if you could add a quickstart for Hive. I'll play around with the `hive-dev-box` docker image, is this an official image that makes sense to use in a published quickstart?

**Comment by pvary** [comment]
@samredai: Created the  #4915 with the following changes:
- Type Compatibility - no change here, left it at the end of the page
- Added several paragraphs:
    - Feature support
    - DDL Commands
    - DML Commands

Could you please review?
Thanks,
Peter

**Comment by kgyrtkirk** [comment]
`hive-dev-box` is being used to run all the unit tests of `hive/master` / metastore integration tests and sometime in the future some smoke tests - so in most cases it should work :)
I don't say it's official...but I think its the easiest way to spin-up Hive for some testing ; there are some timestampted labels if you want to be sure to use a specific version...

**Comment by samredai** [comment]
Closing this now that the hive docs are updated. Thanks everyone!
