### ISSUE TITLE
ParallelIterator is using too much memory

### ISSUE THREAD

**Issue by lirui-apache** [apache/iceberg#4822]
ParallelIterator launches multiple threads to read manifest files and store the entries in an unbounded queue. For large tables (~ 2 million data files in our example), planning files can easily lead to full GC or OOM, especially when column stats is included.
We verified that switching to a bounded blocking queue can solve the problem.

**Comment by lirui-apache** [comment]
By analyzing the heap dump, we also noticed some memory inefficiency regarding how column stats is stored. E.g. object overhead ratio is high because there's a map for each single metric.

**Comment by szehon-ho** [comment]
Looks like same issue as reported : https://github.com/apache/iceberg/pull/4596
