### ISSUE TITLE
[Python] Define a TableBuilder API to create a Table, without Transaction API

### ISSUE THREAD

**Issue by dhruv-pratap** [apache/iceberg#4827]
This is a child issue of the parent epic #3227  - Support table in iceberg python library. Please refer the conversations in the parent tracker for design and the Work Breakdown Structure. 

**Scope**: 
I want to define a TableBuilder API to create a Table, without Transaction to begin with.

Mandatory attributes for a table to be created: 
- `Table identifier`
- `Schema`

Optional attributes for a table to be created: 
- `PartitionSpec`
- `SortOrder`
- `Location`
- `Properties`

**Out-of-scope**:
- Implementation of `create()`API is out-of-scope for this and will follow in a subsequent tracker under the parent tracker #3227

**Comment by rdblue** [comment]
What is the purpose of a TableBuilder API for Python? I think that the current `create` method works well because you can already use named arguments and omit unnecessary metadata.

**Comment by Fokko** [comment]
I believe we can close this one: https://github.com/apache/iceberg/blob/master/python/pyiceberg/catalog/__init__.py#L136-L161
