### ISSUE TITLE
can we store metadata and data in different places?

### ISSUE THREAD

**Issue by johndb2016** [apache/iceberg#4834]
there are 2 reasons to separate meta files from data files:
1. meta files are usually small files;
2. meta files are accessed more frequently;

For example, we may have 2 warehouses, like metahouse and datahouse, so we may use a high-performance fs for metahouse, to accelerate metadata access, then we will have a high-performance iceberg table.

**Comment by RussellSpitzer** [comment]
Yes, they have their own config properties so you can put both types of files in different places if you like

**Comment by ajantha-bhat** [comment]
Yes, these are the table properties supported for that.
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/TableProperties.java#L239-L247
