### ISSUE TITLE
where to get started for iceberg?

### ISSUE THREAD

**Issue by ElapsedSoul** [apache/iceberg#4837]
where to get started for iceberg?
for this page:[jara api quickstart for create a table](https://iceberg.apache.org/docs/latest/java-api-quickstart/#create-a-table)

```java
import org.apache.iceberg.hive.HiveCatalog;

Catalog catalog = new HiveCatalog();
catalog.setConf(spark.sparkContext().hadoopConfiguration());  // Configure using Spark's Hadoop configuration

Map <String, String> properties = new HashMap<String, String>();
properties.put("warehouse", "...");
properties.put("uri", "...");

catalog.initialize("hive", properties);
```

this demo do not import the `Catalog`

**Comment by ajantha-bhat** [comment]
yes, this example can be improved.

You can replace `Catalog` with `HiveCatalog` and go ahead. Feel free to open a PR on the example improvement.

**Comment by ElapsedSoul** [comment]
> 



> yes, this example can be improved.
> 
> You can replace `Catalog` with `HiveCatalog` and go ahead. Feel free to open a PR on the example improvement.

Thank you for your help.
Then how can I get the Table table instance for a table I want?
The final goal for me,  it is to rewritedatafiles of the table.
Now I found out there no eg.  for me to work out .

**Comment by ajantha-bhat** [comment]
Once you have a catalog, you can load the table using identifier

import org.apache.iceberg.Table;
import org.apache.iceberg.catalog.TableIdentifier;

TableIdentifier name = TableIdentifier.of("db1", "t1");

// or to load an existing table, use the following line
Table table = catalog.loadTable(name);

once you have the table object, call rewrite data files actions like this.
https://iceberg.apache.org/docs/latest/maintenance/#compact-data-files

You can also check out the code and look for package names and info.

**Comment by ElapsedSoul** [comment]
Thanks for @ajantha-bhat ,
I put the demo code here:
```java

import java.util.HashMap;
import java.util.Map;

import org.apache.iceberg.Table;
import org.apache.iceberg.catalog.TableIdentifier;
import org.apache.iceberg.hive.HiveCatalog;
import org.apache.iceberg.spark.actions.SparkActions;
import org.apache.spark.sql.SparkSession;

public class IcebergMergeFile {
    public static void main(String[] args) throws Exception {

        SparkSession spark = SparkSession
        .builder()
        .appName("IcebergMergeFile")
        .getOrCreate();

        HiveCatalog catalog = new HiveCatalog();
        catalog.setConf(spark.sparkContext().hadoopConfiguration());

        Map <String, String> properties = new HashMap<String, String>();
        properties.put("uri", "thrift://127.0.0.1:9083");

        catalog.initialize("hive", properties);

        TableIdentifier name = TableIdentifier.of("ice_database", "ice_t1");

        // or to load an existing table, use the following line
        Table table = catalog.loadTable(name);
        SparkActions
            .get()
            .rewriteDataFiles(table)
            .option("target-file-size-bytes", Long.toString(500 * 1024 * 1024)) // 500 MB
            .execute();

        spark.stop();
    }
}
```
