### ISSUE TITLE
Can Iceberg support different FileIO for meta and data? 

### ISSUE THREAD

**Issue by johndb2016** [apache/iceberg#4839]
I'd like to write metadata on the local ssd, but data on S3 with Iceberg, and i am wondering whether iceberg supports that. 
Should I provide two kinds of FileIO?
Any help willl be appreciated ~

**Comment by nastra** [comment]
I don't think this is currently supported. In fact we have a potential use case where having this would be helpful and I was planning to work on a prototype for this exact feature this week.

**Comment by singhpk234** [comment]
[doubt] wouldn't [ResolvingFileIO](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java) work here ?

This fileIo based on the location decides which FileIO impl should it use and stores, the instantiated fileIo in a local cache to avoid re-instantiation.

**Comment by nastra** [comment]
IIUC `ResolvingFileIO` has the capability to use different schemes, where `s3` / `s3n` / `s3a` all resolve to `S3FileIO` and `fs` resolves to `HadoopFileIO`. There's no differentiation between which FileIO implemenentation should be used for data and metadata files.

I think the idea behind this ticket is that users would have the capability to explicitly specify which FileIO implementation should be used for data files and which one for metadata files.

**Comment by singhpk234** [comment]
> There's no differentiation between which FileIO implemenentation should be used for data and metadata files.

Agree with you, As per my understanding, wouldn't this differentiation be automatically be done by the `location` produced for meta-data & data path as :
meta-data path would be : `file://mnt/meta-data`
data path would be : `s3://<bucket>/prefix`
(this can be controled via conf's such as `write.metadata.path`). 

Now a user when uses ResolvingFileIO it will implicitly use `HadoopFileIO` for meta-data (i.e paths like `file://mnt/meta-data`), S3FileIO for data (i.e paths like `s3://<bucket>/prefix`).

> I think the idea behind this ticket is that users would have the capability to explicitly specify which FileIO implementation should be used for data files and which one for metadata files.

This sounds like an interesting use case as to why would we want two diff FileIO's when let's say both data / meta-data share the same schemes. One case comes to mind that we want to seperate tuned SDK for S3FileIO obj which would read heavy data files and other has light weight meta-data files.

**Comment by nastra** [comment]
The use case I have in mind for example is: what if users would like to use S3+GCS or simply have different S3 locations for data and metadata files.

**Comment by johndb2016** [comment]
yep, ResolingFileIO works for my case, but much better if iceberg  provides the capability to set custom FileIO for data & meta individually.
