### ISSUE TITLE
Flakey Test TestRemoveOrphanFilesAction3 > orphanedFileRemovedWithParallelTasks causing CI to Fail

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#4856]
The test, `TestRemoveOrphanFilesAction#orphanedFileRemovedWithParallelTasks`. appears to be flakey.

It has caused CI to fail for branches merged into master. 

An example is found in this merge commit, where the Spark 3.2 run failed (though likely it's flakey and not version dependent): https://github.com/apache/iceberg/commit/77b1e9bf1a06323c16a390a9314f9814079a39ba

Failure output
```
org.apache.iceberg.spark.actions.TestRemoveOrphanFilesAction3 > orphanedFileRemovedWithParallelTasks FAILED
    java.lang.AssertionError: Should delete 4 files expected:<4> but was:<3>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.apache.iceberg.spark.actions.TestRemoveOrphanFilesAction.orphanedFileRemovedWithParallelTasks(TestRemoveOrphanFilesAction.java:317)
```

Looking over the task, it seems that we might benefit from using `waitUntilAfter`, or possibly a countdown lock.

Link to the test: https://github.com/apache/iceberg/blob/77b1e9bf1a06323c16a390a9314f9814079a39ba/spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java#L251-L318

Locally this ahas passed for me.

**Comment by singhpk234** [comment]
+1, looks like we should sleep atleast by 1000 ms to avoid scenarios like these [SO](https://stackoverflow.com/questions/24804618/get-file-mtime-with-millisecond-resolution-from-java) where we loose tracking millisecond precision while getting lastModification time.

**Comment by kbendick** [comment]
Adding Russells suggestion now.

**Comment by kbendick** [comment]
This has been fixed
