### ISSUE TITLE
Webpage breaks at medium width

### ISSUE THREAD

**Issue by AndrewJudson** [apache/iceberg#4862]
![Screen Shot 2022-05-24 at 9 05 26 PM](https://user-images.githubusercontent.com/1229570/170177457-50fad5e1-ffd3-43a7-8f9d-263afa93479e.png)

**Comment by kbendick** [comment]
Thanks for the report @AndrewJudson! We are going through a coming docs refactor.

Im by no means a UI / front end dev, but can you clarify what you mean by medium width? Forgive my ignorance. And is this web (if so which browser) or mobile (if so in portrait or landscape)?

We’re hoping the updated docs site will resolve some of these issues, but if you’re interested in helping in that area, I’d LOVE to be of assistance in helping you get reviews etc. The docs are built from `/docs` and we also have a docs repo, github.com/apache/iceberg-docs . If front end is at all within your skill set or interests, I’d be happy to help in any way possible get you set up to contribute. No pressure, but it’s a great way to get involved / familiar with the project and community and always appreciated!
