### ISSUE TITLE
how to integrations object storage with minio/ceph s3 ?

### ISSUE THREAD

**Issue by ming12713** [apache/iceberg#4869]
i want use s3fileio integration object storage like minio or ceph object storage,but not found some BKM for refer.

**Comment by kbendick** [comment]
@samredai made a wonderful blog post, with an associated docker-compose file, for using minio with Spark and Iceberg

**Comment by kbendick** [comment]
Not 100% sure what BKM means, but hopefully that answers your question! I'm going to close this issue, please feel free to reopen it or open a new issue with follow up questions if this doesn't resolve your issue @ming12713 🙂

**Comment by ming12713** [comment]
@kbendick thanks a lot

**Comment by kbendick** [comment]
Yeah no problem. Happy to pass the info along. Many thanks to Sam for providing the great resource.

**Comment by jkl0898** [comment]
> @samredai made a wonderful blog post, with an associated docker-compose file, for using minio with Spark and Iceberg
> 
> Blog Post: https://tabular.io/blog/minio/ Associated Repository with Docker Compose set up: https://github.com/tabular-io/docker-spark-iceberg

hello, we use ceph as object storage, does iceberg support ceph?
