### ISSUE TITLE
How to shorten the merge time of multi-partitioned tables

### ISSUE THREAD

**Issue by Cqz666** [apache/iceberg#4875]
Hi team,
  I use Flink to write data from Kafka to Iceberg. Tables use date and event partitions like 'datekey='20220526' and 'event='xxxx'. 
  Event partitions generate more than 300 partitions per day.
  Because streaming writes produce a lot of small files(It will generate a Parquet file under their respective partitions almost every minute.), I tried using an official Spark program for data merging,as shown below:
```
SparkActions
                    .get()
                    .rewriteDataFiles(table)
                    .filter(Expressions.equal("datekey", dateKey))
                    .filter(Expressions.equal("event", event))
                    .option("target-file-size-bytes", Long.toString(128 * 1024 * 1024))
                    .execute();
```
![image](https://user-images.githubusercontent.com/50294123/170440638-bc7c6306-abfd-42cf-893b-1ae1c3585416.png)

  Unfortunately, it was too slow, taking almost half a day to merge all the data in one day.
  When I try a multi-threaded parallel merge, the commit of the metadata doesn't seem to work, giving this error:
  "Cannot commit: stale table metadata".
 
 Questions are as follows:
  1.How to shorten the data merge time of multi-partition table?
  2.How to coordinate the work of these three action 'rewriteDataFiles','expireSnapshots','deleteOrphanFiles' , I don't know when to execute them and in what order.
  3.Will the iceberg support automatic merging of small files in the future? if yes, it would take a lot less extra work  

  Can someone answer my doubts?   

  ps. My iceberg version is  0.13.1.
   

Best regards,

Cqz

**Comment by kbendick** [comment]
Hi @Cqz666! So it's hard for me to comment on the time it takes for your Spark job to complete, as I'm not sure how much resources you have etc. Also, it does look like you have _many_ small files that are getting compacted.

A few things I would suggest for making your compactions faster (as well as speeding up your ingest somewhat).

First off, you can see many relevent configuration keys by looking at this code here: https://github.com/apache/iceberg/blob/128d5a161fda076118a7cab1d95ab5064400e08a/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java#L79-L87 . I would suggest that you download the project, import it into IntelliJ, and then jump around from there to look at relevant configs. As well as looking at the unit tests.


As for things you can do to speed up the process:

1. Using avro for the Flink ingestion part, then rewriting the files as parquet.
    - This might be something you don't want to tackle right away (it's a large change to your pipeline), but parquet files are somewhat inefficient at such a small size, because they need things like their footer and row groups, which can increase file size. With so little data per file, using Avro might be better recommended.
    - This is completely allowed, as tables can have a mixture of file formats. I would suggest, if Flink is the primary writer to this job, setting the tables `write.format.default` to `avro` and then overriding that in the `options` when using Spark. Please try this on a non-production table first.
2. Breaking the job into several commit groups.
    - By default, compaction jobs write all of their newly written files in _one_ commit of up to 100GB per group. You might consider using the configuration `partial-progress.enabled` se to `true` to allow for work to be committed in more batches. This will cause the data to be committed in up to 10 groups by default, helping you reduce the amount of work that needs to be redone if the underlying table has changed. There's on-going work for smarter detection of change sets so less work needs to be replayed if another writer has committed to the table.

**Comment by RussellSpitzer** [comment]
Agree with @kbendick , Max-concurrent-file-group rewrites alone should be boosted up and that would give you way better performance. It defaults to 1, which is very good if you have very large partitions with lots of big data files, but bad if you have tons of very small partitions with very small data files.

**Comment by kbendick** [comment]
Also, if you can eventually handle it, you can set your `target-file-size-bytes` to a slightly larger value if you add a sort key to the table.

This will make the rewrite job much more expensive, as you'll have to sort, although `write.distribution.mode` can help with that as `range` distribution will use the sort key.

**Comment by Cqz666** [comment]
@kbendick Thank you very much for your patient and detailed reply , which is very helpful to me. I will make some attempts.
@RussellSpitzer Also thank you for your advice.

**Comment by Cqz666** [comment]
Maybe I'm thinking in the wrong direction above, expiring the snapshot via `ExpireSnapshotsAction` might be a better choice, suppose my scene only needs to keep the latest snapshot. Committing snapshot changes will automatically clean up outdated manifest and data files, right?
