### ISSUE TITLE
hive MR insert change iceberg table(create by spark) FORMAT 

### ISSUE THREAD

**Issue by user-GitHub-user** [apache/iceberg#4883]
hive：3.1.2
spark: 3.2.1
iceberg:0.13.1

i set iceberg.engine.hive.enabled=true in my spark hive-site.xml  ,create table by spark:
  CREATE TABLE test (
  `id` INT NOT NULL COMMENT 'id')
USING iceberg;

before insert data by hive, hive create table show :

CREATE EXTERNAL TABLE `default.test`(
  `id` int COMMENT 'id')
ROW FORMAT SERDE 
  'org.apache.iceberg.mr.hive.HiveIcebergSerDe' 
STORED BY 
  'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' 

after hive execute:
insert into test values(1);

hive create table show :
CREATE EXTERNAL TABLE `default.test`(
  `id` int COMMENT 'id')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.FileInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.mapred.FileOutputFormat'

format change,and hive select throw exception:
Output Format must implement HiveOutputFormat, otherwise it should be either IgnoreKeyTextOutputFormat or SequenceFileOutputFormat

if i create table like this:
  CREATE TABLE test (
  `id` INT NOT NULL COMMENT 'id')
USING iceberg
TBLPROPERTIES(
  'engine.hive.enabled' = 'true');

This problem does not occur，so engine.hive.enabled is diff set iceberg.engine.hive.enabled=true?

**Comment by pvary** [comment]
You should set the `iceberg.engine.hive.enabled` to `true` in Hive too

**Comment by user-GitHub-user** [comment]
> You should set the `iceberg.engine.hive.enabled` to `true` in Hive too

thanks
