### ISSUE TITLE
Support ORDERED BY in CTAS statement

### ISSUE THREAD

**Issue by cccs-jc** [apache/iceberg#4889]
The dbt-spark adapter uses CTAS to create tables. 
https://iceberg.apache.org/docs/latest/spark-ddl/#create-table--as-select

```sql
REPLACE TABLE prod.db.sample
USING iceberg
PARTITIONED BY (part)
TBLPROPERTIES ('key'='value')
AS SELECT ...
```
When the table is partition iceberg implicitly performs a order by for the given partitions. However for some tables you want to partition by day and also sort by user_id.

You can achieve this by applying a write ordered by.

https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--write-ordered-by

However there does not seem to be a way to specify the ordered by clause when creating the table i.e.: using a CTAS. I would need this capability to implement support for ORDERED BY in dbt-spark https://github.com/dbt-labs/dbt-spark/issues/343
```sql
REPLACE TABLE prod.db.sample
USING iceberg
PARTITIONED BY (part)
ORDERED BY part, user_id
TBLPROPERTIES ('key'='value')
AS SELECT ...
```

**Comment by shay1bz** [comment]
It seems that Spark ( > 3) does not support creating sorted tables, unless the table is bucketed. Does this mean that the only way to create a sorted Iceberg table (without buckets) is to create it non-sorted, and then apply "WRITE ... ORDERED BY" ?

Currently, we are creating the table with the Java API - not through Spark - with the desired sorting spec, and then writing the DataFrame to the existing, empty table. I'd like to avoid interacting with Iceberg API directly, but the other option (CTAS and then WRITE ORDERED BY) results in 2 Spark jobs. @kbendick I'd really appreciate you opinion on that :D Thanks.
