### ISSUE TITLE
how can we clean the history metadata.json 

### ISSUE THREAD

**Issue by flashJd** [apache/iceberg#4901]
Spark ExpireSnapshotsAction never expire metadata.json, neither the Remove OrphanFilesAction, so I wonder if we could add the metadata.json expire logic in ExpireSnapshotsAction, otherwise there will be a lot of boring history metadata.json exists in file system.
I'm willing to offer a PR if it is worthy

**Comment by samredai** [comment]
Hey @flashJd, there are some table properties that can be used for this, as described [here](https://iceberg.apache.org/docs/latest/maintenance/#remove-old-metadata-files) in the docs.
- `write.metadata.delete-after-commit.enabled`
- `write.metadata.previous-versions-max`

**Comment by flashJd** [comment]
thanks
