### ISSUE TITLE
How to change compression when writing parquet files using pyspark

### ISSUE THREAD

**Issue by CFan7** [apache/iceberg#4914]
I found in docs that I can set the write property:"write.parquet.compression-codec" to change the parquet compression codec when using spark to write, however, I found that didn't work.
I read an essay on stackoverflow, somebody said configure it using `write.option("compression", "uncompressed")`, sadly, things didn't get better.

Here are the ways I have tried
```python
from pyspark.sql import SparkSession

resource_path = "/home/xxx"

if __name__ == "__main__":
    spark = SparkSession \
        .builder \
        .master("local[*]") \
        .appName("iceberg_test") \
        .config("spark.jars.packages", "org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.1") \
        .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
        .config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog") \
        .config("spark.sql.catalog.local", "org.apache.iceberg.spark.SparkCatalog") \
        .config("spark.sql.catalog.local.type", "hadoop") \
        .config("spark.sql.catalog.local.warehouse", "$PWD/warehouse") \
        .config("spark.sql.parquet.compression.codec", "uncompressed") \
        .config("write.parquet.compression-codec", "uncompressed") \
        .getOrCreate()

    # write method1:spark.sql -- doesn't work
    spark.sql("set spark.sql.parquet.compression.codec=uncompressed")
    spark.sql("CREATE TABLE local.db.test1 (num int, character string) USING iceberg")
    spark.sql("INSERT INTO local.db.test1 VALUES (1, 'a'), (2, 'b')")

    # write method2:v1 DataFrame API -- doesn't work
    spark.sql("CREATE TABLE local.db.test2 (path String, modificationTime timestamp, length string, content binary) USING iceberg")
    df = spark.read.format("binaryFile").option("pathGlobFilter", "*.bin").load(resource_path)
    df.write.option("compression", "uncompressed").format("iceberg").mode("overwrite").saveAsTable("local.db.test2")

    # write method3:v2 DataFrame API -- doesn't work
    spark.sql("CREATE TABLE local.db.test3 (path String, modificationTime timestamp, length string, content binary) USING iceberg")
    df = spark.read.format("binaryFile").option("pathGlobFilter", "*.bin").load(resource_path)
    df.writeTo("local.db.test3").option("compression", "uncompressed").append()
```
Is there anyone to help me ?

**Comment by RussellSpitzer** [comment]
So did you try using the table property `write.parquet.compression-codec`? This is a table property you need to set. It looks like you tried using only the Spark property and never the Iceberg one.

On write I believe you can pass through the same thing as a write option ... but I haven't checked, we don't have it doc'd.

**Comment by kbendick** [comment]
Yes the table property `write.parquet.compression-codec` is best. It looks like `write-format` can be set as an optiion for individual writes, but for Iceberg, the table level property `write.parquet.compression-codec` is what you want.

You can update it later if you want to try something new, and then future writes to that Iceberg table will use that codec for parquet files. Generally the codec isn't changed very often.

**Comment by CFan7** [comment]
> So did you try using the table property `write.parquet.compression-codec`? This is a table property you need to set. It looks like you tried using only the Spark property and never the Iceberg one.
> 
> On write I believe you can pass through the same thing as a write option ... but I haven't checked, we don't have it doc'd.

Thank you for your reply! It's true that I mixed up the Spark property with the table property, now everything is on the right track, thanks again!

**Comment by CFan7** [comment]
> Yes the table property `write.parquet.compression-codec` is best. It looks like `write-format` can be set as an optiion for individual writes, but for Iceberg, the table level property `write.parquet.compression-codec` is what you want.
> 
> You can update it later if you want to try something new, and then future writes to that Iceberg table will use that codec for parquet files. Generally the codec isn't changed very often.

You're right, most of the data I need to store are binary files, so I prefer to use `uncompressed` to speed up reading and writing time.

**Comment by kbendick** [comment]
Ahh ok. But `uncompressed` worked with `compression-codec` set to `none`?

**Comment by NhatDuy11** [comment]
hello @CFan7, can you give me an example of compress parquet to gzip , my wish is when i query it to output gzip file , i am working with iceberg table and i am using pyspark language,recommend using  property write.parquet.compression-codec

Mycode:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("CSVICEBERG") \
    .config("spark.jars.packages", "org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0") \
    .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog") \
    .config("spark.sql.catalog.spark_catalog.type", "hive") \
    .config("spark.sql.catalog.local", "org.apache.iceberg.spark.SparkCatalog") \
    .config("spark.sql.catalog.local.type", "hadoop") \
    .config("spark.sql.catalog.local.warehouse", "D:\iceberg_warehouse") \
    .config("spark.sql.defaultCatalog", "local") \
    .config("spark.sql.parquet.compression.codec", "gzip") \
    .config("write.parquet.compression-codec", "gzip") \
    .getOrCreate()
spark.conf.set("write.parquet.compression-codec", "gzip")
spark.sql("CREATE TABLE local.test.cnd10 (name STRING,id INT) using iceberg")
spark.sql("INSERT INTO local.test.cnd10 values ('ABC',1) ")

**Comment by Silver-PN** [comment]
Wish you a good day @kbendick,can you give me an example of compress parquet to gzip , my wish is when i query it to output gzip file , i am working with iceberg table and i am using pyspark language,recommend using property write.parquet.compression-codec. It would be my honor if you could help me

Mycode:
from pyspark.sql import SparkSession

spark = SparkSession.builder
.appName("CSVICEBERG")
.config("spark.jars.packages", "org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0")
.config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
.config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog")
.config("spark.sql.catalog.spark_catalog.type", "hive")
.config("spark.sql.catalog.local", "org.apache.iceberg.spark.SparkCatalog")
.config("spark.sql.catalog.local.type", "hadoop")
.config("spark.sql.catalog.local.warehouse", "D:\iceberg_warehouse")
.config("spark.sql.defaultCatalog", "local")
.config("spark.sql.parquet.compression.codec", "gzip")
.config("write.parquet.compression-codec", "gzip")
.getOrCreate()
spark.conf.set("write.parquet.compression-codec", "gzip")
spark.sql("CREATE TABLE local.test.cnd10 (name STRING,id INT) using iceberg")
spark.sql("INSERT INTO local.test.cnd10 values ('ABC',1) ")

**Comment by ajantha-bhat** [comment]
@NhatDuy11 and @Silver-PN, 

It is a table property. Not a spark property. 
In the create table SQL we can specify the table property. 

```
spark.sql("CREATE TABLE local.test.cnd10 (name STRING,id INT) using iceberg TBLPROPERTIES ('write.parquet.compression-codec' = 'gzip')")
  ```
  
  There is an option to specify them as table-default properties at the catalog level aswell as mentioned by the last two entries of table https://iceberg.apache.org/docs/latest/spark-configuration/#catalog-configuration

**Comment by NhatDuy11** [comment]
@ajantha-bhat hello,
I tried your method again but still did not receive the gzip file, only received the parquet file when querying
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("CSVICEBERG") \
    .config("spark.jars.packages", "org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0") \
    .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog") \
    .config("spark.sql.catalog.spark_catalog.type", "hive") \
    .config("spark.sql.catalog.local", "org.apache.iceberg.spark.SparkCatalog") \
    .config("spark.sql.catalog.local.type", "hadoop") \
    .config("spark.sql.catalog.local.warehouse", "D:\iceberg_warehouse") \
    .config("spark.sql.defaultCatalog", "local") \
    .config("write.parquet.compression-codec","gzip")\
    .getOrCreate()
    spark.sql("CREATE TABLE local.dcn.two (name STRING ,age INT) USING iceberg TBLPROPERTIES('write.parquet.compression-codec'='gzip')").show()
spark.sql("insert into local.dcn.two values ('duy',1) ").show()
spark.sql("SELECT * FROM  local.dcn.two ").show()

**Comment by ajantha-bhat** [comment]
> I tried your method again but still did not receive the gzip file, only received the parquet file when querying

How do you know the parquet file is not compressed with gzip?

**Comment by NhatDuy11** [comment]
hello @ajantha-bhat ,I checked the data folder in my local warehouse, but only received the parquet file, not the gzip file

**Comment by RussellSpitzer** [comment]
The compression is modular (it is inside the parquet file groups). Use `parquet-tools` to check the rowgroup compression And other file metadata.Sent from my iPadOn Sep 21, 2023, at 9:02 PM, NhatDuy11 ***@***.***> wrote:﻿
hello @ajantha-bhat ,I checked the data folder in my local warehouse, but only received the parquet file, not the gzip file

**Comment by NhatDuy11** [comment]
hello @RussellSpitzer , Let me ask about the decompression problem. I use this configuration write.avro.compression-codec "gzip", they only compress the internal data and the default is parquet, right?
