### ISSUE TITLE
Should issue an error/warning message when no data file to delete

### ISSUE THREAD

**Issue by waterlx** [apache/iceberg#492]
I used the following API, trying to delete a data file
```
table.newDelete().deleteFile("file:///path1")
```
And got the following message: INFO SnapshotProducer: `Committed snapshot xxxxx (StreamingDelete)`
I thought the deletion succeeded, but actually it did not, because the data file is "file:/path1", not "file:///path1".
While [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) is another topic, but it would be better to issue an error/warning here when files to delete are not in data files, to warn the user

**Comment by waterlx** [comment]
I used the following API, trying to delete a data file
```
table.newDelete().deleteFile("file:///path1")
```
And got the following message: INFO SnapshotProducer: `Committed snapshot xxxxx (StreamingDelete)`
I thought the deletion succeeded, but actually it did not, because the data file is "file:/path1", not "file:///path1".
While [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) is another topic, but it would be better to issue an error/warning here when files to delete are not in data files.

**Comment by rdblue** [comment]
We could add an option to StreamingDelete to validate that some data is deleted, if you wanted a failure instead of an idempotent delete. Other operations configure validations that are exposed by the base class, MergingSnapshotProducer. We could add a validation method here as well.

**Comment by waterlx** [comment]
May I add a warning to the log but not exit the app to keep the delete as idempotent?  @rdblue

**Comment by rdblue** [comment]
@waterlx, if the validation is configurable then callers can choose whether to ignore the failure or throw an exception. I don't think we should produce warnings for expected behavior, and when this is an idempotent operation I would consider not deleting anything expected behavior.
