### ISSUE TITLE
Can we specify the zorder field when creating a table?

### ISSUE THREAD

**Issue by linfey90** [apache/iceberg#4927]
Now we can set zorder columns when rewrite files.We can also set the order sort like 'ALTER TABLE prod.db.sample WRITE ORDERED BY category, id'. 
Can we specify the zorder field when creating a table? Then the data is distributed when it is written, like sql use: insert into target_xxx select * from source_xxx, then the data in the target table will distributed by zorder columns. Any suggestion do you have?

**Comment by linfey90** [comment]
> No, currently you can only Zorder during rewrites. Work to allow Zorder on all writes is ongoing

OK，thanks very much！I am looking forward to the realization of the function. If possible, I can also reveal some ideas in advance. Which version will be implemented？Looking forward to your reply.

**Comment by minjing0824** [comment]
> 

It will be appreciated if you can solve the problem when I use zoder to speed query . First I rewrite all file of a table by zorder, then I insert some data to the table, I need to use zorder to rewrite all files or not? I see I can set the option "rewrite-all" to true or false, So I don’t know when to set it true or false.

**Comment by akki** [comment]
@JMin824 This ticket is about creating a table with z-order prespecified (like in the `INSERT` SQL). Maybe you would get a response if you create a separate issue for your question (as far as I am understanding your query).

Good luck!
