### ISSUE TITLE
[Support] The generated parquet file name is suffixed with the compress code name

### ISSUE THREAD

**Issue by melin** [apache/iceberg#4928]
Spark Iceberg generates filename suffix without compressed code name，
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/1145830/171428741-7cd63ba6-683e-49c9-baa4-24428491c8ba.png">

Spark parquet generated parquet file name is suffixed with the compress code name，
![image](https://user-images.githubusercontent.com/1145830/171346996-b00d6afb-8f73-4654-b023-319ae00be48a.png)

**Comment by RussellSpitzer** [comment]
What is the issue with this?

**Comment by amogh-jahagirdar** [comment]
This is something I've observed as well. I think it makes sense to add because it's useful to know what the compression codec is just by the filename (from a user perspective). The parquet metadata should still be the source of truth when decompressing but it's more about having context as a user.

**Comment by kbendick** [comment]
We explicitly chose not to, as the file compression can be changed and it's inferred on read for each file. So it's not necessary.

If you want to have it add the extension, there would probably need to be a strong argument for why that's needed / depending on how much work is requireed.

You might try using a custom `LocationProvider`, which is how file paths are determined.
Docs for custom location provider: https://iceberg.apache.org/docs/latest/custom-catalog/#custom-location-provider-implementation
Source code for current location providers: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/LocationProviders.java

**Comment by amogh-jahagirdar** [comment]
Thanks for the explanation @kbendick !
