### ISSUE TITLE
Schema evolution on migrated Hive tables

### ISSUE THREAD

**Issue by lcspinter** [apache/iceberg#4930]
I've been playing with schema evolution on migrated Hive tables and I noticed some inconsistencies. Here is what I did

Create a simple hive table
`CREATE EXTERNAL TABLE customers (id int, first_name string, last_name string) STORED AS PARQUET;`
Insert one record
`INSERT INTO customers VALUES (11, 'Lisa', 'Truman');`
Migrate it to Iceberg
`ALTER TABLE customers SET TBLPROPERTIES " +
        "('storage_handler'='org.apache.iceberg.mr.hive.HiveIcebergStorageHandler')`
Drop a column
`ALTER TABLE customers REPLACE COLUMNS (id int, last_name string)`
Readd the same column
`ALTER TABLE customers ADD COLUMNS (first_name string)`

Running a select query on the readded column will give back the previously inserted record, which I believe is the expected outcome. 

I've added an additional step to the test scenario. Before dropping the column I renamed it. 
`ALTER TABLE customers CHANGE COLUMN first_name first_name_1 string`

If I readd the renamed column and run a query on it I get `null` values.

**Comment by lcspinter** [comment]
@RussellSpitzer Thanks for your reply.

> Data in old files will not be read because we consider that data to be associated with the old column which doesn't exist
Based on my investigations this might be not true. Please check the first part of my example. If I drop a column without renaming it and right after I readd it, I'm able to read the old data. This is what confuses me.

**Comment by RussellSpitzer** [comment]
Oh sorry I see, that alter table statement will not actually migrate a table to iceberg as far as I know. It just marks a table as being an iceberg table. Only Spark currently had migrate and snapshot actions for converting a table

**Comment by lcspinter** [comment]
@RussellSpitzer 
Migration to iceberg is already supported in hive. When I run
`ALTER TABLE customers SET TBLPROPERTIES " + "('storage_handler'='org.apache.iceberg.mr.hive.HiveIcebergStorageHandler')` it will import the files and generate the metadata. Both spark and hive are using the `TableMigrationUtil`to perform the migration.

Nonetheless, the issue is reproducible from spark as well. I wrote a unit test and the symptoms are the same 
- after table migration to iceberg if I drop and readd a column I'm able to read old data
- after table migration to iceberg if I rename, drop and readd a column the data is not read back

**Comment by RussellSpitzer** [comment]
I believe the proper behavior should be that neither allows the old data to be read back. Currently I wrote a repo

```scala
scala> spark.sql("CREATE external TABLE migratetest (foo int, bar int, zaz int) USING PARQUET LOCATION '/Users/russellspitzer/Temp/migratetest'").show

scala> spark.sql("INSERT INTO migratetest (foo, bar , zaz) VALUES (1, 1, 1)")
res7: org.apache.spark.sql.DataFrame = []

scala> spark.sql("call spark_catalog.system.migrate('spark_catalog.default.migratetest')")
res8: org.apache.spark.sql.DataFrame = [migrated_files_count: bigint]

scala> spark.sql("SELECT * FROM migratetest").show
+---+---+---+
|foo|bar|zaz|
+---+---+---+
|  1|  1|  1|
+---+---+---+

scala> spark.sql("ALTER TABLE migratetest DROP COLUMN foo")
res10: org.apache.spark.sql.DataFrame = []

scala> spark.sql("SELECT * FROM migratetest").show
+---+---+
|bar|zaz|
+---+---+
|  1|  1|
+---+---+

scala> spark.sql("ALTER TABLE migratetest ADD COLUMN foo int")
res12: org.apache.spark.sql.DataFrame = []

scala> spark.sql("SELECT * FROM migratetest").show
+---+---+---+
|bar|zaz|foo|
+---+---+---+
|  1|  1|  1|
```

The issue here is that the default name mapping is changed when the second foo column is added, overriding the original name mapping.

Name Mapping in original table : Foo maps to 1
```json
[
 {\n  \"field-id\" : 1,\n  \"names\" : [ \"foo\" ]\n},
 {\n  \"field-id\" : 2,\n  \"names\" : [ \"bar\" ]\n}, 
 {\n  \"field-id\" : 3,\n  \"names\" : [ \"zaz\" ]\n} ]```
```

Name Mapping after dropping "foo" : Foo still maps to 1
```json
[ {\n  \"field-id\" : 1,\n  \"names\" : [ \"foo\" ]\n}, 
{\n  \"field-id\" : 2,\n  \"names\" : [ \"bar\" ]\n}, 
{\n  \"field-id\" : 3,\n  \"names\" : [ \"zaz\" ]\n} 
|]

Name Mapping after adding "foo" back : Foo now maps to 4 *This is incorrect we should not be changing the existing mapping*
```json
[ {\n  \"field-id\" : 1,\n  \"names\" : [ ]\n}, 
{\n  \"field-id\" : 2,\n  \"names\" : [ \"bar\" ]\n},
 {\n  \"field-id\" : 3,\n  \"names\" : [ \"zaz\" ]\n}, 
 {\n  \"field-id\" : 4,\n  \"names\" : [ \"foo\" ]\n} ]
```

I'm on vacation now so i'm not going to look into this more, but IMHO that final default name mapping should be identical to the one when dropping the column. So the error here is in the "ADD COLUMN" code.

**Comment by karuppayya** [comment]
@RussellSpitzer Does how does Iceberg currently handle dropping a column and add the column with same name again, is this scenario similar?
