### ISSUE TITLE
Rewrite Data Files with Manual Sort Order should also use Table Partitioning in Sort Order

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#4931]
Currently when a user provides a SortOrder to RewriteDataFiles to manually override the table sort order it ignores the underlying table partitioning sort. We should still include this even if we are ignoring the table's set SortOrder for other columns.

**Comment by rajarshisarkar** [comment]
I would like to contribute this enhancement. One possible approach I can think of is to combine both the Sort Order (table sort order + manual sort order). Please let me know your thoughts.

**Comment by RussellSpitzer** [comment]
@rajarshisarkar If you have a chance see if you can get a repo test as well. I think in the particular case that this was reported to me it may have also been a rewrite between partition specs with a manually specified order...
