### ISSUE TITLE
Caching Data In Memory

### ISSUE THREAD

**Issue by ymZhao1001** [apache/iceberg#4940]
**Is your feature request related to a problem? Please describe this feature request :** 
In some multi-table associative query scenarios, the data volume of the dimension table is small and the update is slow. We can cache the dimension table in memory to improve query performance

**Describe the solution you'd like :** 
Add a cache attribute to the table, then we use spark.catalog.cacheTable("tableName") or implements the LookupTableSource in flink connector to cache table in Spark and Flink, for example 

@rdblue  @kbendick   what do you thinik of it ? It would be a pleasure to hear your thoughts

**Comment by kbendick** [comment]
Is it not already possible to use `spark.table("iceberg.tableName").cache` using the normal Spark cache?

**Comment by ymZhao1001** [comment]
> Is it not already possible to use `spark.table("iceberg.tableName").cache` using the normal Spark cache?

i am not sure about this. The key point is it necessary to cache data? if it is necessary , it depends on iceberg or the compute engine? Looking forward to your reply

**Comment by ymZhao1001** [comment]
closed by 
https://github.com/apache/iceberg/pull/4649
