### ISSUE TITLE
revapi plugin will not work in an non-english locale computer

### ISSUE THREAD

**Issue by KarlManong** [apache/iceberg#4959]
Ref https://github.com/palantir/gradle-revapi/issues/550.

It starts from https://github.com/apache/iceberg/pull/4638

Once running build in an non-english  computer, it failed:

```
$ ./gradlew build -x test -x integrationTest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59821  100 59821    0     0  61926      0 --:--:-- --:--:-- --:--:-- 61862
Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.4.2!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':iceberg-api:revapiAnalyze'.
> Failed to query the value of task ':iceberg-api:revapiAnalyze' property 'oldApiJars'.
   > Failed to query the value of extension 'revapi' property 'oldVersions'.
      > Failed running command:
                Command:[]
                Exit code: 128
                Stdout:
                Stderr:fatal: 没有标签能描述 '7ff467106431cdd8715aeec9b5f58458dc5d2102'。
        尝试 --always，或者创建一些标签。


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Export `LANGUAGE=en_US` can solve this problem.

But I prefer using another version of revapi plugin.

cc @kbendick

**Comment by kbendick** [comment]
I don’t necessarily know of another version of the Revapi plug-in for gradle. Have any input on that subject @KarlManong?

Also, what happens if you set the lang 
Ideally we can get them to fix this upstream?

And what is your `LANGUAGE` configured to or how can we otherwise replicate this?

**Comment by KarlManong** [comment]
I'm not familiar with Revapi, so can't give an idea.

My computer is running as this LANGUAGE
```shell
$ echo $LANGUAGE
zh_CN:en_US:en
```
Just set the $LANGUAGE can reproduce the issue.

Maybe we can comment the build doc which set the LANGUAGE before building.

By the way, according https://stackoverflow.com/questions/10633564/how-does-one-change-the-language-of-the-command-line-interface-of-git, there has some other ways to  change the output language of the Git.

**Comment by kbendick** [comment]
No worries about your English.

I think it’s best in the long run to ask the project to set the language if they depend on the output string (which they do).

For now, if running with LANGUAGE before the build helps, we can consider adding that the the FAQ for users who hit this issue. We can also set the LANGUAGE value in the GitHub actions, though that won’t fix the local.

I’ll try reproducing and then also commenting on the issue in the project that you opened.

Definitely at least making note of this in our documentation in an FAQ would be good. Thanks @KarlManong!

**Comment by KarlManong** [comment]
Yes, FAQ would be good.

Thank U too.
