### ISSUE TITLE
whether flink.actions.RewriteDataFilesAction does not implement option

### ISSUE THREAD

**Issue by JunjianS** [apache/iceberg#4970]
flink:1.13.5
iceberg-flink-runtime-1.13:0.13.1

Iceberg provides API to rewrite small files into large files by submitting flink batch job. The behavior of this flink action is the same as the spark’s [rewriteDataFiles](https://iceberg.apache.org/docs/latest/maintenance/#compact-data-files).

<img width="1381" alt="截屏2022-06-06 22 13 24" src="https://user-images.githubusercontent.com/7474234/172178625-fc8f7288-6cdb-4b12-a07c-c070a40cabec.png">

 However, I get some error: 

<img width="1411" alt="截屏2022-06-06 22 09 15" src="https://user-images.githubusercontent.com/7474234/172178680-93b03399-1519-458a-9fe8-4529f40891db.png">
whether flink.actions.RewriteDataFilesAction does not implement option ？ how to use flink RewriteDataFilesAction ?

**Comment by luoyuxia** [comment]
I think you can just remove `.option()`.
