### ISSUE TITLE
new snapshot file(../metadata/snap-xxx.avro) will be generated as checkpoint commit, even though there is no data from cdc

### ISSUE THREAD

**Issue by JunjianS** [apache/iceberg#4971]
flink:1.13.5
iceberg-flink-runtime-1.13:0.13.1
flinkcdc:2.2.0

i write iceberg table with flink cdc from mysql, but i found new snapshot file(../metadata/snap-xxx.avro) will be generated as checkpoint commit, even though there is no data from cdc.  how to do not generate new snapshot file when there is no data in the checkpoint commit. Thank you very much.

**Comment by kbendick** [comment]
Hi @JunjianS!

Thanks for your interest and report.

You’re right that a commit is generated. I know in other places we do that for what is effectively a no-op (or might be viewed as one).

Some people have argued in some cases that they _do_ want the commit to occur / new snapshot to be present, to still represent that the action took place.

Perhaps this might be better suited for the user (or even dev) mailing list? I know there have been many opinions on whether or not certain operations should generate commits.

**Comment by kbendick** [comment]
As an aside, may I ask what you have you max concurrent checkpoints set to with Flink? I would advise you keep it at 1.

Additionally, I would advise that you configure (via Flink configuration) a minimum time between checkpoints.

Defining a minimum time between checkpoints (default is zero) ensures that if a checkpoint takes place, if it takes long enough to complete that another checkpoint would have already started, that checkpoint is skipped to allow the engine time to process more data.

I know that an empty commit could still occur in some scenarios, for example a Kafka topic might not receive data at all for 10 minutes.

But if you’re not using those two Flink configurations, I highly suggest you do as they will reduce the chances of this happening and also generally make your jobs more stable. 🙂

**Comment by JunjianS** [comment]
@kbendick Thank you for your advice.
