### ISSUE TITLE
Support Kafka Connect within Iceberg

### ISSUE THREAD

**Issue by kondamudikarthik** [apache/iceberg#4977]
Currently, data ingestion into Iceberg tables is only supported by Spark, Presto, and Flink. It would be nice to support ingestion via Kafka Connect as well.

cc @kbendick

**Comment by youngxinler** [comment]
Write to iceberg should be use compute enginer,  computing and storage should be separated.
Iceberg itself has no computing power;  Writing and reading should be done by a computing framework.
It may be better to use Flink CDC to make Kafka write to iceberg.

**Comment by kbendick** [comment]
That said, I’d love to know of / hear from people who have Kafka Connect experience and would be interested in helping contribute code or review code! I’m by no means an expert with Kafka Connect, but I can gladly help with the Iceberg side of things.

**Comment by youngxinler** [comment]
thanks for @kbendick discussion,  i agree for @kbendick  advice,  althought usually sometime we use compute engine to write, but kafka is very popular,  if iceberg support kafka connector to iceberg, it will help more developer who use iceberg or want to use iceberg.

**Comment by kondamudikarthik** [comment]
Thanks, @kbendick. That's right having the ability to ingest data into Iceberg via Kafka Connect is a very powerful feature to have. @youngxinler I'm working on spec for the same, keep an eye on this space for more updates.

**Comment by almogtavor** [comment]
A nice implementation project at the subject - https://github.com/getindata/kafka-connect-iceberg-sink

**Comment by code-magician323** [comment]
@kbendick Do you think there will be progress at this area soon?

**Comment by jaehyeon-kim** [comment]
+1 for Kafka connect.

**Comment by ddcprg** [comment]
Are there any progress on this area? If that's not the case, we are working on a connector at the moment and hopefully we'll be able to open source it

**Comment by kondamudikarthik** [comment]
We just started working this, timeline wise we think in a month or so we should be able to get it out.

**Comment by jvican** [comment]
Excited to hear you're working on it @kondamudikarthik Is progress happening in the OSS repo or internally somewhere else?

**Comment by ddcprg** [comment]
we've just open sourced this https://github.com/10xfuturetechnologies/kafka-connect-iceberg if anyone is interested

**Comment by Fokko** [comment]
Hey everyone, the Kafka connect sink by Tabular has been donated to Iceberg in https://github.com/apache/iceberg/pull/8701. I go ahead and close this issue, feel free to open up a new one if there are any further questions.

**Comment by ajantha-bhat** [comment]
> Hey everyone, the Kafka connect sink by Tabular has been donated to Iceberg in https://github.com/apache/iceberg/pull/8701. I go ahead and close this issue, feel free to open up a new one if there are any further questions.

Note: Just the initial PR got merged. Still a long way to go. But yeah, we can close this issue mentioning it is already supported from https://github.com/tabular-io/iceberg-kafka-connect and is also in the process of donation.
