### ISSUE TITLE
Flink: [doc] Is there a full example for Iceberg+Flink+Aliyun OSS ?

### ISSUE THREAD

**Issue by noneback** [apache/iceberg#4981]
I am trying to use Aliyun OSS + Iceberg + Flink， but I cannot find a good example or tutorial .

**Comment by noneback** [comment]
@openinx

**Comment by noneback** [comment]
How to use hadoop as the catalog?

**Comment by ajantha-bhat** [comment]
https://iceberg.apache.org/docs/latest/flink/#hadoop-catalog

**Comment by noneback** [comment]
No reply. So I just close this issue.
