### ISSUE TITLE
 rewritedatafile: Cannot commit, found new position delete for replaced data 

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#4996]
i use spark to run rewritedatafile， and i have a flink job write this table every 5 min, but if the rewritefatafile spend more than 5 min, it will commit error with "ValidationException: Cannot commit, found new position delete for replaced data file: GenericDataFile{content=data, file_path=qbfs://online01/warehouse/prod_censor_datalake.db/document/dataxxx", so there is a good solution? so now i must keep rewritedatafile in 5 min, otherwise it will commit failed

**Comment by chenwyi2** [comment]
and i already use using use-starting-sequence-number variable, iceberg version is 0.13.1

**Comment by chenwyi2** [comment]
we use cdc mode, the data is always changing, even if we use strategy to auto-retry,  rewritedatafile will always be failed

**Comment by humengyu2012** [comment]
My iceberg version is 1.0.0, but the same problem occurs.

**Comment by humengyu2012** [comment]
Is there any recent progress on this issue?

**Comment by anistal** [comment]
Same here, it is a big issue because we can not ingest and optimize at the same time. Is there any idea or workaround to solve it?
