### ISSUE TITLE
which iceberg-spark jar should I choose? 

### ISSUE THREAD

**Issue by shiyuhang0** [apache/iceberg#5015]
I have found three types of spark jar in maven central:
- iceberg-spark3-runtime
- iceberg-spark-runtime
- iceberg-spark-runtime-${spark_version}_${scala_version}

Can you help to explain the difference of them?

**Comment by RussellSpitzer** [comment]
Iceberg Spark is 2.4
Iceberg Spark3 is 3.0
All other versions are for that specific Spark version 

The Spark and Spark3 naming are historical from before we decided to break the build into separate modules.

**Comment by shiyuhang0** [comment]
thanks
