### ISSUE TITLE
Can I change catalog's name

### ISSUE THREAD

**Issue by shiyuhang0** [apache/iceberg#5028]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/52435083/173487626-b1b29f71-c7f4-472a-9e9c-b2242edfb76a.png">

Can I change the catalog's name and use the new name.
For example：change `spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog` to `spark.sql.catalog.${new_name}=org.apache.iceberg.spark.SparkCatalog`

**Comment by romibuzi** [comment]
Hi @shiyuhang0, yes you can name your catalog as you want. 
Then you will reference it in you spark sql queries: 
```sql
"CREATE TABLE ${your_catalog_name}.db.table (id long, data string) USING iceberg"
```

**Comment by shiyuhang0** [comment]
thank you for your answer
