### ISSUE TITLE
Python: Decimal scale can't be greater than precision

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#5038]
https://github.com/apache/iceberg/pull/5011#discussion_r895229695

**Comment by rdblue** [comment]
We should consider what we want to do here. Technically, you could have lower precision if you wanted to store really really small values. For example, a `duration_seconds` column with nanosecond precision and is never greater than 1 millisecond could be stored as `decimal(6, 9)`. This is allowed by the spec currently. We don't state that P >= S.
