### ISSUE TITLE
Docs: missing bigint in available types

### ISSUE THREAD

**Issue by romibuzi** [apache/iceberg#5054]
Hi. I see in many examples usage of `bigint` type but it is not listed in documentation: https://iceberg.apache.org/docs/latest/schemas/. Is it the same as long type ?

**Comment by wuwenchi** [comment]
1.  `bigint` in flink will be converted to `long` in iceberg. For other flink type conversions, you can look #4865.
2. `bigint` in spark is same as `long` in spark, `long` in spark will be converted to `long` in iceberg. For other spark type conversions, you can look https://iceberg.apache.org/docs/latest/spark-writes/#spark-type-to-iceberg-type.

**Comment by romibuzi** [comment]
Thank you @wuwenchi ! does that means that technically there is no `bigint` type in Iceberg ?

**Comment by wuwenchi** [comment]
Yes, I personally think so.

**Comment by romibuzi** [comment]
Indeed in the end there is just long type in Iceberg: https://github.com/apache/iceberg/blob/44c1d00b37f0d7fc2e978baad4f7a861a8335cf0/api/src/main/java/org/apache/iceberg/types/Types.java#L46. Thanks @wuwenchi i am closing this.
