### ISSUE TITLE
iceberg v2 table cannot expire delete files after rewrite datafile action

### ISSUE THREAD

**Issue by eric666666** [apache/iceberg#5058]
I'm using v2 format iceberg table.  When i use spark3.2 rewrite iceberg datafile (extrally add an where cause statement) . And i use expire statement to expire old delefiles, i see only the old small data files are deleted ,but the 'equalitly delete file' and 'position delete file' cannot be deleted. They will still remain in filesystem.
rewrite datafile sql is
```
CALL hive_prod.system.rewrite_data_files(table => 'test.mock_pre_dwv'
, where  => 'dt >= "2022-06-04" '
, options => map (
    'delete-file-threshold','1'
    ,'min-input-files','1'
    ,'partial-progress.enabled','true'
    ,'max-concurrent-file-group-rewrites','20'
    )
 );
```
expire snapshot sql  is

`CALL hive_prod.system.expire_snapshots(table => 'test.mock_pre_dwv', older_than => timestamp '2022-06-08 11:31:49',retain_last => 1) ;`
Spark expire action execute result:
  {
    "deleted_data_files_count": 5
    "deleted_position_delete_files_count": 0,
    "deleted_equality_delete_files_count": 0,
    "deleted_manifest_files_count": 588,
    "deleted_manifest_lists_count": 319
  }

**Comment by Initial-neko** [comment]
The deletefile without datafile Association will be cleaned up; Maybe your datafile is the best size. You can try to increase the size of the rewritten file so that all files can be rewritten. This will clean up all old deletefiles

**Comment by eric666666** [comment]
> The deletefile without datafile Association will be cleaned up; Maybe your datafile is the best size. You can try to increase the size of the rewritten file so that all files can be rewritten. This will clean up all old deletefiles

Thanks for your reply! I‘m already set 'min-input-files'='1' , so it will rewrite all datafiles. But the equality delete file and pos-delete file  can not remove from expire snapshot action.
I test it seems like occour on partition table which added where cause in rewrite_data_files action.

**Comment by szehon-ho** [comment]
Would it happen to be because https://github.com/apache/iceberg/issues/4127. ?  (Check the sequence number of the delete file, maybe it's the same and hence it's not getting deleted)

**Comment by eric666666** [comment]
> Would it happen to be because #4127. ? (Check the sequence number of the delete file, maybe it's the same as your data files and hence it's not getting deleted)

I test again. It seems because of partition table's sequence number problem. Do you have a test with PR #3990.

**Comment by szehon-ho** [comment]
I think pr #3990 wont work, it is too much to do in the commit phase, and we need a spark action.

**Comment by cbwn123** [comment]
I have same problem by using SparkActions.get(ss).rewriteDataFiles function.

**Comment by szehon-ho** [comment]
I think the way to do this is to write a Spark job that finds 'dangling' delete files (that is, delete files that don't point to any live data file).  I think once this pr is in:  https://github.com/apache/iceberg/pull/4812, we can implement the new Spark action 'removeDanglingDeleteFile'.  I think this was in the original delete file design doc https://docs.google.com/document/d/1-EyKSfwd_W9iI5jrzAvomVw3w1mb_kayVNT7f2I-SUg/edit#heading=h.fxypqdd7zxcj

**Comment by lintingbin2009** [comment]
This is a very serious problem, we use date as the iceberg table partition, detefile can never be cleaned up, unless all data files are rewritten.

**Comment by szehon-ho** [comment]
I'm working on this, in the end we plan to have a RewriteDeleteFilesSparkAction.   As part of the rewrite, we will do the cleanup of dangling position deletes (ie, unused ones)

Almost all the pieces are there.  #6365 #6716 #7029 , then after this the action itself.

**Comment by pnain** [comment]
I can still see this issue is not resolved 100%. while querying manifest$files, I can see less file compared to number of files on S3
