### ISSUE TITLE
StructLikeWrapper equals method is broken

### ISSUE THREAD

**Issue by homar** [apache/iceberg#5064]
I ran into a situation when I had to check if two StructLikeWrapper are equal.  
Those were results of some operations on partition schema (details here https://github.com/trinodb/trino/issues/12874)
Their structs fields were different:
1. `struct<1000: event_time_day: optional date, 1001: level: optional string>` 
2. `struct<1001: level: optional string, 1002: event_time_hour: optional int>` 

Different types of fields resulted in `IllegalArgumentException` thrown from https://github.com/apache/iceberg/blob/a38e66323a99b65f433cb6e96007674a741a2f5a/core/src/main/java/org/apache/iceberg/util/StructLikeWrapper.java#L76

I think it should just return false instead of throwing an exception

**Comment by findinpath** [comment]
Note that the operation is `compare` (returning `-1` /  `0` / `1` and not `equals`). If the provided arguments are not comparable, I think throwing IAE is correct.

**Comment by homar** [comment]
> Note that the operation is `compare` (returning `-1` / `0` / `1` and not `equals`). If the provided arguments are not comparable, I think throwing IAE is correct.

So maybe it should not be used as a part of equals method or maybe the exception should be caught? The ticket is about equals being broken.

**Comment by alexjo2144** [comment]
Maybe `StructLikeWrapper` should keep track of the `type` that's passed in to the constructor and should check the types are equal before calling `compare` in equals

**Comment by homar** [comment]
> Maybe `StructLikeWrapper` should keep track of the `type` that's passed in to the constructor and should check the types are equal before calling `compare` in equals

That may work. I didn't think about solution yet. I just reported a problem ;)

**Comment by szehon-ho** [comment]
Yea the trick is both StructLikeWrapper need the same type to compare.  It may be risky to change it at this point?

@findinpath there's a few prs on master fixing partitions table, not released yet, did you check with those?  In particular #4560 and #4516 and #4637 (the first one being perhaps the more pertinent for this issue).

**Comment by alexjo2144** [comment]
https://github.com/apache/iceberg/pull/5157
