### ISSUE TITLE
Remove withPartitionPath from the public API

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#507]
Several issues (#428, #505) have been opened where people are using `DataFiles.Builder#withPartitionPath` to parse partition key strings. This is an anti-pattern and Iceberg should not support serialization to and from string. Conversion to a partition key is a one-way conversion.

Having the `withPartitionPath` method in the public API encourages using this anti-pattern. I think we should remove it.

**Comment by rdblue** [comment]
@aokolnychyi, @prodeezy, what do you think about this issue and possibly targeting this for the release?

**Comment by aokolnychyi** [comment]
We used that only for importing existing tables to Iceberg. We tests but I haven't seen a real use case that required it.

**Comment by rdblue** [comment]
Yeah, for importing, I'm wondering if we shouldn't require going through an import API call, like the one in `SparkTableUtil`. That would make imports still work, but avoid a misleading call in the API.

**Comment by aokolnychyi** [comment]
That would work for us. We developed our version of migration before we had it in `SparkTableUtil`.

**Comment by prodeezy** [comment]
We unfortunately depend on this currently but we will work on taking this out. 
cc @fbocse @rominparekh

**Comment by rdblue** [comment]
@prodeezy, we'll leave it in for now. Just let us know when you've moved away from it.
