### ISSUE TITLE
Support UNSET of sortOrder from the SQL

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#5071]
Currently, users can set sort_order using `ALTER TABLE ... WRITE ORDER BY `in SQL.
But if the users feel data loading is slow because of sorting and want to reset it. There are no options from SQL. We need to provide one.

from API, `table.replaceSortOrder().commit()` will set to `SortOrder.UNSORTED_ORDER`
But the requirement is from the pyspark users who use only SQL with Iceberg.

**Comment by puchengy** [comment]
Can we reopen this given this feature is useful?

**Comment by RussellSpitzer** [comment]
Isn't this supported via UNORDERED or did that not get into OSS yet?

**Comment by ajantha-bhat** [comment]
> Isn't this supported via UNORDERED or did that not get into OSS yet?

I saw the code, looks like syntax is there but no where documented or have testcase. 
I will add documentation and test via this issue. 

This is the syntax.
`sql("ALTER TABLE %s WRITE UNORDERED", tableName);`

**Comment by ajantha-bhat** [comment]
There is a test case also
https://github.com/apache/iceberg/blob/b9a4478b0f8f5eeae553eb3900b08a7a08dbdb40/spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java#L167

Only doc update is pending. I will raise PR. No need to keep this as issue.
