### ISSUE TITLE
Add a connector for Python Flink DataStream API

### ISSUE THREAD

**Issue by deadwind4** [apache/iceberg#5086]
Inspired by other Python Flink connector  for DataStream API.
Looks like https://issues.apache.org/jira/browse/FLINK-18887

**Comment by Fokko** [comment]
Hey @deadwind4 Thanks for opening the issue. Could you elaborate a bit more on how you would see this?

I'm new to the Flink connectors, and I see it being used with Elastic as you mention in the linked issue above. And in the examples of Flink itself with Kafka: https://nightlies.apache.org/flink/flink-docs-master/docs/dev/python/table/python_table_api_connectors/

For the tables that we create, we recommend setting the type of the catalog to Iceberg, and that way you'll create iceberg tables inside of that catalog. Examples are given in our docs: https://iceberg.apache.org/docs/latest/flink/#create-table

Let me know what you think!
