### ISSUE TITLE
Docs: Add copyright style and configuring copyright for IDEA

### ISSUE THREAD

**Issue by deadwind4** [apache/iceberg#5111]
Add the "how to set copyright" in the doc of contributing.

Inspired by the Flink official doc, https://flink.apache.org/contributing/code-style-and-quality-common.html and https://nightlies.apache.org/flink/flink-docs-master/docs/flinkdev/ide_setup/#copyright-profile

related PR: https://github.com/apache/iceberg-docs/pull/95

**Comment by nastra** [comment]
fixed by https://github.com/apache/iceberg-docs/pull/95
