### ISSUE TITLE
Flink: FLIP-143 & FLIP-191 based Iceberg sink

### ISSUE THREAD

**Issue by hililiwei** [apache/iceberg#5119]
In Flink 1.12 the community focused on implementing a unified Data Sink API ([FLIP-143](https://cwiki.apache.org/confluence/display/FLINK/FLIP-143%3A+Unified+Sink+API)). The new abstraction introduces a write/commit protocol and a more modular interface where the individual components are transparently exposed to the framework.

In Flink 1.15 the community extend the unified Sink API to broaden the spectrum of supported scenarios and fix the small-file-compaction  problem.

I suggest that we optimize Iceberg's Flink sink based on the above FLIP.

There is a preliminary proposal: 
https://docs.google.com/document/d/1G4O6JidAoKgbIdy8Ts73OfG_KBEMpsW-LkXIb89I5k8/edit?usp=sharing

and a PR: https://github.com/apache/iceberg/pull/4904

Thanks to @kbendick for your assistance in this.

**Comment by hililiwei** [comment]
im working on it.

**Comment by zhaofuw** [comment]
Is there any latest progress in this work?

**Comment by hililiwei** [comment]
> Is there any latest progress in this work?

Further discussion is clearly warranted.
