### ISSUE TITLE
No way to rollback first commit in table

### ISSUE THREAD

**Issue by harnsit** [apache/iceberg#5141]
We are using system.rollback_to_snapshot to rollback a table.  It works fine as long as the parent_id exists.  

After doing first insert into the table, there is no way to rollback to the original state of the table.

```
spark-sql> select * from hive_prod.default.test_iceberg.history;
2022-06-27 17:05:26.985	8757768064614539325	NULL	true
```

The first history snapshot has NULL as parent id.

```
spark-sql> call hive_prod.system.rollback_to_snapshot('hive_prod.default.test_iceberg', NULL);
Error in query: 
no viable alternative at input 'NULL)'(line 1, pos 81)
```

Is there a way or do I have to delete all rows from the table?

**Comment by kbendick** [comment]
Since this is the first commit of a table, you could potentially get the create table DDL from spark `SHOW CREATE TABLE` and then do some variant of `REPLACE TABLE <tbl>`.

Sort of a hack, but might be a worthwhile avenue of investigation.
