### ISSUE TITLE
Iceberg Vectorized code path to support dictionary encoded data

### ISSUE THREAD

**Issue by anjalinorwood** [apache/iceberg#518]
String data type is very frequently dictionary encoded. Categorical data expressed using other data types is also frequently dictionary encoded. This milestone is to support vectorized read of such dictionary encoded data by copying (the whole or skinnied down) dictionary into arrow buffer. Not paying the penalty to deserialize and serialize the data and being able to apply predicates on the dictionary encoded data would be crucial for performance.

**Comment by samarthjain** [comment]
Support for dictionary encoded data was merged to the vectorized_read branch. 
https://github.com/apache/incubator-iceberg/pull/634
