### ISSUE TITLE
Optimize reading of String data type in vectorized Iceberg code path

### ISSUE THREAD

**Issue by anjalinorwood** [apache/iceberg#519]
Vectorized Iceberg read of all primitive data types except 'string' data type is at parity with Spark data source V1 vectorized path. Reads of string data type are 5-10% slower compared to the Spark Vectorized code path.
This issue is for closing that performance gap.

**Comment by rdblue** [comment]
@samarthjain, any update on this?

**Comment by samarthjain** [comment]
For non dictionary encoded Strings, Iceberg vectorized reads are still slower:
```
VectorizedReadStringsBenchmark.readIcebergVectorized5k                 1.482
VectorizedReadStringsBenchmark.readSparkVectorized5k                   1.286
VectorizedReadStringsBenchmark.readSparkNonVectorized                  2.553
```

For dictionary encoded Strings, Iceberg vectorized reads are faster:
```
VectorizedReadDictionaryStringsBenchmark.readIcebergVectorized5k       0.881 
VectorizedReadStringsBenchmark.readSparkVectorized5k                   1.142
VectorizedReadStringsBenchmark.readSparkNonVectorized                  2.324
```

**Comment by rdblue** [comment]
Okay, so we should leave this open for non-dictionary strings. Thanks!
