### ISSUE TITLE
When will 0.14 be released?

### ISSUE THREAD

**Issue by melin** [apache/iceberg#5217]

**Comment by samredai** [comment]
Hi @melin. To keep up with the ongoing efforts around Iceberg, it’s useful to check out the [notes](https://docs.google.com/document/d/1YuGhUdukLP5gGiqCbk0A5_Wifqe2CZWgOd3TbhY3UQg/edit?usp=drive_web) from the community sync. @rdblue is the release manager for 0.14 and pending a few blockers listed in the community notes, we are expecting a release candidate very soon.
