### ISSUE TITLE
Metadata file always gets created under /user/hive/ dir

### ISSUE THREAD

**Issue by varunsrinath** [apache/iceberg#5231]
Despite overriding the workdirectory the meta data is alway getting create under /user/hive/  dir

the table gets created at the correct location, only the metadata still points to /user/hive.

unfortunately on Mac we cannot create /user/hive folder..

hive> CREATE TABLE z (i int) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.iceberg.exceptions.RuntimeIOException: Failed to create file: file:/user/hive/warehouse/z/metadata/00000-34dff96a-8d34-43f3-b49a-592deada0e0d.metadata.json

`<property>
    <name>hive.metastore.warehouse.dir</name>
    <value>/Users/myname/Desktop/workspace/hdfs</value>
    <description>location of default database for the warehouse</description>
  </property>`

**Comment by varunsrinath** [comment]
Not sure why it tried to do a file:// protocol

**Comment by nastra** [comment]
@varunsrinath could you please share your catalog configuration that you're using?

**Comment by pvary** [comment]
@varunsrinath: Also please share the Hive/Iceberg versions too
