### ISSUE TITLE
iceberg + hive4.0

### ISSUE THREAD

**Issue by nashiyue** [apache/iceberg#5243]
I use this command to create a iceberg table with hive4.0
```
create table iceberg_test.test ( 
  id bigint, 
  name string ) 
PARTITIONED BY (dept string ) 
stored by iceberg;
```
I alter table add columns age, it works

but i use insert into command like: `insert into iceberg_test.test values (1,"1","1", 1);` and can not select; like 
![PA25pLVLSR](https://user-images.githubusercontent.com/7080576/178218894-48cbb3cd-b7ad-40d9-af44-763a1bf04f53.jpg)

**Comment by samredai** [comment]
@nashiyue this seems to work for me. Here are the commands I ran, including the ones to run the docker image `kgyrtkirk/hive-dev-box:bazaar` to try this out with.

*Start the docker container*
```sh
docker run --rm -p 10000:10000 --name hive4 -e HIVE_VERSION=4.0.0-alpha-1 -e TEZ_VERSION=0.10.1 -v hive-dev-box_work:/work kgyrtkirk/hive-dev-box:bazaar
```

*Launch beeline*
```sh
docker exec -it hive4 /bin/bash --login -e safe_bl
```

*Create the table*
```sql
create table test ( 
  id bigint, 
  name string ) 
PARTITIONED BY (dept string ) 
stored by iceberg;
```

*Add the `age` column*
```sql
alter table default.test add columns (age int);
```

*Insert a record*
```sql
insert into test values (1, "1", "1", 1);
```

*Query the table*
```
select * from test;
```

output:
```
+----------+------------+------------+-----------+
| test.id  | test.name  | test.dept  | test.age  |
+----------+------------+------------+-----------+
| 1        | 1          | 1          | 1         |
+----------+------------+------------+-----------+
1 row selected (0.158 seconds)
```

**Comment by pvary** [comment]
@nashiyue: Which execution engine did you use? Any errors during the insert on the console or in the HS2/HMS logs?
