### ISSUE TITLE
Optimize the performance of MOR on Trino

### ISSUE THREAD

**Issue by shidayang** [apache/iceberg#5245]
I had done a chbenchmark of iceberg on Trino. I found that the performance of MOR is very low when have many delete files. The scale of data is 10 warehouse.  The average duration is less than 10 second when no have delete files, but when I add some delete file to every tables some queries spent over one hour.

Reasons:

1. #5195 The Trino every page will call DeleteFilter#filter, every calling of DeleteFilter#filter will initialize delete files.
2. #5244 #5242 We found that the cost of creating StructLikeWrapper and InternalRecordWrapper is high.
this is Flame Graph:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/26699250/178226456-9e953b2b-5154-4693-9b74-2ec9f277fd97.png">

The query performance improved when we made these optimizations. such as the query "select count(*) from stock", before optimize spent 8 minutes, after optimize only spent 20 seconds.

**Comment by findinpath** [comment]
Please see https://github.com/trinodb/trino/pull/13112 which is very likely related to your problem.

**Comment by shidayang** [comment]
@findinpath I think this problem is not only for Trino. Iceberg core should be responsible for delete file loading once

**Comment by lhofhansl** [comment]
I think Trino is special here as it operated a page at a time. Spark does not have this problem. And, as state in the PR, caching the filters outright unconditionally could be detrimental on Spark (increase memory usage)

**Comment by flyrain** [comment]
Hi @shidayang, how many delete files were there in your test?

I did benchmark multiple delete files, you can see the result here https://github.com/apache/iceberg/pull/3287#issuecomment-960433304.
```
with 25% rows are deleted and distribute these deletes to 1, 2, 5, 10 delete files
```
The perf doesn’t degrade much with more delete files. Please be ware that non-vectorized read is using the path without caching the filter. I am guessing Trino could be different from Spark in terms of read pattern.

**Comment by shidayang** [comment]
@flyrain About running 5 minutes TPCC on 10 warehouse of chbenchmark

**Comment by rdblue** [comment]
Thanks for working on this, @shidayang! The PRs are all resolved so I'm going to close this now.
