### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector

### ISSUE THREAD

**Issue by zfno111** [apache/iceberg#5267]
hive: 2.3.4
iceberg-hive-metastore-0.11.1.jar

 when i create table like that:
`0: jdbc:hive2://10.0.5.66:10000/default> CREATE EXTERNAL TABLE `iceberg_hive`(
. . . . . . . . . . . . . . . . . . . .>   `id` int, 
. . . . . . . . . . . . . . . . . . . .>   `name` string)
. . . . . . . . . . . . . . . . . . . .>   STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
. . . . . . . . . . . . . . . . . . . .> LOCATION
. . . . . . . . . . . . . . . . . . . .>   'hdfs://10.0.5.66:9000/tmp/warehouse/test/iceberg_hive';
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector
Error: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector
	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
	at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1911)
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:362)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector`

anyone face the same problem?

**Comment by nastra** [comment]
@zfno111 are you potentially missing the [iceberg-hive-runtime.jar](https://search.maven.org/artifact/org.apache.iceberg/iceberg-hive-runtime/0.11.1/jar)? See also https://iceberg.apache.org/docs/latest/hive/#loading-runtime-jar on how to add this

**Comment by kbendick** [comment]
+1. NoClassDefFoundError is usually a missing dependency.

It can also occur due to a duplicated  dependency, so when switching to the runtime JAR get rid of any additional Iceberg dependencies you don’t need (according to the doc above).

**Comment by zfno111** [comment]
> @zfno111 are you potentially missing the [iceberg-hive-runtime.jar](https://search.maven.org/artifact/org.apache.iceberg/iceberg-hive-runtime/0.11.1/jar)? See also https://iceberg.apache.org/docs/latest/hive/#loading-runtime-jar on how to add this

tks for answer, 
here is my full code 
hive   
hive> add jar /mnt/disk1/iceberg/iceberg-hive-runtime-0.11.1.jar ;
Added [/mnt/disk1/iceberg/iceberg-hive-runtime-0.11.1.jar] to class path
Added resources: [/mnt/disk1/iceberg/iceberg-hive-runtime-0.11.1.jar]
hive> add jar   /mnt/disk1/iceberg/libfb303-0.9.3.jar;
Added [/mnt/disk1/iceberg/libfb303-0.9.3.jar] to class path
Added resources: [/mnt/disk1/iceberg/libfb303-0.9.3.jar]
hive> add jar   /mnt/disk1/iceberg/iceberg-hive-metastore-0.11.1.jar;
Added [/mnt/disk1/iceberg/iceberg-hive-metastore-0.11.1.jar] to class path
Added resources: [/mnt/disk1/iceberg/iceberg-hive-metastore-0.11.1.jar]
hive> CREATE EXTERNAL TABLE `iceberg_hive`(
    >   `id` int, 
    >   `name` string)
    >   STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
    > LOCATION
    >   'hdfs://10.0.5.66:9000/tmp/warehouse/test/iceberg_hive'
    > TBLPROPERTIES (
    >   'numFiles'='1',
    >   'table_type'='ICEBERG');
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector

i‘m use  hive EXTERNAL TABLE to connect iceberg,not flink

**Comment by nastra** [comment]
I wonder if you're missing `engine.hive.enabled=true` in your table properties (see also the doc I linked above)

**Comment by zfno111** [comment]
> 

![image](https://user-images.githubusercontent.com/32893310/178937285-d4108bf8-7e22-409f-be18-bc108063d7f3.png)
 
i have  already  add this one..

**Comment by zfno111** [comment]
**i think i  have use a bad version**

**Comment by blackmani** [comment]
I face the same problem too!
hive> add jar hdfs://sserver1:9000/spark/jars/iceberg-hive-runtime-0.14.0.jar;
Added [/tmp/27d8cc24-d1c9-4286-a2be-a3dcb6993fe7_resources/iceberg-hive-runtime-0.14.0.jar] to class path
Added resources: [hdfs://sserver1:9000/spark/jars/iceberg-hive-runtime-0.14.0.jar]
hive> use default;
OK
Time taken: 0.51 seconds
hive> create EXTERNAL table test_iceberg_tbl2(
    > id int,
    > name string,
    > age int
    > )
    > partitioned by (dt string)
    > stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
    > ;
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: MetaException(message:java.lang.NoClassDefFoundError Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector)
