### ISSUE TITLE
[DOC] - Incorrect JavaDoc in SparkCatalog

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#5269]
https://github.com/apache/iceberg/blob/51a9702367e22aff635ae05f2a313a19c3ba2fb8/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java#L95-L96

Documents this incorrectly saying that a completely new SparkCatalog must be created for a custom IcebergCatalog impl which can actually be created just by specifying the "catalog-impl" Prop

We can either remove or correct this javadoc.

**Comment by hrishisd** [comment]
Do you mind if I pick this one up?
