### ISSUE TITLE
Support tagging snapshot during snapshot generation in spark-3.2 

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#5279]
Seems not planned or done in https://github.com/apache/iceberg/projects/4#card-67954222.

Also can you help me link this ticket to the project? thanks.

**Comment by amogh-jahagirdar** [comment]
Hi Puchneg! Thanks for your interest in this area.  Do you mind clarifying the desired behavior "Support tagging snapshot during snapshot generation"?

**Comment by amogh-jahagirdar** [comment]
I see are you looking for specifically accessing it via Snapshot Summary or is it just for the ability to query the snapshot ID from the ref? There's an ongoing [PR](https://github.com/apache/iceberg/pull/4807/files) for the snapshot ref metadata table. Once that gets merged, then the refs table can be queried to determine the corresponding snapshot id for a given tag. 

For actually creating a tag after the write completes in Spark, I'm working on a change for that, will publish a draft for that soon

**Comment by puchengy** [comment]
@amogh-jahagirdar thank you! it doesn't need to be done via snapshot summary, ref metadata table is fine. For the tag creation via spark write, looking forward to that, thanks!
