### ISSUE TITLE
Docs missing version dropdown

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg#5290]
I'm really happy to see the "version dropdown" in the Iceberg website. I think it's a great feature to have. 

<img width="1494" alt="Screen Shot 2022-07-17 at 11 08 46 AM" src="https://user-images.githubusercontent.com/9057843/179419068-16074732-b50f-4b25-b777-eececa132a97.png">

### Problem
Looks like the version dropdown in the header disappears when I read the actual doc webpage.
For example:
https://iceberg.apache.org/docs/latest/
https://iceberg.apache.org/docs/0.13.1/
https://iceberg.apache.org/docs/0.12.1/

<img width="1494" alt="Screen Shot 2022-07-17 at 11 10 06 AM" src="https://user-images.githubusercontent.com/9057843/179419116-eaf064b0-46d6-4069-b6cc-c8614de7881d.png">

Which is weird because I followed the [iceberg-docs](https://github.com/apache/iceberg-docs) instructions and ran it locally. Locally there is the version dropdown in the header:
<img width="1494" alt="Screen Shot 2022-07-17 at 11 10 49 AM" src="https://user-images.githubusercontent.com/9057843/179419143-76de4da1-9638-4aa9-866b-b985d3aef398.png">

Reading the [docs deployment documentation](https://github.com/apache/iceberg-docs#docs-deployment), my hunch is that the version dropdown was added recently and the older versions of the docs were not updated to reflect this change. 

cc @samredai since you've [enabled the version-dropdown](https://github.com/apache/iceberg-docs/blame/5b97fe0f510f93dad3809ca7181c53ed205e6521/iceberg-theme/layouts/partials/version-dropdown.html)

**Comment by samredai** [comment]
@kevinjqliu thanks for your comments and opening this issue! Yes the new theme will provide the experience you're seeing locally where the top nav bar is fixed and the version drop-down is always available.

We're in the process of deploying the theme to the versioned docs site (each version of the docs site is deployed on its own) so once that's deployed, this will all be live. This should be done within a few days. 👍

**Comment by kevinjqliu** [comment]
awesome! so this is not a bug. I'll close out the issue. 

Im curious how you were able to make this work across versions. I really like this feature and want to do the same for other projects docs. like for trino https://github.com/trinodb/trino/issues/13205

**Comment by samredai** [comment]
@kevinjqliu the magic happens in 3 places really. The versions are defined in the [config.toml](https://github.com/apache/iceberg-docs/blob/main/docs/config.toml#L25-L31) file, that list is used to generate the [drop-down](https://github.com/apache/iceberg-docs/blob/main/iceberg-theme/layouts/partials/version-dropdown.html) in the theme, and then the [deployment CI](https://github.com/apache/iceberg-docs/blob/main/.github/workflows/deploy.yml#L87) deploys the site to a sub-directory named after the branch/version name.

We use hugo but I would imagine a similar setup is achievable with most other static site frameworks. Let me know if you want to chat about how to make this work with your deployment setup. 😃
