### ISSUE TITLE
restrictions on metadata delete

### ISSUE THREAD

**Issue by zinking** [apache/iceberg#5307]
when purging data, it is hoped that the delete should go through metadata delete instead of  `replaceData` plan.

for example if my table went through partition evolutions:
1. ts
2. ts, name
3. ts, year, name

ideally if I write delete statements like `delete from table where ts < 2022`, metadata deletes should still work. 
but currently it is restricted.

```

  public boolean canDeleteWhere(Filter[] filters) {
    Preconditions.checkArgument(
        snapshotId == null,
        "Cannot delete from table at a specific snapshot: %s", snapshotId);

//TODO: this is preventing delete going through metadata delete
    if (table().specs().size() > 1) {
      // cannot guarantee a metadata delete will be successful if we have multiple specs
      return false;
    }

    Set<Integer> identitySourceIds = table().spec().identitySourceIds();
    Schema schema = table().schema();

    for (Filter filter : filters) {
      // return false if the filter requires rewrite or if we cannot translate the filter
      if (requiresRewrite(filter, schema, identitySourceIds) || SparkFilters.convert(filter) == null) {
        return false;
      }
    }

    return true;
  }

```

**Comment by rajan-v** [comment]
I have verified Deletion through Spark-SQL. It's happening  through metafiles and generating delete files. 
Setup:- spark-3.2.1-bin-hadoop3.2   	iceberg-spark-runtime-3.2_2.12-0.13.0.

And yes i can see table().specs().size() > 1)  in iceberg-spark-runtime-3.0 and 3.1
v3.2
https://github.com/apache/iceberg/blob/906ba1b4998f938c4615a96ec90921e4ccd09c4a/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java#L236


[iceberg-delete_files_generation.txt](https://github.com/apache/iceberg/files/9156024/iceberg-delete_files_generation.txt)

**Comment by zinking** [comment]
ok seems spark3.1 only issue.
