### ISSUE TITLE
ManifestGroup entries() reads the manifest 2 times when ignoreDeleted is set. This causes perf issues.

### ISSUE THREAD

**Issue by palaniappa** [apache/iceberg#5308]
ManifestGroup entries() reads the manifest 2 times when ignoreDeleted is set. Since every manifest is read 2 times, if the table contains more manifest the planFiles time keeps increasing.

**Comment by nastra** [comment]
I wonder if this is related to what's being addressed in https://github.com/apache/iceberg/pull/5306
