### ISSUE TITLE
The error message of 'org.apache.iceberg.util.SnapshotUtil#snapshotIdAsOfTime' can be misleading to users.

### ISSUE THREAD

**Issue by lipenglin** [apache/iceberg#5321]
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java#L320

The error message of 'org.apache.iceberg.util.SnapshotUtil#snapshotIdAsOfTime' shows the timestamp in UTC timezone, this can be misleading to users who is in another timezone.

e.g:
When I snapshotIdAsOfTime('2022-06-17 11:00:00'), the error message show me 'Cannot find a snapshot older than 2022-06-17 09:00:00', because I'm not in UTC timezone.

**Comment by luckymeng** [comment]
您的来信已收到，谢谢。

**Comment by nastra** [comment]
I agree that this is confusing. I wonder if we should report back the timestamp in UTC to make this clearer

**Comment by rdblue** [comment]
Iceberg only works with UTC timestamps. All translation to UTC is done by engines. I think this is the correct behavior for Iceberg, but it may not be the correct behavior for an engine to just pass the timestamp through.

**Comment by nastra** [comment]
We're doing https://github.com/apache/iceberg/blob/ffee32c48859eef2136f728438b1da613429fe7e/core/src/main/java/org/apache/iceberg/util/DateTimeUtil.java#L89 (aka reporting back without a time zone). 
I wonder if changing this code to `Instant.ofEpochMilli(millis).atOffset(ZoneOffset.UTC).toZonedDateTime().toString()` would be good enough so that the TimeZone is shown in the string

**Comment by rdblue** [comment]
Will `toZonedDateTime` always show `+00:00`? I don't think adding `Z` would help much. I think adding the offset for log or error messages would be fine.

**Comment by lipenglin** [comment]
> Iceberg only works with UTC timestamps. All translation to UTC is done by engines. I think this is the correct behavior for Iceberg, but it may not be the correct behavior for an engine to just pass the error through.

Thanks for your reply. That's fine, we're currently catching InternalException and converting it to the timezone that the user wants.
