### ISSUE TITLE
Allow table read/write options to be configured and/or enforced at catalog level using catalog properties

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#5343]
**Background:** #4011 allowed table properties to be set on newly-created tables via catalog properties.

**Proposal:** It would be nice to have these propagate to runtime table properties as well for read/write time.

**Problem Solved:**  There are a lot of table properties that should be overriden at runtime, see : https://iceberg.apache.org/docs/latest/configuration/ .  For example, now the delete write-distribution-mode defaults to hash which cause unexpected shuffles (see https://github.com/apache/iceberg/issues/5224), and these are not always desirable.  Or users would like to override vectorization due to compatibility bugs (https://github.com/apache/iceberg/pull/2740) or change read/write split size dynamically.  

But, in spark, spark.sql() cannot take any options, so users are stuck setting table properties for this.  This is not user-friendly, as imagine concurrent jobs are running, setting a table property just for one job may break something for another job if it picks it up.

This proposal could be one way without changing Spark, for Iceberg to be able to override table properties at runtime, for the cases where there is no other way to override these properties.

**Comment by szehon-ho** [comment]
@SinghAsDev @RussellSpitzer @rdblue @aokolnychyi @dramaticlly if there's any thoughts on this

**Comment by rdblue** [comment]
I'm reluctant to create a broader work-around for this just because Spark can't pass options. What about adding the options in SQL hints to Spark? I think that was discussed earlier, but I don't know where it went.

**Comment by szehon-ho** [comment]
I see, I must have missed that discussion, if anyone has any link?  If there a some issue or proposal there we could definitely take a look at it on spark side, hoping it will be do-able.

**Comment by zhongyujiang** [comment]
@szehon-ho  FYI: https://issues.apache.org/jira/browse/SPARK-36680, this might be the link you want if you haven't found it yet.

**Comment by szehon-ho** [comment]
Thanks, I guess it did not go far.  FWIW I think your proposal makes sense.  Will have to see any spark folks can help with this if we can take if further.

**Comment by bitsondatadev** [comment]
@rdblue @szehon-ho can this be closed?

**Comment by szehon-ho** [comment]
Sure, i have checked with Spark folks recently, will follow up with them there.

**Comment by dramaticlly** [comment]
I am not 100% sure but #7732 seems promising
