### ISSUE TITLE
Docs：Double click [Docs] menu return 404 Not Found

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#5351]
![image](https://user-images.githubusercontent.com/3785228/180707238-cca949ab-3d4c-403c-92ff-bc0fe368c505.png)

the error URL:
![image](https://user-images.githubusercontent.com/3785228/180707324-067fb372-8ca8-4892-8f98-b248c76646d0.png)

**Comment by nastra** [comment]
@samredai FYI, I confirmed that clicking on the `Docs` link multiple times appends `docs/latest` to the URL

**Comment by samredai** [comment]
Ah thanks for catching this. This is quick fix, the docs menu item is supposed to actually be a relative link, similar to the others. So [this](https://github.com/apache/iceberg-docs/blob/main/docs/config.toml#L35) line needs to be changed from:
```
    { name = "Docs", url = "/docs/latest", weight = 200 },
```
to:
```
    { name = "Docs", pre = "relative", url = "../../docs/latest", weight = 200 },
```
We'll need that change to happen in the `main`, `latest`, `0.14.0`, and `0.13.2` branches.

**Comment by felixYyu** [comment]
@nastra @samredai    Another minor error:

1.click any one of the bottom buttons
![image](https://user-images.githubusercontent.com/3785228/181149991-70b1b8a1-9e03-4f71-99af-8df05ff94602.png)

2.After returning to the houme page,the main menu is not displayed.
![image](https://user-images.githubusercontent.com/3785228/181150406-81aa554d-11d5-4175-9b67-3d5ac6cba638.png)
