### ISSUE TITLE
Actions：API Binary Compatibility Checks #29 BUILD FAILED

### ISSUE THREAD

**Issue by felixYyu** [apache/iceberg#5356]
```
Run ./gradlew :iceberg-api:revapi --rerun-tasks
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 59821  100 59821    0     0  2434k      0 --:--:-- --:--:-- --:--:-- 2434k
Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.4.2!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':iceberg-api:revapiAnalyze'.
> Failed to query the value of task ':iceberg-api:revapiAnalyze' property 'oldApiJars'.
   > Failed to resolve old API, meaning revapi cannot use it tofind API/ABI breaks. This usually happens when the last
     release was git tagged correctly but the publish build was not successful. If this is the case, there are two options:
     
     1) Ideally: Retrigger the publish build to ensure the API is published.
     2) Otherwise: You can choose to target against a different version, ideally the last correctly published version. Either run:
          * ./gradlew revapiVersionOverride --replacement-version <version>
            to override for all projects
          * ./gradlew :iceberg-api:revapiVersionOverride --replacement-version <version>
            to override for just this project "project ':iceberg-api'"
     
     Errors:
     
     We tried version release-base-0.12.0 but it failed with errors:
     
     Could not find org.apache.iceberg:iceberg-api:release-base-0.12.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-api/release-base-0.12.0/iceberg-api-release-base-0.12.0.pom
       - file:/home/runner/.m2/repository/org/apache/iceberg/iceberg-api/release-base-0.12.0/iceberg-api-release-base-0.12.0.pom

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Error: Process completed with exit code 1.
```

> the correct link  [](https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-api/0.12.0/iceberg-api-0.12.0.pom )
![image](https://user-images.githubusercontent.com/3785228/180933714-2f0349ab-54b1-4f47-8df2-2d15d99d97f2.png)

**Comment by nastra** [comment]
Interesting, this seems to work fine on CI on latest `master` as can be seen in https://github.com/apache/iceberg/runs/7510936323?check_suite_focus=true. I also tried locally and don't see the issue. Did this happen for you after you checked out the project for the first time @felixYyu? Does it fail after you do `git fetch origin --tags`?

**Comment by felixYyu** [comment]
@nastra I have forked the master branch at last year, But recently, we often receive **build failed** information

![image](https://user-images.githubusercontent.com/3785228/180956618-9f029718-f3a4-41bc-a3c5-cc01dfb27132.png)

**Comment by nastra** [comment]
@felixYyu it's difficult to tell what exactly is different on your fork. My guess would be that your fork doesn't have the latest tags from Iceberg that have been published, since RevAPI is configured to check API compatibility against `apache-iceberg-0.14.0` (which your fork doesn't have)

**Comment by kbendick** [comment]
I also think that your fork doesn’t have the latest tags and can confirm this is working for me.

If you `git fetch upstream —all` (replacing upstream with apache or whatever you call the Apache GitHub remote repository), you should be good.

Here’s where it’s specified btw: https://github.com/apache/iceberg/blob/1b989c86a3c0da0bbe7d5f385618116cd899bdf2/.palantir/revapi.yml#L2

**Comment by kbendick** [comment]
Oh I just noticed you’re trying on 0.12.0. Is that intentional?

Previously, the previous version was determined off of a tag on the master branch `release-base-0.xx.yy` like `release-base-0.13.0`.

If you’re intentionally on 0.12.0, then revapi shouldn’t be run there at all and I’d love to find out how that happened. If it’s just stating `release-base-0.12.0`, then that’s the last “release-base” tag you have and you need to fetch release-base-0.13.0 and others via `git fetch`.
