### ISSUE TITLE
Building iceberg-0.14.0 failed

### ISSUE THREAD

**Issue by xuzhiwen1255** [apache/iceberg#5365]
After downloading the latest version of iceberg-0.14.0, there is a 'Could not find method gitVersion()'  problem in Building

As shown in the figure below
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/105710753/181212511-236374fd-9226-4a8c-9b9d-edeed1e14b31.png">

I haven't had the same problem building other versions

Java version "1.8.0_333"
Gradle version  "7.4.2"

**Comment by nastra** [comment]
@rdblue It looks like the `version.txt` file is missing from the source zip. @xuzhiwen1255 as a workaround you could probably just do `echo "0.14.0" > version.txt` for now.

**Comment by xuzhiwen1255** [comment]
@nastra  Problem solved, thank you very much for your reply

May I make a suggestion ? I think we can test it before and after release to avoid problems

**Comment by xuzhiwen1255** [comment]
@nastra Problem solved, thank you very much for your reply

Can I help with this problem

**Comment by nastra** [comment]
It looks like whatever tarball/zip landed on the [GH releases page](https://github.com/apache/iceberg/releases) is different from the tarball we link on the [Iceberg releases page](https://iceberg.apache.org/releases/). The one on the [GH releases page](https://github.com/apache/iceberg/releases) is missing `version.txt` & `iceberg-build.properties`

**Comment by rdblue** [comment]
The GH releases tarball doesn't have build info or the version file. Those are now added as part of the release process, rather than creating a commit. The benefit is that now release tags are on the master branch. You should always use the release tarball, not a github tarball.
