### ISSUE TITLE
Hive: Concurrency Issue for CachedClientPool

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#5371]
As discovered by @flyrain , sometimes this issue occurs in ClientPool.
```
java.lang.IllegalStateException: Cannot get a client from a closed pool
    at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:502)
    at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118)
    at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:56)
    at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
    at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:76)
    at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:203)
    at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:95)
    at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:78)
    at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:44)
    at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:710)
    at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:156)
    at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:111)
    at org.apache.iceberg.spark.Spark3Util.loadIcebergTable(Spark3Util.java:648)
```

The problem comes from [CachedClientPool](https://github.com/apache/iceberg/blob/master/hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java).  There, run() always asks the clientPoolCache (Caffeine) for new clientPool.  But clientPoolCache has been constructed with expireAfterAccess() and removalListener(), which removes from cache and then calls close() with a background thread after it is expired, which happens after x time.  Thus, we may hit the situation (as described by @flyrain )

Thread A; clientPoolCache.get() creates client A
Thread B: clientPoolCache.get() comes, gets client A since A is not closed
Caffeine Thread: Close the client A by the removal listener
Thread B: Run the command, failed with above because the client since it is closed.

**Comment by flyrain** [comment]
Thanks @szehon-ho for filing this. Yes, that's my initial thought based on the fact that the error only happens when there are a lot of client pool requests.

**Comment by szehon-ho** [comment]
Yea to sum up, these are the options:

1.  Implement a counter  for each ClientPool, that is incremented at beginning of ClientPool::run() call, and decremented at the end.  The close() thread will block until counter is 0.

2.  Implement a retry mechanism in CachedClientPool::run(), which will call call clientPool() again if we hit a closed client.

**Comment by pvary** [comment]
@lcspinter, @szlta: You might be interested in this as well

**Comment by szlta** [comment]
Hi @szehon-ho, in your example above shouldn't Thread B's get() call reset the counter in the cache?
And if so, then Caffeine should not invoke the removalListener as the object was not removed, so serving the same client pool object should work for Thread B (for another x time duration, 5 mins default AFAIK)

Similarly, if the pool object did time out since the last access (done by Thread A), then Caffeine should remove that object, and serve Thread B a fresh one (and in the meantime it may very well call the removalListener on the old one simultaneously, that's fine as Thread B won't have a reference to that)

To me it seems like that the scenario that you describe could only go sideways if Caffeine itself is not thread safe with handing out / expiring objects within. Am I missing something?

**Comment by szehon-ho** [comment]
Yea I think you are right.  

We were discussing with @RussellSpitzer , the problem is more related to concurrency issues between eviction thread and operations.  So in a one thread scenario:

- Thread A: calls get()
- Caffeine Thread:  calls remove()
- Caffeine Thread:  listener calls close()
- Thread A: does a Hive client operation and finds the client is closed

So now we are thinking, its a mainly problem if a Hive operation takes longer than the eviction interval.

**Comment by szlta** [comment]
Hm I still don't think this is the full picture of what's happening. In light of the stack trace above...
```
java.lang.IllegalStateException: Cannot get a client from a closed pool
    at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:502)
    at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118)
    at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:56)
    at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
    at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:76)
    at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:203)
    ...
```
... this is how I think things happened:
- inside `HiveTableOperations.doRefresh()` we wanted to do a `getTable()` call on HMS
- so we invoked `CachedClientPool.run`
  - this has called `clientPool()` first to get an instance of the appropriate ClientPoolImpl instance, which in this case is a HiveClientPool object
    - this calls `get()` on the `clientPoolCache`, which either creates a new instance or returns a used one, but either way the **clock is reset at this point** (this part is not visible in the stacktrace but should have already happened quite recently)
  - right after we have the instance, we invoke `run()` (and its overloaded `run()` right after)
    - which calls `get()` to get one Client from the ClientPool
And this is where the exception happens stating that the whole pool is closed already.. 

We didn't event get to start working on the Hive operation, we just got `HiveClientPool (ClientPoolImpl)` from the `clientPoolCache` with clock reset on it and attempted to get one `Client` from it, but it was already closed between these couple of frames.

Perhaps somebody else closed this HiveClientPool, and it was stored in this closed state within the cache, or there's a problem with the cache implementation?

**Comment by szehon-ho** [comment]
Yea you are right, in @flyrain  scenario the eviction time was set to 0, causing the Caffeine eviction + removal_listener thread to spawn immediately and close the client.  It is probably not a common issue if the eviction is set to 5 minutes, unless you have a custom user call run on the pool and waits awhile before using the client.

**Comment by szlta** [comment]
>  the eviction time was set to 0
Oh! Well that explains it, I guess all bets are off in that case as JVM's thread scheduling will decide..

Should we perhaps throw an IllegalArgumentException if CachedClientPool is attempted to be configured with 0 eviction time? Or maybe even define a larger minimum, let's say 1 second?
