### ISSUE TITLE
read iceberg table by flink timeout

### ISSUE THREAD

**Issue by jorkzheng** [apache/iceberg#5388]
when I want read all data by flink batch mode,I always get error.
TimeoutException: Heartbeat of TaskManager with id container_e148_1653747647067_1367745_01_000008(bjtx-hd-data-160.bjtx.keep:8041) timed out.
I guess  some one cotainer load too many data,so the container always execute gc.
My table hava 130 millon datas,storage as parquet+gzip on hdfs,about 3gb.
iceberg version is 0.14,flink verison is 1.15.1.
We are expecting a reply

**Comment by xuzhiwen1255** [comment]
@jorkzheng 
I am not sure about your specific configuration, such as the memory size and timeout time of taskManager. If it is allowed, you can try to increase the TM memory and timeout time to see if it works
This is a personal experience of mine

**Comment by luoyuxia** [comment]
What's the parallelism for reading the data? I think you can increase the TM memory and the parallelism.
Above are  general ways,  the better is to analyze the memory usage using some tools like jmap to  know what's the bottleneck and  try to do optimization case by case.
