### ISSUE TITLE
Refactoring flink upsert ut test so the table is partitioned by date.

### ISSUE THREAD

**Issue by hililiwei** [apache/iceberg#5418]
We should consider refactoring these in a follow up PR so the table is partitioned by date.

I've encountered this confusion as well before.

_Originally posted by @kbendick in https://github.com/apache/iceberg/pull/5050#discussion_r933426976_

**Comment by hililiwei** [comment]
I think it's friendly to beginners. Of course, if no one wants to take the ticket for a long time, I will work for it.

**Comment by lvyanquan** [comment]
Thank you for providing this opportunity, I will try it.

**Comment by hililiwei** [comment]
> Thank you for providing this opportunity, I will try it.

Good luck.

**Comment by lvyanquan** [comment]
should be fixed by https://github.com/apache/iceberg/pull/5486
