### ISSUE TITLE
The configuration of 'table.exec.iceberg.use-flip27-source' doesn't work

### ISSUE THREAD

**Issue by Cqz666** [apache/iceberg#5509]
### Query engine

Flink

### Question

Hi team,
  I tried using the new version of the Source API, and I set this configuration 'table.exec.iceberg.use-flip27-source'  to true, from the Flink Web UI, you can see that the configuration is set up successfully, but from the execution graph, it doesn't seem to go the right way.
![image](https://user-images.githubusercontent.com/50294123/184269344-96e0cdb9-a53d-42fc-a004-8347c977bbe0.png)

![image](https://user-images.githubusercontent.com/50294123/184269494-3419e8f0-6a4f-4d7d-aa51-0e85ea5feea2.png)

Does anyone know why? 

Iceberg version : iceberg-flink-runtime-1.14-0.14.0.jar
Flink version : 1.14.5

**Comment by pvary** [comment]
@Cqz666: The new config is added by this [commit](https://github.com/apache/iceberg/commit/41570a1877bb0f7dd4b2a91addbbca08b3721588). I think this is not part of the 0.14 Iceberg release yet. If it is possible for you, you can try out the feature using Iceberg compiled from the master branch.

Thanks,
Peter

**Comment by Cqz666** [comment]
@pvary Thanks, your are right. I will close the issue
