### ISSUE TITLE
Access Control in Iceberg

### ISSUE THREAD

**Issue by justusrk** [apache/iceberg#5527]
### Query engine

Spark

### Question

I see that Iceberg is designed to be invisible. But I wanted to clarify this.

Thinking about Access Control features - like users being allowed to access tables, columns, and rows.
These features would be useful for GDPR Audits or maybe understanding data lineage.

Should Iceberg ideally care about this? Or should this be handled by something else?

If something else, then can you suggest what it could be? Like the query engine or something like Presto?

I am curious where Data Governance features would be fitting.  Are there Iceberg implementations that do this already?

**Comment by nastra** [comment]
Generally speaking, access control is something that engines should be implementing on top of Iceberg. Every engine has its own way of defining access control rules and enforcing them (even beyond Iceberg tables), so I think handling this in Iceberg across all engines might be quite difficult to achieve
