### ISSUE TITLE
Imported parquet tables may have wrong metrics

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#5543]
### Apache Iceberg version

main (development)

### Query engine

Spark

### Please describe the bug 🐞

I found this problem while doing https://github.com/apache/iceberg/pull/5376#discussion_r934960703, which now attempts to convert metrics to readable ones for "files" metadata table and encountered an exception trying to do so in an existing test case.  So just reporting the problem.  

**Early Analysis:**
It seems it happens when the parquet file schema does not match the destination Iceberg table schema, in this case because of a missing column in the file (in this case, the partition column, which definitely should not exist in parquet files of Hive tables.). It seems the import code expects it to exist.

**Repro:**
See the test:  TestIcebergSourceTablesBase::testFilesTableWithSnapshotIdInheritance https://github.com/apache/iceberg/blob/5f5c9235c10ed4a711a64de880491b3ae4f348ec/spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java#L466

The parquet table is a partitioned one, so when we insert data to that table, there is only one column in the file (data).  Column "Id" is partitioned so does not exist in the file.

**Details:**
The import code calls via TableMigraitonUtil::listPartition -> TableMigrationUtil::getParquetMetrics -> finally ParquetUtil::footerMetrics().  The ParquetUtil::footerMetrics does the following https://github.com/apache/iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java#L90
1. Assign New Field Ids
2.  Calculate metrics based on those field ids.

The first step, it sees the parquet file schema does not have ids (expected) and assigns the ids using ParquetSchemaUtil::addFallbackIds https://github.com/apache/iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetSchemaUtil.java#L120.  This starts with id= 1, so now data column has id 1.

The second step calculates metrics for 'data' column and puts them in the map with id=1.

However, in the Iceberg destination table schema, id=1, data=2.  So now, when we try to read the metrics, they are not correct.

**Comment by karuppayya** [comment]
>This starts with id= 1, so now data column has id 1.

I think we should be looking up the destination table to assign ids.
Also if we are new ids I think we should be starting from highest id of the  destination table.

**Comment by szehon-ho** [comment]
Yea im not too famililar with the code, but it sounds resaonable to me.

**Comment by chenjunjiedada** [comment]
@szehon-ho I hit this as well when trying to resolve lower/upper bounds issue, passing `namemapping` can resolve this.

```
    NameMapping mapping = MappingUtil.create(table.schema());
    String mappingJson = NameMappingParser.toJson(mapping);

    table.updateProperties().set(TableProperties.DEFAULT_NAME_MAPPING, mappingJson).commit();
```

**Comment by szehon-ho** [comment]
Thanks for looking at it!
