### ISSUE TITLE
Support Lifecycle keyword

### ISSUE THREAD

**Issue by hunter-cloud09** [apache/iceberg#5557]
### Query engine

Spark

### Question

Now we use spark to create iceberg tables through hms, but found that the lifecycle keyword is not supported when creating tables. Does the community plan to support it? Or can you give some guidance on how to do this?
 thx！

**Comment by hililiwei** [comment]
What is the purpose of using the `Lifecycle keyword`?

**Comment by hunter-cloud09** [comment]
> What is the purpose of using the `Lifecycle keyword`?

The life cycle of the table can be customized, in order to better manage cold data

**Comment by hililiwei** [comment]
Do you want to use the `Lifecycle keyword` to delete or migrate data automatically?

**Comment by hunter-cloud09** [comment]
> Do you want to use the `Lifecycle keyword` to delete or migrate data automatically?

yep, it seems like that
