### ISSUE TITLE
[Spark] How do I configure the client factory to ensure it is using the DefaultCredentialsProvider

### ISSUE THREAD

**Issue by ja-michel** [apache/iceberg#5567]
### Query engine

Spark 3.3.1 stand-alone
Iceberg 0.14.0
iceberg-spark-runtime-3.3_2.12 0.14.0

```
org.apache.iceberg:iceberg-aws:0.14.0
org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:0.14.0
org.apache.hadoop:hadoop-aws:3.3.3
```

### Question

I'm running a simple spark application in a standalone pod inside and EKS cluster. The pods have a service account associated and the environment variables set:
```
AWS_DEFAULT_REGION: eu-west-2  
AWS_REGION: eu-west-2  
AWS_ROLE_ARN: arn:aws:iam::0000000000:role/MyServiceAccountRole  
AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
This is my Spark configuration (relevant to Iceberg):
```
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
iceberg.engine.hive.enabled=true
spark.sql.catalog.ice=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.ice.warehouse=s3a://my-bucket/spark-jobs/warehouse
spark.sql.catalog.ice.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
spark.sql.catalog.ice.io-impl=org.apache.iceberg.aws.s3.S3FileIO
```
When the spark context starts and the `DefaultAwsClientFactory` is created, I don't think it is using the `DefaultCredentialsProvider` because the clients ultimately use the node's role and not the role in the env variables and web identity token.

**Q:** How do I configure the client factory to ensure it is using the `DefaultCredentialsProvider` and the `AWS_WEB_IDENTITY_TOKEN_FILE` env variable https://github.com/apache/iceberg/blob/6d2edd6284ebc5301dbe45376a31ca8316852a77/aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java#L181-L194

**Comment by ja-michel** [comment]
I can test different configurations if you can point me in some direction. I tried using the AssumeRole factory, described in the docs [here](https://iceberg.apache.org/docs/latest/aws/#aws-client-customization) and it did try to assume the role but the node role doesn't have permissions to do that. 

I also tested a simple python scrip to read the glue databases using boto3 which works as expected - uses the web token (AWS_WEB_IDENTITY_TOKEN_FILE) and role for authenticating.

**Comment by mailtoraja18** [comment]
i have the same issue . any ideas ?

**Comment by ja-michel** [comment]
@mailtoraja18  this worked for me. 
It's really a config of the credential provider. 
`spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.DefaultAWSCredentialsProviderChain`
This provider will follow the verification order described in the [docs ](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html)

Web Identity Token, which is the one generated by irsa roles and added to the pod, is the third one. 

Hope it helps.
