### ISSUE TITLE
Table remains in HMS when using HiveCatalog.dropTable() after dropping the files of the table from HDFS

### ISSUE THREAD

**Issue by gaborkaszab** [apache/iceberg#5584]
### Apache Iceberg version

0.13.1

### Query engine

Impala

### Please describe the bug 🐞

When you delete the files of a table from HDFS and then call HiveCatalog.dropTable() then TableOperations.current() throws an uncaught NotFoundException and as a result the table won't be erased from HMS as HiveCatalog.dropTable() will exit before running the code to erase the table from HMS.
https://github.com/apache/iceberg/blob/dd5bb497175bcc75cf63bba16038b7a5d93ffdb2/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L172

Further investigation and repro steps are in this Impala ticket: https://issues.apache.org/jira/browse/IMPALA-11503
We had a repro using Iceberg 0.13.1 but after checking the code I believe this is still an issue on latest master.

I have an ongoing implementation for this fix. Let me know if there are any comments on this issue!

**Comment by nastra** [comment]
@gaborkaszab is this potentially related to https://github.com/apache/iceberg/pull/5510?

**Comment by gaborkaszab** [comment]
Thanks for the pointer, @nastra! Indeed this is a duplicate of #5510

**Comment by nastra** [comment]
let's leave this issue open until #5510 fixes this

**Comment by vamen** [comment]
We also face this issue
A lot of our team mates delete data file in hdfs or s3 because they got used to hadoop catalog based iceberg tables.
when we switched to glue catalog based iceberg table. we used to face this issue.

**Comment by rdblue** [comment]
Merged #5510, so I'll close this. Thanks, @yabola!
