### ISSUE TITLE
Incorrect table definition after executing rollback_to_snapshot procedure

### ISSUE THREAD

**Issue by ebyhr** [apache/iceberg#5591]
### Apache Iceberg version

0.14.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Spark returns the latest table definition even after executing `rollback_to_snapshot` procedure.

Steps to reproduce
```
> CREATE TABLE test USING iceberg AS SELECT 1 c1;
> ALTER TABLE test ADD COLUMN c2 int;
> INSERT INTO test VALUES (1, 1);
> SELECT * FROM iceberg_test.default.test.snapshots;
2022-08-19 07:32:29.499	2770581293596517273 ...
2022-08-19 07:32:50.006	6893045681966948046 ...

> DESC iceberg_test.default.test.snapshot_id_2770581293596517273;
c1                  	int

# Partitioning
Not partitioned

> CALL iceberg_test.system.rollback_to_snapshot('default.test', 2770581293596517273);
> DESC iceberg_test.default.test;
c1                  	int
c2                  	int
```

The result is same even after I executed `REFRESH TABLE iceberg_test.default.test` after `rollback_to_snapshot`. 

Relates to https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1660895079836159
Trino issue https://github.com/trinodb/trino/issues/13699

**Comment by Fokko** [comment]
I'm able to reproduce it and it looks like the data is rolebacked, but the schema isn't.

```sql
%%sql

CREATE TABLE test.test USING iceberg AS SELECT 1 c1;
```

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
                                                                                  




<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>




```sql
%%sql

ALTER TABLE test.test ADD COLUMN c2 int;
```




<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>




```sql
%%sql

INSERT INTO test.test VALUES (1, 1);
```




<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>




```sql
%%sql

SELECT * FROM test.test;
```

                                                                                    




<table>
    <thead>
        <tr>
            <th>c1</th>
            <th>c2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>None</td>
        </tr>
        <tr>
            <td>1</td>
            <td>1</td>
        </tr>
    </tbody>
</table>




```sql
%%sql

SELECT * FROM test.test.snapshots;
```




<table>
    <thead>
        <tr>
            <th>committed_at</th>
            <th>snapshot_id</th>
            <th>parent_id</th>
            <th>operation</th>
            <th>manifest_list</th>
            <th>summary</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>2022-08-22 07:47:45.143000</td>
            <td>5161623784319151399</td>
            <td>None</td>
            <td>append</td>
            <td>s3://tabular-wh-us-west-2-dev/8bcb0838-50fc-472d-9ddb-8feb89ef5f1e/03b32560-7561-4f96-992b-01ef730946f5/metadata/snap-5161623784319151399-1-cde4c05b-670c-47dd-8860-bcd6f07756f9.avro</td>
            <td>{&#x27;added-data-files&#x27;: &#x27;1&#x27;, &#x27;total-equality-deletes&#x27;: &#x27;0&#x27;, &#x27;added-records&#x27;: &#x27;1&#x27;, &#x27;partition-summaries-included&#x27;: &#x27;true&#x27;, &#x27;partitions.&#x27;: &#x27;added-data-files=1,added-records=1,added-files-size=389&#x27;, &#x27;total-records&#x27;: &#x27;1&#x27;, &#x27;spark.app.id&#x27;: &#x27;local-1661154453400&#x27;, &#x27;changed-partition-count&#x27;: &#x27;1&#x27;, &#x27;total-position-deletes&#x27;: &#x27;0&#x27;, &#x27;added-files-size&#x27;: &#x27;389&#x27;, &#x27;total-delete-files&#x27;: &#x27;0&#x27;, &#x27;total-files-size&#x27;: &#x27;389&#x27;, &#x27;total-data-files&#x27;: &#x27;1&#x27;}</td>
        </tr>
        <tr>
            <td>2022-08-22 07:47:52.492000</td>
            <td>2279922865032537001</td>
            <td>5161623784319151399</td>
            <td>append</td>
            <td>s3://tabular-wh-us-west-2-dev/8bcb0838-50fc-472d-9ddb-8feb89ef5f1e/03b32560-7561-4f96-992b-01ef730946f5/metadata/snap-2279922865032537001-1-58b2d439-1420-49c2-bf06-228c77f1ebd0.avro</td>
            <td>{&#x27;added-data-files&#x27;: &#x27;1&#x27;, &#x27;total-equality-deletes&#x27;: &#x27;0&#x27;, &#x27;added-records&#x27;: &#x27;1&#x27;, &#x27;partition-summaries-included&#x27;: &#x27;true&#x27;, &#x27;partitions.&#x27;: &#x27;added-data-files=1,added-records=1,added-files-size=599&#x27;, &#x27;total-records&#x27;: &#x27;2&#x27;, &#x27;spark.app.id&#x27;: &#x27;local-1661154453400&#x27;, &#x27;changed-partition-count&#x27;: &#x27;1&#x27;, &#x27;total-position-deletes&#x27;: &#x27;0&#x27;, &#x27;added-files-size&#x27;: &#x27;599&#x27;, &#x27;total-delete-files&#x27;: &#x27;0&#x27;, &#x27;total-files-size&#x27;: &#x27;988&#x27;, &#x27;total-data-files&#x27;: &#x27;2&#x27;}</td>
        </tr>
    </tbody>
</table>




```sql
%%sql

CALL system.rollback_to_snapshot('test.test', 5161623784319151399)
```




<table>
    <thead>
        <tr>
            <th>previous_snapshot_id</th>
            <th>current_snapshot_id</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>2279922865032537001</td>
            <td>5161623784319151399</td>
        </tr>
    </tbody>
</table>




```sql
%%sql

SELECT * FROM test.test;
```

                                                                                    




<table>
    <thead>
        <tr>
            <th>c1</th>
            <th>c2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>None</td>
        </tr>
    </tbody>
</table>




```sql
%%sql

DESCRIBE TABLE test.test;
```




<table>
    <thead>
        <tr>
            <th>col_name</th>
            <th>data_type</th>
            <th>comment</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>c1</td>
            <td>int</td>
            <td></td>
        </tr>
        <tr>
            <td>c2</td>
            <td>int</td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td># Partitioning</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Not partitioned</td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>




```sql
%%sql

SELECT * FROM test.test.snapshots;
```




<table>
    <thead>
        <tr>
            <th>committed_at</th>
            <th>snapshot_id</th>
            <th>parent_id</th>
            <th>operation</th>
            <th>manifest_list</th>
            <th>summary</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>2022-08-22 07:47:45.143000</td>
            <td>5161623784319151399</td>
            <td>None</td>
            <td>append</td>
            <td>s3://tabular-wh-us-west-2-dev/8bcb0838-50fc-472d-9ddb-8feb89ef5f1e/03b32560-7561-4f96-992b-01ef730946f5/metadata/snap-5161623784319151399-1-cde4c05b-670c-47dd-8860-bcd6f07756f9.avro</td>
            <td>{&#x27;added-data-files&#x27;: &#x27;1&#x27;, &#x27;total-equality-deletes&#x27;: &#x27;0&#x27;, &#x27;added-records&#x27;: &#x27;1&#x27;, &#x27;partition-summaries-included&#x27;: &#x27;true&#x27;, &#x27;partitions.&#x27;: &#x27;added-data-files=1,added-records=1,added-files-size=389&#x27;, &#x27;total-records&#x27;: &#x27;1&#x27;, &#x27;spark.app.id&#x27;: &#x27;local-1661154453400&#x27;, &#x27;changed-partition-count&#x27;: &#x27;1&#x27;, &#x27;total-position-deletes&#x27;: &#x27;0&#x27;, &#x27;added-files-size&#x27;: &#x27;389&#x27;, &#x27;total-delete-files&#x27;: &#x27;0&#x27;, &#x27;total-files-size&#x27;: &#x27;389&#x27;, &#x27;total-data-files&#x27;: &#x27;1&#x27;}</td>
        </tr>
        <tr>
            <td>2022-08-22 07:47:52.492000</td>
            <td>2279922865032537001</td>
            <td>5161623784319151399</td>
            <td>append</td>
            <td>s3://tabular-wh-us-west-2-dev/8bcb0838-50fc-472d-9ddb-8feb89ef5f1e/03b32560-7561-4f96-992b-01ef730946f5/metadata/snap-2279922865032537001-1-58b2d439-1420-49c2-bf06-228c77f1ebd0.avro</td>
            <td>{&#x27;added-data-files&#x27;: &#x27;1&#x27;, &#x27;total-equality-deletes&#x27;: &#x27;0&#x27;, &#x27;added-records&#x27;: &#x27;1&#x27;, &#x27;partition-summaries-included&#x27;: &#x27;true&#x27;, &#x27;partitions.&#x27;: &#x27;added-data-files=1,added-records=1,added-files-size=599&#x27;, &#x27;total-records&#x27;: &#x27;2&#x27;, &#x27;spark.app.id&#x27;: &#x27;local-1661154453400&#x27;, &#x27;changed-partition-count&#x27;: &#x27;1&#x27;, &#x27;total-position-deletes&#x27;: &#x27;0&#x27;, &#x27;added-files-size&#x27;: &#x27;599&#x27;, &#x27;total-delete-files&#x27;: &#x27;0&#x27;, &#x27;total-files-size&#x27;: &#x27;988&#x27;, &#x27;total-data-files&#x27;: &#x27;2&#x27;}</td>
        </tr>
    </tbody>
</table>




```sql
%%sql

REFRESH TABLE test.test
```




<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>




```sql
%%sql

SELECT * FROM test.test;
```

                                                                                    




<table>
    <thead>
        <tr>
            <th>c1</th>
            <th>c2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>None</td>
        </tr>
    </tbody>
</table>



# Waiting one minute


```sql
%%sql

SELECT * FROM test.test;
```

                                                                                    




<table>
    <thead>
        <tr>
            <th>c1</th>
            <th>c2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>None</td>
        </tr>
    </tbody>
</table>

**Comment by Fokko** [comment]
@ebyhr Thanks for reporting this, this looks like a bug 🐛  I've created a PR to fix this, but I would love to get some input from other maintainers.

**Comment by rdblue** [comment]
This isn't a bug. Metadata and data updates are intended to be separate, although I can see why there are cases where you'd assume that they are not.

If you update the schema and commit data in a single job, then it isn't unreasonable to assume the schema change would be rolled back. But if I concurrently add a column while someone else commits, then a rollback should be independent. Expectations can go both ways.

While expectations differ, Iceberg never rolls back to a previous schema because that operation is unsafe. For example, if someone deletes a required column and then tries to roll that back, there may have been data written without that column. You can recover the column, but you need to make it optional (or in the future, set a read default).

**Comment by Fokko** [comment]
@rdblue thanks for the background information. I see the point.

One question, are there situations where it is possible to do a rollback, but still have additional data being written? I would expect that the rollback would cause a conflict on a concurrent write. And then it would fail because of a schema mismatch.

**Comment by rdblue** [comment]
Schema evolution rules allow always being able to write with an older schema, so that there is no need to check whether the schema a writer is using is allowed. That cuts down on commit conflicts, but it also means that schemas should always be rolled forward and never backward. I don't think that we want to start adding extra validation to support a case where we roll back a schema.

**Comment by ebyhr** [comment]
> This isn't a bug.

Could you please document the behavior? I believe the current behavior isn't intuitive and I saw some other people said "it's a bug".

**Comment by findepi** [comment]
From end-user perspective, there is a difference between

1. querying table state at given snapshot -- at least in Trino, this uses the "schema current at that time", so includes columns that have been dropped since then

2. query table state after rollback_to_snapshot -- if this uses current schema, this doesn't include columns that have been dropped since the snapshot

Now consider example

```
-- add new column
ALTER TABLE orders ADD COLUMN order_timestamp timestamp(6) with time zone;
-- feel in data for new column
UPDATE orders SET order_timestamp = CAST(json_value(order_data, '$.timestamp') AS timestamp(6) with time zone);
-- drop the now-redundant column
ALTER TABLE orders DROP COLUMN order_data;

-- imagine now that comparing this uncovered that `order_data` was encoded in a bad way, so we need to roll this all back
CALL rollback_to_snapshot(.....)
```

As a user, i would expect to see `order_data` column back in my table.
Per this issue, i understand this wouldn't be the case. As a user I would call it a data loss (and so a bug).

cc @alexjo2144 @electrum
