### ISSUE TITLE
Support to write a custom partition transforms in iceberg 

### ISSUE THREAD

**Issue by vamen** [apache/iceberg#5606]
### Feature Request / Improvement

Some times we often need to partition the column based on  transforms that are not  one among the already defined Partition Transforms[ 🔗](https://iceberg.apache.org/spec/#partition-transforms).

It would be great if there is a way to create custom partition transform by extending some base transform class and plug in the custom transform class in the spark config.

There are couple of use cases in the past where we need this.

1)  We needed to partition the data on half yearly / quarterly basis similar to year , month and date 
2) We wanted to hash on primary key columns and apply truncate transform on it as part of single partition transform and write.
    - Having custom transform plugged in will allow users to query the data  using actual primary key values. 
@RussellSpitzer @rdblue 

### Query engine

Spark

**Comment by majin1102** [comment]
hi, vamen
maybe we could use an UDF to transform custom partition field to meet your needs

cause from my view, transforming extension on sql(flink/spark/trino. etc) could be a heavy option and hard to maintenance and share
