### ISSUE TITLE
Use DefaultAWSCredentialsProviderChain for AWS credentials

### ISSUE THREAD

**Issue by chajath** [apache/iceberg#5608]
### Feature Request / Improvement

[DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) is preferred way of getting the AWS credentials and it works around the problem of for example instance-based credentials overriding service account based credentials on k8s. Inconsistency in AWS credential resolution between different parts of Spark application creates a lot of confusion in deployment story.

**Comment by majidazimi** [comment]
@chajath Did you manage to configure this work with instance profile based credentials (like IRSA on k8s)? The only way for me is to implement `AwsClientFactory` and provide custom client factory. I don't find any solution to configure Glue client to use IRSA.
