### ISSUE TITLE
[python] Provide an implementation for combining FileScanTask into an arrow table

### ISSUE THREAD

**Issue by TGooch44** [apache/iceberg#561]
One of the primary way of consuming data in python is expected to be by returning a combined arrow table that is the result of reading from all of the FileScanTasks generated from a TableScan.plan_tasks().

**Comment by Fokko** [comment]
This issue has been resolved a while ago. Closing this PR since we've split out the Python implementation into a separate repository: https://github.com/apache/iceberg-python
