### ISSUE TITLE
[python] Add implementation for converting a TableScan into a pandas DF

### ISSUE THREAD

**Issue by TGooch44** [apache/iceberg#562]
One of the primary way of consuming data in python is expected to be by returning a pandas dataframe  that is the result of reading from all of the FileScanTasks generated from a TableScan.plan_tasks().

**Comment by BACtaki** [comment]
Hi @danielcweeks , is anyone working on this?

**Comment by TGooch44** [comment]
The python library as a whole is currently being refactored[1]. Part of the
goal of that effort is to produce a library with that feature.
I'd encourage you to join the sync meeting[2](there is one coming up next
Wednesday 11/10) if you are interested in get more context on the current
progress, or to read the meeting notes[3] if you aren't able to attend

[1]
https://docs.google.com/document/d/17emc0cag-edj0Nf9CCgZa0UZhEBIfHhUZH-7u5CAenc/edit#
[2] https://groups.google.com/g/iceberg-python-sync
[3]
https://docs.google.com/document/d/1oMKodaZJrOJjPfc8PDVAoTdl02eGQKHlhwuggiw7s9U/edit#

**Comment by TGooch44** [comment]
I should also mention there is a Slack workspace for the project:
https://join.slack.com/t/apache-iceberg/shared_invite/zt-tlv0zjz6-jGJEkHfb1~heMCJA3Uycrg

**Comment by BACtaki** [comment]
Thanks @TGooch44 ! I'll join the meeting on 11/10 to see how I can get involved.

**Comment by Fokko** [comment]
This issue has been resolved a while ago. Closing this PR since we've split out the Python implementation into a separate repository: https://github.com/apache/iceberg-python
