### ISSUE TITLE
Can use HadoopCatalog to create Iceberg on S3?

### ISSUE THREAD

**Issue by allenhaozi** [apache/iceberg#5620]
### Apache Iceberg version

0.14.0 (latest release)

### Please describe the bug 🐞

like the following code:
```java
        HadoopCatalog catalog = HadoopCatalog();

        Schema schema = buildSchema(createTable.getColumns());
        String tableName = createTable.getName();
        TableIdentifier name = TableIdentifier.of(fqn.split("\\."));

        catalog.createTable(name, schema);
        
```

**Comment by Fokko** [comment]
Hey @allenhaozi You can, but it is highly discouraged. The HadoopCatalog relies on atomic renames that HDFS provides, and this isn't supported by object storage like S3. Therefore using a catalog is the recommended way of doing this.

**Comment by allenhaozi** [comment]
> Hey @allenhaozi You can, but it is highly discouraged. The HadoopCatalog relies on atomic renames that HDFS provides, and this isn't supported by object storage like S3. Therefore using a catalog is the recommended way of doing this.

thank you @Fokko 

Is there a sample code for Java here? I am new to Java.

**Comment by Fokko** [comment]
Depends on what you're trying to achieve. In the case you're new to Java, you could create Iceberg tables using Spark SQL: https://iceberg.apache.org/docs/latest/getting-started/

**Comment by allenhaozi** [comment]
got it, thank you @Fokko
