### ISSUE TITLE
[Question] Flink SQL read upsert data from iceberg

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/iceberg#5623]
### Query engine

Flink 1.14.4

### Question

In the "iceberg 0.13.2" version, does it support streaming Flink SQL to read upsert data？

**Comment by luoyuxia** [comment]
Do you means [streaming reading](https://iceberg.apache.org/docs/0.13.2/flink/#flink-streaming-read)?  It should support.

**Comment by luoyuxia** [comment]
FYI
> current Flink streaming read doesn't support upsert/row-level deletes
https://github.com/apache/iceberg/issues/5803#issuecomment-1259759074
