### ISSUE TITLE
Unsupported partition transform

### ISSUE THREAD

**Issue by jasondavindev** [apache/iceberg#5637]
### Apache Iceberg version

0.14.0 (latest release)

### Query engine

Athena

### Please describe the bug 🐞

In the below scenarios Athena returns `GENERIC_INTERNAL_ERROR: Unsupported partition transform: 1000`

- Write dataset using overwrite mode
- Changes table partition fields

I have a table partitioned by the `date` column and after I changed the partition field to `months(date)` Athena cannot query the table returning `GENERIC_INTERNAL_ERROR: Unsupported partition transform: 1000: date: void(7)`

I'm using
Iceberg 0.14.0
Spark 3.2.1 - AWS EMR Containers release 6.6.0 with provided Iceberg jar

**Comment by singhpk234** [comment]
As per this doc, Athena  only supports Iceberg V2 Tables. : https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg.html

"_**Iceberg v2 tables – Athena only creates and operates on Iceberg v2 tables. For the difference between v1 and v2 tables, see [Format version changes](https://iceberg.apache.org/spec/#appendix-e-format-version-changes) in the Apache Iceberg documentation.**_"

By default iceberg table creates tables in v1 format : 
https://github.com/apache/iceberg/blob/1526c1f663b2359de01183160b1236cd4eee04bf/core/src/main/java/org/apache/iceberg/TableMetadata.java#L51

Can you please try updating table format verison to 2 in table properties
