### ISSUE TITLE
DecoderResolver may lead to OOM of flink jobs writing to iceberg tables

### ISSUE THREAD

**Issue by ldwnt** [apache/iceberg#5652]
### Apache Iceberg version

0.13.1

### Query engine

Flink

### Please describe the bug 🐞

I have a flink job writing to iceberg tables. When the job runs for several days, an OOM occurs. The reason is described below:

The DecoderResolver holds a ThreadLocal variable of a two-layer map:
```
    private static final ThreadLocal<Map<Schema, Map<Schema, ResolvingDecoder>>> DECODER_CACHES = ThreadLocal.withInitial(() -> {
        return (new MapMaker()).weakKeys().makeMap();
    });

    private static ResolvingDecoder resolve(Decoder decoder, Schema readSchema, Schema fileSchema) throws IOException {
        Map<Schema, Map<Schema, ResolvingDecoder>> cache = (Map)DECODER_CACHES.get();
        Map<Schema, ResolvingDecoder> fileSchemaToResolver = (Map)cache.computeIfAbsent(readSchema, (k) -> {
            return Maps.newHashMap();
        });
...
    }
```

The outer map has a weak key while the inner map has a strong one. As the inner map holds a reference to a Schema object, the outer map holding the same weak reference to the Schema object will not release the weak key. That leads to the OOM.

What I suggest is to change the inner map to one with weak key, too:
```
        Map<Schema, ResolvingDecoder> fileSchemaToResolver = (Map)cache.computeIfAbsent(readSchema, (k) -> {
//            return Maps.newHashMap();
            return new WeakHashMap<>();
        });
```

So far it seems working with my jobs.

**Comment by stevenzwu** [comment]
@ldwnt while your analysis on the inner map makes send to me, I have a couple of questions. 

- shouldn't `DecoderResolver` only be used by reader (not writer)?
- I assume you confirmed the memory issue from a heap dump?

**Comment by ldwnt** [comment]
> * shouldn't `DecoderResolver` only be used by reader (not writer)?
I'm not familiar with Iceberg source code, but are meta files (manifest list/manifest) read during writing and that involves DecoderResolver?
> * I assume you confirmed the memory issue from a heap dump?
Yes, please refer to the snapshot below:
![image](https://user-images.githubusercontent.com/7655486/190180075-aa92912f-fc2c-4bf6-84ae-5aaed85fcb1e.png)

**Comment by magus0219** [comment]
@ldwnt @stevenzwu 
I meet the same issue and hope for the official fix.

**Comment by stevenzwu** [comment]
@ldwnt can you create a PR for the weak reference fix?

Regarding the OOM, does your use case have many different read schemas and file schemas?

**Comment by ldwnt** [comment]
> @ldwnt can you create a PR for the weak reference fix?

Sure, I'll cerate one. 

> Regarding the OOM, does your use case have many different read schemas and file schemas?

I have a job writing to around 100 iceberg tables. The table schema barely changes, but snapshots and manifests are continuously generated due to incoming data.

**Comment by stevenzwu** [comment]
> I have a job writing to around 100 iceberg tables. The table schema barely changes, but snapshots and manifests are continuously generated due to incoming data.

We also have a similar setup internally. We didn't run into OOM issue. Not sure what's the difference here.

Checking your heap dump. The whole map has retained memory of 109 MB, which doesn't seem too much? is that the main cause of the OOM?

**Comment by takeono** [comment]
Our flink app that commits every minute causes OOM after a month. This may be because each commit generates a avro reader/writer to read/writer the manifest.

With the current implementation, when readSchema and fileSchema are the same reference (this can happen), Schema object is not released even if the reference holder disappears. This is because the reference continues to exist as a key for the inner map.

So the fileSchema used as the key should be a cloned one.

**Comment by ConeyLiu** [comment]
We have met a similar problem and I have submitted a PR for this. @stevenzwu Could you help to review it?
