### ISSUE TITLE
Flink: Metric can be selectively enabled or disabled

### ISSUE THREAD

**Issue by xuzhiwen1255** [apache/iceberg#5664]
### Feature Request / Improvement

After the test, the writing efficiency will be affected after the Metric is enabled. Can we selectively enable the Metric? Because some scenarios do not need or users do not need the Metric, disabling the Metric can improve the performance to a certain extent

CC: @rdblue @jackye1995 @namrathamyske @aokolnychyi @rdblue @kbendick @szehon-ho @nastra

### Query engine

Flink

**Comment by szehon-ho** [comment]
Metrics are able to be selectively enabled: https://iceberg.apache.org/docs/latest/configuration/#write-properties.  see "write.metadata.metrics.column.col1"
