### ISSUE TITLE
Limit the number of files for rewrite/compaction action

### ISSUE THREAD

**Issue by dmgcodevil** [apache/iceberg#5675]
### Query engine

Flink

### Question

We have a streaming Flink job that continously consumes records from Kafka and stores them into Iceberg. 
The [RewriteDataFilesAction](https://github.com/apache/iceberg/blob/master/flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/actions/RewriteDataFilesAction.java) is getting slower over time and `TaskManager` is starting to fail with OOM. Is it possible to limit the number of data files for compaction? I have the following ideas:

1. Modify https://github.com/apache/iceberg/blob/master/flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/actions/RewriteDataFilesAction.java#L49 to limit a number of `FileScanTask` in `CombinedScanTask`. We can create some sort of _wrapper_:

```java
    class BoundedCombinedScanTask implements CombinedScanTask {
        private final CombinedScanTask original;
        private final int limit;

        public BoundedCombinedScanTask(CombinedScanTask original, int limit) {
            this.original = original;
            this.limit = limit;
        }

        @Override
        public Collection<FileScanTask> files() {
            return original.files().stream().limit(limit).collect(Collectors.toList());
        }

        @Override
        public CombinedScanTask asCombinedScanTask() {
            return original;
        }
    }
```

Flink code will look as follows:

```java
protected List<DataFile> rewriteDataForTasks(final List<CombinedScanTask> combinedScanTasks) {
        final List<CombinedScanTask boundedCombinedScanTasks = combinedScanTasks.stream(t -> new BoundedCombinedScanTask(t, 100)).collect(Collectors.toList());
        int size = boundedCombinedScanTasks .size();
        int parallelism = Math.min(size, this.maxParallelism);
        DataStream<CombinedScanTask> dataStream = this.env.fromCollection(boundedCombinedScanTasks );
        RowDataRewriter rowDataRewriter = new RowDataRewriter(this.table(), this.caseSensitive(), this.fileIO(), this.encryptionManager());

        try {
            return rowDataRewriter.rewriteDataForTasks(dataStream, parallelism);
        } catch (Exception var7) {
            throw new RuntimeException("Rewrite data file error.", var7);
        }
    }
```

2. Modify [BaseRewriteDataFilesAction](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java) https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java#L268

So that each group will contain at most N files.

Another approach is to limit the number of bins https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/BinPacking.java (edit: is it controled by `lookback` ?)

**Comment by stevenzwu** [comment]
@dmgcodevil not quite following option 1 that you described. that will skip some files for compaction, right? 

seems like the `lookback` is the right knob for your problem.

**Comment by dmgcodevil** [comment]
PR: https://github.com/apache/iceberg/pull/6174

**Comment by nastra** [comment]
@dmgcodevil did you try solving your issue by setting `read.split.planning-lookback`?

**Comment by dmgcodevil** [comment]
@nastra do you mean [this](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java#L167) ? What is supposed to do?

**Comment by nastra** [comment]
This is the `lookback` parameter that is being passed to `BinPacking.PackingIterable`. According to the docs it is `Number of bins to consider when combining input splits`

**Comment by dmgcodevil** [comment]
@nastra oh, right, we tried that. It limits the number of bins while iterating, however, the whole input will be processed anyway.
see https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/BinPacking.java#L122-L154
