### ISSUE TITLE
Document release candidate validation process

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#568]
I think we need to document [steps required to validate a release candidate](http://mail-archives.apache.org/mod_mbox/iceberg-dev/201910.mbox/%3cCAO4re1kCSRLF1AZwQ0efshammE+xxdB275_Z9wvLv1hDzSyYKw@mail.gmail.com%3e) somewhere on the website.

**Comment by rdsr** [comment]
This seems ripe for automation. Maybe check this ticket to create a script for validation of a release?

**Comment by aokolnychyi** [comment]
@rdsr I think having a script is a great idea!

**Comment by aokolnychyi** [comment]
This has been resolved.
