### ISSUE TITLE
Not dropping stats when scanning all columns caused Spark driver exceeding GC limit

### ISSUE THREAD

**Issue by manuzhang** [apache/iceberg#5706]
### Apache Iceberg version

0.13.1

### Query engine

Spark

### Please describe the bug 🐞

We recently migrated a Spark parquet table to Iceberg table. With the same query scanning all columns and return 10 rows, the Spark job after migration failed due to driver exceeding GC limit.

```sql
select * from iceberg_table limit 10;
```

The driver memory is set to 4g. After dumping the driver memory, I find it's most taken up by the stats like `lowerBounds` maps from the `GenericDataFile`. 

That has lead me to https://github.com/apache/iceberg/blob/apache-iceberg-0.13.1/core/src/main/java/org/apache/iceberg/ManifestReader.java#L292 where stats are returned when scanning all columns.

```java
  static boolean dropStats(Expression rowFilter, Collection<String> columns) {
    // Make sure we only drop all stats if we had projected all stats
    // We do not drop stats even if we had partially added some stats columns, except for record_count column.
    // Since we don't want to keep stats map which could be huge in size just because we select record_count, which
    // is a primitive type.
    if (rowFilter != Expressions.alwaysTrue() && columns != null &&
        !columns.containsAll(ManifestReader.ALL_COLUMNS)) {
      Set<String> intersection = Sets.intersection(Sets.newHashSet(columns), STATS_COLUMNS);
      return intersection.isEmpty() || intersection.equals(Sets.newHashSet("record_count"));
    }
    return false;
  }
```

The issue is resolved by either removing `!columns.containsAll(ManifestReader.ALL_COLUMNS)` or not scanning all columns.

**Comment by manuzhang** [comment]
@rdblue @yyanyy Do you know why we not drop stats for `ManifestReader.ALL_COLUMNS`?

**Comment by manuzhang** [comment]
@rdblue Thanks for pointing out that it's manifest columns being projected. Also, with `rowFilter` being `true` `dropStats` is `false` regardless of the columns. Disabling parallel planning only has made it slower but not solved the memory issue.

After more debugging, I find [all stats are read from manifest file](https://github.com/apache/iceberg/blob/apache-iceberg-0.13.1/core/src/main/java/org/apache/iceberg/ManifestReader.java#L202) and [copied to data file](https://github.com/apache/iceberg/blob/apache-iceberg-0.13.1/core/src/main/java/org/apache/iceberg/ManifestGroup.java#L181) with `dropStats` being false.

**Comment by manuzhang** [comment]
I also did a heap dump which proved it's stats like `valueCount` from `GenericDataFile` that took up so much memory.

<img width="1396" alt="CleanShot 2022-09-09 at 15 39 30@2x" src="https://user-images.githubusercontent.com/1191767/189484086-00add250-83ad-41fa-b6f8-71e6a67fd418.png">

![image](https://user-images.githubusercontent.com/1191767/189484099-d394bb91-aac0-4f5e-9f09-af23265c1950.png)

**Comment by rdblue** [comment]
@manuzhang, it sounds like the problem is that dropStats is false for some reason. Do you know why that's happening?

**Comment by manuzhang** [comment]
@rdblue It's because `rowFilter == true` in the following function.

```
  static boolean dropStats(Expression rowFilter, Collection<String> columns) {
    // Make sure we only drop all stats if we had projected all stats
    // We do not drop stats even if we had partially added some stats columns, except for record_count column.
    // Since we don't want to keep stats map which could be huge in size just because we select record_count, which
    // is a primitive type.
    if (rowFilter != Expressions.alwaysTrue() && columns != null &&
        !columns.containsAll(ManifestReader.ALL_COLUMNS)) {
      Set<String> intersection = Sets.intersection(Sets.newHashSet(columns), STATS_COLUMNS);
      return intersection.isEmpty() || intersection.equals(Sets.newHashSet("record_count"));
    }
    return false;
  }
```

**Comment by rdblue** [comment]
I just did some digging and I think that the reason for checking whether the row filter is always true is to match the logic when we add stats columns. We only add stats columns if the row filter is non-trivial (not always true) so we probably carried that over when removing stats columns. If tests are passing without this, then I think it would be safe to drop that requirement.

**Comment by manuzhang** [comment]
@rdblue thanks for checking. I opened #5815 to fix it. Please help review.
