### ISSUE TITLE
Registering BucketUDF on PySpark

### ISSUE THREAD

**Issue by mrendi29** [apache/iceberg#5721]
### Query engine

Apache Spark (PySpark)

### Question

On https://iceberg.apache.org/docs/latest/spark-writes/#writing-to-partitioned-tables if you need to register the bucket UDF you can do so by:

```
import org.apache.iceberg.spark.IcebergSpark
import org.apache.spark.sql.types.DataTypes

IcebergSpark.registerBucketUDF(spark, "iceberg_bucket16", DataTypes.LongType, 16)
```
How would we do this in PySpark? Does the method below work or is there another suggested method? 

```
from pyspark.sql.types import  LongType
from pyspark.sql import functions as F

spark.udf.register("iceberg_bucket16", F.bucket(16), LongType())
```

**Comment by fireking77** [comment]
I would also curious about this question!

**Comment by TechTinkerer42** [comment]
Here is an example of Pyspark code to register a bucketing UDF. @mrendi29, I hope you have figured out your issue by now, but I'm sharing this in case it helps someone else.

` # Register bucket UDF
    jvm_gateway = spark.sparkContext._gateway.jvm
    iceberg_spark = jvm_gateway.org.apache.iceberg.spark.IcebergSpark
    data_types = jvm_gateway.org.apache.spark.sql.types.DataTypes
    # 100 is the number of buckets
    iceberg_spark.registerBucketUDF(spark._jsparkSession, "iceberg_bucket", data_types.StringType, 100)
    `
