### ISSUE TITLE
iceberg's spark-runtime version 0.14  jar contains scala classes rather than 0.13 may cause ClassCastException

### ISSUE THREAD

**Issue by KarlManong** [apache/iceberg#5732]
### Apache Iceberg version

0.14.0 (latest release)

### Query engine

Other

### Please describe the bug 🐞

When using [kyuubi](https://kyuubi.readthedocs.io/en/latest/), I got an exception:

<img width="1428" alt="企业微信截图_7d656f74-2b0f-416d-b643-1816c8973e38" src="https://user-images.githubusercontent.com/2627662/189279089-a47ad23a-324b-47a1-a115-9d4585f52128.png">

After compared version 0.13.2 and 0.14.0, I found scala classed contained in 0.14.x which cause some ClassCastExceptions .
<img width="629" alt="image" src="https://user-images.githubusercontent.com/2627662/189279556-70d43dd2-9b76-41ce-b485-072d26b09602.png">

**Comment by Fokko** [comment]
@KarlManong do you have more information on the Spark version and the version of Iceberg JARs that you are using?

**Comment by ajantha-bhat** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/5889404/189678815-8a89f2f1-cf8a-426b-9032-b0ea2949f9ac.png">

I do see a scala folder in 0.14.0 when I compare spark-3.2 Iceberg runtime jars from  0.13.2 and 0.14.0

**Comment by jotarada** [comment]
I have a collision problem when doing assembly on spark 3.2.1, scala 2.12.12 when moving from iceberg runtime 0.13.2 to  0.14.0 or 0.14.1

**Comment by ajantha-bhat** [comment]
I see only two commits that modifies the runtime jars gradle files after 0.13.2

1) https://github.com/apache/iceberg/commit/4d7837093bd19a42237446a9b656a248e106b789#diff-b15dc25a696e6961c7612efe266e5cb1b999a530ad91e5c552ca8105dd7cbc1a

2) https://github.com/apache/iceberg/commit/8752e778573c5bb528ecfdd3f8af7fa0bb4a3cad

Might have to manually revert and check.

**Comment by ajantha-bhat** [comment]
@KarlManong : What are the steps to reproduce the issue?

@jotarada mentioned "in my case is doing sbt assembly, as it tries to build a fat jar with all the dependencies.  Trying to add scala with existing scala in iceberg crashes"

**Comment by KarlManong** [comment]
The key point is setting "spark.executor.userClassPathFirst" to  true.

@Fokko @ajantha-bhat  I have uploaded files to https://gist.github.com/KarlManong/cb30a80624788f4f7804c232dc2f743c.

Septs:
1. please change the metastore uri at file '[spark-defaults.conf](https://gist.github.com/KarlManong/cb30a80624788f4f7804c232dc2f743c#file-spark-defaults-conf)' 
2. run `docker build`
3. run `docker run -it <image-id> /bin/bash`
4. execute `./bin/kyuubi start` in the container
5. execute `./bin/beeline -u "jdbc:hive2://localhost:10009"` in the container

Thank You!

**Comment by ajantha-bhat** [comment]
It finally mapped down to https://github.com/apache/iceberg/pull/4009

this adds dependency on `scala.collection.compat` which brings scala code to the runtime jars (and also other spark iceberg jars)

**Comment by ajantha-bhat** [comment]
@KarlManong , @jotarada : Can you please build a runtime jar from this PR (#5754) and confirm whether the issue is resolved?

**Comment by KarlManong** [comment]
@ajantha-bhat verified, Thank You! Will this patch backport to branch-0.14?

**Comment by Fokko** [comment]
@KarlManong You could give it a try using the development snapshot: https://github.com/apache/iceberg-docs/pull/162

**Comment by Fokko** [comment]
I also added 0.14.2 as a discussion point for the upcoming sync: https://docs.google.com/document/d/1YuGhUdukLP5gGiqCbk0A5_Wifqe2CZWgOd3TbhY3UQg/edit#
