### ISSUE TITLE
Spark + HMS + Minio(S3) missing slash at uri path when just using bucket-name

### ISSUE THREAD

**Issue by meyergin** [apache/iceberg#5741]
### Apache Iceberg version

0.14.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞
hive-metastore: 3.1.3
hadoop: 3.3.4

the spark catalog configure as follow:
```
spark.sql.catalog.warehouse.type                hive
spark.sql.catalog.warehouse.warehouse           s3a://warehouse/
```
when I tried to ```create database test``` at Spark-SQL, it throws error:
java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: s3a://warehousetest
seems that the spark-iceberg runtime missed slash and give wrong path to HMS.
After add folder path, it works well: 
```spark.sql.catalog.warehouse.warehouse s3a://warehouse/test/```
And I switch to trino, it creates correct schema at s3a://warehouse, seems hms works well.

**Comment by Fokko** [comment]
Hey @meyergin thanks for raising this. I ran into the same issue and pushed a fix here: https://github.com/apache/iceberg/pull/5405

This has been merged and is in the codebase. Unfortunately, this hasn't been released yet. This should be part of the upcoming 1.0 release. I'm going to close this, for now, feel free to reopen it if you have any further questions.

**Comment by meyergin** [comment]
have seen the commit, thanks for your reply.
