### ISSUE TITLE
Why is region not set in AwsClientFactories

### ISSUE THREAD

**Issue by XBaith** [apache/iceberg#5769]
### Query engine

Java API

### Question

In `AwsClientFactories`, the region is not set in the `s3()` and `glue()` functions. This causes some exceptions when using the Java API. So is it necessary to append the region in the relevant builder?
```
public GlueClient glue() {
  return GlueClient.builder().httpClientBuilder(configureHttpClientBuilder(httpClientType)).build();
}
```

```
public S3Client s3() {
  return S3Client.builder()
      .httpClientBuilder(configureHttpClientBuilder(httpClientType))
      .applyMutation(builder -> configureEndpoint(builder, s3Endpoint))
      .serviceConfiguration(s3Configuration(s3PathStyleAccess, s3UseArnRegionEnabled))
      .credentialsProvider(credentialsProvider(s3AccessKeyId, s3SecretAccessKey, s3SessionToken))
      .build();
}
```

**Comment by amogh-jahagirdar** [comment]
The exposed way currently is for allowing an endpoint override (which can be used for essentially setting another region) for each of these, the default aws client factory and assume role client factories leverage those. For example, check out https://github.com/apache/iceberg/blob/master/aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java#L152.

I do agree though it would be nice to have a simpler interface for just setting region. For that, I think we can follow up on this [PR](https://github.com/apache/iceberg/pull/5046/files). cc: @dungdm93
