### ISSUE TITLE
run SmokeTest with ClassNotFoundException

### ISSUE THREAD

**Issue by lordk911** [apache/iceberg#5791]
### Query engine

spark

### Question

I clone the iceberg project to idea , when trying to run spark/v3.3/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java

I got some test faild with  `java.lang.ClassNotFoundException: scala.jdk.CollectionConverters$` error

I want to know how can I run the test, thanks.

**Comment by nastra** [comment]
I can confirm that those are actually failing when running `./gradlew :iceberg-spark:iceberg-spark-runtime-3.3_2.12:integrationTest`

**Comment by nastra** [comment]
@lordk911 can you please re-try running the smoke test with the fix proposed in https://github.com/apache/iceberg/pull/5819?
