### ISSUE TITLE
Read iceberg table into a PyArrow Dataset

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#5801]
### Feature Request / Improvement

Convert an Iceberg table into a PyArrow dataset. This would unlock all the users that use Arrow and Pandas. This way users can read data that fits into memory from a huge iceberg table, and iterate on it quickly.

### Query engine

Other

**Comment by djouallah** [comment]
Looking forward to use it with DuckDB :)

**Comment by dungdm93** [comment]
Implemented in #6233

**Comment by djouallah** [comment]
@dungdm93 trust me, I made sure every one knows about it :) , please don't close till the python binary is released :)
https://twitter.com/mim_djo/status/1594821677904715776

**Comment by Fokko** [comment]
Since this is in, I'm going to close this to clean up the milestone for the next release. This way we can see what needs to be done before creating the Release Candidate.

**Comment by ianmcook** [comment]
Nit: the term _Dataset_ has a [specific meaning in PyArrow](https://arrow.apache.org/docs/python/dataset.html). It refers to a lazily read set of files on disk. As opposed to a _Table_ in PyArrow which is materialized in memory. I believe what has been implemented in #6233 is converting an Iceberg Table to a PyArrow _Table_.

**Comment by Fokko** [comment]
@ianmcook that is correct. If you have a petabyte Iceberg table, and you'll select a subset of the rows, only the relevant files are being read. This is directly read into a `pa.table`, and not a `pa.dataset`. If we want to make this truly lazy, the Iceberg primitives need to be implemented on the PyArrow side.

**Comment by djouallah** [comment]
either there is a bug or it is really loading a table not a view , testing it in colab and it is Out of memory

**Comment by Fokko** [comment]
@djouallah you are right on that. 

Currently, it is still a two-stage rocket, you first need to prune the data using the PyIceberg `row_filter`:

```python
catalog = load_catalog('default')
tbl = catalog.load_table('nyc.taxis')

sc = tbl.scan(row_filter=And(
    GreaterThanOrEqual("tpep_pickup_datetime", "2022-01-01T00:00:00.000000+00:00")
    LessThan("tpep_pickup_datetime", "2022-02-01T00:00:00.000000+00:00")
).to_arrow() # Same for .to_duckdb()
```

This will load all the data from January. If you don't pass in a `row_filter`, it will pull in the current version of the table. Right now, it won't push the predicate down to the Iceberg layer, unfortunately. This is something that we're working on but requires tighter integration with PyArrow and DuckDB.

**Comment by djouallah** [comment]
@Fokko that's fine, the confusion is in the title of the bug report, Pyarrow dataset means a view, but currently to_duckdb() load a table that's two different thing, that's the same point raised by @ianmcook 

the row_filter does not work anyway in 0.3, so basically we end up with crashing the local session as it loads the whole table

**Comment by Fokko** [comment]
> the row_filter does not work anyway in 0.3

Can you elaborate? Or even better, create a ticket for this?

> do you mind changing the title of the bug and replace dataset with table.

No problem at all
