### ISSUE TITLE
Python: Add CLI support for adding existing parquet file to table.

### ISSUE THREAD

**Issue by joshuarobinson** [apache/iceberg#5825]
### Feature Request / Improvement

The request is for the CLI to be able to add a parquet file (created by another tool) to an existing Iceberg table. The closest equivalent functionality would be the [add_files](https://iceberg.apache.org/docs/latest/spark-procedures/#add_files) Spark procedure.

The idea is that some/any other tool can write a parquet file to a location in the table directory and then invoke the CLI to import that into the table with metadata-only operations. Specifically, the CLI just creates the manifests and snapshot metadata and can optionally validate the schema of the parquet file.

Motivation: this would be an easy way to increase composability of Iceberg with other tools and serve as a waypoint on the way to getting full support for adding data via the python SDK.

**Comment by rdblue** [comment]
This would be great! I think it's a little ways out since we can't yet write metadata files. But I think this should be an early target because it is basically the append path.
