### ISSUE TITLE
Add support to set "use-table-distribution-and-ordering" in table level or session level

### ISSUE THREAD

**Issue by rbalamohan** [apache/iceberg#5853]
### Feature Request / Improvement

Iceberg adds "sort" before writing out partitioned dataset. 

"use-table-distribution-and-ordering" determines if sorting can be added or not in SparkWriteBuilder/SparkWriteConf.

If user uses dataframe, he can explicitly set these options. It will be helpful to expose this option for SQL users as well via session conf or table conf.

### Query engine

Spark

**Comment by zixiao144** [comment]
flink ,do it
