### ISSUE TITLE
How to use hadoopcatelog in python?

### ISSUE THREAD

**Issue by zixiao144** [apache/iceberg#5855]
### Feature Request / Improvement

How to use hadoopcatelog in python?
Now, iceberg have hive and rest catelog,but it do't have hadoop catelog .how to do it if I use hadoop catelog in python.

### Query engine

Flink

**Comment by Fokko** [comment]
The steps are given here: https://iceberg.apache.org/docs/latest/flink/#preparation-when-using-flinks-python-api
