### ISSUE TITLE
Flink version after 1.14.3 failed to pass test cases: TestChangeLogTable.testChangeLogOnDataKey()

### ISSUE THREAD

**Issue by kingwind94** [apache/iceberg#5858]
### Apache Iceberg version

0.13.1

### Query engine

Flink

### Please describe the bug 🐞

I'm using version 1.14.5 for my flink cluster, and the 1.14 iceberg-flink connector is 1.14.0. I thought it is not a big deal to upgrade 1.14.0  to 1.14.5  (acutually bugs happened after 1.14.3).  It turned out that iceber-flink confused the Rowkind of rowdata and it gained a wrong result. 

Expected :[Record(1, aaa), Record(2, ccc), Record(2, aaa), Record(1, ccc)]
Actual   :[Record(1, aaa), Record(2, bbb), Record(2, ccc), Record(2, aaa), Record(1, bbb, 1, false), Record(1, ccc)]

I tried to discovery which flink modules affect the result, but could not find it. Some APIs are changed, totally a mess.

**Comment by kingwind94** [comment]
ps. the Iceberg version is tag 0.13.2.

**Comment by luoyuxia** [comment]
@kingwind94  Could you please explain which test method will fail?

**Comment by kingwind94** [comment]
I figure the problem myself... Set the  table configuration "table.exec.sink.upsert-materialize" to "NONE" will pass the case.

Flink 1.14.3 add an upsert materialize view before the sink, which could cause the problem.
