### ISSUE TITLE
Fix Parquet's fallback field id assignment 

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#586]
As discussed in #580, we need to fix how Parquet assigns fallback ids. Today, it checks if the schema has at least one id missing, it assigns fallback ids to all fields, but as pointed out by @rdblue it should check if  any id is set, we should not use fallback assignment.

**Comment by rdblue** [comment]
For context, I think the idea was to catch when fallback was needed as quickly as possible. That works for cases where the schema either has IDs for every field or has no IDs, as in our environment when I wrote the logic. But that isn't necessarily the case for all data files, so we should update the logic to be more careful.
