### ISSUE TITLE
Test flakiness: TestManifestCaching > testWeakFileIOReferenceCleanUp

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#5861]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

The test itself was introduced with #4518 and failed on latest master in https://github.com/apache/iceberg/actions/runs/3129464949/jobs/5078743589:

I've been running `TestManifestCaching` in a loop and this test failed quite often for me locally
```
TestManifestCaching > testWeakFileIOReferenceCleanUp FAILED
    java.lang.AssertionError: expected:<8> but was:<1>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.apache.iceberg.TestManifestCaching.testWeakFileIOReferenceCleanUp(TestManifestCaching.java:182)
```

**Comment by rizaon** [comment]
It looks like the assertion in line 182 and 184 might not be true under some corner case scenario (memory pressure). They can be removed since the next assertions in the end of the test is sufficient.

**Comment by nastra** [comment]
It looks like even with removing those 2 assertions, the test still fails at `Assert.assertEquals(2, manifestCache.estimatedSize());`
