### ISSUE TITLE
Running out of disk space on row level deletes

### ISSUE THREAD

**Issue by calvin-pietersen** [apache/iceberg#5871]
### Query engine

EMR 6.7.0
Spark 3.2.1
Iceberg 0.14.0

### Question

Hi,

We are performing row level deletion on an Iceberg table using Spark SQL. Rows need to be deleted across multiple partitions/files. 

`delete from data as d where exists ( select id from deletes where d.id = id )`

When deletion runs, our EMR cluster is running out of disk space if a high number of partitions/files are hit. On further inspection, Iceberg is performing a final repartition and sort just before replacing the data. My question is, why does Iceberg need to repartition and sort the files? Should the files not already be partitioned/sorted?

<img width="450" alt="image" src="https://user-images.githubusercontent.com/16835507/192633685-f15fcc5b-b38c-4735-8257-91c9af3b7419.png">

The deletes table seems to be joined onto the data table via broadcast join.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/16835507/192634589-4c193747-1e63-4867-911d-e422ab0c2b72.png">

**Comment by singhpk234** [comment]
I think this would be happening becuase `write.delete.distribution-mode` default is set to `hash` can try setting to `none`

**Comment by calvin-pietersen** [comment]
Can confirm this has resolved the issue. Thank you @singhpk234! - sorry will share plans next time.

![image](https://user-images.githubusercontent.com/16835507/193121736-07b69f0c-5b51-4566-8276-bf617d1a30b5.png)

Two more questions
- Why is `write.delete.distribution-mode=hash` by default? Seems like `write.delete.distribution-mode=none` is safer?
- Is the sort unnecessary considering the files should already be sorted?
