### ISSUE TITLE
Iceberg additional field metadata

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#5881]
### Query engine

Spark

### Question

Is there a capability to store additional meta data for fields. We are trying to have additive schema evolution and if column is deprecated we mark it as deprecated but it will continue to live in our store. 
I want to store this information that the field is deprecated somewhere in metadata. I have used description column to store the data but its stored with catalog. Is there a native way to have this information stored in metadata for the field?

**Comment by asheeshgarg** [comment]
Any guidance is appreciated. If we write directly to Parquetmeta data does it have any impact?

**Comment by irshadcc** [comment]
This might be what you are looking for, https://github.com/apache/iceberg/issues/5631.
