### ISSUE TITLE
Allow SnapshotManager to be created using an existing iceberg transaction

### ISSUE THREAD

**Issue by bartash** [apache/iceberg#5882]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

SnapshotManager creates its own iceberg transaction which is private. This prevents clients from adding anything to the transaction. An example use case where this is desirable is that some catalog users use additional HMS properties to include version numbers for cache invalidation.  It is desirable that these HMS properties are updated as part of the same iceberg transaction used by SnapshotManager. 
One fix would be to allow SnapshotManager to be created from Transaction in  a similar way that an ExpireSnapshots object can be created by Transaction.expireSnapshots(). An alternative fix would be to add a constructor to SnapshotManager that takes an iceberg transaction Object as a parameter. For convenience an overload of BaseTable.manageSnapshots() would also be added.

**Comment by gaborkaszab** [comment]
Let me take a look, @bartash

**Comment by gaborkaszab** [comment]
Merged by #6074
