### ISSUE TITLE
How to combine vertically split tables into one table in iceberg

### ISSUE THREAD

**Issue by moonService** [apache/iceberg#5883]
### Query engine

flink

### Question

I tried the following:
`CREATE TABLE source_part_1 ( `
`columns...` 
`PRIMARY KEY (pk) NOT ENFORCED`
 `) WITH ( `
`connectinfo... `
`);`

`CREATE TABLE source_part_2 (`
`columns...`
`PRIMARY KEY (pk) NOT ENFORCED`
`) WITH (`
`connectinfo...`
`);`

`CREATE TABLE iceberg_table (`
`part_1_columns...`
`part_2_columns...`
`PRIMARY KEY (pk) NOT ENFORCED`
`) WITH (`
`connectinfo...`
`);`

`insert into iceberg_table (part_1_columns...) select part_1_columns from source_part_1;`
`insert into iceberg_table (part_2_columns...) select part_2_columns from source_part_2;`

but iceberg can not just update part of fields ，only can update by line，How can I solve this problem？

**Comment by xuzhiwen1255** [comment]
I know your problem, for example, you can change SQL, such as JOIN, but this is not a good solution

**Comment by moonService** [comment]
@xuzhiwen1255 Yes, that means I need to manage the state of Flink, which will cause additional resource waste

**Comment by xuzhiwen1255** [comment]
At present, iceberg only achieves row-level update, so it has to get around this problem by other ways

**Comment by majin1102** [comment]
It could be done in offline way using MERGE INTO sql
