### ISSUE TITLE
ParallelIterable.close() will not clear queue

### ISSUE THREAD

**Issue by Heltman** [apache/iceberg#5886]
### Apache Iceberg version

0.14.1 (latest release)

### Query engine

Trino

### Please describe the bug 🐞

When Trino query Iceberg failure in file scan time, it call `fileScanTaskIterable.close()`. However, because the queue in   `ParallelIterable` is not cleared, it will occupy more Coordinator memory, and even cause OOM.

This is a question related to #4596 , this queue may be use too much memory in coordinator when query run. But when query failed, this queue still use much memory until trino expire this query(default: 15min and newest 100 query).

We need to confirm that the queue has been cleared when close() method is called.

**Comment by rdblue** [comment]
@Heltman, would you like to open a PR to clear the queue?

**Comment by Heltman** [comment]
@rdblue Yes, I had
