### ISSUE TITLE
Manifest partition stats include partition values from deleted files

### ISSUE THREAD

**Issue by vincentpoon** [apache/iceberg#5936]
### Apache Iceberg version

0.14.0

### Query engine

Trino

### Please describe the bug 🐞

With a simple table partitioned by one identity column, e.g. `partCol int`
Insert 2 rows, where partCol=1 and partCol=2
Now DELETE where partCol=2

The manifest list will show that the new manifest  partition stats for `partCol` are lower=1 upper=2
That is, it incorporates the stats for all files in the manifest, including those with `status: 2` (i.e. deleted file)

This has query perf implications in that a query `SELECT * FROM table WHERE partCol=2` must still read the manifest.

It is only after the manifest is further rewritten, when the `status: 2` file is evicted, that the column stats are accurately reflected.

**Comment by rdblue** [comment]
I don't think this is a bug. The behavior should be correct, right? Changing this behavior would be a performance improvement?

I'm not sure that we need to do this. I'd rather include a mode where we simply drop files that were deleted rather than keeping references to them. That would achieve the same goal, but would use less space for metadata.

**Comment by vincentpoon** [comment]
@rdblue  Hmm I guess it depends on what "correct" behavior means here, but if the partition stats reflect values that can never be returned in a query (because the files containing those values have been deleted), then that seems incorrect to me.

And changing the behavior would be a perf improvement, particularly when the manifests are quite large, as they are in our use case.  Filtering using the partition stats at the manifest list level means certain manifests don't have to be read.  With incorrect partition stats, the manifests are read even when they don't have any files that can answer the query.

Agree that a mode to simply drop files rather than keep references would solve the problem.  But then I would ask, what's the functionality of keeping around deleted files in the manifests with "Status: 2" (deleted) ?
