### ISSUE TITLE
[Hadoop] [Iceberg] How to change hadoop location from iceberg metadata

### ISSUE THREAD

**Issue by sontt710** [apache/iceberg#5947]
### Question

Hello,

I'm using Iceberg + Hadoop with Hive Metastore.

After create the table, the location of table will be "location" : "hdfs://xxx.:8020/warehouse/table_01".

I need to sync data of this table to AWS S3 or other Hadoop Cluster. In other environment, We have to change scheme of the location to S3:// other hadoop cluster name hdfs:/yyyy

If anyone have experience on it, please suggest for me.

Thanks.

**Comment by XBaith** [comment]
Migrate iceberg between different data center:
For version 1 table:  you can just load the data files into Spark dataset and then write into target table.
For version 2 table: config different cluster Spark catalog like this:
```
.config("spark.sql.catalog.hive_prod_src", classOf[SparkCatalog].getName)
.config("spark.sql.catalog.hive_prod_src.type", "hive")
.config("spark.sql.catalog.hive_prod_src.uri", $hiveMetaStores1)
.config("spark.sql.catalog.hive_prod_dst", classOf[SparkCatalog].getName)
.config("spark.sql.catalog.hive_prod_dst.type", "hive")
.config("spark.sql.catalog.hive_prod_dst.uri", $hiveMetaStores2)
```
read and write iceberg data by Spark SQL.

**Comment by ludlows** [comment]
how to change the json and avro files in metadata and data folders? 
the location hdfs://xxx1 has been changed to hdfs://xxx2 .
