### ISSUE TITLE
In batch mode, pos delete may trigger oom

### ISSUE THREAD

**Issue by linfey90** [apache/iceberg#5955]
### Feature Request / Improvement

We use a **upsert** table, then write data  with flink **batch** mode. Of course there is no ck, the insertedRowMap 
 in BaseTaskWriter.java will be bigger and bigger,and the resource will not be released, so oom might  happen.
method: BaseTaskWriter.write
`PathOffset previous = insertedRowMap.put(copiedKey, pathOffset);`
@openinx@rdblue
any advice can give me?
thanks!

### Query engine

Flink

**Comment by singhpk234** [comment]
An interesting PR on similar lines, addressing the issue by @openinx : 
- https://github.com/apache/iceberg/pull/2680

**Comment by linfey90** [comment]
> An interesting PR on similar lines (supporting spilling), addressing the issue by @openinx :
> 
> * [Core: Add RocksDBStructLikeMap #2680](https://github.com/apache/iceberg/pull/2680)

thanks, I'll take a look.
