### ISSUE TITLE
Not able to process hundred of RowData types

### ISSUE THREAD

**Issue by 0xNacho** [apache/iceberg#5958]
### Query engine

Flink

### Question

Hello!

I have a Flink application that reads arbitrary AVRO data, maps it to RowData and uses  several FlinkSink instances to write data into ICEBERG tables. By arbitrary data I mean that I have 100 types of AVRO message, all of them with a common property "tableName" but containing different columns. I would like to write each of these type of message into a separated Iceberg table.

For doing this I'm using side outputs: when I have my data mapped to RowData I use a ProcessFunction to write each message into a specific OutputTag.

Later on, with the datastream already processed, I loop into the different output tags, get records using getSideOutput and  create an specific IcebergSink for each of them. Something like:

```java

        final List<OutputTag<RowData>> tags = ... // list of all possible output tags

        final DataStream<RowData> rowdata = stream
                .map(new ToRowDataMap()) // Map Custom Avro Pojo into RowData
                .uid("map-row-data")
                .name("Map to RowData")
                .process(new ProcessRecordFunction(tags)) // process elements one by one sending them to a specific OutputTag
                .uid("id-process-record")
                .name("Process Input records");;

        CatalogLoader catalogLoader = ...
        String upsertField = ...
     
        outputTags
                .stream()
                .forEach(tag -> {
                    SingleOutputStreamOperator<RowData> outputStream = stream
                            .getSideOutput(tag);

                    TableIdentifier identifier = TableIdentifier.of("myDBName", tag.getId());

                    FlinkSink.Builder builder = FlinkSink
                            .forRowData(outputStream)
                            .table(catalog.loadTable(identifier))
                            .tableLoader(TableLoader.fromCatalog(catalogLoader, identifier))
                            .set("upsert-enabled", "true")
                            .uidPrefix("commiter-sink-" + tableName)
                            .equalityFieldColumns(Collections.singletonList(upsertField));
                    builder.append();
                });

```

It works very well when I'm dealing with a few tables. But when the number of tables scales up, Flink cannot adquire enough task resources to keep the application alive and generates a very complex execution plan (two diffrent task per sink, per table) that actually the Flink UI cannot show, by needing too many resources.

Is there any other more efficient way of doing this? or maybe any way of optimizing it?

Thanks in advance ! :)

**Comment by luoyuxia** [comment]
Actually, I don't think there's a more efficient way.  For you job, it does need so much resources since you need to write so many tables.
Is it possible to allocate more resource for Flink cluster or split the whole job into serveral small jobs?

**Comment by 0xNacho** [comment]
@luoyuxia thanks for you reply and sorry getting yo back so late!

yeah, it's possible to split the whole job into several small jobs, but number of tables is always increasing and I would like to have some generic implementantion.

Is there any way to implemenet a "generic" sink, containing a map of <String, IcebergFileCommiter>  where the string is the name of the application? so in the end I would only have a "sink" operator instead.
