### ISSUE TITLE
spark 3.2 + iceberg0.13.1 的 ANTLR 脚本问题

### ISSUE THREAD

**Issue by sun-help** [apache/iceberg#5964]
### Query engine

evn：
spark3.2
iceberg0.13.1
jar:
iceberg-runtime:iceberg-spark-runtime-3.2_1.12:0.13.2

### Question

 ANTLR Runtime version 4.8 used for parser compilation does not match the current runtime version 4.7.1ANTLR Runtime version 4.8 used for parser compilation does not match the current runti

**Comment by Fokko** [comment]
@sun-help Thanks for opening the issue. Could provide some steps to reproduce this? I would also suggest moving to 0.14.1 as that's the latest release. Thanks!

**Comment by sun-help** [comment]
> @sun-help Thanks for opening the issue. Could provide some steps to reproduce this? I would also suggest moving to 0.14.1 as that's the latest release. Thanks!

I have solved the problem
