### ISSUE TITLE
Iceberg with Glue Catalog updates glue table version on every commit, but there's a maximum of 100,000 versions

### ISSUE THREAD

**Issue by vshel** [apache/iceberg#5965]
### Query engine

Spark

### Question

Hello, I am trying out Iceberg with aws integration, every time a commit is done the glue table version is incremented, however, there's an aws hard limit of 100,000 versions per glue table.

-- I believe this line of code is responsible for version update: https://github.com/apache/iceberg/blob/3cddc9f28c93b9231060ecb6b90e2d524bd5d160/aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java#L150 --
Edit: I now think glue increments the table version upon every 'UpdateTable' request, even without corresponding version input from iceberg.

How could I use Iceberg with glue once I have 100,000 commits and the aws hard limit is reached? Is there anyway around it?

Thank you.

**Comment by singhpk234** [comment]
I think we can expire the previous table version when the current version is successfully committed, or you can override glue table level version count default to a big value as per : https://docs.aws.amazon.com/general/latest/gr/glue.html

to get rid of existing version of table via a separate clean-up job you can use this util as well : https://github.com/aws-samples/aws-glue-table-versions-cleanup-utility

cc @jackye1995

**Comment by vshel** [comment]
@singhpk234 thank you for responding so quickly. There's a "glue.skip-archive" provided in Iceberg, upon testing I see that it prevents a history of table versions from being available in glue, so no actual version is saved, but the version number is still incremented upon every commit. After further investigation I don't think anything from iceberg explicitly updates the version, it looks like glue increments it just after every 'UpdateTable' request.

Do I still have to use the DynamoLockManager even if I rely on the optimistic concurrency control provided by glue table versions? Unfortunately, it was not clear from the documentation whether I should be using only one or the other.

However, considering that this is streaming the tableVersion number will be growing very fast, I hope the ceiling aws provides for it will suffice.

**Comment by singhpk234** [comment]
> Do I still have to use the DynamoLockManager even if I rely on the optimistic concurrency control provided by glue table versions? Unfortunately, it was not clear from the documentation whether I should be using only one or the other.

DynamoLockManager should not be required in this case.

> However, considering that this is streaming the tableVersion number will be growing very fast, I hope the ceiling aws provides for it will suffice.

I think it should not be a problem, long has ~2 bil. Let's say u commit per second it would still require ~63 years to hit that.

**Comment by amogh-jahagirdar** [comment]
@singhpk234 If I'm not mistaken, I think @vshel point was on the Glue table version which gets incremented every UpdateTable regardless of glue.skip-archive. In this case, the 100000 limitation the glue table version limit would get exhausted much quicker (~1 day) assuming 1 commit/sec . 

But @vshel in the mean time as @singhpk234 mentioned you can try requesting higher limits / setup the Glue table version cleanup. https://github.com/aws-samples/aws-glue-table-versions-cleanup-utility

I'll look into if it makes sense to do an expiration of older versions in Iceberg itself.

**Comment by vshel** [comment]
Thank you for the answers!

**Comment by idrissa-mgs** [comment]
@vshel Did you finally find a long term solution rather than asking for an increase of the aws soft limit on tables versionning ?
Did the skipArchive flag help ?

**Comment by aakash-8** [comment]
Hey @vshel ! Were you able to find a permanent solution for the table versioning issue?
