### ISSUE TITLE
How to write to a bucket-partitioned table using PySpark?

### ISSUE THREAD

**Issue by RLashofRegas** [apache/iceberg#5977]
### Query engine

Spark

### Question

In the documentation for Spark writes, under the section for [Writing to partitioned tables](https://iceberg.apache.org/docs/latest/spark-writes/#writing-to-partitioned-tables), there are two Spark Jira issues linked that explain why (1) pre-write sort is required ([SPARK-23889](https://issues.apache.org/jira/browse/SPARK-23889)), and (2) manually registering the iceberg bucket function as a UDF is required for bucket-partitioned tables ([SPARK-27658](https://issues.apache.org/jira/browse/SPARK-27658)). Both of these issues are in the resolved state.

1. Is the Iceberg documentation still valid?
2. If not, what release versions of Spark/Iceberg support writing to bucket-partitioned tables without the steps above?
3. If so, how can I write to a bucket-partitioned table with PySpark given that (as far as I can tell) the bucket function is not available as a Python API so I cannot register it as a UDF?

**Comment by Neuw84** [comment]
Hi, 

Any hints of this? Stuck on same problem! 


Thanks!

**Comment by robinsinghstudios** [comment]
Hi,

My data is being appended to the partitioned table without registering any UDFs but the data seems to be written as one row per file which is creating a huge performance impact. Any suggestions or fixes will be really appreciated.

**Comment by robinsinghstudios** [comment]
@RussellSpitzer I'm sorting the data frame globally before inserting the data but still facing the same issue.

**Comment by RussellSpitzer** [comment]
If you aren’t sorting on the partition transform the rows will be in random order with regards to that transform. So if you don’t have the UDF registered and you are just sorting on the column itself I would expect you to generate at least 1 file per bucket per Spark taskOn Dec 2, 2022, at 1:36 AM, robinsinghstudios ***@***.***> wrote:﻿
@RussellSpitzer I'm sorting the data frame globally before inserting the data but still facing the same issue.

**Comment by robinsinghstudios** [comment]
@RussellSpitzer Any way to register the bucket UDF with Pyspark? Will the built-in bucket method not work for the same?

**Comment by fireking77** [comment]
Hi Guys!

I would also curious about this: 
 Any way to register the bucket UDF with Pyspark? Will the built-in bucket method not work for the same?

@robinsinghstudios have you figured out something? - are you able to write partitioned table with pyspark?

Thanks in advance,
 Darvi

**Comment by robinsinghstudios** [comment]
Hi @fireking77 , I was able to create bucketed tables by using SparkSQL query without any data. It just works for some reason.

**Comment by fireking77** [comment]
@robinsinghstudios that is OK, but were youable to write data into that table with pyspark?

**Comment by robinsinghstudios** [comment]
@fireking77 Merge statement works with SparkSQL. Had the same issue with append pyspark method.

**Comment by fireking77** [comment]
@robinsinghstudios Thanks! :D you were right :D
I hope there will be someone fix insert too... ;)
Thanks again!
 Darvi

**Comment by mjf-89** [comment]
Hi, I don't have a deep understandin of pyspark internals but I think that you can write to a partitioned iceberg table with the following approach:

```
# registering iceberg udf for partition transformation bucket(32,string_column)
spark.sparkContext._jvm.org.apache.iceberg.spark.IcebergSpark.registerBucketUDF(spark._jsparkSession,'iceberg_bucket_str_32',spark.sparkContext._jvm.org.apache.spark.sql.types.DataTypes.StringType,32)

# sorting using the registerd udf and write to the partitioned iceberg table
df.sortWithinPartitions(F.expr("iceberg_bucket_str_32(string_column)")) \
  .writeTo("iceberg_table") \
  .using("iceberg") \
  .partitionedBy(F.bucket(32,"string_column")) 
```
Another option as far as I understand is to avoid sorting and use the fanout writer instead:
```
df.writeTo("iceberg_table") \
  .using('iceberg') \
  .option("fanout-enabled", "true") \
  .partitionedBy(F.bucket(32,"esum_id")) \
  .createOrReplace()
```

**Comment by Gatsby-Lee** [comment]
thank you

**Comment by ignaski** [comment]
Apparently there is sql catalog functions `catalog.system.bucket()` and `catalog.system.truncate()` which allows to pre-order the data before writing to partitioned table

**Comment by pnain** [comment]
df.writeTo("iceberg_table") \
  .using('iceberg') \
  .option("fanout-enabled", "true") \
  .partitionedBy(F.bucket(32,"esum_id")) \
  .createOrReplace()

-- This works well but create small files. Hash/Range options are not working despite using the sorting
