### ISSUE TITLE
how to use rewrite datafile 

### ISSUE THREAD

**Issue by sun-help** [apache/iceberg#5996]
### Query engine

env:
  SparkActions
                                    .get(spark)
                                    .rewriteDataFiles(table)
                                    .options(pro)
                                    .execute();

### Question

Why must I use hivecatalog： 
22/10/17 17:13:25 WARN BaseRewriteDataFilesSparkAction: Failure during rewrite process for group BaseRewriteDataFilesFileGroupInfo{globalIndex=1, partitionIndex=1, partition=PartitionData{}}
java.lang.IllegalArgumentException: Cannot initialize Catalog implementation org.apache.iceberg.hive.HiveCatalog: Cannot find constructor for interface org.apache.iceberg.catalog.Catalog
	Missing org.apache.iceberg.hive.HiveCatalog [java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/UnknownDBException]

**Comment by vshel** [comment]
@sun-help trough trial and error I figured it out:
if you want to use a different catalog, for example Glue:
```
spark.sql.catalog.glue_cat=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.glue_cat.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
spark.sql.catalog.glue_cat.warehouse=s3://bucket
```
Additionally, when creating your table, which you are supplying to .rewriteDataFiles(table), use the same catalog name - glue_cat.

`CatalogUtil.buildIcebergCatalog("glue_cat", catalogConfiguration, hadoopConfig).loadTable(...`

This is the relevant part in documentation: https://iceberg.apache.org/docs/0.13.1/spark-configuration/#loading-a-custom-catalog

**Comment by sun-help** [comment]
> @sun-help trough trial and error I figured it out: if you want to use a different catalog, for example Glue:
> 
> ```
> spark.sql.catalog.glue_cat=org.apache.iceberg.spark.SparkCatalog
> spark.sql.catalog.glue_cat.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
> spark.sql.catalog.glue_cat.warehouse=s3://bucket
> ```
> 
> Additionally, when creating your table, which you are supplying to .rewriteDataFiles(table), use the same catalog name - glue_cat.
> 
> `CatalogUtil.buildIcebergCatalog("glue_cat", catalogConfiguration, hadoopConfig).loadTable(...`
> 
> This is the relevant part in documentation: https://iceberg.apache.org/docs/0.13.1/spark-configuration/#loading-a-custom-catalog

At present, I want to use Spark to clear small data files.

**Comment by sun-help** [comment]
I don't know if the data file can be rebuilt in parallel with the write operation
