### ISSUE TITLE
rewrite datafile OOM bug

### ISSUE THREAD

**Issue by goomhow** [apache/iceberg#6028]
### Query engine

I use FLINK compact small files             
Actions.forTable(table)
                    .rewriteDataFiles()
                    .maxParallelism(maxParallelism)
                    .caseSensitive(false)
                    .filter(Expressions.equal("d_1", d_1))
                    .targetSizeInBytes(512 * 1024 * 1024)
                    .execute();

### Question

even if i set 16G memory to compact 800M iceberg table ,omm bug still happen

**Comment by luoyuxia** [comment]
@goomhow Could you please post the detail stacktrace so that we can track what bring the oom.
