### ISSUE TITLE
Add delete file information to partitions table

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#6042]
### Feature Request / Improvement

@ajantha-bhat brought up that Partitions table fields 'file_count' and 'record_count' are not reflecting delete files, and was interested to fix it.

One possibility is to add 'pos_delete_x' and 'eq_delete_x' combinations to these two fields, so:

- file_count
- record_count
- pos_delete_file_count
- pos_delete_record_count
- eq_delete_file_count
- eq_delete_record_count

Was trying to come up with smallest number of columns, this was the least i could think of and still convey the information.

@rdblue @aokolnychyi for any thoughts

### Query engine

Spark

**Comment by ajantha-bhat** [comment]
@szehon-ho : 
Say for `partition-a` I have `record_count`=6 and `file_count`=2. [3 records in each file]
Now, I do position delete which marks 3 records in file1 as deleted for `partition-a`. 

So, are you suggesting instead of decrementing `record_count` to 3 and incrementing `file_count` to 3,
increment `pos_delete_record_count`=3, `pos_delete_file_count`=1 ?

In this case, the user has to manually calculate that now instead of 6 there are 3 total records and instead of 2 files, now need to scan 3 files.

Sounds good to me. It avoids confusion. 

What about the global deletes?  (row level delete for unpartitioned data). Does it come under the partition value `null`?

**Comment by szehon-ho** [comment]
Yea I think , we cant do any arithmetic otherwise it becomes a matter of applying the delete file, which shouldn't be done in metadata table.  This should be coming just from file metadata, in my opinion.

> What about the global deletes? (row level delete for unpartitioned data). Does it come under the partition value null?

Yea I would say for partitions table, we may choose not to show it or show it like that (up for debate).  Anyway it should be there in the delete_files table.

**Comment by ajantha-bhat** [comment]
> Yea I think , we cant do any resolution of deletes, otherwise it becomes a matter of applying the delete file, which shouldn't be done in metadata table. This should be coming just from file metadata, in my opinion.

for `eq_delete_record_count` we have to apply the filters and compute the actual count of records that are deleted?

**Comment by szehon-ho** [comment]
I was thinking , just number of records in that file, without applying.  Obviously, not sure if eq_delete_record_count and pos_delete_record_count are very useful, but if we want to do this.

**Comment by ajantha-bhat** [comment]
> I was thinking , just number of records in that file, without applying. Not sure if eq_delete_record_count and pos_delete_record_count are very useful, but if we want to do this.

Say, for a given partition value I have 1000 records and deleted 500 records, to calculate the effective `record_count`, I think `pos_delete_record_count` and `eq_delete_record_count` will be useful If it represents actual records that will be masked from delete.

**Comment by sgcowell** [comment]
From the perspective of estimating scan costs with partition pruning - pos_delete_record_count is definitely useful for calculating the effective record count, eq_delete_record_count/eq_delete_file_count is less useful, but can at least be a signal of there being increased costs for handling those eq deletes, even if the cost estimate becomes much less precise.  Eq delete stats at least would be a good signal on increased mem usage requirements.  Computing actual record counts impacted by eq deletes up front seems cost-prohibitive and starts to erode their value proposition.

**Comment by gaborkaszab** [comment]
Well, my plan was to keep the existing columns in the partitions metadata table intact and add some delete file related ones on top. Currently, I only dealt with position deletes and my plan was to add 2 counters: # of pos delete files and # of rows within these position delete files.
I haven't given a thought to equality deletes. The # of files might be useful for some extent but I don't know if the row count would give us any further insight for query planning or table maintenance. To have parity between the 2 types of delete files we might want to add the equality delete row count as well.
I for sure didn't plan to apply the delete files to have counters that reflect the remaining rows/files.

**Comment by wypoon** [comment]
I'm trying to understand the proposed behavior.
To go back to @ajantha-bhat's example: Suppose you have a partition `{A}` with `record_count`=6 and `file_count`=2 (3 records in each file). Suppose you now delete 3 records in one file. I understand that `pos_delete_file_count` will be 1 and `pos_delete_record_count` will be 3. But what about `record_count` and `file_count`? Will `file_count` be 3 (is it supposed to be the total number of data files, including delete files)? And `record_count`? When is it possible to correctly compute the `record_count` using metadata alone (without applying delete files)?

Another example: Suppose you have two partitions `{A}` and `{B}`. Let's say `record_count`=1000 and `file_count`=1 for partition `{B}`. Suppose you rename `B` to `C` (using an `UPDATE <table> SET <partition column> = 'C' where <partition column = 'B'` where we use merge-on-read, resulting in 1 delete file and 1 new pure data file). If you do a `SELECT * FROM <table>.partitions` currently, you will get an entry for each of `{A}`, `{B}` and `{C}`. What should the behavior be (should there be an entry for `{B}` and if so, what should be shown for it? and for `{C}`?)?

**Comment by ajantha-bhat** [comment]
>  But what about record_count and file_count? Will file_count be 3 (is it supposed to be the total number of data files, including delete files)? And record_count? When is it possible to correctly compute the record_count using metadata alone (without applying delete files)?

record_count and file_count is just be data files record_count and file_count (not the delete files). So, it won't be modified for the delete operation.  (may be we have to rename the columns) 

> What should the behavior be (should there be an entry for {B} and if so, what should be shown for it? and for {C}?)?

The update is a delete + append operation. So, `<table>.partitions` will show entries for both {B} and {C} I think.

cc: @szehon-ho

**Comment by gaborkaszab** [comment]
> > What should the behavior be (should there be an entry for {B} and if so, what should be shown for it? and for {C}?)?
> 
> The update is a delete + append operation. So, `<table>.partitions` will show entries for both {B} and {C} I think.

Hi @ajantha-bhat,
In the example described by @wypoon the output of querying the partitions table would be a bit misleading in my opinion as {B} would still be there even though we renamed that partition to {C} before. On the other hand I believe if we rewrite the table to compact the data files with the delete files then {B} would be gone from the output.

I wonder if there is any way to get around this problem. With position deletes would it be possible to compare the record_count of a partition with the new pos_delete_record_count and don't show the partition if they match? Is there a use case where these 2 numbers won't be equal even though the whole partition has been deleted using position deletes? This won't solve the issue with equality deletes, though.

**Comment by gaborkaszab** [comment]
I think the above is a slightly different topic so I created a new issue where we can discuss: https://github.com/apache/iceberg/issues/6257

**Comment by ajantha-bhat** [comment]
> I think the above is a slightly different topic so I created a new issue where we can discuss: https://github.com/apache/iceberg/issues/6257

Not an off-topic at all. I was about to point out that V2 update has a similar problem with the existing code itself. 
Unless we apply the delete file content and compute the actual live partitions, we can't fix this problem. 
But computing the actual live partitions is expensive (@szehon-ho also mentioned the same above)

**Comment by gaborkaszab** [comment]
Well, in my opinion if we talk about whether we should apply delete files when we calculate the existing 'file_count' and 'record_count' metrics then it might not worth the extra performance impact as we can always say that these 2 metrics are for the contents of the data files (without applying the delete files).

Showing a partition in the output that has already been renamed is a different story I think. I'm not saying that we should definitely implement the code to apply the delete files to omit these partitions, I just think that we might want to re-consider if this is worth the work and the extra perf impact. Hence, I opened #6257 because this topic feels a bit different as the current ticket is for introducing new fields in the metadata table while the one I opened is for discussing whether we want to introduce applying delete files to get rid of partitions from the output that got renamed meanwhile.

**Comment by ajantha-bhat** [comment]
May be we need to rename `file_count` to `data_file_count` and `record_count` to `data_record_count`

Until we do the rewrite data files, the other metrics (pos_delete_file_count, pos_delete_record_count, eq_delete_file_count, eq_delete_record_count) are just to give a rough idea that the data_file_count and data_record_count are not the final stats. 

@szehon-ho, @wypoon 
With the above assumption, I am starting the implementation of the same.
