### ISSUE TITLE
[Python] Add examples

### ISSUE THREAD

**Issue by thomafred** [apache/iceberg#6061]
### Feature Request / Improvement

The documentation, nor the repo itself, has any examples on how to use pyiceberg.

Having examples would make it a lot easier for noobs such as myself to get started :)

**Comment by nickvazz** [comment]
Would love to see a minimal getting started / setup

**Comment by nickvazz** [comment]
Looks like  https://github.com/tabular-io/docker-spark-iceberg is a good place to start

**Comment by Fokko** [comment]
@nickvazz I'm actually preparing a dedicated notebook for that repository. This is currently blocked because of some bugs that we've discovered in 0.2.0: https://lists.apache.org/thread/2c27f5pombsdq2vtdczbsbypwfxhbnd0

**Comment by nickvazz** [comment]
Awesome! Can't wait 😁
