### ISSUE TITLE
exec insert into (hive on spark),no erro log,but table no data

### ISSUE THREAD

**Issue by eyeryone** [apache/iceberg#6067]
### Apache Iceberg version

0.14.0

### Query engine

Spark

### Please describe the bug 🐞

exec insert into (hive on spark),no erro log,but table no data. if use  `set hive.execution.engine=mr;` can insert into table!

this is exec log!

0: jdbc:hive2://cdh01:10000> insert into student1 values(10011,'bob','2022-10-27','China');
INFO  : Compiling command(queryId=hive_20221027172719_240518b0-2aac-4961-93ab-02b8196dda5b): insert into student1 values(10011,'bob','2022-10-27','China')
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:_col0, type:bigint, comment:null), FieldSchema(name:_col1, type:string, comment:null), FieldSchema(name:_col2, type:string, comment:null), FieldSchema(name:_col3, type:string, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20221027172719_240518b0-2aac-4961-93ab-02b8196dda5b); Time taken: 0.285 seconds
INFO  : Executing command(queryId=hive_20221027172719_240518b0-2aac-4961-93ab-02b8196dda5b): insert into student1 values(10011,'bob','2022-10-27','China')
INFO  : Query ID = hive_20221027172719_240518b0-2aac-4961-93ab-02b8196dda5b
INFO  : Total jobs = 1
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Launching Job 1 out of 1
INFO  : Starting task [Stage-1:MAPRED] in serial mode
INFO  : Running with YARN Application = application_1666676510935_0042
INFO  : Kill Command = /opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hadoop/bin/yarn application -kill application_1666676510935_0042
INFO  : Hive on Spark Session Web UI URL: http://cdh02:46883
INFO  : 
Query Hive on Spark job[0] stages: [0]
INFO  : Spark job[0] status = RUNNING
INFO  : Job Progress Format
CurrentTime StageId_StageAttemptId: SucceededTasksCount(+RunningTasksCount-FailedTasksCount)/TotalTasksCount
INFO  : 2022-10-27 17:27:31,294 Stage-0_0: 0/1
INFO  : 2022-10-27 17:27:34,300 Stage-0_0: 0/1
INFO  : 2022-10-27 17:27:35,302 Stage-0_0: 1/1 Finished
INFO  : Spark job[0] finished successfully in 6.03 second(s)
INFO  : Completed executing command(queryId=hive_20221027172719_240518b0-2aac-4961-93ab-02b8196dda5b); Time taken: 15.259 seconds
INFO  : OK
1 row affected (15.562 seconds)
0: jdbc:hive2://cdh01:10000> select * from student1;
INFO  : Compiling command(queryId=hive_20221027172751_0aa29e18-67d7-477c-b8cf-1cb0f5be64f1): select * from student1
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:student1.id, type:bigint, comment:null), FieldSchema(name:student1.name, type:string, comment:null), FieldSchema(name:student1.birthday, type:string, comment:null), FieldSchema(name:student1.country, type:string, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20221027172751_0aa29e18-67d7-477c-b8cf-1cb0f5be64f1); Time taken: 0.064 seconds
INFO  : Executing command(queryId=hive_20221027172751_0aa29e18-67d7-477c-b8cf-1cb0f5be64f1): select * from student1
INFO  : Completed executing command(queryId=hive_20221027172751_0aa29e18-67d7-477c-b8cf-1cb0f5be64f1); Time taken: 0.0 seconds
INFO  : OK
+--------------+----------------+--------------------+-------------------+
| student1.id  | student1.name  | student1.birthday  | student1.country  |
+--------------+----------------+--------------------+-------------------+
| 10010        | 123            | 2022-10-27         | China             |
+--------------+----------------+--------------------+-------------------+
1 row selected (0.107 seconds)
0: jdbc:hive2://cdh01:10000> show create table student1;
INFO  : Compiling command(queryId=hive_20221027172907_0d860aec-7424-4285-8060-d6404b68684c): show create table student1
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:createtab_stmt, type:string, comment:from deserializer)], properties:null)
INFO  : Completed compiling command(queryId=hive_20221027172907_0d860aec-7424-4285-8060-d6404b68684c); Time taken: 0.02 seconds
INFO  : Executing command(queryId=hive_20221027172907_0d860aec-7424-4285-8060-d6404b68684c): show create table student1
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Completed executing command(queryId=hive_20221027172907_0d860aec-7424-4285-8060-d6404b68684c); Time taken: 0.019 seconds
INFO  : OK
+----------------------------------------------------+
|                   createtab_stmt                   |
+----------------------------------------------------+
| CREATE TABLE `student1`(                           |
|   `id` bigint COMMENT 'from deserializer',         |
|   `name` string COMMENT 'from deserializer',       |
|   `birthday` string COMMENT 'from deserializer',   |
|   `country` string COMMENT 'from deserializer')    |
| ROW FORMAT SERDE                                   |
|   'org.apache.iceberg.mr.hive.HiveIcebergSerDe'    |
| STORED BY                                          |
|   'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'  |
|                                                    |
| LOCATION                                           |
|   'hdfs://highnameserver/user/hive/warehouse/iceberg/student1' |
| TBLPROPERTIES (                                    |
|   'current-schema'='{"type":"struct","schema-id":0,"fields":[{"id":1,"name":"id","required":false,"type":"long"},{"id":2,"name":"name","required":false,"type":"string"},{"id":3,"name":"birthday","required":false,"type":"string"},{"id":4,"name":"country","required":false,"type":"string"}]}',  |
|   'current-snapshot-id'='5813138393199784685',     |
|   'current-snapshot-summary'='{"added-data-files":"1","added-records":"1","added-files-size":"1233","changed-partition-count":"1","total-records":"1","total-files-size":"1233","total-data-files":"1","total-delete-files":"0","total-position-deletes":"0","total-equality-deletes":"0"}',  |
|   'current-snapshot-timestamp-ms'='1666861452846',  |
|   'default-partition-spec'='{"spec-id":0,"fields":[{"name":"birthday","transform":"identity","source-id":3,"field-id":1000},{"name":"country","transform":"identity","source-id":4,"field-id":1001}]}',  |
|   'engine.hive.enabled'='true',                    |
|   'external.table.purge'='TRUE',                   |
|   'iceberg.catalog'='hive_catalog',                |
|   'last_modified_by'='hdfs',                       |
|   'last_modified_time'='1666862840',               |
|   'metadata_location'='hdfs://highnameserver/user/hive/warehouse/iceberg/student1/metadata/00001-b298bba7-f3d8-49cd-80cb-9d68f39bb47d.metadata.json',  |
|   'previous_metadata_location'='hdfs://highnameserver/user/hive/warehouse/iceberg/student1/metadata/00000-58c1a7ed-1039-4e4c-9fc0-5af4db0a5e35.metadata.json',  |
|   'snapshot-count'='1',                            |
|   'table_type'='ICEBERG',                          |
|   'transient_lastDdlTime'='1666862840',            |
|   'uuid'='7119e9c1-01d3-450c-9ab4-7e38ae18dad6')   |
+----------------------------------------------------+
29 rows selected (0.072 seconds)

**Comment by eyeryone** [comment]
env:cdh6.3.2  hive 2.1.1 spark 2.4

**Comment by eyeryone** [comment]
It is normal to insert other types of tables（hive on spark）

**Comment by pvary** [comment]
Hive on Spark is not supported/tested
Also Hive 2.1.1 is also not supported/tested
Could you use newer CDH/CDP version?

**Comment by pvary** [comment]
I did not see progress on HoS side, and I think the Hive community decided to remove Spark as an execution engine, so I think there is not too much hope there.

OTOH I know that there were plans to support Hive+Iceberg in newer Cloudera distributions, but I am not sure what is the status there.

**Comment by eyeryone** [comment]
> I did not see progress on HoS side, and I think the Hive community decided to remove Spark as an execution engine, so I think there is not too much hope there.
> 
> OTOH I know that there were plans to support Hive+Iceberg in newer Cloudera distributions, but I am not sure what is the status there.
ok，thinks

**Comment by 1043038630** [comment]
> I did not see progress on HoS side, and I think the Hive community decided to remove Spark as an execution engine, so I think there is not too much hope there.
> 
> OTOH I know that there were plans to support Hive+Iceberg in newer Cloudera distributions, but I am not sure what is the status there.

Thank you very much for your answer.

Planned support in the future hive on spark(hive 1.2.1，spark 2.4) write iceberg table ？
