### ISSUE TITLE
The metadata table returns from Spark query should show human readable string for lower/upper bounds

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#6085]
### Feature Request / Improvement

When querying `files` table via Spark SQL returns rows that match the `DataFile` schema, which defines `Map<Integer, ByteBuffer>` type for lower/upper bounds. And thus the return lower/upper bounds strings are addresses of `ByteBuffer`. It is better to decode the byte buffer to human-readable strings like what the Presto side did. 

### Query engine

Spark

**Comment by szehon-ho** [comment]
Yea I have a pr for awhile for that, waiting review:  https://github.com/apache/iceberg/pull/5376   if you want to take a look.

**Comment by chenjunjiedada** [comment]
@szehon-ho Nice, let me take a look.

**Comment by szehon-ho** [comment]
Fixed by #5376
