### ISSUE TITLE
Flink: Add support for Flink 1.16

### ISSUE THREAD

**Issue by deadwind4** [apache/iceberg#6099]
### Feature Request / Improvement

The Flink 1.16 has been released.
https://nightlies.apache.org/flink/flink-docs-release-1.16/

### Query engine

Flink

**Comment by deadwind4** [comment]
I would like to take this.

**Comment by ajantha-bhat** [comment]
Already there is an ongoing work
https://github.com/apache/iceberg/pull/6092

**Comment by nastra** [comment]
given that #6092 is merged, we can close this one out
