### ISSUE TITLE
Build iceberg error

### ISSUE THREAD

**Issue by GanfengTan** [apache/iceberg#6100]
### Apache Iceberg version

0.12.0 (latest release)

### Please describe the bug 🐞

step1. Import iceberg project to Idea.
step2. Exec './gradlew build'

* What went wrong:
Plugin [id: 'nebula.dependency-recommender', version: '9.0.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'nebula.dependency-recommender:nebula.dependency-recommender.gradle.plugin:9.0.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by nastra** [comment]
@GanfengTan 0.12.0 is fairly outdated. Are you building the project after checking it out from GitHub or did you download the source tarball and building it from there?
