### ISSUE TITLE
Rewrite iceberg small files with flink succeeds but no snapshot is generated (V2 - upsert model)

### ISSUE THREAD

**Issue by SHuixo** [apache/iceberg#6104]
### Apache Iceberg version

0.14.1

### Query engine

Flink

### Please describe the bug 🐞

> flink: 1.13.5
> iceberg:  1.13.2 / 1.14.1

When using Rewrite files action API **rewriteDataFiles()**, the new compressed file is generated without a corresponding manifest file, I tried iceberg versions 1.13.2 and 1.14.1 which has a similar problem under the iceberg-catalog of Hive and Hadoop. 

> The Iceberg Maven dependent, table structure and code to compress the file using the Java API is as follows：
```
      <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-flink-runtime-1.13</artifactId>
<!--            <version>0.13.2</version>-->
            <version>0.14.1</version>
        </dependency>
```
```
name: iceberg_hive_catalog
type: iceberg
catalog-type: hive
uri: thrift://xxxxx:9083
clients: 5
property-version: 1
warehouse: hdfs://nameservice1/user/hive/warehouse/

create table iceberg_hive_catalog.dhome_db.ods_d_base_inf_229_iceberg (
`did` string,
`name` string,
`address` string,
`did_seq`  string,
PRIMARY KEY (did_seq) NOT ENFORCED
) with (
 'format-version'='2',
 'write.upsert.enabled'='true',
 'write.metadata.delete-after-commit.enabled'='true',
 'write.metadata.previous-versions-max'='5',
 'flink.rewrite.enable' = 'true',
 'flink.rewrite.parallelism' = '5',
 'flink.rewrite.target-file-size-bytes' = '536870912',
 'flink.rewrite.max-files-count' = '5'
);
```
```
final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
TableIdentifier identifier = TableIdentifier.of("dhome_db", "ods_d_base_inf_229_iceberg");
TableLoader tableLoader = TableLoader.fromCatalog(hive_iceberg, identifier);
tableLoader.open();
Table table_iceberg = tableLoader.loadTable();

Actions.forTable(env, table_iceberg)
		.rewriteDataFiles()
		.maxParallelism(5)
		.targetSizeInBytes(128*1024*1024)
		.execute();
```

> The results:
<img width="1068" alt="result" src="https://user-images.githubusercontent.com/20868410/199470742-abe8e600-0bd5-4c6d-838b-6a96745cd55e.PNG">

If there is anything wrong with the question, please correct it, thank you.

**Comment by luoyuxia** [comment]
Seems the files has been compressed, but it fails to to generate snapshot.  Maybe some exception happen when commit.
Is there any error or warning in the log?

**Comment by SHuixo** [comment]
Think you @luoyuxia for your replay.

Later, I tried again a few times and found that when the cumulative storage of iceberg data small files was relatively small, the flink 1.13.5 compressed file ran normally and could generate snapshot files.

However, when the file volume accumulates a lot, it takes a long time to rewrite the data each time, and it is easy to cause **OOM** exceptions, here are my attempts at **Flink 1.13.5 / 1.15.2, iceberg 1.14.1**  and the log logs generated by the task.

> The following figure shows that the compression task has been in the Map stage：
<img width="872" alt="dag-13-1" src="https://user-images.githubusercontent.com/20868410/201018299-e64b3a02-3ff2-4d49-b1cc-e7bdf703f3aa.PNG">

> OOM exception information that occurs when the compression task occurs：

**flink 1.13.5:**
[error-flink-1.13.5.log](https://github.com/apache/iceberg/files/9978008/error-flink-1.13.5.log)


**flink 1.15.2:**
[error-flink-1.15.2.log](https://github.com/apache/iceberg/files/9978009/error-flink-1.15.2.log)


Here I want to ask, if the data is continuously written to iceberg, the problem of data compression OOM is inevitable, and the compression time will become longer and longer.

 I see that there are API methods   **appendsBetween() / appendsAfter()** related to incremental compression in the source code, does this mean that incremental compression can be used to replace the repeated compression process of full data in the future?

thanks.

**Comment by luoyuxia** [comment]
> the repeated compression process of full data
The compaction won't be repeated. I mean during one compaction, some files are compacted to one file. In next compaction, it won't compact these files again. I don't think it's a repeated compression process. From my side, it's still a incremental process.
 
Back to your problem, actuall, there's a pr #2680 to use disk to avoid OOM. And I think it'll also fix your problem.
I think you can try to
1:  increase the memorag of TM. 
2:  do compaction more frequently , so that every compaction won't compact much data, which may well  relieve the OOM.

**Comment by luoyuxia** [comment]
> The new features of rocksdb mentioned in the PR https://github.com/apache/iceberg/pull/2680 have not found the relevant configuration items in the latest 1.0.0 version? Do you have to wait for a subsequent version to be added?
Yes, we have to wait it to be merged.

> In compressing data it is indeed possible to solve the OOM problem by increasing the memory of TaskManger and increasing the compression frequency of data.
I agree with you, so I think use rocksdb as backend is a better solution

>  and the commit exception problem will be encountered when the data compression task is performed.
Had a look about your exception log. The reason is the cdc contains a delete row, but the compaction for such case that contains delete files hasn't been supported.

**Comment by SHuixo** [comment]
> Yes, we have to wait it to be merged.

Good, looking forward to the merger of this rockdb new feature.

> Had a look about your exception log. The reason is the cdc contains a delete row, but the compaction for such case that contains delete files hasn't been supported.

This means that in the CDC data that is streaming to Iceberg, don't have a viable data compression scheme for data streams that contain delete operations at this stage?

In order to verify whether the **commit exception** in the flow scenario has a similar problem in the batch scenario, we made the following attempts: 

```
1. Enable flink CDC streaming writing iceberg, and the checkpoint is 5 minutes; 
2. When the writer is running, start the compression program until a **commit exception** occurs; 
3. When the above **commit exception** occurs, stop the CDC data writing program and compression program; 
4. Turn on the data compression program again until the program is up and running. 
```

> The following figure shows the start and end times when flink CDC writes data to iceberg：

<img width="941" alt="stream-write-iceberg" src="https://user-images.githubusercontent.com/20868410/203070483-d39c3107-ca61-4d31-bb30-7d63cf821697.PNG">

> Some of the logs are as follows:

[compact-data-when-stream-write.log](https://github.com/apache/iceberg/files/10056982/compact-data-when-stream-write.log)
[compact-data-when-write-finish.log](https://github.com/apache/iceberg/files/10056985/compact-data-when-write-finish.log)


Here's a question,is it possible to pause the writer for data compression once, and when the data compression is completed, resume the data writing from the checkpoint again, and handle the above commit exception by cyclically suspending, compressing, and writing again?

**Comment by luoyuxia** [comment]
> This means that in the CDC data that is streaming to Iceberg, don't have a viable data compression scheme for data streams that contain delete operations at this stage?

Yes, I'm afraid so.

> Here's a question,is it possible to pause the writer for data compression once, and when the data compression is completed, resume the data writing from the checkpoint again, and handle the above commit exception by cyclically suspending, compressing, and writing again?

I think it's possible. From the code, IIUC, the exception happens when you start a compression, but it find delete files before finish compression. And once it won't produce any deletes files between start and finish a compression, there shouldn't throw exception.
But I'm not sure, you can have a try and to see whether it works.
