### ISSUE TITLE
Add StartsWith and NotStartsWith operator to PyIceberg

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#6112]
### Feature Request / Improvement

These are missing in Python, would be great to add them:

https://github.com/apache/iceberg/blob/8271791061e72dbf554028e477746e89fca9ec02/api/src/main/java/org/apache/iceberg/expressions/Expression.java#L45-L46

**Comment by srilman** [comment]
@MichaelDeSteven are you still working on this?

**Comment by MichaelDeSteven** [comment]
> @MichaelDeSteven are you still working on this? I would like to pick this up if not.

I'm busying. you can pick it up，good luck.
