### ISSUE TITLE
RemoveDanglingDeleteFiles

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#6126]
### Feature Request / Improvement

With DeleteFiles introduced to Iceberg Spec V2, we need a more comprehensive mechanism to remove them from the current snapshot after they become invalid (ie, stop applying to any data file).  In some situations, invalid Delete Files remain live in current snapshot, taking up storage and potentially affecting performance.

Related issues:

- https://github.com/apache/iceberg/issues/5058
- https://github.com/apache/iceberg/issues/4127

Description and proposal is here:  https://docs.google.com/document/d/11d-cIUR_89kRsMmWnEoxXGZCvp7L4TUmPJqUC60zB5M/edit?usp=sharing

Pre-requisite for Phase 2 will depend on : https://github.com/apache/iceberg/pull/4812  which is not yet merged.  That is pending refactoring of ScanTask   like in https://github.com/apache/iceberg/pull/5922  that needs to be propagated to Spark layer.

**Comment by lintingbin2009** [comment]
@szehon-ho I have the same problem, is there any progress update?

**Comment by szehon-ho** [comment]
Sorry late reply, this is already fixed by new procedure RewritePositionDeleteFiles.  It will clean dangling deletes.

**Comment by lintingbin2009** [comment]
@szehon-ho Thanks! Already used it.

**Comment by chenwyi2** [comment]
so how about equality delete file?

**Comment by kavimaluskam** [comment]
> Sorry late reply, this is already fixed by new procedure RewritePositionDeleteFiles. It will clean dangling deletes.
When using rewitePositionDeletes, should keeping this as true?

**Comment by szehon-ho** [comment]
> When using rewitePositionDeletes, should keeping this as true?

Yes (if I understand correctly the question)
