### ISSUE TITLE
can't upsert v2 table by add hint /*+ OPTIONS('upsert-enabled'='true') */

### ISSUE THREAD

**Issue by get1boat** [apache/iceberg#6180]
### Apache Iceberg version

1.0.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

table DDL:
`
CREATE TABLE hive_catalog.ods_ice.tmp_lkj_kafka2iceberg (
   id varchar NOT NULL,
   create_time timestamp(6),
   user_id bigint
)
WITH (
   format = 'PARQUET',
   format_version = 2,
   location = 'hdfs://eva:8020/user/hive/warehouse/ods_ice.db/tmp_lkj_kafka2iceberg'
)
;
`
with the hint,insert 2 rows which having the same key by trino:
`
insert into hive_catalog.ods_ice.tmp_lkj_kafka2iceberg /*+ OPTIONS('upsert-enabled'='true') */
select '1'as id ,localtimestamp  as create_time,111 as user_id
;
insert into hive_catalog.ods_ice.tmp_lkj_kafka2iceberg /*+ OPTIONS('upsert-enabled'='true') */
select '1'as id ,localtimestamp  as create_time,222 as user_id
;
`
Then,we select the table and we found it has two rows with the same key.Upsert hint did not work:
![image](https://user-images.githubusercontent.com/68981063/201518039-a32f37b4-9098-4fd3-8671-e60314705aef.png)

**Comment by krvikash** [comment]
Hi @get1boat,
 
You are missing the primary key while creating the table.

> Enabling UPSERT mode using upsert-enabled in the [write options](#Write options) provides more flexibility than a table level config. Note that you still need to use v2 table format and specify the primary key when creating the table.

https://iceberg.apache.org/docs/latest/flink/#upsert

Please try adding a `PRIMARY KEY` while creating the table like below.

`CREATE TABLE hive_catalog.ods_ice.tmp_lkj_kafka2iceberg( id varchar NOT NULL, create_time timestamp(6), user_id bigint, PRIMARY KEY(id) NOT ENFORCED ) WITH ( format = 'PARQUET', format_version = 2, location = 'hdfs://eva:8020/user/hive/warehouse/ods_ice.db/tmp_lkj_kafka2iceberg' ) ;`

**Comment by get1boat** [comment]
> 
I created the table in flinksql definitely with the primary key.This DDL was gained by `show create table ` in the Trino.In flink client,this table has a primary key.
The original DDL is blow,and my question remain:
`
create table if not exists hive_catalog.ods_ice.tmp_lkj_kafka2iceberg
(
    `id` STRING 
    ,`create_time` timestamp 
    ,`user_id` BIGINT 
    ,primary key(`id`) not enforced
) comment 'kafka2iceberg test table'
with (
        'format-version'='2'
        )
;
`
