### ISSUE TITLE
Spark DDL: upgrade format-version from v1 to v2 is not working

### ISSUE THREAD

**Issue by 0xffmeta** [apache/iceberg#6194]
### Apache Iceberg version

0.14.1

### Query engine

Spark

### Please describe the bug 🐞

I'm running below spark sql to migrate an iceberg table from v1 to v2 format:
```
alter table tmp.table SET TBLPROPERTIES('format-version'='2')
```

The spark sql can finish with no error, but it still shows `'option.format-version'='1'` while querying form hive `show create table`. 

Do I need to use this table property for the foramt upgrade? `option.format-version`

**Comment by Fokko** [comment]
It works fine with Spark:

![image](https://user-images.githubusercontent.com/1134248/202388833-2935c614-634a-4389-9265-4232022f1f46.png)

In Hive, could it be that you need to refresh the table? Using `REFRESH tmp.table`

**Comment by 0xffmeta** [comment]
Seems I need to use `alter table tmp.table SET TBLPROPERTIES('option.format-version'='2')` to update the format-version. But I'm not very sure why it required prefix `option.`.

**Comment by gaborkaszab** [comment]
@0xffmeta I think Hive currently is not using the 'format-version' table property set by Spark and in turn takes another one that is meant to be stored in HMS to check the version of an Iceberg table. I believe there is active work on this to fix.

**Comment by 0xffmeta** [comment]
Many thanks @gaborkaszab for the information. So I think right now the proper way to check for the table's `format-version` is by checking the `.metadata.json` file?

**Comment by 0xffmeta** [comment]
Understood. Thanks for the explanation. @gaborkaszab
