### ISSUE TITLE
How to use equality delete  in Iceberg v2 table

### ISSUE THREAD

**Issue by wsjz** [apache/iceberg#6196]
### Feature Request / Improvement

I want to generate equality delete in EMR spark, but It's all position delete, so how can I use this

### Query engine

Spark

**Comment by singhpk234** [comment]
writing Equality deletes are not supported in spark as of now, I think only flink supports it at the moment

**Comment by nastra** [comment]
@singhpk234 is it worth documenting this so that it's clearer for users?

**Comment by singhpk234** [comment]
> @singhpk234 is it worth documenting this so that it's clearer for users?

+1 I think we should document this, have seen this come up quite a number of times in slack discussions. 
I think adding a note here https://github.com/apache/iceberg/blob/master/docs/spark-writes.md#spark-writes or https://github.com/apache/iceberg/blob/master/docs/spark-writes.md#delete-from should be sufficient thoughts ?

**Comment by ajantha-bhat** [comment]
@singhpk234, @nastra: 

I think we need to add it to this. Without mentioning what is row-level-deletes, we can't add the note in spark writes.
https://github.com/apache/iceberg/pull/3432

I pinged @jackye1995 at that time, but he didn't reply. Maybe I can open a new PR by adding him as a co-author.

**Comment by tanvn** [comment]
> @singhpk234 is it worth documenting this so that it's clearer for users?

Actually it took me a while to find this issue to confirm that  Equality deletes are not supported in Spark (after spending one hour reading the source code). I think it would be very helpful if this information can be found more easily.

**Comment by link3280** [comment]
> > @singhpk234 is it worth documenting this so that it's clearer for users?
> 
> Actually it took me a while to find this issue to confirm that Equality deletes are not supported in Spark (after spending one hour reading the source code). I think it would be very helpful if this information can be found more easily.

@tanvn Hi, would you kindly get me a pointer to the code snippet? Thx!
