### ISSUE TITLE
colStats flag in TableContext remains false except in situation where delete files are present

### ISSUE THREAD

**Issue by ahshahid** [apache/iceberg#6198]
### Feature Request / Improvement

Enabling this flag would allow  non partition column stats (lower & upper bounds especially) to be available in the Manifest file, which can aid in pruning for range filters pushed down to scan by ManifestEvaluators

Is there a particular reason why this flag is not turned on by default?
There does not appear  any significant cost for writing this data in manifest file, as I believe the data files already contain that information...

### Query engine

Spark

**Comment by RussellSpitzer** [comment]
What exactly are your commenting on? By default we record all metrics for all columns unless there is a high number of columns.

See https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/MetricsConfig.java

**Comment by ahshahid** [comment]
What I noticed was that by default when iceberg format files are generated,  the manifest file  does not contain lower bound/ upper bound info for non-partition columns.
For **non partition** columns it writes empty bytes.

And this behaviour is due to the flag colStats being false by default and gets turned on , only under specific cases ( like presence of delete files).

If colStats flag is true, then manifest file records valid (i.e not empty byte buffer),  non-partition-column's stats, too.

I believe these stats if available can help in pruning for some queries atleast...

**Comment by ahshahid** [comment]
@RussellSpitzer Pardon my ignorance, I am little new to iceberg, but what I noticed was that because these stats were not present in Manifest file for non-partition-columns, the  range filters pushed at scan level, could not prune in ManifestEvaluator.

**Comment by RussellSpitzer** [comment]
Do you have a repo of this?

Here is an example of creating a table without partitions, then reading the upper bounds of the column from the metadata table which only reads manifest data.
```
scala> spark.sql("create table local.default.nopart_test (x int, y int)")
res15: org.apache.spark.sql.DataFrame = []

scala> spark.sql("INSERT INTO table local.default.nopart_test (x,y) values (127,127)")
res16: org.apache.spark.sql.DataFrame = []

scala> spark.sql("SELECT lower_bounds, upper_bounds from local.default.nopart_test.files").collect()(0)(1)
res18: Any = Map(1 -> Array(127, 0, 0, 0), 2 -> Array(127, 0, 0, 0))
```

**Comment by RussellSpitzer** [comment]
I think I understand what you are asking about, not the Manifests but the ManifestList files. The manifest list files only store metrics for partitions since they contain entries for manifests and not data files. A given manifest contains entries for many data files along with the data metrics for each of those files. 

The current thought process there is that a manifest will most likely contain many if not thousands of data file entries but will only contain data files for a few distinct partitions. Because it will include so many datafiles, possibly all of those for a partition, storing metric bounds for non partition columns isn't vary useful since it would be the entire range for that column.

**Comment by ahshahid** [comment]
@RussellSpitzer . Thanks for responding... Initially I also spent a good time to figure out which data structre was holding entries in ManifestList and which was holding data of Manifest file..
Actually I do mean Manifest file & not List.
The content of Manifest File is represented in memory by a class Implementing interface ContentFile.. 
I think the concrete class for Manifest conent is GenericDataFile.  This has methods to get lower bounds/ upper bounds for non partition columns..
If the boolean colStats is false, the Manifest file are generated without  valid stats for non-partition-cols.
As a result ManifestEvaluator is not able to make use of prunning at Manifest level.

Let me see if I can find an image of Manifest file generated without valid stats & one with valid stats

**Comment by ahshahid** [comment]
"The current thought process there is that a manifest will most likely contain many if not thousands of data file entries but will only contain data files for a few distinct partitions. Because it will include so many datafiles, possibly all of those for a partition, storing metric bounds for non partition columns isn't vary useful since it would be the entire range for that column."

@RussellSpitzer . I see that you sort of answered my question .
I have some thought about  allowing  non partition columns being pushed to scan level by spark and execute an approximate Dynamic Non Partition Pruning query , which just gets approximate bounds for that non partition columns ( which could be served very fast using manifest file only)

**Comment by ahshahid** [comment]
"Because it will include so many datafiles, possibly all of those for a partition, storing metric bounds for non partition columns isn't vary useful since it would be the entire range for that column."

But I suppose the bounds would be for each data file,... right?

**Comment by RussellSpitzer** [comment]
The manifest contains DataFile entries, each of which contains all upper and lower bounds of the data files which were persisted in the manifest.

**Comment by RussellSpitzer** [comment]
To fully go over the path

First you read a manifest list
The manifest contains a list of manifests
The partition filter is compared to each manifests upper and lower partition bounds
Manifest files which pass this filter are then read
Manifest files contain a list of data files
Each data file is compared with all filters provided for all columns
Data files which are pass these filters are then used for planning scan tasks

**Comment by ahshahid** [comment]
@RussellSpitzer Its my mistake ... For some reason It appeared to me that lower/upper bounds data was either missing from manifest file for non partition cols and that manifest file was not filtering based on that..
But I was wrong.. I can see that bounds data is present in manifest files for non partition cols & InclusiveMetricsEvaluator is using that stats of manifest file to trim data files.
