### ISSUE TITLE
Using iceberg-parquet and iceberg-spark-runtime throws ClassCastException for MessageType

### ISSUE THREAD

**Issue by eemario** [apache/iceberg#6205]
### Query engine

Spark

### Question

When I am using iceberg-parquet to perform write to iceberg table in my source code and using iceberg-spark-runtime to validate table content in unit tests, I get this java.lang.ClassCastException: class org.apache.parquet.schema.MessageType cannot be cast to class org.apache.iceberg.shaded.org.apache.parquet.schema.MessageType:
        at org.apache.iceberg.parquet.ReadConf.<init>(ReadConf.java:136)
        at org.apache.iceberg.parquet.VectorizedParquetReader.init(VectorizedParquetReader.java:90)
        at org.apache.iceberg.parquet.VectorizedParquetReader.iterator(VectorizedParquetReader.java:99)
        at org.apache.iceberg.spark.source.BatchDataReader.open(BatchDataReader.java:139)
        at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:112)
        at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:93)
        at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:130)
......

It seems that MessageType exists in both iceberg-parquet and iceberg-spark-runtime and is shaded in iceberg-spark-runtime because of version confict but not completely shaded? Is there any way to solve this problem?

**Comment by nastra** [comment]
There have been some fixes in the past around Spark + Parquet (https://github.com/apache/iceberg/pull/4667), so would be interesting to know which Iceberg + Spark version you're using.

**Comment by eemario** [comment]
I think these two dependencies triggered the exception when I call `spark.read().format("iceberg").load(...)` :

<dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-parquet</artifactId>
            <version>1.0.0</version>
</dependency>
<dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-spark-runtime-3.2_2.12</artifactId>
            <version>1.0.0</version>
</dependency>


I solved it by changing these to:

<dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-parquet</artifactId>
            <version>1.0.0</version>
</dependency>
<dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-spark</artifactId>
            <version>1.0.0</version>
</dependency>
<dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-arrow</artifactId>
            <version>1.0.0</version>
</dependency>

Thanks!

**Comment by ajantha-bhat** [comment]
`iceberg-spark-runtime-3.2_2.12` dependency itself is enough. No need to depend on `iceberg-parquet` explicitly I think.

**Comment by eemario** [comment]
Yes, I have tried it too and that is another way to get around this. 
But we only use iceberg-spark-runtime to test. It is a bit too big to be included as a whole and so we choose to use `iceberg-parquet` in the source and give `iceberg-spark-runtime` the `test` scope.

**Comment by ismailsimsek** [comment]
Thank you. ran into same error and it solved my error.

`Caused by: java.lang.ClassCastException: class org.apache.parquet.schema.MessageType cannot be cast to class org.apache.iceberg.shaded.org.apache.parquet.schema.MessageType`

replaced spark runtime with following 

```

        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-spark-${version.spark.major}_${version.spark.scala}</artifactId>
            <version>${version.iceberg}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-spark-extensions-${version.spark.major}_${version.spark.scala}</artifactId>
            <version>${version.iceberg}</version>
            <scope>test</scope>
        </dependency>
```

**Comment by nastra** [comment]
@ismailsimsek it is actually correct to use the spark runtime jar. You just need to make sure to not use a separate parquet lib. If you want to still use a separate parquet dependency, then you'd need to make sure that it's always the same version that Iceberg is using
