### ISSUE TITLE
Flink version Support Issue wrt IceBerg

### ISSUE THREAD

**Issue by Gajai** [apache/iceberg#6208]
### Question

Latest Flink Version Supported is is 1.11.x only? Do we have any upcoming possibilities for flink 1.16.x version anytime soon?

**Comment by luoyuxia** [comment]
The comming iceberg 1.1.0 which is in preparing release will support flink 1.16.x.

**Comment by nastra** [comment]
Note that Iceberg 1.0.0 supports Flink 1.15.0. The project is about to ship Iceberg 1.1.0 in the next few days, which will include Flink 1.16.0 support.

**Comment by nastra** [comment]
@Gajai I hope that answered your question. Please re-open the issue if not.
