### ISSUE TITLE
write.metadata.metrics.default how to works?

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#6216]
### Query engine

spark 3.xx

### Question

i set write.metadata.metrics.default =full to an iceberg table, how can i see if it works? i log the upper and lower message, the object message is : 'java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]', it seems  that write.metadata.metrics.default is truncat(16), so i am a little confused

**Comment by nastra** [comment]
You can look at the manifest file and it should contains metrics for `lower_bounds` / `upper_bounds`/ and a few others. Or is your question more specific to using `full` metrics mode?

**Comment by chenwyi2** [comment]
manifest file  can see deleteFile.lowerBounds() ?

**Comment by nastra** [comment]
@chenwyi2 could you please rephrase your question so that I can help you better in answering it?
