### ISSUE TITLE
Set COMMIT_MIN_RETRY_WAIT_MS_DEFAULT to 1000 ms instead of 100 ms to avoid too frequent commit exceptions

### ISSUE THREAD

**Issue by rbalamohan** [apache/iceberg#6218]
### Please describe the bug 🐞

COMMIT_MIN_RETRY_WAIT_MS_DEFAULT has been set to 100ms. Though it has 4 retries, with exponential backoffs, it mostly would be complete within 1-2 seconds. 

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/TableProperties.java#L89

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/Tasks.java#L441-L443

For large tables, it can take couple of seconds for commit operation and current default leads to frequent commit failures. Since this is table level property, it can't be set in session level as well causing inconvenience. It will be helpful to set this value to 1000ms instead of 100ms as the default. This should provide roughly 8+ seconds for exponential backoffs, giving better chance for commits.

**Comment by nastra** [comment]
I'm not sure we would want to increase the default as that would cause things to generally take longer in the case of retries. For large tables I think it would better to selectively increase `commit.retry.num-retries` / `commit.retry.min-wait-ms` for those particular tables. 
I'm curious why commits in your case take several seconds to complete. Do you have lots of small data files that are being tracked in metadata files?
