### ISSUE TITLE
using pyiceberg with kerberized hive metastore

### ISSUE THREAD

**Issue by metalshanked** [apache/iceberg#6229]
Hi, 
Can anyone share examples of using pyiceberg with a kerberized hive metastore?
Trying for Windows but a Linux example would do as well.

```
raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```

Thanks!

**Comment by brysd** [comment]
same issue here: 

```python
from pyiceberg.catalog import load_catalog

database = "mydatabase"
table = "mytable"

catalog = load_catalog("default")
table = catalog.load_table((database, table))
schema = table.schema
print(schema)
```

returns exactly the same error as mentioned above by @metalshanked 

pyiceberg configuration (.pyiceberg.yaml):

```yaml
catalog:
  default:
    uri: thrift://master1.url:9083,thrift://master2.url:9083

```

our Cloudera environment is also fully kerberized.

Can we set additional logging settings to see more details in the DEBUG level to find the root cause?
