### ISSUE TITLE
Fix for issue #2796 is missing from 0.14.1 and 1.0.x releases

### ISSUE THREAD

**Issue by psnilesh** [apache/iceberg#6245]
### Apache Iceberg version

1.0.0 (latest release)

### Please describe the bug 🐞

Same bug as https://github.com/apache/iceberg/issues/2796.  I see it is [already fixed by](https://github.com/apache/iceberg/pull/5282) @jfz  and merged into `master` but I don't see the fix in either `0.14.1` or `1.0.0` branch.  Is it a miss or deliberately not included for some reason ?

**Comment by ajantha-bhat** [comment]
0.14.1 and 1.0.0 release is not from the master branch. It was based on 0.14.0 branch. 
The fix that you are expecting will be available in the upcoming 1.1.0 release.

**Comment by psnilesh** [comment]
Thank you.  When can I expect 1.1.0 ?

**Comment by psnilesh** [comment]
Got it. Closing the issue.
