### ISSUE TITLE
Update Iceberg Hive documentation

### ISSUE THREAD

**Issue by InvisibleProgrammer** [apache/iceberg#6249]
### Feature Request / Improvement

https://iceberg.apache.org/docs/latest/hive/ tracks the documentation of Iceberg features supported by Hive. It currently reflects whatever was released with Hive 4.0.0-alpha-1. 

Now with the imminent release of 4.0.0-alpha-2, we have some yet-to-be-documented features such as rollback functionality that we need to amend the upstream doc with.

To document

https://issues.apache.org/jira/browse/HIVE-26077 - Implement CTAS for Iceberg tables with partition spec

https://issues.apache.org/jira/browse/HIVE-26354 - Support expiring snapshots on iceberg table

https://issues.apache.org/jira/browse/HIVE-26519 - Iceberg: Add support for CTLT queries

https://issues.apache.org/jira/browse/HIVE-26535 - Iceberg: Support adding parquet compression type via Table properties

https://issues.apache.org/jira/browse/HIVE-26203 - Implement alter iceberg table metadata location

https://issues.apache.org/jira/browse/HIVE-26228 - Implement Iceberg table rollback feature

https://issues.apache.org/jira/browse/HIVE-26397 - Honour Iceberg sort orders when writing a table

### Query engine

Hive

**Comment by InvisibleProgrammer** [comment]
https://issues.apache.org/jira/browse/HIVE-26077 - Implement CTAS for Iceberg tables with partition spec - it is already docummented in the following commit: https://github.com/InvisibleProgrammer/iceberg/commit/6e0a952e6dd059e1b9273b3e7dc36ae00cea9671

**Comment by TuroczyX** [comment]
Nice :)

**Comment by InvisibleProgrammer** [comment]
PRs for older versions: 

- 0.14.1: https://github.com/apache/iceberg-docs/pull/188
- 1.0.0: https://github.com/apache/iceberg-docs/pull/189
- 1.1.0: https://github.com/apache/iceberg-docs/pull/190

**Comment by InvisibleProgrammer** [comment]
Hey, @rdblue : 

First of all, thank you for your feedback. I'll get the necessary information to answer your questions.

As all the PRs are merged, to do any changes, we will have to raise a new PR. 

What do you think if I put your questions into the issue, move the conversation there and close that PR?
Issue: https://github.com/apache/iceberg/issues/6249

Thank you, 
Zsolt

**Comment by InvisibleProgrammer** [comment]
There are some ongoing questions, I'll try to answer them here. Context: https://github.com/apache/iceberg/pull/6379
