### ISSUE TITLE
Does iceberg not support stream reading and updating tables

### ISSUE THREAD

**Issue by yinshan612** [apache/iceberg#6262]
### Query engine

Flink

### Question

Read the test table through the iceberg stream, and then update the test. The stream read task will report an error and terminate. Is this a bug or a function not implemented at present

一.sqlclient

 CREATE TABLE test2(
  id BIGINT COMMENT 'unique id',
   data STRING,
  primary key(id) not ENFORCED
 ) WITH (
    'connector'='iceberg',
    'catalog-name'='hadoop_catalog',
    'catalog-type'='hadoop',  
    'warehouse'='hdfs://nn1:8020/warehouse/iceberg1',
    'format-version'='2'
  );

insert into test2 values (1,'202-11-20');
insert into test2 values (1,'2022-11-11');

二.other sqlclient

select * from test2 OPTIONS('streaming'='true', 'monitor-interval'='10s');

**Comment by nastra** [comment]
@yinshan612 could you please attach the error/stacktrace you're seeing in this case?

**Comment by yinshan612** [comment]
> 
The first insert is OK, but the second insert of the same key is the update operation. At this time, the following error will be reported when the stream of iceberg reads the table


error: Found overwrite operation, cannot support incremental data in snapshots (4030445746041511082, 4197372471984049664]

**Comment by nastra** [comment]
I don't think it's supported to perform **overwrites** when streaming is enabled. When streaming is enabled, Iceberg will use [Incremental scans](https://github.com/apache/iceberg/blob/master/flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java#L123) and those do not support [overwrites](https://github.com/apache/iceberg/blob/8b8a1038609610873c7d40023b4fc98ba341a502/core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java#L140-L145).

**Comment by yinshan612** [comment]
> Collaborator

It means that when monitoring a table through the stream read of iceberg, the table can only be append, not update or delete. Am I right in understanding this

**Comment by nastra** [comment]
Correct, via SQL + streaming you can only select + append, see also https://iceberg.apache.org/docs/latest/flink/#flink for what's supported currently

**Comment by yinshan612** [comment]
> Correct, via SQL + streaming you can only select + append, see also https://iceberg.apache.org/docs/latest/flink/#flink for what's supported currently

Will you support this in the future

**Comment by stevenzwu** [comment]
@yinshan612 support for deletes will probably be added in the future. e.g., here is one PR from @Reo-LEI 
https://github.com/apache/iceberg/pull/6182/files

**Comment by yinshan612** [comment]
> @yinshan612 support for deletes will probably be added in the future. e.g., here is one PR from @Reo-LEI https://github.com/apache/iceberg/pull/6182/files

okay, thank you
