### ISSUE TITLE
Unable to create Iceberg Table using HIVE 

### ISSUE THREAD

**Issue by kowshikdremio** [apache/iceberg#6263]
[HiveConfiguration.pdf](https://github.com/apache/iceberg/files/10082239/HiveConfiguration.pdf)

### Query engine

Hive

### Environment: 
**HIVE:** I am running HIVE with Local storage ( Not HADOOP). Regular HIVE tables are getting created. MariaDB is holding HIVE metastore. Please view the hive-site.xml given below
**Java:** OpenJDK Version 1.11
**Iceberg:** Cloned the latest from github and build using gradle script

### Ran the Following commands on HIVE command line:

add jar /home/ec2-user/iceberg/hive-runtime/build/libs/iceberg-hive-runtime-1.2.0-SNAPSHOT.jar;
add jar /home/ec2-user/iceberg/core/build/libs/iceberg-core-1.2.0-SNAPSHOT.jar;
add jar /home/ec2-user/iceberg/mr/build/libs/iceberg-mr-1.2.0-SNAPSHOT.jar;

### Error Description:
hive> create table test (name String) stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: MetaException(message:java.lang.NoClassDefFoundError Could not initialize class org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector)

Ideally as per document, we need to add only iceberg-hive-runtime-1.2.0-SNAPSHOT.jar. I did add the other two jars as well and it made me overcome some other class not found error. However, stuck with the above error now.

Please let me know what other jars I need to add to HIVE to make this work. 

Regards,
Kowshik

### Configuration of hive-site.xml:
<configuration> 
   <property> 
      <name>javax.jdo.option.ConnectionURL</name> 
      <value>jdbc:mysql://localhost/metastore?createDatabaseIfNotExist=true</value> 
      <description>metadata is stored in a MySQL server</description> 
   </property> 
   <property> 
      <name>javax.jdo.option.ConnectionDriverName</name> 
      <value>com.mysql.jdbc.Driver</value> 
      <description>MySQL JDBC driver class</description> 
   </property> 
   <property> 
      <name>javax.jdo.option.ConnectionUserName</name> 
      <value>hiveuser</value> 
      <description>user name for connecting to mysql server</description> 
   </property> 
   <property> 
      <name>javax.jdo.option.ConnectionPassword</name> 
      <value></value> 
      <description>hivepassword for connecting to mysql server</description> 
   </property>
   <property>
         <name>hive.metastore.schema.verification</name>
         <value>false</value>
      </property>
   <property> 
        <name>hive.metastore.warehouse.dir</name> 
	<value>file:///home/ec2-user/warehouse</value> 
        <description>location of default database for the warehouse</description> 
</property>
   <property> 
        <name>fs.default.name</name> 
        <value>file:///home/ec2-user/warehouse</value> 
     </property> 
   
    <property> 
	    <name>hive.metastore.uris</name> 
	    <value>thrift://localhost:9083</value>
        <description>Thrift URI for the remote metastore.</description>
    </property>
    <property>
        <name>hive.server2.enable.doAs</name>
        <value>false</value>
</property>
    <property>
	<name>iceberg.engine.hive.enabled</name>
	<value>true</value>
   </property>
</configuration>

**Comment by nastra** [comment]
It is correct to only add `iceberg-hive-runtime-1.2.0-SNAPSHOT.jar` (if you inspect its content, then it will also contain `org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector`). The other two jars should not be necessary. Which Hive version are you running?

**Comment by kowshikdremio** [comment]
I am using Hive 3.1.3....

> It is correct to only add `iceberg-hive-runtime-1.2.0-SNAPSHOT.jar` (if you inspect its content, then it will also contain `org.apache.iceberg.mr.hive.serde.objectinspector.IcebergObjectInspector`). The other two jars should not be necessary. Which Hive version are you running?

**Comment by pvary** [comment]
What is the execution engine that you are using?
Could you use Hive 4.0.0 instead? Iceberg is already integrated there, and should work OOB.

**Comment by kowshikdremio** [comment]
Hi,
      I added the below jars to the HIVE lib directory and it all works fine now. 
1.iceberg-hive-runtime-1.2.0-SNAPSHOT.jar ( Got it by running ./gradlew build -x test -x integrationTest on Iceberg download)
2. iceberg-hive3-1.1.0.jar (Downloaded it from Maven Central https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-hive3/1.1.0/iceberg-hive3-1.1.0.jar)

All running good now.

Thanks,
Kowshik
