### ISSUE TITLE
I use pyiceberg to read the iceberg table based on the hdfs file system and an exception is thrown

### ISSUE THREAD

**Issue by MrDannyWu** [apache/iceberg#6269]
### Query engine

python + pyiceberg

### Question
catalog = HiveCatalog(HIVE_CATALOG_NAME,  uri=HIVE_METASTORE_FAKE_URL)
table = catalog.load_table(("ods", "table"))

When I use pyiceberg to read the iceberg table based on hdfs file system, the following exception is thrown:
![image](https://user-images.githubusercontent.com/19458048/203909145-43552835-8e37-4a20-a765-695e8fa27361.png)

I want to know will pyiceberg support hdfs file system?
How often is pyiceberg updated?

**Comment by Fokko** [comment]
Thanks for creating the issue @MrDannyWu. PyArrow has support for HDFS: https://arrow.apache.org/docs/python/filesystems.html#hadoop-distributed-file-system-hdfs But it is untested. Would you be interested in contributing support for HDFS? 

> How often is pyiceberg updated?

We aim to update often. We'll do another release in the upcoming weeks after read support has been added.

**Comment by MrDannyWu** [comment]
> 

Thanks for your reply, I may try to test it.

**Comment by nastra** [comment]
Should we close this issue and track support for HDFS in a separate issue? Alternatively we could rename this issue to indicate that we're adding support for HDFS

**Comment by MrDannyWu** [comment]
Okay，thanks！

**Comment by MrDannyWu** [comment]
Okay，thanks！Sent from my phone-------- Original message --------From: Eduard Tudenhöfner ***@***.***>Date: Mon, Nov 28, 2022, 20:43To: apache/iceberg ***@***.***>Cc: DannyWu ***@***.***>, Mention ***@***.***>Subject: Re: [apache/iceberg] I use pyiceberg to read the iceberg table based on the hdfs file system and an exception is thrown (Issue #6269)
Should we close this issue and track support for HDFS in a separate issue? Alternatively we could rename this issue to indicate that we're adding support for HDFS
