### ISSUE TITLE
How to migrate (metadata only) Hadoop catalog to Hive catalog?

### ISSUE THREAD

**Issue by shay1bz** [apache/iceberg#6302]
### Query engine

Spark 3.3.0, Dremio

### Question

Hi,

We have some existing Hadoop tables, and recently deployed HMS as the new catalog for Iceberg. Is there a way to recreate all the required metadata in the metastore based on the Hadoop metadata?

**Comment by singhpk234** [comment]
you can use register table functionality which basically just registers / add's your metadata.json pointer to your hive metastore.

Here is a sample code (a UT) for migrating Hadoop Catalog to metastore backed tables 
https://github.com/apache/iceberg/blob/66fd615cd4cdab2ff76915dc5929d5c93705063e/hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java#L449-L500

**Comment by shay1bz** [comment]
Great, thanks a lot!
