### ISSUE TITLE
Hive: add Kerberos auth support in HiveCatalog

### ISSUE THREAD

**Issue by mas-chen** [apache/iceberg#6312]
### Feature Request / Improvement

Implement Kerberos support for Hive Catalog, the feature could be enabled by a property. Kerberos is required when HMS is kerberized and requires authentication. For Flink in specific, the Kerberos TGT needs to be refreshed since it is a long running job, which can be part of the HiveCatalog.

**Comment by stevenzwu** [comment]
I work with @mas-chen on the same team. @pvary @rdblue @szehon-ho what do you think about adding Kerberos/auth support to Hive Catalog?

**Comment by pvary** [comment]
RetryingMetaStoreClient should take care of refreshing, or `reloginExpiringKeytabUser`. See: https://github.com/apache/hive/blob/master/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java#L180

Also there is an ongoing effort to use `DelegationToken`-s for Flink which would affect Hive as well in the long run. @gsomogyi knows more about this effort.

**Comment by gaborgsomogyi** [comment]
One just needs to implement a [delegation token provider](https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/security/token/HadoopDelegationTokenProvider.java) for Hive and all done. This popped up already in the Flink community so sooner or later it will happen. There is already such provider in Spark...

**Comment by gaborgsomogyi** [comment]
Just to be crystal clear I see no reason to solve Kerberos authentication in Iceberg.

**Comment by stevenzwu** [comment]
Based on the feedbacks, we will not pursue this route. closing the issue.
