### ISSUE TITLE
Drop TableProperties.HMS_TABLE_OWNER in 1.3.0

### ISSUE THREAD

**Issue by gaborkaszab** [apache/iceberg#6316]
### Feature Request / Improvement

This field is deprecated in 1.2.0 by https://github.com/apache/iceberg/pull/6314 and should be removed in 1.3.0. The similar one from HiveCatalog should be used instead.

**Comment by john8628** [comment]
I will try it , please assign it to me,  thanks

**Comment by gaborkaszab** [comment]
@john8628 thanks for the interest! However, we should wait with this ticket for 1.2.0 to go out that will mark this property as deprecated, so that we can drop it in 1.3.0. It's kind of too early to implement it now.

**Comment by jackye1995** [comment]
@gaborkaszab do you plan to work on this deprecation?

**Comment by gaborkaszab** [comment]
Thanks for the reminder, @jackye1995 ! Apparently, https://github.com/apache/iceberg/pull/7156 has already dropped this. Closing the issue.
