### ISSUE TITLE
executor logs ton of `INFO CodecPool: Got brand-new decompressor [.zstd]`

### ISSUE THREAD

**Issue by camper42** [apache/iceberg#6318]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

call rewrite_data_files on a zstd+parquet table (feed by stream)

executor logs too many `INFO CodecPool: Got brand-new decompressor [.zstd]` and I have to set log level to `WARN` or my pod log will fill up ephemeral storage

Is this a side effect of #5681 ? 

![image](https://user-images.githubusercontent.com/3177898/204755406-0a75af51-5f98-409d-bfd5-4528017fe598.png)

**Comment by nastra** [comment]
I've looked at the code and this happened even before #5681. The decompressors are actually being re-used, but not across different Parquet Files. So this means in your case you have lots of Parquet files that are being read, and thus you're seeing this log output from Hadoop's `CodecPool`

**Comment by camper42** [comment]
thx, so for my scenario, I may need to compact more promptly and/or set the log level of the `CodecPool` to `WARN`
