### ISSUE TITLE
Cache in GenericArrowVectorAccessorFactory causing lot of upfront allocations causing slowness in Vectorized parquet reading

### ISSUE THREAD

**Issue by rbalamohan** [apache/iceberg#6319]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Iceberg uses vectorized parquet reader in arrow format. Internally "ColumnBatchLoader" invokes "IcebergArrowColumnVector::forHolder". In that codepath, it uses "GenericArrowVectorAccessorFactory", which caches getDecimal usage. 

For cache usage, it creates decimal[] array upfront. This causes slowness in queries during vectorized parquet reading. I will attach the memory allocation profile for reference. In certain cases, it was observed that some of the arrays are in the range of 100-200K.

It will be helpful to remove the cache or provide an option to optionally use it.  There is also an issue with arrow boundary checks, for which I will create a separate ticket.

![q27_ice_alloc_v2](https://user-images.githubusercontent.com/7969713/204758773-ece14f1a-1031-462e-a91e-62404e4808c7.png)

**Comment by aokolnychyi** [comment]
This is a very interesting finding.

Null and boundary checks are well-known and we are trying to automate their setting in PR #6550. I did not know about this performance limitation. I'll take a closer look this week. Any updates on this, @rbalamohan?

**Comment by rbalamohan** [comment]
Thanks for #6550 which takes care of boundary checks issue in arrow. I haven't revisited this ticket yet; Need to check that removing the cache doesn't cause additional issues for decimal.
