### ISSUE TITLE
ArrowBuf boundary checks causing CPU burn and slowness in vectorized parq reading

### ISSUE THREAD

**Issue by rbalamohan** [apache/iceberg#6320]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

When running queries like Q27 in iceberg V2 with vectorized parquet reading, it was observed that it is slower than traditional spark+vectorized_parq_reading.  Profile more revealed that cache allocation was causing pressure on JVM which is covered in https://github.com/apache/iceberg/issues/6319.

I added a local patch to disable the cache and profile for CPU. This was done to get past this issue and look for other bottlenecks. This revealed that good amount of CPU was spent on ArrowBuf boundary checks. This can be disabled by having "-Darrow.enable_unsafe_memory_access=true" in the JVM options.  I observed 25% improvement in runtime with vectorized processing in q27 with both these issues addressed. Need to check if this option can be enabled in iceberg directly, or it needs to be documented so that users can include it in executor & driver JVM options.

![q27_ice_alloc_cpu_v2](https://user-images.githubusercontent.com/7969713/204759995-feaea6f6-1fd8-45a3-915c-9a7294863ff3.png)

**Comment by singhpk234** [comment]
+1 on documenting considering the speedup it brings. I think having a section like https://spark.apache.org/docs/latest/sql-performance-tuning.html in iceberg could be really helpful.

@kbendick also mentioned the same in https://github.com/apache/iceberg/issues/4217#issuecomment-1159209016 as a recommendation to avoid redundant checks.

**Comment by rbalamohan** [comment]
Looks like this property is document in arrow project itself in perf section. It will be good to have this document it for iceberg for perf (given vecctorized parq uses arrow).
https://github.com/apache/arrow/blob/master/java/README.md

**Comment by hililiwei** [comment]
+1 on documenting

**Comment by aokolnychyi** [comment]
Resolved by PR #6550.
