### ISSUE TITLE
Iceberg write by flink perjob too slow!!!!!

### ISSUE THREAD

**Issue by HavAnIdea** [apache/iceberg#6321]
### Query engine

flink

### Question

I used flink API to write data
By flink local mode, the speed is more than 20000 record/s
but i change to flink perjob mode, the speed is under 50 record/s

Same code, only changed submit mode 

Code like :

SingleOutputStreamOperator<RowData> map = source.filter(new RichFilterFunction<Record>() {
            @Override
            public boolean filter(Record value) throws Exception {
                return filterRecord(value);
            }
        }).map(new RichMapFunction<Record, RowData>() {
            @Override
            public RowData map(Record value) throws Exception {
                return mappingAndConvert(value);
            }
        });

FlinkSink.Builder sinkBuilder = FlinkSink.forRowData(map)
                .table(table)
                .tableLoader(TableLoader.fromHadoopTable(tableLocation, getHadoopConf(icebergConfig)))
                .writeParallelism(parallelism+10)
                .equalityFieldColumns(equalityFiledColumns)
                .overwrite(overwrite);
        if (Objects.nonNull(writeFileSize) && writeFileSize > 0) {
            sinkBuilder.set("target-file-size-bytes", String.valueOf(writeFileSize));
        }
        sinkBuilder.append();

**Comment by luoyuxia** [comment]
@HavAnIdea Is there any difference in the job graph between local mode and per job mode.

**Comment by pvary** [comment]
@HavAnIdea: You might want to define `.returns(typeInfo)` for the `map` stream to have better serialization performance
