### ISSUE TITLE
estimateStatistics cost mush time to compute stats

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#6326]
### Query engine

spark 3.1

### Question

spark driver will cost too much time to computes stats since listing all the files to getstats,and the thread is below:
![reliao_img_1669864216597](https://user-images.githubusercontent.com/19389434/204957073-f7672b97-4ad5-418a-a5b1-2f50ec020146.png)
 and the code is 
````java
for (CombinedScanTask task : tasks()) {
      for (FileScanTask file : task.files()) {
        // TODO: if possible, take deletes also into consideration.
        double fractionOfFileScanned = ((double) file.length()) / file.file().fileSizeInBytes();
        numRows += (fractionOfFileScanned * file.file().recordCount());
      }
    }
````
maybe we can add an option to disable estimateStatistics ?

**Comment by RussellSpitzer** [comment]
While I don't have a problem with disabling statistics reporting, I am pretty dubious this takes that long. What I believe you are actually seeing is the task list being created fort the first time and stored in a list. We use a lazy iterator which needs to be turned into a list before the job begins (even if statistics are not reported). This means even if we don't spend the time iterating the list when we are estimating stats, we will spend that same amount of time later when planning tasks. The only difference would be in the current case the second access to "tasks()" is cached so it's very fast.

In this case the speed could probably be improved if the parallelism of the Manifest Reads was increased.

**Comment by rbalamohan** [comment]
Check if increasing "iceberg.worker.num-threads" helps in this case. Default should be the number of processors available in the system. This can be increased by setting it as system property (try sending it via spark driver/executor jvm opt).
