### ISSUE TITLE
Create tables error when using JDBC catalog and mysql backend

### ISSUE THREAD

**Issue by loleek** [apache/iceberg#6332]
### Apache Iceberg version

1.1.0 (latest release)

### Please describe the bug 🐞

When I use jdbc catalog with mysql backend in flink test case, the create catalog operation return an error.

>Flink SQL> CREATE CATALOG iceberg_catalog WITH (
>   'type'='iceberg',
>   'catalog-impl'='org.apache.iceberg.jdbc.JdbcCatalog',
>   'catalog-name' = 'iceberg_catalog',
>   'warehouse' = 'file:///path/to/warehouse',
>   'uri' = 'jdbc:mysql://host:port/iceberg_catalog',
>   'jdbc.user' = 'root',
>   'jdbc.password' = 'passwd');
[ERROR] Could not execute SQL statement. Reason:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes.

I think the root cause is here https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L179 which use CATALOG_NAME VARCHAR(255) + NAMESPACE_NAME VARCHAR(255) + NAMESPACE_PROPERTY_KEY VARCHAR(5500) as primary key.

Here is a related issue https://github.com/apache/iceberg/pull/2778/files, which fix CREATE_CATALOG_TABLE statement.

**Comment by nastra** [comment]
The `max key length limit=767` is actually a limit that is imposed by the underlying database being used (MySQL in this case). A valid approach would be to increase that limit on MySQL. 

Related issue: https://github.com/apache/iceberg/issues/6236

**Comment by nastra** [comment]
I have created to https://github.com/apache/iceberg/pull/6338 to make this less of an issue with MySql
