### ISSUE TITLE
Deleting a column from an iceberg table breaks schema in AWS Glue catalog

### ISSUE THREAD

**Issue by alesk** [apache/iceberg#6340]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

When deleting a column with Spark SQL using `ALTER TABLE table_name DROP COLUMN column_name`, the following happens:

1) The column gets removed from the current schema in the Table's metadata on s3. 
2) A new version of the schema is created in AWS Glue but the column is moved to the last position in the table instead of being removed.

The two schemas have diverged. Querying with Spark works as expected but using Athena the wrong schema is reported thus breaking tools such as Metabase.

**Comment by nastra** [comment]
@amogh-jahagirdar could you please take a look at this one?

**Comment by mattiamatrix** [comment]
Hello, any updates on this? This bug is still present!

**Comment by nastra** [comment]
@mattiamatrix since this seems to be an Athena-specific issue, it's probably best to take this issue to the Athena team
/cc @jackye1995 @amogh-jahagirdar

**Comment by qoqajr** [comment]
Hello, any updates on this? This bug is still present!

**Comment by 00Fede** [comment]
This is still happening. We have to delete the dropped column directly from AWS Glue Data Catalog to be able to run queries in Athena or Quicksight.

**Comment by qoqajr** [comment]
I did the same but having to write custom code for both deleting a column with spark.sql and then in the glue catalog (I did it with awswrangler lib) is a bit messy to me.

**Comment by d4r3topk** [comment]
Still facing this in 1.4.0
