### ISSUE TITLE
[Docs]: improve ChangeLog

### ISSUE THREAD

**Issue by code-magician323** [apache/iceberg#6347]
### Feature Request / Improvement

The [Iceberg changelog](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.1.0) isn't quite useful, only because we can't see in a unified place all of the changes for each specific subject. Separation of changelog bullets to their component - e.g. some grouping by Spark, Core, Flink, etc., would be super helpful and much more comfortable to read.

### Query engine

None

**Comment by TuroczyX** [comment]
@code-magician323 Something like this? https://github.com/apache/iceberg/issues/6249

**Comment by Fokko** [comment]
Hey @InvisibleProgrammer I like the idea. The changelog for 1.1.0 is rather big, grouping it by engine, core, etc would help a lot. I already removed all the Python PRs to reduce the noise, since PyIceberg has its own release cycle.

**Comment by TuroczyX** [comment]
+1

**Comment by code-magician323** [comment]
https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.3.0 This changelog is just not readable

**Comment by bitsondatadev** [comment]
@code-magician323 Agreed, I'm the new Head of Developer Relations at Tabular and This is definitely on my roadmap to fix. I'll have more details in the coming weeks. We're hiring someone who will help with the release process.
