### ISSUE TITLE
Python: Ignore home folder when running tests

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#6361]
### Feature Request / Improvement

When you run tests on your local machine, and you have a `~/.pyiceberg.yaml` around, there is a possibility that the `test_missing_uri` will fail because it will pick up the URI from the configuration.

Instead, for the tests, we could create a fixture that will create a temporary directory, and point the home directory to that freshly created folder. This way the tests are more isolated from the environment it runs in.

### Query engine

None

**Comment by rubenvdg** [comment]
Happy to take this one on, if nobody is working on it atm.

**Comment by rubenvdg** [comment]
@Fokko this one can be closed.

**Comment by Fokko** [comment]
Thanks @rubenvdg much appreciated
