### ISSUE TITLE
What is the purpose of Hive Lock ?

### ISSUE THREAD

**Issue by dmgcodevil** [apache/iceberg#6370]
### Query engine

Flink/Spark/Trino

### Question

What is the purpouse of Hive Lock ? is it possible to replace it with an atomic operation: replace.(expectedMetadata, newMedata) ? Hive metastore is backed by a sql db wich supports transactions

**Comment by pvary** [comment]
@dmgcodevil: The purpose of the Hive Lock is to make sure that there are no concurrent changes to the table. Specifically that there is no concurrent Iceberg commit.

In theory the replace is a good idea, but in an ideal world that is a new feature in HMS which could be only supported in the upcoming releases (4.0.0). Most of the Iceberg community uses older 3.x Hive (HMS) version, or even older 2.x some cases. Adding a new feature there is usually not allowed.

Just from the Iceberg perspective this change would be very much needed and welcome as it would mean faster/more reliable commit flow for HiveCatalogs

**Comment by TuroczyX** [comment]
It is definitely something that we need to consider. We will talk about it on our next meeting.

**Comment by dmgcodevil** [comment]
Does the JdbcCtalog support atomic updates w/o locks?

**Comment by hililiwei** [comment]
> Just from the Iceberg perspective this change would be very much needed and welcome as it would mean faster/more reliable commit flow for HiveCatalogs

+1. If we could do that, that would be great. We sometimes encounter unexpected issues with Hive Lock in production.

**Comment by InvisibleProgrammer** [comment]
@pvary I think it is not  a simple yes or no question. We need some time to better understand the topic and the consequences of the change.

**Comment by pvary** [comment]
@InvisibleProgrammer: Fair enough. If it would have been a simple question, I might not have asked 😄

**Comment by pvary** [comment]
@InvisibleProgrammer, @TuroczyX: any news about the atomic lock?

**Comment by pvary** [comment]
Maybe something like this:
```
diff --git a/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift b/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
index 179a4960b9..6a3f9e40fa 100644
--- a/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
+++ b/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
@@ -22,7 +22,7 @@
 # Thrift Service that the MetaStore is built on
 #
 
-include "share/fb303/if/fb303.thrift"
+include "/Users/petervary/tmp/fb303.thrift"
 
 namespace java org.apache.hadoop.hive.metastore.api
 namespace php metastore
@@ -2165,7 +2165,9 @@ struct AlterTableRequest {
   6: optional i64 writeId=-1,
   7: optional string validWriteIdList
   8: optional list<string> processorCapabilities,
-  9: optional string processorIdentifier
+  9: optional string processorIdentifier,
+  10: optional string expectedPropertyKey,
+  12: optional string expectedPropertyValue
 // TODO: also add cascade here, out of envCtx
 }

diff --git a/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java b/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
index 1226cd1a1a..0b12e68401 100644
--- a/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
+++ b/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
@@ -102,7 +102,7 @@ public void setConf(Configuration conf) {
   @Override
   public void alterTable(RawStore msdb, Warehouse wh, String catName, String dbname,
       String name, Table newt, EnvironmentContext environmentContext,
-      IHMSHandler handler, String writeIdList)
+      IHMSHandler handler, String writeIdList, String expectedKey, String expectedValue)
           throws InvalidOperationException, MetaException {
     catName = normalizeIdentifier(catName);
     name = name.toLowerCase();
@@ -187,6 +187,11 @@ public void alterTable(RawStore msdb, Warehouse wh, String catName, String dbnam
             TableName.getQualified(catName, dbname, name) + " doesn't exist");
       }
 
+      if (expectedKey != null && !oldt.getParameters().get(expectedKey).equals(expectedValue)) {
+        throw new MetaException("The table already modified. The parameter value for key: " + expectedKey + " is "
+                + oldt.getParameters().get(expectedKey) + ". The expected was value was " + expectedValue);
+      }
+
       validateTableChangesOnReplSource(olddb, oldt, newt, environmentContext);
 
       // On a replica this alter table will be executed only if old and new both the databases are

```

**Comment by pvary** [comment]
Created the Hive jira: https://issues.apache.org/jira/browse/HIVE-26882
And the PR: https://github.com/apache/hive/pull/3888

**Comment by dmgcodevil** [comment]
@pvary is it still based on locks?

**Comment by pvary** [comment]
Why would it be based on locks? HMS changes inside a HMS call are transactional.
This is essential, otherwise we could end up in a situation where concurrent HMS changes could push the Metastore into an inconsistent state.
Using this transaction we could check and set the snapshot of the Iceberg table

**Comment by pvary** [comment]
@dmgcodevil: It turns out you have been right. Even though we do the changes in transaction on HMS side, the isolation level we use for those changes is `READ_COMMITTED`. This does not prevent reading old data and writing out the new ones concurrently.

Thanks for the feedback! I updated the Hive PR to use `REPEATABLE_READ` which would prevent the situation and act as a lock for our case.

**Comment by dmgcodevil** [comment]
@pvary I mean, does it solve the problem with orphan locks? Also, we see a lot of errors thrown [here](https://github.com/apache/iceberg/blob/master/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L294), but I don't understand how it's possible. Is it b/c some other process released the lock and update a table? Nonetheless, can get rid of locks, i.e. this [line](https://github.com/apache/iceberg/blob/master/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L266)?

**Comment by pvary** [comment]
@dmgcodevil: after the Hive PR we need to add a table property for Iceberg tables which will do 2 things:
- Adds the new `expected_parameter_key` and `expected_parameter_value` properties to the `alter_table` context
- Turns off the lock acquisition and heartbeating.

This would work only in the following situation:
- HMS server contains the new Hive change
- All of the Iceberg writers contain the new Iceberg change (the one which turns off the locks and adds the new parameters to the alter table call)

In every other situation, the old locking should be used

**Comment by dmgcodevil** [comment]
I see, it will be an optimistic locking:  

```
1.  set  properties  
2.  send a request to HMS
3. if failed ->  got to step  1
4. if succeded -> exit
```

**Comment by pvary** [comment]
In this regard, this will be the same as with normal locks

**Comment by dmgcodevil** [comment]
I still don't understand why we need locks if we have transactions and we can implement `optimistic locking` model.

**Comment by pvary** [comment]
With the apache/hive#3888 we can implement a solution which will handle failures the same way as the current one, without using locks, and depending on the `alter_table` to fail.
