### ISSUE TITLE
Question about usage of RewriteFile with Zorder Strategy

### ISSUE THREAD

**Issue by JMin824** [apache/iceberg#6373]
### Query engine

Iceberg:0.14.1
Spark:3.2.1

### Question

I have a question about the usage of Zorder, When I use rewritefile by zorder strategy. If I inserto some new rows into table, Do I need to use rewriteFile by Zorder again? Or the new rows can be insert into file by z-value?

**Comment by RussellSpitzer** [comment]
There are two main issues here,

1) If you only add enough data for a single file it is most likely not going to help if that single file has been ZOrdered all by itself. Z ordering as we have it currently implemented can only really help across multiple files being ZOrdered at the same time. This is similar to if you were just doing a normal sort, sorting a single file in isolation would not change the min/max stats of that file so it wouldn't help iceberg.

2) We currently do not have the ability to have ZOrder as a table defined sort order yet. There are tickets for that but currently if you wanted to take advantage of ZOrdering you would need to use rewrite again. Again like with normal sort, you would only gain the benefit from effected files.

**Comment by JMin824** [comment]
> * If you only add enough data for a single file it is most likely not going to help if that single file has been ZOrdered all by itself. Z ordering as we have it currently implemented can only really help across multiple files being ZOrdered at the same time. This is similar to if you were just doing a normal sort, sorting a single file in isolation would not change the min/max stats of that file so it wouldn't help iceberg.
> * We currently do not have the ability to have ZOrder as a table defined sort order yet. There are tickets for that but currently if you wanted to take advantage of ZOrdering you would need to use rewrite again. Again like with normal sort, you would only gain the benefit from effected files.

I find there is an option named rewrite-all in RewriteFile. if I use it in Zorder when I add enough data and some new files are created, what will happen? old files will not be rewritten? I guess it costs less than rewriting all file and maybe the query is a little slower than rewriting all file. thanks a lot for your reply

**Comment by RussellSpitzer** [comment]
Rewrite all rewrites all files, this means reading all data of the files, ordering them, then writing out new ordered files. If no predicates are selected this would completely rewrite the table.

**Comment by JMin824** [comment]
> Rewrite all rewrites all files, this means reading all data of the files, ordering them, then writing out new ordered files. If no predicates are selected this would completely rewrite the table.

Thanks a lot, I understand after your reply
