### ISSUE TITLE
Consider delete manifests for rewrite manifests

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#6375]
### Feature Request / Improvement

As per the code it looks like we are just considering data manifests for the rewrite. Should we also, support delete manifests to be rewritten into a bigger delete manifest file? 
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java#L214

I would like to know if there is any edge case around this or why it is not handled. If not, I can start working on this. 
cc: @RussellSpitzer, @szehon-ho, @aokolnychyi 

 

### Query engine

None

**Comment by szehon-ho** [comment]
Hi, sorry for delay, just saw this.  Was thinking about what happens when you combine two delete manifest with different sequence numbers, and I think this makes sense, unless I'm missing something.
