### ISSUE TITLE
Docs: Fix side menu disappears on small width resolution  

### ISSUE THREAD

**Issue by InvisibleProgrammer** [apache/iceberg#6381]
### Feature Request / Improvement

The side menu completely disappears at small width. I put some screen shots here as an example. 
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/1486749/206294258-c5aa4141-8863-4cc3-86cb-4192554b1de3.png">
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/1486749/206294346-43e3107f-f74c-468d-8eae-9b37dc4d7a33.png">

### Query engine

None

**Comment by RussellSpitzer** [comment]
I just noticed this, and the width doesn't have to be that small to get it to vanish, like 140 characters by my eyeball estimate?

**Comment by InvisibleProgrammer** [comment]
Yes, it is enough to put the site into the left half of an average MacBook screen.

**Comment by InvisibleProgrammer** [comment]
The issue is caused by that block in `iceberg-theme.css`: 
```css
@media screen and (max-width: 1280px) {
    div.sidebar { display: none; }  /* Hide the sidebar if the page is less than 1280px */
  }
  ```
  
I'm not a UI expert and also, I don't know if it is important to have great user experience on smaller screens (like mobile). 
If I remove  that line and shrink the screen, I get that: 
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1486749/206509082-066944e3-b61a-43c2-8bdf-c379f31c3327.png">


What do you think about that?
