### ISSUE TITLE
Python: Support Nessie catalog

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#6414]
### Feature Request / Improvement

very recently pyiceberg has added support for glue catalog (0.2.0).
We need to have support for Nessie catalog too just like hive, glue, REST catalogs.  
https://github.com/apache/iceberg/tree/master/python/pyiceberg/catalog

### Query engine

None

**Comment by ajantha-bhat** [comment]
I will wait a week or two to see if anyone wants to pick it up. If not, I will try to work on it.

**Comment by Fokko** [comment]
@ajantha-bhat I think you're good to pick this up if you're still interested :)

**Comment by ajantha-bhat** [comment]
> @ajantha-bhat I think you're good to pick this up if you're still interested :)

Sure. But I am occupied with partition stats and some internal work. Can't promise this in 0.4.0 :)

**Comment by s-akhtar-baig** [comment]
@Fokko, is this issue still up for grabs? If so then, can I work on it?

**Comment by ajantha-bhat** [comment]
I think @AlexMercedCoder and Jacopo Tagliabue is working on it. 

May be you can coordinate with them. 

more info: 
https://project-nessie.zulipchat.com/#narrow/stream/371193-dev/topic/contributing.20connection.20to.20PyIceberg/near/347547058

cc: @snazy, @dimas-b, @XN137

**Comment by snazy** [comment]
@s-akhtar-baig feel free to contribute :)

**Comment by AlexMercedCoder** [comment]
I have started on some of the steps regarding this which high-level would be:

- Update Pynessie to support the V2 endpoints
- Use Pynessie to create a catalog class for PyIceberg

My schedule has gotten busier so may be a bit before I can do anymore but here is some links to what I've done if anyone wants to continue from there.

- [Link to Pull request for new methods for V2 methods in pynessie](https://github.com/projectnessie/pynessie/pull/21)
- [Link to Unofficial V2 Client I made to help myself better understand the spec](https://pypi.org/project/nessiev2-unofficial/)

**Comment by Fokko** [comment]
Closing in favor of https://github.com/apache/iceberg-python/issues/19
