### ISSUE TITLE
Transactions for write operations

### ISSUE THREAD

**Issue by jiron12** [apache/iceberg#6418]
### Feature Request / Improvement

Is full transaction support anywhere on the roadmap? What I tried (SQL):

``` sql
START TRANSACTION;

insert into my_trino_schema.my_table
select 43, 'hello world 2', 12.12;

insert into my_trino_schema.my_table2
select 43, 'hello end of the world', 42.42 / 0; --<-- division by zero, leading to rollback

COMMIT WORK;
```

What I got (Error message):
```SQL Error [25]: Query failed (#20221213_145826_00039_it4nx): Catalog only supports writes using autocommit: iceberg```

Probably I'm naive here, but with time travelling already supported, this might not be a huge thing? Coming from the traditional SQL Systems, this is still missing.

### Query engine

Trino

**Comment by nastra** [comment]
@jiron12 given that the Trino Iceberg connector is developed outside of the Iceberg project, you might want to rather move this issue to https://github.com/trinodb/trino/issues
