### ISSUE TITLE
[Feature Proposal] Log Store in Iceberg

### ISSUE THREAD

**Issue by a49a** [apache/iceberg#6429]
### Feature Request / Improvement

This proposal aims to improve Iceberg's capability in real-time via importing a log store system. Streaming read data that are cached in a log store(Kafka).

Proposal document:
https://docs.google.com/document/d/1Zy4bbvSuN9ax7Tq4TuxL2vi4xQ4DR4wbR4QK5m69qQo/edit?usp=sharing

Code demo:
https://github.com/deadwind4/iceberg/tree/log-store

### Query engine

None

**Comment by bitsondatadev** [comment]
@bryanck is there any overlap here with the kafka connect sink?

**Comment by bryanck** [comment]
I don't believe so. With the Kafka Connect sink, all files written and commits performed are logged as messages on a control topic. That acts as a log for write activity (at file-level grain), so a downstream process could consume from that without requiring an addition log.
