### ISSUE TITLE
Python: Support for static table

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#6430]
### Feature Request / Improvement

In Java we have the StaticTableOperations: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/StaticTableOperations.java That allows the user to directly load a table from a metadata location. This static table does not support any modifications to the table. I think this would be valuable for PyIceberg as well, as this will enable users to easily pull in data, or share datasets.

### Query engine

None

**Comment by djouallah** [comment]
FWIW, BigQuery has a *read only* implementation that uses the metadata location.
