### ISSUE TITLE
Views on top of Iceberg tables

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#644]
Is there a support/plan to create views on top of multiple tables?

**Comment by asheeshgarg** [comment]
I have created a hive view using spark.sql on top of two iceberg tables?
The view get created but while querying the data on the view not able to read the data.

I tried Presto client and able to create the view and able to read the data using Presto. But the same view is not queryable using spark.
I tried loading the data using spark.read.format("iceberg") but it fails as it doesn't have the iceberg type defined in the HiveMetastore table properties.

**Comment by SreeramGarlapati** [comment]
@aokolnychyi @rdblue @rdsr - would you folks know - if there is a plan or any ongoing discussion on natively support Views in [Iceberg Table Spec](https://iceberg.apache.org/spec/)?

**Comment by rdblue** [comment]
I think it would be great to support views of some kind in Iceberg catalogs. We do that in our internal branch. That said, it is a bit tangental to the goals of the Iceberg project itself so I'd want to make sure the broader community is interested.

Also, @jzhuge is leading the way to add a `ViewCatalog` interface to Spark to support this sort of thing. We'd need that in order to use these from Spark.

**Comment by jzhuge** [comment]
Yeah, we have an internal "common view" design that supports both Spark and Presto. The common view metadata format and implementation borrow heavily from Iceberg, including schema, data type, manifest, snapshot, isolation, etc. If the community is interested, we will be happy to contribute it to the Iceberg project.

In Spark, our Iceberg catalog serves as TableCatalog, ViewCatalog ([Spark SPIP](https://docs.google.com/document/d/1XOxFtloiMuW24iqJ-zJnDzHl2KMxipTjJoxleJFz66A/edit?usp=sharing)), and FunctionCatalog simultaneously.

**Comment by rymurr** [comment]
@jzhuge We would be interested in views. I would be happy to help where I can to get your impl into iceberg.

**Comment by jzhuge** [comment]
Great! The first step is to get ViewCatalog API into Spark.

**Comment by SreeramGarlapati** [comment]
@jzhuge - we are interested & am happy to help too.

**Comment by rymurr** [comment]
From what I can tell the last discussion about the above SPIP on the spark community was >6 months ago. Any idea of when that will land in Spark? Can we move forward on this proposal in parallel? I am happy to put a straw man document together,

**Comment by melin** [comment]
> Great! The first step is to get ViewCatalog API into Spark.

very interested in view.  can provide patch？ thanks

**Comment by melin** [comment]
> In Spark, our Iceberg catalog serves as TableCatalog, ViewCatalog ([Spark SPIP](https://docs.google.com/document/d/1XOxFtloiMuW24iqJ-zJnDzHl2KMxipTjJoxleJFz66A/edit?usp=sharing)), and FunctionCatalog simultaneously.

Spark 3.2 Support FunctionCatalog

**Comment by wilsonpenha** [comment]
Hello there
When this PR will be merged and we will be able to create and query views from iceberg tables?

**Comment by felixYyu** [comment]
@jzhuge interested and happy to help too.

**Comment by emkornfield** [comment]
What is the current state of Views, in general, it seems like there has been development effort here but I didn't see a vote on the mailing list officially adopting the specification (could just be my poor search abilities).  Is the specification formally ratified?  If not, what are the milestones before a vote happens?

**Comment by vungle-wesleygoi** [comment]
this would be very useful for DBT
