### ISSUE TITLE
Provide Puffin reader API allowing read without decompression

### ISSUE THREAD

**Issue by findepi** [apache/iceberg#6443]
### Feature Request / Improvement

When a query engine wants to add new stats to a snapshot that already has some stats, it currently needs to merge existing stats file' blobs with new ones.  

Currently, the only Puffin reader API for reading blobs will decompress them implicitly.
The application merging stats probably doesn't know much about these old stats, so also doesn't know whether they should be compressed, so it should preserve the compression. Thus it will want to re-compress them again.

- This process is wasteful: redundant decompression and compression
- Also, it is not possible to implement it in a future-proof manner: application can preserve compression only for the puffin codecs it was built with

### Query engine

None

**Comment by ajantha-bhat** [comment]
> When a query engine wants to add new stats to a snapshot that already has some stats, it currently needs to merge existing stats file' blobs with new ones.

Can you please explain about when a "query engine wants to add new stats to a snapshot that already has some stats" ? 

Aren't stats computed once for the snapshot (using ANALYZE command). Are we planning that each column can generate stats independently?

**Comment by findepi** [comment]
@ajantha-bhat there may be many different types of stats, and stats can be computed for subset of columns.
