### ISSUE TITLE
flink  streaming query  Cannot get a client from a closed pool

### ISSUE THREAD

**Issue by MurderWind** [apache/iceberg#6455]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

flink: 1.16.0

 - Start scheduling with scheduling strategy，  i get errors when Job Flink Streaming Job running . of course . i use                  catalog-impl is  "org.apache.iceberg.jdbc.JdbcCatalog"  
 
40601 [SourceCoordinator-Source: Summer_Iceberg] ERROR org.apache.iceberg.flink.source.enumerator.ContinuousIcebergEnumerator  - Failed to discover new splits
java.lang.IllegalStateException: Cannot get a client from a closed pool
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:56)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
	at org.apache.iceberg.jdbc.JdbcTableOperations.getTable(JdbcTableOperations.java:228)
	at org.apache.iceberg.jdbc.JdbcTableOperations.doRefresh(JdbcTableOperations.java:74)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97)
	at org.apache.iceberg.BaseTable.refresh(BaseTable.java:68)
	at org.apache.iceberg.flink.source.enumerator.ContinuousSplitPlannerImpl.planSplits(ContinuousSplitPlannerImpl.java:73)
	at org.apache.iceberg.flink.source.enumerator.ContinuousIcebergEnumerator.discoverSplits(ContinuousIcebergEnumerator.java:95)
	at org.apache.flink.runtime.source.coordinator.ExecutorNotifier.lambda$notifyReadyAsync$5(ExecutorNotifier.java:130)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by stevenzwu** [comment]
@MurderWind if you can reproduce it in IDE, you may be able to troubleshoot it with debugger.

`IcebergSource` should use a new thread pool 
```
  public ContinuousSplitPlannerImpl(Table table, ScanContext scanContext, String threadName) {
    this.table = table;
    this.scanContext = scanContext;
    this.isSharedPool = threadName == null;
    this.workerPool =
        isSharedPool
            ? ThreadPools.getWorkerPool()
            : ThreadPools.newWorkerPool(
                "iceberg-plan-worker-pool-" + threadName, scanContext.planParallelism());
  }
```

As the threadName is non-null passed in from `IcebergSource`
```
    // Ideally, operatorId should be used as the threadPoolName as Flink guarantees its uniqueness
    // within a job. SplitEnumeratorContext doesn't expose the OperatorCoordinator.Context, which
    // would contain the OperatorID. Need to discuss with Flink community whether it is ok to expose
    // a public API like the protected method "OperatorCoordinator.Context getCoordinatorContext()"
    // from SourceCoordinatorContext implementation. For now, <table name>-<random UUID> is used as
    // the unique thread pool name.
    return lazyTable().name() + "-" + UUID.randomUUID();
  }
```

**Comment by MurderWind** [comment]
> // Ideally, operatorId should be used as the threadPoolName as Flink guarantees its uniqueness
>     // within a job. SplitEnumeratorContext doesn't expose the OperatorCoordinator.Context, which
>     // would contain the OperatorID. Need to discuss with Flink community whether it is ok to expose
>     // a public API like the protected method "OperatorCoordinator.Context getCoordinatorContext()"
>     // from SourceCoordinatorContext implementation. For now, <table name>-<random UUID> is used as
>     // the unique thread pool name.

actually. i  i found the bug  when org.apache.iceberg.jdbc.JdbcTableOperations#connections  connections properties closed turn true  ,it is happened.  but i don't find why closed  turns true.

**Comment by MurderWind** [comment]
> @MurderWind if you can reproduce it in IDE, you may be able to troubleshoot it with debugger.
> 
> `IcebergSource` should use a new thread pool
> 
> ```
>   public ContinuousSplitPlannerImpl(Table table, ScanContext scanContext, String threadName) {
>     this.table = table;
>     this.scanContext = scanContext;
>     this.isSharedPool = threadName == null;
>     this.workerPool =
>         isSharedPool
>             ? ThreadPools.getWorkerPool()
>             : ThreadPools.newWorkerPool(
>                 "iceberg-plan-worker-pool-" + threadName, scanContext.planParallelism());
>   }
> ```
> 
> As the threadName is non-null passed in from `IcebergSource`
> 
> ```
>     // Ideally, operatorId should be used as the threadPoolName as Flink guarantees its uniqueness
>     // within a job. SplitEnumeratorContext doesn't expose the OperatorCoordinator.Context, which
>     // would contain the OperatorID. Need to discuss with Flink community whether it is ok to expose
>     // a public API like the protected method "OperatorCoordinator.Context getCoordinatorContext()"
>     // from SourceCoordinatorContext implementation. For now, <table name>-<random UUID> is used as
>     // the unique thread pool name.
>     return lazyTable().name() + "-" + UUID.randomUUID();
>   }
> ```

actually. i i found the bug when org.apache.iceberg.jdbc.JdbcTableOperations#connections connections properties closed turn true ,it is happened. but i don't find why closed turns true.

**Comment by MurderWind** [comment]
> @MurderWind if you can reproduce it in IDE, you may be able to troubleshoot it with debugger.
> 
> `IcebergSource` should use a new thread pool
> 
> ```
>   public ContinuousSplitPlannerImpl(Table table, ScanContext scanContext, String threadName) {
>     this.table = table;
>     this.scanContext = scanContext;
>     this.isSharedPool = threadName == null;
>     this.workerPool =
>         isSharedPool
>             ? ThreadPools.getWorkerPool()
>             : ThreadPools.newWorkerPool(
>                 "iceberg-plan-worker-pool-" + threadName, scanContext.planParallelism());
>   }
> ```
> 
> As the threadName is non-null passed in from `IcebergSource`
> 
> ```
>     // Ideally, operatorId should be used as the threadPoolName as Flink guarantees its uniqueness
>     // within a job. SplitEnumeratorContext doesn't expose the OperatorCoordinator.Context, which
>     // would contain the OperatorID. Need to discuss with Flink community whether it is ok to expose
>     // a public API like the protected method "OperatorCoordinator.Context getCoordinatorContext()"
>     // from SourceCoordinatorContext implementation. For now, <table name>-<random UUID> is used as
>     // the unique thread pool name.
>     return lazyTable().name() + "-" + UUID.randomUUID();
>   }
> ```

i found the issues  .


`   protected JdbcTableOperations(
            JdbcClientPool dbConnPool,
            FileIO fileIO,
            String catalogName,
            TableIdentifier tableIdentifier,
            Map<String, String> catalogProperties) {
        this.catalogName = catalogName;
        this.tableIdentifier = tableIdentifier;
        this.fileIO = fileIO;
        this.connections = dbConnPool;
        this.catalogProperties = catalogProperties;
    }`
the dbConnPool has initialize.  but  org.apache.iceberg.jdbc.JdbcCatalog#close   this.closed =true .  when  org.apache.iceberg.ClientPoolImpl#get          Preconditions.checkState(!this.closed, "Cannot get a client from a closed pool");

**Comment by xuzhiwen1255** [comment]
I found the cause of the problem and tried to solve it.
