### ISSUE TITLE
Allow specifying data file format in RewriteDataFiles

### ISSUE THREAD

**Issue by peay** [apache/iceberg#6464]
### Feature Request / Improvement

A common use case for streaming pipelines is to be able to write small Avro data files in micro-batch fashion, and then periodically compact those into a few Parquet data files.

It'd be great if `RewriteDataFiles` had an [option](https://iceberg.apache.org/javadoc/1.1.0/org/apache/iceberg/actions/RewriteDataFiles.html#field.summary) to rewrite data files in a different data file format from that in the table properties to support such a workflow. This would allow a table configured to write Avro by default, but running compactions actions to Parquet.

A workaround today is to flip this around, by configuring a table with Parquet format, and having writers explicitly request Avro data files (e.g., with Spark, by passing the [`write-format`](https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java#L27) option explicitly). However, it'd be great to have the option to handle this in `RewriteDataFiles` instead to keep the writers agnostic to such details. 

### Query engine

None

**Comment by hililiwei** [comment]
We happen to have an internal implementation. I have raised a PR #6470 . If you are interested in it, can you review it? Thx.
