### ISSUE TITLE
Iceberg not rolling files to hdfs while flink streaming job running 

### ISSUE THREAD

**Issue by MohamedAdelHsn** [apache/iceberg#6465]
### Query engine

Flink SQL 

### Question

Hello, 
I am using Flink ssql to stream data from cdc to hive table and hdfs 
i create create flink tables one as source table kafka and the other hive table 
while streaming  job  running i can not see data rolled in hdfs and hive table  if i canceled flink job i can see data in hdfs / hive table 

Thanks for your feedback ASAP.

**Comment by SHuixo** [comment]
@MohamedAdelHsn Can you provide more details about the code?

**Comment by luoyuxia** [comment]
is checkpoint enabled?

**Comment by MohamedAdelHsn** [comment]
this code is used 

CREATE TABLE flink_table_source (
id BIGINT
,data VARCHAR
) WITH (
'connector' = 'kafka'
,'topic' = 'flink'
,'properties.bootstrap.servers' = 'localhost:9092'
,'properties.group.id' = 'user_log_x'
,'scan.startup.mode' = 'earliest-offset'
,'format' = 'json'
);

this table are using default_catalog and default_database and when i start publish data to kafka topic it is working fine with
select * from flink_table_source;

i want to insert data into iceberg hive table from that table and i am facing an issue with below sql

insert into hive_iceberg_table select * from flink_table_source;

my hive_iceberg_table created as below

CREATE CATALOG ice WITH (
'type'='iceberg',
'catalog-type'='hive',
'uri'='thrift://localhost:9083',
'clients'='5',
'property-version'='2',
'warehouse'='hdfs://localhost:9000/user/hive/warehouse'
);

USE ice;

CREATE DATABASE iceberg;

USE iceberg;

/*hive table definition */
CREATE TABLE ice.ice.user_log_sink (
user_id INT,
item_id STRING,
PRIMARY KEY (user_id) NOT ENFORCED
)WITH(
'engine.hive.enabled' = 'true',
);

**Comment by MohamedAdelHsn** [comment]
@SHuixo @luoyuxia

**Comment by SHuixo** [comment]
How do you write the context configuration code for the flink execution environment? Like this：

```
final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

env.enableCheckpointing(60000, EXACTLY_ONCE);
env.setStateBackend(new HashMapStateBackend());

final CheckpointConfig checkpointConfig = env.getCheckpointConfig();
checkpointConfig.setMinPauseBetweenCheckpoints(500);
checkpointConfig.setCheckpointTimeout(60000);
checkpointConfig.setTolerableCheckpointFailureNumber(2);
checkpointConfig.setMaxConcurrentCheckpoints(1);
checkpointConfig.enableUnalignedCheckpoints();
checkpointConfig.enableExternalizedCheckpoints(
        CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);
checkpointConfig.setCheckpointStorage(path);
.....
```

**Comment by MohamedAdelHsn** [comment]
i am using sql client so i go through flink and iceberg document and i can not found something like this sorry can you explain more i am not expert in flink

**Comment by hililiwei** [comment]
> is checkpoint enabled?

Your current problem is that you have not found any data in the iceberg table?

As mentioned above, please confirm whether checkpoint is enabled. If you do not, the data will not be commited to the iceberg table.

When Flink writes data, it will roll the file when the size of the file being written is larger than the max target file size value, or  when Flink performs a checkpoint.

**Comment by MohamedAdelHsn** [comment]
Thank you all ,it is working now after enabling checkpoints in flink
