### ISSUE TITLE
Support for predicate pushdown on s3

### ISSUE THREAD

**Issue by LionTao** [apache/iceberg#6481]
### Query engine

None, I'm using Java API

### Question

Currently, when reading files, iceberg utilizes vectorized reading to read files.
But when a filter is applied, we can use the s3 select API to reduce the file size needed to transfer. That will reduce time and cost.
According to s3 documents and minio documents, parquet is the only supported format for iceberg.

Any guides or advice on implementing this feature?

**Comment by RussellSpitzer** [comment]
Could you elaborate a bit more on what you would like to do here?

**Comment by LionTao** [comment]
Hi, thank you for your reply, and merry christmas🎄

> Could you elaborate a bit more on what you would like to do here?

**I am building a distributed computing engine for trajectory data based on Faas service, Dapr and Iceberg. I want to minimize the network IO. So I think using S3-Select may be helpful.**

After digging around the code, I found currently the FileIO API relies on Stream to process content. But the S3-select response seems to be different. 
So I think if we need to utilize the S3-Select ability, we need some new mechanism to deal with Input files.
Also, this new mechanism may not be supported by all storage, so it could be AWS-specific. I'm not sure whether it is ideal for the extensibility of Iceberg.
