### ISSUE TITLE
How can table created using Spark DDL be used in Flink's upsert operation?

### ISSUE THREAD

**Issue by e-rudic** [apache/iceberg#6488]
### Query engine

Spark
Flink

### Question

Hello,

according to the Iceberg documentation for Flink to be able to perform upsert operation on the table primary key needs to be defined like this:
` PRIMARY KEY(`id`) NOT ENFORCED
`

However Spark DDL does not support this kind of syntax. Furthermore, as stated in [this comment](https://github.com/apache/iceberg/issues/5069#issuecomment-1215041789) primary keys as stored as equality keys and used in upsert operation. [Specs](https://iceberg.apache.org/spec/#manifests) define that equality_ids are part of the manifest files and not a table property.

How can one set table's equality keys using Spark so that Flink can be able to upsert data into it?

**Comment by felixYyu** [comment]
ref to [FLINK-21634](https://issues.apache.org/jira/browse/FLINK-21634)

**Comment by luoyuxia** [comment]
After we upgrade Flink to Flink 1.17 and implement the newly added interfaces. 
We should have aibility to add primary key to a table created by `Spark` via `Flink`

**Comment by e-rudic** [comment]
Thank you very much! Comments answer my question so I'm closing this.
