### ISSUE TITLE
Improve Test Coverage of RowGroupFilter Code with Nans

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#6518]
### Feature Request / Improvement

Currently bounds checking with NaN's in file metrics (for parquet) is essentially untested, I added a small set of tests in #6517 but we should probably have a full range of checks. The tests also need to be parameterized since for Parquet we can never correctly skip a file which contains NaN but this may not be the case for ORC.

Specifically we should have a set of tests in TestMetricsRowGroupFilter or TestMetricsRowGroupFilterTypes which covers double and float columns which contain NaN as well as non-nan values. 

### Query engine

Other

**Comment by lvyanquan** [comment]
Willing to do this if no one else asks

**Comment by youngxinler** [comment]
I have submitted PR. #6554  @RussellSpitzer  can you help with the review?
