### ISSUE TITLE
iceberg-1.1.0 - flink sql create hive catalog error

### ISSUE THREAD

**Issue by zqzhen091** [apache/iceberg#6522]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

I download iceberg-flink-runtime-1.16-1.1.0.jar from [https://iceberg.apache.org/releases/]()
when i create a hive catalog on flink sql client, it comes a problem.

the SQL is:
```sql
CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://localhost:9083',
  'clients'='5',
  'property-version'='1'
);
```
error info:
```shell
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassCastException: org.apache.iceberg.hive.HiveCatalog cannot be cast to org.apache.iceberg.catalog.Catalog

**Comment by leichangqing** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/36058877/219867698-c745b74b-11cf-463f-8b37-89eb14d9f529.png">

# HADOOP_HOME is your hadoop root directory after unpack the binary package.
export HADOOP_CLASSPATH=`$HADOOP_HOME/bin/hadoop classpath`

# Start the flink standalone cluster
/app/flink/bin/sql-client.sh embedded \
-j '/app/flink/lib/iceberg-flink-runtime-1.16-1.1.0.jar' \
-j '/app/flink/lib/flink-sql-connector-hive-3.1.2_2.12-1.16.1.jar' \
shell
~       

java.lang.ClassCastException: org.apache.iceberg.hive.HiveCatalog cannot be cast to org.apache.iceberg.catalog.Catalog

**Comment by luoyuxia** [comment]
@leichangqing Is there any jar related to iceberg been put in `FLINK_HOME/lib`?
