### ISSUE TITLE
Python: Support DynamoDB catalog

### ISSUE THREAD

**Issue by marsupialtail** [apache/iceberg#6541]
### Query engine

PyIceberg -- I just want to read the metadata

### Question

Say I got a dynamodb table prodiceberg_metastore as my catalog.

How I read it in PyIceberg? Can someone give some instructions please?

**Comment by Fokko** [comment]
Thanks for creating this ticket @marsupialtail. Currently, PyIceberg only supports Hive, REST, and Glue. DynamoDB would be a great addition and PRs are welcome :)

**Comment by arminnajafi** [comment]
Hi Fokko,

This is Armin. I've worked on integration of Iceberg with Athena and also have had some minor contributions to Iceberg open source. I like to take this task and implement it with your help and guidance.

**Comment by Fokko** [comment]
Hi @arminnajafi Please do, and happy to help!

**Comment by jackye1995** [comment]
@arminnajafi thanks for taking this, also let me know how I could help, looking forward to the PR!

**Comment by arminnajafi** [comment]
Thanks Fokko and Jack. I'll take a close look at it this weekend and will reach out for help. 

Looking forward to working with you. 
:)

**Comment by arminnajafi** [comment]
- Read https://py.iceberg.apache.org/ cover to cover
- Set up the repo in IntelliJ with a Poetry env

**Comment by arminnajafi** [comment]
However I realized when running `make test` on mainline branch `test_missing_uri` unit test fails. 

Here is the PR for the unit test fix:
https://github.com/apache/iceberg/pull/6607
