### ISSUE TITLE
Consider introducing repartitioning in MergeIntoIcebergTable

### ISSUE THREAD

**Issue by rbalamohan** [apache/iceberg#6604]
### Apache Iceberg version

0.14.0

### Query engine

Spark

### Please describe the bug 🐞

Without repartitioning, there is a chance of creating way too many files in merge operation. It will be good to introduce repartitioning in MergeIntoIcebergTable. This should help in reducing the number of files that are created at the end of the job. Kind of similar to "hive.optimize.sort.dynamic.partition.threshold" parameter.

**Comment by RussellSpitzer** [comment]
This should be already covered with the write distribution mode code for Spark. We did mention in the last sync that we should default to a distribution rather than require users to set the property. Currently the default is nine

**Comment by RussellSpitzer** [comment]
Example tests
https://github.com/apache/iceberg/blob/dbb8a404f6632a55acb36e949f0e7b84b643cede/spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java


Application in write builder
https://github.com/apache/iceberg/blob/8c6adf6e5e17603025d23b2012aa576c071ff269/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java#L204-L276

Properties
https://github.com/apache/iceberg/blob/8c6adf6e5e17603025d23b2012aa576c071ff269/core/src/main/java/org/apache/iceberg/TableProperties.java#L299-L302
https://github.com/apache/iceberg/blob/8c6adf6e5e17603025d23b2012aa576c071ff269/core/src/main/java/org/apache/iceberg/TableProperties.java#L322
https://github.com/apache/iceberg/blob/8c6adf6e5e17603025d23b2012aa576c071ff269/core/src/main/java/org/apache/iceberg/TableProperties.java#L330
https://github.com/apache/iceberg/blob/8c6adf6e5e17603025d23b2012aa576c071ff269/core/src/main/java/org/apache/iceberg/TableProperties.java#L351


We probably want to default all of these to something other than none. In 3.3 the adaptive skew handling is good enough to avoid most OOM issues, I think Hash is probably fine for every table that doesn't have a global ordering set.
