### ISSUE TITLE
Bug with Branch Transactions

### ISSUE THREAD

**Issue by amogh-jahagirdar** [apache/iceberg#6632]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

Creating this issue for awareness, was discussing with @rdblue seems like there's a bug in https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L415

when committing the transaction, currentSnapshotId is set to current's main snapshot id but this is incorrect if a transaction is being committed to a branch

**Comment by amogh-jahagirdar** [comment]
I'm working on a fix for this @jackye1995 could you assign this to me?

**Comment by jackye1995** [comment]
Sure, assigned!

**Comment by amogh-jahagirdar** [comment]
Since the fix for this is merged, I'm going to close this issue
