### ISSUE TITLE
Unclear messaging about Glue catalog locking

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#6636]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

Based on reader feedback, the message presented in https://iceberg.apache.org/docs/latest/aws/#optimistic-locking, specifically the sentence "Users can update the table, but only if the version id on the server side has not changed" makes readers feel that Iceberg cannot retry and resolve conflict for Glue catalog. We should make that section more clear.

**Comment by bitsondatadev** [comment]
@jackye1995 is this completed?
