### ISSUE TITLE
Support for global shadow writes + logs

### ISSUE THREAD

**Issue by holdenk** [apache/iceberg#6652]
### Feature Request / Improvement

For job migration testing I'd really like to be able to set an environment variable that indicates all of the commits should be staged and logged for comparison.

### Query engine

None

**Comment by holdenk** [comment]
Actually I think we could do this with a small extension to Icebergs WAP so that the logs contain the table names.

**Comment by holdenk** [comment]
hmm more poking I can probably do this with an Iceberg listener. Closing for now.

**Comment by RussellSpitzer** [comment]
This is also kind of similar to Nessie's branching idea, I think Iceberg is also moving towards having some first level branching support.

**Comment by amogh-jahagirdar** [comment]
Yeah +1 to what @RussellSpitzer mentioned, we've recently added support for writes to branches in Iceberg itself and if I understand your use case correctly that's actually a perfect application of branching. I'm working on a separate page in documentation for branching and tagging, after I publish the initial PR I'll add you @holdenk for review and you can also help confirm if branching would help facilitate your use case?

**Comment by holdenk** [comment]
Awesome thanks @amogh-jahagirdar :)
