### ISSUE TITLE
[Nessie] Nessie should store his table in the namespace location if he can

### ISSUE THREAD

**Issue by tprelle** [apache/iceberg#6675]
### Feature Request / Improvement

In order to mimic HMS behavior to facilitate migration, Nessie should store his table in the namespace location if the namespace have it.

Currently Nessie store it on the default warehouse location so it's impossible without specifing the location directly on the create table to store it somewhere else.

This feature will facilitate admin life so he can create namespace where he want then user just use the same behavior than in Hive.

### Query engine

None

**Comment by ajantha-bhat** [comment]
Sounds reasonable to me. I will take a look at the PR today.
