### ISSUE TITLE
[DOC] Incorrect mention of engines tab

### ISSUE THREAD

**Issue by zjffdu** [apache/iceberg#6693]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

There's no engines tab (maybe it exists before).
![image](https://user-images.githubusercontent.com/164491/215308439-1b315674-f982-4b92-9b12-165455aa65ad.png)

**Comment by wypoon** [comment]
I suggest changing "You can also view documentations of using Iceberg with other compute engine under the Engines tab." to "You can also view documentation of using Iceberg with other compute engines under each engine (e.g., Flink, Hive)."
