### ISSUE TITLE
Iceberg doesn't read credentials from WebIdentityTokenCredentialsProvider when using with AWS

### ISSUE THREAD

**Issue by cw-pradyumna** [apache/iceberg#6718]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I am running spark on EKS. When I use a service account in spark on kubernetes and attach a role to it in AWS, that service account is able to access AWS resources through the AWS WebIdentityTokenCredentialsProvider. But in case of Iceberg, it doesn't seem to be doing so.

When I passed tokens to it though the following properties, I was able to write to s3, without any issue. 
```
spark.sql.catalog.my_catalog.s3.secret-access-key
spark.sql.catalog.my_catalog.s3.access-key-id
spark.sql.catalog.my_catalog.s3.session-token
```

**Comment by stevenzwu** [comment]
@cw-pradyumna I think this is the same issue as issue #6715. I am closing this one as duplicate. feel free to repopen it if you think otherwise.

**Comment by cw-pradyumna** [comment]
> @cw-pradyumna I think this is the same issue as issue #6715. I am closing this one as duplicate. feel free to repopen it if you think otherwise.

@stevenzwu , ok Steven, if it's the same then no problem. I had read through #6715 but I thought it was something else, so I made this issue.

**Comment by stevenzwu** [comment]
@cw-pradyumna can you try the system property that I mentioned in the other issue?
```
-Dsoftware.amazon.awssdk.http.service.impl=software.amazon.awssdk.http.apache.ApacheSdkHttpService
```

also can you verify if the runtime classpath loaded both url-connection-client and apache-httpclient jars?
