### ISSUE TITLE
Add namespace support in Iceberg Catalog

### ISSUE THREAD

**Issue by jerryshao** [apache/iceberg#672]
To better adapt Spark's DSv2 namespace interface, Iceberg should add namespace related API support in Catalog.

**Comment by aokolnychyi** [comment]
@jerryshao, do you mean methods that will be needed to implement `SupportsNamespaces`?

**Comment by jerryshao** [comment]
Yes, that's what I mean.

**Comment by aokolnychyi** [comment]
Sounds like a good idea to me!
