### ISSUE TITLE
How to detect if the partition's data is ready to consume

### ISSUE THREAD

**Issue by 0xffmeta** [apache/iceberg#6725]
### Question

For the downstream of the iceberg table, how to detect if the daily or hourly partition is ready to consume? 
We used to leverage `_SUCCESS` file for the dection, and now we can query the partition metadata of the iceberg table, but just wonder if there is any lightweight way, e.g. `_SUCCESS` file sensor?

**Comment by RussellSpitzer** [comment]
There is no such thing in iceberg. If there is data in a partition the commit has suceeded. So if for example you do a Spark Query and there is data in the partition, that means your operation inserting into that partition finished. If you have multiple operations appending into the same partition that would require application logic to differentiate.

**Comment by 0xffmeta** [comment]
Do you think we can add one configuration to allow iceberg output the `_SUCCESS` file to external path? For most of the use cases in our company, we need to listen to the sensor file to trigger the downstream jobs in airflow. Otherwise, we need to connect to the query engine for the partition info. 
So I think it might be a common case for other users as well.

**Comment by RussellSpitzer** [comment]
That doesn't make sense to me. Would we add success on just the first time? What happens on subsequent modifications?

It's way simpler to just use the Java api(if you don't want to use a full engine) to see if there are any files for a given partition. 

In Iceberg we also don't require files to be in any specific directory, so for example with object store location provider we end up with basically every file in its own path. Where would we keep the success file then? Again the source of truth for an iceberg table is only known by reading the current metadata.json so the Java APIs are the way to go if you don't want to use Spark or trino. 

Or if you want you can just listen for changes in the catalog, whenever metadata location properly has changed, you know the table has been committed to.

**Comment by 0xffmeta** [comment]
For our case, we just need to add success file for the first time to let the downstream know that the daily or hourly partition is ready to consume. On subsequent update, we leverage the timestamp of the success file to dertermain the downstream behaviour. 

Agree that we should maintian only one source of truth, and it's a good idea to use the Java api to fetch the information. 

Many thanks for your explanation!
