### ISSUE TITLE
Improving Scala Checkstyle/Spotless configurations

### ISSUE THREAD

**Issue by amogh-jahagirdar** [apache/iceberg#6736]
This is a tracking issue based on the [discussion](https://github.com/apache/iceberg/pull/6637#discussion_r1095386173) . Scala checkstyle doesn't catch some styling issues around spacing, I think we should revisit the checkstyle configurations just to make reviewer's lives a bit easier. Also seems like [Spotless](https://github.com/diffplug/spotless) also supports Scala so maybe we can leverage that as well although I haven't done a deeper analysis.

**Comment by jackye1995** [comment]
@amogh-jahagirdar do you want to take this?

**Comment by amogh-jahagirdar** [comment]
Sure @jackye1995 feel free to assign to me!

**Comment by jackye1995** [comment]
Thanks!

**Comment by jackye1995** [comment]
And I would +1 on spotless if that's available, to make the experience consistent with Java
