### ISSUE TITLE
Integrate CRT with Iceberg S3 client

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#6739]
### Feature Request / Improvement

Amazon S3 recently officially launched its common runtime (CRT) client, which claims 85% improvement in GET and 71% improvement in PUT. We are already on SDK v2 and should start integration with this.

More info: https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/

### Query engine

None

**Comment by chandanagp1** [comment]
Interested. Can I work on this issue?

**Comment by jackye1995** [comment]
Thanks, assigned!

**Comment by aokolnychyi** [comment]
Sounds really promising!

**Comment by jackye1995** [comment]
Assigning to me for now, working with Atreya for the async client integration, and then enable CRT from that.

**Comment by map9000** [comment]
Hi @jackye1995 do you have any updates as to progress?

**Comment by jivanic-demystdata** [comment]
Hi everyone,

What's the status of this issue, please?

**Comment by guizmaii** [comment]
Hi everyone,

What's the status of this issue, please?
Can we re-open the issue maybe? It seems to be quite an interesting improvement

_Edit 02 June 2025:_ 
Re-opened the issue here: https://github.com/apache/iceberg/issues/13210
