### ISSUE TITLE
S3FileIO Can Create Non-Posix Paths

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#6758]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

An interesting thing we ran into:

Our FileIo API contains this method

https://github.com/apache/iceberg/blob/c07f2aabc0a1d02f068ecf1514d2479c0fbdd3b0/api/src/main/java/org/apache/iceberg/io/FileIO.java#L44-L46

Which uses a "String" as the Path for creating a new file reference. Now in general this is not an issue but there are some edge cases here. For example, S3FileIO doesn't enforce posix rules when creating paths or directories (since neither of those really exist in S3.) This means we the two following locations are actually different:

1. foo//bar/file
2. foo/bar/file

But within posix systems these two should refer to the exact same thing. See https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_266

> A pathname may optionally contain one or more trailing slashes. Multiple successive slashes are considered to be the same as one slash.

Which we can see holds true in Java's Path class. 

```scala
scala> import java.nio.file.Paths
import java.nio.file.Paths

scala> Paths.get("/foo//bar/file").equals(Paths.get("/foo/bar/file"))
res29: Boolean = true
```

Or more importantly in Hadoop's Path Class
```scala
scala> val p = new Path("foo/bar//bazz")
p: org.apache.hadoop.fs.Path = foo/bar/bazz

scala> p.toUri
res38: java.net.URI = foo/bar/bazz
```

This leads to an issue when a table is written to by S3FileIO but then read with HadoopFileIO. HadoopFileIO cannot read from the special `foo//bar/file` path because this isn't a valid posix path. This means if for some reason we end up generating double slashes in our path's metadata_location (or other paths) when using S3FileIO those files will be inaccessible if S3FileIO is swapped with HadoopFileIO.

I think in this case we should probably add to the spec that all files (and paths) must comply with posix standards.

**Comment by RussellSpitzer** [comment]
@amogh-jahagirdar + @jackye1995 Do you have any thoughts on this?

**Comment by jackye1995** [comment]
So internally we have a fix, where we extend Hadoop `Path` to work with double slash instead of the posix standard, and use that Path object for Iceberg for the specific `FileSystem` implementation. But for existing tables written with //, it seems like a case that has to continue to be supported in this way.

But I agree it would be good to enforce this across all FileIOs, and just make sure removing trailing slash is done whenever needed. I am not sure if it has to be in the spec, given it has been like this for a pretty long time.

**Comment by RussellSpitzer** [comment]
https://github.com/apache/iceberg/blob/cecb10bb8ab0458fb3f6a650692a8e432f08cbd2/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L226 I think it makes sense to do the remove trailing slash here. I'm not sure why we only do it for custom metadata locations

**Comment by RussellSpitzer** [comment]
For the Spec I was just considering something like "path" a path is a POSIX normalized path

**Comment by amogh-jahagirdar** [comment]
Mostly agree with @jackye1995 here. I think at minimum, we for sure should remove trailing slash when writing any file that's part of the Iceberg table. 

As for the spec change, I think it's good to enforce at the spec level. Even though our systems will need to enforce backwards compatibility for the files written with double slash, at least for future Iceberg releases we can establish the guarantee. Standardizing file paths reduces this complexity of having to understand nuances of each FileIO implementation. Iceberg users would be confident that all FileIO implementations follow the same pattern

**Comment by RussellSpitzer** [comment]
This is also an issue for data files here
https://github.com/apache/iceberg/blob/223177faf955bd8f11864477da16013cf5d7cc75/core/src/main/java/org/apache/iceberg/LocationProviders.java#L126-L135

**Comment by RussellSpitzer** [comment]
@findepi Is this an issue with Trino's file IO rules? Or does it always require all paths be Posix compliant? I know you have special S3 IO code as well

**Comment by findepi** [comment]
@RussellSpitzer thanks for the ping, but honestly I do not know.
I guess by non-POSIX you mean handling of double-slashes. For that @electrum @ebyhr are experts and I think we differentiate between paths containing repeated slashes.

@RussellSpitzer what else I should look at?

**Comment by RussellSpitzer** [comment]
I think (2) we can actually do immediately without losing backwards compatibility. All readers can read paths written in the posix compliant matter, so implementing 2 even without a feature flag should be valid. The only issue is that new files will be in a slightly different location in S3 than they would have been previously. So I don't think this even needs a flag.

IE If we say from this point on, all files that are created will have posix normalized paths, should have no effect on compatibility. So I don't think we need (1). We let everyone read paths as they are in the metadata, we just make sure they are all written in the metadata in a way that is universally compatible.

Then I do think we may need a (3) but this is just for tables which have been written with non-posix compatible FileIO's that need to be used with a posix compatible file IO. This is a bit more intensive.

**Comment by RussellSpitzer** [comment]
Yeah my plan would be, regardless of what string ends up at the FileIO. The FileIO is responsible for only writing a posix compatible path. So just because I have a table location "foo/bar/" doesn't mean I get files at "foo/bar//data/". I'm open to other suggestions but this seems like a way we can resolve the issue.

For our users I'm trying to deal with the fact that they have many many tables and don't want to go through them modifying the table location in all of them. Ideally I think we should be able to go back and forth between FileIO's without causing a failure. This is a slightly unique situation  because I'm not sure if there are any other FileIO's which allow access to the same underlying filesystem.

**Comment by jackye1995** [comment]
> This is a slightly unique situation because I'm not sure if there are any other FileIO's which allow access to the same underlying filesystem.

I think this is probably a problem for all the S3-compatible storage systems, we already have a few implemented in this repo like the one from Dell ECS, so agree we should solve compatibility of it.

> Yeah my plan would be, regardless of what string ends up at the FileIO. The FileIO is responsible for only writing a posix compatible path. 

Yes I agree this is a simpler plan than my original thought. Are you currently already working on this? If not I can take it.

I think (3) as a procedure I think is probably still needed for tables already in that situation, and once we have that we can probably enforce it as a requirement and users for tables with issue can have a clear path forward.

**Comment by RussellSpitzer** [comment]
I have not started, so you are free to take it if you like. I do think we need confirmation from the Trino folks that this is something they can also follow. I know they have a completely different pathway for opening and creating files.

**Comment by jackye1995** [comment]
I think Trino is mostly fine, because all the file paths are converted to Hadoop paths before writing, so technically it already enforces posix style.

https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java#L336

https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java#L173

https://github.com/trinodb/trino/blob/master/lib/trino-filesystem/src/main/java/io/trino/filesystem/hdfs/HdfsInputFile.java#L46

https://github.com/trinodb/trino/blob/master/lib/trino-filesystem/src/main/java/io/trino/filesystem/hdfs/HadoopPaths.java

**Comment by RussellSpitzer** [comment]
Oh then this is actually much needed for trino too, since by default they can't read a non-posix file either?

**Comment by jackye1995** [comment]
Correct, that's why I said there is an internal patch in Athena to support non-posix files.

**Comment by electrum** [comment]
We have a hack in Trino to allow reading non-standard paths. That's the [`HadoopPaths`](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem/src/main/java/io/trino/filesystem/hdfs/HadoopPaths.java) code referenced above, along with [this code in `TrinoS3FileSystem`](https://github.com/trinodb/trino/blob/e41c3a7534d20ed55791335c892c8bd96ae30dd2/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java#L987-L990).

All of our writing code currently goes through Hadoop, so paths in S3 will be normalized, but we have a project to [decouple Trino from Hadoop and Hive codebases](https://github.com/trinodb/trino/issues/15921), so we'll want our upcoming non-Hadoop [`TrinoFileSystem`](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java) implementations to handle this correctly.

Handling `.` and `..` is tricky, though. If a user does this:

```sql
CREATE TABLE ... WITH (location = 's3://foo/bar/../baz')
```

What should the resulting object name in S3 be? What gets written to the Iceberg manifest? Where should the normalization happen? Do we need to normalize all "user input" locations?

While I like the idea of just using strings and not dealing with directories (which we copied from Iceberg `FileIO`), it certainly has annoyances and problems when interacting with POSIX-like systems.

**Comment by RussellSpitzer** [comment]
My call would be that everything new file we create with FileIO (in iceberg) hits this transformation

```scala
import java.nio.file.Paths
scala> def posixNormalize(s: String) = Paths.get(s).normalize.toString
posixNormalize: (s: String)String
scala> posixNormalize("s3://foo/bar/../baz")
res41: String = s3:/foo/baz
```

So I would add that as an protected method in FileIO and then any calls to   
OutputFile newOutputFile(String path);

call posixNormalize before doing anything else. Ideally I wish I could force this on all calls to newOutputFile but I don't think we can manage that without breaking the API. Maybe we can do that in Iceberg 2.0 and have 

```java
final OutputFile newOutputFile(String path) {
  return newOutputFileImpl(posixNormalize(path))
}

OutputFile newOutputFileImpl(String path)
```

**Comment by jackye1995** [comment]
>  Handling . and .. is tricky, though. If a user does this:
> 
> CREATE TABLE ... WITH (location = 's3://foo/bar/../baz')
> 
> What should the resulting object name in S3 be? What gets written to the Iceberg manifest? Where should the normalization happen? Do we need to normalize all "user input" locations?

Yes this case is interesting, I can see it go both ways. Sounds like we should still have a feature flag controlling this behavior then?

**Comment by RussellSpitzer** [comment]
I still think we just set this up, Iceberg only makes posix paths for any new files it creates. Anything going through FileIO.create is normalized. This means everything in the metadata is normalized unless a user explicitly and manually adds a data file that isn't.

**Comment by electrum** [comment]
I just realized this has implications for the specification. If a manifest file contains a location containing `.` or `..` path segments, how are readers supposed to interpret that? The current implementations that use Hadoop code will normalize them. Is this correct behavior? Should we formalize this behavior in the specification?

**Comment by RussellSpitzer** [comment]
@electrum thats part of my suggestion, no path entries can contain any unnormailzed posix characters. No .., ., //, maybe also specify no symbolic links although I'm not sure how we enforce that.

**Comment by findepi** [comment]
I am concerned about security implications of handling `..` in paths. At the same time I don't see any practical implications of that. If we gonna do any form of normalization, we should forbid such paths.
I think we should forbid `.` too.

**Comment by jackye1995** [comment]
I put up a draft for discussion, there are different ways to achieve that, the idea in the PR is to normalizes all the places that we write a location, which includes table location, metadata file location and data location.

> I am concerned about security implications of handling .. in paths

How do Hadoop file systems currently handle such use case? I believe it will also support `..` and `.` by default and derive the posix path of it right?

**Comment by RussellSpitzer** [comment]
Consensus at Community Sync was that for now we will just add a strip trailing slash to

https://github.com/apache/iceberg/blob/6697129a314d98cb793601495f7ebb2ae000b40a/core/src/main/java/org/apache/iceberg/TableMetadata.java#L451

To remove any chance of accidentally adding the double slash.

For all the other oddities Jack's PR will allow for manually setting a flag to forbid/only write posix compatible files. This would cover ".., ." and some other things but still not help us in the case of symbolic links which ends up being a weirder proposition based on the FileIO
