### ISSUE TITLE
Support Delta name mapping to Iceberg conversion

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#6768]
### Feature Request / Improvement

Support mapping Delta physical column name to Iceberg using Iceberg's name mapping feature

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#column-mapping

### Query engine

None

**Comment by JonasJ-ap** [comment]
More info regarding this feature request:
Delta Lake community is working on supporting column mapping (physical column name) in `delta-standlone` which is used by the `iceberg-delta-lake` module:https://github.com/delta-io/connectors/pull/453

We can start to implement this feature once they finished and release this new support
