### ISSUE TITLE
Support Changed PartitionCount in AddFiles Procedure output

### ISSUE THREAD

**Issue by dramaticlly** [apache/iceberg#6794]
### Feature Request / Improvement

Today Spark https://iceberg.apache.org/docs/latest/spark-procedures/#add_files only return number of files added to the iceberg table but missing other statistics such as partition changed. Partition stats are helpful especially files added are used across multiple partitions.

Since number of added files is sourced from snapshot summary https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java#L156-L158 , we can easily do this for changed partition https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotSummary.java#L53

But as what @RussellSpitzer suggested, we need to be cautious as this change the return type and need to wait for next major release

Input
```scala
val sql = """
|CALL iceberg.system.add_files(
|table =>'foo.bar',
|source_table => '`parquet`.`s3a://bucket/warehouse/foo.db/bar/data/`', 
|check_duplicate_files => false)"""
spark.sql(sql).show
```

Output
```
+-----------------+
|added_files_count|
+-----------------+
|             1084| 
+-----------------+
```

desired
```
+-----------------|-----------------------+
|added_files_count|changed_partition_count|
+-----------------|-----------------------+
|             1084|          24           |
+-----------------|-----------------------+
```

### Query engine

Spark

**Comment by RussellSpitzer** [comment]
I think the Procedure we can actually change the output for in a minor (as long as we are just adding fields) I forgot that this wasn't actually Action! I thought there was an AddFilesResult api we had to modify
