### ISSUE TITLE
AvtoSchemaUtils.convert() method produces Iceberg schema different from that by Hive/Spark

### ISSUE THREAD

**Issue by romanstreamsets** [apache/iceberg#6796]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Say, I run this in Spark/Hive: `CREATE TABLE FOO (col1 int) USING iceberg;`

Then I run something like this in a Java/groovy code:
```
org.apache.avro.Schema avroSchema = org.apache.avro.Schema.parse("{   \"type\" : \"record\",\"name\" : \"Employee\",   \"fields\" :  [    { \"name\" : \"col1\" , \"type\" : \"int\" } ] }");
org.apache.iceberg.Schema icebergSchema = AvroSchemaUtil.toIceberg(avroSchema);
```
... and proceed with writing data into the table:
```
GenericRecord record = GenericRecord.create(icebergSchema);
ImmutableList.Builder<GenericRecord> builder = ImmutableList.builder();
builder.add(record.copy(ImmutableMap.of("col1", 111)));

```
When reading the table back in Hive, the record would exist, but return a NULL value.
However, creation of icebergSchema from scratch produces a correct result:
```
org.apache.iceberg.Schema icebergSchema = new org.apache.iceberg.Schema(
      Types.NestedField.optional(1, "col1", Types.IntegerType.get())
    );

```
It seems that numbering field IDs from 1 has an effect. While AvroSchemaUtil.convert() method numbers fields from 0.
It seems to be an inconsistency.

**Comment by Fokko** [comment]
Hey @romanstreamsets,

Thanks for opening up this issue. Do you want the field to be required or optional? There is a difference between the schema that's being parsed from the JSON and the one you define in the code:
![image](https://user-images.githubusercontent.com/1134248/218050928-72357430-056e-4f72-a584-380b78e11d57.png)

However, this should not result in issues with reading null values. Let me try to reproduce this on my end

**Comment by Fokko** [comment]
Can you share how you append the records to the table? This blog might also be helpful for what you're trying to achieve: https://tabular.io/blog/java-api-part-3/

**Comment by Fokko** [comment]
I think we have to start the schema from 1 anyway, I took the liberty and created a PR: https://github.com/apache/iceberg/pull/6802

I'm still very curious to see whats going on with Hive, returning a null. But this requires me to setup a hive setup, but that takes a bit more time.

**Comment by rdblue** [comment]
I looked at @Fokko's PR, but I think that it doesn't address the underlying problem.

It looks like the flow here is to take a schema then convert to Iceberg and create a table. Then convert the schema to Avro and expect that it matches the table. That is incorrect. When writing to a table, you must always use the table's schema. Tables are responsible for assigning and tracking field IDs and you should never guess at what they will probably be.

The right solution is to convert your schema to Iceberg and create the table, then throw it away and use the table's schema. Convert the table schema to Avro and write records that way.

**Comment by romanstreamsets** [comment]
Hi @rdblue, what's the rationale behind such treatment of iceberg Schema when creating a table? -
1. Create icebergSchema
2. Create a table
3. discard the original Schema
4. get the correct icebergSchema from the table

It just looks like an unnecessary hoop.
