### ISSUE TITLE
Consolidate file path creation to LocationProvider

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#6809]
### Feature Request / Improvement

from https://github.com/apache/iceberg/pull/6772#issuecomment-1426873914, also copied here:

We have different places for creating file path names,
- `LocationProvider` for data files
- `TableOperations.metadataFileLocation` for manifests and manifest lists
-  catalog specific impl for metadata file location (e.g. `BaseMetastoreTableOperations.newTableMetadataFilePath`)

We should consolidate all the file path creations to `LocationProvider` if possible. Any thoughts? @rdblue @nastra @RussellSpitzer 

This would also help us enforce things like object storage mode to not just data files but also metadata files.

### Query engine

None

**Comment by youngxinler** [comment]
If this PR was added, I think it would be better to declare it to tell users that all added paths should follow POSIX compliant paths? Even though we have normalized it internally.
