### ISSUE TITLE
FlinkSql streaming read iceberg v2 table 

### ISSUE THREAD

**Issue by skywalker2256** [apache/iceberg#6816]
### Query engine

flink 1.15
iceberg 1.1.0

### Question

I can't read any data,when use flinksql /*+ OPTIONS('streaming'='true', 'monitor-interval'='1s')*/ streaming read iceberg v2 table ,
How should I do ?

**Comment by xuzhiwen1255** [comment]
Do you have upsert enabled?

**Comment by skywalker2256** [comment]
> Here is what I did.

CREATE TABLE sample_9 (
    id BIGINT COMMENT 'unique id',
    data BIGINT ,
   PRIMARY KEY(id) NOT ENFORCED
) with ('format-version'='2',
'write.upsert.enabled'='true')
;

query sql :
select * from hive_catalog.iceberg_db.sample_9 /*+options('streaming'='true','monitor-interval'='5s')*/ ;

result:
![image](https://user-images.githubusercontent.com/41573491/218367084-10ea34ef-f1fa-46bd-bb1b-7ea31ddf32c3.png)

**Comment by xuzhiwen1255** [comment]
iceberg does not support stream reading of tables with upsert enabled.

It is filtered out in the code, see https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java#L128 here

**Comment by ibnummuhammad** [comment]
will it be supported in the future? for flink to read iceberg table with upsert enabled streamingly?

**Comment by pvary** [comment]
Depends on core changes like: #14264 
After something like #14264 is ready, the Flink part needs to be implemented
