### ISSUE TITLE
Iceberg rewrite files parallel execution

### ISSUE THREAD

**Issue by mgorsk1** [apache/iceberg#6821]
### Feature Request / Improvement

We are using Spark.get.rewriteDataFiles action to compact files in partitioned tables. I've noticed that, although it should be possible to parallelize such task (taking into account that the table is partitioned and rewriting files happens on partition-level in such case) it's not really happening. From what I've observed such action is handled by single executor (according to my dynamicAllocation settings it could be up to 10) sequentially and takes awfully long time - 6300 (not large at all) files across 100 partitions are compacted in nearly 30 minutes (27 to be precise). 

This issue proposes considering introducing parallelization for this action to speed the process up - as for example happens when using action to remove orphan files.

### Query engine

Apache Spark 3.3.1 & Iceberg 1.1.0

**Comment by RussellSpitzer** [comment]
This feature already exists.

**Comment by mgorsk1** [comment]
Thanks @RussellSpitzer indeed I must've missed it. I used this and after increasing it increased the number of executors. The improvement I see that currently:
- with table has thousands of very small files across few partitions, and let's assume each file has size < 10000 bytes
- if MAX_FILE_GROUP_SIZE_BYTES_DEFAULT is set to > 10000 bytes
- spark will spawn many executors (up to MAX_CONCURRENT_FILE_GROUP_REWRITES) but no compaction will be done

so some pre-spawn executor job that also takes this into account would be useful, wdyt?

**Comment by RussellSpitzer** [comment]
Sorry I don't know what you mean
