### ISSUE TITLE
iceberg can not write data when last unlock error use hive catalog

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/iceberg#6824]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

When I use the hive catalog to manage the iceberg table, every time I take a snapshot, I will apply for the lock of the corresponding hive table and unlock it after the writing is completed, but when the unlock fails, no exception will be thrown, which will lead to the following A snapshot cycle can never acquire a lock, the task cannot continue to write, and the small file merge program cannot be called at the same time.
Corresponding code to unlock
：
```
  private void unlock(Optional<Long> lockId) {
    if (lockId.isPresent()) {
      try {
        doUnlock(lockId.get());
      } catch (Exception e) {
        LOG.warn("Failed to unlock {}.{}", database, tableName, e);
      }
    }
  }
```
get lock ：
```
              try {
                LockResponse response = metaClients.run(client -> client.checkLock(id));
                LockState newState = response.getState();
                state.set(newState);
                if (newState.equals(LockState.WAITING)) {
                  throw new WaitingForLockException("Waiting for lock.");
                }
              } catch (InterruptedException e) {
                Thread.interrupted(); // Clear the interrupt status flag
                LOG.warn("Interrupted while waiting for lock.", e);
              }
            }, TException.class);
```

It seems that there is always this problem

**Comment by huyuanfeng2018** [comment]
@raptond

**Comment by pvary** [comment]
#6451 Try to helps in most of the case
#6570 might be interesting for you as well

**Comment by lurnagao** [comment]
> #6451 Try to helps in most of the case #6570 might be interesting for you as well

Hi，This doesn't seem to solve the problem

**Comment by huyuanfeng2018** [comment]
> 

I think so too

**Comment by huyuanfeng2018** [comment]
> > #6451 Try to helps in most of the case #6570 might be interesting for you as well
> 
> Hi，This doesn't seem to solve the problem

I think so too
