### ISSUE TITLE
Write iceberg Table Using Pyarrow

### ISSUE THREAD

**Issue by akash-goel** [apache/iceberg#6830]
### Query engine

Spark

### Question

Hi Team,

we want to perform write operation (like Create Table , Update Columns ) in iceberg table using pyarrow Dataframe , Can you please guide how can we do it.

Regards,
Akash Goel

**Comment by Fokko** [comment]
Hi @akash-goel Thanks for raising this issue. [Creating tables](https://py.iceberg.apache.org/api/#create-a-table) is already possible. We're working on the API to alter tables, and that should be in soon.
