### ISSUE TITLE
Iceberg to Redshift load

### ISSUE THREAD

**Issue by nia94** [apache/iceberg#6841]
### Question

Has anyone tried loading data from iceberg tables to Redshift DB? Any suggestions are much appreciated. We have a use case to load data from iceberg tables to Redshift

**Comment by alvsanand** [comment]
Iceberg via Spectrum is in preview as of today https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-redshift-querying-apache-iceberg-tables/
