### ISSUE TITLE
Consider allows catalog.warehouse for Spark Hive Catalogs

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#6863]
### Feature Request / Improvement

Currently we only allow setting warehouse dir for Hadoop Catalogs but it would probably be useful to allow this for Hive Catalogs as well. We now make a new Hadoop configuration for every Hive Catalog so we could always just add in hive.metastore.warhouse.dir property.

This would allow folks to not specify locations for tables for a configured Catalog.

### Query engine

Spark

**Comment by youngxinler** [comment]
I will be happy to do this. @RussellSpitzer 
But I have a question, you mean if `spark.sql.catalog.catalog-name.type=hive`, use `spark.sql.catalog.catalog-name.warehouse` as `hive.metastore.warhouse.dir` default configuration of hive catalog value passed into `HiveCatalog`?

**Comment by RussellSpitzer** [comment]
I think that is one way to do it. We also may want to consider if we should respect the Spark.sql.warehouse did property if it exists

**Comment by youngxinler** [comment]
thanks for @RussellSpitzer , good hint,  i supports `spark.sql.warehouse.dir` and assumes that `spark.sql.catalog.$catalogName.warehouse` is preferred.

PR has been associated, if there is any problem with the code, you can directly raise it, looking forward to your guidance and review.
