### ISSUE TITLE
[Big manifest] If the manifest file is very big, the decode cost time is very long

### ISSUE THREAD

**Issue by zombee0** [apache/iceberg#6868]
### Feature Request / Improvement

I think iceberg decode manifest avro file each file one thread, do we have some method that split the file and decode parallel?

### Query engine

None

**Comment by Fokko** [comment]
@zombee0 thanks for raising this question.

Avro supports parallelization by decoding the blocks in parallel. For example, we could reduce the block size to increase parallelism. But before doing so, I think it is important to understand why the Manifest file is so big. It can be that there are many columns, or there are many small files that you can compact.

**Comment by zombee0** [comment]
> @zombee0 thanks for raising this question.
> 
> Avro supports parallelization by decoding the blocks in parallel. For example, we could reduce the block size to increase parallelism. But before doing so, I think it is important to understand why the Manifest file is so big. It can be that there are many columns, or there are many small files that you can compact.

Yes, we have an iceberg table with almost 1000 column, and I don't know why the manifest file were compacted to several files, and it is very big, when I use iceberg tablescan.plantasks it cost long time

**Comment by Fokko** [comment]
@zombee0 Got it, and do you use the statistics over all the columns? You can also configure how to collect all the statistics: https://iceberg.apache.org/docs/latest/configuration/#write-properties

![image](https://user-images.githubusercontent.com/1134248/219660666-67572dc0-ed12-48eb-8399-b8c72d36a0c0.png)

**Comment by zombee0** [comment]
@Fokko Does the iceberg team have any plan to support decode a big manifest file with several threads parallel?

**Comment by Fokko** [comment]
@zombee0 Currently manifests are decoded in parallel, but a single manifest isn't decoded by multiple threads. I'm not aware of any plans to make this possible. If you're interested in working on this, you're more than welcome.

**Comment by zombee0** [comment]
@Fokko thank you very much, I might do this work when I have some time. And another question, is there any team do some work on cache the decoded manifest information, because decoding avro file is really cpu intensive.

**Comment by hongli-my** [comment]
> there are many small files that you can compact.

 data in iceberg over two years,  if we compact data to big file,  For example 2GB,    I  think  filtering will not work well.

**Comment by rustyconover** [comment]
I'm also seeing this behavior. I have 10 manifest files each 8mb in size.

It seems that there is a lot of contention for Python's GIL across all of the threads.  It may be better to use a ProcessPool rather than a thread pool to do the decoding of the Avro file.  That way there wouldn't be contention around the GIL lock and the result can be easily serialized back to the calling function.  If I have time I will build a comparison between ThreadPool and ProcessPool based loading.
