### ISSUE TITLE
SchemaParser::fromJson error parsing decimal(p,s) but works for decimal(p, s)

### ISSUE THREAD

**Issue by s-akhtar-baig** [apache/iceberg#6910]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

SchemaParser.fromJson(String schema) throws an error if the type string is decimal(p,s), but the call is successful for decimal(p, s). 

I looked at the Types class and it looks like the DECIMAL pattern is "decimal\\((\\d+),\\s+(\\d+)\\)". Can we change this to "decimal\\((\\d+),\\s*(\\d+)\\)" instead to avoid throwing an error when a whitespace is not present in the type string?

For reference: 
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/types/Types.java : line number 57

**Comment by nastra** [comment]
It might make sense to update the regex pattern for decimals in this case. @s-akhtar-baig would you like to open a PR for that?

**Comment by clesaec** [comment]
Sorry, just see your comment @nastra, i just made [this PR](https://github.com/apache/iceberg/pull/6917), accepting space for Fixed and Decimal type inside bracket for first and parenthesis for second.

**Comment by s-akhtar-baig** [comment]
@nastra, I would have loved to, but I am also glad that the issue has been taken care of so quickly. :)
