### ISSUE TITLE
change partition led to query bug

### ISSUE THREAD

**Issue by ymZhao1001** [apache/iceberg#6914]
### Apache Iceberg version

main (development)

### Query engine

Flink

### Please describe the bug 🐞

```sql
CREATE CATALOG c1WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://***:9083',
  'clients'='5',
  'property-version'='1',
  'warehouse'='hdfs://***:8020/iceberg/'
);
use catalog c1;
create database d1; 
use d1;

CREATE TABLE t1(
  ss_create_time TIMESTAMP(3),
  ss_update_time TIMESTAMP(3),
  ss_user_name STRING,
  ss_product_name STRING,
  ss_shop_name STRING,
  ss_city_name STRING,
  ss_country_name STRING,
  ss_sold_date_sk BIGINT,
  ss_sold_time_sk BIGINT,
  ss_item_sk BIGINT,
  ss_customer_sk BIGINT,
  ss_cdemo_sk BIGINT,
  ss_hdemo_sk BIGINT,
  ss_addr_sk BIGINT,
  ss_store_sk BIGINT,
  ss_promo_sk BIGINT,
  ss_ticket_number BIGINT,
  PRIMARY KEY(ss_ticket_number,ss_sold_date_sk,ss_sold_time_sk) NOT ENFORCED
) PARTITIONED BY (ss_sold_date_sk) WITH ('format-version'='2','write.upsert.enabled'='true');

insert into t1 select * from default_catalog.default_database.datagen_src;

wait for several times  completed checkpoint

then spark engine 
ALTER TABLE t1 ADD PARTITION FIELD ss_sold_time_sk;

flink query
select * from t1;
```

exception：
org.apache.flink.table.api.TableException: Column 'ss_sold_time_sk' is NOT NULL, however, a null value is being written into it. You can set job configuration 'table.exec.sink.not-null-enforcer'='drop' to suppress this exception and drop such records silently.
	at org.apache.flink.table.runtime.operators.sink.SinkNotNullEnforcer.filter(SinkNotNullEnforcer.java:56)
	at org.apache.flink.table.runtime.operators.sink.SinkNotNullEnforcer.filter(SinkNotNullEnforcer.java:30)
	at org.apache.flink.streaming.api.operators.StreamFilter.processElement(StreamFilter.java:38)

**Comment by ymZhao1001** [comment]
#6915 https://github.com/apache/iceberg/pull/6915

**Comment by nastra** [comment]
It seems that you're inserting null values for `ss_sold_time_sk`, then making it a partition field and Flink errors about it (which is the correct thing to do). Flink even says that you can set `table.exec.sink.not-null-enforcer'='drop'` to silently drop those null values.

**Comment by ymZhao1001** [comment]
@nastra in fact , there is no null values for ss_sold_time_sk.
