### ISSUE TITLE
when use beeline read iceberg table on HDFS, cast error

### ISSUE THREAD

**Issue by fss233** [apache/iceberg#6918]
### Query engine

use hdp ,hive3.1 integration with Iceberg ,
when berfore insert data:
SET hive.execution.engine = mr;
Error: Error while processing statement: hive execution engine mr is not supported. (state=42000,code=1)

how to solve the problem?

### Question

use hdp ,hive3.1 (hadoop3+) integration with Iceberg ,
when berfore insert data:
SET hive.execution.engine = mr;
Error: Error while processing statement: hive execution engine mr is not supported. (state=42000,code=1)

how to solve the problem?

**Comment by pvary** [comment]
I  would suggest to use Hive 4.
Alternatively you can try Tez as an execution engine
