### ISSUE TITLE
Partition Spec Performance

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#692]
I have two timeseriers intra day data fro multiple days. The ticktime is in seconds. I had added a partition spec .identity("DATE").hour("TICKTIME")to both dataset 
After the write I see both data get partition in Date and hourly buckets.
I am trying to query where one of the data ticktime is less than the other data timeseries for the same day.
I ran through the same example without any external partition spec I am not seeing any performance compare to no external partitioning. 
I was assuming the query would not look into hourly partition where hour in ticktime is greater the joined ticktime.
Do I need to do something extra so that partition spec will start taking effect.

**Comment by rdblue** [comment]
It's difficult to understand what you're trying to do from the information provided. I recommend looking at logs to find out what predicates were applied to your table scans.

**Comment by rdblue** [comment]
It's difficult to understand what you're trying to do from the information provided. I recommend looking at logs to find out what predicates were applied to your table scans.
