### ISSUE TITLE
Merge-on-read vs copy-on-write behavior during merge into

### ISSUE THREAD

**Issue by arunb2w** [apache/iceberg#6928]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I am running a merge-into query and wanted to see how it behaves with write.merge.mode'='copy-on-write' and 'merge-on-read' for the same input on the same cluster config."
From the spark UI, the merge sql took only **2.5mins in copy-on-write** and for the same load **merge-on-read took 11mins.**
Attaching the images to show stage level behavior in which we can see huge shuffle write with merge-on-read whereas it is very minimal with copy-on-write.
When further analysing the SQL tab of the spark UI, were able to find out dynamic-pruning is not happened with MoR whereas we could see that filter in CoW.
My understanding is that, for faster writes we should prefer MoR but in this case MoR is actually performing worst than CoW. 

<img width="1449" alt="stage_mor" src="https://user-images.githubusercontent.com/38204827/221536497-51de7061-c6cd-49f9-b0d8-307ff8f708bd.png">

<img width="1494" alt="stage_cow" src="https://user-images.githubusercontent.com/38204827/221536557-e39109b1-1b51-43b7-a713-86d9e4ede71d.png">

Questions:
Why dynamic pruning is not happening with MoR when running merge into query?
Why shuffle write is huge when using MoR for the same input batch?
How to optimize the MoR performance?

**Comment by BsoBird** [comment]
+1
The write performance of MOR tables is worse than COW tables.
