### ISSUE TITLE
Migrating iceberg table on object storage

### ISSUE THREAD

**Issue by BiuBiu2323** [apache/iceberg#6964]
### Query engine

SparkSQL

### Question

Is there any other way to migrate my iceberg table from the old object store to the new object store besides using sparksql to select?

**Comment by BiuBiu2323** [comment]
can i just load the parquet file from old table into new table?

**Comment by amogh-jahagirdar** [comment]
@BiuBiu2323 did you get a chance to look at the `addFiles` procedure? https://iceberg.apache.org/docs/latest/spark-procedures/#add_files . you can also write your own logic using the java library https://iceberg.apache.org/docs/latest/api/#transactions `AppendFiles` API
