### ISSUE TITLE
Cannot write incompatible data

### ISSUE THREAD

**Issue by pkhetrapal** [apache/iceberg#6979]
### Apache Iceberg version

0.13.1 (Using iceberg sink connector for AWS Glue 3.0)

### Query engine

Pyspark

### Question

I am unable to write to a struct column if there is a new field added to it. Would I have to update the schema of the struct column to handle this case or can I bypass the compatibility check? In the below example the order also changes.

I am using aws glue catalog to manage the schema.

Existing schema for the struct column:
```
	|-- home: struct (nullable = true)
 		|-- city: string (nullable = true)
		|-- country: string (nullable = true)
		|-- state: string (nullable = true)
```

New schema:
```
	|-- home: struct (nullable = true)
		|-- phone: string (nullable = true)
 		|-- city: string (nullable = true)
		|-- country: string (nullable = true)
		|-- state: string (nullable = true)
```

**Comment by Fokko** [comment]
@pkhetrapal Thanks for reaching out. Would be great if you could include the steps that you took to reproduce the issue. It works on my machine: 

![image](https://user-images.githubusercontent.com/1134248/222946691-b292dbd6-f603-4105-b43a-3147ad584542.png)

**Comment by pkhetrapal** [comment]
Hi @Fokko, thanks for the response.

My use case is to handle streaming data with variable fields in the struct column. 
I was able to find the missing fields from the struct column on the fly and was able to update the table using the `ADD COLUMN`, but now, even if the fields are nullable, I can't add the data with missing fields.

For eg:
I have the below struct col in the table
```
my_col: struct (nullable = true)
 |    |-- key1: string (nullable = true)
 |    |-- key2: string (nullable = true)
 |    |-- key3: string (nullable = true)
```
but when I try to add a row where `key3` is missing in the `my_col` column, I get:
```
pyspark.sql.utils.AnalysisException: Cannot write incompatible data:
- Struct 'my_col' missing fields: 'key3'
```
