### ISSUE TITLE
Table Corruption iceberg

### ISSUE THREAD

**Issue by ferrari6666** [apache/iceberg#6989]
### Query engine

Spark

### Question

When spark abort is called from SparkWrite if a few files are deleted but manifest, manifest lists, and metadata are not deleted this is causing table corruption with AWS glue catalog TableOperations Pls can throw some light on this.
The catalog commit was in the UNKOWN state which causes cleanupOnAbort = false;  ideally, this should not attempt file cleanup.
It attempted file cleanup as S3 logs show the file marked as deleted.

```
 if (deletedFilesCount.get() < paths.size()) {
      LOG.warn("Deleted only {} of {} file(s) ({})", deletedFilesCount, paths.size(), context);
    }
```

Does manual rollback need to be done?

@aokolnychyi

**Comment by ferrari6666** [comment]
@jackye1995  pls can you look into this

**Comment by RussellSpitzer** [comment]
Can you please be a little more clear about what happened? Did the metadata.json from the commit get changed in the catalog? Were the Aborted files deleted? Did Spark treat the write as failed?

What versions of Iceberg and Spark are you using?
