### ISSUE TITLE
PyIceberg ValueError: An Expression cannot be evaluated to python True or False. 

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg#7012]
### Apache Iceberg version

main (development)

### Query engine

Other

### Please describe the bug 🐞

using this code to read some data from Tabular

```
from pyiceberg.expressions import GreaterThanOrEqual
scan = taxi.scan(
    row_filter=GreaterThanOrEqual("extra_surcharges", 100),
    selected_fields=("vendor_id", "pickup_time", "dropoff_time")
)
parquet_list = [task.file.file_path for task in scan.plan_files()]
con= scan.to_duckdb('xxx')
con.sql('select * from xxx')
```

I get this error
```
/usr/local/lib/python3.8/dist-packages/pyarrow/_compute.pyx in pyarrow._compute.Expression.__bool__()

ValueError: An Expression cannot be evaluated to python True or False. If you are using the 'and', 'or' or 'not' operators, use '&', '|' or '~' instead.
```

**Comment by Fokko** [comment]
Thanks for reporting this @djouallah 

I tried to reproduce this on my end, but unfortunally was unable to trigger the issue on the main branch and on PyIceberg 0.3.0:

![image](https://user-images.githubusercontent.com/1134248/222903127-152b580f-1528-4bfd-9614-f72974ecbe39.png)


Could you give more information on how you ran into this? Is this on your local machine or in some environment?

Could you share the PyArrow version?

```python
python3
Python 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> pyarrow.__version__
'11.0.0'
```

**Comment by djouallah** [comment]
sorry was running from pip install git, maybe delete your credential :)
sorry for the noise

**Comment by Fokko** [comment]
Whoops! Thanks for notifying me about the credential. No problem at all, great to hear that it has been resolved.
