### ISSUE TITLE
Flink: filters not applied at row-level for non-partition columns

### ISSUE THREAD

**Issue by gensheng-mo** [apache/iceberg#7022]
### Apache Iceberg version

0.13.0

### Query engine

Flink

### Please describe the bug 🐞

I run a program to read data from iceberg table by flink batch api , it seem the ` flilters() ` funtion is unless when iceberg table is stored by ` PARQUET` fromat .
Source table t3 has 4 recods  and program add filter expression ` a >= 3 ` . And , the program result is incorrect !
Please see follow pictures :

![image](https://user-images.githubusercontent.com/12807493/222997769-08d6be44-fe9b-4ae2-b81c-c7136efcfb86.png)
![image](https://user-images.githubusercontent.com/12807493/222997779-8181ea14-5cd7-4596-a7ee-6804d3068b58.png)
![image](https://user-images.githubusercontent.com/12807493/222997784-e10b3ae3-aa6d-44d4-93e6-4a730b512620.png)

However , I can get  correct result when iceberg table stored by `ORC ` format. 
Wait for some body give me something useful solutions , thanks !

**Comment by gensheng-mo** [comment]
Here is  the iceberg table desc information. 

![image](https://user-images.githubusercontent.com/12807493/223001511-51420a93-8dcd-47ae-a70b-10c642a34ecf.png)

**Comment by gensheng-mo** [comment]
@stevenzwu Hi, can you get me some helps ?

**Comment by Fokko** [comment]
I can confirm:
```
public class TestFokko {
    @Test
    public void testFokkoLoadTable() throws Exception {
        StreamExecutionEnvironment env = StreamExecutionEnvironment.createLocalEnvironment();

        Map<String, String> properties = new HashMap<>();

        properties.put("uri", "http://localhost:8181");
        properties.put("s3.access-key-id", "admin");
        properties.put("s3.secret-access-key", "password");
        properties.put("s3.endpoint", "http://localhost:9000");

        CatalogLoader catalog = CatalogLoader.custom(
                "rest",
                properties,
                new Configuration(true),
                "org.apache.iceberg.rest.RESTCatalog"
        );

        TableLoader tableLoader = TableLoader.fromCatalog(catalog, TableIdentifier.of("nyc", "taxis_vendors"));
        DataStream<RowData> batch = FlinkSource.forRowData()
                .env(env)
                .tableLoader(tableLoader)
                .streaming(false)
                .filters(Arrays.asList(Expressions.greaterThanOrEqual("VendorID", 2)))
                .build();

        batch.addSink(new SinkFunction<RowData>() {
            @Override
            public void invoke(RowData value) {
                System.out.println(value.getInt(0));
            }
        });
        env.execute("Test Iceberg Batch Read");
    }
}
```

In the output I don't see any filtering.

**Comment by Fokko** [comment]
It pushes the filter down to skip row groups:
https://github.com/apache/iceberg/blob/d59e6c85e216dab2316d52cd45f18fa4896302c0/parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java#L1044-L1052

The `readerFunc` passed in there just reads the records. So there is no row-level filtering being done currently.

**Comment by Fokko** [comment]
I'm not sure if the current behavior is intentional, because the residual filter is passed in the builder:

https://github.com/apache/iceberg/blob/d59e6c85e216dab2316d52cd45f18fa4896302c0/flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java#L145-L165

**Comment by Fokko** [comment]
Did some extensive digging into this today. And it looks like the filter operation returns residuals; that means that row groups that may contain valid rows are read as a whole. Fixing this requires quite a bit of an overhaul of the code. 

Currently, we read everything directly using `FlinkParquetReaders`, and we don't filter currently. If the column isn't part of the requested schema, then we can't filter afterward, so we have to make sure that the columns are included, or skip directly while reading.

**Comment by doki23** [comment]
The filters should not be removed after getting pushed down.

**Comment by zhongyujiang** [comment]
I don't know why this gets the correct result when stored as ORC, but I think Iceberg always leave the row level filter to the post scan. And the java doc for `FlinkSource#forRowData` said that it's equivalent to `TableScan`, it is not for row level filtering, so I think this is an expected result.

> Initialize a FlinkSource.Builder to read the data from iceberg table. Equivalent to TableScan. See more options in ScanContext.
> The Source can be read static data in bounded mode. It can also continuously check the arrival of new data and read records incrementally.
> Without startSnapshotId: Bounded
> With startSnapshotId and with endSnapshotId: Bounded
> With startSnapshotId (-1 means unbounded preceding) and Without endSnapshotId: Unbounded
> 
> Returns:
> FlinkSource.Builder to connect the iceberg table

**Comment by doki23** [comment]
> so I think this is an expected result.

If it's an expected result, we'd better rename 'filter' to 'unpreciseFilter'(maybe) to avoid making developers confused.

**Comment by stevenzwu** [comment]
Just looked at the `TestFlinkScan` class. it only has coverage for filtering on partition column. I don't have the full history on the the residual filter behavior. I do agree the current behavior is a bit confusing to the users.

**Comment by stevenzwu** [comment]
> so we'd better add a flink filter operator after source scan 

@doki23 that would requires users to add it explicitly, which is also unintuitive for users that filters have to be provided in two different places. E.g. for FLIP-27 source.

```
    IcebergSource.Builder<RowData> sourceBuilder =
        IcebergSource.forRowData()
            .tableLoader(tableLoader())
            .table(table)
            .assignerFactory(new SimpleSplitAssignerFactory())
            .flinkConfig(config);
    sourceBuilder.filters(filters);
    sourceBuilder.properties(options);

    DataStream<Row> stream =
        env.fromSource(
                sourceBuilder.build(),
                WatermarkStrategy.noWatermarks(),
                "testBasicRead",
                TypeInformation.of(RowData.class))
            .filter(<some Flink filter function>); <<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by Fokko** [comment]
For other engines, the source also filters down to a row level, instead of a row group level as it is now.

I think we need to do a few things:

- When projecting the schema that's being passed down to the parquet reader, make sure that the fields that that's being filtered on, are being read.
- Read as we do now, which will do the partition pruning, metrics evaluation, and row group filtering.
- Filter using Flink since it is probably heavily optimized (and we don't want to reinvite the wheel here).
- Do a final projection to the requested schema that will exclude the fields that are part of the filter, but not part of the selected columns.

**Comment by Fokko** [comment]
I've created a PR https://github.com/apache/iceberg/pull/7109. This does fix the filtering but does not do the projection correctly (yet). I don't think this is an issue, the only downside is that you have to include the field that you're filtering in your projection. We can pick that up in a follow-up PR.
