### ISSUE TITLE
Flink: Update the docs

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7025]
### Feature Request / Improvement

The Flink docs look outdated: https://iceberg.apache.org/docs/latest/flink/

It points to `flink-iceberg-runtime`. While this has been replaced with the runtime with the version in it, for example `iceberg-flink-runtime-1.15`. See: https://repo.maven.apache.org/maven2/org/apache/iceberg/ 

Would be cool to update this so we can easily spin up Flink with the latest Iceberg releases

### Query engine

Flink

**Comment by mhmohona** [comment]
Hello @Fokko, I would like to work on this issue. I would like to confirm if I have the correct understanding. 

Does this mean that every instance of `flink-runtime` needs to be replaced with `iceberg-flink-runtime-1.15` in all over the documentation?
