### ISSUE TITLE
Spark Write Documentation missing distribution mode text and is out of date

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#7037]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

https://iceberg.apache.org/docs/latest/spark-writes/#writing-to-partitioned-tables

Has a few inaccuracies and some missing information.

1. We need a section on distribution modes
2. The examples need to be updated, the sort within partitions information is no longer correct
3. Registering functions is no longer required

Basically a full overhaul

**Comment by RussellSpitzer** [comment]
If anyone wants to take this I would be glad to do reviews

**Comment by bitsondatadev** [comment]
@RussellSpitzer could you add the docs tag to this please?
