### ISSUE TITLE
Dynamic Split generation based on table size

### ISSUE THREAD

**Issue by singhpk234** [apache/iceberg#7071]
### Feature Request / Improvement

Split generation should take table size also into consideration, not only just the defined split sizes, to improve the performance of read for small table sizes.

cc @jackye1995 

### Query engine

None

**Comment by jackye1995** [comment]
thanks for bringing this up! Yes I remember we briefly discussed this in a past community sync. cc @danielcweeks @rdblue 

I am sure this is going to help with the case where people do not set default at all, and we can dynamically reduce target file size to increase utilization of worker nodes. 

But people can technically do that by setting `read.split.target-size` to customize for each table, and I think they should do that. But that goes to the realm of auto-optimization.

I am interested to know what other people think.
