### ISSUE TITLE
数据合并

### ISSUE THREAD

**Issue by luxl6** [apache/iceberg#7092]
### Query engine

Flink

### Question

flink 结合iceberg写入minio，小文件怎么合并

**Comment by xuzhiwen1255** [comment]
see:https://iceberg.apache.org/docs/latest/flink/#rewrite-files-action

**Comment by luxl6** [comment]
> 参见：https://iceberg.apache.org/docs/latest/flink/#rewrite-files-action

Exception in thread "main" org.apache.iceberg.exceptions.NoSuchTableException: Table does not exist at location: s3a://iceberg/flink_db/flink_hb
	at org.apache.iceberg.hadoop.HadoopTables.load(HadoopTables.java:97)
	at org.apache.iceberg.flink.TableLoader$HadoopTableLoader.loadTable(TableLoader.java:76)
一直报表不存在，我的catalog用的是jdbc模式存在了pgsql,数据存在了minio里面，这个怎么做呢？？

**Comment by luxl6** [comment]
> 参见：https://iceberg.apache.org/docs/latest/flink/#rewrite-files-action

官网这个说的是Hadoop的吧，大佬们，求指教

**Comment by xuzhiwen1255** [comment]
@luxl6 I suggest you use English. No one here uses Chinese

**Comment by luxl6** [comment]
> 参见：https://iceberg.apache.org/docs/latest/flink/#rewrite-files-action
线程 “main” org.apache.iceberg.exceptions.NoSuchTableException： Table 在 location： s3a：//iceberg/flink_db/flink_hb at org.apache.iceberg.hadoop.HadoopTables.load（HadoopTables.java：97）
at org.apache.iceberg.flink.TableLoader$HadoopTableLoader.loadTable（TableLoader.java：76）


The report does not exist, my catalog uses jdbc mode, pgsql exists, and the data exists in minio, how do I merge data? ?

**Comment by luxl6** [comment]
> 参见：https://iceberg.apache.org/docs/latest/flink/#rewrite-files-action
The official website is about Hadoop.

**Comment by luxl6** [comment]
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"

Does Hadoop not support the s3 protocol?

**Comment by luxl6** [comment]
You can access minio implementation rewrite using the s3 protocol.

How to do this? ? ask for advice

**Comment by xuzhiwen1255** [comment]
You need aws dependency

**Comment by luxl6** [comment]
> You need aws dependency

<properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <scala.version>2.12</scala.version>
        <flink.version>1.15.3</flink.version>
        <hadoop.version>3.3.1</hadoop.version>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-runtime</artifactId>
            <version>${flink.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-common</artifactId>
            <version>${flink.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java</artifactId>
            <version>${flink.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner_${scala.version}</artifactId>
            <version>${flink.version}</version>

        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>

        </dependency>

        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-java</artifactId>
            <version>${flink.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
            <version>${flink.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients</artifactId>
            <version>${flink.version}</version>

        </dependency>

        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-s3-fs-hadoop</artifactId>
            <version>${flink.version}</version>

        </dependency>



        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc</artifactId>
            <version>${flink.version}</version>

        </dependency>

       
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-hive_2.12</artifactId>
            <version>${flink.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge</artifactId>
            <version>${flink.version}</version>

        </dependency>

        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>${hadoop.version}</version>

        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>${hadoop.version}</version>

        </dependency>

        
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-hdfs-client</artifactId>
            <version>${hadoop.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-mapreduce-client-core</artifactId>
            <version>3.3.1</version>
        </dependency>


        
 <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-aws</artifactId>
            <version>${hadoop.version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-bundle</artifactId>
            <version>1.11.271</version>
        </dependency>



        
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-exec</artifactId>
            <version>2.3.9</version>

        </dependency>


        


        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-sql-connector-hbase-2.2</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-server</artifactId>
            <version>1.2.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>1.2.4</version>
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>iceberg</groupId>
            <artifactId>iceberg-flink-runtime-1.15</artifactId>
            <version>1.1.0</version>

        </dependency>
        <dependency>
            <groupId>iceberg</groupId>
            <artifactId>bundle</artifactId>
            <version>2.17.257</version>

        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>url-connection-client</artifactId>
            <version>2.17.257</version>

        </dependency>

        
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.5.1</version>

        </dependency>
        
        <dependency>
            <groupId>org.apache</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.48</version>

        </dependency>
    </dependencies>


This is all my dependencies, can you see which one is missing

**Comment by xuzhiwen1255** [comment]
hadoop-aws aws-java-sdk-bundle 1.11.271 Does it exist?

**Comment by luxl6** [comment]
<dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-aws</artifactId>
            <version>${hadoop.version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-bundle</artifactId>
            <version>1.11.271</version>
        </dependency>

exist   My Hadoop is 3.3.1

**Comment by xuzhiwen1255** [comment]
I think the documentation is very detailed.

Change the address to the one that accesses minio, change the catalog to the corresponding catalog, and you may need some access-related configuration

```java
import org.apache.iceberg.flink.actions.Actions;
 
TableLoader tableLoader = TableLoader.fromHadoopTable("xxx");
Table table = tableLoader.loadTable();
RewriteDataFilesActionResult result = Actions.forTable(table)
        .rewriteDataFiles()
        .execute();

```

Such as these, of course, not all of them are necessary, I am just an example
```java
      config.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem");
      config.set("fs.s3a.path.style.access", "true");
      config.set("fs.s3a.connection.ssl.enabled", "false");
      config.set("fs.s3a.access.key", access);
      config.set("fs.s3a.secret.key", secret);
      config.set("fs.s3a.endpoint", endpoint);
      .....
```

**Comment by luxl6** [comment]
Configuration conf = new Configuration();
        conf.set("fs.s3a.connection.ssl.enabled", "false");
        conf.set("fs.s3a.endpoint", "http://ip:9000");
        conf.set("fs.s3a.access.key", "minioadmin");
        conf.set("fs.s3a.secret.key", "minioadmin");
        conf.set("fs.s3a.path.style.access", "true");
        conf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem");
        conf.set("fs.s3a.fast.upload", "true");
        conf.set("catalog-impl", "org.apache.iceberg.jdbc.JdbcCatalog");
        conf.set("uri", "jdbc:postgresql://ip:5432/icebergcat");
        conf.set("user", "PostgreSQL");
        conf.set("password", "PostgreSQL");


        TableLoader tableLoader = TableLoader.fromHadoopTable("s3a://iceberg/flink_db/flink_hb",conf);
        tableLoader.open();
        Table table = tableLoader.loadTable();
        RewriteDataFilesActionResult result = Actions.forTable(table)
                .rewriteDataFiles()
                .execute();

Teacher, my main problem is that my catalog is not Hadoop catalog, but jdbc catalog. I merged Hadoop catalog successfully. I use jdbc to store catalog, and when I use Hadoop to merge files on minio, it cannot find it. Related table information, so the report does not exist all the time. Table does not exist at location: s3a://iceberg/flink_db/flink_hb

**Comment by luxl6** [comment]
Teacher, the jdbc_catalog data merge that has troubled me for a week has finally been solved, thank you teacher for your previous help
