### ISSUE TITLE
Deprecate usages of AssertHelpers in codebase

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7094]
### Feature Request / Improvement

as a part of discussions in #6977 , create an issue to track the effort.

This seems like a good beginners task, or for someone that have some spare time to remove all references.

This does not need to happen in a giant PR, can be done module by module.

### Query engine

None

**Comment by liuxiaocs7** [comment]
@jackye1995 I would like to work on this. Can you assign it to me?
I think this can start after #6977 is merged, what do you think?

**Comment by nastra** [comment]
@liuxiaocs7 Doing this on a module-by-module basis would be a good thing, as it makes it easier for reviewers to review small PRs. Also might be worth starting in one of the modules that has a lower amount of usages of `AssertHelpers`  (iceberg-orc can probably be combined with another module)

![image](https://user-images.githubusercontent.com/271029/224974292-e70302d5-280e-4e9f-a61e-f13b68bc9049.png)

**Comment by liuxiaocs7** [comment]
> @liuxiaocs7 Doing this on a module-by-module basis would be a good thing, as it makes it easier for reviewers to review small PRs. Also might be worth starting in one of the modules that has a lower amount of usages of `AssertHelpers` (iceberg-orc can probably be combined with another module)
> 
> ![image](https://user-images.githubusercontent.com/271029/224974292-e70302d5-280e-4e9f-a61e-f13b68bc9049.png)

Thank you for your suggestion. I will revise it step by step.

**Comment by akshayakp97** [comment]
Hi! I'm going to try making this change to `iceberg-orc` module

**Comment by akshayakp97** [comment]
@liuxiaocs7 I sent out a [PR](https://github.com/apache/iceberg/pull/7468) to remove usage of AssertHelpers. It overlaps with changes from your PR. Specifically these two files - https://github.com/apache/iceberg/pull/7482/files#diff-52c0deff4e445a4ed751511025b1cf380549283a85d91f67528116d9072bb86b and https://github.com/apache/iceberg/pull/7482/files#diff-65e74287fd4b789cbc6789d0f1435ca700c121114d98823e827fd1ee76174d08

Please note that I will remove these two files from my PR.

**Comment by liuxiaocs7** [comment]
Hi, @akshayakp97, sorry, I didn't notice your pr and covered ORC and MR modules in Hive module. Thanks for removing the related module in #7468.

**Comment by gzagarwal** [comment]
Is there any module that i can pick up

**Comment by nastra** [comment]
@gzagarwal you can just search through the codebase and pick up any of them, such as the ones in `iceberg-aws` module

**Comment by gzagarwal** [comment]
okay let me pick

**Comment by amshali** [comment]
Working on flink module...

**Comment by gzagarwal** [comment]
> okay let me pick, I am working on iceberg-aws

Shall i assume current test cases are working? on my local system they are not working so asking this question. 
Is there any perquisite to work on the iceberg workspace .Some settings do i need to run to work.

**Comment by nastra** [comment]
@gzagarwal yes the tests should all be working. What issue are you seeing? https://github.com/apache/iceberg/blob/a3aff95f9e60962240b94242e24a778760bdd1d9/CONTRIBUTING.md and https://iceberg.apache.org/contribute/#building-the-project-locally should contain everything needed in order to configure the project locally

**Comment by gzagarwal** [comment]
> @gzagarwal you can just search through the codebase and pick up any of them, such as the ones in `iceberg-aws` module

I am running existing testcase in iceberg-aws module . 
TestCase Name : 
TestDefaultAwsClientFactory.testS3FileIoCredentialsOverride
Exception : while running the test case
getting this message "software.amazon.awssdk.core.exception.SdkClientException: Unable to marshall request to JSON: Parameter 'Bucket' must not be null"

**Comment by nastra** [comment]
The only modules left are Spark 3.2 + Spark 3.3

![image](https://github.com/apache/iceberg/assets/271029/869d8ec2-7d9d-4a14-8dd9-3326c64db850)

I don't think we want to spend time migrating those. Once Spark 3.2 + 3.3 are deprecated and removed from the codebase, we can remove `AssertHelpers`.

**Comment by findepi** [comment]
follow-up to complete removal of AssertHelpers -- https://github.com/apache/iceberg/pull/10500

> I don't think we want to spend time migrating those

agreed! fortunately they turned out mechanically updatable. in the PR above i did this using Intellij structural replace.
