### ISSUE TITLE
Add checkstyle rule to ensure hasMessage is called for exception assertions

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7095]
### Feature Request / Improvement

based on https://github.com/apache/iceberg/pull/6977#discussion_r1125057764

### Query engine

None

**Comment by nastra** [comment]
I opened https://github.com/apache/iceberg/issues/7040 already a few days ago, so I think we can close this one.

**Comment by jackye1995** [comment]
ah I see I overlooked that, thanks!
