### ISSUE TITLE
Remove code deprecated in Iceberg 1.2.0

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#7102]
### Feature Request / Improvement

Once Iceberg 1.2.0 is out, we should remove all the code that was deprecated and marked for 1.3.0 removal.

### Query engine

None

**Comment by nastra** [comment]
I could handle all the deprecations in the `iceberg-core` module.

@szehon-ho would you be interested in doing the same for spark 3.3?

**Comment by szehon-ho** [comment]
Sure, I think @aokolnychyi has done some in https://github.com/apache/iceberg/pull/7069, and I did others in https://github.com/apache/iceberg/pull/6760, will see if there are more

**Comment by nastra** [comment]
Handling core deprecations in https://github.com/apache/iceberg/pull/7156

**Comment by nastra** [comment]
I have opened https://github.com/apache/iceberg/pull/7489 to remove a deprecated/unused class. It looks like the only other class with `@deprecated will be removed in 1.3.0` is `VectorizedSparkParquetReaders`.

**Comment by nastra** [comment]
The last piece that we need to get in is https://github.com/apache/iceberg/pull/7591

**Comment by amogh-jahagirdar** [comment]
Closing since all relevant code deprecation removals are complete!

**Comment by szehon-ho** [comment]
Thanks so much @amogh-jahagirdar !
