### ISSUE TITLE
Support write to identifier branch when WAP is enabled

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7103]
### Feature Request / Improvement

This is disabled today as noted in https://github.com/apache/iceberg/pull/7050#discussion_r1134707787

quote here:

> I don't think this behavior is a blocker because it is strict, but I would expect to be able to write to another branch with the WAP branch set. I'm curious what other people think the long-term behavior should be.
> 
> I think this behavior does help ensure that there are no side-effects, which is good if you want people to trust the pattern. But that's undermined by enabling/disabling WAP on a per-table basis.

Would love to know what others think.

cc @rdblue @amogh-jahagirdar @namrathamyske @aokolnychyi 

### Query engine

None

**Comment by aokolnychyi** [comment]
If we remove that check, would it mean I can load a table with the branch name and then commit to another branch?
