### ISSUE TITLE
Support to read iceberg table's metadata column with Flink 

### ISSUE THREAD

**Issue by luoyuxia** [apache/iceberg#7110]
### Feature Request / Improvement

Since Flink 1.12, Flink supports to read metadata of table source with [FLIP-107](https://cwiki.apache.org/confluence/display/FLINK/FLIP-107%3A+Handling+of+metadata+in+SQL+connectors), and Flink has an implemententaion for [flink-connnector-kafka](https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSource.java) & [flink-connector-files](https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSource.java).
It'll be valuable for Flink can also read the metadata of iceberg table like file_path,row_pos, etc.
If there is anyone is interested in it, I'm glad to help review. 
If not, I would like to take it.

### Query engine

Flink

**Comment by xuzhiwen1255** [comment]
This is implemented in #6222

**Comment by luoyuxia** [comment]
Thanks @xuzhiwen1255 for your informatin. But I expect read metadata with Flink SQL, like:
```
CREATE TABLE icberg_t(
   id STRING,
   file_path STRING METADATA
) with
 ('connector' = 'iceberge', xxx);

SELECT file_path FROM icberg_t;
```

**Comment by xuzhiwen1255** [comment]
@luoyuxia What does file_path refer to, the path of the table, or the file location
If it's a file location you can look at this https://iceberg.apache.org/docs/latest/spark-queries/#metadata-log-entries

**Comment by xuzhiwen1255** [comment]
If flink implements metadata tables, it should also be able to query them.

**Comment by stevenzwu** [comment]
this is already added by @hililiwei in PR #6222

**Comment by luoyuxia** [comment]
Thanks all for the information. Now I got it. Maybe the issue's title is not clear.  Now I change the title from `Support to read iceberg table's metadata with Flink` to `Support icberge table's metadata column`.

What I mean is that we can implemet `SupportsReadingMetadata`  for `IcebergTableSource` just like `SparkTable` implements `SupportsMetadataColumns`.  So that user can use such Flink SQL to know which file the row comes from by the column `file_path`.
```
CREATE TABLE icberg_t(
   id STRING,
   file_path STRING METADATA
) with
 ('connector' = 'iceberge', xxx);

SELECT  id, file_path FROM icberg_t;
```

**Comment by stevenzwu** [comment]
ah. I see now. for kafka source, the metadata columns could be topic and offset

**Comment by hililiwei** [comment]
This is useful, and we can try to implement it.
