### ISSUE TITLE
Support listing metadata table information in pyiceberg CLI

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7112]
### Feature Request / Improvement

We have a few customer requests for the ability to have a CLI tool that can see Iceberg table information like data files in the table on S3, because they are used to doing `s3 ls s3://table/root` to see files under Hive tables.

The result might be huge but it might be worth implementing a CLI console cursor to display the result for the use case. I would imagine it to be pretty handy for various dev purposes as well.

Any thoughts? @Fokko

### Query engine

None

**Comment by jackye1995** [comment]
> Would you point to a directory, or to a metadata JSON?

I am mostly thinking along the line of supporting something like `pyiceberg show ns.table.files --limit 10` so catalog is still involved. But static table would also work with a metadata JSON.

I just notice that I had the misunderstanding that querying metadata table is already supported in the core library in Python, but seems like it is not supported yet. In that case that is something to add first.

I will try to see if I have time to take this in my spare time, but before I self assign, if other people have bandwidth feel free to take it!

**Comment by Fokko** [comment]
Closing this one for now since the basic operations are in there: https://py.iceberg.apache.org/cli/
