### ISSUE TITLE
Replace Thread.sleep() usage in test code with Awaitility

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#7154]
### Feature Request / Improvement

It would be great to re-visit all `Thread.sleep()` usages in the test code and see which can be converted to [Awaitility](https://github.com/awaitility/awaitility/wiki/Usage)

### Query engine

None

**Comment by zhaomin1423** [comment]
Could you assgin it to me?

**Comment by jackye1995** [comment]
@zhaomin1423 do you still plan to work on this?

**Comment by zhaomin1423** [comment]
> @zhaomin1423 do you still plan to work on this?

Sorry for the late reply, I am busy recently, I am willing to do it, if this affects the progress, you can reassign it.

**Comment by clownxc** [comment]
Can you assign this task to me?

**Comment by coded9** [comment]
@clownxc are you still working on this ?

**Comment by liuxiaocs7** [comment]
Hi, @clownxc, any update with this? Hi, @nastra, i want to have to try if no one works on this now.

**Comment by clownxc** [comment]
> Hi, @clownxc, any update with this? Hi, @nastra, i want to have to try if no one works on this now.

Sorry, I'm sorry. I was too busy a while ago and I'm still happy to do it. I can finish it by this week. Sorry again @coded9 @nastra

**Comment by coded9** [comment]
Let me know if you need a hand @clownxc

**Comment by clownxc** [comment]
> Let me know if you need a hand @clownxc

Sorry, I was on a business trip recently, sorry again for not being able to complete this task on time, you can reassign this task to other interested people @coded9 @liuxiaocs7 @nastra

**Comment by coded9** [comment]
I will pick it up then, @nastra could you assign to me ?

**Comment by KirtiKamal** [comment]
@coded9 have you solved the issue , I am new to this i want to contribute to this

**Comment by atifiu** [comment]
@nastra I just wanted to understand the benefits of Awaitility in place of sleep

**Comment by nastra** [comment]
> @nastra I just wanted to understand the benefits of Awaitility in place of sleep

With a fixed sleep in tests you might wait too long or too short for a condition to happen, which results in either long or flaky tests. With awaitility you can fluently add retry behavior to make tests shorter and more robust.

**Comment by gzagarwal** [comment]
shall i start working on this if it is not worked or picked up

**Comment by nastra** [comment]
@gzagarwal you might want to talk to @coded9 as he also wanted to work on this, although I don't know the current state of this

**Comment by gzagarwal** [comment]
okay let me find something else.

**Comment by shreyanshR7** [comment]
@nastra I tried to implement the above method.

**Comment by shreyanshR7** [comment]
@nastra  please consider the pr #8725

**Comment by nastra** [comment]
I've opened https://github.com/apache/iceberg/pull/8853 and https://github.com/apache/iceberg/pull/8852 to give an idea about places that are good candidates to replace with Awaitility. I believe there are more similar places in the codebase that can be fixed as part of #7154

**Comment by coded9** [comment]
It seems all usages were replaced. Are we good to close this @nastra  ?

**Comment by nastra** [comment]
I think a few other places that would be good to address are all places that use https://github.com/apache/iceberg/blob/main/spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java#L331
