### ISSUE TITLE
how to integrations object storage ceph ?

### ISSUE THREAD

**Issue by jkl0898** [apache/iceberg#7158]
### Question

Hi, we use ceph as object storage. does iceberg support for ceph? 
I had read iceberg's doc, but not found about that. 
iceberg docs: https://iceberg.apache.org/docs/latest/

Thanks!

**Comment by amogh-jahagirdar** [comment]
My understanding is Ceph Object storage is S3 compatible, so one should be able to leverage `S3FileIO` to use Ceph https://iceberg.apache.org/docs/latest/aws/#s3-fileio. Have you looked in to these docs? You can provide the io implementation  `S3FileIO`  for the catalog you are using. Then, I think you should be able to configure the S3 endpoint to be the Ceph object gateway endpoint but I'm admittedly less familiar with Ceph's architecture, maybe it's a different endpoint. someone else more familiar with Ceph can correct me if I'm wrong there.

**Comment by hchautrung** [comment]
Hi @jkl0898 ,

I am looking a solution to use Ceph with Iceberg. Currently I used MinIO but the we looking for an alterantive solution to replace MinIO. Could you share technical detail how to config Ceph with Iceberg. Thanks

**Comment by jkl0898** [comment]
> Hi @jkl0898 ,
> 
> I am looking a solution to use Ceph with Iceberg. Currently I used MinIO but the we looking for an alternative solution to replace MinIO. Could you share technical detail how to config Ceph with Iceberg. Thanks

Hi. refer to amogh-jahagirdar replied please!
