### ISSUE TITLE
presto read iceberg v2 table

### ISSUE THREAD

**Issue by skywalker2256** [apache/iceberg#7169]
Use flink create table and write data into iceberg_db.sample_12!
CREATE TABLE hive_catalog.iceberg_db.sample_12 (
    id BIGINT COMMENT 'unique id',
    data BIGINT ,
    name string ,
   PRIMARY KEY(id) NOT ENFORCED
) PARTITIONED BY (`id`)
 with ('format-version'='2',
'write.upsert.enabled'='true')

when read sample_12 with presto,I get all data. For example:id=1 data duplication
![image](https://user-images.githubusercontent.com/41573491/226837409-70ffa31c-e2aa-4854-8932-c84948250c86.png)
How do I set up?
By the way,can I use flink to develop real-time tasks based on iceberg_db.sample_12?How would I read it if it support,or any other plans?
Thank you very much!

**Comment by luoyuxia** [comment]
Not very sure whether presto can read iceberg v2 format. At least, the [document](https://prestodb.io/docs/current/connector/iceberg.html#iceberg-file-format) of presto haven't said it.
But I think maybe you can try with [trino](https://trino.io/docs/current/connector/iceberg.html) which supports iceberg v2 forma.

**Comment by skywalker2256** [comment]
> Not very sure whether presto can read iceberg v2 format. At least, the [document](https://prestodb.io/docs/current/connector/iceberg.html#iceberg-file-format) of presto haven't said it. But I think maybe you can try with [trino](https://trino.io/docs/current/connector/iceberg.html) which supports iceberg v2 forma.

Thanks,trino supports iceberg v2 format,Thanks!
