### ISSUE TITLE
Can't create iceberg catalog

### ISSUE THREAD

**Issue by Cather0** [apache/iceberg#7170]
### Query engine

Spark

### Question

I'm trying to configure an iceberg dell catalog, connecting the spark to an ecs server. 
But when I try to create the catalog through the spark, following the tutorial I get warns from hiveconf and objectStore, and the spark creates a local db instead of connecting to the ecs.
The warns:
WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist 
WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
WARN ObjectStore:  version information not found in metastore. Hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0

What could cause this?

**Comment by nastra** [comment]
@Cather0 could you please add your entire catalog configuration as this would greatly help understanding how the catalog is configured.

**Comment by Cather0** [comment]
> 

I followed the configuration in the following documentation: https://iceberg.apache.org/docs/latest/dell/

My spark and ecs are already existing, I'm just trying to use the jars to enable a basic catalog

**Comment by nastra** [comment]
Can you describe what issue you're running into? As I mentioned in my previous comment, those warnings aren't harmful and catalog instantiation shouldn't be affected by those
