### ISSUE TITLE
Does JDBC connector uses any retry mechanism?

### ISSUE THREAD

**Issue by lorransr** [apache/iceberg#7173]
### Query engine

Trino

### Question

As mentioned in this [issue](https://github.com/trinodb/trino/issues/16284), we have an aurora serverless database, and we use it as our iceberg catalog. The serverless db scales up and down during the day and can reach to 0 instances, when it happens, all connections are lost. The expected behavior for the jdbc connection in this case would be to try to reconnect to the database, since it will be the trigger for starting the db instances.

Should it be possible to implement this connection retry feature? Or is it expected, the non retry behavior?

**Comment by jackye1995** [comment]
> The serverless db scales up and down during the day and can reach to 0 instances, when it happens, all connections are lost. 

As Amogh suggested the code can definitely be updated to accommodate more exception cases for retry. I guess the question is if there is anything more than just `org.postgresql.util.PSQLException`, like an error code, that can be used to detect the issue? Using error message like "This connection has been closed" seems to be too specific.

**Comment by lorransr** [comment]
It seems to be related to this code:

https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/util/PSQLState.java#L29

Since it is the one used here:

https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L991

**Comment by jackye1995** [comment]
Cool, in that case I think we can add a code change to check that error code and retry. @lorransr unfortunately I am a bit short of capacity, but I can help with review, do you have time to make the code change?

**Comment by lorransr** [comment]
Unfortunnely I don't 😢  And also not sure how

**Comment by netanelm-upstream** [comment]
We are encountering the same problem as well.

**Comment by lorransr** [comment]
I end up solving by ditching the serverless approach and provisioning a common database on aws

**Comment by amogh-jahagirdar** [comment]
I think I have some bandwidth to try and get a fix in for this before next release, I'm assigning to myself

**Comment by cccs-eric** [comment]
> I see the PR didn't make it to a release. Do you need any help with it?

As I [stated ](https://github.com/apache/iceberg/pull/7561#issuecomment-1591804604) in the linked PR, I think those codes should be configurable.  We don't have much cycles to spare on our side right now, but if you can help, that would be great.  We can test your fix easily.

**Comment by kkd927** [comment]
Is there any progress on this issue? I have the same issue.
