### ISSUE TITLE
Add support for Spark 3.4

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#7174]
### Feature Request / Improvement

We should add support for Spark 3.4.

### Query engine

Spark

**Comment by aokolnychyi** [comment]
I am on it.

**Comment by jkolash** [comment]
When can we expect a new 1.2.2 release with this included?  it is not in 1.2.1

**Comment by Fokko** [comment]
@jkolash It is planned for 1.3.0 which is being wrapped up, and should go out for voting any time.
