### ISSUE TITLE
Enforce variable order in checkstyle

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7186]
### Feature Request / Improvement

Not sure if possible, but ideally we want checkstyle to enforce all variables in all classes in the order of
- logger
- `public static final`
- `private static final`
- `private static`
- `private final`
- `private`
- `private transient`
- `private transient volatile`

Any thoughts? @nastra @ajantha-bhat 

### Query engine

None

**Comment by amogh-jahagirdar** [comment]
I think it should be possible, using `DeclarationOrder` https://checkstyle.sourceforge.io/config_coding.html#DeclarationOrder

**Comment by nastra** [comment]
I'm sure this can be enforced but I don't think it's a good idea to do that if we don't have tools that would automatically apply those variable orderings. 
Then you basically have the same problem that we had pre-spotless, where checkstyle would enforce something but you would have to manually go and apply it.
That being said, I generally like the idea of consistent formatting & ordering across the codebase, but I'm not sure this can be easily achieved automatically when formatting code via CMD line / IDE

**Comment by jackye1995** [comment]
>  if we don't have tools that would automatically apply those variable orderings.

I think the argument against that is, even today there are still checkstyle failures that cannot be fixed by spotless. I encountered it a few times but sorry I cannot recall what were the checkstyle errors.

At least my goal is to remove as much need for human-linting as possible. This is one case, there are also cases about styles of newlines that we sometimes still human-lint. If adding some checkstyle rules means we no longer need to check those styles and the developer him/herself has to fix some checkstyle error I am actually fine with that. What do you think?
