### ISSUE TITLE
OPTIMIZE operation prunes data not visible to the table

### ISSUE THREAD

**Issue by ddcprg** [apache/iceberg#7192]
### Feature Request / Improvement

The **OPTIMIZE** job removes data from data files which don't have a column mapped in the table schema.

For example, let's say that there is a table with column A and two data files: one with columns A and B and another file with columns A and C. When the optimize operation runs the optimization job will merge both files into a single file with only colunm A, i.e. data for columns B and C is lost.

We would expect the job to merge the file schemas into a single schema with columns A, B and C to avoid data loss.

### Query engine

Athena

**Comment by RussellSpitzer** [comment]
How would this work with physically deleting data? Does this mean we can never physically remove data from a column once it's been dropped?

**Comment by ddcprg** [comment]
I would control the behaviour with a table property, leave as it is by default. There are cases when dropping  column from the table doesn't necessarily translate to deleting the physical data

**Comment by RussellSpitzer** [comment]
Could you elaborate on your use cases?

**Comment by ddcprg** [comment]
I work for a company that builds software for financial institutions. We get data on Kafka and we deliver it to the data lake. We have built this connector to sink the data to iceberg tables, specifically AWS Athena in parquet format 

https://github.com/10xfuturetechnologies/kafka-connect-iceberg

We sink the data to the blob store keeping the record schema for audibility and we create iceberg tables exposing a subset of the data. However now and then we have to expose additional columns in the table retroactively, i.e. data from records older than the date when the column was added also need to show up in the table. Backfilling would be a very expensive option for us. We usually add columns, so far we haven't had to drop columns from te table but this could be the case in future requirements

**Comment by RussellSpitzer** [comment]
I would argue for your use case you should always just have all the columns in your iceberg table. Keeping around data that doesn't actually belong to the table seems a bit messy. I think it would also complicate schema evolution since these other columns would not have guaranteed field ids. H

**Comment by ddcprg** [comment]
I'm not sure if I understand what you mean by "guaranteed field IDs"for these columns. We've tested keeping the data in the files and then exposing by adding a new column to the table, this seemed to work with no issues. I'll get back to you once I understand more how these IDs are handled. Thanks

**Comment by RussellSpitzer** [comment]
There are two mechinisms,

1. Field Ids, directly mapping a column in a file to a known schema element 
and
2. Default Field Mappings, which map column names to a given field ID which maps to a known schema element

You are most likely using 2 as these files are being added directly to Iceberg and not written by iceberg. This is basically added as a compatibility layer for these files that have been directly imported into Iceberg. You would be able to recover data from a not-iceberg written parquet file with this method, but any files written by iceberg have explicit field ids and don't use 2 to resolve fields.

**Comment by ddcprg** [comment]
Thanks for sharing. I actually use 1, the connector above uses the iceberg API to write the data files but I'm tricking the writer so it sees the column as though it is part of the table schema. Maybe this is a bad thing to do
