### ISSUE TITLE
Python: support virtual addressing style in PyArrowFileIO

### ISSUE THREAD

**Issue by nshagadatov** [apache/iceberg#7219]
### Feature Request / Improvement

I found that pyiceberg is not able to work with files that can be accessed only using virtual addressing style. I want to read table from glue catalog (using default PyArrowFileIO implementation), where metadata and parquet files are located on s3, that supports only virtual addressing style. 

### Query engine

None

**Comment by Fokko** [comment]
Not stale :) cc @danielcweeks

**Comment by Fokko** [comment]
Migrated to: https://github.com/apache/iceberg-python/issues/21
