### ISSUE TITLE
Procedures rewrite_data_files  not work

### ISSUE THREAD

**Issue by liuzx8888** [apache/iceberg#7237]
### Query engine

spark 3.3.2

### Question

schema table:
![image](https://user-images.githubusercontent.com/10862577/228567721-f4d0df39-b9b0-4564-95d6-abdc7d6926a4.png)

execute spark-sql script
`CALL system.rewrite_data_files(table => 'iceberg_test.hz_jzjbxx1', strategy => 'sort', sort_order => 'zorder(hzxm, hzsfzh, blh, ynkh, ybkh, hzid)');`

![image](https://user-images.githubusercontent.com/10862577/228568499-eb8cb0cd-ff2c-4f1c-bf86-2cad26c4f2b8.png)

how can execute Procedures rewrite_data_files  success??

**Comment by RussellSpitzer** [comment]
What files did you expect to be rewritten? Did you check the docs? For example there are several parameters that effect whether or not a partition will have files rewritten. See

https://iceberg.apache.org/javadoc/1.2.0/org/apache/iceberg/actions/BinPackStrategy.html#field.summary

**Comment by RussellSpitzer** [comment]
Yes, right below that table is a list of classes and all of their other options. By default, none of the optimize commands will rewrite the entire table. They only touch files which pass their filters, please read the link I added above. 

If you want to rewrite_all, look carefully and you will see that is one of the options.

**Comment by liuzx8888** [comment]
@RussellSpitzer  Thank you very much,add option it can work
