### ISSUE TITLE
Add checks in create/alter table if table location conflicts

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#7238]
### Feature Request / Improvement

Currently, when user makes multiple tables point to same location, running removeOrphanFiles on one of them will destroy the data of other tables.

Its a known issue, the the concept of table ownership is discussed at: https://github.com/apache/iceberg/issues/4159.  Looks like there are two general directions, either

1. The user explicitly chooses to share table locations among tables (to take more advantage of "write.object-storage.enabled"),  and then instead of using table-level removeOrphanFiles, uses some warehouse-level remove orphan file (not currently in Iceberg OSS project)
2. We discourage sharing of table locations for all other users.

This issue is to achieve the second one.  Initial suggestions (can be changed)

- Create/Alter table can check if there's other tables in catalog with the same location
- Create/Alter table can check if there's any existing files in location.
- This check can be configured at catalog level (?), in case the first option is achieved above and user wants to put tables in same location.

Though its not a perfect fix, it is a useful check to catch increasing problem, and it matches Trino-side fix, eg:  https://github.com/trinodb/trino/pull/12749

### Query engine

None

**Comment by karuppayya** [comment]
Thanks @szehon-ho for creating this issue, I will try to add some validations in the create/alter and remove orphan files flows.
