### ISSUE TITLE
Python: Avro write support

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7255]
### Feature Request / Improvement

In order to write a ManifestList (`List[ManifestFile]`) and ManifestFile (`List[ManifestEntry]`) we need to have the ability to write Avro. 

- Construct the `pyiceberg/avro/encoder.py` that encodes the Python primitives into bytes, according to the Avro spec: https://avro.apache.org/docs/1.11.1/specification/. Also the Python Avro implementation is a good source for inspiration: https://github.com/apache/avro/blob/master/lang/py/avro/io.py#L415
- Similar to the read path, we need to construct a writer, see `resolver.py:construct_reader` for reference, and this will return a `Writer`.
- The writer will accept an Encoder and by passing in `List[ManifestFile]` and `List[ManifestEntry]` we'll be able to write the datums to Avro.

### Query engine

None

**Comment by ggbaro** [comment]
@dariocurr @emanueledomingo @enryls

**Comment by Fokko** [comment]
Fixed in https://github.com/apache/iceberg/pull/7873
