### ISSUE TITLE
Python: Ability to the Metadata JSON

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7257]
### Feature Request / Improvement

In order to do updates, we need to alter the Metadata JSON file to point to the latest ManifestList. To update to the latest version a new snapshot needs to be added, and the current snapshot needs to point to the newly created snapshot.

I did a first version attempt in: https://github.com/apache/iceberg/pull/6323/ @danielcweeks did you have any thoughts on this with respect to the multi-table transactions? The abovementioned PR focusses on table level transactions.

### Query engine

None

**Comment by ggbaro** [comment]
@dariocurr @emanueledomingo @enryls

**Comment by Fokko** [comment]
Not stale :)

**Comment by Fokko** [comment]
Migrated to the new repository: https://github.com/apache/iceberg-python/issues/22
