### ISSUE TITLE
Support commit operations in pyiceberg

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7259]
### Feature Request / Improvement

This will likely come eventually as we support write operation in pyiceberg. Create this issue in case anything is already looking at the implementation. I might take it depending on my time allocation.

We are working on a compactor that will be good to have this feature, related issue: https://github.com/ray-project/deltacat/issues/118

### Query engine

None

**Comment by pdames** [comment]
@jackye1995 Any progress updates or ETA here, or is a link available to track prerequisite work required to close this issue (e.g. milestones, other issues/PRs/docs)?

**Comment by Fokko** [comment]
Hey @pdames Commit operation is in there for the REST catalog: https://py.iceberg.apache.org/api/#create-a-table See the section of `Update table properties`. The schema updates are also underway https://github.com/apache/iceberg/pull/8174
