### ISSUE TITLE
Support data file compaction on branch via Spark `rewrite_data_files` procedure

### ISSUE THREAD

**Issue by amogh-jahagirdar** [apache/iceberg#7272]
### Feature Request / Improvement

There's still some gaps in branch write capabilities, namely being able to run Spark procedures against a branch. This issue is for tracking the support of being able to run `rewrite_data_files` procedure on a specific branch.  

### Query engine

Spark

**Comment by ajantha-bhat** [comment]
Tracked by : https://github.com/apache/iceberg/issues/8762
https://github.com/apache/iceberg/pull/8797

**Comment by relentless-leader** [comment]
Latest PR tracked by: [#12257 ](https://github.com/apache/iceberg/pull/12257)
