### ISSUE TITLE
Broken Unit tests on Windows OS 

### ISSUE THREAD

**Issue by karim-ramadan** [apache/iceberg#7287]
### Apache Iceberg version

main (development)

### Query engine

None

### Problem statement 
Most of the Hadoop/Spark files API use URIs to address resource locations, this solution should work for any OS, but due to some manual URI generation inside of unit tests such as:

`String location = table.table().location().replaceFirst("file:", "");
new File(location + "/data/trashfile").createNewFile();`

and some direct usage of java.io.File instead of URI:

`sql("ALTER TABLE %s ADD PARTITION(id=0) LOCATION '%s'", source, temp.newFolder().toString());`

At the current state, unit tests work only on Unix-based operating systems. 

### Problem solution 
Replace all manual URI generation with Java API and always use URIs when specifying locations.
Here is the solution to the 2 examples: 

`String location = table.table().location();
File trashFile = new File(Paths.get(URI.create(location)).toFile(), "/data/trashfile");
trashFile.createNewFile();
URI trashUri = trashFile.toURI();`

`sql("ALTER TABLE %s ADD PARTITION(id=0) LOCATION '%s'", source, temp.newFolder().toURI().toString());`

**Comment by jackye1995** [comment]
Thanks for bringing this up! Windows compatibility is a known issue that we never get time to address. Are you interested in working on this, or are you asking for the community to address it?

**Comment by karim-ramadan** [comment]
Hi @jackye1995 I'd like to open a PR to fix it, I was also thinking instead of fixing all the problems case by case we could create a class like this 

`
public class UriFileSystem {
  File parent;

  public UriFileSystem(URI uri) {
    this.parent = Paths.get(uri).toFile();
  }

  public UriFileSystem(File file) {
    this.parent = file;
  }

  public UriFileSystem(Path path) {
    this.parent = path.toFile();
  }

  public URI newFolder(String... paths) throws IOException {
    if (paths.length == 0) {
      return parent.toURI();
    }
    File f = parent;
    for (String p : paths) {
      f = new File(f, p);
    }
    f.mkdirs();
    return f.toURI();
  }

  public URI newFile(String name) throws IOException {
    File f = new File(parent, name);
    f.createNewFile();
    return f.toURI();
  }

  public static Stream<URI> listFiles(URI location) {
    return Arrays.stream(Objects.requireNonNull(Paths.get(location).toFile().listFiles()))
        .map(File::toURI);
  }
}
`
Inside the core test module, in this way, we could manage all resources as URIs avoiding silly mistakes and ensuring that in the future tests are always compatible across all OS.
What do you think?
