### ISSUE TITLE
Intermittent CheckStyle Failure on SparkParquetReaders

### ISSUE THREAD

**Issue by dramaticlly** [apache/iceberg#7292]
### Apache Iceberg version

1.2.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

Example failure CI run
https://github.com/apache/iceberg/actions/runs/4633674115/jobs/8199130326?pr=7190

```
* What went wrong:
Execution failed for task ':iceberg-spark:iceberg-spark-3.3_2.12:checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > An unexpected error occurred configuring and executing Checkstyle.
      > java.lang.Error: Error was thrown while processing /home/runner/work/iceberg/iceberg/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
```

But my change in #7190 does not touch that file

**Comment by dramaticlly** [comment]
And close the PR and reopen force the CI to rerun and it now pass all checks (without any code change)

**Comment by dramaticlly** [comment]
Looks like we saw similar problem in #7024 where upgraded to checkstype 9.3 by @ajantha-bhat

**Comment by dramaticlly** [comment]
Looks like we are using code quality plugin released https://github.com/palantir/gradle-baseline/releases/tag/4.42.0 about Nov 2021

**Comment by ajantha-bhat** [comment]
#7024 didn't really fix the issue. 

After analyzing more found the cause. 

https://github.com/apache/iceberg/pull/7139#issuecomment-1477337787

Ned to explore alternative checkstyle plugin and use it.

**Comment by dramaticlly** [comment]
Another occurrence when merging into master https://github.com/apache/iceberg/actions/runs/4640467754/jobs/8212439841

**Comment by stevenzwu** [comment]
another occurrence: https://github.com/apache/iceberg/actions/runs/4645775368/jobs/8221806082

@ajantha-bhat thx for looking into it

**Comment by ajantha-bhat** [comment]
I believe I properly fixed it now. Please review. 
https://github.com/apache/iceberg/pull/7321
