### ISSUE TITLE
identifier-field-ids not supported for Float or double

### ISSUE THREAD

**Issue by officialtushark** [apache/iceberg#7302]
### Question

Why do we not support the identifier-field Ids for Float and Double fields?
Link: https://iceberg.apache.org/spec/#identifier-field-ids
 Is there any specific discussion which I can refer to understand the reasoning behind this implementation?

**Comment by zhongyujiang** [comment]
The main reason is that it is difficult to deal with NaN and -0 values ​​in floating point numbers, you can refer to this [conversition](https://github.com/apache/iceberg/pull/2654#discussion_r651439115).
