### ISSUE TITLE
Support Delete & Update iceberg table with Flink

### ISSUE THREAD

**Issue by luoyuxia** [apache/iceberg#7311]
### Feature Request / Improvement

In #7254, Iceberg supports Flink 1.17.  In Flink 1.17, Flink introuces [delete & update api](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=235838061) to enable external connector  to delete & update data.
I think we can make Flink support delete & update  iceberg data which will be useful to help user manage iceberg by Flink.
If someone may want to take it, I'm glad to help review as the designer of Flink delete & update api.
If not, I'll be happy to take it.

### Query engine

Flink

**Comment by clownxc** [comment]
hi, I would like to give a try on this, can  I take this ticket?I will try my best to complete it

**Comment by luoyuxia** [comment]
@clownxc Sure, feel free to take it.  I'm glad to help review.

**Comment by legendtkl** [comment]
+1 for this

**Comment by linyanghao** [comment]
Hi @clownxc . Is there any progress on this? Thanks!

**Comment by clownxc** [comment]
> Hi @clownxc . Is there any progress on this? Thanks!

I'm working on this task, there will be progress recently😊

**Comment by luoyuxia** [comment]
Hi, just for reference, Pamion has integrated [UPDATE](https://github.com/apache/incubator-paimon/pull/1010) & [DELETE](https://github.com/apache/incubator-paimon/issues/786) for flink-1.17.
Also in previous investagtion,  IIUC, to implement DELETE & UPDATE for iceberg, we may need to finish #7110  first.

**Comment by clownxc** [comment]
> Hi, just for reference, Pamion has integrated [UPDATE](https://github.com/apache/incubator-paimon/pull/1010) & [DELETE](https://github.com/apache/incubator-paimon/issues/786) for flink-1.17. Also in previous investagtion, IIUC, to implement DELETE & UPDATE for iceberg, we may need to finish #7110 first since Iceberg will use the metadata columns, file_path, file_pos to delete data.

i see, thank you very much for your guidance.

**Comment by linyanghao** [comment]
> Hi, just for reference, Pamion has integrated [UPDATE](https://github.com/apache/incubator-paimon/pull/1010) & [DELETE](https://github.com/apache/incubator-paimon/issues/786) for flink-1.17. Also in previous investagtion, IIUC, to implement DELETE & UPDATE for iceberg, we may need to finish #7110 first since Iceberg will use the metadata columns, file_path, file_pos to delete data.

The meta columns are required for UPDATE & DELETE on tables without pk. But for tables with pk, we can UPDATE & DELETE using the pk, which does not rely on https://github.com/apache/iceberg/issues/7110. 
In fact, UPDATE & DELETE in Paimon also only supports tables with pk.

IMHO, we can first support tables with pk. While support for tables without pk can be added later, after https://github.com/apache/iceberg/issues/7110 is finished.
@luoyuxia @clownxc What are your thoughts on this? Thanks!

cc @hililiwei @stevenzwu @chenjunjiedada

**Comment by luoyuxia** [comment]
> > Hi, just for reference, Pamion has integrated [UPDATE](https://github.com/apache/incubator-paimon/pull/1010) & [DELETE](https://github.com/apache/incubator-paimon/issues/786) for flink-1.17. Also in previous investagtion, IIUC, to implement DELETE & UPDATE for iceberg, we may need to finish #7110 first since Iceberg will use the metadata columns, file_path, file_pos to delete data.
> 
> The meta columns are required for UPDATE & DELETE on tables without pk. But for tables with pk, we can UPDATE & DELETE using the pk, which does not rely on #7110. In fact, UPDATE & DELETE in Paimon also only supports tables with pk.
> 
> IMHO, we can first support tables with pk. While support for tables without pk can be added later, after #7110 is finished. @luoyuxia @clownxc What are your thoughts on this? Thanks!
> 
> cc @hililiwei @stevenzwu @chenjunjiedada

Sounds good to me.
