### ISSUE TITLE
Integrate Flink's alter table column  

### ISSUE THREAD

**Issue by luoyuxia** [apache/iceberg#7312]
### Feature Request / Improvement

In #7254, Iceberg supports Flink 1.17. In Flink 1.17, Flink [improves Catalog API to support `ALTER TABLE` syntax](https://cwiki.apache.org/confluence/display/FLINK/FLIP-273%3A+Improve+the+Catalog+API+to+Support+ALTER+TABLE+syntax) which  is useful to help user alter coulmns like add primary constraints,  watermark, etc.
If someone may want to take it, I'm glad to help review.
If not, I'll be happy to take it.

### Query engine

Flink

**Comment by rakesh-das08** [comment]
Hi @luoyuxia can i try my hands on this. Will surely take it to completion.

**Comment by legendtkl** [comment]
+1 for this Feature

**Comment by linyanghao** [comment]
Is anyone currently working on this? If not, I would like to take it.

**Comment by linyanghao** [comment]
@luoyuxia https://github.com/apache/iceberg/pull/7628 is ready for review. Could you take a look at it? Thanks!
