### ISSUE TITLE
how can i use spark-shell Time Travel query a hive catalog table

### ISSUE THREAD

**Issue by hellochueng** [apache/iceberg#7329]
### Query engine

spark-shell

### Question

spark ddl
CREATE TABLE hive_prod.temp.iceberg_hive_test1(id bigint,name string, data string)USING iceberg;

spark-shell
spark.read.format("iceberg").option("start-snapshot-id", "10963874102873")
  .option("end-snapshot-id", "63874143573109").load("**/temp/iceberg_hive_test1").createTempView("t1")
throw Exception
java.io.FileNotFoundException: File does not exist: ***/temp/iceberg_hive_test1/metadata/version-hint.text

**Comment by singhpk234** [comment]
If you are giving a path in the load command, it assumes it's an HadoopTable and hence tries to find the version-hint.text in the metadata path what you can do instead is, directly give the fully qualified table name in the `load()`.

please ref the doc below : 
- https://iceberg.apache.org/docs/latest/spark-queries/#catalogs-with-dataframereader
