### ISSUE TITLE
TableLoader tableLoader = TableLoader.fromHadoopTable(String location, Configuration hadoopConf)  NullPointerException

### ISSUE THREAD

**Issue by zz5440435** [apache/iceberg#7394]
### Query engine

flink

### Question

![图片](https://user-images.githubusercontent.com/131437603/233571387-3db18358-f54e-4e65-ba4b-bb5ee610d758.png)
本地运行正常,   iceberg1.2.1 and flink 1.16.1

**Comment by xuzhiwen1255** [comment]
Can you describe the steps.

**Comment by zz5440435** [comment]
@xuzhiwen1255 https://github.com/apache/iceberg/issues/7394#issuecomment-1518915540 我这边尝试将侧输出流的数据写入到iceberg中, TableLoader.HadoopTableLoader类中的loadTable方法相比之前的版本多了FlinEnvironmentContext.init()方法里面调用EnvironmentContext类, 初步判断EnvironmentContext类问题, 但是我这边尝试重新编译EnvironmentContext增加控制输出并没有发现什么.

**Comment by zz5440435** [comment]
@xuzhiwen1255 
![图片](https://user-images.githubusercontent.com/131437603/233815237-342bdca9-8d70-4a60-8fef-2da0236d53e8.png)
这是我出现异常地方的代码

**Comment by xuzhiwen1255** [comment]
@zz5440435 I can no longer reproduce locally,running and well,  i guess the problem is caused by not getting the flink version.

**Comment by xuzhiwen1255** [comment]
You may need to provide more details.
