### ISSUE TITLE
Some question about zorder

### ISSUE THREAD

**Issue by BsoBird** [apache/iceberg#7405]
### Query engine

spark 3.3.2
iceberg 1.2.1

### Question

1. How should I proceed if I want to keep the ZORDER sort for incremental writes as well?
2. When I do MERGE INTO/UPDATE/DELETE on ICEBERG table, will the ZORDER sorting of MOR table and COW table be disrupted?

**Comment by RussellSpitzer** [comment]
There is currently no way. New data files will not be zordered. That said our zorder is really only valuable in the context of many files being written at the same time.

**Comment by BsoBird** [comment]
Okay,Thanks.
Can we refer to an idea similar to apache kyuubi to process new files to keep the ZORDER sorted?
