### ISSUE TITLE
Question about iceberg partition table

### ISSUE THREAD

**Issue by BsoBird** [apache/iceberg#7406]
### Query engine

spark 3.3.2
iceberg 1.2.1

### Question

My SQL table creation statement and execution SQL are shown below.
```
create table if not exists test_iceberg(
id string,
name string,
created string   --yyyy-MM-dd HH:mm:ss
)
PARTITIONED BY (truncate(4,created))  --I want to use year as partition
STORED AS iceberg;

insert into table test_iceberg select * from source_table;
```
I filtered 4 years of data from the source table, and I found that the Spark job produced four task-skewed TASKs.
![image](https://user-images.githubusercontent.com/30249475/233796345-9adbd3d7-d0e0-46b3-a564-d869c1872428.png)

Currently, my SQL runs for a long time without ending. What should I do to change this?

I don't want to create too many partitions. Partitions speed up queries, but are very unfriendly to writes.

**Comment by BsoBird** [comment]
Can anyone help guide me?
In a batch scenario, currently when I write a large number of partitions, Spark Driver ends up OOM and the task cannot be completed. And when I write a small number of partitions, the parallelism is not fast enough

**Comment by bharos** [comment]
I was exploring a similar issue and found a few things that might be helpful.

The partition skew is mostly happening because of the `write.distribution-mode` config.

By default, it is set to `hash` for partitioned tables using Spark writes. This means that Spark does a shuffle (which is expensive) and assigns each partition to a single task (which is observed in your example).

The benefit of this is that you get large-sized files, which result in smaller metadata files and reduce the small files problem.

One config you can try to speed up the writes is to set `write.distribution-mode` to `None`. This means there is no shuffle, and any task can write to any partition. This can result in a large number of files, which can trigger the small files problem and slower reads. 

I also think there can be an intermediate option, such as setting `write.distribution-mode` to` None` and then repartitioning the data during the Spark write to get more parallelism. You can use `repartition(numPartitions)` or `coalesce(numPartitions)` if applicable, so that you can have more parallelism and still have somewhat larger files.

**Comment by BsoBird** [comment]
@bharos 
Thank you very much for your reply. 
But the solution you mentioned I think there are some problems as follows: 
1. When I write a large number of datasets to a large number of partitions, because we need to write data to a large number of partitions for each TASK, so each TASK will create a lot of FlieWriter objects, which will quickly lead to the OOM of the job.
2.  3. In the above case, we will create a large number of handles on the server, the load on the server will rapidly increase, and the risk of downtime increases. 
4. even if the job can be completed, we will get a bunch of small files, which will lead to a significant drop in performance of analysis tasks based on this table.

If I am using HIVE, when I write to the partition table, I tend to do the following.
···
insert overwrite table partition(part)
select id,name,part from source_table
distribute by part  //or distribute by hash(part)%1024
···
The data is bucketed before it is written to the partition table. Each TASK writes a relatively small number of partitions, so the writes are quite acceptable. 
This SQL statement tends to take longer to run because I redistribute the data.

When `write.distribution-mode=HASH`, ICEBERG works in the same way as the SQL above. 
But the problem is, ICEBERG has hidden partitions, so I can't control the data distribution manually outside. 
And our jobs are basically SQL jobs, our users can't accept to use SPARK API to redevelop their jobs. 
So now the situation is rather awkward.

**Comment by bharos** [comment]
> I don't want to create too many partitions. Partitions speed up queries, but are very unfriendly to writes.
I'm wondering that in your case, if you create more partitions, won't it reduce skew and more distribution of data to tasks with more partitions ?

**Comment by BsoBird** [comment]
@bharos 
The main problem is that the more partitions you have on a table, the slower the writes and the more likely the job is to have problems. Even if you use a non-ACID type job to process the data, you may cause data loss.
So I don't want too many partitions.
For example, I have a 10TB table, if I don't set up partitioning, it will take me 40 minutes to rewrite the whole table.
When I use the year+month partition, it takes me 8-10 hours to rewrite it once.
And, if I don't do a redistribution of the data, my job will immediately report an error when I write a large number of partitions.

**Comment by BsoBird** [comment]
With few partitions, the performance of direct query is really bad. However, we can use ZORDER or ORDER BY to sort the ORC files into order, which can also achieve the effect of DATA-SKIP.

**Comment by bharos** [comment]
I'm not an expert here, but I see the bucket partition transformation mentioned in [writing-to-partitioned-tables  section](https://iceberg.apache.org/docs/latest/spark-writes/#writing-to-partitioned-tables ). Is that something that can help with your case ? I'm thinking if that can help you achieve something similar to what you did in hive case above like `distribute by hash(part)%1024`

**Comment by BsoBird** [comment]
I don't really want to add calculated columns to solve the problem, and to redundant some special fields in order to deal with their own problems, I think this approach is very ugly.

I haven't tried if ICEBERG's hidden partition supports nested functions, let me try

**Comment by BsoBird** [comment]
But with all due respect, setting `write.distribution-mode` on a table property to affect the write behavior of a job seems a bit clunky at the moment.
This will result in a consistent behavior for all details written to the table, but users in some cases will want to control the details of data writes themselves, which is not a small problem.
Although I can not propose a better suggestion for a while, but it is a little inconvenient to use now

**Comment by hellochueng** [comment]
The following sentence is the exact words of the iceberg document

Iceberg requires the data to be sorted according to the partition spec per task (Spark partition) in prior to write against partitioned table

I think this is the reason why writing slant partitions is slow
Partitioned data needs to be sorted and written，So parallelism doesn't work

**Comment by bharos** [comment]
@hellochueng , for you as well, the https://github.com/apache/iceberg/issues/7406#issuecomment-1526757304 about repartitioning doesn't work well ? 
Will it help if you distribute data for the same partition across multiple tasks by repartitioning. It is not optimal but it might help the writes to be faster. But still requires the shuffle phase.

**Comment by atifiu** [comment]
Is it resolved ? I am facing a similar issue when trying to insert data from one iceberg table to another for a single partition. On the contrary inserting using Trino is 3 times faster.

**Comment by BsoBird** [comment]
@atifiu
