### ISSUE TITLE
Spark3.x fails to run the test

### ISSUE THREAD

**Issue by xuzhiwen1255** [apache/iceberg#7413]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

ci: https://github.com/xuzhiwen1255/iceberg/actions/runs/4775773009/jobs/8490338758
local :  
<img width="929" alt="image" src="https://user-images.githubusercontent.com/105710753/233824596-6117f069-dec1-4879-b3e6-86d958169fe4.png">

 I guess it has something to do with  #4479 

In the execution test method testFailReadingCheckpointInvalidSnapshot,a null pointer exception occurred.
The problem code is as follows,
SparkMicroBatchStream#latestOffset().
```java

Snapshot curSnapshot = table.snapshot(startingOffset.snapshotId());
```
Because the snapshot has been cleaned up, the snapshot cannot be obtained when the snapshot is obtained, which leads to a null pointer problem because it is not judged whether the snapshot is null when it is passed down.

**Comment by xuzhiwen1255** [comment]
Is anyone working on this problem synchronously?

**Comment by singhpk234** [comment]
Hey @xuzhiwen1255, have added a pr for the same, https://github.com/apache/iceberg/pull/7414

**Comment by xuzhiwen1255** [comment]
> Hey @xuzhiwen1255, have added a pr for the same, #7414
@singhpk234 Thank you for your contribution. It solved my doubts
