### ISSUE TITLE
DecimalType declaration check missing proper assertions

### ISSUE THREAD

**Issue by akshayjain3450** [apache/iceberg#7420]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

Precision and Scale are two important things when declaring a Decimal. Iceberg currently allows a user to create a Decimal Type with 0 precision. Also, you can create decimals with scale more than precision.

Precision is defined as the number of digits in a Decimal number.
Scale is the number of digits right to the decimal point in a Decimal number.

The conditions for precision and scale are inconsistent with the Mathematical law, and once the user creates such Decimals and the schema is parsed using any other Utility like Avro, they reject this schema allowed by Iceberg.

For eg.
A Decimal Number: 12345.67 has a precision of 7 and a scale of 2.
If you try to think of a number with a precision of 2 and a scale of 7, then it does not exist.

**Comment by aokolnychyi** [comment]
Can we have a summary of what is supported in different languages and engines?

**Comment by akshayjain3450** [comment]
We could definitely dig in there, but my concern is the inconsistency in the checks. AvroSchemaUtils have different checks as compared to the Iceberg Schema Types. 

So, the user is allowed to create a Decimal Type with precision 0 and scale 2 but when the same schema is converted to Avro Schema, the util declines due to the precondition check there. @aokolnychyi  @RussellSpitzer

**Comment by RussellSpitzer** [comment]
Yes that's what we would like some references to, other libraries ability or inability to detail with certain combinations. So we know the landscape. For example, will we get parquet files that we can't read? Can Spark handle this? etc... 

If we have a lot of examples, and ideally a standard we can refer to, then we can make a better decision here.

**Comment by jackye1995** [comment]
According to Oracle Documentation https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements001.htm, in the section of `NUMBER Datatype`:


> Scale can be greater than precision, most commonly when e notation is used. When scale is greater than precision, the precision specifies the maximum number of significant digits to the right of the decimal point. For example, a column defined as NUMBER(4,5) requires a zero for the first digit after the decimal point and rounds all values past the fifth digit after the decimal point.

> It is good practice to specify the scale and precision of a fixed-point number column for extra integrity checking on input. Specifying scale and precision does not force all values to a fixed length. If a value exceeds the p


We probably want to look a bit more into the SQL standard of the definition of Decimal.

**Comment by akshayjain3450** [comment]
According to MySQL and SQL Server which are following SQL Standards: we have this rule as I stated in the discussion.

Please go through this documentation: 

1. https://learn.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-ver16
2. https://dev.mysql.com/doc/refman/8.0/en/precision-math-decimal-characteristics.html

Whereas Postgresql follows the one which Oracle does: https://www.postgresql.org/docs/current/datatype-numeric.html

I still think it's up to us to decide which we should be going with and what should be supported. In any case we go, we should have similar checks all the way to avoid inconsistency as currently it exists.

**Comment by RussellSpitzer** [comment]
Spark seems to have the same restrictions on their DecimalType
```
scala> DecimalType(0,3)
org.apache.spark.sql.AnalysisException: Decimal scale (3) cannot be greater than precision (0).
  at org.apache.spark.sql.errors.QueryCompilationErrors$.decimalCannotGreaterThanPrecisionError(QueryCompilationErrors.scala:1690)
  ```

**Comment by jackye1995** [comment]
Seems like there is a general consensus in most systems about `0 <= s <= p`. 

So for the part of the question about having 0 precision, looks like that is allowed?

**Comment by RussellSpitzer** [comment]
> Seems like there is a general consensus in most systems about `0 <= s <= p`.
> 
> So for the part of the question about having 0 precision, looks like that is allowed?

Allowed in Spark 

scala> DecimalType(0,0)
val res2: org.apache.spark.sql.types.DecimalType = DecimalType(0,0)

**Comment by jackye1995** [comment]
`precision = 1` is not permitted in Trino: https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/type/DecimalType.java#L37

**Comment by rdblue** [comment]
It's reasonable for precision=0 to be disallowed, but there are some cases where precision can be less than scale. Scale is where the decimal point goes, so you can have `decimal(3,2)` like `3.14` or `decimal(3,4)` like `0.0314`. Scale can also be negative to encode small precision large numbers, like `decimal(3, -4)` and `3140000`.

We should go with the SQL spec, but it may be that these are valid even if Trino doesn't support them.

**Comment by jackye1995** [comment]
Is this the formal definition of the SQL spec? Does anyone have a formal definition of decimal from ANSI?

**Comment by akshayjain3450** [comment]
I do not have the formal definition, but spark-sql tries to conform with ANSI compliance if you enable this property: spark.sql.ansi.enabled=true.

With this property: 
I have these results:

scala> DecimalType(0,0)
res3: org.apache.spark.sql.types.DecimalType = DecimalType(0,0) as mentioned by @RussellSpitzer 

scala> DecimalType(2,3)
org.apache.spark.sql.AnalysisException: Decimal scale (3) cannot be greater than precision (2).

scala> DecimalType(2, -3)
org.apache.spark.SparkException: [INTERNAL_ERROR] Negative scale is not allowed: -3. Set the config "spark.sql.legacy.allowNegativeScaleOfDecimal" to "true" to allow it.

**Comment by jackye1995** [comment]
Cool. In that case @rdblue @RussellSpitzer what do you think? Should we comply with ANSI on this? 

From usability perspective, given that non of the underlying file formats or query engine supports `p < s` or `s < 0`, I think it's probably more convenient to just throw error upfront for now, and if there is something that can back decimal with a wider definition that Iceberg support, we can always update that definition in the future.

**Comment by RussellSpitzer** [comment]
I mainly just don't want to break anything that is currently working (even if the definition of the type doesn't make sense), If the types wouldn't work in the file formats or in the engines we use to query them, I think it's fine to add more assertions. Do we need to define this in the spec as well?

**Comment by jackye1995** [comment]
> Do we need to define this in the spec as well?

I feel we should? because this kind of data type definition check should be based on the spec

**Comment by akshayjain3450** [comment]
Is there a final conclusion to this: @rdblue

**Comment by akshayjain3450** [comment]
Hi, I am still waiting for a reply on this issue. @rdblue @RussellSpitzer @aokolnychyi
