### ISSUE TITLE
Typo in Spark Read Option Vectorization Javadoc

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#7438]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

https://github.com/apache/iceberg/blob/master/spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java#L59

Wrong Javadoc for this property

**Comment by RussellSpitzer** [comment]
Needs to be fixed in all Spark versions

**Comment by vishnukumarsinha** [comment]
Hi @RussellSpitzer , for this issue we just need to update the comment 
`Overrides the table's read.split.open-file-cost` to `Overrides the table's read.parquet.vectorization.vectorization-enabled`, right?

**Comment by RussellSpitzer** [comment]
I think it also would override the ORC vectorization code path as well, should quickly check that as well, but you are correct

**Comment by vishnukumarsinha** [comment]
then can I raise a PR for it? let me know.

**Comment by RussellSpitzer** [comment]
Go for it
