### ISSUE TITLE
ExpireSnapshots break on top of PR https://github.com/apache/incubator-iceberg/pull/695

### ISSUE THREAD

**Issue by mehtaashish23** [apache/iceberg#744]
Apart from cleaning up deleted dataFiles while expiring snapshot, the current ExpireSnapshots [code here] tries to delete underlying files added by dangling snapshots i.e. that is not parent of anybody.

With cherrypick feature with WAP, the approach is to generate a new snapshot with dataFiles of underlying WAP snapshot, and commit it on top of latest/current snapshot. This makes the WAP snapshot dangling, and when you expire this snapshot then underlying dataFiles are deleted, and making the table un-readable. Please see the gist here https://gist.github.com/mehtaashish23/fb87c57d13de8f9f56b5a1516265bfff which try to reproduce this, on top of PR https://github.com/apache/incubator-iceberg/pull/695

[code here] : https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L234

**Comment by rdblue** [comment]
Good catch, @mehtaashish23!

The snapshot expiration code will need to detect picked snapshots and ignore them. @prodeezy, do we keep the picked snapshot ID in the summary metadata? If not, we should add it for this purpose.

**Comment by prodeezy** [comment]
right .. we should add it in the published snapshot's summary for other operations like ExpireSnapshots to lookup.

**Comment by mehtaashish23** [comment]
+1, I was trying to come up with a fix, but noticed, that we do track `published-wap-id` in cherrypick commit, but don't currently track the WAP's original snapshotId.

**Comment by prodeezy** [comment]
@mehtaashish23  do you have a preference on what the summary property should be called?  For instance: `source-snapshot-id` ?

**Comment by mehtaashish23** [comment]
@prodeezy I was thinking about `cherrypick-snapshot-id`, but I wonder `source-snapshot-id` is better and extendable name. I would go with `source-snapshot-id` if no-one has any concern.

**Comment by rdblue** [comment]
Either one sounds good to me!

**Comment by bachar84** [comment]
Re-write

**Comment by bachar84** [comment]
Re-write

**Comment by mehtaashish23** [comment]
I was planning to do code changes for this, and the approach will be following

1. If you are expiring a stagedSnapshot, then a) if its referred by a snapshot, which is part of ancestor list of current table, then the underlying data isn't deleted. b) If not then its deleted.
2. If you are expiring a snapshot (say S1) which refer to another snapshot via property `source-snapshot-id` (say B1) then both of them are expired to avoid problems in future. By problem, I mean, if we don't do this, then client can expire S1 first, and then expire B1 (which will be detected as dangling, if S1 is not in Ancestor list)

Let me know, if you have any concerns. Thanks!

**Comment by rdblue** [comment]
@mehtaashish23, I think it is a little simpler than that because we know that snapshots will only reference older snapshots.

Say I have snapshots A <- B <- C and my current table state is B. If I pick C on top of B to create D(C), then I know D must have come after D. If we also assume that the changes in C are identical to D, but with a different parent, then we can handle expiration fairly easily. First, if C is the source-snapshot-id for any known snapshot then we skip it during expiration. The same set of changes will be expired by D. Second, when we expire D, we don't need to look for C because it expired first. These rules also work regardless of the current table state and its ancestors.

I think it would be okay to say that if D expires then C also expires, but it shouldn't be necessary.

**Comment by mehtaashish23** [comment]
Thanks @rdblue for explaining. Correct me if I am wrong but, IIUC there is an API [expireSnapshotId here], which can expire any snapshot by id. So my above cases is to handle if someone uses that API to expire snapshot. For example. in your scenario, if someone used this expireSnapshotId then
1) If C is marked expired, then no dataFiles are deleted, since its in some other's `source-snapshot-id`
2) if D is marked expired, then C has to also marked expired. Since if we keep around C, then someone can come back again using this API to expire C, which won't be referred by anyone, as D was already expired before.

Does that make sense? For all other API i.e. `expireOlderThan` and `retainLast` I expect that C would be expired before D, and your explanation makes perfect sense in that, and my changes would handle that.

There is another API `deleteWith` with a UDF passed in, which I suppose is onus of client to maintain consistency.

[expireSnapshotId here]: https://github.com/apache/incubator-iceberg/blob/master/api/src/main/java/org/apache/iceberg/ExpireSnapshots.java#L48

**Comment by mehtaashish23** [comment]
Raised PR https://github.com/rominparekh/incubator-iceberg/pull/3 on top of feature being currently build out by @prodeezy , @rominparekh

**Comment by rdblue** [comment]
@mehtaashish23, you're right about the need to find a fix given that snapshots can be specifically expired. I'm thinking about it and will update here when I have a clearer picture of what we need to do in my head. I at least agree with your point 1, but I'm not sure that point 2 is sufficient.
