### ISSUE TITLE
Simplify JDK build versions using --release flag

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7440]
### Feature Request / Improvement

Currently we run CI for each JDK version (8, 11, 17). As discussed on devlist https://lists.apache.org/thread/hr7rdxvddw3fklfyg3dfbqbsy81hzhyk, it is unlikely for Iceberg to move to higher Java versions because of downstream dependency.

However, we could technically use the highest version of Java to build, and use `--release` flag to enforce that it uses only JDK8 language features.

This requires changes in the gradle build, CI configurations and release script configurations.

Once it is done, we can run all CIs directly in the latest JDK version, and be confident that it won't break JDK8.

### Query engine

None

**Comment by jackye1995** [comment]
In that case, feels like we could technically already remove all the DJK8 CIs and default to just run on JDK11 or 17? Is everyone good with that? @aokolnychyi @flyrain @boroknagyz @amogh-jahagirdar @laurentgo

**Comment by laurentgo** [comment]
We can choose to default to 17 for the build, but hive would still need to use java 8 to at least run tests, and we may also want to run tests in general with Java 8 as a compatibility measure?

**Comment by jackye1995** [comment]
when you say Hive, do you mean any tests involving Hive metastore, or just `iceberg-hive3` tests?
