### ISSUE TITLE
Python: Add `__repr__` to Table

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7442]
### Feature Request / Improvement

Currently:

![image](https://user-images.githubusercontent.com/1134248/234699970-ef5d5c15-c8c2-4105-80a3-ea8c86fc3d11.png)

Many libraries have nice `repr`s for their table. As a community, we decide what to include in the `repr`. For example, Arrow one also shows a summary of data, but this would mean that we need to plan and fetch. And then implement it.

### Query engine

None

**Comment by DarthData410** [comment]
Hey @Fokko let me know if I can help out here, or any other areas for Python

**Comment by Fokko** [comment]
Has been fixed in https://github.com/apache/iceberg/pull/8447
