### ISSUE TITLE
Expose data and file sequence numbers on ContentFile or ContentScanTask

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#7449]
### Feature Request / Improvement

We should expose data and file sequence numbers on `ContentFile` or `ContentScanTask`.

### Query engine

None

**Comment by gaborkaszab** [comment]
Thanks for opening this issue, @aokolnychyi ! Is there any one working on this? If not, I can take a look.

**Comment by jackye1995** [comment]
assigned to you!

**Comment by aokolnychyi** [comment]
PR #5760 is relevant. However, it seems to cover more than what we need, so it may be a good idea to just focus on exposing what we currently have.

**Comment by aokolnychyi** [comment]
@gaborkaszab, I took a look at that PR and I believe the primary goal is different. Would you be interested to create a separate PR to expose data and file sequence numbers? I'd try to expose it on `ContentFile` first. If too complicated, we can consider doing this on `ContentScanTask`. I think #5760 contains a reasonable idea of doing this in `InheritableMetadata`. We can add @chenjunjiedada as co-author if you decide to reuse some parts.

**Comment by rdblue** [comment]
@gaborkaszab, can you link your PR here?

**Comment by gaborkaszab** [comment]
Thanks for taking a look at this! Sure, I can create a separate PR to simply focus on exposing the sequence numbers through ContentFile or if it's not that straightforward then on ContentScanTask. I don't have anything ready atm, though. I see this item is added to 1.3.0. I wonder if this is because someone is expecting this change asap. Frankly, I'll have time to take care of this somewhere around next week so if there is no real time pressure on this, we could push this out with one release.

**Comment by stevenzwu** [comment]
will rebase the JSON parser PR #6934 after this.

**Comment by aokolnychyi** [comment]
This logic is also required for rewriting position deletes. We promised it a long time ago and shouldn't be that hard to implement. I can look into it, probably, this week. Let me know if you start working on it earlier, @gaborkaszab.

**Comment by gaborkaszab** [comment]
Good to know there is a need for this :) I started looking into now, will let you know once I have anything to share.

**Comment by gaborkaszab** [comment]
Just an FYI: I have a WiP PR, making some test changes and will submit a PR this weekend or early next week.

**Comment by aokolnychyi** [comment]
Sounds good, @gaborkaszab! Could you link it here once the PR is up?

**Comment by gaborkaszab** [comment]
Removed this from the 1.3.0 milestone to reduce noise, as the PR is also added to the milestone items.

**Comment by aokolnychyi** [comment]
Resolved by PR #7555.
