### ISSUE TITLE
spark insert partition table Data skew

### ISSUE THREAD

**Issue by hellochueng** [apache/iceberg#7455]
### Query engine

spark

### Question

use spark3.3 iceberg 1.2
insert into partition table,Large amount of data in one partition
doc
![image](https://user-images.githubusercontent.com/29030883/235065890-053b3519-a38b-4db2-b4e7-631756e26d23.png)
Iceberg requires the data to be sorted according to the partition spec per task (Spark partition) in prior to write against partitioned table. This applies both Writing with SQL and Writing with DataFrames.
![image](https://user-images.githubusercontent.com/29030883/235097804-6e501662-55b3-44e3-84b9-37bea8e5970b.png)

The problem of slanting data writing occurred in my job

how can i solve this problem

**Comment by BsoBird** [comment]
Hey, dude. Looks like you and I are having the same problem. Why don't you come over here and we'll discuss it?
https://github.com/apache/iceberg/issues/7406
