### ISSUE TITLE
Python: Add code highlighting

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7459]
### Feature Request / Improvement

It looks like we lost the colors on the code:
![image](https://user-images.githubusercontent.com/1134248/235121068-b83d3200-9755-4f5e-b0a2-3146af5b828c.png)

Now everything is gray and makes it a bit harder to read.

### Query engine

Other

**Comment by DarthData410** [comment]
Feel free to assign this to me, and I will get this completed.

**Comment by DarthData410** [comment]
Alright so this is a theme configuration in mkdocs.yml was not completely setup for python code highlighting, pure the theme being used 'material'.
mkdocs-material theme: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=highlight+js#highlight

 
![Screenshot from 2023-04-30 18-01-57](https://user-images.githubusercontent.com/119692461/235380033-43e7a48c-8ea9-4984-8285-5d00c93f716e.png)

Have a look at what I generated, after applying the correct updates for the mkdocs.yml file. The code highlighting is now in place.

**Comment by Fokko** [comment]
Nice! Works on my side as well, thanks for digging into this @DarthData410 

![image](https://user-images.githubusercontent.com/1134248/235418121-5a7a72b3-a0d0-48ff-9251-c87fcdbca1bd.png)
