### ISSUE TITLE
Predicate Pushdown Not Working as Expected

### ISSUE THREAD

**Issue by matthewwillian** [apache/iceberg#7461]
### Query engine

Glue 3.0

### Question

I have the following query
```
        results_df = spark.sql(f'''
MERGE INTO {args["catalog"]}.{args["database"]}.{args["output_table"]} t
USING (SELECT * FROM {NEW_EVENTS_DATA_VIEW}) s
ON (s.client_id = t.client_id AND
    s.foo = t.foo AND
    s.bar = t.bar AND
    s.timestamp = t.timestamp AND
    s.baz = t.baz AND
    s.id = t.id)
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *''')
```
that is merging into a table with the following schema
```
# Table schema:		
# col_name	data_type	comment
id	string	
foo	string	
bar	string	
baz	string	
timestamp	timestamp		
		
# Partition spec:		
# field_name	field_transform	column_name
foo	identity	foo
bar	identity	bar
baz	identity	baz
timestamp_day	day	timestamp
```
When I run this query, the spark query plan appears to show that predicate pushdown is not happening on the `timestamp_day` partitions. Is that intended behavior?

**Comment by RussellSpitzer** [comment]
What's the plan, and why would there be a pushdown on timestamp_day? The pushdown would be on timestamp which Iceberg would then convert to an expression on timestamp_day

**Comment by matthewwillian** [comment]
Attaching the query plan
[query_plan.txt](https://github.com/apache/iceberg/files/11355981/query_plan.txt)

**Comment by RussellSpitzer** [comment]
Oh so you are looking for dynamic runtime partition pruning?

**Comment by matthewwillian** [comment]
If by that you mean what's described in this article then yes https://medium.com/@prabhakaran.electric/spark-3-0-feature-dynamic-partition-pruning-dpp-to-avoid-scanning-irrelevant-data-1a7bbd006a89. Will it work if I just enable that config in my Spark job? If so, are there tradeoffs to consider when enabling that config?
