### ISSUE TITLE
Inconsistent API for remove_orphan_files and DeleteOrphanFiles

### ISSUE THREAD

**Issue by sushi30** [apache/iceberg#7480]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

According to iceberg docs. There are two methods for running spark procedures:
1. SQL
2. Spark Actions

For [remove_orphan_files](https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files) it appears that the SQL procedure has the `max_concurrent_deletes` parameter which does not exist in the spark action [DeleteOrphanFiles](https://iceberg.apache.org/javadoc/1.2.0/org/apache/iceberg/actions/DeleteOrphanFiles.html).

While it is theoretically possible to imitate the SQL behavior using `executeDeleteWith`, the method that is used under the hood is a private method [`removeService`](https://github.com/apache/iceberg/blob/4d54f4cf8f19f74a8f2463f4b10a7c39ba417d14/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java#L160-L166). Therefore this is not possible and it creates a discrepancy in the APIs.

**Comment by dramaticlly** [comment]
I dont think there's guarantee for keeping the API consistent between iceberg SparkAction and SparkProcedure. The Procedure can be exposed and used by client who's more familiar with SparkSQL interface while SparkAction provide more versatile capabilities to allow native integration in java or scala. 

If you want to run multithreading delete in spark 3.1 actions, this is how it can be done below in scala/java

```scala
import org.apache.iceberg.Table
import org.apache.iceberg.actions.DeleteOrphanFiles
import org.apache.iceberg.spark.actions.SparkActions
import org.apache.spark.sql.SparkSession

import java.util.concurrent.{Executors, TimeUnit}

class RemoveOrphansAPI {

  def removeOrphansWithSparkAction(
      sparkSession: SparkSession,
      table: Table,
      threadsCount: Int,
      olderThanTS: Long
  ): DeleteOrphanFiles.Result = {

    val executor = Executors.newFixedThreadPool(threadsCount)
    val result: DeleteOrphanFiles.Result = SparkActions
      .get(sparkSession)
      .deleteOrphanFiles(table)
      .olderThan(olderThanTS)
      .executeDeleteWith(executor)
      .execute()

    executor.shutdown()
    result
  }
}
```
