### ISSUE TITLE
Is is possible to control the number of partitions (groups) for compaction ?

### ISSUE THREAD

**Issue by dmgcodevil** [apache/iceberg#7506]
### Query engine

Trino

### Question

I've found a new compaction option `max-file-group-size-bytes` which is very useful b/c it allows compacting very large data sets while using sorting. However, is there an option to control a max number of groups (partitions)? I could not find it. It could be useful in a case where a lot of partitions should be compacted. We'd like to limit the execution time of our compaction spark job.

**Comment by singhpk234** [comment]
> It could be useful in a case where a lot of partitions should be compacted. We'd like to limit the execution time of our compaction spark job.

You can pass a partition filters via the `where` clause to run compaction on a subset of partitions. please ref (https://iceberg.apache.org/docs/latest/spark-procedures/#rewrite_data_files)

**Comment by dmgcodevil** [comment]
@singhpk234 is `where` only available when using [Iceberg SQL extensions](https://iceberg.apache.org/docs/latest/spark-configuration#sql-extensions) ?

We are using `BaseRewriteDataFilesSpark3Action`:

Example:

```scala
    val result = SparkActions.get().rewriteDataFiles(table)
      .filter(Expressions.greaterThanOrEqual(field, startDate * 1000))
      .filter(Expressions.lessThan(field, endDate * 1000))
      .option("target-file-size-bytes", String.valueOf(config.targetSizeMB * 1024 * 1024))
      .option(RewriteDataFiles.MAX_FILE_GROUP_SIZE_BYTES, String.valueOf(1024L * 1024L * 1024L * 10L)) // 10 Gigabytes
      .option(RewriteDataFiles.PARTIAL_PROGRESS_MAX_COMMITS, "20")
      .option(RewriteDataFiles.PARTIAL_PROGRESS_ENABLED, "true")
      .execute()
```
