### ISSUE TITLE
Add an option to decide whether to delete data files in Catalog.dropTable()

### ISSUE THREAD

**Issue by waterlx** [apache/iceberg#751]
I would like to propose to modify Catalog.dropTable() to add an option to decide whether to delete data files when dropping the table, like:
```
  /**
   * Drop a table; optionally delete data and metadata files.
   * <p>
   * If purge is set to true the implementation should delete all data and metadata files.
   *
   * @param identifier a table identifier
   * @param purge if true, delete all data and metadata files in the table
   * @param deleteData ignored if purge is false; 
                     If purge is true and deleteData is true, delete all data and metadata files in the table
                     If purge is true and deleteData is false, delete all metadata files while keep all data files
   * @return true if the table was dropped, false if the table did not exist
   */
  boolean dropTable(TableIdentifier identifier, boolean purge, boolean deleteData);
```
The proposal above is trying to meet the following requirement:
We are in process of implementing update and delete. A staging table is introduced and its data files are referenced by the base table's manifest. When dropping the staging table (as the last step of update or delete operation), we would like to purge the metadata of the staging table while keep its data files.

**Comment by waterlx** [comment]
@rdblue does it make any sense to you?

**Comment by rdblue** [comment]
I think you're saying you want a purge option that deletes metadata, but not data?

I'm very reluctant to add cases like this to the API. We want to keep the API small, and I think this may be specific to your use case. What about doing this in the application that creates the staging tables instead? You'd set purge=false when dropping the table and then clean up the metadata using your own code. Would that work?

**Comment by waterlx** [comment]
@rdblue got your idea. Thanks!
I might need to check with you about the expected behavior of dropTable, especially when purge = false.
Catalog # dropTable() defines the behavior to handle metadata and data when purge = true explicity, as 
```
* @param purge if true, delete all metadata and data files in the table
```
But what about purge = false? 
(1) keep both data and metadata
or
(2) keep data and delete metadata

(1) is the current behavior of Iceberg. But is it the expected behavior? I might think that (2) is the correct behavior: When I am calling dropTable,  metadata is deleted for sure, while purge is used to determine if data files are deleted or not.

Could you please share your idea about that? Thanks!
I am trying to check the behavior of Spark or Hive regarding dropTable with purge = false.

**Comment by rdblue** [comment]
I think that keeping both data and metadata is the correct behavior. That way, drop removes a reference to the table, but the table itself is still readable should you wish to recover it. If Iceberg were to drop metadata, then it would be extremely difficult to actually use the data files that are left if you wanted to recover the table.

**Comment by waterlx** [comment]
@rdblue got your idea. Thanks!
