### ISSUE TITLE
How can I use Glue catalog  in EMR 6.10.0 without catalog name

### ISSUE THREAD

**Issue by ryu3065** [apache/iceberg#7512]
### Query engine

EMR 6.10.0 
Spark 3.3.1
Iceberg 1.1.0-amzn-0

apply spark options

'spark.sql.extensions': 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions',
'spark.sql.catalog.{catalog}': 'org.apache.iceberg.spark.SparkCatalog',
'spark.sql.catalog.{catalog}.catalog-impl': 'org.apache.iceberg.aws.glue.GlueCatalog',
'spark.sql.catalog.{catalog}.warehouse': '{S3_bucket_location}/spark_iceberg/',
'spark.sql.catalog.{catalog}.io-impl': 'org.apache.iceberg.aws.s3.S3FileIO',
'spark.sql.catalog.{catalog}.lock-impl': 'org.apache.iceberg.aws.dynamodb.DynamoDbLockManager',
'spark.sql.catalog.{catalog}.lock.table': '{My_Lock_Table_Name}',

### Question

How can I use Glue catalog with Iceberg in EMR 6.10.0 and reference tables in the format of `{database}.{tables}` like Athena without using a custom catalog name?

ex) 
`{catalog}.{database}.{table}` -> `{database}.{table}` 
select * from spark_sql.db.tbl1  -> select * from db.tbl1

plz help :)

**Comment by akshayakp97** [comment]
Hi! 

I use the Spark's built-in catalog - 

```
"spark.sql.extensions":"org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions",
"spark.sql.catalog.spark_catalog":"org.apache.iceberg.spark.SparkSessionCatalog",
"spark.sql.catalog.spark_catalog.io-impl":"org.apache.iceberg.aws.s3.S3FileIO",
"spark.sql.catalog.spark_catalog.catalog-impl":"org.apache.iceberg.aws.glue.GlueCatalog",
```

And, then I can do ``select * from db.tbl1``

**Comment by ryu3065** [comment]
@akshayakp97 
Oh! It works well. Thank you so much :)

Have a nice day.
