### ISSUE TITLE
Why did the bot do this?

### ISSUE THREAD

**Issue by sri-ka1kiZ** [apache/iceberg#7521]
### Question

I'm not understanding why the depenabot did this.

See attached 

![Screenshot_20230503-185510_Chrome](https://user-images.githubusercontent.com/104856737/236094764-a49a75d6-5a2f-4c0a-9b4f-16c30db05908.jpg)

**Comment by nastra** [comment]
This is because there is a configuration file for GitHub's Dependabot in Iceberg (and also in your fork). You can disable Dependabot in your fork of Iceberg: 

![image](https://user-images.githubusercontent.com/271029/236125350-4b7588b2-3131-4c4b-ad83-11fe00a5582d.png)
