### ISSUE TITLE
Improve retry algorithm for Tasks

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7528]
### Feature Request / Improvement

Currently we just use exponential backoff. In practice when there are many concurrent writes, the conflict rate is still high even with jitter. There are some other algorithms like AIMD that was proven to be effective, and might be worth considering to add to Tasks to retry commits.

Reference: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-emrfs-retry.html

### Query engine

None

**Comment by singhpk234** [comment]
+1 for this, it will be awesome if we could make the retry pluggable as well :) !
