### ISSUE TITLE
Error reading version hint file

### ISSUE THREAD

**Issue by getAlexRibeiro** [apache/iceberg#7537]
### Query engine

PySpark 3.1.2 and hadoop 3.0.0 and iceberg-spark-runtime-3.1_2.12-0.13.1.jar

### Question

Hello there strangers!

I'm using PySpark 3.1.2 and hadoop 3.0.0 and iceberg-spark-runtime-3.1_2.12-0.13.1.jar on my SparkSession config.

When running my test im getting the error mentioned in the title: WARN HadoopTableOperations: Error reading version hint file ../../../../warehouse/catalog/my-table/metadata/version-hint.text

And further:  File "C:\Users\alexandre.ribeiro\AppData\Roaming\Python\Python310\site-packages\py4j\protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o40.table.
: java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z

Any idea?

Thxs

**Comment by BhavanaRK17** [comment]
Did you find a solution to this issue?
