### ISSUE TITLE
upsert mode : when total-equality-deletes value can be clear ?

### ISSUE THREAD

**Issue by lichaohao** [apache/iceberg#7540]
### Query engine

spark

### Question

i test ,in upsert mode , although execute rewrite_data_files  , expire_snapshots , rewrite_manifests ,  total-equality-deletes value can not be clear 。 
before :  total-equality-deletes  =1009 
after  total-equality-deletes = 1009

once total-equality-deletes appears , it will exists all the time ?

**Comment by singhpk234** [comment]
yes / no, there are some cases where it can dropped, Here is a proposal for removing dangling delete files https://docs.google.com/document/d/11d-cIUR_89kRsMmWnEoxXGZCvp7L4TUmPJqUC60zB5M/edit.

**Comment by lichaohao** [comment]
> yes / no, there are some cases where it can dropped, Here is a proposal for removing dangling delete files https://docs.google.com/document/d/11d-cIUR_89kRsMmWnEoxXGZCvp7L4TUmPJqUC60zB5M/edit.

hello，When a delete operation occurs ，a sequence number at which step was it generated and how was it generated?

Thanks a lot

**Comment by lichaohao** [comment]
done
