### ISSUE TITLE
dynamic write partition with an extra shuffle 

### ISSUE THREAD

**Issue by langchao209** [apache/iceberg#7541]
### Apache Iceberg version

1.2.0

### Query engine

Spark

### Please describe the bug 🐞

When over writing iceberg table with dynamic partitions, spark sql will generate an extra shuffle to partition data by the partition column before writing to the table. This can make all data processed by only one task when the partition contains only a single value. 

With Hive, we can disable this by setting hive.optimize.sort.dynamic.partition to false.
How can I disable this feature?

However, org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.1.0 is OK for me by default.

**Comment by RussellSpitzer** [comment]
https://github.com/apache/iceberg/pull/7499

Docs explaining




https://github.com/apache/iceberg/issues/6679

Issue where we made the change

**Comment by langchao209** [comment]
Thanks @RussellSpitzer. How can I change the table property when writing with SQL statement?

**Comment by RussellSpitzer** [comment]
Alter table properties
