### ISSUE TITLE
How to ensure the data is not repeated when using spark to write to the iceberg table

### ISSUE THREAD

**Issue by saimigo** [apache/iceberg#7554]
### Query engine

Spark

### Question

Assuming that there are two rows of data as follows, we think that these two data are the same data, so how to avoid duplication of data in the Iceberg table when using spark to write data？

("2023-04-25 08:00:00.000000",  "Name 1",  "Note 1")
("2023-04-25 08:00:00.000000",  “Name 1",  "Note 2")

**Comment by Fokko** [comment]
@saimigo Are you appending the data, or overwriting? In the case of the first, you can call [`.dropDuplicates` using Spark](https://spark.apache.org/docs/3.1.2/api/python/reference/api/pyspark.sql.DataFrame.dropDuplicates.html). In the case of incremental data, you need to perform a [merge operation](https://iceberg.apache.org/docs/latest/spark-writes/#merge-into).

**Comment by saimigo** [comment]
> @saimigo Are you appending the data, or overwriting? In the case of the first, you can call [`.dropDuplicates` using Spark](https://spark.apache.org/docs/3.1.2/api/python/reference/api/pyspark.sql.DataFrame.dropDuplicates.html). In the case of incremental data, you need to perform a [merge operation](https://iceberg.apache.org/docs/latest/spark-writes/#merge-into).

Appending the data, If I use the merge into operation, do I need to create a new table every time, and then delete this table after merging?

**Comment by jhchee** [comment]
@saimigo Merge into command is executed based on certain condition. A common use case is to use it for `UPSERT` operation. E.g. 
```sql
MERGE INTO target t   -- a target table
USING source s        -- your source (can be a table)
ON t.id = s.id                -- condition to find updates for target rows (can be your unique identifiers)
WHEN MATCHED UPDATE *
WHEN NOT MATCHED INSERT *
```
To address few questions, 
1. You don't have to delete the table.
2. Be in mind, Spark engine will perform join based on condition you define. This means it requires to read from a table to find the matching row, so the target table must exist in the first place.

**Comment by saimigo** [comment]
> @saimigo Merge into command is executed based on certain condition. A common use case is to use it for `UPSERT` operation. E.g.
> 
> ```sql
> MERGE INTO target t   -- a target table
> USING source s        -- your source (can be a table)
> ON t.id = s.id                -- condition to find updates for target rows (can be your unique identifiers)
> WHEN MATCHED UPDATE *
> WHEN NOT MATCHED INSERT *
> ```
> 
> To address few questions,
> 
> 1. You can to guarantee uniqueness of your data by dropping duplicates in the source's Spark Dataframe or by doing UPSERT against the target table.
> 2. You don't have to delete the table when doing UPSERT.
> 3. Be in mind, Spark engine will perform join based on condition you define. This means it requires to read from a table to find the matching row, so the target table must exist in the first place.

Thank you very much, I need to learn more about this.

**Comment by saimigo** [comment]
> @saimigo Merge into command is executed based on certain condition. A common use case is to use it for `UPSERT` operation. E.g.
> 
> ```sql
> MERGE INTO target t   -- a target table
> USING source s        -- your source (can be a table)
> ON t.id = s.id                -- condition to find updates for target rows (can be your unique identifiers)
> WHEN MATCHED UPDATE *
> WHEN NOT MATCHED INSERT *
> ```
> 
> To address few questions,
> 
> 1. You can to guarantee uniqueness of your data by dropping duplicates in the source's Spark Dataframe or by doing UPSERT against the target table.
> 2. You don't have to delete the table when doing UPSERT.
> 3. Be in mind, Spark engine will perform join based on condition you define. This means it requires to read from a table to find the matching row, so the target table must exist in the first place.

Please, Is there any example or document of dataframe api related to merge?

**Comment by dramaticlly** [comment]
I am not sure if merge into can be done using dataframe API, same with deletion

**Comment by sinban04** [comment]
It seems MERGE INTO is supported as Spark DataFrame v2 API since Spark 4.0.0
