### ISSUE TITLE
Support Rewrite Datafiles into a custom Partition Spec

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#7557]
### Feature Request / Improvement

Currently rewrite data-files always uses the current table partition spec when rewriting but it is useful to be able to use any partition spec in the table. In this way, a user could potentially write with one spec like `hours`, but then rewrite into `days`.

This would require expanding the API and then changing the implementation a bit. We should probably do this in two PR's, one adding the new API. Then additional follow up PR's actually adding implementations for the various existing rewrites like Spark's Rewrite DataFiles.

### Query engine

Spark

**Comment by W-I-D-EE** [comment]
Do you see this as less about Partition evolution and more about being able to rewrite data into a more optimal partition spec. Like in your example maybe your default partition is using days, but on one specific day your data was exceptionally chatty resulting in suboptimal query performance. So being able to rewrite the chatty days into hours could result in a more optimal partition setup.

If so, would it make sense for users to be able to add a partition spec to a table without altering/evolving the existing default. Maybe this already exists?

**Comment by RussellSpitzer** [comment]
Note that @dpaani Has a PR for this.
#7585

**Comment by himadripal** [comment]
#9803 revised PR
