### ISSUE TITLE
Document all metadata tables

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#757]
We should document our entries metadata table that shows all manifest entries.

**Comment by aokolnychyi** [comment]
In addition, we should document new metadata tables added in #805.

**Comment by whoAbhishekSah** [comment]
@aokolnychyi can you assign this issue to me?
I am new to this repository and would like to contribute.

**Comment by prodeezy** [comment]
I also noticed that https://iceberg.apache.org/spark/ only documents metadata tables exposed by catalog like `db.table.files` , `db.table.snapshots`, etc. and not using location based tables e.g. `hdfs://${basePath}#files` ,  `hdfs://${basePath}#snapshots` , etc. Would be good to add these as well.

**Comment by aokolnychyi** [comment]
I agree with @prodeezy that documenting those will be helpful.

@whoAbhishekSah, sorry for the late reply. Please feel free to pick this up and contribute!

**Comment by RussellSpitzer** [comment]
I was just reminded of this yesterday when I saw someone attempting to count all the rows in their partitions using a full table scan, we should really do these, I probably will if I have some time but this would be a GREAT ticket for anyone who wants to do a first time contribution :)

**Comment by BACtaki** [comment]
@RussellSpitzer I am working on this

**Comment by nssalian** [comment]
@aokolnychyi could I work on this as a first-issue? I'll post back for clarifications on the Issue?

**Comment by jackye1995** [comment]
@nssalian would definitely be great if you can pick this up! Let me know if you need any help

**Comment by nssalian** [comment]
Thanks @jackye1995. I'll post back if I have questions.

**Comment by BACtaki** [comment]
Hi @nssalian, I was working on this a while back but I got sidetracked. I have created a PR with my changes [here](https://github.com/apache/iceberg/pull/3159), please feel free to take it from there and merge it in when you are ready (and after reviews).

@RussellSpitzer @jackye1995

**Comment by nssalian** [comment]
@BACtaki  I think you already did most/all of the work. Please go ahead. I can always pick up another issue. :)

**Comment by BACtaki** [comment]
@nssalian Sounds good, thanks for understanding and apologies for the confusion!

**Comment by jackye1995** [comment]
@BACtaki @nssalian based on the discussion in the PR opened by @BACtaki , we should document metadata tables for each engine. Based on what currently is in Spark I think we still need the following work if you are interested in picking up:
1. add documentation in Spark for missing metadata tables
2. add Flink metadata table query doc

**Comment by nssalian** [comment]
Thanks @jackye1995. I can take up the Spark metadata tables issue. Do we have an open issue for it?

**Comment by bitsondatadev** [comment]
@jackye1995 or @aokolnychyi could one of you tag this with docs?

**Comment by bitsondatadev** [comment]
Note: `changes` metadata table [was requested in Slack](https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1687340786148789) and should be included.

> I noticed in the code that there is a changes metadata table in Spark, but the docuemntation for it is missing in https://iceberg.apache.org/docs/latest/spark-queries/
Could you please document the metadata table to increase its usage?
