### ISSUE TITLE
Iceberg / Spark writing to s3 warehouse : Unable to load region from any of the providers in the chain software

### ISSUE THREAD

**Issue by UFMurphy** [apache/iceberg#7570]
StackOverflow Gurus:

So I am going through some of the quickstarts on iceberg using Jupyter Notebooks. I have a postgres catalog set up and an s3 bucket for the warehouse.

I am able to create the table (I see folder in the s3 bucket), but not insert into it. I also do see the catalog entry in my postgres db. I will post code below.

I get the error below, which doesn't make sense, as I am setting environment variables in my JupyterNotebook for my aws credentials and region.

```
23/05/09 09:57:34 WARN TaskSetManager: Lost task 1.0 in stage 4.0 (TID 5) (192.168.86.41 executor 0): software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@5558d94d: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@483d5d05: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@4542969b: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@6070ed64: Unable to contact EC2 metadata service.
```

I know it's something simple I am missing. So any guidance you can offer is appreciated.

```python
#### CODE ####
from pyspark.sql import SparkSession
from pyspark.conf import SparkConf
from pyspark.sql.functions import udf, array
from pyspark.sql.types import StringType
from datetime import datetime as Date
from pyspark.sql.dataframe import DataFrame

%env AWS_REGION=us-east-1
%env AWS_ACCESS_KEY_ID=XXXXX
%env AWS_SECRET_ACCESS_KEY=XXXXXX


conf = (
    SparkConf()
    .setAppName('DealStampede')
    .setMaster("spark://ds2.lan:7077")
    .set("spark.executor.memory", "4g")
    .set("spark.ui.port",4042)
    #packages
    .set('spark.jars.packages', 'org.apache.iceberg:iceberg-spark3-runtime:0.13.2,software.amazon.awssdk:bundle:2.20.57,software.amazon.awssdk:url-connection-client:2.20.57,org.postgresql:postgresql:42.2.23')
    #SQL Extensions
    .set('spark.sql.extensions', 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions')
    #Configuring Catalog    
    .set('spark.sql.catalog.iceberg', 'org.apache.iceberg.spark.SparkCatalog')
    #.set('spark.sql.catalog.iceberg.type', 'hadoop')
    .set('spark.sql.catalog.iceberg.warehouse', 's3://ds.iceberg/warehouse')
    .set('spark.sql.catalog.iceberg.io-impl', 'org.apache.iceberg.aws.s3.S3FileIO')
    #Configuring metastore
    .set('spark.sql.catalog.iceberg.catalog-impl', 'org.apache.iceberg.jdbc.JdbcCatalog')
    .set('spark.sql.catalog.iceberg.uri', 'jdbc:postgresql://ds3.lan:5432/iceberg')
    .set('spark.sql.catalog.iceberg.jdbc.verifyServerCertificate', 'false')
    .set('spark.sql.catalog.iceberg.jdbc.useSSL', 'false')
    .set('spark.sql.catalog.iceberg.jdbc.user', 'xxxxxx')
    .set('spark.sql.catalog.iceberg.jdbc.password', 'xxxxx')
)    

spark = SparkSession.builder.config(conf=conf).getOrCreate()
print("Spark Running")

data = [
[10,'Direct Sales','Mario'],
[12,'Direct Sales','Joe'],
[20,'Online Sales','Sally'],
[25,'Online Sales','Dawn'],
]
 
df = spark.createDataFrame(data , ['revenue','department','boss'])
 
df.show()

print("### CREATING TABLE")

spark.sql("""CREATE TABLE IF NOT EXISTS iceberg.table1 (
revenue int,
department string,
boss string)
USING iceberg
location 's3://ds.iceberg/warehouse/table1'""")

print("### INSERTING INTO TABLE")
df.writeTo("iceberg.table1").append()

print("### SELECTING FROM TABLE")
df_result = spark.read.format("iceberg").load("iceberg.table1")
df_result.show()

```

**Comment by Fokko** [comment]
@UFMurphy I don't have a direct answer, and it isn't easy to replicate on my side. I did notice that the `0.13.2` is using `software.amazon.awssdk:bundle:2.15.7`. Can you give that a try?

**Comment by UFMurphy** [comment]
@Fokko Thanks for the thoughtful reply. That did not do the trick, unfortunately.  What I am learning (the hard way) is that iceberg is a versioning nightmare.  

This morning, I wiped the slate clean and started over...

So I am running the following...

Spark 3.3.1 (on spark master/worker and a separate jupyter notebook box)
iceberg-spark-runtime: org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.1.0
AWS libraries:
software.amazon.awssdk:bundle:2.19.19
software.amazon.awssdk:url-connection-client:2.19.19
Spark extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
Postgres iceberg catalog
Local Minio object store

I can read files off minio fine. I can also connect to the iceberg catalog ok from spark-sql cli.
It's just the pyspark in the notebook - even using same config params. It gets stuck on the region error.

**Comment by dramaticlly** [comment]
I think this looks like runtime failure where region cannot be loaded properly. 

Although I saw your set `%env AWS_REGION=us-east-1` but somehow it's not picked up by iceberg when trying to initialize S3 fileIO. I would try the following
- read env in spark after `AWS_REGION` is set to make sure it's actually set 
- try add region as jvm argument as a workaround
```
spark.driver.extraJavaOptions=-Daws.region=us-east-1
spark.executor.extraJavaOptions=-Daws.region=us-east-1
```

**Comment by UFMurphy** [comment]
@dramaticlly

Thank you for your suggestion. I wasn't able to properly set the environment variables using that specific approach. But it got me thinking about other ways. I got it working by setting the aws credentials as environment variables in the conf/spark-env.sh file. These Jupyter notebooks throw a wrench in to everything ;-). Thanks again!

**Comment by YannickLecroart21** [comment]
> @dramaticlly
> 
> Thank you for your suggestion. I wasn't able to properly set the environment variables using that specific approach. But it got me thinking about other ways. I got it working by setting the aws credentials as environment variables in the conf/spark-env.sh file. These Jupyter notebooks throw a wrench in to everything ;-). Thanks again!

How did you do that please?
