### ISSUE TITLE
Add retry framework to Hadoop table load

### ISSUE THREAD

**Issue by rominparekh** [apache/iceberg#758]
When we have concurrent writes being committed to a Hadoop table, there is a possibility we might not be able to load the table. One example, would be if we are committing too frequently, we might not be able to find `version-hint.txt` file, resulting in an NPE.

```scala
java.lang.NullPointerException
    at org.apache.iceberg.hadoop.HadoopTableOperations.readVersionHint(HadoopTableOperations.java:232)
    at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:75)
    at org.apache.iceberg.hadoop.HadoopTableOperations.current(HadoopTableOperations.java:68)
    at org.apache.iceberg.hadoop.HadoopTables.load(HadoopTables.java:68)
    at org.apache.iceberg.spark.source.IcebergSource.findTable(IcebergSource.java:134)
    at org.apache.iceberg.spark.source.IcebergSource.getTableAndResolveHadoopConfiguration(IcebergSource.java:160)
    at org.apache.iceberg.spark.source.IcebergSource.createReader(IcebergSource.java:75)
    at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
    at ...
```

**Comment by prodeezy** [comment]
For more context: The file system we use doesn't provide atomicity garuntees on file rename. So when version-hint.txt is being re-written by writers, readers or other concurrent writers could see an empty version-hint file and fail with above error. To get around this the writer and readers have to retry outside of iceberg. We feel, Iceberg should be resilient on this and refresh table state and retry commit.

**Comment by rominparekh** [comment]
We use ADLS file system that does not share atomic guarantees with when `overwrite = TRUE`. Here's the documentation - https://hadoop.apache.org/docs/current3/api/org/apache/hadoop/fs/adl/AdlFileSystem.html#rename-org.apache.hadoop.fs.Path-org.apache.hadoop.fs.Path-org.apache.hadoop.fs.Options.Rename...-

This is where atomic guarantees are not honored - https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java#L220

**Comment by rdblue** [comment]
A retry framework may help you avoid problems like this one, but it does not fundamentally change the fact that using Hadoop tables on a file system without atomic rename is not safe.

The recommended solution when using a file system without atomic rename is to use a metastore catalog, like we have available in the Hive integration.

**Comment by mehtaashish23** [comment]
Guys, correct me if I am wrong, I feel this doesn't look like problem with rename guarantee, its about guarantees while reading the `version-hint.text` file during read time operation (according to above stack trace) in a environment where there are many writers trying to update the table, in sequence or parallel. 

IIUC after doing the `rename` from `GUID.metadata.json` to `version.metadata.json`, we try to use `create with overwrite` [here] to update the version-hint.text with the current version number. The behavior of this API, is to update the content of this file in place, and during that time, if someone is reading this file might see different behavior, based on underlying filesystem guarantees i.e the file doesn't exist, or the data in the file is momentarily empty etc. 

I suppose, we would need retries in read path of versionHint. *Also* if above is true, then we need better documentation, around guarantees we expect w.r.t `create with overwrite` from underlying filesystem.

[here]: https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java#L220

**Comment by prodeezy** [comment]
@mehtaashish23  Right , the `create(path, overwrite=true)` not being atomic in ADLS is the real issue and a retry framework can help alleviate this (which we have added in to our writer/reader wrappers) but as Ryan said a retry framework won't fix things for us. We need a way to build an atomic commit.
