### ISSUE TITLE
planFiles with ParallelIterator OOM(Out of memory)

### ISSUE THREAD

**Issue by waltczhang** [apache/iceberg#7594]
### Question

Background：
When I was doing a full table scan (table DataFiles with millions or even more records), I found that using ParallelIterator often leads to OOM (out of memory) issues. The main reason is that the ParallelIterator queue model has a many-to-one relationship, meaning that there is at least one producer but only one consumer. Is there a need for some mechanism (such as the default queue length) to control the speed or capacity of the generated data in this case?
<img width="1219" alt="image" src="https://github.com/apache/iceberg/assets/35056804/b96f416b-f16c-4201-8ff1-0b2bc0a5dc45">

For example：
`CloseableIterable<FileScanTask> fileScanTasks = table.newScan().planFiles();
  fileScanTasks.forEach(...);`

**Comment by dramaticlly** [comment]
similar issue reported before in https://github.com/apache/iceberg/issues/4822
