### ISSUE TITLE
Suggestion for newbie getting started guide

### ISSUE THREAD

**Issue by ramkumarkb** [apache/iceberg#761]
Hello,

I am a newbie with Iceberg and was going thru the documentation and table format specs. I was wondering if there is a more simpler way to get started w/o Spark or Presto. Specifically, can one do the following:

1. Install local S3 Object Store with MinIO - https://min.io/ - rather straightforward
2. Java app to create tables - is it https://iceberg.apache.org/api-quickstart/#using-hadoop-tables - can this be used for S3 with `s3a://` instead of `hdfs://` - this is to configure the storage to the above mentioned S3 installation. Is this as simple as that? I am bit wary of the versions of the Hadoop libraries (and its compatibility with S3) to use.
3. Similarly create Schema, Partition Spec - https://iceberg.apache.org/api-quickstart/#create-a-schema
4. Client Java app to add some data, read data and modify one particular record - Not sure if this via `IcebergGenerics`?

I think can contribute this, with some guidance of course, if this if of any use.

**Comment by rdblue** [comment]
Hadoop tables cannot be used with a file system that doesn't support atomic rename. They should only be used with HDFS or a local FS, not with S3. For S3, you should be using a metastore, like Hive.

You're right that IcebergGenerics is the recommended way to read a table directly, without using an engine like Spark or Presto.

If you want to write up some documentation, that would be great! Please open a PR.

**Comment by ramkumarkb** [comment]
Ryan,

Thank you for your reply.

As per the MinIO docs - https://docs.minio.io/docs/distributed-minio-quickstart-guide.html 
> MinIO follows strict read-after-write and list-after-write consistency model for all i/o operations both in distributed and standalone modes.

With this, a Hive Metastore is still needed?

**Comment by rdblue** [comment]
@ramkumarkb, it isn't clear from that alone. Iceberg's Hadoop table implementation requires atomic rename for correctness.

**Comment by apatrida** [comment]
Looks like no atomic rename:

https://github.com/minio/minio-js/issues/787
https://docs.min.io/docs/disaggregated-spark-and-hadoop-hive-with-minio.html
