### ISSUE TITLE
Documentation doesn't tell you how to do a REST catalog 

### ISSUE THREAD

**Issue by alberttwong** [apache/iceberg#7614]
### Feature Request / Improvement

Per https://iceberg.apache.org/docs/latest/spark-configuration/#catalogs.  It says that you should find an examples of different catalogs.   I can't seem to find an example of using the REST catalog 

### Query engine

None

**Comment by prateek** [comment]
fwiw - i stumbled upon https://tabular.io/blog/docker-spark-and-iceberg/ when trying to answer a similar question.
