### ISSUE TITLE
Quickstart should give an example of a REST catalog enablement in the spark iceberg docker compose setup

### ISSUE THREAD

**Issue by alberttwong** [apache/iceberg#7615]
### Feature Request / Improvement

Per https://iceberg.apache.org/spark-quickstart/#adding-a-catalog.   I want to enable a REST catalog.   The docker compose image seems to the "bits" for the rest catalog but I can't seem to find instructions on how to enable it.

----

Hi, I'm doing the https://iceberg.apache.org/spark-quickstart/ and I want to connect to the iceberg catalog through the rest interface.  I followed the instructions to create the table and load it with 4 entries.   I was able to put a hostname to the iceberg-rest image but when I try to go to http://iceberg-rest:8181/ or  http://iceberg-rest:8181/ws, it says - {"error":{"message":"No route for request: GET ","type":"BadRequestException","code":400}}.   What am I missing?
I'm thinking the REST equivalent of https://iceberg.apache.org/spark-quickstart/#adding-a-catalog.  The example is hive but looking for the REST version.

### Query engine

None

**Comment by Fokko** [comment]
Hey @alberttwong Thanks for raising this, and I agree that the docs are incomplete. The config for setting up a REST catalog in Spark can be found in the `docker-spark-iceberg` repository as well: https://github.com/tabular-io/docker-spark-iceberg/blob/main/spark/spark-defaults.conf

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/discussions/23427
