### ISSUE TITLE
Harmonize RewriteData, DeleteFilesSparkAction

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#7625]
### Feature Request / Improvement

We did some a few code style fixups to RewriteDeleteFileSparkAction that can be applied as well to RewriteDataFileSparkAction https://github.com/apache/iceberg/pull/7565#pullrequestreview-1427730581

### Query engine

Spark

**Comment by szehon-ho** [comment]
If anyone has cycles to take a look, feel free, else I can do this later

**Comment by ajantha-bhat** [comment]
@szehon-ho: I can work on this.

**Comment by ajantha-bhat** [comment]
I fixed for rewrite data files via #7630. 
And in the issue summary, `DeleteFilesSparkAction` is mentioned. Which one did you mean `DeleteOrphanFilesSparkAction` or `DeleteReachableFilesSparkAction`.  I didn't find the same pattern for optimization in those actions.

**Comment by dramaticlly** [comment]
> I fixed for rewrite data files via #7630. And in the issue summary, `DeleteFilesSparkAction` is mentioned. Which one did you mean `DeleteOrphanFilesSparkAction` or `DeleteReachableFilesSparkAction`?. I didn't find the same pattern for optimization in those actions.

I think the issue asked to harmonize both `RewriteDataFilesSparkAction` and `Rewrite(Position)DeleteFilesSparkAction` based on feedback given in #7565. Delete Orphan and ReachableFiles shall not be relevant here

**Comment by szehon-ho** [comment]
Ugh im sorry guys, i made the issue name wrong, should be RewritePositionDeleteFilesSparkAction.  Looked at that word too much this year :)
