### ISSUE TITLE
When using flink dataframe api for upsert, the deduplication effect is not achieved

### ISSUE THREAD

**Issue by saimigo** [apache/iceberg#7639]
### Query engine

Flink 1.14.2    datastream java api
Iceberg 0.13.2

### Question

I create a table as follows:
        create table VTC_Tracking (
                vin STRING,
                datetime TIMESTAMP_LTZ(6),
                data STRING,
                PRIMARY KEY (vin, datetime) NOT ENFORCED)
                WITH ('format-version'='2',
                'catalog-name'='s3IcebergCatalog',
                'catalog-type'='hive',
                'write.upsert.enable'='true',
                'write.format.default'='orc',
                'warehouse'='s3a://warehouse/',
                'engine.hive.enabled'='true');

And write upsert through flink datastream api, but there is still duplicate data.

        FlinkSink.forRowData(dataStream)
                .table(table)
                .tableLoader(tableLoader)
                .writeParallelism(5)
                .equalityFieldColumns(ImmutableList.of("vin", "datetime"))
                .upsert(true)
                .append();

If I write data with Flink sql there is no duplicate data:
`insert into vtc_tracking values ('t03_2', to_timestamp('2022-06-28 17:17:04.289', 'test duplicate'));`

May I ask if the method I used is wrong or the datastream api does not support it?

**Comment by Crossoverrr** [comment]
I have the same problem, any help will be appreciated!
or if can tell the reason why can this duplicated data happen.
It looks like one UPDATE_AFTER create 2 records, one to send to Iceberg to ask it to delete the old rec, the other one to insert, but both of them were saved as new data.
