### ISSUE TITLE
iceberg table query bug

### ISSUE THREAD

**Issue by shiwl** [apache/iceberg#7640]
### Apache Iceberg version

0.13.0

### Query engine

Spark

### Please describe the bug 🐞

When some parquet files are missing, using Spark-SQL to query table data will result in an error. I cannot retrieve the missing parquet file. I want to ignore the small amount of missing data, but I cannot find a way. Can I only delete the entire table and rebuild it

**Comment by edgarRd** [comment]
This is not a  bug.

You can remove the missing files from the metadata via [DeleteFiles](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/Table.java#L275) API.
