### ISSUE TITLE
Remove the direct dependency on Apache Commons

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7658]
### Feature Request / Improvement

See https://github.com/apache/iceberg/pull/5024/files#r896336657

### Query engine

None

**Comment by hrishisd** [comment]
Hi Fokko,

Is the goal of this issue to remove all uses of apache.commons.io?
```java
$rg 'import org.apache.commons'

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
24:import org.apache.commons.lang3.StringUtils;

spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
31:import org.apache.commons.io.FileUtils;
32:import org.apache.commons.io.filefilter.TrueFileFilter;
...
```

**Comment by anki7t** [comment]
Hi @Fokko ,
 is this issue solution already merged? if not, i can work on it.

**Comment by anki7t** [comment]
@Fokko yes it is a dependency.

**Comment by Neuw84** [comment]
Hi, 

I had some spare time and wanted to start contributing. I have cleaned the dependency on those projects that make sense ( Spark & Flink declare it as direct dependency). 

Thanks!
