### ISSUE TITLE
Object name contains unsupported characters

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7678]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Some weird stuff, I tried to run:

```sql
DELETE FROM default.test_positional_mor_deletes WHERE number IN (1, 3, 5, 7, 9, 11)
```

And it failed:

```
23/05/22 12:15:17 WARN TaskSetManager: Lost task 0.0 in stage 25.0 (TID 32) (0436561124c6 executor driver): software.amazon.awssdk.services.s3.model.S3Exception: Object name contains unsupported characters. (Service: S3, Status Code: 400, Request ID: 17617637CB486230, Extended Request ID: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
```

Turns out the path has a double slash:

```
s3://warehouse/default/test_positional_mor_deletes/data//00000-32-70be11f7-3c4b-40e0-b35a-334e97ef6554-00001-deletes.parquet
```

When I run:

```sql
DELETE FROM default.test_positional_mor_deletes WHERE number = 1 
```

Everything is fine 😨 I see the error as well when using `number % 2 = 0` (what I tried initially).

**Comment by edgarRd** [comment]
I wonder if this is similar to what I saw in https://github.com/apache/iceberg/issues/7635 step 4.

**Comment by Fokko** [comment]
Hey @edgarRd that is correct. I ran your steps in the issue, and was able to replicate it. This will fix step 4.
