### ISSUE TITLE
Explore: option of creating single delete file to reduce number of delete files in a partition in MOR

### ISSUE THREAD

**Issue by rbalamohan** [apache/iceberg#7690]
### Feature Request / Improvement

MOR suffers from delete file bloat up and scan issues during reads. It will be good to explore an option, where single delete file is created irrespective of the number of files present in the partition (or the number of files updated in the partition). This will help reduce the number of files that needs to be accessed during reads specifically with MOR.

### Query engine

None

**Comment by ajantha-bhat** [comment]
Recently, a CALL procedure was added for rewriting the position deletes, which should help to solve this problem. 

https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewritePositionDeleteFilesProcedure.java

**Comment by rbalamohan** [comment]
Thanks @ajantha-bhat . It will be nice to provide an option to have this (optionally) at the time of writing itself. If the user choose to run it explicitly during commit, it could be run and it can help instead of running minor compaction periodically. Again this should be optional and it is a way of providing the flexibility to write compacted delete files during writes in certain cases.

**Comment by rbalamohan** [comment]
That is the reason it has to be made optional (depending on need basis of usecase and user pref)
