### ISSUE TITLE
Define location parameter when creating iceberg table with Spark API

### ISSUE THREAD

**Issue by gszecsenyi** [apache/iceberg#7708]
### Query engine

Spark 3

### Question

How can I define the location parameter when I use the Spark API to create an Iceberg table? 

```
val data: DataFrame = ...
data.writeTo("prod.db.table").create()
```

**Comment by ajantha-bhat** [comment]
Can you please refer to the last example in this section?

https://iceberg.apache.org/docs/latest/spark-writes/#creating-tables

**Comment by gszecsenyi** [comment]
Thanks
