### ISSUE TITLE
How to Set AWS region for S3FileIo

### ISSUE THREAD

**Issue by ismailsimsek** [apache/iceberg#7749]
### Feature Request / Improvement

is it possible to configure region for S3FileIo?  Im getting following error with Minio setup and couldn't find a way to set it explicitly using iceberg config.

seems like its possible for python but not for java. 
cc @jackye1995 @amogh-jahagirdar 

https://github.com/apache/iceberg/blob/1ea185290ac505e6c2e4d6f4eb429448860701e8/python/mkdocs/docs/configuration.md?plain=1#L69

```

Error:    IcebergChangeConsumerUpsertTest.testSimpleUpsert:52 » 

SdkClient Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@d8852f7: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@351bd548: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@473b1e5d: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@6cc1aeaf: Unable to retrieve region information from EC2 Metadata service. Please make sure the application is running on EC2.]
```

### Query engine

None

**Comment by nastra** [comment]
@ismailsimsek the correct one is `client.region`. See also https://github.com/apache/iceberg/blob/master/aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java#L67

**Comment by ismailsimsek** [comment]
got it, it works. thank you @nastra
