### ISSUE TITLE
 Failed to check if LessThan(status,2) can be pushed down: Cannot find field 'status' in struct: struct<>

### ISSUE THREAD

**Issue by wangyayuan18** [apache/iceberg#7774]
### Apache Iceberg version

None

### Query engine

Spark

### Please describe the bug 🐞

23/06/06 10:24:23 WARN SparkScanBuilder: Failed to check if LessThan(status,2) can be pushed down: Cannot find field 'status' in struct: struct<>
23/06/06 10:25:38 WARN SparkScanBuilder: Failed to check if In(reference_snapshot_id, [1230373703852306628,1849808359982020922,4330935422616301778,4470204942634271028,479194513693275545,4913067589943267683,5923369296085234103,5928155272764525083,6522090854024475726,6569070495140542522,6593087282459211619,7300047816255470666,7337438763244849602,7874321092049585761,7916454240168025164,8152119409258656830,8695853146397779334,9180876912423898377]) can be pushed down: Cannot find field 'reference_snapshot_id' in struct: struct<>
23/06/06 10:25:38 WARN SparkScanBuilder: Failed to check if In(reference_snapshot_id, [1230373703852306628,1849808359982020922,4330935422616301778,4470204942634271028,479194513693275545,4913067589943267683,5923369296085234103,5928155272764525083,6522090854024475726,6569070495140542522,6593087282459211619,7300047816255470666,7337438763244849602,7874321092049585761,7916454240168025164,8152119409258656830,8695853146397779334,9180876912423898377]) can be pushed down: Cannot find field 'reference_snapshot_id' in struct: struct<>

iceberg version  1.3.0
![image](https://github.com/apache/iceberg/assets/64136230/dbf415e9-b685-4886-a397-f787caea60e3)
code
![image](https://github.com/apache/iceberg/assets/64136230/a839c02c-ef0b-410f-9b60-6e009cbcbf44)
Task Progress
![image](https://github.com/apache/iceberg/assets/64136230/b6640e08-35f8-4f0f-80ab-1f43b2ceb302)

I don't know what the problem is when merging partitioned and non partitioned tables with small files

**Comment by JackGoldsworth** [comment]
I am seeing this as well after upgrading from EMR 6.10 (Spark 3.3.1, Iceberg 1.1.0) to EMR 6.11 (Spark 3.3.2, Iceberg 1.2.0) on the following Spark write to a partitioned Iceberg Table: `df.writeTo(s"${...}.${tableName}") .overwrite(col(s"${id}") === id)`. 

I am also seeing substantially increased our write times.

**Comment by ZachDischner** [comment]
I am seeing this behavior specifically when attempting to query the `.files` metadata table in Iceberg. 

When running against a table created with Iceberg 1.1.0, querying the `partitions` struct does not seem to work when I upgrade to spark 3.4.

```
spark-shell --packages "org.apache.spark:spark-sql_2.13:3.3.1,org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0,org.apache.iceberg:iceberg-aws:1.1.0,org.apache.iceberg:iceberg-core:1.1.0
<--conf for existing Iceberg 1.1.0 table>
```

Example query:
```
SELECT * FROM catalog.db.table.files where partition.myPartitionName = ...


23/07/13 13:26:48 WARN SparkScanBuilder: Failed to check if IsNotNull(partition.myPartitionName) can be pushed down: Cannot find field 'partition.myPartitionName' in struct: struct<>
23/07/13 13:26:48 WARN SparkScanBuilder: Failed to check if GreaterThanOrEqual(partition.myPartitionName,2023-07-03T00:00:00Z) can be pushed down: Cannot find field 'partition.myPartitionName' in struct: struct<>
```

https://iceberg.apache.org/docs/latest/spark-queries/#files - `partition` is a struct. It appears as though we cannot push down predicates in spark to query against this field. This impacts reading and writing.

**Comment by szehon-ho** [comment]
Yea this sounds like a regression.  (Though there may be several problems listed here).  A bit preoccupied at the moment, but will take a look , at least starting from files table, when I get a chance.

**Comment by szehon-ho** [comment]
I tried a few of these cases (ExpireSnapshot, files table).  I see the predicate pushdown happening.

I think what may be happening, is you are not using the right Iceberg version for Spark 3.4.  See :  https://github.com/apache/iceberg/tree/1.1.x/spark   Iceberg 1.1 does not have support for Spark 3.4, so maybe it does not understand the Spark 3.4 filters.

Please use latest Iceberg.  There's a vote ongoing, that should be done soon, for Iceberg 1.3.1.

**Comment by ZachDischner** [comment]
Can you clarify what you mean by "not using the right version of Iceberg"? Do you mean the existing Iceberg tables I'm working with (created with Iceberg V 1.1.0) must be upgraded? 

I'm seeing the same behavior when I use updated 1.3.0 libs with my Spark 3.4 session.

```
spark-shell --packages "org.apache.spark:spark-sql_2.13:3.3.1,org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0,org.apache.iceberg:iceberg-aws:1.3.0,org.apache.iceberg:iceberg-core:1.3.0,software.amazon.awssdk:bundle:2.20.25,software.amazon.awssdk:url-connection-client:2.20.25"\
   --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions\
  ...catalog conf pointing at 1.1.0-created Iceberg catalog

spark.sql("SELECT * FROM catalog.db.table.files WHERE partition.<something> = 'value'
23/07/18 16:06:40 WARN SparkScanBuilder: Failed to check if GreaterThanOrEqual(partition.something,'value) can be pushed down: Cannot find field 'partition.something' in struct: struct<>
```

**Comment by szehon-ho** [comment]
OK I looked into it some more.  I think its a problem with metadata tables,  but it works ok here.  

I verified that the pushdown does happen.

In this code:   https://github.com/apache/iceberg/blob/master/spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java#L167   

we add to pushedFilters, so filters _are_ used.

But the next part fails as it tries to figure out whether the filter selects the entire partition, so we do not need to return to Spark.  This just fails as the metadata table does not have any partition spec.

Here, we get an error message, and in fact it does get returned to Spark here, so it is correct, just alarming.
```
      } catch (Exception e) {
        LOG.warn("Failed to check if {} can be pushed down: {}", filter, e.getMessage());
        postScanFilters.add(filter);
      }
```

**Comment by ZachDischner** [comment]
Interesting. I ran an experiment - spun up two side-by-side EMR clusters as a controlled test. EMR 6.10 (Spark 3.3.1, Iceberg 1.1.0) and EMR 6.11 (Spark 3.3.2, Iceberg 1.2.0).

Verified that the same operations on the `files` metadata tables do read the _same_ exact amount of input data, indicating to me that predicates are working. The same query (`SELECT * FROM <preamble>.files`) takes 2x as long on EMR 6.11 as it does on 6.10. So the warning about predicates not being pushed seems like a red herring - they _are_ being pushed, but the operation still takes longer. 

I'm now guessing that the metadata is undergoing additional processing (maybe adding `readable_metrics`?) which is causing it to take longer to get a partition's file information.

**Comment by szehon-ho** [comment]
Thanks for the feedback!  Yea it sounds possible.  Is it possible to select everything but readable_metrics and test to verify that?

By the way, we are thinking how to fix this issue about the false warning.  cc @dramaticlly as well

**Comment by ZachDischner** [comment]
Confirmed it takes about the same amount of time if I select just a limited subset of columns

**Comment by szehon-ho** [comment]
You mean, same amount of time as the old version, right?

By the way, the optimization that caused the false warning is:  https://github.com/apache/iceberg/pull/6899

**Comment by ZachDischner** [comment]
Correct.  And thanks! I'm stoked to see that change
