### ISSUE TITLE
Python: Fix docstrings

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7776]
### Feature Request / Improvement

Since we're [releasing docstrings](https://github.com/apache/iceberg/pull/7108), thanks @LuigiCerone! 🙌🏻 We should make sure that we keep our docstrings tidy.

Currently, there are quite a few violations: 

- [ ] D100: Missing docstring in public module
- [ ] D101: Missing docstring in public class
- [ ] D102: Missing docstring in public method
- [ ] D103: Missing docstring in public function
- [ ] D104: Missing docstring in public package
- [x] D105: Missing docstring in magic method
- [ ] D106: Missing docstring in public nested class
- [ ] D107: Missing docstring in __init__
- [x] D200: One-line docstring should fit on one line with quotes
- [x] D202: No blank lines allowed after function docstring
- [ ] D205: 1 blank line required between summary line and description
- [x] D209: Multi-line docstring closing quotes should be on a separate line
- [x] D400: First line should end with a period
- [x] D401: First line should be in imperative mood
- [x] D403: First word of the first line should be properly capitalized
- [x] D414: Section has no content ('Returns')

To fix this, we need to remove the violation code from `.pre-commit-config.yaml`, run pre-commit `make lint`, fix the violations, and profit!

### Query engine

None

**Comment by mderoy** [comment]
I'd like to contribute on this

**Comment by mderoy** [comment]
@Fokko I've opened a PR for the D403 issues. Is there a guide to contribute for python (required python version, packages to install, etc) I assume for such a basic change there is CI that will run a set of unittests?

**Comment by Fokko** [comment]
Thanks @mderoy for picking this up! Yes, there is a CI that I just kicked off.

**Comment by mderoy** [comment]
opened a pr for D205. FYI you missed checking off D202 from the above list :)

**Comment by mderoy** [comment]
Fixes for D105 (and D209 which doesn't flag any issues) @Fokko https://github.com/apache/iceberg/pull/7852

**Comment by Fokko** [comment]
Thanks again @mderoy, looks like D209 was fixed along the way with all the great work 👍🏻

**Comment by atifiu** [comment]
@Fokko I want to work on the below task as a starter. Could you please help me from where to start and if there is any guidelines which I can refer for this task.

> D205: 1 blank line required between summary line and description

**Comment by Fokko** [comment]
For the migration, I'll close this one for now. We've moved to ruff and that also offers a lot of configuration.
