### ISSUE TITLE
PyIceberg: Passing configuration for glue client when creating catalog.

### ISSUE THREAD

**Issue by tilman151** [apache/iceberg#7777]
### Feature Request / Improvement

I am using pyIceberg to read tables organized in a glue catalog. My AWS credentials are stored in a `config` file and updated via SSO. I would like configure which AWS profile, e.g. sandbox or production, pyIceberg uses when it creates a glue catalog. Right now it will only pick up the default profile. I don't want to change the default profile each time.

A fix would be relatively simple, i.e. passing kwargs inside `properties` to the glue client constructor:

https://github.com/apache/iceberg/blob/66b0631b3f67dfbfe69bfd5974db034e9500a6fe/python/pyiceberg/catalog/glue.py#L132-L134

Passing a `boto3.Session` this way would allow me to select a profile.

### Query engine

Other

**Comment by Fokko** [comment]
Hey @tilman151 that would be a great addition. Would you be interested in creating a pull request? Both updating the code and the docs `python/mkdocs/docs/configuration.md`

**Comment by tilman151** [comment]
I'll have a look.
