### ISSUE TITLE
configure file size in iceberg table?

### ISSUE THREAD

**Issue by CaduRodrigues** [apache/iceberg#7797]
### Query engine

I'm using Spark with Gglue catalog and athena

### Question

Guys, I'm creating iceberg tables for migration, and I need the files generated in the iceberg to be around 256 MB, I couldn't find any configuration that would do this function, can anyone help me?

**Comment by zhongyujiang** [comment]
@CaduRodrigues you can set 'write.target-file-size-bytes' to control the size of files, and you can find more tuning table configurations [here](https://iceberg.apache.org/docs/latest/configuration/).
