### ISSUE TITLE
[bug] Encountered Chinese garbled code issue during Iceberg rest HTTP transmission

### ISSUE THREAD

**Issue by hxgdada** [apache/iceberg#7821]
### Apache Iceberg version

ALL

### Query engine

None

### Please describe the bug 🐞

org.apache.iceberg.rest.HTTPClient

origin：
    private StringEntity toJson(Object requestBody) {
        try {
            return new StringEntity(mapper.writeValueAsString(requestBody));
        } catch (JsonProcessingException e) {
            throw new RESTException(e, "Failed to write request body: %s", requestBody);
        }
    }

After modification：
  private StringEntity toJson(Object requestBody) {
        try {
            return new StringEntity(mapper.writeValueAsString(requestBody), Charset.forName("UTF-8"));
        } catch (JsonProcessingException e) {
            throw new RESTException(e, "Failed to write request body: %s", requestBody);
        }
    }

**Comment by nastra** [comment]
This probably makes sense. @hxgdada do you have a small reproducible example?

**Comment by nastra** [comment]
@hxgdada thanks for reporting this. I've opened #8046 that should fix it.
