### ISSUE TITLE
Implement Spark `fast_forward` procedure

### ISSUE THREAD

**Issue by jpugliesi** [apache/iceberg#7830]
### Feature Request / Improvement

[As discussed on slack](https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1682464799477819?thread_ts=1682025581.770009&cid=C025PH0G1D4), it would be useful to have a Spark procedure to fast-forward a table to a branch.

Example (copied from the slack thread):
```sql
-- update main branch to the state of xyz
call system.fast_forward(
    table => 'db.table',
    to => 'xyz');

-- update another branch to the state of xyz
call system.fast_forward(
    table => 'db.table',
    branch => 'another',
    to => 'xyz')
```

### Query engine

Spark

**Comment by rakesh-das08** [comment]
Is anyone currently working on this? If not i would like to take a stab at it.

**Comment by flyrain** [comment]
I'm not aware of anyone working on it. @amogh-jahagirdar and @jackye1995 may know more.

**Comment by rakesh-das08** [comment]
Looks like no is currently working on this and @rdblue also confirmed the same on Slack.
I will start working on this.

**Comment by rakesh-das08** [comment]
Adding a little more background:
Lets say we are working on a branch (wap) where we have ran some operations like `rewrite_data_files`.
Now we want to fast forward the `main` or `some_other_branch` to `wap_branch`.
Currently we do not have a procedure that does this.

**Comment by manuzhang** [comment]
Yes, it looks really weird in this [audit-branch](https://iceberg.apache.org/docs/latest/branching/#audit-branch) SQL example that we have to use table API to fast-forward.
