### ISSUE TITLE
Remove deprecated APIs for 1.4.0 release

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#7837]
### Feature Request / Improvement

There are a few deprecated APIs that should be removed before releasing 1.4.0

### Query engine

None

**Comment by nastra** [comment]
I've handled most deprecations in #7987. @akshayakp97 could you handle the deprecations in `AwsProperties` please?

**Comment by jbonofre** [comment]
Let me double check, I think I have a PR ready.

**Comment by aokolnychyi** [comment]
Let me know once there is PR, @jbonofre.

**Comment by jbonofre** [comment]
@aokolnychyi Hey Anton. I'm rebasing and doing new tests, I should be able to open the PR later today or tomorrow.

**Comment by aokolnychyi** [comment]
Perfect, please tag it here for visibility.

**Comment by jbonofre** [comment]
https://github.com/apache/iceberg/pull/8612

@Fokko @aokolnychyi if you guys can take a look.

I have one question: I had to update `GlueCatalog` to pass `S3FileIOProperties` in addition of `AwsProperties` (in order to have required S3 properties/configuration). Is it OK for you guys ?

**Comment by jbonofre** [comment]
#8612 has been merged. I think we can close this issue right ?
