### ISSUE TITLE
delete with clause IN

### ISSUE THREAD

**Issue by CaduRodrigues** [apache/iceberg#7850]
### Query engine

spark

### Question

Guys, I'm trying to do a delete via pyspark, and it's not working when I use the IN clause, has anyone experienced this problem?

For example:

delete from table where field = 1 works,

delete from table where field in(1) , does not give error but does not delete

**Comment by nastra** [comment]
We have a a few [tests](https://github.com/apache/iceberg/blob/master/spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java#L1186) in the codebase that verify this behavior. Could you describe your schema and how you determined that data isn't being deleted?
A reproducible short example would be helpful here, thanks.
