### ISSUE TITLE
Python: Add update schema

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7875]
### Feature Request / Improvement

It would be great to add update schema support for PyIceberg. This has been discussed a bit here https://github.com/apache/iceberg/pull/6323#discussion_r1217020366 and we can also copy the [Java tests](https://github.com/apache/iceberg/blob/master/core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java#L669-L737).

### Query engine

Other

**Comment by Fokko** [comment]
cc @jun-he

**Comment by hililiwei** [comment]
Hi @Fokko, I plan to do it gradually, first I raised #8174 to support adding columns, could you please help to review?

**Comment by Fokko** [comment]
This is in, thanks @hililiwei
