### ISSUE TITLE
[Flink] NullPointer when doing `FlinkEnvironmentContext.init` for Flink 1.17 and iceberg 1.3.0

### ISSUE THREAD

**Issue by pawel-big-lebowski** [apache/iceberg#7879]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

I am running Flink 1.17 and iceberg 1.3.0. I am trying to start simple example app with a code available here:
https://github.com/OpenLineage/OpenLineage/blob/main/integration/flink/examples/stateful/src/main/java/io/openlineage/flink/FlinkIcebergApplication.java#L19

Building a Flink source fails with NPE which originates in `FlinkEnvironmentContext` when doing 
```
public static void init() {
    EnvironmentContext.put("engine-name", "flink");
    EnvironmentContext.put("engine-version", FlinkPackage.version());
  }
```
The problem is that `FlinkPackage.version()` is null. The version is equal to:
```
private static final String VERSION = DataStream.class.getPackage().getImplementationVersion();
```
`DataStream.class` is on my classpath but `getImplementationVersion()` gives null. 

The error is observer when running integration test in docker container `flink:1.17.1-java11`. 

The same app used to work for previous flink & iceberg versions.

**Comment by nastra** [comment]
My first guess would be that there's maybe something wrong with the classpath. Any particular reason that you both have 
```
compileOnly "org.apache.iceberg:iceberg-flink:$icebergVersion"
implementation "org.apache.iceberg:iceberg-flink-runtime-$flinkVersionShort:$icebergVersion"
```
on the classpath?
Do you know why `getImplementationVersion()` returns a `null` in your case?

**Comment by Fokko** [comment]
cc @stevenzwu

**Comment by pawel-big-lebowski** [comment]
@nastra No particular reason behind having both. In one of my tests, I got rid of the top one and this did not change anything. 

I am able to see `DataStream.class.getPackage().getName()` which suggests the jar is available on a classpath. And this is something I find confusing most.

**Comment by pawel-big-lebowski** [comment]
Hi @nastra @stevenzwu , I think I found the reason. So, for some reason we were creating Uber-jar with shadow plugin which contained Flink libraries including `org.apache.flink:flink-streaming-java`. This was not necessary and we can get rid of it and this solves the problem on our side.

So the scenario is: 
 * Someone tries to create Uber-jar containing `org.apache.flink:flink-streaming-java`,
 * While using gradle's `shadowJar` plugin, manifests of dependencies get overwritten, 
 * The code 
```
DataStream.class.getPackage().getImplementationVersion();
```
returns `null` and `NullPointerException` is thrown when doing `EnvironmentContext.put("engine-version", FlinkPackage.version());` 

The bug is nasty to understand because one does have `DataStream.class` on the classpath but the manifest with `implementationVersion` is missing. And the only thing observed on the top is `NullPointerException`.

So, if you don't mind, I could prepare a PR which prevents putting `null` in `org.apache.iceberg.flink.FlinkEnvironmentContext#init` and throws more meaningful Exception. It would have been even better if you were able to find flink version some other way. Alternatively, we can close the issue if it so rare and uncommon to happen elsewhere.

**Comment by stevenzwu** [comment]
@pawel-big-lebowski it is good to improve this. feel free to submit a PR.

which uber jar you were referring to?

**Comment by stevenzwu** [comment]
@pawel-big-lebowski it is good to improve this. feel free to submit a PR.

which uber jar you were referring to?

**Comment by UlyanovskCN** [comment]
try set your flink-streaming dependency scope to provided,I solved same problem throught it

<groupId>org.apache.flink</groupId>
<artifactId>flink-streaming-java_${scala.binary.version}</artifactId>
<version>${flink.version}</version>
<scope>**provided**</scope>
