### ISSUE TITLE
missing option in remove_orphan_files (prefix mismatch)

### ISSUE THREAD

**Issue by cccs-jc** [apache/iceberg#7884]
### Feature Request / Improvement

My Iceberg table has datafiles that have paths with blob, while my metadata files have a dfs. In Azure there are two API to refer to files blob and dfs. You can use a path which uses `<container>@<storageaccount>.blob.core.windows.net` against the dfs API.

So the table works just fine I can read, write, delete, partition rewrite, etc. No issues.

However, the `remove_orphan_files` has an additional checks where it verify the prefix which fail.

![image](https://github.com/apache/iceberg/assets/56140112/bfe84152-7996-4356-946b-84e9fa75c088)

I would like to ignore this check because I know it's okay to delete these files. The option is missing from the store procedure.

https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java#L49

I see the functionality to ignore prefix is available but not via the procedure.
Could this be added please.

### Query engine

Spark

**Comment by nastra** [comment]
I believe this already exists and was added by #5385 (there's a `prefix_mismatch_mode` which takes `error` / `ignore` / `delete` options`).
