### ISSUE TITLE
Rate limiting feature for structured streaming

### ISSUE THREAD

**Issue by namrathamyske** [apache/iceberg#7885]
### Apache Iceberg version

main (development)

### Query engine

Spark

### Please describe the bug 🐞

In rate limiting for structured streaming PR -  https://github.com/apache/iceberg/pull/4479.  
According to line https://github.com/apache/iceberg/pull/4479/files#diff-26782bf5c27f69e5cc9cd4a9363f601a97d1c9f97fe0c1a7fb927da7c60c014fR169 unit test, it says the stream get stuck if number of records exceed SparkReadOptions.STREAMING_MAX_ROWS_PER_MICRO_BATCH. It's is a major blocker to consume this feature. If the stream is stuck, then no further advancement of stream takes place even if new snapshots comes in.

E.g.:
STREAMING_MAX_ROWS_PER_MICRO_BATCH - 2
Snapshot1 - (2 records, 1 data file) - Read fully in Microbatch-1
Snapshot2 - (3 records, 1 data file) - Can never be read as 3 records > STREAMING_MAX_ROWS_PER_MICRO_BATCH ( Stuck forever )
Snapshot3 - 3 records
Please let me know if this is intended behavior or is it expected to change. 

@singhpk234 @jackye1995 @RussellSpitzer @rdblue

**Comment by RussellSpitzer** [comment]
Yes I believe the smallest unit that is allowed to be streamed is a single data file. So the rate limit must be larger than the largest possible data file

**Comment by namrathamyske** [comment]
Thanks for responding. @RussellSpitzer @singhpk234

**Comment by singhpk234** [comment]
yes, that true @wypoon, presently its the limitation as for the initial implementation, 

I didn't wanted to block it on opening a file and reading it partially. As there were 2 options for me 
1/ either open the file again read till row X and include more row till the rows in file is exhausted 
2/ read the file totally once and keep the value in memory and hold it till asked 

I started getting back on OSS recently, I will try address this limitation as well as add this pr Trigger.AvaliableNow() very soon !
