### ISSUE TITLE
Migrate Files using TestRule in dell package to Junit5

### ISSUE THREAD

**Issue by DaVincii** [apache/iceberg#7888]
### Feature Request / Improvement

This is in relation to #7160

Some of the files which uses `@Rule`, `@ClassRule` or `extend TestRule` in dell package needs to be migrated to Junit5. These are:
1. EcsS3MockRule 
2. TestEcsSeekableInputStream

**Comment by ashutosh-roy** [comment]
Hi @DaVincii, Please provide your feedbacks on the PR for this issue.

**Comment by DaVincii** [comment]
> Hi @DaVincii, Please provide your feedbacks on the PR for this issue.

Hi @ashutosh-roy, updates looks fine to me but Eduard Tudenhoefner(https://github.com/nastra) would be the best person to accept them.

**Comment by ashutosh-roy** [comment]
Hi @nastra, Please provide your feedbacks on the PR for this issue.
