### ISSUE TITLE
Read is not working on Iceberg Hive table

### ISSUE THREAD

**Issue by Aggarwal-Raghav** [apache/iceberg#7924]
### Query engine

Hive

### Question

I am new to iceberg and trying to read the data from hive table but the output of select query is empty:

**Iceberg Version:1.3.0
Hive version: 3.1.2
Hadoop Version: 3.2.2
Tez Version: 0.10.1
Execution Engine=tez**

```
ADD JAR /home/hive/iceberg-hive-runtime-1.3.0.jar;
SET iceberg.engine.hive.enabled=true; 
SET engine.hive.enabled=true; 
SET hive.vectorized.execution.enabled=false;
SET iceberg.mr.catalog=hive;
CREATE EXTERNAL TABLE test_tbl (id int) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'; 
INSERT INTO test_tbl values (1); 
select * from test_tbl;
```
Insert is working fine and in hdfs also the .parquet file is getting generated and when I decode that parquet file using parquet-tools, I can see the data which I wrote using insert query. But when I perform select operation, it show no data. Here is the output:
```
+-----+
| id  |
+-----+
+-----+
```
What am I missing?

Here is desc formatted test_tbl
```
+-------------------------------+----------------------------------------------------+----------------------------------------------------+
|           col_name            |                     data_type                      |                      comment                       |
+-------------------------------+----------------------------------------------------+----------------------------------------------------+
| # col_name                    | data_type                                          | comment                                            |
| id                            | int                                                | from deserializer                                  |
|                               | NULL                                               | NULL                                               |
| # Detailed Table Information  | NULL                                               | NULL                                               |
| Database:                     | iceberg_testing                                    | NULL                                               |
| OwnerType:                    | USER                                               | NULL                                               |
| Owner:                        | hive                                               | NULL                                               |
| CreateTime:                   | Tue Jun 27 16:59:06 GMT 2023                       | NULL                                               |
| LastAccessTime:               | UNKNOWN                                            | NULL                                               |
| Retention:                    | 0                                                  | NULL                                               |
| Location:                     | `HDFS_LOCATION`                                    | NULL                                               |
| Table Type:                   | EXTERNAL_TABLE                                     | NULL                                               |
| Table Parameters:             | NULL                                               | NULL                                               |
|                               | EXTERNAL                                           | TRUE                                               |
|                               | bucketing_version                                  | 2                                                  |
|                               | current-schema                                     | {\"type\":\"struct\",\"schema-id\":0,\"fields\":[{\"id\":1,\"name\":\"id\",\"required\":false,\"type\":\"int\"}]} |
|                               | discover.partitions                                | true                                               |
|                               | engine.hive.enabled                                | true                                               |
|                               | external.table.purge                               | TRUE                                               |
|                               | last_modified_by                                   | hive                                               |
|                               | last_modified_time                                 | 1687885147                                         |
|                               | metadata_location                                  | `HDFS_LOCATION`/iceberg_testing.db/test_tbl/metadata/00000-9a4c82e8-d35f-4701-b22c-7b342146fa70.metadata.json |
|                               | numFiles                                           | 0                                                  |
|                               | numRows                                            | 0                                                  |
|                               | rawDataSize                                        | 0                                                  |
|                               | snapshot-count                                     | 0                                                  |
|                               | storage_handler                                    | org.apache.iceberg.mr.hive.HiveIcebergStorageHandler |
|                               | table_type                                         | ICEBERG                                            |
|                               | totalSize                                          | 0                                                  |
|                               | transient_lastDdlTime                              | 1687885147                                         |
|                               | uuid                                               | cc635575-5338-43a2-a7cd-224ae58ec808               |
|                               | NULL                                               | NULL                                               |
| # Storage Information         | NULL                                               | NULL                                               |
| SerDe Library:                | org.apache.iceberg.mr.hive.HiveIcebergSerDe        | NULL                                               |
| InputFormat:                  | org.apache.iceberg.mr.hive.HiveIcebergInputFormat  | NULL                                               |
| OutputFormat:                 | org.apache.iceberg.mr.hive.HiveIcebergOutputFormat | NULL                                               |
| Compressed:                   | No                                                 | NULL                                               |
| Num Buckets:                  | 0                                                  | NULL                                               |
| Bucket Columns:               | []                                                 | NULL                                               |
| Sort Columns:                 | []                                                 | NULL                                               |
+-------------------------------+----------------------------------------------------+----------------------------------------------------+
```

Thanks

**Comment by nastra** [comment]
@Aggarwal-Raghav could you describe your catalog settings please? Also did you have a chance to look through https://iceberg.apache.org/docs/latest/hive/ to double-check that everything is properly set up? It might be worth checking which from https://iceberg.apache.org/docs/latest/hive/#create-external-table-overlaying-an-existing-iceberg-table applies for your use case

**Comment by Aggarwal-Raghav** [comment]
First of all thanks for the reply. 
I tried with `SET iceberg.mr.catalog=hive;` and with below catalog config also:

```
SET iceberg.catalog.another_hive.type=hive; 
SET iceberg.catalog.another_hive.uri=thrift://<nodename>:9083; 
SET iceberg.catalog.another_hive.clients=10; 
SET iceberg.catalog.another_hive.warehouse=hdfs://<nodename>:8020/warehouse;
```
**With both the config select is not working.** The rest of the config are taken from  here only: https://iceberg.apache.org/docs/latest/hive/ 
Let me know if anything else is required.

**Comment by pvary** [comment]
I think the issue is with the Iceberg commit is not done, or it was not successfully.
I see that there is no `previous_metadata_location` in the list of the HMS table properties, and the filename for the `metadata_location` starts with `00000`.

You can confirm the theory by reading the Iceberg table with another tool.

Also you can see in the documentation:

> DML operations work only with MapReduce execution engine.

Could you try the write with `set hive.execution.engine=mr`?

If you want to use tez as an execution engine, you should switch to Hive 4.0.0-alpha-2 which has native Iceberg support.

**Comment by Aggarwal-Raghav** [comment]
In mr logs, I checked that indeed its job commit issue
`Job commit failed: org.apache.iceberg.hive.RuntimeMetaException: Failed to connect to Hive Metastore at org.apache.iceberg.hive.HiveClientPool.newClient(HiveClientPool.java:84) at org.apache.iceberg.hive.HiveClientPool.newClient(HiveClientPool.java:34) at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:125) at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:56) at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51) at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:122) at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:158) at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97) at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:80) at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47) at org.apache.iceberg.mr.Catalogs.loadTable(Catalogs.java:124) at org.apache.iceberg.mr.Catalogs.loadTable(Catalogs.java:111) at org.apache.iceberg.mr.hive.HiveIcebergOutputCommitter.commitTable(HiveIcebergOutputCommitter.java:320) at org.apache.iceberg.mr.hive.HiveIcebergOutputCommitter.lambda$commitJob$2(HiveIcebergOutputCommitter.java:214) at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413) at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219) at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203) at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196) at org.apache.iceberg.mr.hive.HiveIcebergOutputCommitter.commitJob(HiveIcebergOutputCommitter.java:207) at org.apache.hadoop.mapred.OutputCommitter.commitJob(OutputCommitter.java:291) at org.apache.hadoop.mapreduce.v2.app.commit.CommitterEventHandler$EventProcessor.handleJobCommit(CommitterEventHandler.java:286) at org.apache.hadoop.mapreduce.v2.app.commit.CommitterEventHandler$EventProcessor.run(CommitterEventHandler.java:238) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) Caused by: java.lang.NoClassDefFoundError: com/facebook/fb303/FacebookService$Iface at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:756) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) at java.net.URLClassLoader.access$100(URLClassLoader.java:74) at java.net.URLClassLoader$1.run(URLClassLoader.java:369) at java.net.URLClassLoader$1.run(URLClassLoader.java:363) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:362) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at org.apache.hadoop.hive.metastore.utils.JavaUtils.getClass(JavaUtils.java:52) at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:146) at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:119) at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:112) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.iceberg.common.DynMethods$UnboundMethod.invokeChecked(DynMethods.java:60) at org.apache.iceberg.common.DynMethods$UnboundMethod.invoke(DynMethods.java:72) at org.apache.iceberg.common.DynMethods$StaticMethod.invoke(DynMethods.java:185) at org.apache.iceberg.hive.HiveClientPool.newClient(HiveClientPool.java:63) ... 24 more Caused by: java.lang.ClassNotFoundException: com.facebook.fb303.FacebookService$Iface at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 50 more`

**Comment by pvary** [comment]
Could you try to add the missing jar to the class path with the `ADD JAR` command. It is some metastore jar IIRC

**Comment by Aggarwal-Raghav** [comment]
@pvary 
- Yes, I tried `add jar /path/to/libfb303-0.9.3.jar` and the **insert is working without kerberos** (_execution engine is MR_). With kerberos it is still failing with job commit issue.
- In non-kerberos case, I can see the updated `metadata_location` in `describe formatted <tableName>`. It has updated to `00001-.....` as you previously mentioned in your first comment.

**Comment by Aggarwal-Raghav** [comment]
Is Hive read working in this case? 
Ans:
- In non-kerberos case, insert and select both are working with hive execution engine as mr. 
- With kerberos, insert is failing with execution engine as mr

Commands ran in working case:
```
add jar /path/to/libfb303-0.9.3.jar;
add jar /path/to/iceberg-hive-runtime-1.3.0.jar;
SET iceberg.engine.hive.enabled=true;
set hive.execution.engine=mr;
SET hive.vectorized.execution.enabled=false;
CREATE EXTERNAL TABLE test_tbl (id int) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';
INSERT INTO test_tbl values (1);
select * from test_tbl;

+-----+
| id  |
+-----+
| 1   |
+-----+
```

In case of kerberos with execution engine as mr here is the partial stack trace:

`Job commit failed: org.apache.iceberg.hive.RuntimeMetaException: Failed to connect to Hive Metastore at 
....
org.apache.hadoop.hive.metastore.utils.JavaUtils.newInstance(JavaUtils.java:84) ... 36 more Caused by: MetaException(message:Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: GSS initiate failed at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:199) at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:281) at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:39) at org.apache.hadoop.hive.metastore.security.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:51) at org.apache.hadoop.hive.metastore.security.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:48)
....
`
**_I am trying to debug it. Will post the updated here. Let me know if you want the full stack trace._**

**Comment by s-akhtar-baig** [comment]
@Aggarwal-Raghav a similar stack is thrown when Kerberos authentication fails. Can you double check Kerberos settings on your client side such as keytab, valid ticket, etc.? 

  If read is working but insert is not when Kerberos is enabled then, try checking permissions for the kerberos principal that you are using.

**Comment by pvary** [comment]
Also, you might want to focus on the Kerberos authentication against the HMS, as for reads, Iceberg doesn't need it (so the read is successful), but for write, the commit operating needs it.
IIRC the MR commit happens in the MapReduce committer, which runs not in the mapper/reducer context, but in the ResourceManager(?) - take this last sentence with a grain of salt, as it was long time ago when I was playing around with Hive/MR, and I am only sure, that the commit happens in a strange place.

**Comment by AwasthiSomesh** [comment]
@Aggarwal-Raghav  How did u resolve this issue ?

**Comment by eugeny-stoyka** [comment]
@Aggarwal-Raghav 
hello, can you show your hive/tez configuration please, i'm using 

Iceberg Version:1.5.1
Hive version: 3.13
Hadoop Version: 3.3.6
Tez Version: 0.10.2
Execution Engine=tez

and your example doesn't work for insert purpuse
