### ISSUE TITLE
can not migrate/ snapshot Hive table whose partition value contains "/"

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#7925]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

```
java.lang.IllegalArgumentException: Invalid partition data, too many fields (expecting 4): col=2023-03-12/col2=ad_manager/col3=7/7/1/col4=val1/val2/null/null
```

Current implementation always assume no "/" within the partition value, so it always use "/" to split the partition path into fields. 

My recommendation would be adding a option to allow user to specify a splitter.

**Comment by JonasJ-ap** [comment]
I think it is the same issue as #7612 and PR #7744 may address it.
