### ISSUE TITLE
The expire_snapshots link is broken

### ISSUE THREAD

**Issue by Aitozi** [apache/iceberg#7930]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

https://iceberg.apache.org/docs/latest/branching/

<img width="795" alt="image" src="https://github.com/apache/iceberg/assets/9486140/aac95833-392e-4381-bc7b-edc51c96cd08">

**Comment by nastra** [comment]
@Aitozi thanks for reporting this. Woud you be interested in opening a PR to fix the link?

**Comment by Aitozi** [comment]
I'm not familiar with the iceberg's doc structure. You can go ahead to fix this, thanks.
