### ISSUE TITLE
Python: tables loaded by Glue catalog should have catalog's name as part of their identifier

### ISSUE THREAD

**Issue by cccs-eric** [apache/iceberg#7935]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

When loading a table stored in the Glue catalog using pyiceberg, the table identifier does not have the catalog's name in its identifier.  See this line of code: https://github.com/apache/iceberg/blob/master/python/pyiceberg/catalog/glue.py#L169

If you look at DynamoDB's implementation, it adds the catalog name: https://github.com/apache/iceberg/blob/master/python/pyiceberg/catalog/dynamodb.py#L590

**Comment by JonasJ-ap** [comment]
@cccs-eric Thank you very much for reporting this. I opened a PR to address this issue
