### ISSUE TITLE
How to remove orphan manifest and manifest list file

### ISSUE THREAD

**Issue by wandongchen** [apache/iceberg#7937]
### Apache Iceberg version

1.1.0

### Query engine

Spark

### Please describe the bug 🐞

The snapshot expiration process is to remove the snapshots first, and then clean up the files selected by those  expired snapshots. If the task execution failed during the cleanup processing, such as OOM or task timeout, only part of expired files will be deleted, but many manifest or manifest list or data file files may left, these residual files may never be cleaned up.

How to remove thoes files if  these residual files is manifest or manifest list file？

**Comment by JMin824** [comment]
the residual files you can try DeleteOrphanFiles
