### ISSUE TITLE
Add View Support to Trino

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#7939]
### Feature Request / Improvement

Once https://github.com/apache/iceberg/pull/7880 is in, work could be started on supporting Views in Trino

### Query engine

Trino

**Comment by bitsondatadev** [comment]
CC: @findepi @martint

**Comment by fxu175** [comment]
I'm interested in the view support at Iceberg, do we have the ETA for #7880 to be released?

**Comment by nastra** [comment]
It should land on master within the next week I would assume

**Comment by wmoustafa** [comment]
How does this change the views implementation in Iceberg? Particularly for Trino, the Iceberg connector/plugin code is part of the Trino codebase.

**Comment by findepi** [comment]
I would recommend moving this issue to Trino project.

**Comment by maxpoulain** [comment]
Hi ! Is there any news on this subject ? Is this issue was moved to Trino project ?

**Comment by amogh-jahagirdar** [comment]
Hey @maxpoulain yes, the tracking issue is in Trino https://github.com/trinodb/trino/issues/14120#issuecomment-1803568597

I also have a PR open there for View Support in Trino for the REST Catalog if you're interested: https://github.com/trinodb/trino/pull/19818

**Comment by maxpoulain** [comment]
Thanks @amogh-jahagirdar ! What about Iceberg views in Trino with Hive metastore catalog ? 
It seems that views created in Trino inside an iceberg catalog using HMS can be queried using Trino but it seems that it's not "a real iceberg view" so then when we tried to read this view using Spark it's not working..
