### ISSUE TITLE
Migrate/ snapshot action should exclude file that does not contain any record

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#7949]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

The current behavior is migrate/ snapshot action will add the file even without any record into the Iceberg table. This part is fine but it create issues later on. For example, if an Iceberg table contains a partition that only have files without any record, `delete from table where partition = emptey_partition` will not be able to drop that partition.

Ideally we should skip adding those files to the table.

**Comment by zinking** [comment]
guess the question is still the same, if the file is empty with records, why is it included in the commit in the first place? isn't that supposed to be fixed?

**Comment by puchengy** [comment]
@zinking I see what you mean, it is hard to fix the source since these files are produced by various engines.

**Comment by zinking** [comment]
not really at the various engine side, but actually at the moment when it is included into iceberg. or to be precise during the `commit` process of iceberg, we can simply check and discard those empty files.

**Comment by puchengy** [comment]
@zinking https://github.com/apache/iceberg/pull/8040 is already doing this
