### ISSUE TITLE
Consider removing the use of Guava

### ISSUE THREAD

**Issue by adamkennedy** [apache/iceberg#797]
The use of Guava in Iceberg does not appear to be excessive or highly critical at this time. The use of Guava in projects in the Hadoop/Spark ecosystem almost always seems to cause trouble eventually, due to it's "god package" all-in-one nature and dependency maintenance troubles.

Beyond relocating, we should consider removing it entirely

**Comment by rdsr** [comment]
Hi Adam,  Is relocation not a good solution here? Iceberg does provide different shaded runtime jars for Spark, Pig etc, where Iceberg's internal Guava will never conflict with the one provided by the engine/platform.

Guava does provide some nice apis which Iceberg makes use of - Iterables, preconditions, immutable collections etc.

**Comment by adamkennedy** [comment]
Since effectively every project needs to relocate Java to use it safely, that means every package using Guava adds 2.8MB of dependency bloat into jars and assemblies. And Guava itself has another 6 dependencies now in the latest versions.

Many of the things in Guava have similar equivalents in the Apache Commons ecosystem, which are much more incremental dependencies and have much stronger backwards compatibility.

**Comment by rdblue** [comment]
I'd love to remove guava. The main blocker is replacing Guava's collections. We use ImmutableMap and ImmutableList quite a bit, and I don't know of a good alternative.

**Comment by adamkennedy** [comment]
The new version of commons collections is using generic now?

https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/UnmodifiableMap.html

**Comment by adamkennedy** [comment]
Alternatively, generating your own ImmutableMap by doing a repeated inheritance inlining of the commons collections classes would be fairly straight forwards as well, if the licenses are compatible.
