### ISSUE TITLE
Pyiceberg StaticTable can't read metatdata with a gzip compression

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg#7977]
### Apache Iceberg version

None

### Query engine

Other

### Please describe the bug 🐞

Thanks for the static table functionality, but unfortunately tabular create a compressed json file, which pyiceberg can't read, I test it with Athena and it works fine

**Comment by Fokko** [comment]
Thanks @djouallah for raising this. I assume it is gzip compressed? Let me add this for you right away!

**Comment by Fokko** [comment]
Thanks for raising this @djouallah. If you want, you can give it a try by installing the lastest development version directly from Github: https://py.iceberg.apache.org/

**Comment by djouallah** [comment]
@Fokko Thanks, it does work now :)
