### ISSUE TITLE
can not execute procedure "rewrite_data_files" with option "max-concurrent-file-group-rewrites"

### ISSUE THREAD

**Issue by Zelin1203** [apache/iceberg#7981]
### Query engine

iceberg 1.1.0
spark 3.1.2

### Question

CALL realtime_catalog.system.rewrite_data_files(table => 'trancare_realtime_dws.dws_stability_app_crash_hourly',  strategy => 'sort', sort_order => 'pkg ASC NULLS LAST,country ASC NULLS LAST,device ASC NULLS LAST', options => map('max_concurrent_file_group_rewrites', '10'))

CALL realtime_catalog.system.rewrite_data_files(table => 'trancare_realtime_dws.dws_stability_app_crash_hourly',  strategy => 'sort', sort_order => 'pkg ASC NULLS LAST,country ASC NULLS LAST,device ASC NULLS LAST', options => map('max_concurrent_file_group_rewrites', '10'))
java.lang.IllegalArgumentException: Cannot use options [max_concurrent_file_group_rewrites], they are not supported by the action or the strategy SORT
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:435)
	at org.apache.iceberg.spark.actions.BaseRewriteDataFilesSparkAction.validateAndInitOptions(BaseRewriteDataFilesSparkAction.java:419)
	at org.apache.iceberg.spark.actions.BaseRewriteDataFilesSparkAction.execute(BaseRewriteDataFilesSparkAction.java:163)
	at org.apache.iceberg.spark.actions.BaseRewriteDataFilesSpark3Action.execute(BaseRewriteDataFilesSpark3Action.java:27)
	at org.apache.iceberg.spark.actions.BaseRewriteDataFilesSparkAction.execute(BaseRewriteDataFilesSparkAction.java:74)
	at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.lambda$call$0(RewriteDataFilesProcedure.java:118)
	at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:86)
	at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:74)
	at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.call(RewriteDataFilesProcedure.java:96)

**Comment by nastra** [comment]
@RussellSpitzer any idea why https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java#L80 isn't part of any rewriter's valid options?

**Comment by dramaticlly** [comment]
Looks like it's a valid option here for spark 3.1 but stacktrace above seems to differ https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java#L82

**Comment by RussellSpitzer** [comment]
Yeah they get set as valid options in the base validate and init methodSent from my iPhoneOn Jul 11, 2023, at 6:52 PM, dramaticlly ***@***.***> wrote:﻿
Looks like it's a valid option here for spark 3.1 but stacktrace above seems to differ https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java#L82

**Comment by wood-dunamu** [comment]
@RussellSpitzer  any updates?

**Comment by RussellSpitzer** [comment]
Update on what?

**Comment by RussellSpitzer** [comment]
So I checked and this is user error. Although the title of this issue uses the correct name of the parameter, the actual command in the example uses underscores instead of dashes.

`max_concurrent_file_group_rewrites` should be `max-concurrent-file-group-rewrites`

https://github.com/apache/iceberg/blob/42cf1579ab97ff0080630c752e877593882a4fac/api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java#L75-L80

```scala
scala> spark.sql("CALL local.system.rewrite_data_files(table => 'db.table', strategy => 'sort', sort_order=>'data asc', options => map(
'max_concurrent_file_group_rewrites', '10'))")
java.lang.IllegalArgumentException: Cannot use options [max_concurrent_file_group_rewrites], they are not supported by the action or the rewriter SORT
  ...
  
  
scala> spark.sql("CALL local.system.rewrite_data_files(table => 'db.table', strategy => 'sort', sort_order=>'data asc', options => map('max-concurrent-file-group-rewrites', '10'))")
val res10: org.apache.spark.sql.DataFrame = [rewritten_data_files_count: int, added_data_files_count: int ... 2 more fields]
```
