### ISSUE TITLE
Python: Delegate json deserialization to Pydantic

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7982]
### Feature Request / Improvement

Currently, we decode a bytestream using `json.load` in `serializers.py`. It would be better to have this directly done by Pydantic, to avoid constructing a Python dictionary. 

### Query engine

None

**Comment by aless10** [comment]
Hi @Fokko, I would like to contribute. Do you think this issue can be a good starting point to understand how it works? Thanks
