### ISSUE TITLE
use tez can't write data

### ISSUE THREAD

**Issue by BoomLee1024** [apache/iceberg#7990]
### Query engine

tez

### Question

I am using Iceberg 1.3.0, Tez 0.10.2, and Hive 3.1.3. When I create an Iceberg table using the MR engine, I can insert data and view it. I can also use Tez to select and view the data. However, when I create an Iceberg table using Tez, the insert operation doesn’t throw any errors, and I can see the data in HDFS. But when I try to select the data, it doesn’t return any results. When I execute “show create table,” I noticed that the information such as ‘current-snapshot-id’=‘8543337784714735606’, ‘current-snapshot-summary’=‘{“added-data-files”:“1”,“added-records”:“1”,“added-files-size”:“404”,“changed-partition-count”:“1”,“total-records”:“3”,“total-files-size”:“1212”,“total-data-files”:“3”,“total-delete-files”:“0”,“total-position-deletes”:“0”,“total-equality-deletes”:“0”}’, and ‘current-snapshot-timestamp-ms’=‘1687932559706’ is missing. Can you please advise on how to resolve this issue?

**Comment by pvary** [comment]
@BoomLee1024: This is documented here: https://iceberg.apache.org/docs/latest/hive/
```
DML operations work only with MapReduce execution engine.
```

The reason behind this that Tez changes are needed to archive the required results.
If you want to use Hive on Tez with Iceberg, you might want to try out [Hive 4.0.0-alpha-2](https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12351489&styleName=Html&projectId=12310843). It has Iceberg automatically included, and also plenty of new features around Iceberg integration.
