### ISSUE TITLE
Iceberg Vacuum doesn't remove old metadata file

### ISSUE THREAD

**Issue by wduan101** [apache/iceberg#8000]
I have a iceberg table and the metadata layer is as below screenshot where there are multiple versions of snapshots and associated metadata files and manifest files.
![iceberg_pre_vaccum](https://github.com/apache/iceberg/assets/135859358/9aaef7af-1f16-4684-ac10-1e413bdf9a5a)

I set the iceberg table property for garbage collection as below screenshot:
![iceberg_tp](https://github.com/apache/iceberg/assets/135859358/5ca3eb15-d712-4b3b-b2cd-960df920dda2)

after running the Vacuum command on the iceberg table through Athena console, I see old snapshots are removed, the associated manifest files are removed. However, all the metadata files are still there including the metadata version 0. The developer guide (https://docs.aws.amazon.com/athena/latest/ug/vacuum-statement.html) said that the Vacuum api call will "Removes any metadata and data files that are unreachable as a result of the snapshot removal." 
![iceberg_pv](https://github.com/apache/iceberg/assets/135859358/0efba92b-c544-43dc-8cdb-9bf8875ab3fe)

**Comment by nastra** [comment]
@wduan101 vacuum is an AWS Athena feature, not an Iceberg feature, so you'd rather want to take this AWS Athena
