### ISSUE TITLE
Spark: Document MergeSchema, AcceptAnySchema and Schema Evolution Code

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#8005]
### Feature Request / Improvement

Although we have had this feature for over a year and a half now there is no documentation for it.

Feature was originally added here 
https://github.com/apache/iceberg/commit/69c06cead6e5ddfe58c17630c4863eb98e04ff4e

And tests illustrating it's usage and the need for other Spark properties are shown here
https://github.com/apache/iceberg/blob/1f1ec4be478feae79b04bcea3e9a8556d8076054/spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2.java#L53-L178

We should add some quick docs and examples like in the tests to the Write page of the Spark Docs

### Query engine

Spark

**Comment by coded9** [comment]
could you assign to me @RussellSpitzer ?
