### ISSUE TITLE
Default Range Partioning w/Sorted Table causes performance issues

### ISSUE THREAD

**Issue by holdenk** [apache/iceberg#8010]
### Apache Iceberg version

1.1.0

### Query engine

Spark

### Please describe the bug 🐞

After upgrading to 1.1 w/Spark 3.3 we noticed that writes to a table with a sort order specified resulted in a range partioning of w/ only two partitions during the write phase (for an output of 22TB).

As a work around we can set write distribution mode to none and do our own sort (like before), but ideally we could do something "smarter" inside of Iceberg (or Spark?) and trigger a sort with some "extra" bits so that we don't end up with huge stuck partitions.

**Comment by RussellSpitzer** [comment]
I'm guessing this is probably AQE messing with us again? although 22TB and 2 partitions seems a bit obscene. If you can do a quick check can you see if the same behavior happens with 1.1 and 3.2? 

I know Anton is working on better requests of target size for AQE but that is in 3.4 I think?

**Comment by holdenk** [comment]
So I think (and I could be wrong here) that it's the exclusive range side effect rather than AQE per-se.

**Comment by RussellSpitzer** [comment]
This sounds like it will be a fun thing to figure out :(

**Comment by holdenk** [comment]
Ok! So I did some more digging and I _think_ the fix could go in the Iceberg side.

Spark's `RequiredDistributionAndOrdering` has an option `distributionStrictlyRequired()` which when true (which is the default) will force a repartition to match the desired dist to the T (see `DistributionAndOrderingUtils.scala`). I _think_ we might want instead to set it to false so we get `RebalancePartitions` which would allow `OptimizeSkewInRebalancePartitions` to maybe address the skew issue that we are seeing.

WDYT @RussellSpitzer ?

**Comment by holdenk** [comment]
Follow up: looks like this is set in Spark 3.4 w/Iceberg so it's probably fine already and a problem from using Spark 3.3.

**Comment by padraic00** [comment]
> Follow up: looks like this is set in Spark 3.4 w/Iceberg so it's probably fine already and a problem from using Spark 3.3.

Wish I found this thread a week ago. Fixed by bumping to EMR 6.12 (Spark 3.4)
