### ISSUE TITLE
Python: Update to pydantic V2

### ISSUE THREAD

**Issue by Polectron** [apache/iceberg#8030]
### Feature Request / Improvement

Recently pydantic V2 has been released, which made V1 deprecated and [will only receive critical bug fixes for 1 year](https://docs.pydantic.dev/2.0/version-compatibility/#pydantic-v1-support). We are planning on migrating our project to V2 but we are blocked because PyIceberg still relies on V1.

Migration to V2 should be pretty straightforward following this guide https://docs.pydantic.dev/2.0/migration/ and could bring several performance benefits to PyIceberg, according to pydantic, [V2 is between 4x and 50x faster than V1](https://docs.pydantic.dev/2.0/blog/pydantic-v2/#performance)

### Query engine

None

**Comment by glesperance** [comment]
@Fokko do you have any updates on this? I'm integrating ray into my codebase but I'm having to backport it to pydantic v1.10 -- is there perhaps a pre-release with v2 support?

**Comment by Fokko** [comment]
Hey @glesperance, PyIceberg is actually at Pydantic v2 with PyIceberg 0.5.0, previous versions are at 1.10.x. This ticket is still open, but can be closed.
