### ISSUE TITLE
How Can safely delete small files after executed  rewriteDataFiles

### ISSUE THREAD

**Issue by liuzx8888** [apache/iceberg#8066]
### Query engine

spark 3.2

### Question

When I execute the rewriteDataFiles API, the small files are merged into large files. These original small files still exist in the hdfs file. The root user is the merged large file, and the flink user is the original small file.

![image](https://github.com/apache/iceberg/assets/10862577/ea88917c-d207-4f10-8dcc-f5843ccad063)

trino query 'SELECT * FROM "fy_zy_fymx5$files"', the valid file is the file generated by executing the rewriteDataFiles API, the previous small file should be an invalid file
![image](https://github.com/apache/iceberg/assets/10862577/a3fa3ca2-7a9b-4c90-98cd-51226809cf02)

but  executed in order rewriteManifests api -->expireSnapshots api -->deleteOrphanFiles api

```
    //expireSnapshots
    if (operationMode.equalsIgnoreCase("expireSnapshots")) {
      val tsToExpire = System.currentTimeMillis()  
      SparkActions
        .get(spark)
        .expireSnapshots(table)
        .expireOlderThan(tsToExpire)
        .execute()
    }

    //deleteOrphanFiles
    if (operationMode.equalsIgnoreCase("deleteOrphanFiles")) {
      val olderThanTimestamp = System.currentTimeMillis
      SparkActions
        .get(spark)
        .deleteOrphanFiles(table)
        .olderThan(olderThanTimestamp)
        .prefixMismatchMode(PrefixMismatchMode.DELETE)
        .execute()
    }

    //rewriteManifests
    if (operationMode.equalsIgnoreCase("rewriteManifests")) {
      SparkActions
        .get(spark)
        .rewriteManifests(table)
        .execute()
    }
```
These small files still exist in hdfs and have not been deleted. How Can safely delete small files after executed  rewriteDataFiles API？

**Comment by liuzx8888** [comment]
@bitsondatadev If you can help me to solve this problem in your spare time, I will be very grateful, you have helped me solve the problem of good results before！！！

**Comment by JMin824** [comment]
you can use expireSnapshots API in this page [Procedures](https://iceberg.apache.org/docs/latest/spark-procedures/)

**Comment by chennurchaitanya** [comment]
i ran rewriteDataFiles/compaction from spark , it created big files and left small files.
Then i ran deleteOrphanFiles which have cleaned up all small files and its respective manifest list & manifest files.

try compaction then deleteOrphanFiles.

The issue i am facing is deleteOrphanFiles takes very long and i am hitting my platform timeouts.
