### ISSUE TITLE
Cannot add data files to target table because that table is partitioned and contains non-identity partition transforms which will not be compatible

### ISSUE THREAD

**Issue by ElsayedAwdElsayed** [apache/iceberg#8095]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I am integrating iceberg with Apache spark , I tried to create the table test partitioned by hour(EndTime) ,

```
create table local.db.test (
MSISDN string,
START_TIME timestamp,
END_TIME timestamp
)
USING iceberg PARTITIONED BY (hours(END_TIME)); 
```

then I tried to call a procedure to import the data from parquet files ,

```
CALL local.system.add_files(
  table => 'local.db.test',
  source_table => '`parquet`.`path/to/parquet/files`'
);
```
it supposed to work as in the documentation , but got this exception , 

`java.lang.IllegalArgumentException: Cannot add data files to target table local.db.test because that table is partitioned and contains non-identitypartition transforms which will not be compatible. Found non-identity fields [1000: END_TIME_hour: hour(3)]`

**Comment by rdblue** [comment]
The problem is that you can't add data files that don't match the partitioning of the table, and this table uses a partition strategy that is not compatible with Hive (it uses hidden partitions). You should set the partitioning of the table to the same as the Hive table, then run the import.

**Comment by atifiu** [comment]
@rdblue I was trying to do the same but in my case partitioning is same as I am trying to add files from the same table with the same partition transformation on a new table with exact same DDL except that I am changing the path of new table. Actually I am trying to change the path of existing table and there is no simple way in Iceberg so I have copied all the files from old table to a temp path (parquet files) and then trying to add_files to new table.
