### ISSUE TITLE
StarRocks link is going to the wrong URI

### ISSUE THREAD

**Issue by alberttwong** [apache/iceberg#8097]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

I can't figure out how to change the docs.   The StarRocks link should send people to https://docs.starrocks.io/en-us/latest/data_source/catalog/iceberg_catalog

**Comment by flyrain** [comment]
I couldn't find the place to change as well. It's in different repo?

**Comment by alberttwong** [comment]
https://github.com/apache/iceberg-docs/edit/main/docs/config.toml

**Comment by alberttwong** [comment]
https://github.com/apache/iceberg-docs/pull/255
