### ISSUE TITLE
Rewrite Existing Datafiles with new compression

### ISSUE THREAD

**Issue by W-I-D-EE** [apache/iceberg#8103]
### Query engine

Spark

### Question

If i have existing data files that were written with the default compression GZIP, how would can i get them to be rewritten using a different compression codec such as ZSTD?

I have attempted this using a Compaction but i have been unsuccessful at this writing out a different compression other than the default GZIP.

**Comment by W-I-D-EE** [comment]
Does this work with the Spark 2.4 implementation?

Something like:
`actions.rewriteDataFiles()
        .filter(Expressions.equal("date", "2023-07-19"))
        .set("rewrite-all", "true")
        .execute();`

Thanks!

**Comment by RussellSpitzer** [comment]
2.4 is basically in maintenance only, it doesn't have the new logic present in 3.x so that would not surprise me

**Comment by W-I-D-EE** [comment]
Appreciate it Russell.
