### ISSUE TITLE
SparkCatalog.load should continue resolving identifier on NoSuchNamespaceException

### ISSUE THREAD

**Issue by miR172** [apache/iceberg#8121]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I was using a customized catalog that on `load` throws `NoSuchNamespaceException` when the `Namespace` component of a `TableIdentifier` is not found. Only when namespace exists, will it check the table and throws `NoSuchTableException` if the table is not found.

IMO this behavior respects the Catalog.java API
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L326

However, when using this customize Catalog with a SparkCatalog I can't do time-travel read 
```
spark.read.option("snapshot-id", id).format("iceberg").load("catalog.namespace.table")
```
for `NoSuchNamespace` from my customize Catalog.
After debugging I found the root cause was [SparkCatalog will not try further on NoSuchNamespace from my Catalog](https://github.com/apache/iceberg/blob/master/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java#L573). Only `NoSuchTable` will be retried, so it failed before trying the pattern that I specified according to doc [here](https://iceberg.apache.org/docs/latest/spark-queries/#catalogs-with-dataframereader): 
this was when `namespace.table` was treated as a namespace. 

I think this is a bug because SparkCatalog is the one that decided to try using `namespace.table` as a namespace, therefore it could optimistically just continue trying other formats when that namespace does not exist. 

This should be a simple change, please let me know whether this make sense and I'll put up a merge request soon.

**Comment by nastra** [comment]
> I was using a customized catalog that on load throws NoSuchNamespaceException when the Namespace component of a TableIdentifier is not found. Only when namespace exists, will it check the table and throws NoSuchTableException if the table is not found.

> IMO this behavior respects the Catalog.java API
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L326

I don't think your assumption here is correct. `Catalog.loadTable()` only states `@throws NoSuchTableException if the table does not exist` and doesn't say anything about throwing a `NoSuchNamespaceException`. This is also the behavior that is implemented in [BaseMetastoreCatalog.loadTable()](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java#L43-L69).

**Comment by miR172** [comment]
Hmmm, so when the namespace is not found on ‘load(identifier)’, Catalog should still throw ‘NoSuchTable’? Isn’t that confusing? How does that help with debug?

**Comment by miR172** [comment]
Same question also asked in Slack. NoSuchTable seem to be the only allowed NOTFOUND here. 

Actually that’s not that bad in terms of clarity because I can chain the exception and still get the cause. I’ll close this.

**Comment by nastra** [comment]
Not every custom Iceberg catalog is required to support namespaces, that's why the `SupportsNamespaces` API exists and that's most likely the reason why `loadTable()` throws a `NoSuchTableException` rather than looking at the namespace part of the identifier

**Comment by miR172** [comment]
I'll use chained exception in the impl. 
Thanks for providing the context!
