### ISSUE TITLE
iceberg materialized views

### ISSUE THREAD

**Issue by kaijiezhang0319** [apache/iceberg#8143]
### Query engine

Spark 3.2

### Question

I am using Spark 3.2 load data from a iceberg materialized views which reference a iceberg table.  what i find is :  initially the iceberg table has 2 records, the view also has 2 records since it reference the table.  Then new record go to the table, i can find that the iceberg table refreshed which get 3 records total,  however seems the materialized views NOT refreshed and still keep in 2 records.  

It seems we have to reload the view, otherwise it keep in old status. 

i want to know, is there any cache logic in iceberg internally so the materialized views NOT refreshed to get the latest snapshot from the iceberg table ?  is there any way that we can auto refresh for the materialized view instead of reload it every time. thanks

**Comment by manuzhang** [comment]
Proposal for materialized view is still under discussion https://github.com/apache/iceberg/issues/6420
