### ISSUE TITLE
Docs: document the compareWithFileList parameter

### ISSUE THREAD

**Issue by bitsondatadev** [apache/iceberg#8155]
We should document the awesome compareWithFileList parameter that lets you use inventory reports for [remove_orphan_files in the docs](https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files). I had to find it after googling and stumbling on PR https://github.com/apache/iceberg/pull/4503.

https://apache-iceberg.slack.com/archives/C03LG1D563F/p1690322588417159

**Comment by fernandocast** [comment]
Hello @bitsondatadev, could you please assign me this issue?
I would like to contribute on this project

**Comment by bitsondatadev** [comment]
Done!

**Comment by Tavisca-vinayak-bhadage** [comment]
This compareWithFileList would be good solution for AWS S3 based iceberg tables also. As we are facing below exception with default remove orphan file implementation :

`org.apache.iceberg.exceptions.RuntimeIOException: java.io.IOException: com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown;)`

Is there any way to use compareWithFileList parameter from pyspark or spark-sql. As we are having AWS Glue as spark engine which is not supporting java Data Set api.
