### ISSUE TITLE
NullPointerException when doing FlinkEnvironmentContext.init() for Flink 1.17 and iceberg 1.3.0

### ISSUE THREAD

**Issue by zz5440435** [apache/iceberg#8159]
### Apache Iceberg version

1.3.0

### Query engine

None

### Please describe the bug 🐞

我这边尝试将flink作业打包后运行, 当执行到TableLoader类的FlinkEnvironmentContext.init()方法时, 如下代码
    public static void init() {
        EnvironmentContext.put("engine-name", "flink");
        EnvironmentContext.put("engine-version", FlinkPackage.version());
    }
发现FlinkPackage.version()报空指针异常, 通过判断确定是FlinkPackage中获取flink版本的值为NULL
    private static final String VERSION = DataStream.class.getPackage().getImplementationVersion();
如上, DataStream.class.getPackage().getImplementationVersion()获取不到版本号, 本地可以正常获取, maven打包后获取不到

**Comment by nastra** [comment]
This is most likely the same issue as https://github.com/apache/iceberg/issues/7879, indicating that there's a classpath issue. Are you creating your own uber jar?

**Comment by zz5440435** [comment]
> This is most likely the same issue as #7879, indicating that there's a classpath issue. Are you creating your own uber jar?

是的, 我是通过maven将代码以及第三方依赖打包后运行出现的, 
    public static void main (String[] args) throws Exception {
        // 获取当前flink版本
        System.out.println(DataStream.class.getPackage().getImplementationVersion());
        // 获取执行环境
        StreamExecutionEnvironment env = FlinkUtil.getProduceMode("dws");
}
上述代码, 在打包后运行的时候是可以获取到fink的版本, 但是在FlinkPackage中发现获取到的为NULL, 我只能尝试利用子模块重写FlinkPackage类覆盖依赖中FlinkPackage类来临时解决
