### ISSUE TITLE
Support partitioning and sorting on nested struct

### ISSUE THREAD

**Issue by lksvenoy-r7** [apache/iceberg#8175]
### Feature Request / Improvement

This feature request encompasses supporting specifying partitions and sort order on nested structs. It does not make sense to support this on lists nor maps, as these are collections with multiple values.

When ingesting data from different sources today, you have to flatten structs to the root-level of the table to allow partitioning and sorting on a specific column. While this is fine, being able to support partitioning on structs would allow for more flexibility in how a schema is defined.

For a concrete example, consider a schema for a table that looks like this
```
{
   eventId,
   ...
   timestamps {
      createdAt,
      lastSeenAt,
   }
}
```

If nested partitioning and sorting on structs was natively supported, defining a partition spec or sort order could be achieved without unnesting the structure. A json path could be used to define these specs, for example:
```
day(timestamps.createdAt)
```
And for sort order, in the same vein
```
{
    sortBy: timestamps.lastSeenAt,
    sortDirection: DESC,
    nullOrder: NULLS_LAST,
    caseSensitive: false

}
```

### Query engine

None

**Comment by lksvenoy-r7** [comment]
> Seems a reasonable request. What happens for partition/sort on struct fields?

Not sure what you mean. Is there any reason as to why the behaviour should be any different from partitioning or sorting on non-nested fields? I would imagine it to be completely orthogonal, partitioning/sorting on a nested field on a struct would be the equivalent of partitioning/sorting on a field that is present top-level.

**Comment by ConeyLiu** [comment]
I mean what's the problem are you met. I could create a table on a struct field:
```
scala> spark.sql("create table local.db.test_partition_struct(id long, data struct<id: long, ts: timestamp>) using iceberg partitioned by (years(data.ts))").show()

scala> spark.sql("insert into local.db.test_partition_struct values(1, struct(2, timestamp('2023-01-01')))").show()

scala> spark.sql("select * from local.db.test_partition_struct").show()
+---+--------------------+
| id|                data|
+---+--------------------+
|  1|{2, 2023-01-01 00...|
+---+--------------------+

scala> spark.sql("desc table local.db.test_partition_struct").show()
+--------------+--------------------+-------+
|      col_name|           data_type|comment|
+--------------+--------------------+-------+
|            id|              bigint|   null|
|          data|struct<id:bigint,...|   null|
|              |                    |       |
|# Partitioning|                    |       |
|        Part 0|      years(data.ts)|       |
+--------------+--------------------+-------+
```

**Comment by lksvenoy-r7** [comment]
Oh interesting, thank you @ConeyLiu. I asked in Slack and was told it wasn't possible, so was asked to create a feature request. If this is indeed possible then this isn't a problem of course.

**Comment by PROteinBY** [comment]
Probably found some bug here

```
object TestCaseClass {
  case class MyCaseClass(_1: Int, _2: Inner)
  case class Inner(id: Int, _2: String)
}

// ...

      spark
        .sql(
          s"create table test_partition_struct(_1 int NOT NULL, _2 struct<id: INT, _2: string>) using iceberg partitioned by (_1, _2.id)"
        )
        .show()

      Seq(MyCaseClass(1, Inner(1, "sample 1")), MyCaseClass(1, Inner(2, "sample 2")), MyCaseClass(2, Inner(1, "sample 3"))).toDF
        .writeTo("test_partition_struct")
        .overwritePartitions() // Writing using writeTo api
//      spark
//        .sql(
//          "insert into test_partition_struct values (1, struct(1, 'sample 1')), (1, struct(2, 'sample 2')), (2, struct(1, 'sample 3'))"
//        )
//        .show() // Writing using SQL
      spark.table("test_partition_struct").show(false)
```

It results in
```
+---+----+
|_1 |_2  |
+---+----+
|1  |null|
|1  |null|
|2  |null|
+---+----+
```

But if you uncomment SQL writing it will work as expected.

One more thing: if you change type of Inner id to Long it will work both using writeTo and SQL. But if you change create table statement to also use BIGINT for inner id, it won't work again.

**Comment by devinrsmith** [comment]
The spec does specifically allow for partitioning on a nested struct field.

https://iceberg.apache.org/spec/#partitioning
> The source columns, selected by ids, must be a primitive type and cannot be contained in a map or list, but may be nested in a struct.

I think a potential disconnect is that the libraries might not expose this functionality. I'm opening an issue for this.
