### ISSUE TITLE
Create table should take in sort order/ distribution mode

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#8179]
### Feature Request / Improvement

Looks like in Spark, alter table DDL can change sort order and distribution mode, but cannot set them.  We should support this, perhaps by Table Properties just like we take in the format-version today.

### Query engine

Spark

**Comment by rakesh-das08** [comment]
I think it would be a good to have feature. @szehon-ho , I would be glad to contribute if you are already not working on this.

**Comment by ajantha-bhat** [comment]
Linking an issue discussion that I created for the same 1.5 years ago.
https://github.com/apache/iceberg/issues/3547

**Comment by szehon-ho** [comment]
Hi, sure, I have not actively started yet

**Comment by szehon-ho** [comment]
Let me follow the discussion

**Comment by manuzhang** [comment]
Hi @fbertsch,

As per discussion in https://github.com/apache/iceberg/issues/3547, it would be better supported by engines, in your case, Spark.
