### ISSUE TITLE
Python: add support to optimize, analyze tables and expire snapshots, remove orphan files

### ISSUE THREAD

**Issue by alaturqua** [apache/iceberg#8183]
### Feature Request / Improvement

As an pyiceberg user I would like to be able to do following with PyIceberg:

- expire snapshots
- remove orphan files
- optimize tables
- analyze tables

Regards.

### Query engine

Other

**Comment by Fokko** [comment]
Thanks @alaturqua for raising this. It would be cool to add this. Can you elaborate on what you mean by analyze tables?

**Comment by alaturqua** [comment]
I mean letting it gather statistics. I don‘t know exactly if metadata files are holding statistics.

For example trino has this function:
`analyze table_name`
https://trino.io/docs/current/connector/iceberg.html#table-statistics

**Comment by Fokko** [comment]
@alaturqua That's an interesting thought. I think that should be quite straightforward. We could collect all the column metrics, and combine them to show `count`, `null_count`, `nan_count`, `min` and `max`.

**Comment by alaturqua** [comment]
@Fokko 

We are using hive metastore. But plan to switch to rest catalog, if it supports views in the future.

**Comment by Fokko** [comment]
This would be quite straightforward. You would need to implement the `_commit_table` to update the table properties for the Hive catalog, this is already done for the REST catalog.

**Comment by onerishabh** [comment]
Hey @Fokko, happy to start looking into some features here one by one. Would be great if each task is an issue and has a brief description about how to tackle it. 😃

**Comment by netanelm-upstream** [comment]
@alaturqua Hi, Can you please also add the rewriteManifests operation?
It can be very useful.

**Comment by alaturqua** [comment]
Hi @netanelm-upstream,

I created the feature request but unfortunately I do not have time to work on these in the next time.

I was hoping @Fokko would take these into his backlog.

**Comment by Fokko** [comment]
Thanks everyone for jumping in here.

- **Expire snapshots, and optimize table** These require write support, which we are working on! This will also include rewriteManifest operations.
- **Remove orphan files** Is something that could be done today. This would require listing all the files from the table, and also listing all the files from a specific directory. We could do this in the CLI where you get a prompt of the files that need to be deleted.
- **Analyze tables** We currently have listing capabilities in the CLI, maybe it would be cool to also include the min/max/nulls in there.

> I was hoping @Fokko would take these into his backlog.

Yes, I'm happy to, but we first need to get write support in :)

**Comment by Fokko** [comment]
I've migrated this issue to the new repository: https://github.com/apache/iceberg-python/issues/31 We definitely don't want to lose track of this! 👍
