### ISSUE TITLE
Python: Support `date`, `time` and `datetime` in `to_bytes`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8191]
### Feature Request / Improvement

We have the `to_bytes` in `conversions.py` to convert a Python type to actual bytes. We use this for writing partition values, and column metrics. It looks like we're inconsistent when writing logical types. When writing an uuid, we expect a `UUID`, but when writing a date, we expect an integer.

Would be great to also allow:

```python
from datetime import datetime, date, time

to_bytes(TimestampType(), datetime(2023, 3, 1, 19, 25, 0)
to_bytes(TimestamptzType(), datetime(2023, 3, 1, 19, 25, 0)
to_bytes(DateType(), date(2023, 3, 1, 19, 25, 0))
to_bytes(TimeType(), time(19, 25, 0))
```

Also, it is important to keep backward compatibility. For example for a `date`, if it is already an int, we should not raise an error, but just return the int (days since epoch).

### Query engine

Other

**Comment by onerishabh** [comment]
Hey, looking for my first contribution to this project. Can I give this a shot?

**Comment by Fokko** [comment]
@onerishabh Of course, that would be much appreciated.

**Comment by onerishabh** [comment]
@Fokko , could you share an example for `to_bytes(TimestamptzType(), datetime(2023, 3, 1, 19, 25, 0)
`. Just keen to see how timezones are being passed with datetime.

**Comment by onerishabh** [comment]
Hey @Fokko , created a PR #8214 . 

Just wondering, from_bytes always returns epoch timestamp (current state) or do we want it to return datetime objects? Once this is clear, I can add test cases in `test_from_bytes` and `test_round_trip_conversion`.
