### ISSUE TITLE
NamedReference::bind performance issue

### ISSUE THREAD

**Issue by lirui-apache** [apache/iceberg#8196]
### Apache Iceberg version

0.13.1

### Query engine

Trino

### Please describe the bug 🐞

`NamedReference::bind` works by creating a `Schema` from the `StructType` parameter. This usually means repeated creation of the Schema instance, which involves re-computing fields like `idToName`, `idToAccessor`, etc. So I wonder whether we can have an interface to directly work with a Schema parameter?
The following code takes about 1400ms on my laptop. If I bind against the Schema instance, run time is reduced to 40ms.
```java
public void test() throws Exception {
    List<Types.NestedField> fields = Lists.newArrayList();
    for (int i = 1; i <= 100; i++) {
      fields.add(Types.NestedField.optional(i, String.format("x%d", i), Types.IntegerType.get()));
    }
    Schema schema = new Schema(fields);
    Expression filter = Expressions.alwaysTrue();
    for (int i = 1; i <= 3; i++) {
      filter = Expressions.and(filter, Expressions.equal(String.format("x%d", i), i));
    }
    long start = System.currentTimeMillis();
    for (int i = 0; i < 10000; i++) {
      Binder.bind(schema.asStruct(), filter, false);
    }
    System.out.println(System.currentTimeMillis() - start);
  }
```
Some background: we implemented indexes that can be used to skip splits on Trino workers. For these indexes to work, the coordinator needs to distribute the filter expressions to workers. Therefore we need to access `FileScanTask::residual` on coordinator during split generation, which involves the evaluation and binding stuff. And we noticed it can become a hot spot method, or even the bottleneck of the whole query.

**Comment by ConeyLiu** [comment]
Yeah, this is indeed a performance problem that we have noticed as well, especially for tables with huge amounts of columns. We have implemented the binding to the schema directly internally. I could submit a PR recently.

cc @rdblue @aokolnychyi @szehon-ho

**Comment by szehon-ho** [comment]
Sounds good, nice find

**Comment by lirui-apache** [comment]
Yeah we are also binding against Schema internally. So far everything works fine.
