### ISSUE TITLE
Spec: define meta columns for row-level deletes

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#825]
In order to support the row-level delete, we may need to add some meta columns to the table schema, such as file name, row index and key.

**Comment by rdblue** [comment]
I don't think we need to add columns to schemas, although we can make additional columns available. We've discussed this in the Spark community and the plan was to allow Spark to project additional metadata columns when pruning.

**Comment by chenjunjiedada** [comment]
Thanks for the explanation. Do you mean that spark will pass schema with metadata columns and Iceberg doesn't need to add additional columns by itself? If Iceberg doesn't contain the separated logic for meta column handling, other engines will need to contain logic like what spark will do. Does those things we want to? 

BTW, do we have any jira or doc about the discussion? Many thanks if you could provide the link about the context.

**Comment by openinx** [comment]
@rdblue , from the perspective of flink, the iceberg update/delete feature should not depend on any spark-binded feature I think.  Any detail about the spark addition meta columns projection ?  I would see whether it work in flink, Thanks.

**Comment by rdblue** [comment]
@openinx, what I have working in Spark could be implemented in Flink as well. I've just updated Spark to be able to request additional columns, which I've currently named `_file` and `_pos`. The columns that can be requested are "metadata columns" so that `select *` doesn't show them.

The same code used to provide the metadata values to Spark could be used for Flink.

**Comment by rdblue** [comment]
Here's the Spark PR that adds metadata columns: https://github.com/apache/spark/pull/28027

I just ported that over from our internal branch, where we have it working and can project `_file` from Iceberg tables. I still need to add unit tests for it.

**Comment by jerryshao** [comment]
@rdblue I have a question about metadata columns defined in Spark. IIUC, if we want to merge base file and delete file, the file needs to be sorted by metadata column, this should be done by compute framework, shall we require metadata columns to be sorted? If not, how do we merge the base file and delete files?

**Comment by rdblue** [comment]
Metadata columns are a way to project extra fields on read. That allows us to attach identifying information to each row: the data file and the row's position in that file. There is no need to sort this on read. But when writing out a set of rows to delete, we want Spark to cluster the data by file and order by position, ascending. This is where we would use Anton's proposal to request a sort order from a write exec node. That way, Spark would insert the necessary shuffles and sorts to cluster data by file and locally order by file and position.

Does that make sense?

**Comment by jerryshao** [comment]
> But when writing out a set of rows to delete, we want Spark to cluster the data by file and order by position, ascending. This is where we would use Anton's proposal to request a sort order from a write exec node. That way, Spark would insert the necessary shuffles and sorts to cluster data by file and locally order by file and position.

Yes, that's actually what I asked. Adding metadata columns may not be enough for the readers to merge the base and diff files efficiently. I saw @aokolnychyi 's proposal about this, was thinking that proposal should be related to this thing.

**Comment by chenjunjiedada** [comment]
I was thinking to abstract the left join logic to handle both sorted case and unsorted case according to the column's sort property. In the case of unsorted one or small deletion files, we could do the hash join.
