### ISSUE TITLE
RemoveSnapshots can incorrectly remove files that are still valid

### ISSUE THREAD

**Issue by lirui-apache** [apache/iceberg#8255]
### Apache Iceberg version

0.13.1

### Query engine

None

### Please describe the bug 🐞

When expiring snapshots, it seems we assume deleted files in expired snapshots can be safely removed, which may not be true. The following test would fail because the file is deleted, even though it's still referenced by a valid snapshot.
```java
  @Test
  public void test() throws Exception {
    File file = temp.newFile();
    Assert.assertTrue(file.exists());
    DataFile dataFile = DataFiles.builder(SPEC)
            .withPath(file.getAbsolutePath())
            .withFileSizeInBytes(10)
            .withPartitionPath("data_bucket=0")
            .withRecordCount(1)
            .withFormat("orc")
            .build();
    table.newAppend().appendFile(dataFile).commit();
    table.newDelete().deleteFile(dataFile).commit();
    table.newAppend().appendFile(dataFile).commit();
    List<Snapshot> snapshots = Lists.newArrayList(table.snapshots());

    table.expireSnapshots().expireSnapshotId(snapshots.get(1).snapshotId()).commit();

    Assert.assertTrue(file.exists());
  }
```

**Comment by zhongyujiang** [comment]
You might want to take a look at this [spec](https://iceberg.apache.org/spec/#manifests), adding a deleted file back is not recommended.

**Comment by lirui-apache** [comment]
Hey @zhongyujiang @RussellSpitzer , thanks for the comments and pointers. I agree adding a deleted file back should not be encouraged. But the problem is we're unable to detect and block such usage. And leaving that burden to users seems unfriendly or even infeasible.
I also believe the spark algorithm does the right thing. So I guess we'll just always use the spark action to clean up expired files.
Thanks again, I'm closing the issue.
