### ISSUE TITLE
Support rebase one branch onto other branch

### ISSUE THREAD

**Issue by wangyinsheng** [apache/iceberg#8268]
### Feature Request / Improvement

Currently, we got multi branch in one table, when the main branch is updated , we need rebase the changes of the spec branch onto the main branch

### Query engine

Spark

**Comment by manuzhang** [comment]
Do you mean some changes of the main branch are not ancestors of the spec branch?

**Comment by wangyinsheng** [comment]
> Do you mean some changes of the main branch are not ancestors of the spec branch?

yes, maybe cherry-picked from the third branch to main branch. The scenario is that, we develop serveral branchs based on the main branch, once one of them is audited, the changes on this branch will be cherry-picked to the main branch, then the other branchs need rebase,  to catch up the main branch.

**Comment by wangyinsheng** [comment]
> How will you resolve conflicts if any?

The simplest way is abort the rebase. I haven't thought it clearly. Maybe there is more strategies. I raise this issue to discuss it

**Comment by manuzhang** [comment]
I suggest you to discuss this on dev list for wider audience.
