### ISSUE TITLE
Python: Add before- and after operations to `PreOrderSchemaVisitor`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8273]
### Feature Request / Improvement

Similar to the `SchemaVisitor` (which is post-order), we want to add the before- and after operations to the `PreOrderSchemaVisitor` to explicitly indicate that something has to happen before- or after an action.

In the `SchemaVisitor`: https://github.com/apache/iceberg/blob/master/python/pyiceberg/schema.py#L276-L304 These are missing here: https://github.com/apache/iceberg/blob/master/python/pyiceberg/schema.py#L331 And then they also need to be called in the visitor: https://github.com/apache/iceberg/blob/master/python/pyiceberg/schema.py#L781

### Query engine

None

**Comment by Fokko** [comment]
Related: https://github.com/apache/iceberg/pull/7831/files#r1285259053

**Comment by MehulBatra** [comment]
I would like to work on this.

**Comment by Fokko** [comment]
Migrated to new repository in https://github.com/apache/iceberg-python/issues/32 (also updated the links with permalinks)
