### ISSUE TITLE
Supporting `double` type for `truncate` partitioning

### ISSUE THREAD

**Issue by lgo** [apache/iceberg#8275]
### Feature Request / Improvement

Similar to some of the other asks, like #1671 which is asking for truncation on timestamp types, I've run into a specific use-case where we have timestamps stored as `double` on an existing column that we wish to partition. While we'd love to do something such use an alternative type which we could partition over, that's simply not possible due to the sheer volume of datasets, producers, and consumers involved.

I'll probably go ahead and plug it in sometime this week as it appears to be a short add to the current supported types with `truncate`.

### Query engine

None

**Comment by RussellSpitzer** [comment]
What would truncate of a double look like? Feels like that would be tricky to keep stable?
