### ISSUE TITLE
Add Apache Iceberg connector/support for PostgreSQL 

### ISSUE THREAD

**Issue by ahmedrachid** [apache/iceberg#8279]
### Feature Request / Improvement

Hello, I'm creating this Feature Request to know if there is a possibility to add support to querying/creating Apache Iceberg tables from PostgreSQL ? 

We're looking to use PostgreSQL as Catalog but also as a Lakehouse.

Many thanks.

### Query engine

Other

**Comment by nastra** [comment]
This is already possible today by using the `JDBCCatalog`. You can find some additional details here: https://iceberg.apache.org/docs/latest/jdbc/

**Comment by nastra** [comment]
Yes this would most likely be better approached in the PostgreSQL community rather than Iceberg itself

**Comment by vdittgen** [comment]
Hi @ahmedrachid i'm looking for a similar solution to have some Postgres tables reading from Iceberg data, like FDW. Have you found a solution?

**Comment by CincyBC** [comment]
@vdittgen There isn't a Foreign Data Wrapper for Iceberg at this time, but you can query from PSQL using PyIceberg. See this writeup for how: https://medium.com/datareply/unlocking-the-power-of-iceberg-within-postgresql-14e8ed2d8ccb
