### ISSUE TITLE
Extend `literal` with `date`, `datetime` and `time`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8282]
### Feature Request / Improvement

The `date`, `datetime` and `time` is currently not supported as literal value:
```
>>> from datetime import date
>>> literal(date(2023, 1, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/expressions/literals.py", line 148, in literal
    raise TypeError(f"Invalid literal value: {repr(value)}")
TypeError: Invalid literal value: datetime.date(2023, 1, 1)
```

We need to accept those as literal:

- **datetime** If there is a timezone, we want to convert it to a timestamptz. We can convert the datetime to an integer using `datetime_to_millis` in `datetime.py`.
- **time** We can convert this into an integer using `time_to_micros` from `datetime.py`
- **date** We can convert this into an integer using `date_to_days` from `datetime.py`

And include tests that hit the newly created branches in the if.

### Query engine

None

**Comment by Fokko** [comment]
Are you interested picking this one up @onerishabh?

**Comment by onerishabh** [comment]
Yes please! Keen on it. 😄

**Comment by Fokko** [comment]
Awesome! Let me know if you run into anything

**Comment by Fokko** [comment]
Thanks @onerishabh again for fixing this
