### ISSUE TITLE
Python: Migrate to Ruff

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8294]
### Feature Request / Improvement

I've been using Ruff at the Pola.rs project, and I really like it. I think we should replace Pylint, isort, and more with ruff since it is much faster and feature-complete.

This would require replacing the legacy tools with `ruff` in the `pre-commit` configuration.

### Query engine

None

**Comment by MehulBatra** [comment]
I can take this up

**Comment by Fokko** [comment]
Awesome, I've assigned the issue, thanks!
