### ISSUE TITLE
Python: Add `__repr__` to Table

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8295]
### Feature Request / Improvement

Table current doesn't have a `__repr__`: `<pyiceberg.table.Table object at 0x106cd9e50>` It would be nice to have something that tells something about the actual table.

### Query engine

None

**Comment by karthikmurali60** [comment]
@Fokko can i work on this issue? I'd love to contribute

**Comment by MehulBatra** [comment]
I can start working on this as I have some bandwidth

**Comment by Fokko** [comment]
@karthikmurali60 I missed your ping here, sorry about that. You're more than welcome to work on it.

@MehulBatra WDYT of https://github.com/apache/iceberg/issues/8294 or https://github.com/apache/iceberg/issues/8273.

**Comment by jayceslesar** [comment]
heads up this is closed by https://github.com/apache/iceberg/pull/8447
