### ISSUE TITLE
Improper commit message post table migration at the Nessie commit

### ISSUE THREAD

**Issue by harshm-dev** [apache/iceberg#8331]
### Apache Iceberg version

1.3.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Steps to repro:

* Migrate a table with existing snapshots on to the NessieCatalog using `registerTable(..)`

* The commit message is configured against the commit type of the current snapshot
```
Iceberg append against db.migration_table
Authored by: xx 2 minutes ago

Properties:
application-type: iceberg
iceberg.operation: append
```
https://github.com/apache/iceberg/blob/c1fc55022557653cfeb6125c1d51bf8ab12c8f96/nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java#L475C15-L475C28

The ask of this ticket is for a better commit message and `iceberg.operation`, which clearly identifies that it's a table registration activity.

**Comment by RussellSpitzer** [comment]
Register table does not create a new commit as far as I know. You are looking at the last commit to the table Sent from my iPhoneOn Aug 16, 2023, at 4:10 AM, Harsh Maheshwari ***@***.***> wrote:﻿
Apache Iceberg version
1.3.1 (latest release)
Query engine
Spark
Please describe the bug 🐞
Steps to repro:


Migrate a table with existing snapshots on to the NessieCatalog using registerTable(..)


The commit message is configured against the commit type of the current snapshot


Iceberg append against db.migration_table
Authored by: xx 2 minutes ago

Properties:
application-type: iceberg
iceberg.operation: append

https://github.com/apache/iceberg/blob/c1fc55022557653cfeb6125c1d51bf8ab12c8f96/nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java#L475C15-L475C28
The ask of this ticket is for a better commit message and iceberg.operation, which clearly identifies that it's a table registration activity.

**Comment by harshm-dev** [comment]
Thanks for the response. 

This is my read -
- [BaseMetastoreCatalog:registerTable](https://github.com/apache/iceberg/blob/c1fc55022557653cfeb6125c1d51bf8ab12c8f96/core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java#L87) invokes TO.commit
- [NessieTableOperations:commitTable](https://github.com/apache/iceberg/blob/c1fc55022557653cfeb6125c1d51bf8ab12c8f96/nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java#L139C7-L139C13  ) calls commitTable on the NessieIcebergClient
- [NessieIcebergClient:commitTable](https://github.com/apache/iceberg/blob/c1fc55022557653cfeb6125c1d51bf8ab12c8f96/nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java#L479) finally tries to commit into Nessie.

IMO we should be able to distinguish between the register and snapshot update cases by checking if the base metadata is present, and update the messages respectively.

**Comment by RussellSpitzer** [comment]
Ah so this is specifically for Nessie metadata, got it.
