### ISSUE TITLE
Export to Long Term Storage and Re Loading

### ISSUE THREAD

**Issue by W-I-D-EE** [apache/iceberg#8339]
### Query engine

Spark 3.2.3

### Question

We have a scenario where we need to export data files into long term tape storage, but still need to maintain the ability to re-add those datafiles if the data in question is needed. Based on our current understanding of Iceberg our procedure is as follows.

Exporting
1. Copy Data Files and its partition folders to tape storage.
2. Execute the deleteFile API on each of the exported datafiles to remove them from the iceberg table

Reloading
1. Copy File Structure back into the folder of the iceberg table data folder.
2. Execute the add_files on the partition folders that were copied into the system.

Based on what i described does anyone see potential issues with this approach. Is there something better recommended? One thing i guess im concerned about is how add_files would handle partition/spec evolution. Simple example being that lets say when we exported the data we had a bucket size of 16, but a year later when we went to reimport the data our table spec now uses a bucket size of 32. Is this a problem? Would we need to essentially rewrite the archived data files to match the current existing spec?

This is probably an unorthodox setup, but my situation is isolated environments with limited data storage resources, so there is a need to be able to move data around as its needed, but more importantly to make room for new data being generated.

Appreciate any feedback.

**Comment by szehon-ho** [comment]
Yea that may be a problem , if partition spec changes.  

I wonder if you can just move the files location (currently delete/add manually, as unfortunately relative paths is not there yet).  Basically whether you can keep them in the table?  Probably the best is if your file system support cold storage migration automatically, like S3 glacier?

**Comment by W-I-D-EE** [comment]
That is what i was afraid of. I am assuming there currently isn't any way to export the metadata about a set of files and bring those along when you re-import the data files?

Unfortunently the "hot" storage and the cold storage are two separate entities :'(. To make things even more complicated we have multiple independent clusters that sometimes need to transfer data between each other. So we would be adding data files to an iceberg table that wasn't even originally responsible for generating them.

**Comment by W-I-D-EE** [comment]
#7557 might actually solve my problem assuming it could be extended to the add_files API.
