### ISSUE TITLE
How can I use iceberg and Minio in the Flink engine?

### ISSUE THREAD

**Issue by aiwhj** [apache/iceberg#8347]
### Query engine

Flink + Minio

### Question

I have been reading the official documentation [AWS (apache.org)](https://iceberg.apache.org/docs/latest/aws/#glue-catalog), which suggests using org.apache.iceberg.aws.glue.GlueCatalog when using S3. However, when I use GlueCatalog, I always encounter an error stating that AWS_ACCESS_KEY_ID cannot be found. I have followed the documentation and tried various different formats for setting it, but the error persists.

```
CREATE TABLE `icebergresult` (
   `id` BIGINT NOT NULL,
   `name` STRING NOT NULL,
   `age` BIGINT NOT NULL,
   PRIMARY KEY (`id`) NOT ENFORCED
 ) WITH (
  'connector'='iceberg',
  'catalog-name'='test_log',
  'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',
  'warehouse'='s3://iceberg/my/key/prefix',
  'fs.s3.access.key' = 'DNxkAw**********',
  'fs.s3.secret.key' = 'YVMYE78PgQ8xBizDPm*************',
  'fs.s3.access-key' = 'DNxkAw**********',
  'fs.s3.secret-key' = 'YVMYE78PgQ8xBizDPm*************',
  'fs.s3.awsAccessKeyId' = 'DNxkAw**********',
  'fs.s3.awsSecretAccessKey' = 'YVMYE78PgQ8xBizDPm*************',
  'fs.s3.access-key-id' = 'DNxkAw**********',
  'fs.s3.secret-access-key' = 'YVMYE78PgQ8xBizDPm*************',
  'fs.s3.endpoint' = 'http://127.0.0.1:30619',
  's3.endpoint' = 'http://127.0.0.1:30619',
  's3.access-key' = 'DNxkAw**********',
  's3.secret-key' = 'YVMYE78PgQ8xBizDPm*************',
  's3.awsAccessKeyId' = 'DNxkAw**********',
  's3.awsSecretAccessKey' = 'YVMYE78PgQ8xBizDPm*************',
  's3.access-key-id' = 'DNxkAw**********',
  's3.secret-access-key' = 'YVMYE78PgQ8xBizDPm*************',
  's3.access.key' = 'DNxkAw**********',
  's3.secret.key' = 'YVMYE78PgQ8xBizDPm*************',
  'aws.accessKeyId' = 'DNxkAw**********',
  'aws.SecretAccessKey' = 'YVMYE78PgQ8xBizDPm*************',
  's3.path.style.access'= 'true',
  's3.path-style'= 'true',
  'client.region'='us-east-1',
  'io-impl'='org.apache.iceberg.aws.s3.S3FileIO'
 );
```

```
Flink SQL> select * from icebergresult;
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Could not execute SQL statement. Reason:
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])): Profile file contained no credentials for profile 'default': ProfileFile(profilesAndSectionsMap=[]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]
```

It seems like the error is returned by AWS rather than Minio, so I checked the source code of iceberg_runtime. When initializing the Client in GlueCatalog, awsClientFactory.glue() is used, but it doesn't seem to utilize applyS3EndpointConfigurations. This seems strange to me. Does GlueCatalog not support connecting directly to Minio's S3?

```
    // aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
    initialize(
        name,
        properties.get(CatalogProperties.WAREHOUSE_LOCATION),
        new AwsProperties(properties),
        awsClientFactory.glue(),
        initializeLockManager(properties));
```

```
    // aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
    @Override
    public S3Client s3() {
      return S3Client.builder()
          .applyMutation(awsProperties::applyClientRegionConfiguration)
          .applyMutation(awsProperties::applyHttpClientConfigurations)
          .applyMutation(awsProperties::applyS3EndpointConfigurations)
          .applyMutation(awsProperties::applyS3ServiceConfigurations)
          .applyMutation(awsProperties::applyS3CredentialConfigurations)
          .applyMutation(awsProperties::applyS3SignerConfiguration)
          .build();
    }

    @Override
    public GlueClient glue() {
      return GlueClient.builder()
          .applyMutation(awsProperties::applyClientRegionConfiguration)
          .applyMutation(awsProperties::applyHttpClientConfigurations)
          .applyMutation(awsProperties::applyGlueEndpointConfigurations)
          .applyMutation(awsProperties::applyClientCredentialConfigurations)
          .build();
    }
```

How should I configure these properties when using Minio? Can you provide an example?

**Comment by nastra** [comment]
For glue you could try and specify the [client.credentials-provider](https://github.com/apache/iceberg/blob/master/aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java#L52). However, I see that you specified a bunch of S3-related **table properties**, which is wrong. Those aren't used in any way.

You need to pass them when creating the catalog, meaning that you need to set **catalog properties** instead of **table properties**. See https://iceberg.apache.org/docs/latest/flink-configuration/#catalog-configuration.

Given that you want to use `S3FileIO`, you'd set only the ones that exist in https://github.com/apache/iceberg/blob/master/aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java#L43. In your case that would most likely be `s3.access-key-id` / `s3.secret-access-key` / `s3.path-style-access` / `s3.endpoint`.

**Comment by xiaowujee** [comment]
I also want to use it this way. Can you provide a complete example.    
My example：
```
CREATE CATALOG hadoop_catalog WITH (
    'type'='iceberg',
    'warehouse'='s3://flink194/hive/data',
    'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',
    'io-impl'='org.apache.iceberg.aws.s3.S3FileIO',
    's3.client-factory-impl'='org.apache.iceberg.aws.s3.DefaultS3FileIOAwsClientFactory',
    's3.access-key-id'='minio',
    's3.secret-access-key'='minio123',
    's3.endpoint'='http://minio:9000',
    's3.path-style-access'='true',
    'client.region'='us-east-1'
);
CREATE TABLE `hadoop_catalog`.`default`.`test`
(
    id   BIGINT COMMENT 'unique id',
    data STRING
);
```
However, error prompts
```
[ERROR] Could not execute SQL statement. Reason:
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])): Profile file contained no credentials for profile 'default': ProfileFile(profilesAndSectionsMap=[]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]
```

**Comment by aiwhj** [comment]
> For glue you could try and specify the [client.credentials-provider](https://github.com/apache/iceberg/blob/master/aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java#L52). However, I see that you specified a bunch of S3-related **table properties**, which is wrong. Those aren't used in any way.
> 
> You need to pass them when creating the catalog, meaning that you need to set **catalog properties** instead of **table properties**. See https://iceberg.apache.org/docs/latest/flink-configuration/#catalog-configuration.
> 
> Given that you want to use `S3FileIO`, you'd set only the ones that exist in https://github.com/apache/iceberg/blob/master/aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java#L43. In your case that would most likely be `s3.access-key-id` / `s3.secret-access-key` / `s3.path-style-access` / `s3.endpoint`.

Thank you for your reply. I tried creating a Catalog first and then creating a table based on the Catalog. I followed your suggestion to configure using client.credentials-provider, and the authorization step has passed. However, I encountered another error. It seems that it is not connecting to my Minio but instead connecting to the online AWS service.
```
CREATE CATALOG my_catalog WITH (
    'connector'='iceberg',
    'catalog-name'='test_log',
    'type'='iceberg',
    'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',
    'warehouse'='s3a://iceberg/my/key/prefix',
    'io-impl'='org.apache.iceberg.aws.s3.S3FileIO',
    's3.access-key-id'='DNxkAwJpbuB***',
    's3.secret-access-key'='YVMYE78PgQ8xBizDPm******',
    's3.endpoint'='http://minio:30619',
    's3.path-style-access'='true',
    'client.region'='us-east-1',
    'client.credentials-provider'='software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider',
    'client.factory'='org.apache.iceberg.aws.s3.DefaultS3FileIOAwsClientFactory'
);
```
```
CREATE TABLE `my_catalog`.`default`.`test`
(
    id   BIGINT COMMENT 'unique id',
    data STRING
);
```
![image](https://github.com/apache/iceberg/assets/16408168/a9c68abf-e858-4022-8617-16af4e23d771)

I found a configuration called `client.factory` and specified it as `org.apache.iceberg.aws.s3.DefaultS3FileIOAwsClientFactory`, but it resulted in an error: org.apache.iceberg.aws.s3.DefaultS3FileIOAwsClientFactory cannot be cast to org.apache.iceberg.aws.AwsClientFactory. 
![image](https://github.com/apache/iceberg/assets/16408168/47c5e751-dafb-450a-a45d-aa1ce1ecee31)

I'm not sure what to do next. Could you provide me with an example? Thank you.

**Comment by nastra** [comment]
Not sure if you meant to pass `DefaultAwsClientFactory` to `client.factory`, but `DefaultS3FileIOAwsClientFactory` can only be configured via `s3.client-factory-impl`, since it's expecting a different class hierarchy. In any case, I don't think you need to set `client.factory` at all (unless you wanted to provide your own implementation).

**Comment by nastra** [comment]
Also just FYI that https://github.com/tabular-io/docker-spark-iceberg/tree/main/flink-example uses Flink with Minio

**Comment by aiwhj** [comment]
> Also just FYI that https://github.com/tabular-io/docker-spark-iceberg/tree/main/flink-example uses Flink with Minio

I have come across this example before, but it uses RESTCatalog, and I don't quite understand why it is necessary to start a REST service as a bridge. However, the official documentation states that GlueCatalog can be used to access S3. Therefore, I have been continuously trying to use GlueCatalog.

**Comment by nastra** [comment]
The purpose of me linking the Flink example was to show how the Minio+Flink setup looks like, since you mainly had issues with the correct catalog configuration. In any case, were you able to successfully make Minio+Flink work and can this issue be closed?

**Comment by aiwhj** [comment]
> The purpose of me linking the Flink example was to show how the Minio+Flink setup looks like, since you mainly had issues with the correct catalog configuration. In any case, were you able to successfully make Minio+Flink work and can this issue be closed?

Okay, thank you very much.

**Comment by dyrnq** [comment]
Is there a way to avoid using system environment variables(AWS_ACCESS_KEY_ID) and system parameters(-Daws.accessKeyId)?

Because there may be multiple iceberg rest catalog on different s3 host.

**Comment by dyrnq** [comment]
@aiwhj  Hi, I found a way use CustomCredentialProvider, THAT as not using system environment variables and system parameters(-Daws.accessKeyId) for the flink cluster.

IcebergRestCatalog use CustomCredentialProvider sample using `table.api`, BUT I don`t know how do it in flink sql-client

<https://github.com/dyrnq/flink-coding/blob/main/src/main/scala/sample/IcebergRestCatalog.scala>
