### ISSUE TITLE
create cdc table on iceberg(type: hive) catalog 

### ISSUE THREAD

**Issue by tb77506668** [apache/iceberg#8369]
### Query engine

Flink 1.16.2

### Question

CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://svr51.yqzh.tech:9083',
  'clients'='5',
  'property-version'='1',
  'warehouse'='hdfs://svr51.yqzh.tech:8020/warehouse/iceberg-hive'
);

show catalogs;
use catalog hive_catalog;

CREATE TABLE products (
    db_name STRING METADATA FROM 'database_name' VIRTUAL,
    table_name STRING METADATA  FROM 'table_name' VIRTUAL,
    order_id INT,
    order_date TIMESTAMP(0),
    customer_name STRING,
    price DECIMAL(10, 5),
    product_id INT,
    order_status BOOLEAN,
    PRIMARY KEY(order_id) NOT ENFORCED
) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'database-name' = 'mydb',
    'table-name' = 'orders'
);

[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Creating table with computed columns is not supported yet.

**Comment by nastra** [comment]
This is because 
```
db_name STRING METADATA FROM 'database_name' VIRTUAL,
table_name STRING METADATA FROM 'table_name' VIRTUAL,
```
is currently not supported. Only physical columns are supported.

**Comment by tb77506668** [comment]
thanks
