### ISSUE TITLE
Docs: document the detail impact of the configuration 'compatibility.snapshot-id-inheritance.enabled'

### ISSUE THREAD

**Issue by zhongyujiang** [apache/iceberg#8375]
### Feature Request / Improvement

This configuration was [introduced](https://github.com/apache/iceberg/pull/675) to control whether data files are allowed to be committed without an explicit snapshot ID. When it is false (which is the default value), rewrite manifest procedure will copy all rewriten manifests before committing to make sure all manifest entries' snapshot-id is not null (so is add files procedure), which makes rewrite manfiest to be very slow. 
IIUC, this [config](https://github.com/apache/iceberg/pull/675#issuecomment-574107528) is only for compatibility for old readers and versions after #675 (0.8.0 and later versions) should all support snapshot-id inheritance when reading manifests, so it's safe to set this to `true` if no old versiosn are in use. If these are all true, then I think we should add these more detailed information in its [doc](https://iceberg.apache.org/docs/latest/configuration/#compatibility-flags) too, so users don't have to worry about the use of this configuration(#7325).

cc @aokolnychyi @rdblue could you take a look? Thanks.

### Query engine

None

**Comment by paulpaul1076** [comment]
Absolutely, I agree.
