### ISSUE TITLE
Python: Check if identifier fields are valid

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8386]
### Feature Request / Improvement

In Python we don't validate the `identifier_field_ids`.  We should check if they are required, and not float or decimal. For more information, check the spec: https://iceberg.apache.org/spec/#identifier-field-ids

### Query engine

None

**Comment by hililiwei** [comment]
May I have this ticket? I'd like to try it.

**Comment by Fokko** [comment]
@hililiwei Certainly, thanks!
