### ISSUE TITLE
Python: Fix promotion of DecimalType

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8389]
### Feature Request / Improvement

A Decimal has precision and scale. This is important for promotion when we promote a `decimal(4, 2)` to `decimal(4, 3)` then this doesn't fit, but is currently allowed. 

`decimal(4, 2)` can store `10.02`, and `decimal(4, 3)` can store `1.002`, but not `10.02` so we should not allow this promotion.

Coincidentally, I also worked on this on the Arrow side: The common precision should be calculated, and used as a lower bound for the promoted type: https://github.com/apache/arrow/pull/36846/files#diff-34166c61c1bd83226ad1277c13dca57ba9afa62dc7fba5206146ef6d2abf623eR383-R385

### Query engine

None

**Comment by hililiwei** [comment]
Where should this check action be performed now? Seems like it's only possible to implement it when we're done evolving the schema?

**Comment by Fokko** [comment]
There is already a very simple check in place: https://github.com/apache/iceberg/blob/master/python/pyiceberg/schema.py#L1461-L1469

We can update this one, add some tests to verify that it works, and then it automatically available when doing the schema evolution. Right now you could evolve the schema, but lose precision, and that's something that we don't want.

**Comment by hililiwei** [comment]
Okay, I'll try to fix it.

**Comment by rdblue** [comment]
@Fokko, promotion does not allow changing the scale of a decimal column.

**Comment by Fokko** [comment]
Thanks for jumping in here. That makes the change much easier

**Comment by Fokko** [comment]
Closing this since that's in already
