### ISSUE TITLE
exec insert into (hive on spark),no erro log,but table no data

### ISSUE THREAD

**Issue by 1043038630** [apache/iceberg#8426]
### Apache Iceberg version

1.1.0

### Query engine

Spark

### Please describe the bug 🐞

exec insert into (hive on spark),no erro log,but table no data. if use set hive.execution.engine=mr; can insert into table!

this is log:

1. 
set hive.execution.engine = mr;

SELECT  *  from iceberg_test2;

+--------------+----------------+
| student1.id | student1.name | 
+--------------+----------------+
| 赵匡胤| 20 |
| 赵普| 26 |
| 朱元璋| 25 |
+--------------+----------------+

2.
insert into table iceberg_test2 values('李世民',60);
SELECT  *  from iceberg_test2;
+--------------+----------------+
| student1.id | student1.name | 
+--------------+----------------+
| 赵匡胤| 20 |
| 赵普| 26 |
| 朱元璋| 25 |
| 李世民| 60 |
+--------------+----------------+

3.
set hive.execution.engine = spark;

insert into table iceberg_test2 values('李渊',80); -- no error log 

SELECT  *  from iceberg_test2;

+--------------+----------------+
| student1.id | student1.name | 
+--------------+----------------+
| 赵匡胤| 20 |
| 赵普| 26 |
| 朱元璋| 25 |
| 李世民| 60 |
+--------------+----------------+

4. look HDFS files  Existed

**Comment by pvary** [comment]
Hive on Spark is not supported for Hive-Iceberg.
Please check for the supported engines here: https://iceberg.apache.org/docs/latest/hive/

Also, you might want to try Hive 4.0.0-beta, as there is an out of the box integration there with Iceberg

**Comment by 1043038630** [comment]
> Hive on Spark is not supported for Hive-Iceberg. Please check for the supported engines here: https://iceberg.apache.org/docs/latest/hive/
> 
> Also, you might want to try Hive 4.0.0-beta, as there is an out of the box integration there with Iceberg



> Hive on Spark is not supported for Hive-Iceberg. Please check for the supported engines here: https://iceberg.apache.org/docs/latest/hive/
> 
> Also, you might want to try Hive 4.0.0-beta, as there is an out of the box integration there with Iceberg

Thank you very much
