### ISSUE TITLE
Can we do Client side Encryption with Iceberg format?

### ISSUE THREAD

**Issue by rajashree12bagal** [apache/iceberg#8431]
currently we are working on AWS environment. 
We are already having server side encryption on s3 bucket . 
But in order to secure data in transit , we are planning to use Client side Encryption with s3 bucket dedicated for iceberg format .
Is there any way we can perform client side encryption with Iceberg format?

**Comment by rdblue** [comment]
We're working on native encryption in Iceberg. You can probably use client-side encryption by either configuring S3A or by using S3FileIO. I'm not sure if the FileIO option supports it though.

**Comment by rajashree12bagal** [comment]
We have tried with S3FileIO. We are  not able to do client side encryption with Iceberg tables.
Is there any other way for the same?
