### ISSUE TITLE
Have a test utility method to programmatically create expected specs

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#8434]
### Feature Request / Improvement

See [here](https://github.com/apache/iceberg/pull/8381#discussion_r1310606954).

### Query engine

None

**Comment by jerqi** [comment]
@aokolnychyi  Could you assign this pr to me? I will solve this issue on this weekend.

**Comment by jerqi** [comment]
@aokolnychyi I have raised a pr #8467.
