### ISSUE TITLE
Logic about Hive version checking in MetastoreLock

### ISSUE THREAD

**Issue by Paddy0523** [apache/iceberg#8440]
### Query engine

Flink1.16

### Question

Why the findLock method check that HIVE_VERSION is higher than HIVE2
<img width="1140" alt="image" src="https://github.com/apache/iceberg/assets/46181516/31344b39-d37d-46b1-acae-d631e0213141">
 but ensure that HIVE_VERSION is less than HIVE2 before calling findLock
<img width="1109" alt="image" src="https://github.com/apache/iceberg/assets/46181516/299a6be4-d961-441d-89ff-c6e7bb5bb6db">

**Comment by pvary** [comment]
The `createLock` rethrows the exception we originally got if we can not use `findLock` to look for the lock. If we can use `findLock`, then we try to recover.

**Comment by Paddy0523** [comment]
> The `createLock` rethrows the exception we originally got if we can not use `findLock` to look for the lock. If we can use `findLock`, then we try to recover.

In the current logic, if an error occurs while obtaining the lock and HiveVersion is lower than Hive2, the findLock method is called and a new error is thrown in this code.
![image](https://github.com/apache/iceberg/assets/46181516/1e9b6780-bc41-4e55-bc52-8fd4e371e140)

**Comment by Paddy0523** [comment]
![image](https://github.com/apache/iceberg/assets/46181516/1644496d-8c07-4791-bc97-85ea9b9726b2)
Does the if statement need to be replaced with the following code
`if（HiveVersion.min(HiveVersion.HIVE2)）
`

**Comment by pvary** [comment]
@Paddy0523: Ohh, I get it...
Thanks for catching this.
Could you please create a test which fails in `TestHiveCommitLocks`, and fix this?

Thanks,
Peter

**Comment by Paddy0523** [comment]
> @Paddy0523: Ohh, I get it... Thanks for catching this. Could you please create a test which fails in `TestHiveCommitLocks`, and fix this?
> 
> Thanks, Peter

I'm happy to do it
