### ISSUE TITLE
IcebergParseException.getMessage does not show the below line

### ISSUE THREAD

**Issue by wForget** [apache/iceberg#8462]
### Apache Iceberg version

main (development)

### Query engine

Spark

### Please describe the bug 🐞

As the error log shows in https://github.com/apache/iceberg/issues/8448#issue-1876777674, I do not find the below  line that points the error position. like spark:

![image](https://github.com/apache/iceberg/assets/17894939/035cff09-a4da-4c7d-a6a1-84310302d16f)

**Comment by KirtiKamal** [comment]
@wForget I want to work on this issue can you assign me this Issue. Can you describe how you actually need in this.

**Comment by wForget** [comment]
> @wForget I want to work on this issue can you assign me this Issue. Can you describe how you actually need in this.

I have sent a PR #8463
