### ISSUE TITLE
unify streaming and batch, combining FLink and iceberg.In case In pipeline, Is kafka necessary?

### ISSUE THREAD

**Issue by hashmapybx** [apache/iceberg#8468]

**Comment by hashmapybx** [comment]
By reading some meetup shares, flow-batch integrated architecture，data must flow in kafka,then, reading data from kafka to iceberg. Now, I have a question, why need kafka?
<img width="496" alt="image" src="https://github.com/apache/iceberg/assets/26193074/b52b07f7-70ec-43af-b3e6-84d299ed65b3">

**Comment by jbonofre** [comment]
What about Apache Beam as API ?
