### ISSUE TITLE
Python: Cannot install from source code.

### ISSUE THREAD

**Issue by frankliee** [apache/iceberg#8482]
### Apache Iceberg version

The latest master.

### Query engine

Python.

### Please describe the bug 🐞

When I try to install pyiceberg from source code by pip3,   it will throw some errors due file missing.

`git clone https://github.com/apache/iceberg.git`

`cd iceberg/python`

`pip3 install -e ".[s3fs,hive]"`
 
(see: https://py.iceberg.apache.org)

My error Info:
”Directory  '.' is not installable. File 'setup.py' not found.“

**Comment by Fokko** [comment]
@frankliee what version of pip are you using? Can you try to update it?

Ps, you can also install it using a single line:
```
pip install "git+https://github.com/apache/iceberg.git#subdirectory=python&egg=pyiceberg[s3fs,hive]"
```

**Comment by frankliee** [comment]
Thanks, I upgrade pip from 8.1.2 to 20.0.2, and  installing from remote git url is worked. 

However, installing from local source code still has the similar error info with pip 20.0.2.

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode:xxxxx/iceberg/python
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by Fokko** [comment]
Which Python version are you using? Still, 20.0.2 is rather old. PyIceberg is Python 3.8+

**Comment by frankliee** [comment]
@Fokko Thanks for you reminder, the root cause is pip version, and pip 23.0 could compile pyiceberg correctly.

**Comment by Fokko** [comment]
@frankliee Thanks for letting me know. I've added a note on the website to update `pip`: https://github.com/apache/iceberg/pull/8484 Let's close this one as well, thanks for reporting this, since it will improve PyIceberg and the documentation
