### ISSUE TITLE
Upgrade to gradle 8.8

### ISSUE THREAD

**Issue by jbonofre** [apache/iceberg#8485]
### Feature Request / Improvement

Upgrade gradle wrapper to 8.3 version.

### Query engine

None

**Comment by Jake-00** [comment]
[pr](https://github.com/apache/iceberg/pull/7995) tells us that to update gradle version would omit build failure of breaking changes, we should estimate following impacts.

**Comment by ajantha-bhat** [comment]
@Jake-00: 
I saw your PR of https://github.com/apache/iceberg/pull/8577

Yes. We might have to raise issue to RevAPI to track this. We can't really hold the gradle upgrade because of revAPI for so long time. 

@nastra: WDYT?

**Comment by nastra** [comment]
> We might have to raise issue to RevAPI to track this

It was not an issue with RevAPI itself, but rather with Gradle. Something in the execution changed that would cause RevAPI failures to not be detected properly.
Is this still an issue with Gradle 8.3?

**Comment by jbonofre** [comment]
@nastra let me check for the RevAPI failures not detected. Thanks.

**Comment by jbonofre** [comment]
FYI, I tested `revapi` with Gradle 8.3 (on my PR). Here's the test I did:
* I added `void test();` method in `SessionCatalog`
* I added the corresponding `public void test() {}` in `RESTSessionCatalog`
So there's actually a change on the API.
With Gradle 8.1, `revapi` fails with `API/ABI breaks detected.`.
With Gradle 8.3, `revapi` doesn't fail, it doesn't detect the API change.

I'm investigating.

**Comment by ajantha-bhat** [comment]
> With Gradle 8.3, revapi doesn't fail, it doesn't detect the API change.

Yes. Thats what we have observed with Gradle 8.2 also. 
Maybe we need to raise an issue to revAPI team. If it is a Gradle issue they will divert us to there.

**Comment by jbonofre** [comment]
I think the problem is more on gradle or a mix with gradle and revapi gradle plugin. 

I'm doing a bisect on gradle to identify the change causing the issue.

**Comment by Fokko** [comment]
@jbonofre Gentle ping on this one!

A later version of Gradle is required to unblock #10209. The 1.14.0 version of Parquet ships with a newer version of Jackson, with JDK21-specific files. These files cause issues with the older version of the Shadow plugin that we're using. The shadow plugin requires a later version of Gradle.

**Comment by jbonofre** [comment]
Back on it. Sorry for the delay.

**Comment by Fokko** [comment]
@jbonofre No problem, we're all busy. I've split out the RevAPI change in https://github.com/apache/iceberg/issues/10368

**Comment by jbonofre** [comment]
Yeah. I saw that. Thanks. I'm working on both right now.
