### ISSUE TITLE
Can sparksql ddl define primary key now?

### ISSUE THREAD

**Issue by waywtdcc** [apache/iceberg#8508]
### Query engine

spark

### Question

Now can sparksql ddl define primary key, and attributes can also be used?

**Comment by ConeyLiu** [comment]
You could check the doc here: https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--set-identifier-fields

**Comment by jia-zhengwei** [comment]
> You could check the doc here: https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--set-identifier-fields

@ConeyLiu  What should I do after setting IDENTIFIER FIELDS ?  I can still insert into deduplicate rows by spark-sql cmd;

![image](https://github.com/apache/iceberg/assets/31585302/351c8894-056f-4c7c-a45e-015f29efb7f9)

**Comment by ConeyLiu** [comment]
You should use `MERGE INTO` to upsert in Spark. https://iceberg.apache.org/docs/latest/spark-writes/#merge-into

**Comment by zhangbutao** [comment]
> You should use `MERGE INTO` to upsert in Spark. https://iceberg.apache.org/docs/latest/spark-writes/#merge-into

Hi @ConeyLiu , IMHO, `MERGE INTO` has nothing to do with `IDENTIFIER FIELDS`? Right?

**Comment by baiyangtx** [comment]
`IDENTIFIER FIELDS`  only work for Flink Streaming upsert.

**Comment by ConeyLiu** [comment]
Yes, `IDENTIFIER FIELDS` is mostly used in equality delete files. Right now only Flink has implemented the MOR with equality delete files.

**Comment by zhangbutao** [comment]
Got it. It seems that the document https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--set-identifier-fields will give users the misconception that Spark can use` IDENTIFIER FIELDS` to deduplicate data.

**Comment by jia-zhengwei** [comment]
> Got it. It seems that the document https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--set-identifier-fields will give users the misconception that Spark can use` IDENTIFIER FIELDS` to deduplicate data.

@zhangbutao Yes, it confused me also. 

@ConeyLiu @zhangbutao Do you have any suggestion for using spark with duplicates data?

**Comment by ConeyLiu** [comment]
You should use `MERGE INTO` if you want to do upsert. `INSERT INTO` will append data instead of upsert data.

**Comment by jia-zhengwei** [comment]
> You should use `MERGE INTO` if you want to do upsert. `INSERT INTO` will append data instead of upsert data.

Got it, Thanks.
