### ISSUE TITLE
Iceberg does not trigger actually rewrite_data_files in certain situations

### ISSUE THREAD

**Issue by wanlce** [apache/iceberg#8510]
### Query engine

- Flink 1.13
- Spark 3.2
- Iceberg 1.2

### Question

The default file size for the merged target in iceberg is 512M. Currently, data is written to iceberg through Flink CDC. Due to the checkpoint time being 5 minutes, there will be a large number of small files generated. Therefore, we adopt a scheduling approach to regularly execute rewrite_data_files and execute expire_snapshots, the date is 3 days ago.

SQL Query:
```
 select count (1) as cnt from catalog. schema. tab. files where file_ Size<1M;
 ```
result:
  cnt=1.7w
then:
I manually execute, rewrite_Data_ Merge small files, return: No small files need to be merged

Question 1:
Why I manually trigger a small file merge operation without actually executing it ?

Question 2:
I don't see the corresponding parameters about rewrite_data_files on the official website, Is there a threshold for controlling whether small file merging is actually execute ?

**Comment by wanlce** [comment]
Sincerely hope to receive answers from the teachers  @nastra @wypoon
Thanks in advance!

**Comment by ConeyLiu** [comment]
You can check the doc here: https://iceberg.apache.org/docs/latest/spark-procedures/#usage-7. And the options doc
> See the [RewriteDataFiles Javadoc](https://iceberg.apache.org/javadoc/1.3.1/org/apache/iceberg/actions/RewriteDataFiles.html#field.summary), [BinPackStrategy Javadoc](https://iceberg.apache.org/javadoc/1.3.1/org/apache/iceberg/actions/BinPackStrategy.html#field.summary) and [SortStrategy Javadoc](https://iceberg.apache.org/javadoc/1.3.1/org/apache/iceberg/actions/SortStrategy.html#field.summary) for list of all the supported options for this action.

**Comment by dramaticlly** [comment]
I think one option we looked into in the past is using rewrite-all option, can read more in https://iceberg.apache.org/javadoc/1.3.1/org/apache/iceberg/actions/BinPackStrategy.html#REWRITE_ALL
