### ISSUE TITLE
Iceberg table support specified column comments by flinksql create

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/iceberg#8511]
### Feature Request / Improvement

When the current flinksql create the iceberg table, it cannot support the use of column comments. It should be supported.

### Query engine

Flink

**Comment by 372242283** [comment]
I also encountered this issue by checking that the field 'COMMENT' in the table 'COLUMNS-V2' in HMS is null and not written in
![image](https://github.com/apache/iceberg/assets/43502242/81df718d-69ed-4066-a924-284485c129a5)

**Comment by huyuanfeng2018** [comment]
@stevenzwu  In flink1.16 and before, it was impossible to parse the comment in the table creation statement. Starting from 1.17, the flink community completed this part of the logic, so I think icebrg should support parsing this part of the information and adding the comment to the field. WDYT, I can do this part

**Comment by huyuanfeng2018** [comment]
> @stevenzwu In flink1.16 and before, it was impossible to parse the comment in the table creation statement. Starting from 1.17, the flink community completed this part of the logic, so I think icebrg should support parsing this part of the information and adding the comment to the field. WDYT, I can do this part
https://issues.apache.org/jira/browse/FLINK-29679
