### ISSUE TITLE
Python: Write Metadata json

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8518]
### Feature Request / Improvement

With the REST catalog setting properties, and updating the schema is working. This is easy since the REST catalog is in charge of updating the metadata, and writing a new version of it. For the other catalogs, we need to write the metadata using PyIceberg and update the table property, pointing to the latest version of the metadata.

### Query engine

None

**Comment by Jake-00** [comment]
@Fokko  Hi, Fokko. I am insterested in this issue. And I need some helps since have just exposed to Iceberg.
