### ISSUE TITLE
Rest catalog server doesn't return table configuration as expected. 

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg#8526]
### Apache Iceberg version

1.3.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

According to rest [open api's spec](https://github.com/apache/iceberg/blob/621d301b17417af4b71a0e8c93db9db6f8266839/open-api/rest-catalog-open-api.yaml#L1899), the `loadTable` api should return configuration of table in `config` property.  This is not implemented in [rest server handler](https://github.com/apache/iceberg/blob/f3826bd9b1111d08262109df741ca8bf5aa0b697/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java#L256)

**Comment by liurenjie1024** [comment]
I'm happy to take this if confirmed that it's a bug.

**Comment by Fokko** [comment]
I see how this is a bit confusing. It is not required to return those configuration options, but it can be used to initialize the FileIO with the appropriate credentials to access the object store and point it to the right region. I don't think this is a bug, but we might want to rephrase the open-api spec a bit.

**Comment by liurenjie1024** [comment]
> I see how this is a bit confusing. It is not required to return those configuration options, but it can be used to initialize the FileIO with the appropriate credentials to access the object store and point it to the right region. I don't think this is a bug, but we might want to rephrase the open-api spec a bit.

So whether the configuration options are returned is dependent on the implementation?
