### ISSUE TITLE
Add `to_file` with Python API

### ISSUE THREAD

**Issue by jayceslesar** [apache/iceberg#8567]
### Feature Request / Improvement

Not sure if the Java iceberg supports this but it would be sweet to be able to write the output of a `TableScan` to some file-like system (cloud, local, ect). Maybe there is already some sort of support for this. Would help move https://github.com/ibis-project/ibis/issues/6013 forward.

### Query engine

None

**Comment by Fokko** [comment]
Closing this one in favor of https://github.com/apache/iceberg-python/issues/25
