### ISSUE TITLE
Write format arrow

### ISSUE THREAD

**Issue by qiunanx** [apache/iceberg#8580]
### Query engine

flink

### Question

1. Why are the writing formats only PARQUET, AVRO, ORC, and what about arrow format?
2.  What scenarios is the arrow format mainly used for?
3.  Can alluxio be used for storage when using arrow?

**Comment by ConeyLiu** [comment]
I think Arrow is not a storage format. It is a memory format. However, a storage like Parquet/orc/avro defines how data are stored.
