### ISSUE TITLE
[Proposal] An iceberg-unstructured module

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#859]
I think an Iceberg unstructured module would be great to have.  This is useful for datasets which do not have proper schema evolution rules [e.g csv] or are completely binary e.g ML models, but still can use Iceberg feature sets like snapshot isolation and partitioning.

This, of-course cannot be supported by any compute engine, this would be more of a standalone API like Iceberg generics module.

I'm unsure, we need  data reading capabilities. As a first version I'd be happy if we only support scan for the read side which can return the files as an Iterable, on the write side we can possibly support appending files to the table.

What do people think, should we build something like this?

**Comment by jerryshao** [comment]
I like this idea. The features like snapshot isolation are quite useful in different areas.

**Comment by shawnding** [comment]
Awesome. In ML area, user could save the  multiple versions embedded data to Iceberg.

**Comment by aokolnychyi** [comment]
There was a similar proposal described in #118. 

I think it is reasonable to support unstructured data in Iceberg with some limitations (e.g. schema evolution). If we do so, I believe it should be a complete implementation so that people using Spark CSV/JSON sources can migrate to it.

**Comment by rdblue** [comment]
Sounds like a good idea to me to extract the parts that can be used to track non-table datasets with atomic changes.

I think #118 is slightly different from my discussions with Matt. The idea there is to define an interface for file formats so you can plug in your own. Those interfaces will define capabilities that Iceberg would enforce. So if you use CSV or TSV, then Iceberg would only allow appending and renaming columns.

**Comment by LLsion** [comment]
> Discussion was in the non-apache Slack
> 
> https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1628242403033700



> I remember this, I forgot to note that I talked with the group internally who wanted this support. They basically had built very similar tooling although were building compressed binaries of all the files in a given addition to the table. So you could build a dataset by indicating which compressed binaries had the files you wanted along with the read offsets.

I want to know whether it is possible to store unstructured data such as pictures or videos through hdfs with iceberg. And it's hard for me to find the relevant API to export the data managed in iceberg. Hope you can answer my questions, thank you.
