### ISSUE TITLE
pyiceberg 0.5.0 cli __init__() takes at least 1 positional argument (0 given)

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg#8606]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

![image](https://github.com/apache/iceberg/assets/23215922/5909143c-1e56-4bac-99ef-748557697c38)
I `m using pyicberg 0.5.0 following the tutorial ，and 
<img src="https://github.com/apache/iceberg/assets/23215922/7316e556-6621-4c46-b45a-c8c1f61c6ec4" alt="Image" width="400" height="300">
encountered the following problem, how can i solve it
![image](https://github.com/apache/iceberg/assets/23215922/6d853434-8534-43ec-a3dd-c83723bf6ce2)
I have configured these items:
![image](https://github.com/apache/iceberg/assets/23215922/d83a1164-9643-4e41-a640-8b7884134f99)

**Comment by Fokko** [comment]
Thanks for raising this. I wasn't able to reproduce this with a rest catalog, let me set up a hive catalog.

**Comment by madeirak** [comment]
> Thanks for raising this. I wasn't able to reproduce this with a rest catalog, let me set up a hive catalog.

Thanks for reply, btw will pyiceberg support aliyun oss access in the future?
![image](https://github.com/apache/iceberg/assets/23215922/af191a0d-14f4-4441-9f3a-9b63fc9b9693)

**Comment by Fokko** [comment]
> Thanks for reply, btw will pyiceberg support aliyun oss access in the future?

I don't see any reason why not to support it, are you interested in contributing? :)
