### ISSUE TITLE
Large Iceberg Parquet file writes are (sometimes?) truncated

### ISSUE THREAD

**Issue by holdenk** [apache/iceberg#8620]
### Apache Iceberg version

1.1.0

### Query engine

Spark

### Please describe the bug 🐞

When we set the target file size > 4gb we've seen truncated files written to S3. This is an early bug report (still need to do a deeper dive and narrow down the repro).

**Comment by RussellSpitzer** [comment]
Ping, just to see if you’ve seen this again. I don’t have any local users with quite that large a target file size (I think 2GB is the largest) but I would love to know if you saw anything.

**Comment by holdenk** [comment]
So initial investigation with local writes only didn't find anything so my suspicion is it's in the S3 layer but I haven't had time to try and repro since.

**Comment by RussellSpitzer** [comment]
Thanks for the update, the only thing I've seen that's similar is some parquet files written where single column pages are corrupted. Very rare though and only on HDFS

**Comment by holdenk** [comment]
Oh hmmm I wonder if it's related to some magic we do with staging to HDFS sometime, I'll investigate that angle too if I can't repro with pure S3.
