### ISSUE TITLE
Update table failed due to concurrent modifications

### ISSUE THREAD

**Issue by lengkristy** [apache/iceberg#8636]
### Query engine

java SDK API

**Comment by lengkristy** [comment]
Caused by: software.amazon.awssdk.services.glue.model.ConcurrentModificationException: Update table failed due to concurrent modifications. (Service: Glue, Status Code: 400, Request ID: 710a23c5-718f-4b56-989b-55ad9afd9c52)

**Comment by nastra** [comment]
@lengkristy I think it would be helpful if you could attach the full stack trace, the Iceberg version you're using and which actions you're running

**Comment by lengkristy** [comment]
<html>
<body>


2023-09-25T17:44:21.178+08:00 | org.apache.iceberg.exceptions.CommitFailedException: Cannot commit glue_catalog.gu_iot_dev_eu_one_platform_result_9b02b87.fact_ota_data because Glue detected concurrent update
-- | --
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.aws.glue.GlueTableOperations.handleAWSExceptions(GlueTableOperations.java:355)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.aws.glue.GlueTableOperations.doCommit(GlueTableOperations.java:180)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:390)
  | 2023-09-25T17:44:21.178+08:00Copyat org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413) | at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
  | 2023-09-25T17:44:21.178+08:00 | at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:364)
  | 2023-09-25T17:44:21.178+08:00 | at com.harman.iceberg.IcebergWriter.save(IcebergWriter.java:121)
  | 2023-09-25T17:44:21.178+08:00 | at com.harman.ProcessKinesisRecords.handleRequest(ProcessKinesisRecords.java:65)
  | 2023-09-25T17:44:21.178+08:00 | at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
  | 2023-09-25T17:44:21.178+08:00 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2023-09-25T17:44:21.178+08:00 | at java.lang.reflect.Method.invoke(Method.java:498)
  | 2023-09-25T17:44:21.178+08:00 | at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:263)
  | 2023-09-25T17:44:21.178+08:00 | at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)
  | 2023-09-25T17:44:21.178+08:00 | at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
  | 2023-09-25T17:44:21.178+08:00 | at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:355)
  | 2023-09-25T17:44:21.178+08:00 | at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:72)
  | 2023-09-25T17:44:21.178+08:00 | at java.lang.Class.forName0(Native Method)
  | 2023-09-25T17:44:21.178+08:00 | at java.lang.Class.forName(Class.java:348)
  | 2023-09-25T17:44:21.178+08:00 | at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
  | 2023-09-25T17:44:21.179+08:00CopyCaused by: software.amazon.awssdk.services.glue.model.ConcurrentModificationException: Update table failed due to concurrent modifications. (Service: Glue, Status Code: 400, Request ID: 2de439bb-065b-4fb0-84f7-0079e1073f3b) | Caused by: software.amazon.awssdk.services.glue.model.ConcurrentModificationException: Update table failed due to concurrent modifications. (Service: Glue, Status Code: 400, Request ID: 2de439bb-065b-4fb0-84f7-0079e1073f3b)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:196)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
  | 2023-09-25T17:44:21.179+08:00 | at software.amazon.awssdk.services.glue.DefaultGlueClient.updateTable(DefaultGlueClient.java:13214)
  | 2023-09-25T17:44:21.179+08:00 | at org.apache.iceberg.aws.glue.GlueTableOperations.persistGlueTable(GlueTableOperations.java:331)
  | 2023-09-25T17:44:21.179+08:00 | at org.apache.iceberg.aws.glue.GlueTableOperations.doCommit(GlueTableOperations.java:160)


</body>
</html>
@nastra Hi this is full stack trace, thank you

**Comment by nastra** [comment]
@lengkristy thanks. Can you please also provide the other information I mentioned?

**Comment by lengkristy** [comment]
@nastra Sure, this is gradle dependencies:

implementation 'org.apache.iceberg:iceberg-core:1.3.1'
    implementation 'org.apache.iceberg:iceberg-parquet:1.3.1'
    implementation 'org.apache.iceberg:iceberg-data:1.3.1'
    implementation 'org.apache.iceberg:iceberg-hive-runtime:1.3.1'
    implementation ('org.apache.hadoop:hadoop-aws:3.3.0'){
        exclude(group:'com.amazonaws',module: 'aws-java-sdk-bundle')
    }
    implementation 'org.apache.hadoop:hadoop-common:3.3.0'
    implementation 'software.amazon.awssdk:s3:2.20.131'
    implementation 'software.amazon.awssdk:glue:2.17.122'
    implementation 'software.amazon.awssdk:sts:2.17.122'
    implementation 'software.amazon.awssdk:dynamodb:2.17.122'

and write iceberg table data with 4 concurrent:

below code:
//write data
        PartitionedFanoutWriter<Record> partitionedFanoutWriter = null;
        try {
            PartitionKey partitionKey = new PartitionKey(table.spec(), table.spec().schema());
            InternalRecordWrapper recordWrapper = new InternalRecordWrapper(table.schema().asStruct());
            // partitionedFanoutWriter will auto partitioned record and create the partitioned writer
            partitionedFanoutWriter = new PartitionedFanoutWriter<Record>(table.spec(), FileFormat.PARQUET, appenderFactory, outputFileFactory, table.io(), TARGET_FILE_SIZE_IN_BYTES) {
                @Override
                protected PartitionKey partition(Record record) {
                    try {
                        partitionKey.partition(recordWrapper.wrap(record));
                    }catch (Exception e){
                        System.out.println("write partition data error:" + e.getMessage() + ExceptionUtil.convertStackToString(e));
                    }
                    return partitionKey;
                }
            };
            for (PipelineData data : records) {
                try {
                    if (data.getRecord() != null)
                        partitionedFanoutWriter.write(data.getRecord());
                } catch (Exception e) {
                    System.out.println("write data error:" + e.getMessage() + ExceptionUtil.convertStackToString(e));
                    if (logger != null) {
                        logger.log("can not write iceberg table :" + data.getRecord().toString());
                        logger.log(ExceptionUtil.convertStackToString(e));
                        //record the data
                        logger.log(records.toString());
                    }
                    ProcessKinesisRecords.errRecords.add(data);
                }
            }
        } catch (Exception e) {
            //
            System.out.println("write data error:" + e.getMessage() + ExceptionUtil.convertStackToString(e));
            if (logger != null) {
                logger.log("can not write data to iceberg table:");
                logger.log(ExceptionUtil.convertStackToString(e));
            }
            throw e;
        }finally {
            if (partitionedFanoutWriter != null){
                partitionedFanoutWriter.close();
            }
        }

        //commit data
        try {
            System.out.println("start commit file,file size:" + partitionedFanoutWriter.dataFiles()[0].recordCount());
            AppendFiles appendFiles = table.newAppend();
            // submit datafiles to the table
            Arrays.stream(partitionedFanoutWriter.dataFiles()).forEach(appendFiles::appendFile);
            // submit snapshot
            appendFiles.apply();
            appendFiles.commit();
            System.out.println("committed file");
        } catch (Throwable e) {
            if (logger != null) {
                logger.log("ERROR: can not commit data to iceberg table:" + e.getMessage());
            }
            System.out.println("can not commit");
            ProcessKinesisRecords.errRecords.addAll(records);
            e.printStackTrace();
            throw e;
        }

**Comment by lengkristy** [comment]
and also get this error:
org.apache.iceberg.exceptions.CommitFailedException: Cannot commit  because base metadata location 's3://xxxx/00426-a7b003ff-2e45-4591-9561-10b9cded215e.metadata.json' is not same as the current Glue location 's3://xxxxx/00427-74a9323a-ffdd-47e8-a54f-278ce87425a0.metadata.json'
	at org.apache.iceberg.aws.glue.GlueTableOperations.checkMetadataLocation(GlueTableOperations.java:272)
	at org.apache.iceberg.aws.glue.GlueTableOperations.doCommit(GlueTableOperations.java:158)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135)
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:390)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:364)

**Comment by nastra** [comment]
If you are writing data concurrently, then `CommitFailedException` is an expected (and retryable) exception. What you could do is add some retry handling:

```
Tasks.foreach(ops)
          .retry(COMMIT_NUM_RETRIES_DEFAULT)
          .exponentialBackoff(
              COMMIT_MIN_RETRY_WAIT_MS_DEFAULT,
              COMMIT_MAX_RETRY_WAIT_MS_DEFAULT,
              COMMIT_TOTAL_RETRY_TIME_MS_DEFAULT,
              2.0 /* exponential */)
          .onlyRetryOn(CommitFailedException.class)
          .run(
              taskOps -> { 
                 // refresh table + perfom the commit
             });
```

**Comment by lengkristy** [comment]
> If you are writing data concurrently, then `CommitFailedException` is an expected (and retryable) exception. In your case, the `CommitFailedException` indicates that the table metadata was modified concurrently by another process, which means that the respective changes can't be applied without first refreshing the table you're doing the changes against. What you could do is add some retry handling:
> 
> ```
> Tasks.foreach(ops)
>           .retry(COMMIT_NUM_RETRIES_DEFAULT)
>           .exponentialBackoff(
>               COMMIT_MIN_RETRY_WAIT_MS_DEFAULT,
>               COMMIT_MAX_RETRY_WAIT_MS_DEFAULT,
>               COMMIT_TOTAL_RETRY_TIME_MS_DEFAULT,
>               2.0 /* exponential */)
>           .onlyRetryOn(CommitFailedException.class)
>           .run(
>               taskOps -> { 
>                  // refresh table + perfom the commit
>              });
> ```

@nastra Thanks, I will try it

**Comment by lengkristy** [comment]
I tested 100000 data, there is no error info, but iceberg just only received 98964 data:
![image](https://github.com/apache/iceberg/assets/37865070/34aed59b-5602-4d6a-8f86-a7b5c8bfc6e9)

**Comment by nastra** [comment]
@lengkristy it's difficult to say what might have gone wrong without having full visibility into your application code that handles those updates

**Comment by lengkristy** [comment]
> @lengkristy it's difficult to say what might have gone wrong without having full visibility into your application code that handles those updates

thanks @nastra, yeah, I catch all exception ,I think if not success, maybe there is error info, but the code running well and no error info , so it's very strange.

**Comment by nastra** [comment]
Catching all exceptions might be the reason for the discrepancy. In any case, I'll go ahead and close this issue, since throwing a CFE on conflict is expected.

**Comment by lengkristy** [comment]
OK, thank you
