### ISSUE TITLE
[InputFormat Followup] Add residual evaluation for Iceberg generics

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#866]
For standalone MR applications where the in memory data model is Iceberg Generics, we can add residual evaluation, like how we do it in `TableScanIterable`. See `org.apache.iceberg.data.TableScanIterable.ScanIterator#hasNext`

**Comment by chenjunjiedada** [comment]
Hi @rdsr , Will you take these follow-ups?

**Comment by rdsr** [comment]
Hi @chenjunjiedada, I may not be able to get to it soon. At least not for the next couple of weeks.
If somebody else wants to take it up, I can definitely help review.
