### ISSUE TITLE
How does iceberg solve the problem of small files? Is there any good solution?

### ISSUE THREAD

**Issue by huanghanyu-vungle** [apache/iceberg#8663]
### Query engine

spark:3.3.1
iceberg:1.2

### Question

When we designed the table structure, we extracted the timestamp from mongodb to partition the iceberg table. now we have encountered a problem, that is, the extraction time is scattered, For example, in the time difference processed today, there will be data from several years ago，If we don't want to lose data， We will generate many small files，Is there any good way to solve this problem?

**Comment by RussellSpitzer** [comment]
https://www.youtube.com/watch?v=4bOCDP-rhuM - One talk I did on this for Subsurface 2023

**Comment by Zhangg7723** [comment]
rewrite data files and position delete files with Spark, expire snapshots and clean orphan files periodically
