### ISSUE TITLE
Could there be duplicate values in the result returned by the findOrphanFiles method?

### ISSUE THREAD

**Issue by hwfff** [apache/iceberg#8670]
### Query engine

spark

### Question

Calling the removeOrphanFiles method may intermittently result in an error: "Exception in thread 'main' software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist.".So could there be duplicate values in the result returned by the findOrphanFiles method?

**Comment by RussellSpitzer** [comment]
I think it is much more likely that another process deleted the file or prefix while remove orphaned files was running. That said, we should be catching and not rethrowing this exception

**Comment by nk1506** [comment]
@RussellSpitzer , I want to look into it and fix it accordingly.

**Comment by nk1506** [comment]
@hwfff , could you please share the stack-trace if handy?

**Comment by nk1506** [comment]
Hi @hwfff , I tried to repro with duplicate files as well invalid files. Iceberg is catching all the errors while deleting the files. Although it has BulkDelete as well as single delete file operation. But both types are catching any exceptions. 
Ref:  [DeleteOrphanFilesSparkAction](https://github.com/apache/iceberg/blob/0259918eb2bac08beb1329f53046aa099de15021/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java#L246 )

If possible , Please share more details like following:

- Iceberg Version
- Engine details like spark with version. 
- Catalog details
- Also Stacktrace 

@RussellSpitzer , I couldn't find anything to fix here. Please correct me if I am wrong. I will plan to add test cases with concurrent `remove_orphan_files`.
