### ISSUE TITLE
Support Zorder for data writes (not just rewrites)

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#8674]
### Feature Request / Improvement

We currently support sort order for the data writes using (WRITE ORDERED BY). But we don't support Zorder in that. 
One of the user has asked it. Hence, raising the issue tracker.

https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1695906407332039

cc: @RussellSpitzer 

### Query engine

None

**Comment by rakesh-das08** [comment]
Would like to see some more discussion around this. And would like to work on this too.

**Comment by RussellSpitzer** [comment]
The multi-arg transform spec is up for review now @rakesh-das08 , please check that out. It's the first step
