### ISSUE TITLE
Spec disagrees with implementation on field names

### ISSUE THREAD

**Issue by JFinis** [apache/iceberg#8684]
### Apache Iceberg version

1.3.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

The [spec](https://github.com/apache/iceberg/blob/3f2884c6d2e514f1112bd440fedfbb7d30227a96/format/spec.md?plain=1#L545) calls the following fields as follows:

 504 added_files_count 
505 existing_files_count 
506 deleted_files_count

The [implementation](https://github.com/apache/iceberg/blob/3f2884c6d2e514f1112bd440fedfbb7d30227a96/api/src/main/java/org/apache/iceberg/ManifestFile.java#L55) calls them as follows:

    optional(504, "added_data_files_count"
      optional(505, "existing_data_files_count"
      optional(506, "deleted_data_files_count"
      
   
   (The `_data` is in the implementation, but not in the spec)

And hence the produced iceberg use these field names, which deviate from the names in the spec. Either the spec or the implementation should be updated.

**Comment by Fokko** [comment]
Thanks for raising this Jan. I made a first attempt to fix this a while ago: https://github.com/apache/iceberg/pull/5338

For context, this has been changed with v2, because then there were both data and delete files. Since Iceberg does the lookup by field-id, this should not impose an issue, but it is good to get it fixed.

**Comment by Fokko** [comment]
@JFinis You're in the right direction. `data_` should be left out.

> Do I get the gist of the discussion correctly? If so, do I understand correctly that we all agree that this should be fixed in the implementation, it was just not merged, yet?

It is on my list for today.
