### ISSUE TITLE
Add view support for Hive catalog

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#8698]
similar to https://github.com/apache/iceberg/pull/7913/

**Comment by ajantha-bhat** [comment]
@nk1506: Would you like to work on this?

**Comment by naveenkrdremio** [comment]
Yes, I would like to continue on this. Thanks @ajantha-bhat

**Comment by nk1506** [comment]
Yes, I would like to contribute on this.  Thanks @ajantha-bhat

**Comment by nk1506** [comment]
As part of this I have couple of questions ?
For IcebergTable we use TableType as [EXTERNAL_TABLE](https://github.com/apache/hive/blob/b02cef4fe943b9aba597dcdfd3b8f3d3a5efca3e/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/TableType.java#L26) as well as properties with [TABLE_TYPE_PROP](https://github.com/apache/iceberg/blob/16c2af49a142d7044b619403de3e52aed13893e0/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L413). 

With View Support:

1. We can set TableType as [VIRTUAL_VIEW](https://github.com/apache/hive/blob/b02cef4fe943b9aba597dcdfd3b8f3d3a5efca3e/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/TableType.java#L27) 
2. It will make implementation more clean.
3. We can also follow the strategy of managing extra field with table properties.
4. To make backward compatibility we must add the required checks every where. 
5. [IMetaStoreClient](https://github.com/apache/hive/blob/b02cef4fe943b9aba597dcdfd3b8f3d3a5efca3e/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java#L654) doesn't have specific APIs for Views. 
6. HiveTableOperations/HiveViewOperations must add all the required checks to manage same table/view name. 

Please share your thoughts. CC: @ajantha-bhat , @jbonofre . 
Also tag the relevant people.

**Comment by pvary** [comment]
@deniskuzZ: Is there there something like this ongoing in the Hive codebase?

**Comment by ajantha-bhat** [comment]
> Please share your thoughts. CC: @ajantha-bhat , @jbonofre .
Also tag the relevant people.

I think we can use `VIRTUAL_VIEW` type to avoid adding custom properties to the table. 


@pvary: 
Thanks for commenting. I was about to tag you. 
Since this is a change for HiveCatalog (to extend `BaseViewOperations`), I think it should be done in this repo? 
As per my knowledge, only the integration code with Hive 4.x is kept in Hive codebase.

**Comment by pvary** [comment]
@ajantha-bhat: The question is whether the Hive 3 HMS API is enough for the integration, or not. I would prefer if it would be enough, but we should definitely try to involve the Hive developers too.

**Comment by deniskuzZ** [comment]
> @deniskuzZ: Is there there something like this ongoing in the Hive codebase?

hi Peter, we have iceberg MV backed by iceberg table support in Hive where query definitions are stored in HMS and data in Iceberg table: HIVE-26578, HIVE-27101

**Comment by ajantha-bhat** [comment]
Closed via https://github.com/apache/iceberg/pull/9852
