### ISSUE TITLE
De-Duping Rows While Compacting

### ISSUE THREAD

**Issue by W-I-D-EE** [apache/iceberg#8702]
### Query engine

Spark 3.2.3

### Question

Looks like i can remove duplicate rows using MERGE INTO. Is there any way to do this during a compaction? Ideally i could remove deduplicate during a compaction rather than requiring two separate "actions".

**Comment by dramaticlly** [comment]
data compaction only change physical files layout but not the data visible to users. Consider you originally have 1000 records with 10 duplicates, after deduplication it would be 990 records and also file layout change, I think deduplication (with ability to identify the row based on primary key or unique row identifier) probably need its own action/procedure instead of rely on data compaction.

**Comment by W-I-D-EE** [comment]
Further to this, i have actually had a lot of trouble getting delete from or merge into working with removing duplicate rows. Today the only way i have been able to remove deuplicates its by selecting a dataset and then using the Dataframe.dropDuplicates function in spark. Finally using the dynamic overwrite to rewrite the partition.

Does anyone know of a better way to do this. Everything i have done with merge into or delete from always results in all records being removed instead of just the duplicated rows.

**Comment by d4r3topk** [comment]
+1 - I think this should be supported either in rewrite_data_files spark procedure as an option or have a separate spark procedure for this action (like a maintenance procedure)

**Comment by zenfenan** [comment]
+1 to have a dedicated `dedupe` Spark procedure. I believe while it may seem easier to add an extra option to the rewrite_data_files procedure, fundamentally they operate on separate objectives & rules. While rewrite_data_files always compact on per partition granularity, dedupe jobs may have to span across multiple partitions depending on the dedupe window.

I will try to draft a quick implementation proposal and summarise it here. I would like to implement and contribute.

**Comment by haggy** [comment]
@zenfenan Was there ever any progress made on this?
