### ISSUE TITLE
Spec: Add `141: spec_id` and `142: schema_id` to the spec

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#8712]
### Feature Request / Improvement

I noticed these fields are defined in the Java implementation:

https://github.com/apache/iceberg/blob/bc066a020b36ec039f6742d6270f3a55a4fcc7cb/api/src/main/java/org/apache/iceberg/DataFile.java#L100-L101

Should we add those to the spec as well?

### Query engine

None

**Comment by amogh-jahagirdar** [comment]
Just noticed this as well, will pick this up
