### ISSUE TITLE
Support deletion in Apache Flink

### ISSUE THREAD

**Issue by Gerrrr** [apache/iceberg#8718]
### Feature Request / Improvement

Hello community,

Is `DELETE FROM` support for Apache Flink already in the roadmap? Example:

```
CREATE TABLE word_count (
    word STRING,
    cnt BIGINT,
    PRIMARY KEY(`word`) NOT ENFORCED
) PARTITIONED BY (word) WITH (
    'format-version'='2', 
    'write.upsert.enabled'='true'
);

DELETE FROM word_count WHERE word = 'z';
[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Can't perform delete operation of the table nessie_catalog.db.word_count because the corresponding dynamic table sink has not yet implemented org.apache.flink.table.connector.sink.abilities.SupportsRowLevelDelete.
```

It looks like this functionality already exists at least for Apache Spark - https://iceberg.apache.org/docs/latest/spark-writes/#delete-from. 

### Query engine

Flink

**Comment by pvary** [comment]
Is this for a V2 table?
I have seen deleting rows working using V2 table, Java code with the stream API, but I yet to try out SQL.

**Comment by Gerrrr** [comment]
Yes, this is a V2 table. I added the DDL to the description now.

**Comment by VidakM** [comment]
Is `DELTE FROM` still on the roadmap for Flink or could we help out in some way?

**Comment by AjayChitumalla** [comment]
> Is this for a V2 table? I have seen deleting rows working using V2 table, Java code with the stream API, but I yet to try out SQL.

Can you share a reference for performing row level deletes on Iceberg V2 table using Flink DataStream API

**Comment by pvary** [comment]
If your input stream contains `-D` records, then they will be deleted from the table.
Like:
```java
      Row row = Row.withPositions(RowKind.DELETE, 3);
      row.setField(0, "hello");
      row.setField(1, true);
      row.setField(2, 1L);
```

**Comment by rlokugamage** [comment]
> If your input stream contains `-D` records, then they will be deleted from the table. Like:
> 
>       Row row = Row.withPositions(RowKind.DELETE, 3);
>       row.setField(0, "hello");
>       row.setField(1, true);
>       row.setField(2, 1L);

@pvary is this still the case?  Nothing in Iceberg's or Flink's documentation state that it can do row level deletes.  I need to test it out myself still but just needed some confirmation.  Are they positional deletes or equality deletes?

**Comment by pvary** [comment]
@rlokugamage: Here is where we state, that update is possible: https://iceberg.apache.org/docs/nightly/flink-writes/#insert-into

The documentation doesn't state how it is done, but it is working as I have described above.

**Comment by rlokugamage** [comment]
> [@rlokugamage](https://github.com/rlokugamage): Here is where we state, that update is possible: https://iceberg.apache.org/docs/nightly/flink-writes/#insert-into
> 
> The documentation doesn't state how it is done, but it is working as I have described above.

@pvary so if I just wanted to delete some data in a table,  I just need a datastream with RowKind.DELETE rows?

**Comment by pvary** [comment]
> > [@rlokugamage](https://github.com/rlokugamage): Here is where we state, that update is possible: https://iceberg.apache.org/docs/nightly/flink-writes/#insert-into
> > The documentation doesn't state how it is done, but it is working as I have described above.
> 
> [@pvary](https://github.com/pvary) so if I just wanted to delete some data in a table, I just need a datastream with RowKind.DELETE rows?

Exactly

**Comment by rlokugamage** [comment]
awesome, do you know if it's writing equality or positional deletes?
