### ISSUE TITLE
Support  Hudi `DeltaStreamer` compatible feature

### ISSUE THREAD

**Issue by LittleWat** [apache/iceberg#8724]
### Feature Request / Improvement

Hi! Currently, we are evaluating Iceberg & Hudi and both tools are great and provide similar features.

One thing we noticed that [Hudi Deltastreamer](https://hudi.apache.org/docs/0.13.1/hoodie_deltastreamer/#deltastreamer) makes it easy to ingest data and it would be great if Iceberg support similar feature.

Thank you!

### Query engine

None

**Comment by amogh-jahagirdar** [comment]
I'm not very familiar with Hudi Deltastreamer but for Kafka ingest into Iceberg tables, @bryanck is working on contributing a Kafka sink connector into the project https://github.com/apache/iceberg/pull/8701 check out this initial PR. Other than Kafka ingestion are there any other specific features you were looking for?

**Comment by LittleWat** [comment]
KafkaConnect is cool! Deltastreamer also supports [the distributed-file-system ingestion](https://hudi.apache.org/docs/0.13.1/hoodie_deltastreamer/#distributed-file-system-dfs). Using this, e.g. we can ingest the raw AVRO/CSV/JSON data in S3.

**Comment by pvary** [comment]
We use Flink for the ingestion.
Flink supports wide range of sources, and the Iceberg FlinkSink enables you to write them to Iceberg tables.

**Comment by LittleWat** [comment]
Yes, Flink is great but still we need to write some code for ingestion, right..? [Hudi Deltastreamer](https://hudi.apache.org/docs/0.13.1/hoodie_deltastreamer/#deltastreamer) is a kind of NoCode solution and I think it will make it easier to ingest data.

**Comment by pvary** [comment]
> Yes, Flink is great but still we need to write some code for ingestion, right..?

Yes, you need to write Flink the job's code. If your goal is just a simple dump, then it could be an overkill, but if you need to do any transformation, you can do it in your code easily
