### ISSUE TITLE
pos delete files not removed immediately after rewrite

### ISSUE THREAD

**Issue by zinking** [apache/iceberg#8743]
### Apache Iceberg version

1.4.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

org.apache.iceberg.spark.actions.TestRewriteDataFilesAction#testBinPackWithDeleteAllData

```
  public void testBinPackWithDeleteAllData() {
    Map<String, String> options = Maps.newHashMap();
    options.put(TableProperties.FORMAT_VERSION, "2");
    Table table = createTablePartitioned(1, 1, 1, options);
    shouldHaveFiles(table, 1);
    table.refresh();

    List<DataFile> dataFiles = TestHelpers.dataFiles(table);
    int total = (int) dataFiles.stream().mapToLong(ContentFile::recordCount).sum();

    RowDelta rowDelta = table.newRowDelta();
    // remove all data
    writePosDeletesToFile(table, dataFiles.get(0), total).forEach(rowDelta::addDeletes);

    rowDelta.commit();
    table.refresh();
    List<Object[]> expectedRecords = currentData();
    long dataSizeBefore = testDataSize(table);

    Result result =
        actions()
            .rewriteDataFiles(table)
            .option(BinPackStrategy.DELETE_FILE_THRESHOLD, "1")
            .execute();
  ```
  
  I am expecting after the rewrite, all position delete files should have gone, but here it remains. 

I did some debug (roughly), the manifest that these position delete files resides have a sequence number that is equal to the min data sequence number. so they remained

is this a bug or is it just working as expected.

**Comment by RussellSpitzer** [comment]
As expected, there is extensive discussion on this. The main issue being that only in the case of a "rewrite-all" are we sure we can remove delete files. There were some thought about special casing in removing delete files for just that action but we decided against it at the time.
