### ISSUE TITLE
Implementation does not write `schema-id` into Manifest Avro headers

### ISSUE THREAD

**Issue by JFinis** [apache/iceberg#8745]
### Apache Iceberg version

1.3.1

### Query engine

Spark

### Please describe the bug 🐞

The spec mandates the field `schema-id` to be written into the Avro header of Manifest files (optional in v1, required in v2).

Yet, the implementation neither writes the field in v1 nor v2.

Also note that the field is somehow redundant, as the `schema-id`, if present, will also be in the `schema` itself, which is in the header as well.

Suggestion: Remove mentioning of field completely from the spec. It's redundant and the implementation doesn't seem to write it anyway.

**Comment by Fokko** [comment]
@JFinis I think this was in there so the schema didn't need to be deserialized. 

> Suggestion: Remove mentioning of field completely from the spec. It's redundant and the implementation doesn't seem to write it anyway.

WDYT of creating a PR, and also raising this on the dev list?
