### ISSUE TITLE
Some questions about Iceberg's capabilities in Flink

### ISSUE THREAD

**Issue by jonathf** [apache/iceberg#8754]
### Query engine

Flink 1.15.2

### Question

There might be a page for this, but I am wondering if there exists an overview of capabilities of iceberg on Flink. Here are some that come to my mind:

1.  Does iceberg support being a lookup table?
2. If so, does it support processing time, event time or both?
3. Does Iceberg support being a streaming source?
4. If so, does it support watermarking?
5. Some sort of throttling so that it plays nice joining it with other realtime streams?

**Comment by pvary** [comment]
> 1. Does iceberg support being a lookup table?

No, I do not think so.

> 2. If so, does it support processing time, event time or both?

See above

> 3. Does Iceberg support being a streaming source?

Currently it is supported for Append only tables.

> 4. If so, does it support watermarking?

We are currently working on this: #8553

> 5. Some sort of throttling so that it plays nice joining it with other realtime streams?

I think the OOB Flink watermark alignment could help you here.

**Comment by jonathf** [comment]
Thank for the swift reply, @pvary! And thanks for your contributions on #8553. Hoping for/Looking forward to it being merged.

One followup question: What is OOB? I am not familiar.

**Comment by pvary** [comment]
Sorry for the confusion 😄 
I meant Out Of The Box, but missed the T

**Comment by jonathf** [comment]
Okay, that explains it.

Last two questions:
* Will #8553 support some sort of ordering guaranty?
* Is the streaminig feature associated with icebergs tagging features? This might be a weird question, but I have heared some people mentioning it, though I can not see it written anywhere.

**Comment by pvary** [comment]
> * Will [Flink: Emit watermarks from the IcebergSource #8553](https://github.com/apache/iceberg/pull/8553) support some sort of ordering guaranty?

Could you please elaborate on the question?
In #8553 The splits/files will ordered by watermarks, and the streaming api will fetch new splits based on the `monitor-interval`. 

In an ideal world the `monitor-interval` is much shorter than the commit frequency. On startup we read the splits/files ordered based on the Iceberg column metrics for the given column, and after that we the commits 1-by-1. This does not entirely prevent out of order reads, but if the timestamps are written in order, then they are most likely read in order as well.

> * Is the streaminig feature associated with icebergs tagging features? This might be a weird question, but I have heared some people mentioning it, though I can not see it written anywhere.

If you ask, whether the braches are supported in streaming reads, then the answer is "yes"

**Comment by pvary** [comment]
> > > * Is the streaminig feature associated with icebergs tagging features? This might be a weird question, but I have heared some people mentioning it, though I can not see it written anywhere.
> > 
> > 
> > If you ask, whether the braches are supported in streaming reads, then the answer is "yes"
> 
> Not really. I was wondering if tagging was required to get this functionality. Sounds to me that the answer to that it is not.

You are right, that tagging is not required for Flink streaming reads
