### ISSUE TITLE
How is iceberg compatible with hive's tez engine

### ISSUE THREAD

**Issue by dragon-feng** [apache/iceberg#8757]
### Question

How is iceberg compatible with hive's tez engine

**Comment by pvary** [comment]
There are some missing features in Hive3's Tez dependency, so DML operations are not supported with Hive3 and Tez. See: https://iceberg.apache.org/docs/latest/hive/#feature-support

On the other hand Hive4 supports Iceberg out of the box. You just download, and use Iceberg tables.
