### ISSUE TITLE
How can I quickly insert data into an iceberg table in a Python environment?

### ISSUE THREAD

**Issue by 1taoze** [apache/iceberg#8801]
### Query engine

Environment:    Presto + Hive-Metastore + Minio

### Question

Is it too slow to import data into an iceberg table that exists in minio through presto.    Is there any fast way to import data?

**Comment by amogh-jahagirdar** [comment]
I guess there are a few different topics here:

> Is it too slow to import data into an iceberg table that exists in minio through presto.

Slow or fast depends on your requirements, your ingestion pattern, table layout etc :)  If you could provide more details that would be helpful. I would say, I don't know about Presto's support for Iceberg, but Trino has a actively maintained Iceberg connector.

>How can I quickly insert data into an iceberg table in a Python environment?

Python write support is actively being worked on, cc @Fokko , you can follow the progress https://github.com/apache/iceberg-python , contributions/feedback always welcome!
