### ISSUE TITLE
How to read data in the order in which files are commited?

### ISSUE THREAD

**Issue by Zhanxiao-Ma** [apache/iceberg#8802]
### Query engine

Iceberg java api(Version 0.14.1)

### Question

I want the data read from iceberg to be in the same order every time. But I can't find an attribute that would make FileScanTask ordered. Is there a way I can implement it?

**Comment by pvary** [comment]
Currently there is no way to order the scan task. The planning side specifically makes sure that even the planning could be done by parallel threads (reading manifests files parallel)

Sometimes we need to do similar thing in Flink Source, and we ended up creating our own comparator for this which compares Iceberg splits (which are a wrapper above ScanTasks).

You can do something similar like this in java code with one serious caveat: For a big table you might not want/able to keep all of the tasks in memory, which is needed for sorting. What we do in flink is limit the number of snapshots to read once.

I hope this helps,
Peter

**Comment by amogh-jahagirdar** [comment]
Thanks @pvary, I have a maybe naive question @MarsKT 

> want the data read from iceberg to be in the same order every time. 

Can I ask what's driving this need?

**Comment by MarsKT** [comment]
> Thanks @pvary, I have a maybe naive question @MarsKT
> 
> > want the data read from iceberg to be in the same order every time.
> 
> Can I ask what's driving this need?

The users of a data analytics software that utilizes a data lake as its storage layer desire consistent data ordering when viewing the data.

**Comment by Zhanxiao-Ma** [comment]
> Currently there is no way to order the scan task. The planning side specifically makes sure that even the planning could be done by parallel threads (reading manifests files parallel)
> 
> Sometimes we need to do similar thing in Flink Source, and we ended up creating our own comparator for this which compares Iceberg splits (which are a wrapper above ScanTasks).
> 
> You can do something similar like this in java code with one serious caveat: For a big table you might not want/able to keep all of the tasks in memory, which is needed for sorting. What we do in flink is limit the number of snapshots to read once.
> 
> I hope this helps, Peter



> Currently there is no way to order the scan task. The planning side specifically makes sure that even the planning could be done by parallel threads (reading manifests files parallel)
> 
> Sometimes we need to do similar thing in Flink Source, and we ended up creating our own comparator for this which compares Iceberg splits (which are a wrapper above ScanTasks).
> 
> You can do something similar like this in java code with one serious caveat: For a big table you might not want/able to keep all of the tasks in memory, which is needed for sorting. What we do in flink is limit the number of snapshots to read once.
> 
> I hope this helps, Peter



> Currently there is no way to order the scan task. The planning side specifically makes sure that even the planning could be done by parallel threads (reading manifests files parallel)
> 
> Sometimes we need to do similar thing in Flink Source, and we ended up creating our own comparator for this which compares Iceberg splits (which are a wrapper above ScanTasks).
> 
> You can do something similar like this in java code with one serious caveat: For a big table you might not want/able to keep all of the tasks in memory, which is needed for sorting. What we do in flink is limit the number of snapshots to read once.
> 
> I hope this helps, Peter

>

**Comment by Zhanxiao-Ma** [comment]
> Sometimes we need to do similar thing in Flink Source, and we ended up creating our own comparator for this which compares Iceberg splits (which are a wrapper above ScanTasks).

I'm sorry, I didn't quite understand this point. Could you please explain it in more detail?
