### ISSUE TITLE
[JdbcCatalog] Issue with Namespace Exists

### ISSUE THREAD

**Issue by haizhou-zhao** [apache/iceberg#8832]
### Apache Iceberg version

main (development)

### Query engine

Other

### Please describe the bug 🐞

Currently, JdbcCatalog relies on this sql statement to check whether a namespace exists:

`"SELECT TABLE_NAMESPACE  FROM CATALOG_TABLE_NAME WHERE CATALOG_NAME  = {} AND  TABLE_NAMESPACE  LIKE {}% LIMIT 1"`

It gives undesired result in this scenario:

1. Create a namespace `my_ns`
2. Create a namespace `my_ns_1`
3. Create a table `my_ns_1.tbl1`
4. Drop namespace `my_ns`
5. Check namespace exists on `my_ns` will return true, which should have been false

It happens because, at step 5, `my_ns_1` still exists and matches query `"SELECT TABLE_NAMESPACE  FROM CATALOG_TABLE_NAME WHERE CATALOG_NAME  = jdbc AND  TABLE_NAMESPACE  LIKE my_ns% LIMIT 1"`. I believe the root cause is that particular sql statement, with regex like "my_ns%", cannot different between "my_ns" and "my_ns_1".

**Comment by amogh-jahagirdar** [comment]
Thanks for reporting @haizhou-zhao , this is a surprising behavior. I put up a fix for this in #8833 to do exact search, let me know what you think.

**Comment by nastra** [comment]
Sounds like a similar issue to https://github.com/apache/iceberg/issues/8321. @amogh-jahagirdar should we get #8321 reviewed first and then we can address any leftovers in this PR?

**Comment by Fokko** [comment]
For context, we've also noticed this when porting the JDBC Catalog to Python and decided to leave out the wildcard over there.

**Comment by amogh-jahagirdar** [comment]
> Sounds like a similar issue to #8321. @amogh-jahagirdar should we get #8321 reviewed first and then we can address any leftovers in this PR?

Ooh missed #8321, yes lets get that in first!

**Comment by amogh-jahagirdar** [comment]
We can close this issue as well, now that #8340 is in
