### ISSUE TITLE
Distributed execution of DeleteReachableFilesSparkAction

### ISSUE THREAD

**Issue by tmnd1991** [apache/iceberg#8862]
### Feature Request / Improvement

Allow to execute `DeleteReachableFilesSparkAction` in distributed fashion using Spark executors.

### Query engine

Spark

**Comment by RussellSpitzer** [comment]
It is distributed in file discovery. Do you mean have the deletes distributed? Previously we didn't want to do this because it's very difficult to control parallelism of delete requests

**Comment by tmnd1991** [comment]
Hi @RussellSpitzer , yes I mean having the delete operations distributed. I guess it’s difficult because you don’t know how many spark executor cores you might have in any given moment, am I right?

**Comment by RussellSpitzer** [comment]
Yep, in our experience we have also seen a single driver is sufficient to issue a very large number of deletes.
