### ISSUE TITLE
Iceberg vs Parquet

### ISSUE THREAD

**Issue by hieuLapTop77** [apache/iceberg#8876]
### Query engine

I am using Spark version 3.4.1

### Question

I wonder about the strengths of Apache Iceberg compared to Apache Parquet. I have used Spark SQL to compare query speed between tables with Iceberg and Parquet, and I've noticed that Parquet is faster. Can you please explain this to me? Thank you.

**Comment by pvary** [comment]
@hieuLapTop77: Apache Parquet is a file format - it describes how the data is written to files, while Apache Iceberg is a table format - while it defines how the data is written to files, it also describes how these files are actually organized to a database table. 
The talks here could help you understand better: https://iceberg.apache.org/talks/
Especially this talk for the basics: https://www.youtube.com/watch?v=mf8Hb0coI6o
