### ISSUE TITLE
Document that distribution modes do not work with  DataFrameWriterV2 API  Create statements [Documentation]

### ISSUE THREAD

**Issue by a-agmon** [apache/iceberg#8887]
### Apache Iceberg version

1.4.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Spark writes are currently using hash as default distribution modes, however distribution modes are not handeled in DataFrameWriterV2 API create statement.
There is a PR (https://github.com/apache/spark/pull/40734) that is supposed to handle this, but until then perhaps its a good idea to document this limitation and the requirement to manually deal with distribution in CTAS statements.
So this will not work as expected:
```scala
formattedDF
  .writeTo(fullTableName)
  .tableProperty("sort-order", "timestamp ASC NULLS FIRST")
  .tableProperty("write.distribution-mode", "range")
  .partitionedBy(days($"timestamp"))
  .create()
```
This might generate the following exception:
```
java.lang.IllegalStateException: Incoming records violate the writer assumption that records are clustered by spec and by partition within each spec. 
Either cluster the incoming records or switch to fanout writers.
```
Instead, distribution mode needs to be explicitly stated in create
```scala
  private def executeDDL(fullTablePath: String): DataFrame = {
    spark.sql(
      s"""
       |CREATE TABLE $fullTablePath (
       |  insert_timestamp TIMESTAMP,
       |  timestamp TIMESTAMP,
       |  role STRING,
       |  type STRING,
       |  file_key STRING,
       |  primary_dir STRING,
       |  secondary_dir STRING)
       |USING iceberg
       |PARTITIONED BY (days(timestamp))
       |TBLPROPERTIES (
       |  'format-version' = '2',
       |  'sort-order' = 'timestamp ASC NULLS FIRST',
       |  'write.distribution-mode' = 'range')
       |""".stripMargin
    )
    spark.sql(s"ALTER TABLE $fullTablePath WRITE ORDERED BY timestamp")
  }
```

**Comment by manuzhang** [comment]
Explicit distribution modes are required in DDL for CTAS/RTAS before Spark 3.5.0
