### ISSUE TITLE
Hive's performance for querying the Iceberg table is very poor.

### ISSUE THREAD

**Issue by BsoBird** [apache/iceberg#8901]
### Query engine

HIVE 3.1.3
ICEBERTG 1.3.1
SPARK 3.3.2

### Question

Hi Team.
      I recently was testing Hive query Iceberg table , I found that Hive query Iceberg table performance is very very poor . Almost impossible to use in the production environment . And Join conditions can not be pushed down to the Iceberg partition.
      I'm using the 1.3.1 Hive Runtime Jar from the Iceberg community.
      Currently I'm using Hive 3.1.3, Iceberg 1.3.1. 
      Now I'm very frustrated because the performance is so bad that I can't deliver to my customers. How can I solve this problem?
     Details:  https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1695050248606629
    I would be grateful if someone could guide me.

**Comment by lurnagao** [comment]
Hi, In Hive3，DML operations work only with MapReduce execution engine. Bad performance of the MR execution engine

**Comment by pvary** [comment]
You might want to try Hive 4.0.0-beta-1 which has plenty of related performance improvements

**Comment by pvary** [comment]
Also Iceberg is included out-of-the-box
