### ISSUE TITLE
Adding new columns (mergeSchema)

### ISSUE THREAD

**Issue by josgarmar14** [apache/iceberg#8908]
### Apache Iceberg version

1.0.0

### Query engine

Spark

### Please describe the bug 🐞

Facing issue when creating a new iceberg snapshot with new schema. 
**Code:**
`datasource_df.writeTo(f"job_catalog.{args['glue_db']}.{args['glue_iceberg_tablename']}").option("mergeSchema","true").overwritePartitions()`

**Error:** 
```
Cannot write incompatible dataset to table with schema:
table {
  1: index: optional string
  2: name: optional string
  3: description: optional string
  4: createdby: optional string
  5: new_column: optional string
}
Provided schema:
table {
  1: index: optional string
  5: new_column: optional string
  2: name: optional string
  3: description: optional string
  4: createdby: optional string
}
Problems:
* new_column is out of order, before createdby
```
I am using a Glue Job. Please provide insights on what is wrong. Thanks

**Comment by RussellSpitzer** [comment]
https://iceberg.apache.org/docs/latest/spark-writes/#schema-merge 
Please make sure you are setting all the appropriate properties

**Comment by josgarmar14** [comment]
I think everything is correct. Once the table is created I execute:

```
query = f"""ALTER TABLE job_catalog.{args['glue_db']}.{args['glue_iceberg_tablename']} SET TBLPROPERTIES ('write.spark.accept-any-schema'='true')"""
spark.sql(query)
```

**Comment by FabricioZGalvani** [comment]
Hello everyone,

After several attempts, I managed to solve the mergeSchema issue I was facing. The solution was to apply the following configuration. I suspect that the check-ordering is set to true by default, which can cause errors when columns are out of order. This happens even when following the documentation's instructions. Without applying the configuration below, I was receiving the 'column is out of order' error.

`--conf spark.sql.iceberg.check-ordering=false`

**Comment by josgarmar14** [comment]
Thank you @FabricioZGalvani !! It worked!!
