### ISSUE TITLE
Schema issue between Arrow and PyIceberg

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#8913]
### Apache Iceberg version

1.4.1 (latest release)

### Query engine

Other

### Please describe the bug 🐞

@Fokko we have a table in iceberg which has some of the column names begin with numbers. We are able to scan the table using PyIceberg. When try to bind it to Arrow or DuckDB we see its Arrow invalid FieldRef.Name no match for field.

What we observe in in Arrow the field name beginning with number like 2030_ABC is renamed to _2030_ABC  while the schema on iceberg is correct to define it as 2030_ABC which is in original data. Which trigger this issue.

Seem more of Arrow Bug happy to open it at Arrow project. Let me know

**Comment by Fokko** [comment]
Thanks @asheeshgarg for raising this. The PyIceberg repository has been moved to https://github.com/apache/iceberg-python. To get the quickest answers, it is best to raise the question over there.

We recently merged a PR that fixes this when reading Avro fields: https://github.com/apache/iceberg-python/pull/83

Can you try if this issue still persists on the main branch? You can easily install it using:

```sh
pip install "git+https://github.com/apache/iceberg-python.git#egg=pyiceberg[arrow]"
```

If you run into anything, could you also share the error? Thanks 🙌
