### ISSUE TITLE
Iceberg streaming using checkpoint does not ignore the stream-from-timestamp option

### ISSUE THREAD

**Issue by cccs-jc** [apache/iceberg#8921]
### Apache Iceberg version

1.3

### Query engine

Spark 3.4

### Please describe the bug 🐞

@singhpk234 I suspect there is a bug in the Spark readStream. I'm not 100% but we had strange issues where iceberg reported it could not find a snapshot retrieved from a checkpoint.

When we check in the table we do find the snapshot.

We suspected that maybe the cause was that we were setting `stream-from-timestamp` and using stored checkpoints.

We removed the `stream-from-timestamp` and we never saw the error again.

However, I always thought the code was going to use the `stream-from-timestamp` only if no stored checkpoints exists and if a stored checkpoint exits it would ignore `stream-from-timestamp`. But that does not seem like that's the case.

When I look at the unit test. I don't see one testing this specifically so I think it might be a bug?

What do you think.

**Comment by singhpk234** [comment]
I am not entirely sure why this would happen, i was under the impression that initialOffset() is used from checkpoint file and the way it's calculated is same as you stated above : 

https://github.com/apache/iceberg/blob/aa891acf20040d15e7ca59dc503adb3c1e4325b8/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java#L112


https://github.com/apache/iceberg/blob/aa891acf20040d15e7ca59dc503adb3c1e4325b8/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java#L458


Is there some caching that would be coming into picture for snapshot not found ? i think we have something like `SparkCachedTableCatalog` can you try making the ttl zero, just making a wild guess here., this might require deep-dive if we have a crisp steps of repro.

**Comment by cccs-jc** [comment]
ya seems pretty clear that it should be picking up the offset from the checkpoint when it exists.

could this come into the picture. There are two checks about the timestamp here
https://github.com/apache/iceberg/blob/aa891acf20040d15e7ca59dc503adb3c1e4325b8/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java#L326

and we do set rate limits on rows and on files.
public Offset latestOffset(Offset startOffset, ReadLimit limit) {

I have only tested with 1.3.

**Comment by singhpk234** [comment]
I am not entirely sure still how would this give us or being us to snapshot id not found as the offset returned here would be pointing to -1 snapshot id but as you suggested earlier you get a valid snapshot id which did exist in the table.
