### ISSUE TITLE
Slow RewriteManifests due to Validation of Manifest Entries

### ISSUE THREAD

**Issue by mirageyjd** [apache/iceberg#8932]
### Apache Iceberg version

0.13.1

### Query engine

Spark

### Please describe the bug 🐞

We ran `BaseRewriteManifestsSparkAction` action on a large table with 7k+ manifests in Spark, and it took more than an hour unexpectedly. The most time-consuming procedure is to validate that each manifest entry in added manifests has a snapshot id, which is not executed in a distributed manner. Without the validation, the entire action takes less than 2 minutes.

I wonder whether it is necessary to validate snapshot id of each manifest entry in manifests written by `BaseRewriteManifestsSparkAction`. It would be better such validation is optional and can be skipped in`BaseRewriteManifestsSparkAction`.

**Comment by RussellSpitzer** [comment]
Do you have a flame graph or some evidence of this? My gut would say that would be a trivial check

**Comment by mirageyjd** [comment]
Hi @RussellSpitzer. I ran an experiment on a table with 100K data files and collected the total cost of invoking [addManifest](https://github.com/apache/iceberg/blob/b56ec5ed421cb82d0c87c4fdd2a579db40f0e036/core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java#L141).

With `compatibility.snapshot-id-inheritance.enabled=true`, the cost is 2ms.

With `compatibility.snapshot-id-inheritance.enabled=false`, the total cost is 13315ms.

When snapshot id inheritance is disabled, all added manifests need to be validated, and then copied to a new file without changing the content. Copying manifests is expensive since it is executed in a single thread.

https://github.com/apache/iceberg/blob/b56ec5ed421cb82d0c87c4fdd2a579db40f0e036/core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java#L151-L157

**Comment by RussellSpitzer** [comment]
Ah yes, we have numerous threads on this
