### ISSUE TITLE
Long overflow when Iceberg reading INT96 timestamp column from Spark parquet table

### ISSUE THREAD

**Issue by manuzhang** [apache/iceberg#8949]
### Apache Iceberg version

1.4.1 (latest release)

### Query engine

Spark 3.1.1

### Please describe the bug 🐞

When a Spark parquet table is imported into Iceberg via `add_files` procedure, reading the timestamp column will fail with `Error while decoding: java.lang.ArithmeticException: long overflow`. All the overflow records have negative long values.

```sql
SELECT $timestamp_column FROM $spark_table limit 1000;
```

The underlying parquet file is written by Spark in legacy mode, and the timestamp column is of type INT96.

After digging into it, I find `isVectorDictEncoded` is false in the following codepath, and thus `TimestampMicroTzAccessor` is used instead of the expected `DictionaryTimestampInt96Accessor`.

```java
  public ArrowVectorAccessor<DecimalT, Utf8StringT, ArrayT, ChildVectorT> getVectorAccessor(
      VectorHolder holder) {
    Dictionary dictionary = holder.dictionary();
    boolean isVectorDictEncoded = holder.isDictionaryEncoded();
    FieldVector vector = holder.vector();
    if (isVectorDictEncoded) {
      ColumnDescriptor desc = holder.descriptor();
      PrimitiveType primitive = desc.getPrimitiveType();
      return getDictionaryVectorAccessor(dictionary, desc, vector, primitive);
    } else {
      return getPlainVectorAccessor(vector);
    }
  }
```

**Comment by manuzhang** [comment]
@yabola  @aokolnychyi @nastra please kindly advise.

**Comment by nastra** [comment]
That sounds like there's currently no support for INT96 for the non-vectorized code path available. #6962 only added support for vectorized reads. 

According to the description in #6962, vectorized reads for INT96 columns were available, so maybe this needs to be properly tested to see what exactly is missing

**Comment by manuzhang** [comment]
As per [parquet format encoding](https://github.com/apache/parquet-format/blob/master/Encodings.md#dictionary-encoding-plain_dictionary--2-and-rle_dictionary--8),
> If the dictionary grows too big, whether in size or number of distinct values, the encoding will fall back to the plain encoding.

I've verified the timestamp column has both encodings `PLAIN_DICTIONARY` and `PLAIN`. It looks this case is not handled currently.

**Comment by yabola** [comment]
@manuzhang Hi, Please correct me if I understand wrong, your error case is vectorized reading, and timestamp96 is not using dictionary. But I have dealt with this case actually. Please look at this test case. The code path you mentioned can actually be reached. 
https://github.com/apache/iceberg/blob/86bb1c09f5ffd2b6a7c72683cb86bb95f4c2b72f/spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java#L2121C2-L2161

**Comment by manuzhang** [comment]
@yabola  timestamp96 column is using dictionary with encodings `PLAIN_DICTIONARY` and `PLAIN`, which is not covered in your case.

**Comment by manuzhang** [comment]
If you check [Spark's VectorizedColumnReader](https://github.com/apache/spark/blob/master/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/VectorizedColumnReader.java#L307), encoding is checked for each page.

**Comment by yabola** [comment]
@manuzhang Can you provide a way for me to reproduce it locally?

**Comment by manuzhang** [comment]
@yabola It's hard to reproduce with simple data samples. I may send you a parquet file via slack or other channels if possible.
