### ISSUE TITLE
Does the Java API support primary keys for creating tables

### ISSUE THREAD

**Issue by FWLamb** [apache/iceberg#8950]
### Query engine

Flink 

### Question

Does the Java API support primary keys for creating tables?

I hope to use the Java API to create tables corresponding to the following SQL statements. How can I implement this?

CREATE TABLE `hive_catalog`.`default`.`sample` (
    id BIGINT COMMENT 'unique id',
    data STRING NOT NULL,
    PRIMARY KEY(`id`) NOT ENFORCED
) WITH ('format-version'='2');

**Comment by nastra** [comment]
@FWLamb you might want to take a look at https://tabular.io/blog/java-api-part-1/ to achieve that

**Comment by Zhangg7723** [comment]
primary key in flink is identifier fields in iceberg

**Comment by FWLamb** [comment]
> primary key in flink is identifier fields in iceberg

@Zhangg7723 Can you show me a simple example of creating a primary key table? Thank you.

**Comment by Zhangg7723** [comment]
Schema schema = new Schema(columns, identifierFieldIds)
