### ISSUE TITLE
Partitions metadata table returns inconsistent results size between 1.3.1 and 1.4.1

### ISSUE THREAD

**Issue by zhangbutao** [apache/iceberg#8951]
### Apache Iceberg version

1.4.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

- I write a UT in `org.apache.iceberg.spark.extensions.TestMetadataTables.java`, in 1.3.1, it returns one partition, but returns two partitions. I have found this problem caused by this commit https://github.com/apache/iceberg/pull/7581.  I am not sure which result is right.
Could you please give some thought? @dramaticlly @szehon-ho @ajantha-bhat 
```
  @Test
  public void testPartitionsTableDeleteDatafile() throws NoSuchTableException, ParseException {
    sql(
        "CREATE TABLE %s (id bigint, data string) "
            + "USING iceberg "
            + "PARTITIONED BY (data) "
            + "TBLPROPERTIES"
            + "('format-version'='2', 'write.delete.mode'='merge-on-read')",
        tableName);

    List<SimpleRecord> recordsA =
        Lists.newArrayList(new SimpleRecord(1, "a"), new SimpleRecord(2, "a"));
    spark
        .createDataset(recordsA, Encoders.bean(SimpleRecord.class))
        .coalesce(1)
        .writeTo(tableName)
        .append();

    List<SimpleRecord> recordsB =
        Lists.newArrayList(new SimpleRecord(1, "b"), new SimpleRecord(2, "b"));
    spark
        .createDataset(recordsB, Encoders.bean(SimpleRecord.class))
        .coalesce(1)
        .writeTo(tableName)
        .append();

    Table table = Spark3Util.loadIcebergTable(spark, tableName);

   // here delete a partition data 
    Expression finalExp = Expressions.in("data", "a");
    DeleteFiles delete = table.newDelete();
    delete.deleteFromRowFilter(finalExp);
    delete.commit();

    List<Row> actualPartitions =
        spark.sql("SELECT * FROM " + tableName + ".partitions ").collectAsList();
    Assert.assertEquals(
        "Partitions size returns one in 1.3.1, but returns two in 1.4.1",
        2,
        actualPartitions.size());
  }
```

**Comment by RussellSpitzer** [comment]
Are the files deleted correctly?

**Comment by zhangbutao** [comment]
@RussellSpitzer Yes, we implemented the hive **truncate partition** syntax by deleting the partition files. I also think it should have two partitions in which the truncated partition(data=a) is empty. 
Looks like we got a bug before 1.4.1? And https://github.com/apache/iceberg/pull/7581 fixed this issue accidentally?

**Comment by RussellSpitzer** [comment]
@zhangbutao 
Iceberg cannot have partitions without data files. Either there is a file which has a tuple for a partition or not. If there is no file entry then the partition cannot be empty. This is why I asked if you checked the "files" metadata table. If the Files metadata table has no tuples of {data: a} then there is not partition data = a.

Now you can have a partition with no rows, this would happen if you have a file for {data:a} but also have delete files which negate all rows in that partition. The partitions metadata table does not look at delete files.

**Comment by ajantha-bhat** [comment]
You are right about behaviour change. 
I think because of new stats addition like delete stats, we don't produce the effective stats for merge-on-read now. 
You can also check other fields of the stats. 
https://github.com/apache/iceberg/blob/a7828dbeb2ef644169f83de1288a4e00f6c6cdca/core/src/main/java/org/apache/iceberg/PartitionsTable.java#L106-L109

**Comment by zhangbutao** [comment]
I want to know if this is Iceberg bug or not?  Or this issue should be handled by engine/user side?
Hope to get a feedback. Thanks in advance.

**Comment by dramaticlly** [comment]
I'll take a look and try to reproduce the problem today

**Comment by dramaticlly** [comment]
Thank you @zhangbutao , looks like this was indeed introduced by #7581, where we changed to scan manifest entry instead of files. I am able to reproduce the problem using provided test above and will try to send a fix PR soon.
