### ISSUE TITLE
Does Spark 3.3 support Tagging in AWS?

### ISSUE THREAD

**Issue by DavidCGarcia89** [apache/iceberg#8952]
### Query engine

Spark 3.3
AWS Glue Catalog
Scala

### Question

I've been working with iceberg table in the glue table for a while and so far so good.

But now i'm trying to implement tags in the tables, but it seems I'm having issues with this.

![image](https://github.com/apache/iceberg/assets/20771695/e2829984-eb59-4791-8a12-e40e484ba1b4)

Do you now if is possible to make a new tag in AWS with spark 3.3?

**Comment by nastra** [comment]
@DavidCGarcia89 which Iceberg version are you using? This should work with Iceberg 1.2.0

**Comment by DavidCGarcia89** [comment]
@nastra Hello Nastra, I think that's the problem. It seems that AWS [only have compatibility with 1.0.0](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-format-iceberg.html)

Thank you
