### ISSUE TITLE
Duplicate file name in Iceberg's metadata

### ISSUE THREAD

**Issue by github-raphael-douyere** [apache/iceberg#8953]
### Apache Iceberg version

1.3.1

### Query engine

Spark

### Please describe the bug 🐞

While writing data to an Iceberg table using Spark Streaming 3.4.1 / Iceberg 1.3.1 / EMR 6.13 we do observe multiple entries in the table's metadata for a single file name (path + name).

```
+-------+-----------------------------------------------------------------------------------------------------------------+-----------+-------+---------+------------+------------------+
|content|file_path                                                                                                        |file_format|spec_id|partition|record_count|file_size_in_bytes|
+-------+-----------------------------------------------------------------------------------------------------------------+-----------+-------+---------+------------+------------------+
|0      |s3://<redacted>/table/data/time_hour=2023-10-12-16/00030-20515-7162e9b9-8d49-4d04-a828-6725e75da400-00001.parquet|PARQUET    |0      |{471424} |1176385     |52215529          |
|0      |s3://<redacted>/table/data/time_hour=2023-10-12-16/00030-20515-7162e9b9-8d49-4d04-a828-6725e75da400-00001.parquet|PARQUET    |0      |{471424} |1152053     |51648666          |
+-------+-----------------------------------------------------------------------------------------------------------------+-----------+-------+---------+------------+------------------+
```

This causes issues when reading data with Athena but it does not cause issues when reading with Spark (or opening parquet files directly with parquet-cli). 
We also see that the two occurrences of the file belong to different snapshots:
```
+------+-------------------+---------------+--------------------+-----------------------------------------------------------------------------------------------------------------+
|status|snapshot_id        |sequence_number|file_sequence_number|file_path                                                                                                        |
+------+-------------------+---------------+--------------------+-----------------------------------------------------------------------------------------------------------------+
|1     |5798287735063119103|605            |605                 |s3://<redacted>/table/data/time_hour=2023-10-12-16/00030-20515-7162e9b9-8d49-4d04-a828-6725e75da400-00001.parquet|
|1     |48372161143873894  |604            |604                 |s3://<redacted>/table/data/time_hour=2023-10-12-16/00030-20515-7162e9b9-8d49-4d04-a828-6725e75da400-00001.parquet|
+------+-------------------+---------------+--------------------+-----------------------------------------------------------------------------------------------------------------+
```

This seems very similar to https://github.com/apache/iceberg/issues/8427 and https://github.com/apache/iceberg/issues/8609.

**Comment by Fokko** [comment]
Slack conversation for reference that provides some more interesting details: https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1698676018510089

**Comment by github-raphael-douyere** [comment]
We enabled S3 versioning on the bucket and can see a file name being used 2 times by 2 distincts micro-batches. So it is not a case of task retry inside Spark. 

This issue leads to data loss as the original file is replaced and metadata corruption as there is a reference to a file that does not exists anymore.

**Comment by amogh-jahagirdar** [comment]
Looking at the code, this shouldn't happen but would need to check more deeply. We create an `OutputFileFactory` per writer,  https://github.com/apache/iceberg/blob/main/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java#L667. Every `OutputFileFactory` should generate a unique file name, https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java#L99 the relevant part here being the last part where it's a monotonically increasing file number.

The only way I can see this maybe happening is if there are somehow multiple OutputFileFactory's happening concurrently (thus multiple concurrent writers in the same task, which I don't think can happen. but that's the part i'll need to double check).

**Comment by amogh-jahagirdar** [comment]
It looks like Spark creates a data writer per task, so we should be good there https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/WriteToDataSourceV2Exec.scala#L436

**Comment by amogh-jahagirdar** [comment]
That being said, I do see there have been a few issues reported that are very similar as @github-raphael-douyere  pointed out. I'm looking into this

**Comment by github-raphael-douyere** [comment]
Not sure it helps but I need to mention that our streaming app is restarted a lot. Maybe all work fine when everything is kept in memory but on restart some elements are reused...

Maybe there is something with using the `queryId` as the `operationId` here https://github.com/apache/iceberg/blob/f7a7eb2c10cb4a9b6b3ea5bfdfc5d085be8b9c31/spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java#L659 .  Should the `operationId` also include the streaming query `runId`?

**Comment by github-raphael-douyere** [comment]
After looking a bit more, we think this https://github.com/apache/iceberg/pull/5214 introduced the bug.

**Comment by cccs-jory** [comment]
We observed the same behaviour in Spark 3.4 with Iceberg 1.3 as well.
Additionally we tested with Spark 3.5 and Iceberg 1.4 and have the same problem.

Our job stops and restarts a lot, so it is likely that the filename generated by the factory does not take enough into account to make the filename unique between Spark application runs.

Reading the tables with Spark seems ok but with Trino it breaks the client.

**Comment by Fokko** [comment]
> After looking a bit more, we think this https://github.com/apache/iceberg/pull/5214 introduced the bug.

@github-raphael-douyere Can you elaborate on why you think this is the case? The filename is still the same I would say.

@cccs-jory Thanks for testing across different versions.

I know that it is hard, but it would be great if we can create a test-case. It looks like the current behavior of the sink is not idempotent.

**Comment by amogh-jahagirdar** [comment]
Yeah +1 to what Fokko said, if we can get a minimal setup reproduction test case of the problem that would be helpful. 

>After looking a bit more, we think this https://github.com/apache/iceberg/pull/5214 introduced the bug.
I'm not sure about that, https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java#L99 it's not just the query ID that's in the file name. The file name also includes task, partition, operation and the file count. That should ensure uniqueness.

 I wonder if it's possible during restart that somehow all of these end up being the same.

**Comment by github-raphael-douyere** [comment]
@Fokko  I don't know how to have a simple and reproductible setup. We had the issue at a rate of ~10 files per week with an app producing hundreds of files per hour. 

@amogh-jahagirdar  And yes I know that the file name is not only the query id. But I think the other elements can definitively repeat (`taskId` and `partitionId`). What I'm not sure of is the `fileCount` part. I think it is kept in memory but resets when the app is restarted (ie: not part of the state). So my point is: with a UUID this can't happen (barring the UUID collision) as whatever collisions on the other part of the filename are handled by a uniq part. 
Another fix could be to keep the `operationId` but add an UUID as well. This would extend the file names a little bit but is probably fine to avoid data loss issues.

**Comment by github-raphael-douyere** [comment]
As an additional info, we did change our app to write inside a `foreachBatch` instead of using Spark Streaming direct writer and we don't see the issue anymore (over more than a week of ingestion). This is not great as `foreachBatch` does not offer the same guarantees compared to direct write but it is a way to temporarily avoid the issue. And this shows that the issue is tied to streaming writer.

**Comment by amogh-jahagirdar** [comment]
Ok I actually looked at the history of these changes now https://github.com/apache/iceberg/pull/5214 was never merged but followed by https://github.com/apache/iceberg/pull/6569/files which actually applied the change and would've been released in 1.2.0.

The goal for including the query ID looks to be to identify which spark job actually performed the write; previously there would've been a new UUID per write, and we would've avoided files stepping on each other. 

Let me try and get a reproducible example,  (we would want one anyways for verifying whatever fix we do actually works) ideally we can get the best of both worlds. I think to do that some combination of the query ID + the hostname + the thread ID would be truly unique and enable better debugging (at the cost of a really long filename :) ).

**Comment by amogh-jahagirdar** [comment]
I also want to verify why fileCount doesn't really cover the uniqueness right now, the only other way would be if it's in a different thread (and both threads just end up having a file count of 1, as in the example)

**Comment by hguercan** [comment]
Hello we are seeing the same issue now with newer versions also. 

We are using iceberg 1.9.2 and stream-writing via kafka connect and doing maintenance (data-compaction, manifest-rewrite, orphan-deletion etc.) via spark 3.5.2 and also iceberg 1.9.2 with partial-commit enabled. 

How can we solve the issue?
