### ISSUE TITLE
flink1.13.2+iceberg0.13.0+hive-metastore3.0.0+minio（S3) Forbidden (Service: Amazon S3; Status Code: 403

### ISSUE THREAD

**Issue by ramdas-jagtap** [apache/iceberg#8968]
### Apache Iceberg version

0.13.0

### Query engine

Flink

### Please describe the bug 🐞

I have setup of [flink1.13.2+iceberg0.13.0+hive-metastore3.0.0+minio（S3). How are specifying s3 storage properties while creating tables?

CREATE TABLE test_table (
id DECIMAL(20, 0) NOT NULL,
name STRING,
address STRING,
phone_number STRING,
email STRING,
PRIMARY KEY (id) NOT ENFORCED
) WITH (
'connector'='iceberg',
'catalog-type'='hive',
'catalog-name'='hive_RJ05',
'catalog-database'='hive_db05',
'uri'='thrift://hive-metastore:9083',
'fs.s3a.path-style'='true',
'fs.s3a.endpoint'='http://minio:9000',
'fs.s3a.access.key'='xxxxx',
'fs.s3a.secret.key'='xxxxxxx',
'fs.s3a.aws.region'='us-east-1',
'warehouse'='s3a://s3 bucket path'
);

I have added below files in flink/lib
flink-csv-1.13.2.jar flink-shaded-hadoop-2-uber-2.7.5-10.0.jar flink-table-blink_2.11-1.13.2.jar log4j-1.2-api-2.12.1.jar
flink-dist_2.11-1.13.2.jar flink-shaded-zookeeper-3.4.14.jar flink-table_2.11-1.13.2.jar log4j-api-2.12.1.jar
flink-json-1.13.2.jar flink-sql-connector-hive-3.1.2_2.11-1.13.2.jar hive-metastore-3.1.3.jar log4j-core-2.12.1.jar
flink-s3-fs-hadoop-1.13.2.jar flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar iceberg-flink-1.13-runtime-0.13.0-SNAPSHOT.jar log4j-slf4j-impl-2.12.1.jar

I am getting below aws error
[ERROR] Could not execute SQL statement. Reason:
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: XXXXXXX; S3 Extended Request ID: xyz==; Proxy: null)

**Comment by ragin0ff** [comment]
does it have solutions ?
