### ISSUE TITLE
Support adding an additional `opType` column when creating a table

### ISSUE THREAD

**Issue by klion26** [apache/iceberg#8973]
### Feature Request / Improvement

Hi community, I want to discuss a feature described as the title here, please let me know what do you think about this, thanks.

One of our customers had reached to us with this feature, the data pipeline here is `[datasource] --> [flinkcdc] --> [iceberg]`, he want to support add an additional `opType` column when creating Iceberg Table(when config is enabled), the `opType` represents the latest update action(`INSERT`, `UPDATE`, `DELETE` etc), and when executing the `DELETE` action, we do not **delete** the row in iceberg table, but only to record the `opType`(the other column but `opType` will no change), the other action（`INSERT`, `UPDATE`) remains the same as now. Let me show some example for this

```
+------+-------------------+---------------+
| id |        data|           opType | 
+------+-------------------+---------------+
+------+-------------------+---------------+
```

after insert a row the table changes to 
```
+------+-------------------+---------------+
| id |        data|           opType | 
+------+-------------------+---------------+
| 1 |        "abcdefg" |           "INSERT" | 
+------+-------------------+---------------+
```

after an execution about `delete` (DELETE FROM table  where id = 1), the table changes to

> The columns but `opType` remains as same with before
```
+------+-------------------+---------------+
| id |        data|           opType | 
+------+-------------------+---------------+
| 1 |        "abcdefg" |           "DELETE" | 
+------+-------------------+---------------+
``` 

The reason why need this feature is that:
1. use for row-level traceback
2. can be used to do audit analysis (such as want to know what data has been deleted)

No sure if this feature makes sense to Iceberg.

PS: Although turning on this feature may consume more storage, this is business-related and we can provide options for users which is disabled by default.

### Query engine

Flink

**Comment by nastra** [comment]
You might want to take a look at https://iceberg.apache.org/docs/latest/spark-procedures/#change-data-capture as that might provide what you're looking for

**Comment by klion26** [comment]
@nastra thanks for the reply. Yes, it looks the same, but seems the `change-data-capture` feature was a view created on a exist iceberg table?

our customer want some iceberg table like `cow` behavior, our customer want some iceberg table like `cow` behavior, the table contains the whole raw data which contains the `deleted data`(labled with additional column `opType`)

Do you think add such feature in iceberg table is a valid feature? thanks
