### ISSUE TITLE
Support MOR CDC view

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#8975]
### Feature Request / Improvement

Currently Iceberg table that is being upserted by Flink can not produce CDC view.
```
Error: Delete files are currently not supported in changelog scans
```
This is due to all below reasons together:
- Flink upsert only support v2 Iceberg table.
- Flink upsert only use MOR and can not use COW.
- Iceberg CDC does not support MOR.

It will be great to support this feature.

### Query engine

Spark

**Comment by puchengy** [comment]
@aokolnychyi @flyrain Hello, do you know how much effort this will take to implement? Thanks!

**Comment by coolderli** [comment]
@flyrain @puchengy any update for supporting this? Is there any plan for supporting Flink streaming read? Thanks.

**Comment by Biman54** [comment]
The changelog view should support deletion vectors (MOR) starting from v3, as Row Lineage tracking simplifies CDC. @RussellSpitzer , please correct me if I’m mistaken.
