### ISSUE TITLE
Data duplicate after the partition is modified

### ISSUE THREAD

**Issue by jiamin13579** [apache/iceberg#8979]
### Query engine

Spark

### Question

When we talk about writing data to Iceberg, it is common practice to first issue an eqDelete record and then write a data record. However, after we made changes by converting from a non-partitioned table to a partitioned table, we noticed that the previous data is still being queried, resulting in two sets of data - one from the old non-partitioned folder and another from the new partitioned folder.

**Comment by nastra** [comment]
@jiamin13579 you might want to take a look at https://iceberg.apache.org/docs/latest/evolution/#partition-evolution.

> Partition evolution is a metadata operation and does not eagerly rewrite files

So what you most likely would want to do in your case is to rewrite data files after you changed the partitioning
