### ISSUE TITLE
hive integration iceberg related problems

### ISSUE THREAD

**Issue by dragon-feng** [apache/iceberg#8993]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

hadoop3.1.2 hive3.1.2  tez0.9.2  iceberg1.4.2   Table creation and data insertion are OK, but the data cannot be queried,
hadoop3.1.1 hive3.1.0  tez0.9.1  iceberg1.4.2  The data table creation and data insertion were normal, but an error occurred in the query: Failed to deserialize object

**Comment by nastra** [comment]
@dragon-feng can you please provide the full stack trace and your catalog configuration? Without this it's quite difficult to tell what went wrong. Also please share the exact command you're executing when the error happens.

**Comment by dragon-feng** [comment]
Both version clusters use the same command, The following commands are used:
Use iceberg_db;
list jars;

add jar hdfs://mycluster/tmp/ftp/checkpoint/iceberg-hive-runtime-1.4.2.jar;
add jar hdfs://mycluster/tmp/ftp/checkpoint/libfb303-0.9.3.jar;

set iceberg.engine.hive.enabled=true;
set hive.vectorized.execution.enabled=false;

create table iceberg_db.test_xu_iceberg_hive_01(
id int ,
name string,
age int)
partitioned by (dt string)
stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
LOCATION 'hdfs://mycluster/warehouse/tablespace/managed/hive/iceberg_db.db/test_xu_iceberg_hive_01'
tblproperties ('iceberg.catalog'='location_based_table');

insert into iceberg_db.test_xu_iceberg_hive_01 values (777777,'zs',18,'2023-09-05');

select * from iceberg_db.test_xu_iceberg_hive_01;

**Comment by dragon-feng** [comment]
Commands containing the catalog configuration:

Use iceberg_db;
list jars;

add jar hdfs://mycluster/tmp/ftp/checkpoint/iceberg-hive-runtime-1.4.2.jar;
add jar hdfs://mycluster/tmp/ftp/checkpoint/libfb303-0.9.3.jar;

set iceberg.engine.hive.enabled=true;
set hive.vectorized.execution.enabled=false;

set iceberg.catalog.hive_catalog.type=hive;
set iceberg.catalog.hive_catalog.uri=thrift://mycluster.node01.com:9083;
set iceberg.catalog.hive_catalog.clients=5;
set iceberg.catalog.hive_catalog.warehouse=hdfs://mycluster/warehouse/tablespace/managed/hive/iceberg_db.db;

create table iceberg_db.test_xu_iceberg_hive_01(
id int ,
name string,
age int)
partitioned by (dt string)
stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
LOCATION 'hdfs://mycluster/warehouse/tablespace/managed/hive/iceberg_db.db/test_xu_iceberg_hive_01'
tblproperties ('iceberg.catalog'='hive_catalog');

insert into iceberg_db.test_xu_iceberg_hive_01 values (777777,'zs',18,'2023-09-05');

select * from iceberg_db.test_xu_iceberg_hive_01;

**Comment by pvary** [comment]
@dragon-feng: Could you please check which execution engine you are using?

My guess is, that you are using `set hive.execution.engine=tez`. And it is working for reads, but not supported for writes. The execution of the insert is finished, but the data files are not added to the Iceberg table.

I would suggest to try out Hive 4.0.0, as it has out-of-the-box support for Iceberg tables.

You can find the supported features / engines here: https://iceberg.apache.org/docs/latest/hive/

> 
> Iceberg compatibility with Hive 2.x and Hive 3.1.2/3 supports the following features:
> 
> - Creating a table
> - Dropping a table
> - Reading a table
> - Inserting into a table (INSERT INTO)
>
> DML operations work only with MapReduce execution engine.

**Comment by dragon-feng** [comment]
@pvary :In contrast, the tez engine I use supports writing, but not reading.

**Comment by dragon-feng** [comment]
@pvary However, writing data does have problems. The data directory is generated normally, and the data file is also generated normally, but the metadata directory only has the matedata.json file and version-tint.text file

**Comment by pvary** [comment]
> @pvary However, writing data does have problems. The data directory is generated normally, and the data file is also generated normally, but the metadata directory only has the matedata.json file and version-tint.text file

So if I understand correctly this confirms, that the issues is with the write, and not the read.
Am I right?

**Comment by pvary** [comment]
You have 2 options:
- Hive 3 - Use MR engine for write, and Tez engine for read
- Hive 4
