### ISSUE TITLE
[Feature Request] Implement `equals` for `RESTMessage`

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg#9003]
### Feature Request / Improvement

In java, `equals` by default compares object identity. Implementing `equals` methods by comparing contents would be quite useful for testing.

### Query engine

Other

**Comment by liurenjie1024** [comment]
I would be happy to take this if there is no objection.

**Comment by Fokko** [comment]
`RESTMessage` is an interface that does not carry any contents. Are there any particular messages that you would like to compare?

**Comment by liurenjie1024** [comment]
> `RESTMessage` is an interface that does not carry any contents. Are there any particular messages that you would like to compare?

Oh, sorry, I mean all the concrete implementations, such as `ConfigResponse`.

**Comment by Fokko** [comment]
@liurenjie1024 No problem and I think that makes sense to be able to check those for equality.

**Comment by liurenjie1024** [comment]
Cool, I will take this.

**Comment by liurenjie1024** [comment]
cc @Fokko Please help to assign it to me.
