### ISSUE TITLE
Spark does not support time datatype

### ISSUE THREAD

**Issue by tundraraj** [apache/iceberg#9006]
### Feature Request / Improvement

Spark does not support time per https://iceberg.apache.org/docs/latest/spark-writes/#iceberg-type-to-spark-type.
see thread https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1699395544460329

### Query engine

Spark

**Comment by Fokko** [comment]
Ah, I didn't realize that this isn't supported by Spark, see https://github.com/apache/spark/pull/25678#issuecomment-531585556 I'm sorry, but I think we can close this one. In the Github thread a suggestion is given to use a datetime, and keep the time part always 1970-01-01. If you feel strongly about this, I would suggest opening an issue on the Spark repository.
