### ISSUE TITLE
Merge into second commit when with no changes

### ISSUE THREAD

**Issue by andreacfm** [apache/iceberg#9024]
### Apache Iceberg version

1.4.1

### Query engine

Spark

### Please describe the bug 🐞

When executing a “merge into” query the source data is committed even if not matched by any of query clause.

Consider the following existing table:

```
id | name
 1 | Andrea
 2 | Luigi  
 3 | John
 4 | Steve
```
And a a temp view like:
```
id | name
 3 | John
 4 | Steve
```
The MERGE INTO query looks  like following:
```
MERGE INTO default.people p
USING (SELECT * from view) v
ON p.id = v.id
WHEN MATCHED AND p.name != v.name THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *
```
The query should not do nothing but the data coming from the temp view is still committed to file. The commit is skipped if `write.merge.mode=merge-on-read` but it should not happen also when on `cow` mode.

**Comment by Fokko** [comment]
I was able to reproduce this locally:

![image](https://github.com/apache/iceberg/assets/1134248/74d876cb-9b89-403f-abd9-8a36e8b6d12b)

@aokolnychyi WDYT?
