### ISSUE TITLE
Hive: Improve performance of HiveCatalog#listTables

### ISSUE THREAD

**Issue by link3280** [apache/iceberg#9031]
### Feature Request / Improvement

Currently, HiveCatalog gets the list of Iceberg tables in 2 steps:
1. list all table names
2. get all table metas with these names and filter them by the table property `table_type`

In fact, we could push down the table property filter to the HMS, and get the Iceberg tables with one request.

### Query engine

None

**Comment by pvary** [comment]
Please check #2722.
We need to fix Hive issues for this, as mentioned there.
I am here to review both Hive and Iceberg fixes

**Comment by link3280** [comment]
@pvary Thanks for the pointer! Then I'll close this issue in favor of the other.
