### ISSUE TITLE
Metadata tables should include data for WAP snapshots when currentSnapshot is null

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#905]
Appropriate metadata tables should report data for WAP snapshots when currentSnapshot is null.

See [here](https://github.com/apache/incubator-iceberg/pull/894#discussion_r405877714) for more details.

**Comment by aokolnychyi** [comment]
One specific case is `all_data_files` and `all_manifest_files`.

**Comment by leo-lao** [comment]
I wonder why this issue is still open after one year? 
can I pick this up and try my first contribution here?
@aokolnychyi

**Comment by nssalian** [comment]
@aokolnychyi can I pick this up if no one is working on it already?

**Comment by rdblue** [comment]
Sure, anyone is welcome to open a PR for this.

**Comment by nssalian** [comment]
Thanks @rdblue . I'll post back if I have questions.

**Comment by rdblue** [comment]
Looks correct to me. Thanks for finding that, @nssalian! I'll close this.
