### ISSUE TITLE
Memory overflow when Iceberg compact files

### ISSUE THREAD

**Issue by leo-livis** [apache/iceberg#9059]
### Feature Request / Improvement

When I compact files using Java APIs, Spark local mode, or Flink local mode, Iceberg memory overflows

### Query engine

None

**Comment by nastra** [comment]
@leo-livis can you provide a stack trace that shows the exact problem? Also how much memory does the JVM have that runs compaction?

**Comment by leo-livis** [comment]
> @leo-livis can you provide a stack trace that shows the exact problem? Also how much memory does the JVM have that runs compaction?

The application has 4GB of memory. The data volume of the table is 10 million pieces, with 10000 pieces of data per datafile file.

![1699951005976](https://github.com/apache/iceberg/assets/16472885/1da253c7-64ab-456c-866b-d33cb89b9d2b)
![1699951227921](https://github.com/apache/iceberg/assets/16472885/8ca3d96f-7068-4b01-bd58-ef45ccf4b961)

**Comment by nastra** [comment]
This doesn't look like a memory issue. It rather seems that the channel was closed as indicated by the `ClosedChannelException`

**Comment by leo-livis** [comment]
> This doesn't look like a memory issue. It rather seems that the channel was closed as indicated by the `ClosedChannelException`

Thank you. This issue seems to be due to a memory overflow causing the channel to be closed. I am using the Java API to merge files. If one thread is used, there will be no memory overflow. If you use Flink or Spark, you will also have similar problems

![1699952279002](https://github.com/apache/iceberg/assets/16472885/ac597c98-eb4f-41f8-b41c-bd018260fac5)

**Comment by nastra** [comment]
Have you tried increasing the Heap size? Additionally, what you can do is limit on which data compaction is executed using a `where` as described in https://iceberg.apache.org/docs/latest/spark-procedures/#rewrite_data_files

**Comment by leo-livis** [comment]
I'll give it a try, thank you

**Comment by leo-livis** [comment]
> Have you tried increasing the Heap size? Additionally, what you can do is limit on which data compaction is executed using a `where` as described in https://iceberg.apache.org/docs/latest/spark-procedures/#rewrite_data_files

I'll give it a try, thank you
