### ISSUE TITLE
Iceberg: Partition-Level Tagging Support

### ISSUE THREAD

**Issue by Am1rr3zA** [apache/iceberg#9060]
### Feature Request / Improvement

I want to be able to support Tagging at partition level.

Let's consider a straightforward fact table that requires restating at specific times: one day and seven days after its initial creation.
I aim to label my partitions as '0-day,' '1-day,' and '7-day' to facilitate easy access to historical data whenever needed.

To show by example let's say this is the table:
```
CREATE TABLE IF NOT EXISTS my_iceberg_fact_table(
        id INT,
        name STRING,
        sale DOUBLE,
        region INT,
        my_date DATE
      ) USING iceberg
      PARTITIONED BY (region, my_date)
```

Some data get inserted in `0-day` Time
```
INSERT INTO my_iceberg_fact_table VALUES
  (1, 'John', 10.5, 1, date '2023-11-12'),
  (2, 'Jane', 20.0, 2, date '2023-11-12'),
  (3, 'Jim', 15.0, 1, date '2023-11-12'),
  (4, 'Jack', 12.3, 3, date '2023-11-12')
```

And after 1 day it get updated
```
CREATE OR REPLACE TEMPORARY VIEW updated_data AS
    SELECT
        1 AS id,
        'John' AS name,
        200.0 AS sale,
        1 AS region,
        DATE('2023-11-12') AS my_date
    UNION ALL
    SELECT
        2 AS id,
        'Alice' AS name,
        100 AS sale,
        2 AS region,
        DATE('2023-11-12') AS my_date


MERGE INTO my_iceberg_fact_table t
      USING updated_data s
      ON t.id = s.id AND t.region = s.region AND t.my_date = s.my_date
    WHEN MATCHED THEN UPDATE SET
    t.sale = s.sale
```
I want to be able to query the latest partition and go back in time like:
```
SELECT * FROM my_iceberg_fact_table where region=1 and my_date= '2023-11-14' AS OF 0-day;
or
SELECT * FROM my_iceberg_fact_table where region=1 and my_date= '2023-11-14' AS OF 1-day;
```

**Note**: For each distinct partition, I intend to apply the same set of tags. While my understanding is that the table-level tag is unique, at the partition level, I aim to designate the '0-day' tag for each specific combination of 'region' and 'my_date'

Something like this should be possible:
```
SELECT * FROM my_iceberg_fact_table where region=1 and my_date= '2023-11-14' AS OF 0-day;
SELECT * FROM my_iceberg_fact_table where region=1 and my_date= '2023-11-14' AS OF 1-day;
SELECT * FROM my_iceberg_fact_table where region=1 and my_date= '2023-11-14' AS OF 7-day;
SELECT * FROM my_iceberg_fact_table where region=2 and my_date= '2023-11-14' AS OF 0-day;
SELECT * FROM my_iceberg_fact_table where region=1 and my_date= '2023-11-15' AS OF 0-day;
...
```

### Query engine

Spark

**Comment by nastra** [comment]
@Am1rr3zA I'm not sure I fully understand the problem you're trying to solve. Can't this be solved using a Tag at the table-level as described in https://iceberg.apache.org/docs/latest/branching?

**Comment by Am1rr3zA** [comment]
@nastra I might be wrong but what Apache iceberg support right now is tagging at Table level and tag is unique
what I want is tagging at partition level and tag not to be unique .

If my description is confusing let me know (which part need more clarification) I will try to re-write it in a way that makes more sense.
