### ISSUE TITLE
when hdfs router restart, task failed with read data files " xx parquet is not a parquet file (length is  too low :0) " or manifest "java.io.EOFException: Unexpected EOF with 4 bytes remaining to read avro"

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#9071]
### Apache Iceberg version

1.2.1

### Query engine

None

### Please describe the bug 🐞

recently, we found that when hdfs router has stuck or restart, we will meet some files are empty, for example, we have a flink task write iceberg every one minute, router has restart during writing and client has java.net.SocketTimeoutException or "A failover has occurred since the start of call create" such exception, but task doesn't failed, then i read this commit with error " xx parquet is not a parquet file (length is  too low :0) ". 
i list the file and the length is zero, and i look hdfs audit log, i find this file was created two times

**Comment by link3280** [comment]
We get the same problem here with Iceberg 1.3.0.

The bug affects not only data files but also metadata.json and .avro files. The files created twice could be corrupted (1-2% chance in my case).
