### ISSUE TITLE
Create JUnit5-version of TableTestBase

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9073]
### Feature Request / Improvement

`TableTestBase` is using JUnit4 imports/mechanisms and is used as a base class for a lot of tests. In order to be able to migrate tests to JUnit5 that depend on this base class, we need a version of that class written in JUnit5.
During the migration process from JUnit4 to JUnit5 both versions of that class would co-exist.

### Query engine

None

related issue: https://github.com/apache/iceberg/issues/7160

**Comment by lisirrx** [comment]
While #9122  is waiting for review, I want to start working on package `iceberg-core`, which makes me better understanding about the project and doing more contribution. Would you like to assign this issue to me?
I found that you raised this issue about the `TableTestBase` class , so maybe I can start from here.

I have read the discussion in #9120 which encoutered a similar situation. So in my understanding, an independent version of `TableTestBase` should be created with Junit5. I'm not sure about it's name, maybe `TestBase` is good enough.

After that, how the rest tests in `iceberg-core` be updated? inheriting the new `TableTestBase` or duplicating a new version?

**Comment by nastra** [comment]
@lisirrx yes we first need to have a JUnit5-version of `TableTestBase` (`TestBase` should be fine as a name) before we can convert any other tests that depend on this class.

To convert the existing tests to the new `TestBase` would mean to change the base class being used and switch to JUnit5 imports and AssertJ-style assertions.

**Comment by lisirrx** [comment]
> @lisirrx yes we first need to have a JUnit5-version of `TableTestBase` (`TestBase` should be fine as a name) before we can convert any other tests that depend on this class.
> 
> To convert the existing tests to the new `TestBase` would mean to change the base class being used and switch to JUnit5 imports and AssertJ-style assertions.

ok, I'll work on this. Thanks for the detail information.
