### ISSUE TITLE
Create JUnit5-version of SparkCatalogTestBase

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9076]
### Feature Request / Improvement

`SparkCatalogTestBase` is using JUnit4 imports/mechanisms and is used as a base class for a lot of tests. In order to be able to migrate tests to JUnit5 that depend on this base class, we need a version of that class written in JUnit5.
During the migration process from JUnit4 to JUnit5 both versions of that class would co-exist.

### Query engine

Spark

**Comment by tomtongue** [comment]
@nastra If no one is working on this, may I create a PR for this?

**Comment by nastra** [comment]
Nobody is working on this, so feel free to comment on such an issue to signal interest and open a PR. Thanks
