### ISSUE TITLE
Create JUnit5-version of FlinkTestBase

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9078]
### Feature Request / Improvement

`FlinkTestBase` is using JUnit4 imports/mechanisms and is used as a base class for a lot of tests. In order to be able to migrate tests to JUnit5 that depend on this base class, we need a version of that class written in JUnit5.
During the migration process from JUnit4 to JUnit5 both versions of that class would co-exist.

### Query engine

Flink

**Comment by cgpoh** [comment]
Hi @nastra , creating a separate `FlinkTestBaseJU5` class good enough?

**Comment by nastra** [comment]
@cgpoh yes that's the goal of this iissue

**Comment by cgpoh** [comment]
@nastra thanks! I am interested in working on this issue.
