### ISSUE TITLE
iceberg-aws: Switch tests to JUnit5 + AssertJ-style assertions

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9080]
### Feature Request / Improvement

The goal is to switch all imports to JUni5 imports and to use AssertJ-style assertions

### Query engine

None

**Comment by ndrluis** [comment]
Hello @nastra, I've started the migration process, and I'm uncertain about how to run the integration tests. Is there any documentation on how to configure it to execute successfully?

**Comment by nastra** [comment]
@amogh-jahagirdar do you have some details about how to run those AWS integration tests?

**Comment by tomtongue** [comment]
@nastra If no one is assigned with this project, could you assign this with me? I'll work on this.

**Comment by tomtongue** [comment]
@nastra Thanks for the review. I believe all the tests in `iceberg-aws` were migrated to JUnit5. Maybe we can close this issue.

**Comment by nastra** [comment]
fixed by #10086
