### ISSUE TITLE
iceberg-aliyun: Switch tests to JUnit5 + AssertJ-style assertions

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9081]
### Feature Request / Improvement

The goal is to switch all imports to JUni5 imports and to use AssertJ-style assertions

### Query engine

None

**Comment by lisirrx** [comment]
@nastra Hi, I have read the discussion in #7160 and read some packages which are already changed to JUnit5. I want to have a try.

**Comment by nastra** [comment]
@lisirrx great, feel free to go ahead and open a PR once you have something and tag me for a review
