### ISSUE TITLE
iceberg-data: Switch tests to JUnit5 + AssertJ-style assertions

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9082]
### Feature Request / Improvement

The goal is to switch all imports to JUni5 imports and to use AssertJ-style assertions

This depends on #9073 

### Query engine

None

**Comment by igoradulian** [comment]
Hi @nastra, can I be assigned to this issue?

**Comment by nastra** [comment]
https://github.com/apache/iceberg/pull/9793

**Comment by nastra** [comment]
fixed by https://github.com/apache/iceberg/pull/10657
