### ISSUE TITLE
iceberg-parquet: Switch tests to JUnit5 + AssertJ-style assertions

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9084]
### Feature Request / Improvement

The goal is to switch all imports to JUni5 imports and to use AssertJ-style assertions

### Query engine

None

**Comment by GianlucaPrincipini** [comment]
Hi @nastra; I would be glad to give it a try! I've already taken a look at #7160

**Comment by nastra** [comment]
this has been fixed by #8056
