### ISSUE TITLE
iceberg-core: Switch tests to JUnit5 + AssertJ-style assertions

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9085]
### Feature Request / Improvement

The goal is to switch all imports to JUni5 imports and to use AssertJ-style assertions

depends on #9073

### Query engine

None

**Comment by seyeh** [comment]
@nastra Could I be assigned this issue? Thank you!

**Comment by tomtongue** [comment]
@nastra Is anyone working on this? May I help the migration to JUnit5?

**Comment by tomtongue** [comment]
@nastra Thanks, sure it can avoid the duplicate efforts. Will list the test files here.

**Comment by tomtongue** [comment]
I'm working on the following currently (will update)

## Current Progress
Read:
- [ ] `MetadataTableScanTestBase` (extends `TableTestBase`) (WIP)
  - [ ] `TestMetadataTableScans`
  - [ ] `TestMetadataTableScansWithPartitionEvolution`
- [ ] `TestEntriesMetadataTable`
- [ ] `TestBatchScans`
- [ ] `TestIncrementalDataTableScan`
- [ ] `TestFindFiles`

**Comment by nk1506** [comment]
@tomtongue , I was working with [TestOverwrite](https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/TestOverwrite.java) and to move this to jUnit5 I had to change [TableTestBase](https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/TableTestBase.java), which ended up changing all the dependent class. With this [PR](https://github.com/apache/iceberg/pull/9862) I will plan to change only 
`@ExtendWith(ParameterizedTestExtension.class)`  and related issues. It seems it's not allowing me to keep mix of jUnit4 and jUnit5. For the above classes I wont make any changes related to assertions.

**Comment by tomtongue** [comment]
@nk1506 thanks for sharing the situation. In your commit, there are some classes that I already migrated to JUnit 5, the classes are listed above. And the `TableTestBase` shouldn't be migrated to JUnit 5, instead of the `TableTestBase`, we should use `TestBase` which was created in https://github.com/apache/iceberg/pull/9217 for this migration.

And for Spark 3.3 and Spark 3.4, should we migrate to JUnit 5? @nastra Could you have a look at @nk1506's commit?

**Comment by nastra** [comment]
Yes we should be using `TestBase` as the new base class for JUnit5 tests that previously extended `TableTestBase`. That allows us to do the migration in small chunks rather than having to change all subclasses of `TableTestBase` in a single PR.

> And for Spark 3.3 and Spark 3.4, should we migrate to JUnit 5?

We do this for Flink, but for Spark the situation is slightly different and the amount of tests is quite a lot. It would be nice to migrate at least Spark 3.4 so that backporting features and tests from Spark 3.5 to Spark 3.4 is easier. It took us already quite long to migrate Spark 3.5 tests. @aokolnychyi @RussellSpitzer any thoughts on also migrating Spark 3.4 tests to JUnit5?

**Comment by nk1506** [comment]
@tomtongue , I have reverted changed for the above files. As recommended by @nastra I will work with `TestBase` for the related files.

**Comment by tomtongue** [comment]
@nk1506 Sure thanks so much. It would be great if you list the classes you're working on in this issue, for avoiding the conflicts.

**Comment by tomtongue** [comment]
Additionally created a PR for the migration of the files related to "snapshot". Here's the progress:

Snapshots:
- [x] TestSnapshot
- [ ] TestSnapshotJson
- [ ] TestSnapshotLoading
- [ ] TestSnapshotSelection
- [ ] TestSnapshotSummary

The following classes are for Iceberg procedures:
- [ ] TestSnapshotManager
- [ ] TestSnapshotRefParser

**Comment by tomtongue** [comment]
Created a PR for the migration of the files related to "metadata". Here's the progress:

- [x] TableMetadataParserCodecTest
- [x] TableMetadataParserTest
- [ ] TestMetadataUpdateParser
- [ ] TestMetadataTableFilters
- [ ] TestTableMetadata
- [ ] TestTableMetadataSerialization

**Comment by seyeh** [comment]
@tomtongue After you make changes, do you run `./gradlew build`? If so, how long does this process take on your computer. 

Also since you've been working this ticket, do you want to just take ownership of this ticket or would you like help with the rest of the tests?

**Comment by tomtongue** [comment]
> After you make changes, do you run ./gradlew build? If so, how long does this process take on your computer.

basically run `./gradlew test` for specific classes and packages. I don't remember what it takes exactly, but It takes less than 1 hour.

If it's no problem with you, I can take the ownership because I'm migrating most of classes.

**Comment by seyeh** [comment]
@tomtongue Makes sense, I figured you'd probably build that test/classes specific package instead of all of them since `./gradlew build` took forever on my computer. 

Sure you can take ownership.

**Comment by tomtongue** [comment]
@nastra If possible, could you assign this issue with me? I'll have the owenership for this core migration.

**Comment by tomtongue** [comment]
Created a PR for the migration of the files related to "manifest". Currently completed and working on the following classes:
- [x] `TestManifestCaching.java`
- [x] `TestManifestCleanup.java`
- [x] `TestManifestEncryption.java`
- [x] `TestManifestListVersions.java`
- [x] `TestManifestReader.java` (already uses JUnit5)
- [ ] `TestManifestReaderStats.java`
- [ ] `TestManifestWriter.java`
- [ ] `TestManifestWriterVersions.java`

**Comment by nastra** [comment]
I think the only task left for this is to convert subclasses of `TableTestBase` to JUnit5 and then remove `TableTestBase`

**Comment by tomtongue** [comment]
Yes, the subclasses of `TableTestBase` are related to several packages like Flink, Spark etc. I will create PRs.
