### ISSUE TITLE
Metrics for Manifest file caching

### ISSUE THREAD

**Issue by agrawalreetika** [apache/iceberg#9093]
### Query engine

Presto

### Question

I was also exploring the Manifest file caching feature which was introduced in Iceberg https://github.com/apache/iceberg/pull/4518 for the Presto execution engine. As I checked Cache Metrics are getting computed and recorded in the Iceberg library for the same, but didn’t find a way to access these metrics on the execution engine side. To validate the cache usage we would require at least cache metrics access for this feature. Could you please let me know if is there any way to access metrics?

**Comment by gaborkaszab** [comment]
Hi @agrawalreetika 
Just FYI, I have a PR that exposes the manifest content cache stats: https://github.com/apache/iceberg/pull/13560
