### ISSUE TITLE
hive iceberg

### ISSUE THREAD

**Issue by luxl6** [apache/iceberg#9094]
### Query engine

hive

### Question

Hive creates an iceberg table and inserts data, but the data is in a temporary table and cannot be found in the created table. How does the data need to be migrated

**Comment by pvary** [comment]
I would guess that you are using Hive 3.1.x, and using Tez execution engine.

Either use Hive 4.0.0 (with the embedded Iceberg), or use Hive 3.1.x with MR for write, and Tez for read.
See the supported configurations on https://iceberg.apache.org/docs/latest/hive/#feature-support

**Comment by pvary** [comment]
In this case you should ask your vendor. A year ago, CDH did not support Iceberg tables.
