### ISSUE TITLE
Question about "Column ID" in Parquet Sepc

### ISSUE THREAD

**Issue by mapleFU** [apache/iceberg#9099]
### Query engine

Not engine specific. It's about the spec.

### Question

Parquet spec [1] mentioned a "Column ID". It says that:

> Column IDs are required.

However, I just found that in spec, we only having a "field ID" here. Are they the same thing?

And from the implemention, I think the meaning of here is also "field ID", am I right?

1. https://iceberg.apache.org/spec/#parquet

**Comment by mapleFU** [comment]
Also, in ORC parquet, I found 

```
column id = [iceberg.id](http://iceberg.id/)
```

Seems they're all equal to field id?

**Comment by emkornfield** [comment]
Yes column IDs are meant to be [field ids](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L459)

**Comment by mapleFU** [comment]
Thanks!

**Comment by wgtmac** [comment]
@bitsondatadev @Fokko It seems that we need to clear the confusion here.

**Comment by emkornfield** [comment]
I can make a PR to clarify
