### ISSUE TITLE
why should we use file.createOrOverwrite to create a datafile or manifest file?

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#9100]
### Feature Request / Improvement

Recently i find that we use overwrite mode to create file for flink or spark,  for example: 
` switch (format) {
        case AVRO:
          return Avro.write(outputFile)
              .createWriterFunc(ignore -> new FlinkAvroWriter(flinkSchema))
              .setAll(props)
              .schema(schema)
              .metricsConfig(metricsConfig)
              .overwrite()
              .build();

        case ORC:
          return ORC.write(outputFile)
              .createWriterFunc(
                  (iSchema, typDesc) -> FlinkOrcWriter.buildWriter(flinkSchema, iSchema))
              .setAll(props)
              .metricsConfig(metricsConfig)
              .schema(schema)
              .overwrite()
              .build();

        case PARQUET:
          return Parquet.write(outputFile)
              .createWriterFunc(msgType -> FlinkParquetWriters.buildWriter(flinkSchema, msgType))
              .setAll(props)
              .metricsConfig(metricsConfig)
              .schema(schema)
              .overwrite()
              .build();`
there  is a situation , when hdfs create requests has stuck or socket timeout, then hdfsclient will try to another node to create, and in this part, we successfully create, write and commit, but the previous request which has stuck is alive, and create again, and we use overwrite mode, then file will be overwrote as empty.
so why should we use  overwrite mode?

### Query engine

Flink

**Comment by singhpk234** [comment]
There was a fix for this in pipeline to fail fast when we have conflicting file names in the pr : 
- https://github.com/apache/iceberg/pull/6839

One logical explanation atleast applicable for HadoopFileIO was that it skips the ifExists check : https://github.com/apache/iceberg/pull/6818#discussion_r1105189453

**Comment by chenwyi2** [comment]
i think this is not iceberg problem, i will close this issue
