### ISSUE TITLE
write data with a specific tag

### ISSUE THREAD

**Issue by Jake-00** [apache/iceberg#9111]
### Feature Request / Improvement

Background: Referring to documentation, I can't find out a way to write data into table along with a specific tag. Nowadays, the common workflow is to list all snapshots-id for locating the exact snapshot. Here is one simple scenario that user just want to add a specific tag like 'first-version' for first time writing. And then user can read the table with tag 'first-version' without checking snapshot id and tagging command.

Idea: To design one handy command below will be convenient, looking for forward to better solution: )
```sql
SET TAG `first-version` 
INSERT INTO demo.nyc.taxis
VALUES (1, 1000371, 1.8, 15.32, 'N'), (2, 1000372, 2.5, 22.15, 'N'), (2, 1000373, 0.9, 9.01, 'N'), (1, 1000374, 8.4, 42.13, 'Y');
```

### Query engine

Spark

**Comment by nastra** [comment]
> Referring to documentation, I can't find out a way to write data into table along with a specific tag

This isn't supported and I don't think there's much value in supporting something like this. Also note that a **tag** is an immutable snapshot (which can be used for retaining important historical snapshots), meaning that you can't write new data to that snapshot and expect the **tag** to move along with your changes (that's the purpose of a **branch**).
Your suggestion however would imply that you first create a **tag** and then write data to it, which is not what a **tag** supports

**Comment by Jake-00** [comment]
> Your suggestion however would imply that you first create a tag and then write data to it, which is not what a tag supports.
My suggestion may not be clear enough. Indeed I want to create tag as soon as data written, so `tag` creating is after writing.

**Comment by nastra** [comment]
@Jake-00 you can already create a Tag right after writing, but it takes an additional SQL call: https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--create-tag

That being said, I don't think we will support writing and creating a tag with a single SQL cmd as that seems rather confusing and wouldn't be used that often. It is better to be explicit and separate writing data and creating a tag.

I'll go ahead and close this one, feel free to re-open if you feel strongly about this feature.
