### ISSUE TITLE
PARSE_SYNTAX_ERROR was encountered for 'ALTER TABLE ... CREATE BRANCH ...

### ISSUE THREAD

**Issue by jackskmok** [apache/iceberg#9116]
I am trying to testing the create branch feature with the table with AWS Glue catalog , but hit the error as title. Here is the message:

>>> spark.sql("alter table iceberg.athena_data create branch 'testing'");
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/apache-spark/3.5.0/libexec/python/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/apache-spark/3.5.0/libexec/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/opt/homebrew/Cellar/apache-spark/3.5.0/libexec/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'create'.(line 1, pos 32)

== SQL ==
alter table iceberg.athena_data create branch 'testing'
--------------------------------^^^

Spark Version is 3.5

Execution Command : 

export AWS_PROFILE=lfdba
spark-sql --packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.1,org.apache.iceberg:iceberg-aws-bundle:1.4.1 \
    --conf spark.sql.defaultCatalog=my_catalog \
    --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
    --conf spark.sql.catalog.my_catalog.warehouse=s3://testingbucket/lficeberg/ \
    --conf spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
    --conf spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO \

Reference : https://iceberg.apache.org/docs/latest/getting-started/

**Comment by nastra** [comment]
@jackskmok it appears that you're missing `--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions`

**Comment by jackskmok** [comment]
Thanks @nastra
