### ISSUE TITLE
The "Status" paragraph in the readme seems very outdated

### ISSUE THREAD

**Issue by ronkorving** [apache/iceberg#9127]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

Looking at the ReadMe in the root of this repository, one would be mistaken for thinking we're living in Table v1 times.

**Quote start:**

Iceberg is under active development at the Apache Software Foundation.

The core Java library that tracks table snapshots and metadata is complete, but still evolving. Current work is focused on adding row-level deletes and upserts, and integration work with new engines like Flink and Hive.

The [Iceberg format specification](https://iceberg.apache.org/spec) is being actively updated and is open for comment. Until the specification is complete and released, it carries no compatibility guarantees. The spec is currently evolving as the Java reference implementation changes.

[Java API javadocs](https://iceberg.apache.org/javadoc/latest) are available for the main.

**Quote end**

That last sentence seems incomplete. But more importantly, I think the information provided is, today at least, no longer correct. I've been told there _are_ compatibility guarantees, and what's being worked on today is probably no longer row-level deletes and upserts.

I would like to suggest that an update, or perhaps a slimming down of the text, is overdue.

**Comment by Fokko** [comment]
Hey @ronkorving Thanks for raising this. That's very true, the status page seems to be very outdated.

The V1, and V2 specs are out there, and work is being done on the V3 spec (more type promotions, nanosecond support, and more). Are you interested in trimming down the section, and updating it where needed?

**Comment by Fokko** [comment]
Yes, I think that makes a lot of sense. @bitsondatadev is also working on updating the [roadmap](https://iceberg.apache.org/roadmap/), it might be a good idea to link to that so we have one single place where people can see what's going on 👍

**Comment by bitsondatadev** [comment]
@ronkorving Let me know if you'd like to raise the PR, or I can do it as well. For now pointing to the roadmap page will be the best. Eventually, I'd like there to be something less static that exists directly in GitHub for this. A main project board or possibly a wiki with links to individual projects.

**Comment by ronkorving** [comment]
PR is ready for review ^
