### ISSUE TITLE
BaseLockManager.scheduler doesn't shutdown when closing

### ISSUE THREAD

**Issue by gabrywu** [apache/iceberg#9142]
### Feature Request / Improvement

BaseLockManager use a static field scheduler, whose type is ScheduledExecutorService, however, it doesn't shutdown when closing. 
Can we close it since its corresponding LockManager closed?

### Query engine

None

**Comment by nastra** [comment]
that's a good idea @gabrywu, could you please open a PR to fix this?

**Comment by gabrywu** [comment]
@nastra please help to review this PR
