### ISSUE TITLE
Does iceberg flink streaming read support recover from last ckp?

### ISSUE THREAD

**Issue by qianzhen0** [apache/iceberg#9175]
### Query engine

Flink

### Question

I am reading from iceberg and write to a sink using flink. The sink supports exactly once semantic based on flink ckp. So i am wondering if iceberg will recover from last ckp if job fails because of some unstable issues, e.g., network or machine error.

I checked the iceberg flink doc, https://iceberg.apache.org/docs/latest/flink-configuration/ 
The streaming mode supports `connector.iceberg.starting-strategy`. But i guess it is a option for starting instead of in recover? 

Thanks!

**Comment by qianzhen0** [comment]
I found code `StreamingMonitorFunction`. So with `startSnapshotId` specified, it should support EOS, right?

**Comment by pvary** [comment]
I am not sure about the FlinkSource, but IcebergSource stores the state, an it should be abe to recover from that when restarted.

The configuration possibilities you have mentioned are independent of that. They configure, how the source starts when the job is started the first time (without state)

**Comment by qianzhen0** [comment]
@pvary  thanks for the input!

by saying `IcebergSource`, do you mean iceberg flink connector? or spark engine? 

So, if i run `insert into sink select * from iceberg_table` in streaming mode (with ckp interval configured), it should recover reading from last ckp.

**Comment by pvary** [comment]
`IcebergSource` is using the new Flink Source API - this is the newer one
`FlinkSource` is using the old Flink SourceFunction API - this will be removed (I plan to deprecate it in the new Iceberg release)

When using the table API the `table.exec.iceberg.use-flip27-source` config option could be used to chose between the 2 versions. See: https://iceberg.apache.org/docs/1.3.1/flink-queries/#flip-27-source-for-sql
