### ISSUE TITLE
Remove `RuntimeIOException` usage

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#9208]
### Feature Request / Improvement

The `RuntimeIOException` has been deprecated, but is still being used in many places. Would be good to remove this.

Would be a good idea to maybe remove this per module, since it is used quite a bit throughout the codebase, and this will lead to smaller PRs that are easier to review and merge.

### Query engine

None

**Comment by ShockleysxX** [comment]
@Fokko, i want to have a try, plz assign to me, thanks~

**Comment by ajantha-bhat** [comment]
Let me know, If you guys want to remove `RuntimeIOException`. I can just rebase these two PRs

**Comment by ajantha-bhat** [comment]
@danielcweeks, @Fokko, @nastra: 
I have revived the PRs and it is ready for review. 

https://github.com/apache/iceberg/pull/6887
https://github.com/apache/iceberg/pull/4776

**Comment by ajantha-bhat** [comment]
Fixed by https://github.com/apache/iceberg/pull/5640
