### ISSUE TITLE
iceberg-mr: Switch class level parameterized tests to Junit5

### ISSUE THREAD

**Issue by lschetanrao** [apache/iceberg#9269]
### Feature Request / Improvement

Once https://github.com/apache/iceberg/pull/9161 is merged, we should migrate class level parameterized tests to Junit5. 

### Query engine

None

**Comment by lisirrx** [comment]
hi @nastra , could you please assign this task to me?

**Comment by nastra** [comment]
fixed by https://github.com/apache/iceberg/pull/9711
