### ISSUE TITLE
Create Branches / TAGS between 2 snapshots 

### ISSUE THREAD

**Issue by fanaticjo** [apache/iceberg#9280]
### Feature Request / Improvement

Is there a way where we can create a branch / TAG based on 2 snapshot ids or only latest data 

We have a use case where we write monthly generated report to a iceberg table , but for every month we want to tag / branch the data for audit purposes . 

Currently branch / tag creates the data from that snapshot to first snapshots . 

### Query engine

Spark

**Comment by nastra** [comment]
closing as this is a duplicate of https://github.com/apache/iceberg/issues/9281
