### ISSUE TITLE
Iceberg table querying and joining issues

### ISSUE THREAD

**Issue by MummadiT** [apache/iceberg#9287]
we have integrated AWS Glue with Iceberg.
I was able to create an iceberg table and insert the data into the table. 
but i have couple of issues listed below.

1. whenever I try to pull the data from non-iceberg table i.e., hive table in the glue editor, I am not able to do so. It is trying to pull hive table as iceberg table that is it is adding glue catalog to the table name. 
2. We have aws athena integrated and i was able to query the data from my iceberg table but whenever i try to join the iceberg table -with non iceberg table or join 2 iceberg tables it gives me error saying **Queries of this type not supported**

**Comment by amogh-jahagirdar** [comment]
This seems like an AWS Athena issue, could you report the issue to them?
