### ISSUE TITLE
hive4 MapReduce query execution engine support

### ISSUE THREAD

**Issue by wfy-belief** [apache/iceberg#9297]
### Feature Request / Improvement

now, when i use hive:4.0.0-beta-2-SNAPSHOT i can write data in a iceberg table，but can't query data，so i read the doc of https://iceberg.apache.org/docs/latest/hive/#select，find it is not support。
I think it is very good to do it.
Thanks!
![image](https://github.com/apache/iceberg/assets/58450591/df58d4a5-aab5-46f4-a2ae-61b4152a726c)

### Query engine

MapReduce

**Comment by pvary** [comment]
@wfy-belief: AFAIK the MR engine is deprecated in Hive, but I would suggest to ask this question on the Hive dev/user mailing list, as the Hive team works on the Hive 4.0.0 integration.

**Comment by wfy-belief** [comment]
@pvary Thanks!
