### ISSUE TITLE
Java calls API error

### ISSUE THREAD

**Issue by smileyboy2019** [apache/iceberg#9339]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

// 1. 构建记录
GenericRecord record = GenericRecord.create(schema);
ImmutableList.Builder<GenericRecord> builder = ImmutableList.builder();
builder.add(ImmutableMap.of("id", 1, "name", "chen", "birth", "2020-03-08"));
builder.add(ImmutableMap.of("id", 2, "name", "yuan", "birth", "2021-03-09"));
builder.add(ImmutableMap.of("id", 3, "name", "jie", "birth", "2023-03-10"));
builder.add(ImmutableMap.of("id", 4, "name", "ma", "birth", "2023-03-11"));
ImmutableList<GenericRecord> records = builder.build();
 
// 2. 将记录写入parquet文件
String filepath = table.location() + "/" + UUID.randomUUID().toString();
OutputFile file = table.io().newOutputFile(filepath);
DataWriter<GenericRecord> dataWriter =
    Parquet.writeData(file)
    .schema(schema)
    .createWriterFunc(GenericParquetWriter::buildWriter)
    .overwrite()
    .withSpec(PartitionSpec.unpartitioned())
    .build();
try {
    for (GenericRecord record : builder.build()) {
        dataWriter.write(record);
    }
} finally {
    dataWriter.close();
}
 
// 3. 将文件写入table中
DataFile dataFile = dataWriter.toDataFile();
table.newAppend().appendFile(dataFile).commit();
  Parquet class not found
GenericParquetWriter class not found

Is it a version issue

If the version is correct, how can I insert data in Java

**Comment by nastra** [comment]
@smileyboy2019 could you please provide the full stack trace and the exact Iceberg library versions you're using?

**Comment by smileyboy2019** [comment]
![image](https://github.com/apache/iceberg/assets/59221294/99063335-ef96-45e1-82a6-f2a605d40093)
Version 1.4.2, using Java API developed by iceberg+minio

**Comment by nastra** [comment]
`GenericParquetWriter` is in `iceberg-data`, so you would have to add that dependency.
