### ISSUE TITLE
How does Iceberg support writing data to local paths, network disks, interfaces, and other storage media

### ISSUE THREAD

**Issue by smileyboy2019** [apache/iceberg#9378]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

My data is stored locally or on Baidu Cloud. Can I directly write the data to a file and then read the data directly.

**Comment by manuzhang** [comment]
It depends on your catalog `io-impl`. Take https://iceberg.apache.org/docs/latest/aws/#spark as an example.

**Comment by amogh-jahagirdar** [comment]
Yeah what @manuzhang said. Effectively, interactions with object stores and any other storage mediums can be done via `FileIO` which is a simple interface for reading/writing/deleting data. Different implementations can interact with different storage mediums. For example `S3FileIO` talks to S3, GCSFileIO talks to GCS etc. You can step through the integrations and see if anyone suits your needs. 

If it doesn't you can always implement your own and plug it in to your catalog! So in your case your custom implementation can do your local + Baidu handling according to your desires. Let me know if that makes sense.

https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/io/FileIO.java#L32

I'm going to close this for now, feel free to reopen in case you still have any doubts.
