### ISSUE TITLE
Can iceberg support truncating table?

### ISSUE THREAD

**Issue by coolderli** [apache/iceberg#9387]
### Query engine

truncate table

### Question

Can iceberg support truncating a table? I have some users who want to clear all data in the iceberg table. If I use `delete from` to drop the data, the iceberg should keep at least one snapshot when executing expirie snapshot. Then the data in the latest snapshot will be kept. 
My question is should we support truncating a table or expiring all snapshots. Why not?

**Comment by coolderli** [comment]
By the way, I don't want to drop the table. Because this table is just for testing, I can reuse it later without recreating it.

**Comment by jhchee** [comment]
You could remove table entry from your catalog and create new table within the same directory. This should preserve all your files.

**Comment by coolderli** [comment]
I found that `truncate table ` is already supported after spark 3.3. `truncate table` twice can resolve my problem.
