### ISSUE TITLE
Review Table/View refresh Operation for InMemoryCatalog 

### ISSUE THREAD

**Issue by nk1506** [apache/iceberg#9434]
### Feature Request / Improvement

`InMemoryCatalog` validate and [disable](https://github.com/apache/iceberg/blob/2101ac2e5528049688d4ce3ea2b4db861ea3c78b/core/src/main/java/org/apache/iceberg/inmemory/InMemoryCatalog.java#L380) metadata location refresh if required. 

Instead of this can we throw exception and catch at caller ?
 Ref : https://github.com/apache/iceberg/pull/8907/files#r1441973958

### Query engine

None

**Comment by nastra** [comment]
@nk1506 I'm not sure I fully understand what the scope of this issue is. I think what the `InMemoryCatalog` currently does is correct. Please re-open if you think this needs to be addressed in the `InMemoryCatalog`

**Comment by pvary** [comment]
#9012 fixed the issue. Thanks @ajantha-bhat for pointing out!
