### ISSUE TITLE
AWS: Support setting description for Glue table

### ISSUE THREAD

**Issue by lkokhreidze** [apache/iceberg#9462]
### Feature Request / Improvement

Iceberg Glue integration supports setting database description as per https://github.com/apache/iceberg/pull/3467
It would be also beneficial to support setting description on a table level.

### Query engine

None

**Comment by lkokhreidze** [comment]
Seems like a small patch and happy to take this on myself if it makes sense.

**Comment by singhpk234** [comment]
sounds good, please feel free to submit a change. happy to review it !

**Comment by lkokhreidze** [comment]
Thanks @singhpk234. Created the PR https://github.com/apache/iceberg/pull/9530
