### ISSUE TITLE
Getting history of Iceberg table in BigQuery

### ISSUE THREAD

**Issue by PiotrBB** [apache/iceberg#9463]
### Query engine

BigQuery

### Question

Hi,
I just created few Iceberg tables in BigQuery using this guide: https://www.youtube.com/watch?v=IQR9gJuLXbQ and this code: https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/blob/main/sql-scripts/rideshare_lakehouse_enriched/sp_iceberg_spark_transformation.sql
Tables are there, I can see the rows but I wonder, how to I get table's history, including snapshot id's and timestamps? In Athena, that was possible by invoking `select * from table$history`.
Also, how do I query table for a given snapshot id and timestamp? 
Thanks in advance.

**Comment by amogh-jahagirdar** [comment]
This is a vendor specific issue, I recommend reaching out to GCP BigQuery support with this request. Closing.
