### ISSUE TITLE
[HadoopCatalog]: [HadoopTableOperations]: Commit flow, renameToFinal does not actually check if lock acquired

### ISSUE THREAD

**Issue by N-o-Z** [apache/iceberg#9485]
### Apache Iceberg version

1.4.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

The last part of the commit flow, requires writing the new metadata version file which uses the renameToFinal method.
In this method there's a use of the lock manager to ensure no 2 committers write the same metadata version file.
However, when trying to acquire lock, there's no check if the lock was actually acquired:
```Java
    private void renameToFinal(FileSystem fs, Path src, Path dst, int nextVersion) {
        try {
            this.lockManager.acquire(dst.toString(), src.toString());
            if (fs.exists(dst)) {
                throw new CommitFailedException("Version %d already exists: %s", new Object[]{nextVersion, dst});
            }
            ...
```

In the LockManager interface, acquire documentation states:
```
Try to acquire a lock
Params: entityId – ID of the entity to lock 
              ownerId – ID of the owner if the lock
Returns:
if the lock for the entity is acquired by the owner
```

I'm fairly new to the Iceberg ecosystem, so if I'm misunderstanding something in the code I would greatly appreciate an explanation.

**Comment by amogh-jahagirdar** [comment]
@N-o-Z Great catch, I think you're right. We should throw an exception if lock acquisition failed. If you're free to put up a PR, feel free , I'm happy to review it.

**Comment by N-o-Z** [comment]
Thanks @amogh-jahagirdar, I'll create a PR today

**Comment by BsoBird** [comment]
@N-o-Z 
Hello, I am working on a fix related to HadoopTableOperations. I have a question for you.
```
      if (!lockManager.acquire(dst.toString(), src.toString())) {
        throw new CommitFailedException(
            "Failed to acquire lock on file: %s with owner: %s", dst, src);
      }
```
Why are you using dst.toString() and src.toString() as lock-key.

**Comment by N-o-Z** [comment]
> @N-o-Z Hello, I am working on a fix related to HadoopTableOperations. I would like to ask you a question.
> 
> ```
>       if (!lockManager.acquire(dst.toString(), src.toString())) {
>         throw new CommitFailedException(
>             "Failed to acquire lock on file: %s with owner: %s", dst, src);
>       }
> ```
> 
> Why are you using dst.toString() and src.toString() as lock-key.

I'm not sure I fully understand the question
The LockManager I used to ensure no two writers are writing the same metadata version file, therefore the entitiy id will be the destionation file path (i.e. the metadata version file to write) and the owner Id used will be the name of the temoporary file used to write the metadata version content.
