### ISSUE TITLE
[doc] Word `Gague ` spelled incorrectly in  https://iceberg.apache.org/docs/latest/flink-writes/#metrics

### ISSUE THREAD

**Issue by Aireed** [apache/iceberg#9527]
### Apache Iceberg version

1.4.3 (latest release)

### Query engine

None

### Please describe the bug 🐞

`Gague`  should be  `Gauge`

**Comment by amogh-jahagirdar** [comment]
Thanks @Aireed ! PRs are welcome, feel free and we can review

**Comment by Aireed** [comment]
> Thanks @Aireed ! PRs are welcome, feel free to make the change in the docs and we can review

OK, i will submit a PR to fix it.
