### ISSUE TITLE
How do I debug iceberg source code using idea

### ISSUE THREAD

**Issue by lpy148145** [apache/iceberg#9549]
### Query engine

spark

### Question

How do I debug iceberg source code using idea

**Comment by ajantha-bhat** [comment]
Locally you can execute the unit testcases and add a break points to the classes (observe logs to find the class names). 

Or if you have Iceberg running as a process with some query engines, you can attach the remote debugger from IDE and debug it. 

Same as  any other java project. 

Project instructions can be found at https://iceberg.apache.org/contribute/#building-the-project-locally

**Comment by lpy148145** [comment]
If I want to run the iceberg task locally, I can use those dependency substitutions in addition to adding iceberg-spark- Run-time -3.2_2.12

**Comment by lpy148145** [comment]
Is iceberg- Spark-Run-time 3.2_2.12 compiled by iceberg project? Why can't I find the corresponding package after compiling
