### ISSUE TITLE
 gc.enabled property is set to false by default for Apache Iceberg table created in Nessie Catalog

### ISSUE THREAD

**Issue by Ashwin07** [apache/iceberg#9562]
I have created the below Apache Iceberg table in Nessie.

Nessie version: 0.58.1
Spark version: 3.3
Apache Iceberg version: 1.3.0

Table Name: gold_layer.CORP_DRM_PKG.PHYS_GEO_HIER
Location: s3a://gold-layer-bkt/nessie_poc/metadata/CORP_DRM_PKG/PHYS_GEO_HIER_4d18ae58-9ffd-42e2-a18e-602950842f22
Table Properties   [current-snapshot-id=7015122799097017057,format=iceberg/parquet,format-version=1,**gc.enabled=false**,nessie.commit.id=b446261a6ad9d65e76edf6ab0bfc7b3147305b9f2e0d095751b2b92c9ad1a39d,option.write.spark.accept-any-schema=true,write.spark.accept-any-schema=true]

gc.enabled property is set to false by default, the alter statements or create statements does not seem to overwrite it,

### Alter statement:
spark.sql("""ALTER TABLE gold_layer.CORP_DRM_PKG.PHYS_GEO_HIER SET TBLPROPERTIES ('gc.enabled' = 'true')""")

### Create statement:
spark.sql("""CREATE TABLE gold_layer.CORP_DRM_PKG.PHYS_GEO_HIER ( BU_ID DECIMAL(15, 0), EFF_STRT_DTTM TIMESTAMP NOT NULL, RGN_CODE STRING, RGN_DESC STRING, RGN_ABBR STRING, SUB_RGN_CODE STRING, SUB_RGN_DESC STRING, SUB_RGN_ABBR STRING, AREA_CODE STRING, AREA_DESC STRING, AREA_ABBR STRING, CTRY_CODE STRING, CTRY_DESC STRING, CTRY_ABBR STRING, BU_DESC STRING, ISO_CTRY_CODE_3 STRING, ISO_CTRY_CODE_2 STRING, EFF_END_DTTM TIMESTAMP, DW_CURR_FLAG STRING, EXTRC_DTTM TIMESTAMP ) USING iceberg  TBLPROPERTIES ('gc.enabled' = 'true')""")

I would like to test the feature of expire snapshots for this Iceberg table, but the fact that gc.enabled flag set to false, does not allow snapshot expiration with the below exception,
 org.apache.iceberg.exceptions.ValidationException: Cannot expire snapshots: GC is disabled (deleting files may corrupt other tables)

**Comment by nastra** [comment]
@Ashwin07 this is in purpose as Nessie doesn't support Iceberg's GC operations due to the way Nessie manages metadata. You'd rather want to use https://projectnessie.org/features/management/#nessie-gc-tool for that

**Comment by clintf1982** [comment]
@ajantha-bhat Thanks a lot:)

**Comment by yunlou11** [comment]
> Yes, Nessie GC tool will clean up the expired or unreferenced data files as well along with Iceberg metadata files.
Thank you.
```
select * from nessie.robot.ods_robot_data.snapshots; 
```
lists hundreds of snapshots, but 
```text
java -jar /root/helm/nessie/nessie-gc-0.99.0.jar gc --cutoff reference-name-regex=PT1H --jdbc-url jdbc:postgresql: ...
```
delete 0 files like below:
```text
...
... 0 files considered expired, 5290 files considered live, 0 files are newer than max-file-modification-time ...
```
even after execute 
```sql
CALL nessie.system.rewrite_data_files(table => 'nessie.robot.ods_robot_data', options => map('target-file-size-bytes','536870912'))
CALL nessie.system.rewrite_manifests('nessie.robot.ods_robot_data')
```
delete 0 files forever.
How expire iceberg snapshots with nessie-gc ? Thank you.
