### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#9588]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

Seeing if there is anything we can do to improve performance:

![profile](https://github.com/apache/iceberg/assets/1134248/e562ebe9-6471-487e-87db-b7f730abfdcd)

**Comment by liurenjie1024** [comment]
Seems a lot of time are spent on decompression.

**Comment by Fokko** [comment]
s3fs:
![output](https://github.com/apache/iceberg/assets/1134248/4332cd61-d280-48b5-88de-30574fd728fc)

PyArrow:
![output](https://github.com/apache/iceberg/assets/1134248/bb6a73bd-cd63-4dcd-b319-5ba180335883)

Also, the PyArrow import is very slow :(
