### ISSUE TITLE
Core: complete task JSON serialization for other types (like data task, manifest task)

### ISSUE THREAD

**Issue by stevenzwu** [apache/iceberg#9597]
### Feature Request / Improvement

Right now, `FileScanTaskParser` JSON serializer only handles `BaseFileScanTask` for data files (see issue #1698 ). There are other `FileScanTask` impl classes that are not covered: `StaticDataTask`, `AllManifestsTable$ManifestListReadTask`, `BaseEntriesTable$ManifestReadTask`, `BaseFilesTable$ManifestReadTask`. This was discovered while I was trying to Flink  FLIP-27 `IcebergSource` with metadata tables unit tests.

I propose that we add a `type` (or `impl`) filed to the JSON format that captures the FQCN of the `FileScanTask` implementation class. Fortunately, with JSON format, this can be a backward compatible change. if the `type` field is not present, the implementation class is defaulted to `BaseFileScanTask`.

We can also incrementally add the missing implementations. The next one to tackle should be the `StaticDataTask`.

cc @nastra @rdblue @aokolnychyi @pvary 

### Query engine

None

**Comment by stevenzwu** [comment]
Regarding `StaticDataTask`, we can make this constructor package private.
```
  private StaticDataTask(
      InputFile metadata, Schema tableSchema, Schema projectedSchema, StructLike[] rows) {
       ...
  }
```

The main question is how to serialize the `StructLike` row. We can use Java serialization to convert the row to `byte[]`. We would need base64 encoding to convert the byte array to a string before adding it to JSON array. Base64 will increase the serialized bytes by 33%. Not sure if we have better option here.

**Comment by nastra** [comment]
I think we could make this similar to how it's done for a `MetricsReport`. We have a `ReportMetricsRequestParser` that reads a `report-type` field and then delegates to the respective parser for the particular type as can be seen [here](https://github.com/apache/iceberg/blob/49fb12e66e865c0b0e1dcabb68cd9ebf1e9989b1/core/src/main/java/org/apache/iceberg/rest/requests/ReportMetricsRequestParser.java#L54-L60).

In this case we could have a `task-type` at the JSON level, which could be an enum in Java (similar to [ReportType](https://github.com/apache/iceberg/blob/49fb12e66e865c0b0e1dcabb68cd9ebf1e9989b1/core/src/main/java/org/apache/iceberg/rest/requests/ReportMetricsRequest.java#L32)). I'm not sure using FQCN is necessarily good, because classes can be moved around and their names could change.

I haven't looked what challeges we'd have with serializing all subclasses of `FileScanTask`, but in terms of handling different task types the proposed approach could be used.

**Comment by stevenzwu** [comment]
@nastra thanks for the comments!

Regarding the JSON format, we are on the same page of adding a new `task-type` or `type` field. 

Are you suggesting adding a new API  `FileScanTask#type()`? I can see the enum type works well for `ReportMetricsRequest`. But I don't know if is most natural with FileScanTask's existing class hierarchy. In my mind, class name (FQCN) is essentially the type.

<img width="757" alt="image" src="https://github.com/apache/iceberg/assets/1545663/45941f2a-2683-4c43-b279-fa5a7ff56273">

Class renaming/moving around can be a problem although I don't know if practically we should do that. We can add a unit test to assert the class's FQCN didn't change. if renamed/relocated, the parser needs to be updated to track both old and new names.

what's your take on the problem of serializing the `StrucktLike` row?

**Comment by stevenzwu** [comment]
@nastra `ReportMetricsRequest` has the type at API level. 
```
  ReportType reportType();
```

**Comment by nastra** [comment]
@stevenzwu this is only because `ReportMetricsRequest` is a REST request class for a `MetricsReport`. So in the case of this issue here we'd define the enum type at the JSON level in the parser that would handle different task types and delegate to their respective JSON parsers

**Comment by stevenzwu** [comment]
yeah. we are on the same page now. `TaskType` enum can be defined in `FileScanTaskParser`.

regarding the `StructLike` row serialization, I am thinking maybe we should implement a `StructParser` for JSON serialization of `StructLike`. 
```
class StructParser {
    public static String toJson(StructLike struct, Schema schema);
    public static StructLike fromJson(String json, Schema schema);
}
```

**Comment by stevenzwu** [comment]
@nastra @aokolnychyi any feedback on the proposal of adding a `StructParser` JSON serializer?

**Comment by stevenzwu** [comment]
Regarding the `InputFile`, we can serialize the `DataFile` using existing `ContentFileParser`
```
  private StaticDataTask(
      InputFile metadata, Schema tableSchema, Schema projectedSchema, StructLike[] rows) {
    this.tableSchema = tableSchema;
    this.projectedSchema = projectedSchema;
    this.metadataFile =
        DataFiles.builder(PartitionSpec.unpartitioned())
            .withInputFile(metadata)
            .withRecordCount(rows.length)
            .withFormat(FileFormat.METADATA)
            .build();
    this.rows = rows;
  }
```

We can add a new package private constructor
```
StaticDataTask(DataFile metadataFile, Schema tableSchema, Schema projectedSchema, StructLike[] rows)
```

**Comment by aokolnychyi** [comment]
I think it is reasonably to have a field in JSON that would indicate the task type. I'd also avoid any changes in task APIs, we can leverage that enum only in the parser. I doubt using FQCN is a good idea as it would make the implementation specific to Java. 

Can we reuse `SingleValueParser` for serializing structs? I believe it is what we use today to serialize partitions.

**Comment by aokolnychyi** [comment]
Given that the task serialization is part of the spec, shall we raise this discussion during the sync?

**Comment by rdblue** [comment]
I think we should definitely use single-value serialization for the values in the structs when we convert to JSON. I probably wouldn't use objects, though. We could use a list and send values by position instead.

**Comment by stevenzwu** [comment]
> I think we should definitely use single-value serialization for the values in the structs when we convert to JSON. I probably wouldn't use objects, though. We could use a list and send values by position instead.

today `SingleValueParser` serializes a struct to a JSON object using field ID as JSON field name. the `StructLike []rows` would be serialized to a list of JSON object. 

@rdblue are you suggesting a different behavior than the current `SingleValueParser` implementation for struct?
