### ISSUE TITLE
ORC does not use InputFile and OutputFile abstractions

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#96]
ORC doesn't create input and output streams using `InputFile` and `OutputFile` methods. It creates a path from the file location:

```java
path = new Path(file.location());
writer = OrcFile.createWriter(path, options);
```

This breaks the IO abstraction and ORC will not work without Hadoop.

**Comment by rdblue** [comment]
@omalley, is it possible to update ORC so that we can pass in a `SeekableInputStream` for reads and a `PositionOutputStream` for writes?

**Comment by omalley** [comment]
I can't make ORC depend on Avro, Parquet, or Iceberg, so I don't see what you are asking for.

If the ask is to make a version of ORC's Java library that can run without Hadoop, it would be a bit touchy. In particular, our main API uses FileSystem, Configuration, and Path from Hadoop. We've talked about making a no-Hadoop set of shims, but is that what you are asking for?

**Comment by rdblue** [comment]
Yeah, I think a set of no-Hadoop shims is the right thing. Maybe we can move FileIO, InputFile, and OutputFile to a separate library? It would be great to standardize this.

**Comment by pavibhai** [comment]
I agree that a no hadoop shim is the right answer. In the meantime I have raised the following PR that offers FileIO support on ORC with the existing abstraction around Hadoop FS.

https://github.com/apache/iceberg/pull/6293
