### ISSUE TITLE
Fix header links with underscores in title.

### ISSUE THREAD

**Issue by bitsondatadev** [apache/iceberg#9617]
The current link fails for the current site: https://iceberg.apache.org/docs/latest/spark-procedures/#expire-snapshots

The reason my linkchecker missed this was that it still loads the page just not the link. So we'll need to do a pass at these in a later PR.

**Comment by raghits** [comment]
@bitsondatadev  looks like `https://iceberg.apache.org/docs/latest/spark-procedures/#expire_snapshots` is valid URL. Should we use `_` underscore instead of hyphen `-` for these links?

**Comment by bitsondatadev** [comment]
To keep compatibility with the old site, we should support both. The only time this becomes an issue is if you have a saved link (or Google in the short term) but using the `-` will still take you to the page, just not the header.

For now use `_` and if there becomes a real need we'll implement it.

**Comment by raghits** [comment]
Thanks. Sounds good. Also, looks like all procedure names have a `_` separator.  So it would be consistent with that convention.

**Comment by bitsondatadev** [comment]
Thanks for this @raghits, have you noticed any other header not using the underscore?

**Comment by raghits** [comment]
@bitsondatadev here are the references where the hyphen (`expire-snapshots`) is used but those are URLs valid and hence I didn't update it:
https://github.com/apache/iceberg/blob/main/docs/docs/spark-structured-streaming.md
https://github.com/apache/iceberg/blob/main/docs/docs/flink-writes.md
