### ISSUE TITLE
Migrate RESTCatalogServlet to use jakarta.* package for Spring boot 3

### ISSUE THREAD

**Issue by mwullink** [apache/iceberg#9626]
### Feature Request / Improvement

 Spring Boot 3.0 has upgraded to the version that is included in Jakarta EE 10. 
Jakarta EE now uses jakarta packages rather than javax

org.apache.iceberg.rest. RESTCatalogServlet.java still uses the older javax package.

see: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee

### Query engine

None

**Comment by nastra** [comment]
I think that would require updating https://eclipse.dev/jetty/ to a newer version. However, newer Jetty versions require JDK 11+ but Iceberg is on JDK8 due to projects like Hive

**Comment by nastra** [comment]
see also https://github.com/apache/iceberg/pull/9632 where upgrading Jetty failed for that reason
