### ISSUE TITLE
HMS lock timeout

### ISSUE THREAD

**Issue by ShubhamSharmaCSE** [apache/iceberg#9654]
### Apache Iceberg version

None

### Query engine

Spark

### Please describe the bug 🐞

iceberg version: iceberg-spark-runtime-3.3_2.12-1.1.0-amzn-0.jar

Spark job is failing due to timeout to acquire lock on the iceberg table. We see that the lock is present in the hive metastore from one of the early runs and it is not getting cleared up. If we manually, remove the lock, the next run finishes. However, it is not consistent as spark job falls into the same issue post few runs.

Any resolution on this?

**Comment by nastra** [comment]
https://github.com/apache/iceberg/issues/2301 is a related issue to this

**Comment by nastra** [comment]
You might want to check if https://github.com/apache/iceberg/pull/6570 applies in your case. Note that this was shipped with Iceberg 1.3.0
