### ISSUE TITLE
Updating a property map in a iceberg table

### ISSUE THREAD

**Issue by namrathamyske** [apache/iceberg#9659]
### Feature Request / Improvement

Currently PropertiesUpdate.java have methods to `set` and `remove` just a a property key-value pair in iceberg. What if the value of a particular is a map?
Ex:
`property-key : {"a":1, "b":2 }` 
Proposal is a to create a new type of transaction for updating propertyMaps.

```
public interface UpdatePropertyMap<T> extends PendingUpdate<Map<String, String>> {
  UpdatePropertyMap addPropertyMap(Map<String, T> propertyValueMap);
  UpdatePropertyMap removePropertyValueFromMap(Set<String> propertyValues);
  UpdatePropertyMap updatePropertyName(String propertyKey);
}
```

cc: @ryarovoy

@rdblue @nastra 

### Query engine

None

**Comment by amogh-jahagirdar** [comment]
IMO I'd prefer to keep the properties API in it's current simple state. To handle the case where the value is a map, a user could always just serialize the value into  JSON and then store that via the current `PropertiesUpdate` API. I wonder what others think though.

**Comment by namrathamyske** [comment]
@amogh-jahagirdar There might be concurrency issues if we directly serialize it to json string. Ex:

Current state of property-val key:
property-val : { "a1":1 }

Two **concurrent** commit:

commit-1 (a2 is key added to map) :
property-val : { "a1":1, "a2":2 } - succeeds

commit-2 (a3 key is added to map) : 
property-val : { "a1":1, "a3":3 } - fails

commit-2 is retried and overwrites commit-1:
property-val : { "a1":1, "a3":3 }  - succeeds

final property-key value
property-val : { "a1":1 , "a3":3}

Above cases should be handled using conflict resolution and json string must be recreated

**Comment by amogh-jahagirdar** [comment]
Thanks for explaining, if I understand right the desired behavior of this new API is more than just storing map values, you wish to have the ability to reconcile the property values upon retries. 

Since we currently reconcile on the basis of the property keys, is it feasible for you to construct a heirarchy/namespacing in your keys? So in your example the keys would be "key.a1", "key.a2", "key.a3". Then when the update gets reapplied you'll end up with all properties instead of losing "key.a2".

**Comment by namrathamyske** [comment]
@amogh-jahagirdar it would be be simple for 1-2 keys, but can get complex if number of keys increase

**Comment by rdblue** [comment]
I don't think this is a good idea. We want to avoid keeping complex state in table properties and use cases involving complex state in properties are often not a good use of properties. I'm not sure what you're trying to do here, but I don't think that we want to modify Iceberg for it. This would require a spec change, which is a ton of work for little benefit.
