### ISSUE TITLE
Difference between iceberg/docs and https://iceberg.apache.org/docs/latest/

### ISSUE THREAD

**Issue by Waterkin** [apache/iceberg#9663]
### Question

@bitsondatadev  Hello! I am trying moving [my original PR from iceberg-docs](https://github.com/apache/iceberg-docs/pull/307) to this repo. 

However, I've found that the iceberg-docs, iceberg/docs and [the latest website](https://iceberg.apache.org/docs/latest/) are totally different.

Are there any documentation on the doc changes and how to build and contribute to new websites?

**Comment by nastra** [comment]
@Waterkin please take a look at https://github.com/apache/iceberg/blob/main/site/README.md that should contain everything relevant for the new docs website

**Comment by nastra** [comment]
@Waterkin I'll go ahead and close this. Feel free to re-open if necessary

**Comment by Waterkin** [comment]
> @Waterkin I'll go ahead and close this. Feel free to re-open if necessary

Thanks for your reply. I'll check it out.

**Comment by bitsondatadev** [comment]
@Waterkin, Thank you for your efforts here. There are quite a few changes that are taking place at this very moment, but I would absolutely love to work on multiple language support for the site. 

This is [easy to do with the mkdocs framework](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector), but we need to get the docs to a stable point in English before we start to translate and we have a lot planned to reorganize the site (see: #9520 and [mailing list discussion](https://lists.apache.org/thread/dv2x9n6pkykmstkhrw1fx934qjtxnofy)). 

Would you be interested in managing and recruiting help to translate the Iceberg docs in Mandarin later this year when the docs are ready?

**Comment by Waterkin** [comment]
@bitsondatadev, Thank you for recognizing my efforts! Looking forward to contributing to the Mandarin translation of Iceberg docs. Happy to discuss further details when the documentation is ready for translation.

**Comment by bitsondatadev** [comment]
Thank you for you initiative to make Iceberg more accessible to the Chinese-speaking community!
