### ISSUE TITLE
Reordering partition columns in iceberg spark

### ISSUE THREAD

**Issue by nandhakumar23** [apache/iceberg#9698]
### Query engine

Spark

### Question

I noticed that there is documentation on partition evolution via hive - https://iceberg.apache.org/docs/latest/hive/#partition-evolution - to allow reordering partitions in hive via ALTER TABLE default.customers SET PARTITION SPEC (last_name);

Is there something similar in iceberg spark? ie can I do the same as the above via a single spark.sql statement?

I was able to accomplish this via the iceberg API using the following code - 

```
    table.updateSpec()
      .removeField("partitionA")
      .removeField(bucket("partitionB", 2))
      .removeField(day("partitionC"))
      .commit()

    table.updateSpec()
      .addField(day("partitionC"))
      .addField(bucket("partitionB", 2))
      .addField("partitionA")
      .commit()
```

but it looks like `rewriteManifests` does not rewrite the metadata tree with the re-ordered partitions for older data - it only starts applying for new data - is the only way to make this apply for all historical data via the rewriteDataFiles Action?

**Comment by amogh-jahagirdar** [comment]
Checkout https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table for how to re-order columns.

>but it looks like rewriteManifests does not rewrite the metadata tree with the re-ordered partitions for older data - it only starts applying for new data - is the only way to make this apply for all historical data via the rewriteDataFiles Action?

Yes if you want to rewrite past data with the updated partitioning you need to perform a rewriteDataFiles. This is because there are effectively new partition values that need to be computed.
