### ISSUE TITLE
Merge into using the exactly dataset copy the entire data

### ISSUE THREAD

**Issue by guitcastro** [apache/iceberg#9736]
### Apache Iceberg version

1.4.3 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I am testing apache spark, and want to update rows if something has changed in the dataset. I have the following code:

```
      dataset.createOrReplaceTempView("tmp_data")
      spark.sql(
        s"""
          | MERGE INTO warehouse.data
          | USING  tmp_data
          | ON t.id = s.id
          | WHEN MATCHED AND s.last_modified> t.last_modified  THEN UPDATE SET *
          |""".stripMargin)

```

The `tmp_data` is literally the same data of `warehouse.data`, when running this code I would expected no changes in the dataset because it didn't match anything. However my parquet files are being duplicated.

<img width="1178" alt="Captura de Tela 2024-02-16 às 13 54 17" src="https://github.com/apache/iceberg/assets/1149991/509dcc2c-5dfa-4204-9907-de9c82b5c2ad">

**Comment by fengguangyuan** [comment]
>The tmp_data is literally the same data of warehouse.data, when running this code I would expected no changes in the dataset because it didn't match anything. However my parquet files are being duplicated.

The data file names imply that these files may be produced by the same Spark Task instance, but I can't make sure the real cause because of lacking logs.

I suggest you to do these checks:
1. to check these data file status in the historical snapshot.
2. to check if task 19 failed and retried.
3. to confirm if these data files were generated by the same action.

**Comment by rushilshah1** [comment]
I also observed the same issue (expected a no-op but observed another metadata and another duplicate data file produced) when I re-ran my query with a new spark instance. Does the Spark task instance affect the behavior?

**Comment by wilsonpenha** [comment]
I got this same issue using iceberg-1.4.3 with spark-3.5 and as many files as the number of times we call that merge command

mytest_data
id, name     , last_modified
1, One, 20240101
2, Two, 20240101
3, Three, 20240101

tmp_view
id, name     , last_modified
1, One, 20240101
2, Two, 20240101
3, Three, 20240101

spark-sql> MERGE INTO mytest_data t
USING  tmp_view s
ON t.id = s.id
WHEN MATCHED AND s.last_modified> t.last_modified  THEN UPDATE SET *

It creates another parquet file each time I run that command with exactly the same data and also another snapshot   

Please advised whether I should use older version or expect it to be fix soon.

**Comment by guitcastro** [comment]
@fengguangyuan  Sorry, the code I posted the wrong code. If I added the following clause then it will rewrite the entire data:

`WHEN NOT MATCHED THEN INSERT *`
