### ISSUE TITLE
branch schema affected by main table schema

### ISSUE THREAD

**Issue by namrathamyske** [apache/iceberg#9737]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

 regarding this PR: https://github.com/apache/iceberg/pull/9131 - the change reads as: Schema for a branch should return table schema
Shouldn't the Schema of a branch be the same as when the branch was created - as opposed to the above change - ie., to move it to a future state of schema change on the table? isn't the concept of branching to create a baseline based on the state of data and metadata of the table - as to - when it was branched? can you pl. help me understand the rationale behind this change?

Please consider this example:
```
-- create a table with a single column and insert a value
spark-sql (default)> create table t (s string);
spark-sql (default)> insert into t values ('foo');
-- create a branch, the schema is the same as the original table
spark-sql (default)> alter table t create branch b1;
```

Describe and Query the table & branch:
```
spark-sql (default)> describe default.t;
s                       string
spark-sql (default)> select * from default.t;
s
foo

spark-sql (default)> describe default.t.branch_b1;
s                       string
spark-sql (default)> select * from default.t.branch_b1;
s
foo
```

Alter the table - using the below statement to diverge the definition of the table:

```
spark-sql (default)> alter table t add column i int;
spark-sql (default)> alter table t del column s;

spark-sql (default)> insert into t values (111);
```

Behavior before the above PR: [Please NOTE that the changes in the main branch - DID NOT IMPACT the data and metadata on the branch - which lookslike is the desirable behavior for any branching concept]

```
spark-sql (default)> describe default.t;
i                       int
spark-sql (default)> select * from default.t;
i
111

spark-sql (default)> describe default.t.branch_b1;
s                       string
spark-sql (default)> select * from default.t.branch_b1;
s
foo
```

Behavior after the above PR: [Please NOTE that a schema change in the main branch - IMPACTED the data and metadata available on the branch - this feels like an undesirable behavior;]

```
spark-sql (default)> describe default.t;
i                       int
spark-sql (default)> select * from default.t;
i
111

spark-sql (default)> describe default.t.branch_b1;
i                       int
spark-sql (default)> select * from default.t.branch_b1;
i
--no-data--
```

Unit test to replicate the issue:

```
@Test
  public void testSchemaChange() throws Exception {
    Assume.assumeFalse("Avro does not support metadata delete", fileFormat.equals("avro"));
    createAndInitUnpartitionedTable();

    sql("INSERT INTO TABLE %s VALUES (1, 'hr'), (2, 'hardware'), (null, 'hr')", tableName);
    createBranchIfNeeded();

    String sql = String.format("SELECT * FROM %s ORDER BY id", selectTarget());
    spark.sql(sql).show();
    /**
     * +----+--------+
     * |  id|     dep|
     * +----+--------+
     * |NULL|      hr|
     * |   1|      hr|
     * |   2|hardware|
     * +----+--------+
     */
    // Metadata Delete
    Table table = Spark3Util.loadIcebergTable(spark, tableName);
    table.refresh();
    table.updateSchema().deleteColumn("dep").commit();
    sql = String.format("SELECT * FROM %s ORDER BY id", selectTarget());
    spark.sql(sql).show();
    /**
     * Data loss in branch, impacted as we consume schema from table schema
     * +----+
     * |  id|
     * +----+
     * |NULL|
     * |   1|
     * |   2|
     * +----+
     */
    sql = String.format("SELECT * FROM %s ORDER BY id", tableName);
    spark.sql(sql).show();
    /**
     * +----+
     * |  id|
     * +----+
     * |NULL|
     * |   1|
     * |   2|
     * +----+
     */
  }
  ```
@SreeramGarlapati @jackieo168

cc: @rdblue @nastra

**Comment by namrathamyske** [comment]
When fetching data the schema which was associated with branch should be issued not table. But for operations like cherry pick from branch to main, it should resolve conflicts between main and branch and **possibly consider main branch table  schema** and re-concile. Let me know your thoughts @rdblue @nastra

**Comment by nastra** [comment]
@namrathamyske I've opened https://github.com/apache/iceberg/pull/10055 to clarify which schema is being used when.

**Comment by danielcweeks** [comment]
@namrathamyske you can force reading with the snapshot id on a branch by using the time travel statement.

```
select * from default.t.branch_b1 for timestamp as of now();
```

This is use the current snapshot and is equivalent to reading from the head of the branch with the snapshot schema.  However, the branches write schema will track with the table schema.

**Comment by nastra** [comment]
> @namrathamyske you can force reading with the snapshot id on a branch by using the time travel statement.
> 
> ```
> select * from default.t.branch_b1 for timestamp as of now();
> ```
> 
> This is use the current snapshot and is equivalent to reading from the head of the branch with the snapshot schema. However, the branches write schema will track with the table schema.

I just checked this workaround and it actually returns the latest snapshot id of the `main` branch rather than the latest snapshot id of `b1` because there's no logic in https://github.com/apache/iceberg/blob/2a39af894f4f00aa37922ef765cc2583517fa1d1/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java#L224-L225 that takes the branch into account. I've opened https://github.com/apache/iceberg/issues/10058 to address that

**Comment by namrathamyske** [comment]
Thanks @danielcweeks @nastra !

**Comment by danielcweeks** [comment]
@namrathamyske it was pointed out to me that workaround may not be working correctly for branches, which is something we might need to address.

**Comment by namrathamyske** [comment]
Looks like we are disabling the workaround from https://github.com/apache/iceberg/pull/10059. 
More future fix is where we track `schemaId` from snapshot in `SnapshotRef` object. For `tagBuilder` we may not pass `schema-id`, but for `branchBuilder` we can pass `schemaId`. 

But there is one more issue with above solution:
```
snapshot1 created at t1 points to schema1
schema progresses from schema1 - schema2, but snapshot1 still points to schema1
branch1 should be from schema1 or schema2 ?
```
Do we want to created a no-op snapshot when a branch is created on **current snapshot**? 
The no-op now points to latest schema. branch now can we created on top of this to point to latest schema

Also suggested in https://github.com/apache/iceberg/issues/7075#issuecomment-1464994270

**Comment by nastra** [comment]
> Looks like we are disabling the workaround from #10059. 

The reason for #10059 is because we don't support time travel on branches themselves, because there's no history tracking on branches available.

The workaround that you can use is documented in https://github.com/apache/iceberg/pull/10055, where you can fetch the latest snapshot id of the given branch and then use that snapshot id in the `VERSION AS OF` stmt: `SELECT * FROM db.table VERSION AS OF 8109744798576441359`
