### ISSUE TITLE
Is it possible to add a set of existing partitioned parquet files to the Iceberg table via the Java Standalone API

### ISSUE THREAD

**Issue by calvinlfer** [apache/iceberg#9763]
### Query engine

I am using [Parquet4S](https://github.com/mjakubowski84/parquet4s) + Hadoop-AWS
Parquet4S is a wrapper on the Apache Parquet library and allows reading/writing of Parquet data to object storage infrastructure like AWS S3. The data that Parquet4S reads/writes is accessible to Spark/Flink/etc.

### Question

I am using Parquet4S to write a directory of partitioned parquet files to S3. Is it possible to register these files with Apache Iceberg through the standalone Java API so that Iceberg can pick up the new parquet data? Are there any Iceberg Java APIs to help with this process?

**Comment by manuzhang** [comment]
You may want to check out [AddFilesProcedure#importFileTable](https://github.com/apache/iceberg/blob/main/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java#L193), which uses public Java API to import parquets to Iceberg table.
