### ISSUE TITLE
Writing Equality Deletes using Iceberg Java API

### ISSUE THREAD

**Issue by robinsinghstudios** [apache/iceberg#9808]
### Query engine

Java API

### Question

I am trying to implement an Iceberg writer based completely on Java API. I am able to use the PartitionedFanoutWriter to write to the specified partitions successfully. 

However, now I need to implement deletes, and there lies the issue. Equality or Position deletes seem to be the best solution for my use case as I don't want to rewrite the existing files again. 

As I looked through the classes and tried to create my own PartitionedFanoutWriter for deletes, I noticed that the constructor function is not public. Any reasons for this and is there an alternate solution to this problem? Any help would be appreciated. Thanks.

```
// org.apache.iceberg.io.BaseTaskWriter

protected class RollingEqDeleteWriter extends BaseTaskWriter<T>.BaseRollingWriter<EqualityDeleteWriter<T>> {

        // This is not public unlike RollingFileWriter -------------------------------

        RollingEqDeleteWriter(StructLike partitionKey) {
            super(partitionKey, null);
        }

        EqualityDeleteWriter<T> newWriter(EncryptedOutputFile file, StructLike partitionKey) {
            return BaseTaskWriter.this.appenderFactory.newEqDeleteWriter(file, BaseTaskWriter.this.format, partitionKey);
        }

        long length(EqualityDeleteWriter<T> writer) {
            return writer.length();
        }

        void write(EqualityDeleteWriter<T> writer, T record) {
            writer.write(record);
        }

        void complete(EqualityDeleteWriter<T> closedWriter) {
            BaseTaskWriter.this.completedDeleteFiles.add(closedWriter.toDeleteFile());
        }
    }
```

**Comment by ismailsimsek** [comment]
@robinsinghstudios i have done [similar implementation here ](https://github.com/memiiso/debezium-server-iceberg/tree/master/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/tableoperator), feel free to check, hope it helps
