### ISSUE TITLE
Broken link at Rest Catalog Spec

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg#9829]
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

The following link is broken: https://github.com/apache/iceberg/blob/bd9c615d5d2fedb1a9fda6eb018017d0cc32f04e/open-api/rest-catalog-open-api.yaml#L102-L102

It should be something like, https://iceberg.apache.org/docs/latest/configuration/#catalog-properties.

**Comment by nastra** [comment]
thanks for spotting @flyrain, this was just recently fixed by https://github.com/apache/iceberg/pull/9825
