### ISSUE TITLE
I'm curious about the `hive.metastore.disallow.incompatible.col.type.changes` settings.

### ISSUE THREAD

**Issue by wngus606** [apache/iceberg#9897]
### Question

Hello.
I'm leaving an inquiry because I want to understand the "hive.metastore.disallow.incompatible.col.type.changes" setting in detail.
When I read the [document](https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.metastore.disallow.incompatible.col.type.changes), it was found to be related to the possibility of converting the data type of the column and compatibility. However, if you use `ALTER TABLE iceberg.iceberg_db.iceberg_table DROP COLUMN 'name'`, the same error occurs. If you delete a column here, the data related to that column will be removed from the table, which I think is separate from the compatibility issue of data type, and I wonder what it has to do with this setting.
can I check the code related to this?

**Comment by pvary** [comment]
I think this question should be asked from the Hive folks.

**Comment by nastra** [comment]
I agree with @pvary, this seems like a question that should be asked in the Hive community at https://github.com/apache/hive (or the Hive JIRA)

**Comment by deniskuzZ** [comment]
@wngus606, what version of HMS are you using, 2.3? 2.x and 3.x are EOL, v4.0 handles drop column properly.
