### ISSUE TITLE
Manage root of URL in manifests in one place per entire table.

### ISSUE THREAD

**Issue by PigNatovsky** [apache/iceberg#9936]
### Feature Request / Improvement

Currently manifests files contains full URL to every manifest/data file in the table. If we need to change location (for example Allxuio cache migration, or S3 migration - but both without need of copying files) it's really heavy and risky operation (without copying entire table with new location).

So my proposal is to split location in two parts:

1. Main manifest list file (one per snapshot) will contain scheme, subdomain, top-level domain and second-level domain part of URL (for example alluxio://some-endpoint:port/)
2. Every other files with contain rest of URL (subdirectories, or path).

With this architecture migration without copying is as easy, as changing main URL part in one file. 
Is something like that acceptable? 
It will be nice if someone would point cons of this approach, from my perspective it's not so bad idea (and huge time and resource saving in case of migration).

### Query engine

Every query engine.

**Comment by RussellSpitzer** [comment]
We have had multiple requests for this or something like it , we have several design docs floating around for relative paths (basically this.) Since this will require a spec change I recommend looking for those past docs and issues and writing up a new design or bring up an old proposal for discussion

**Comment by PigNatovsky** [comment]
Thank You a lot!
Will try to find other proposals, it's worth to work on this.
