### ISSUE TITLE
Open-API: How about adding table change detection in Iceberg Catalog

### ISSUE THREAD

**Issue by mingnuj** [apache/iceberg#9942]
### Feature Request / Improvement

When using the Iceberg Rest-API Catalog, in order to detect changes in the table, it is necessary to retrieve all table metadata using loadTable and then check the current-snapshot-id. If the table doesn't change frequently, it results in fetching unnecessary data repeatedly. 

How about implement a feature solely for confirming that the previous table remains unchanged?
For example, create a operation that takes table name and current-snapshot-id, compares them, and returns true or false accordingly.

### Query engine

None

**Comment by nastra** [comment]
There's an option that you can use to only fetch the latest snapshot via `snapshot-loading-mode=refs` (defaults to `all`) when the table is loaded instead of loading all snapshots.

**Comment by mingnuj** [comment]
> There's an option that you can use to only fetch the latest snapshot via `snapshot-loading-mode=refs` (defaults to `all`) when the table is loaded instead of loading all snapshots.

Thank you for response! I'll try it.
