### ISSUE TITLE
Is there any way to define Iceberg catalog and share it between DataStream API and Table/SQL API?

### ISSUE THREAD

**Issue by okayhooni** [apache/iceberg#9954]
### Query engine

Flink

### Question

I tried to implement Flink application(source: Iceberg, sink: Iceberg). and use both Flink's datastream API and Table API for our convention for structure of Flink apps.

For this purpose, I want to define Iceberg catalog and share it between DataStream API and Table/SQL API.

But, I didn't find the way to share catalog among them. (I couldn't find the way except defining same catalog twice for each Flink API)

Is there any way to define Iceberg catalog and share it between DataStream API and Table/SQL API?

**Comment by dyzcs** [comment]
```
//1. create TableLoader configuration
Configuration conf = new Configuration();

//2. create catalog and set table store path
Catalog catalog = new HiveCatalog(conf,"path");

//3. load table
TableIdentifier name = TableIdentifier.of("", "");
Table table = catalog.loadTable(name);
```
According to my understanding, the above code can solve your problem, and this issue can be closed.

**Comment by okayhooni** [comment]
@dyzcs Thank you for kind reply! I used Glue catalog and tried several approaches similar to your code example.. But it looks Catalog classes between Flink and Iceberg are not compatible with different interface.

@pvary Thank you for sharing experience! (I am newbie to Flink.. but I'll try to investigate it after being more accustomed with Flink!)

**Comment by dyzcs** [comment]
@okayhooni I haven't used AWS Glue before, but as you said, this should be due to interface incompatibility(issue). The above code is available in Spark and Flink, and using Hive and HDFS catalog is acceptable.

**Comment by okayhooni** [comment]
@dyzcs Thank you for additional kind explanation..!

If catalog can be shared between DataStream API and Table API as your code, How can I use that catalog on SQL interface from `StreamTableEnvironment` ?

`registerCatalog` method of `TableEnvironment` has catalog parameter typed as `org.apache.flink.table.catalog`..!

But the catalog loaded from `CatalogLoader.custom()` is typed as `org.apache.iceberg.catalog.Catalog`..! so it cannot be the argument of `registerCatalog` method of `TableEnvironment`..!

```
val glueCatalogLoader = CatalogLoader.custom(
      "iceberg_catalog",
      Map(
        "type" -> "iceberg",
        "warehouse" -> "s3://thank-you-dyzcx",
        "catalog-impl" -> "org.apache.iceberg.aws.glue.GlueCatalog",
        "io-impl" -> "org.apache.iceberg.aws.s3.S3FileIO"
      ).asJava,
      new Configuration,
      "org.apache.iceberg.aws.glue.GlueCatalog"
    )

val glueCatalog = glueCatalogLoader.loadCatalog // it is typed as `org.apache.iceberg.catalog.Catalog`

// tableEnv.registerCatalog() ~ NOT WORKING WITH `org.apache.iceberg.catalog.Catalog`, it needs `org.apache.flink.table.catalog`
```

**Comment by dat-vikash** [comment]
hitting this as well. Would be great to have a way to register the catalog to the table env!
