### ISSUE TITLE
Spark can not delete table metadata and data when drop table

### ISSUE THREAD

**Issue by tomfans** [apache/iceberg#9990]
spark 3.3.2 , iceberg 1.4 , metadata managed by HMS, 

the table which created by spark/iceberg, and metadata managed by HMS, when drop table with purge, the data/metadata directories are still exist.

if metadata managed by HDFS, it works

how to handle this ?

**Comment by tomfans** [comment]
more information:  metadata managed by HMS, not HDFS.  it works when metadata managed by HDFS

**Comment by manuzhang** [comment]
Which catalogs do you use in those two cases? Can you share the configs?

**Comment by tomfans** [comment]
HMS, if i use HMS catalog , i can't delete table directories when i drop table, even i drop table with purge.  the software version is: spark 3.3.2, hive 2.3.9, iceberg jar is:1.4.0.

the iceberg config as below:
#############iceberg####################
spark.sql.catalog.iceberg_prod = org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg_prod.type = hive
spark.sql.catalog.iceberg_prod.uri = thrift://hcshadoop04.dev.xxx.cn:9083,thrift://hcshadoop05.dev.xxx.cn:9083

if i use HDFS as the catalog, it works fine. the config as below:
spark.sql.catalog.iceberg_prod = org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg_prod.type = hadoop
spark.sql.catalog.iceberg_prod.warehouse = hdfs://nameservice/tmp/spark-iceberg

**Comment by tomfans** [comment]
and i have checked other comments on this kind issue , why can't delete table directories when drop table , it's because the table is a external table when created by spark, and giving some tricks like alter table from external table to managed table ,but it still doesn'work.

**Comment by manuzhang** [comment]
> alter table from external table to managed table 

This only works with Hive CLI.

**Comment by tomfans** [comment]
i just want to confirm  while i use  spark with iceberg catalog "org.apache.iceberg.spark.SparkCatalog" and HMS,  if it's normal or not  when it can't delete table directories after table dropped?  

if this is normal, there are a lot table directores will keeped in data warehouse '/user/hive/warehouse', will have many many small files and gabage.

**Comment by wanghualei** [comment]
I meet this problem also.  when user "drop table  purge", it delete files in data and meta directory,but ,the table driectory still exits, in normal sence , the directory should be delete also.

**Comment by manuzhang** [comment]
@tomfans If you mean empty table directories are left over, I can confirm that's behavior for `HiveCatalog`. It removes the table record from metastore, and deletes all referenced metadata and data. The rationale I can see is Iceberg cannot assume all files under the directory belong to the table.

As for the `HadoopCatalog` deleting directory is the only solution since the directory is the catalog itself.

**Comment by tomfans** [comment]
> deleting

yes, it's HiveCatalog, hadoopcatalog works fine.   you mean this is normal operation for HiveCatalog to keep these data/metadata/table directories when drop table ?

if so , when we drop tables , it will keep a lot of table directories , how to handle this kind problem ?

**Comment by manuzhang** [comment]
You may create external auto-purge process if you are sure these directories are safe to delete.

**Comment by wanghualei** [comment]
@manuzhang  

> @tomfans If you mean empty table directories are left over, I can confirm that's behavior for `HiveCatalog`. It removes the table record from metastore, and deletes all referenced metadata and data. The rationale I can see is Iceberg cannot assume all files under the directory belong to the table.
> 
> As for the `HadoopCatalog` deleting directory is the only solution since the directory is the catalog itself.

why not ?  assume all file  under the directory belong to the table ,it is normal sence.

**Comment by wanghualei** [comment]
Is it related to object storage? There is no directory relationship.

**Comment by manuzhang** [comment]
For example, I can create a table B with location under that of table A. I don't want to delete table B when dropping table A.

**Comment by wanghualei** [comment]
> For example, I can create a table B with location under that of table A. I don't want to delete table B when dropping table A.

Generally speaking, this situation should not occur. Because it undermines table level integrity, it can be constrained by encoding specifications. People are more accustomed to having one table and one directory.

**Comment by wanghualei** [comment]
> For example, I can create a table B with location under that of table A. I don't want to delete table B when dropping table A.

If we reason like this, does HadoopCatalog also have cross use of tables and directories.

**Comment by manuzhang** [comment]
> Because it undermines table level integrity
Iceberg manages table integrity. What can be improved is to offer options to delete directory when users know it's safe to do so.
HadoopCatalog is not recommended to use as discussed in [this mail thread](https://www.mail-archive.com/dev@iceberg.apache.org/msg04644.html)

**Comment by wanghualei** [comment]
> > Because it undermines table level integrity
> 
> Iceberg manages table integrity. What can be improved is to offer options to delete directory when users know it's safe to do so. HadoopCatalog is not recommended to use as discussed in [this mail thread](https://www.mail-archive.com/dev@iceberg.apache.org/msg04644.html)

We strongly recommend adding relevant options to clear the table directory. Thank you very much.

**Comment by wForget** [comment]
I also encountered the same problem when using SparkSessionCatalog to delete a non-iceberg hive table.

@manuzhang Iceberg HiveCatalog allows deletion of non-iceberg tables, is this expected behavior?

**Comment by tomfans** [comment]
i don't think this is related to session or non-iceberg table, if it's HMS as catalog, spark can't delete the data files and directories of the table. if HDFS as catalog, no problem.

**Comment by wForget** [comment]
> i don't think this is related to session or non-iceberg table, if it's HMS as catalog, spark can't delete the data files and directories of the table. if HDFS as catalog, no problem.

If Iceberg HiveCatalog only handles iceberg tables, non-iceberg tables will fall back to sparkSessionCatalog. Is that more reasonable?

https://github.com/apache/iceberg/blob/96793bf621524f57e99cd19d410cde734bf588eb/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java#L281

**Comment by zzeekk** [comment]
how can i reference parameters in an ArgoCD template?

**Comment by zhiai007** [comment]
the same issue as me on HiveCatalog

**Comment by zhiai007** [comment]
@tomfans Hope you're doing well, I was wondering if any solution or workaround has been found for this issue?
